### ISSUE TITLE
weekly email report

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#1022]
from @xunker via [Twitter](https://twitter.com/xunker/status/344206451956387841):

> could we get a monthly email letting us know what our tips are? I accidentally tipped someone 4 months longer than I intended.
##

**Comment by whit537** [comment]
Seeing this from Venmo:

> Why am I getting this email when I had no Venmo activity? Can I unsubscribe or opt out of these emails? Venmo is required by federal financial regulations to send this notice to you on a regular basis (see [here](https://www.ecfr.gov/cgi-bin/text-idx?SID=487b52d05de7f8ee4ac917903a65694b&mc=true&node=se12.2.205_19&rgn=div8)), so unfortunately you cannot unsubscribe. We apologize for the inconvenience.

**Comment by mattbk** [comment]
Reticketed from #4564:
> Could be handy to have an email sent to account owner when another user supports/backs one of their projects. Also maybe include a summary of total no of users supporting the project with received information, like estimated payment totals as well prehaps.

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
