### ISSUE TITLE
Idea: Matching Gittip

### ISSUE THREAD

**Issue by aviflombaum** [gratipay/gratipay.com#1033]
It'd be cool if I could specify that I want to match all gittips. As in, say I have a 'budget' set in gittip to $3,584. This last gittip, I could have matched everyone's donation $1 for $1. I think this could let big charities / non-profits get involved without having to choose who to gittip or what to support, but rather, let the community continue to decide that. That would also incentivize people to give, you would know that your $1 is doubled by some charity or patron. A budgeting algorithm could distribute the matches evenly across all gittips so that if the budget is not enough to cover a 1:1 match, it reduces evenly. Then we could solicit large sum commitments from big organizations without them having to administer to account weekly.
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
