### ISSUE TITLE
connect Flattr account

### ISSUE THREAD

**Issue by thiloplanz** [gratipay/gratipay.com#104]
_<b>was:</b> ability to add alternative donation information to your gittip profile page_

It seems that all of the various micro-donation system completely ignore the others' existence, almost as if they were competitors instead of collaborators towards the same common goal.

Gittip should buck that trend and allow its users to promote their presence on the other networks as well.

There should be fields on your gittip profile information to specify information regarding your participation on Flattr, TipTheWeb, Kachingle, PayPal, Bitcoin et al.

Related issues:
- Displaying a Bitcoin donation address is also a good first step for issue #14.
- Recommending accepted alternative ways to donate should also be an option for people who opt-out of gittip, see #55.
##

**Comment by nobodxbodon** [comment]
> It seems that all of the various micro-donation system completely ignore the others' existence, almost as if they were competitors instead of collaborators towards the same common goal.

> Gittip should buck that trend and allow its users to promote their presence on the other networks as well.

Though agreeing with this, https://github.com/gratipay/gratipay.com/issues/4174#issuecomment-260133190 sounds convincing. Plus as suggested [above](https://github.com/gratipay/gratipay.com/issues/104#issuecomment-6776747), the workaround is to put in textarea.
