### ISSUE TITLE
The connect a bank account page needs a second address field.

### ISSUE THREAD

**Issue by rikai** [gratipay/gratipay.com#1046]
Currently the [credit card](https://www.gittip.com/credit-card.html) page has ADDRESS 1 and ADDRESS 2 fields, the [bank account](https://www.gittip.com/bank-account.html) page lacks equivalent fields, only giving a field for "Street Address".

The credit card page is the one following proper conventions.  The second address field is usually used for things such as unit numbers, which is definitely address information that would be needed, i would think. :)

**Comment by Changaco** [comment]
Done in #3250.
