### ISSUE TITLE
Refine a measure of stability/ volatility as overall funding levels grow

### ISSUE THREAD

**Issue by ehmatthes** [gratipay/gratipay.com#1050]
There was some interesting conversation about stability and volatility of a recipient's funding level during the discussion of [issue #1041](https://github.com/gittip/www.gittip.com/pull/1041), "add $100 as a tip option". Briefly, the consensus was to up the maximum tip to $100 for the sake of supporting overall growth in the platform. These large tips create volatility in an individual's funding level, but we accept that volatility in order to support rapid growth.

Two core goals of gittip are to support people at a living wage level, and to give people stability in funding. As people start to reach a living wage level, we may see some people choose to leave their jobs based on gittip funding. These people need accurate, objective measures of the stability of their funding.

It seems we could make a formula that condenses stability down to a single number, but I'm wary of telling people their funding is stable when we can't really promise that. This seems especially important as people make significant life decisions around their level of funding. It seems the best approach might be to give accurate statistics related to stability/ volatility, and share the patterns that we see about funding overall.

The key metrics regarding stability of funding seem to be:
- tip size distribution
- how long someone has been tipping you

Here's an interesting long-term thought, related to stability. We allow people to set funding targets. If we could measure stability, could we allow people to set stability targets as well? For example, if you get $1000/ week through ten $100 tips, that is not as stable as forty $25/week tips. Could people set their own maximum tip level, or maximum number of tips at any given level?

I obviously value stability, but I can accept volatility as long as the recipient has an accurate sense of the volatility of their current funding level.

These concerns may seem far off, but we are one order of magnitude away from the top recipients receiving something close to living wages.
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
