### ISSUE TITLE
Develop and publish Fraud Prevention Policy

### ISSUE THREAD

**Issue by ceboudreaux** [gratipay/gratipay.com#1088]
Define behaviors which constitute fraud on Gittip.

Create a statement listing the measures taken to prevent fraudulent behaviors.  List the steps taken when fraud is suspected.  List the actions that will occur when fraud is detected/verified.

Publish this statement (or a link to it) on the Fraud page.

Consider linking to it on Privacy page and Terms page.

Keep a version history of policy revisions and publicly display the "last updated" date.
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
