### ISSUE TITLE
Allow a statement video

### ISSUE THREAD

**Issue by balupton** [gratipay/gratipay.com#1099]
Referenced from: https://github.com/gittip/www.gittip.com/issues/1096#issuecomment-20252941

> Speaking of activists, and project roadmaps. It would be cool if users can post a video on their profile to showcase what their all about. The word description is great for explaining, but not showing.

Patreon and Youtube both make use of this. It really does add something to the experience.
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
