### ISSUE TITLE
Launchpad integration

### ISSUE THREAD

**Issue by kmf** [gratipay/gratipay.com#1106]
I would like to see Launchpad integration, it would be great for devs to receive tips, and it would be great for others to discover Gittip.

_Note by Changaco:_ Launchpad apparently supports OAuth: https://help.launchpad.net/API/SigningRequests
##

**Comment by nobodxbodon** [comment]
Re-ticketed to https://github.com/gratipay/inside.gratipay.com/issues/983 for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.
