### ISSUE TITLE
make it easy to leave feedback from the site

### ISSUE THREAD

**Issue by gwenbell** [gratipay/gratipay.com#1119]
**was: Feedback Horn, Priority List**

I love (and clicked) the feedback horn powered by uservoice on GitLab. Good way for devs and non-devs alike to contribute feedback on Gittip without having to submit an issue/bug report. 

Also like the voting system, which helps us see what user priorities are (may be different than the dev team's priorities).

![feedback-horn](https://f.cloud.github.com/assets/2355172/756720/8ae24b00-e63b-11e2-82e7-22da94bab82e.png)
![gitlab-feedback-thread](https://f.cloud.github.com/assets/2355172/756723/06004e40-e63c-11e2-8bcc-b0f3cbb90eb8.png)
##

**Comment by nobodxbodon** [comment]
As we have github ribbon on website, it's one click away from creating issue here. Closing until we realize we need broader user feedback.
