### ISSUE TITLE
Email me whenever you bill my credit card

### ISSUE THREAD

**Issue by mw44118** [gratipay/gratipay.com#1124]
I just got charged $10, which is fine, but you really need to send me a receipt via email when this happens.  And for extra credit, warn me the day before in a separate email.

This is why I think you need to do this:

1.  Everybody else sends email receipts.  That's really the main reason.  It's a convention now that if you charge somebody's card, especially in an offline background process, you send an email receipt.

2.  It is way easier for me to forward an email to a bookkeeper than it is to log in to a site, save an HTML page and then forward that.  I consider gittip donations a marketing-related business expense.

2.   If you warn me first, it might reduce chargebacks / fraud complaints / failed charges.  You can put a link in the warning email back to my account so that I can immediately cancel my giving.

Keep up the good work!

**Comment by whit537** [comment]
+1 https://gratipay.freshdesk.com/helpdesk/tickets/1733
