### ISSUE TITLE
deploy branches to heroku automatically

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#1133]
We need this to turbo-charge our development workflow (@corytheboyd and @warreng called it; props). The idea is that any branch in GitHub gets its own public deployment, with its own database with fake data. This should be a subcommand of `gittip`.
##

**Comment by whit537** [comment]
+1 from @techtonik at https://github.com/gratipay/gratipay.com/pull/3718#issuecomment-135723108.

> Should we have a dev.gratipay.com with the WIP site version that is automatically pushed on commits from master?

**Comment by whit537** [comment]
> For each new GitHub pull request (“PR”), Heroku will spin up a disposable “Review App” with a unique URL for the development team to review and test. Now, instead of guessing what the new code might do, reviewers — including designers, testers, and PMs — can receive a link and actually try it out in a browser, before the code reaches staging or production environments.

http://blog.heroku.com/archives/2015/9/3/heroku_flow_pipelines_review_apps_and_github_sync#review-apps-in-the-flow

**Comment by whit537** [comment]
> Today, we are happy to announce the graduation of [Heroku Review apps](https://devcenter.heroku.com/articles/github-integration-review-apps) from an exceptionally popular beta to being generally available to all Heroku users.
>
Review apps are the instant, disposable Heroku app environments that can spin up automatically with each GitHub pull request. They allow developers and their teams to automatically build and test any pull request, updated at every push, at a temporary, shareable URL. When the pull request is closed or merged, the Review app is deleted. GitHub users are notified of all this, right in the pull request web interface.

https://blog.heroku.com/archives/2016/4/18/heroku_review_apps_GA?

**Comment by nobodxbodon** [comment]
The page in the last comment seems to be pulled back. I guess the service is still beta. Will it be free for our purpose?

**Comment by whit537** [comment]
Looks like they have a broken redirect on the blog post. Here's the correct link: https://blog.heroku.com/heroku-review-apps-ga.

**Comment by whit537** [comment]
I've updated the link in my comment.

**Comment by nobodxbodon** [comment]
As the issue isn't user-oriented, reticket to inside.
