### ISSUE TITLE
continuous deployment

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#1138]
When tests pass on a certain branch.

Suggested by @simonsapin on [Twitter](https://twitter.com/SimonSapin/status/356053477601976322).

We'd need to review who has what permissions on the repo.
##

**Comment by nobodxbodon** [comment]
As the issue isn't user-oriented, reticket to inside.

**Comment by whit537** [comment]
> user-oriented

Why is that the criterion, rather than the scope of the issue (gratipay.com vs. Gratipay as an organization, or cross-repo product questions)?
