### ISSUE TITLE
Reach out to companies

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#1149]
This ticket is for @cakey and myself and anyone else potentially interested in recruiting new companies to use Gittip as a way to invest in open-source and market to developers.

A decade ago, under the influence of a business mentor of mine, I made a list of all the school districts in Western Pennsylvania and methodically cold-called each one to offer our web design services. We got one hit, and I still do work for that company to this day and have in fact become friends with my contact there.

We should do the same with companies.
- [ ] develop a straightforward pitch at `/about/companies/`, see #894
- [ ] compile a list of companies to reach out to
- [ ] methodically contact each of them
##

**Comment by whit537** [comment]
Great list of companies to reach out to is shaping up at https://github.com/ossfriendly/open-source-sponsors.

**Comment by mattbk** [comment]
Would love to see Gratipay itself be on that list once it's more solvent.

**Comment by whit537** [comment]
Closing in favor of https://github.com/gratipay/inside.gratipay.com/issues/1170 which is on the (more appropriate) Inside Gratipay repo.
