### ISSUE TITLE
Offer an open source perks program

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#1153]
The idea here is for companies to give their developers a mini-budget for spending on open source projects. We want to be under "Open Source Allowance" [here](https://github.com/basecamp/handbook/blob/master/benefits-and-perks.md#perks)—"$100/mo to spend on whatever open source projects you would like."

-------------------

### Was: offer khan-style splitting for employees of a company

@andyweissman suggested this a while back and it just came up on [HN](https://news.ycombinator.com/item?id=6055168) now that Khan Academy is doing this. Let employees of a company vote on how to split money.
##

**Comment by whit537** [comment]
An alternative to this would be to partner with foundations like the Python Software Foundation, Django, jQuery, etc., and let them handle further distribution (off-site or on Gratipay).

**Comment by techtonik** [comment]
And it will also save 50% on taxes that are paid when people receive cash first and then pay.

**Comment by whit537** [comment]
+1 from Yahoo:

> We seek to celebrate the donors in a branded way (either we grant money to our employees who select projects, or we solicit ideas from them and grant for them, something like that). So we'd want to co-brand and say something that acknowledges both [] and Yahoo for his sponsorship of this very important Node.JS module.

**Comment by whit537** [comment]
+3 from Salesforce during gratipay/inside.gratipay.com#948.

**Comment by mattbk** [comment]
? https://github.com/gratipay/gratipay.com/issues/2571

**Comment by whit537** [comment]
@mattbk Pretty sure that's a separate idea. You see it lining up with this?

**Comment by mattbk** [comment]
I wasn't sure whether parts of the same interface could work for both.

#2571:
- Company A deposits money and makes it available for payday
- Member 1 takes some of the money
- Member 2 takes some of the money

Khan-style:
- Company A deposits money for Khan-style
- Member 1 uses some of the money for Company B
- Member 2 uses come of the money for Company C

Both depend on adding members to a project and self-funding, and then the difference is whether that member can take and/or give.

**Comment by techtonik** [comment]
This is the interface that could be possible with the API we could provide:
```
Thanks to donors:
anonymous
frank [Yahoo]
elija [Westwood]
membrr1
```
This is the project page. People looking at this page can see where people were working and would be able to choose company that allows them to do monetary contributions to that project that they like.

**Comment by mattbk** [comment]
>This assumes that Khan-style uses projects as the main entity, or whether you would make a different entity. I'd argue for everything to be a project, and those who don't want to receive can turn off receiving.

Regarding #4246, companies would be Projects, not ~users, right?

**Comment by whit537** [comment]
> Benefits are far more reliable than perks, and cover more basic needs. Perks are like bonuses that companies offer to make their offer seem better than the competition, and can give a richer picture of the company culture, and what they value for their employees.

https://justworks.com/blog/what-is-the-difference-between-a-perk-and-a-benefit

**Comment by whit537** [comment]
Some brainstorming in [slack](https://gratipay.slackarchive.io/gratipay/page-100/ts-1496668836499750)https://gratipay.slackarchive.io/gratipay/page-100/ts-1496668836499750 about what an "open source perks program" could mean for us.

**Comment by techtonik** [comment]
It is good that there is a public slack archive. Bad that from GitHub activity Gratipay seems mostly dead.

**Comment by whit537** [comment]
There's a [big difference](https://www.youtube.com/watch?v=xbE8E1ez97M) between mostly dead and all dead! 😆

**Comment by whit537** [comment]
+1 from @kennethreitz in private phone call.

Also, P.S., Sentry uses https://www.brightfunds.org/.

**Comment by whit537** [comment]
+1 from @mxstbr [on Twitter](https://twitter.com/mxstbr/status/878689357426765824):

> Yep yep, this is definitely a great idea as a job perk: "Spend $x/m on OSS projects you want to support"

**Comment by whit537** [comment]
+1 from @benvinegar in "[We Offered Matching Funds for Open Source — Here’s What Happened.](https://medium.com/open-collective/matching-funds-for-open-source-9653a81f8dcb)"

> Companies could put up the budget and engage employees in deciding how to distribute it. At bigger companies, the barrier is bureaucracy. Employees don’t want to go to some financial officer and pitch someone who’s probably not going to understand. It’s too hard.
>
>What if companies decided on a dollar amount to contribute to open source, say $10k, and divided that among employees or teams to decide which projects to fund? The commitment would already be unlocked at a higher level, and it would be a great way for companies to engage their engineers.

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
