### ISSUE TITLE
Multiple Currency Support

### ISSUE THREAD

**Issue by cakey** [gratipay/gratipay.com#1165]
This is hard.

There are a number of issues here:

Do people have to choose a primary currency, or can people give and receive multiple currencies simultaneously. Do we work entirely in USD?

At what point do we convert the currency? A primary currency means that conversion can happen on payday, and we can have lower effective rates by cancelling out USD->Euro and Euro->USD for example. However what if I'm happy to receive multiple currencies, such as bitcoin and don't want to incur the extra expense of conversion. If we work entirely in USD then clearly we are throwing away money when a european tips a european, or someone wants to tip in bitcoin.

To support giving in multiple currencies, we need to be able to connect multiple accounts? How do we display this on a user's page, how do we aggregate these values together?

How do we deal with variable conversion rates, do we try to get the best deal, or suck it up and accept what the figure is on pay day?

It seems we either go with a solution that is very complicated, or one that is inefficient and annoying.

This is the main reason I feel bitcoin support isn't trivial and should not be a priority.

Related issues:
#13
#14
#126
##

**Comment by slaivyn** [comment]
+1
I am very interested in being able to receive EUR because I would like to be supported via Gratipay for a software I am developing but the users are mostly very not used to deal with USD so it could be a real obstacle.
I have just created to subjects to bring my contribution: #3134 and #3135 :)

**Comment by whit537** [comment]
Interesting that Uphold (cf. #3870) doesn't hold all of its [liabilities](https://uphold.com/en/transparency) in the currency native to each liability (as it were):

![screen shot 2016-01-27 at 8 54 33 am](https://cloud.githubusercontent.com/assets/134455/12615441/b968014e-c4d3-11e5-9f95-92510529b7db.png)

**Comment by nobodxbodon** [comment]
Re-ticketed to https://github.com/gratipay/inside.gratipay.com/issues/974 for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.
