### ISSUE TITLE
revamp checkout flow

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#1167]
The idea with this ticket is to produce a modal checkout flow that can be used on both gittip.com profiles as well as embedded w/ a "Donate" button on other websites.

Some assets for this are over here: https://layervault.com/jeromegn/Gittip/Widget/tipping.sketch

@jeromegn built the one below for Clarity.fm (visible live on [www.danmartell.com](http://www.danmartell.com/), "Schedule a Call" on the sidebar). See #737 for another example and more of the motivation behind this ticket. This should be hosted on gttp.co and work will go in that repo, but please keep tickets in here.

![screen shot 2013-07-17 at 4 54 04 pm](https://f.cloud.github.com/assets/134455/815290/be8cae62-ef25-11e2-85ac-a915a1ab3164.png)

**Comment by whit537** [comment]
+1 from @elliottw at #3676:

>Have a widget that groups can put on there site, that allows non-gratipay users to easily sign up and donate to that particular group all within their site.
>
<img width="1035" alt="screen shot 2015-08-11 at 12 23 20 am" src="https://cloud.githubusercontent.com/assets/1633097/9190090/489c472a-3fbf-11e5-932a-b64ef22987e6.png">
>
I think Gratipay should be as prominent as it can without being annoying, and we can even have a button like "now go explore other projects to support!".
>
The current thing holding me back from moving a lot of catapultpgh members to gratipay, is that a lot of our base are not developers and I have had to spend 15 minutes onboarding people on to Gratipay to donate, which means lower donation rates not because people don't want to donate, but because they feel they it's very complex and confusing and they are signing up for some big thing when all they want to do is give catapult 10 bucks a months.

And @kzisme:

> I was thinking about something like this for a stint of time. I see a lot of other companies using widgets/buttons on their Twitch streams. Many other people would be interested if these buttons were introduced and the signup process was streamlined.

And @mattbk:

>I like the idea of streamlining the registration/giving process while offsite.
>
Would it have to wait for #1052?

**Comment by whit537** [comment]
This is an important project that needs a champion.

**Comment by elliottw** [comment]
just trying to wrap my ahead around the progress on this issue. @domenkozar looks like you'd a bunch of work. What else needs to get finished?
Do we have a functioning coded prototype?
Has everyone agreed on a user workflow?

My coworking space, @cataputlpgh would move everyone to gratipay if we can get this figured out, so I'm highly motivated!

**Comment by domenkozar** [comment]
@elliottw I wrote a prototype with no logic to talk the the backend, that's where most of the work needs to be done. If I had someone that would implement the backend logic I'm willing to implement the frontend side :)

**Comment by whit537** [comment]
!m @elliottw @domenkozar 

@rohitpaulk @rorepo @kzisme Want to help with the back end on this?

**Comment by elliottw** [comment]
@whit537 just bumped the bounty to 1k!! Also sent this issue to catapult members

**Comment by whit537** [comment]
Yikes! :astonished:

**Comment by mattbk** [comment]
Example of an onboard widget hardcoded in another site (looks like they built it themselves?): https://www.djangoproject.com/fundraising/campaign/django-fellowship/

**Comment by kzisme** [comment]
@whit I would not be opposed, but I would like/need some guidance.

**Comment by whit537** [comment]
For comparison, here's what Catapult has right now:

https://catapultpgh.memberful.com/checkout?product=282
https://catapultpgh.memberful.com/checkout?subscription=62
https://catapultpgh.memberful.com/checkout?subscription=38

![screen shot 2015-10-29 at 10 41 24 am](https://cloud.githubusercontent.com/assets/134455/10821652/d4765206-7e29-11e5-8944-e000ee31cecb.png)

**Comment by whit537** [comment]
Suggestion is to have a little more Gratipay branding ("Powered by ...") especially so that when we are sending Gratipay-branded emails to people it's easier to make the connection.

**Comment by whit537** [comment]
Here's the buttons on Catapult's site that go to the above:

![screen shot 2015-10-29 at 10 53 24 am](https://cloud.githubusercontent.com/assets/134455/10821963/56fab1c6-7e2b-11e5-94cc-66c58ec12f50.png)

**Comment by elliottw** [comment]
another example (from https://www.brainpickings.org):

<img width="689" alt="screen shot 2015-11-01 at 11 37 50 pm" src="https://cloud.githubusercontent.com/assets/1633097/10874406/9a6f5b32-80f1-11e5-95d4-5fd8ccb26814.png">

**Comment by mattbk** [comment]
Using the community as an indicator of trust could be used in some way.  Per [External Revenue Service](https://medium.com/orbital-nyc/schematic-for-a-generosity-engine-e373d076275f#.f370uzm4m):

> Recently, Walt received an email from the External Revenue Service stating that Grace had made a pledge to pay him a tax of $25 per month. He is skeptical that this was some kind of scam and wonders if Grace’s email has been hijacked (an unlikely scenario considering Grace’s technical chops), but after seeing that Grace’s portfolio also included his old pals Carl and Alice from school, he happily clicks to accept the pledge and start the ID verification process to connect his bank account for direct deposit.

**Comment by whit537** [comment]
Internet Archive using Stripe:

![screen shot 2015-12-11 at 4 47 56 pm](https://cloud.githubusercontent.com/assets/134455/11756294/fe655b24-a026-11e5-8b72-5d66de26a68c.png)

![screen shot 2015-12-11 at 4 49 42 pm](https://cloud.githubusercontent.com/assets/134455/11756359/5e580694-a027-11e5-8982-8b7e7411166c.png)

**Comment by whit537** [comment]
Closing in favor of https://github.com/gratipay/grtp.co/issues/103.

**Comment by mattbk** [comment]
Back over here because of my comment at https://github.com/gratipay/gratipay.com/pull/4268#issuecomment-269844784.

I don't think this should be under gratipay/grtp.co#103, because I see grtp.co as an offsite issue (add an onboarding widget away from gratipay.com) whereas this is an onsite issue. I imagine we are more constrained when offsite? In any case, I view these as separate because they can (but don't have to) proceed independently.

**Comment by mattbk** [comment]
So I'm here at https://gratipay.com/Gratipay, ready to donate. Never been here before. How do I give? Oh, it looks like I need to sign in to give. Cool.

![screen shot 2016-12-30 at 9 02 08 pm](https://cloud.githubusercontent.com/assets/3729038/21575499/4358505c-ced3-11e6-81d9-8a44037f8d81.png)

But I don't have an account yet, how can I sign in? Maybe there's a "create account" link behind this button (and I hope I don't get too far away from the page I'm on and wanting to give to)...oh, okay, when my mouse moves over I see that it's a menu with social media. So no "create account" link? What about this one up at the top? Same thing. Huh.

![screen shot 2016-12-30 at 8 59 23 pm](https://cloud.githubusercontent.com/assets/3729038/21575486/0b19ea5c-ced3-11e6-8e1e-a587cebbb870.png)

As much as social logins are used, I think they are usually accompanied by some sort of explanation: "Connect with Twitter to give;" "Sign up with Facebook;" etc.

**Comment by mattbk** [comment]
From [useronboard.com](http://www.useronboard.com/advice/#comment-2242064853) (linked above):

> default to "sign up" with a de-emphasized "log in" link as the alternative. This eases the path for new users in particular, and so long as you're managing cookies well, it's unlikely your existing users will see it very often. Social logins can take a lot of the pressure off, as well, since they can work for either use case.

**Comment by mattbk** [comment]
Even something like this might help:
![image](https://cloud.githubusercontent.com/assets/3729038/21575561/ce0e83f4-ced5-11e6-944a-c274e8cb9184.png)

**Comment by mattbk** [comment]
![image](https://cloud.githubusercontent.com/assets/3729038/21575571/4705045e-ced6-11e6-9712-bd685926ba49.png)
