### ISSUE TITLE
Create a press kit

### ISSUE THREAD

**Issue by pjz** [gratipay/gratipay.com#1172]
_**Original title:** `www.gittip.com needs an 'In the News' section`_

Or maybe it's called 'Elsewhere' or 'Mentions elsewhere' or 'News' or 'Press' or something.. a place to collect mentions of gittip out in the world.
##

**Comment by brareme** [comment]
@colindean mentioned this to me after the retreat this weekend. I think I'm willing to undertake a press kit, including a style guide. Colin will help me with the git stuff, but I'll probably need some more details about what is desired, as well as if I could join Gratipay and take a little to help support myself, as I am looking for work in graphic design presently.

He mentioned something about "reticketing this onto the inside gratipay repo since it's more the org and not the software".

**Comment by colindean** [comment]
Yay, @brareme!

Yes, I think this should be reticketed onto gratipay/inside.gratipay.com as two separate tickets: press kit and style guide. Thoughts, all?


The press kit will include the style guide eventually, but an MVP for the press kit would consist of the logo images and contact information.

These articles contain suggestions on what other things should probably be in the kit.

http://about.pplconnect.mobi/blog/writing-amazing-press-kit/

http://entrepreneursky.com/create-stunning-press-kit-startup/

http://onboardly.com/startup-pr/the-diy-media-kit-for-startups/

http://www.startupnation.com/articles/create-a-media-kit-for-your-small-business/

http://www.surepayroll.com/articles/start-up/how-to-make-a-media-kit.asp

**Comment by seanlinsley** [comment]
@brareme specifically Colin is referencing this project: https://github.com/gratipay/inside.gratipay.com

**Comment by whit537** [comment]
@brareme Awesome! I've added you to https://gratipay.com/Gratipay/members/. Welcome aboard! Has anyone explained to you how our [teams](https://gratipay.com/about/teams/) feature works?

Note that we do have http://inside.gratipay.com/big-picture/brand/. The primary audience for that document is people building Gratipay, but I think some of the content overlaps with what we would want in a press kit.

We're working together this week out in Ambridge. Any chance you'd be interested in joining us Monday or Wednesday to meet others and talk face to face about what your vision is here?

**Comment by brareme** [comment]
Thanks for the ad. Unfortunately, I won’t be available to meet this week. I’m still developing my ideas for the project as I’m familiarizing myself with your target audience. 

@colindean has explained to me the teams feature. I’m not exactly sure how much is appropriate for this task- Perhaps you can tell me what’s fair.

**Comment by whit537** [comment]
> Perhaps you can tell me what’s fair.

The goal is for you to be able to decide that for yourself. :-)

I think the best way forward would be for you to come out to Ambridge some Wednesday afternoon and find me at the Blue Canary Coffeehouse. I think it'll be a lot easier to get you plugged in if we can talk in person. Does this week work for you? Or next week?

**Comment by whit537** [comment]
@brareme We can also drop to email to schedule if you like: chad@zetaweb.com. :-)

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
