### ISSUE TITLE
provide monthly invoices

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#1199]
**was:** _make receipts look like software invoices_

So @wolfr can [deduct as a business expense](https://twitter.com/wolfr_/status/358959551602630657).

We have receipts. They look like this:

![receipt](https://f.cloud.github.com/assets/134455/832226/af6706e8-f23c-11e2-95d1-b4813124b40c.png)

What needs to look different?

##

**Comment by whit537** [comment]
Invoices mailed on [FD1483](https://gratipay.freshdesk.com/helpdesk/tickets/1483) passed muster with the company in question. Let's do more of that! :-)

**Comment by whit537** [comment]
Dribbble, for comparison:

 https://github.com/gratipay/gratipay.com/blob/68a0fc75990762875b2e93653313f39f881b9816/gratipay/billing/payday.py#L404-L450

**Comment by whit537** [comment]
Dribbble, for comparison:

![screen shot 2015-01-12 at 1 01 26 pm](https://cloud.githubusercontent.com/assets/134455/5707980/37811006-9a5b-11e4-8aab-c5e460b648ae.png)

**Comment by chrisdev** [comment]
@whit537 the "opt ins" are fine. 
The charitable organisation can always give explicit guidance to its supports to ensure select the correct options according to its requirements.

**Comment by whit537** [comment]
+1 https://gratipay.freshdesk.com/helpdesk/tickets/1940

**Comment by whit537** [comment]
> One of the things I do for money, is develop Varnish, and the Varnish Moral License is the vehicle I invented for the paperwork.
>
The way it works is very simple:
>
- Happy varnish users tell me that they want a Varnish Moral License
- I send them an invoice from my company
- They pay the invoice
- I develop Varnish

http://phk.freebsd.dk/VML/

(via https://github.com/gratipay/inside.gratipay.com/issues/732)

**Comment by whit537** [comment]
To: “phk@” at this site
Subject: text of the Varnish Moral License?

> Greetings! For the past four years I've been working on a (weird, open-sourcey) startup called Gratipay, which, I am now [starting](https://github.com/gratipay/gratipay.com/issues/1199#issuecomment-233178150) to realize, may be little more than an attempt to productize your Varnish Moral License. An initial question as I come to terms with the implications of this discovery: What is the actual text of the VML that you send to companies that purchase one? If such a text exists, may I share it with the Gratipay community?

**Comment by whit537** [comment]
Another example: http://pgloader.io/pgloader-moral-license.html

> I shamelessly stole the whole idea from [The Varnish Moral License](http://phk.freebsd.dk/VML/ ).

**Comment by whit537** [comment]
> This is the funding model I want to "sell" for other FOSS projects, because it works.

http://queue.acm.org/detail.cfm?id=2636165

**Comment by whit537** [comment]
Sounds like there is no official text, though we will likely discover additional bureaucratic hurdles such as NDAs and vendor registration.

**Comment by whit537** [comment]
> If you run any kind of online business, you’re almost guaranteed to have receipts and invoices. Any healthy business will need to process payments and send receipts for those payments. As ubiquitous as they are, they're emails that are frequently overlooked in terms of value and customer experience. However, a well-designed receipt or invoice can make a great impression on your customers and even help generate additional revenue.

https://postmarkapp.com/guides/receipt-and-invoice-email-best-practices

**Comment by whit537** [comment]
I'm calling this done with the invoices we shipped with the new homepage (#4589).
