### ISSUE TITLE
pjax-ify content

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#1229]
I worked out a good pjax strategy for Aspen on #1184, but then backed it out for that branch. It's recorded on https://github.com/gittip/aspen-python/issues/206. We should pjax-ify the whole app at once. This would involve a little js to update the nav (such as it is) when content changes, and also to fire js such as the chart renderer on `/about/charts.html`.
##

**Comment by nobodxbodon** [comment]
Close according to comment above.
