### ISSUE TITLE
/about/receiving-money/

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/gratipay.com#1234]
**was:** _shamelessly recreate this_

from @hurlothrumbo in private email:

https://www.paypal.com/webapps/mpp/transfer-money-online
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
