### ISSUE TITLE
choose profile picture from among connected accounts

### ISSUE THREAD

**Issue by wyze** [gratipay/gratipay.com#1253]
Give the user the ability to change their profile picture between the accounts they have linked.

Would also tie in with #920.
##

**Comment by whit537** [comment]
+1 on [Twitter](https://twitter.com/emTr0/status/566496355728625664).

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
