### ISSUE TITLE
Provide marketing assistance for those raising money

### ISSUE THREAD

**Issue by balupton** [gratipay/gratipay.com#1273]
Ideally, I would like a full-time income to come from Gittip. There seems to be a few steps to that:

1. Create amazing stuff
2. Expose that amazing stuff to as many people as possible
3. Inspire the people to donate via gittip to continue to fund development of amazing stuff

Gittip currently provides the technology to enable that, but it doesn't help that much with the workflow there. It would be great if there were videos, resources, walkthroughs, guides, tutorials, blogs, interviews etc from prominent people in the open-source community who are able to train people in accomplishing those 3 steps. As only one of those 3 steps needs to be lacking for the entire system to fallover. So the importance of making sure that all three of these things are catered towards, encouraged, facilitated, and fostered could not be stressed enough it seems.

I'd happily help on this, and document my journey as it goes. Any advice on this would be amazing, happy to gain feedback and help others on their journey too, making as much of it public as I possibly can.

[I've experimented with such a thing before in my younger years](https://vimeo.com/channels/milliondollarchallenge) and would be happy to kick such an approach up again with new learnings and others wanting to do the same.

**Comment by whit537** [comment]
+1 https://botbot.me/freenode/gratipay/2015-03-31/?msg=35506430&page=1

**Comment by whit537** [comment]
With the relaunch as [Gratipay 2.0](https://medium.com/gratipay-blog/gratipay-2-0-2453d3c53077) and the new focus on Teams, I think we now fall more directly under regular ol' business marketing advice. Let's point people to a few resources such as [*Traction*](http://tractionbook.com/) on the [payments FAQ](https://gratipay.com/about/features/payments). What are a few other resources we could list?
