### ISSUE TITLE
connect with Drupal.org accounts

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#1298]
Suggested by @wimleers on [Twitter](https://twitter.com/wimleers/status/364458988974657536).

We've got some infrastructure work to do before this is easy. Right now we connect to four different account types and there's a lot of code duplication between them. To do this properly we need to refactor Gittip's "accounts elsewhere" subsystem and then this will make more sense.
##

**Comment by nobodxbodon** [comment]
Re-ticketed to https://github.com/gratipay/inside.gratipay.com/issues/983 for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.
