### ISSUE TITLE
Categories for /giving/

### ISSUE THREAD

**Issue by jdorfman** [gratipay/gratipay.com#1328]
We use Gittip for a few different purposes (Sponsoring a FOSS project, pay developers that help us do a particular task, etc). It would be cool to have a way to categorize receivers we pay so we know who is who. e.g.

![image](https://f.cloud.github.com/assets/398230/971508/bcb9ffe8-05e8-11e3-9cc8-990f08846c1d.png)

Even a note feature would work: "Paying @whit537 because he is the man."
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
