### ISSUE TITLE
redesign profile page

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#133]
This is a meta-ticket for redesigning the profile page.

Originally ... copied from #43:

> Think Facebook timeline. A big part of Gittip for me is "the feeling of participation in someone else's story." I want Gittip to help tippees to tell their story. What are they doing to make the world better? Why? How is their vision unfolding? Let's link out to Twitter, blogs, etc. for the narrative, and let's use Gittip to tell the story in numbers. Here's what they're tipped and how much they tip. Here's when they've bombed or been bombed (#131). Here's how their funding goal has evolved (#110). And then the narrative bits add flesh to the bones. Here's what I did with the money. Here's how I made the world better. Here's how I realized my vision.

**Comment by rohitpaulk** [comment]
Can this be closed?
