### ISSUE TITLE
/on/behance/

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#1333]
Suggested by @cheeyoon on [Twitter](https://twitter.com/cheeyoon/status/369740883144372224).

cf. #504 (dribbble)
##

**Comment by nobodxbodon** [comment]
Re-ticketed to [integrate with software repositories / package manager / crowdfunding services](https://github.com/gratipay/inside.gratipay.com/issues/982) for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.
