### ISSUE TITLE
improve UI for removing a team member

### ISSUE THREAD

**Issue by balupton** [gratipay/gratipay.com#1351]
*was: How to remove a member from a team? How to revert a team to an individual entity?*

I find the gittip teams too complicated to use, so I'd like to go back to making DocPad an individual entity.

1. I can't find a way to remove team members from the DocPad team, as there is no remove button.

    ![image](http://d.pr/i/Vw4X+)

2. I also can't find a way to turn off the teams ability altogether.

**Comment by whit537** [comment]
+1 from @JeffSpies in https://github.com/gratipay/gratipay.com/issues/3177.

**Comment by rohitpaulk** [comment]
No team <-> members now, closing.
