### ISSUE TITLE
escrow the minimum possible

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#1383]
Today's convo on https://github.com/gittip/www.gittip.com/issues/5#issuecomment-23756765, along with "what to do with interest" (#279) and "look into getting a banking license" (#938), make me think that maybe we don't want to escrow any money at all, if we can help it. @zeeg suggested this on [Twitter](https://twitter.com/zeeg/status/344952755611377667) a while back.

The problem with escrowing money is that then we should be doing something with it, namely, earning interest. That's a whole ball of wax in and of itself (#279), and basically turns us into a bank (#938). It's a lot cleaner, both conceptually and legally, if Gittip isn't a bank. (Gittip may still be a money transmitter, but that's different than a bank; see #938 for now, though.)

In order not to hold money in escrow, we would need to require a bank account (or other funding sink) to be attached before we could move money on any recipients behalf. If the deposit fails then we would need a retry-then-refund algorithm, and if that fails then ... eep (that's why I say "as little as possible.").

We need a real EU story (#126) before we can do this. Manual PayPal isn't going to cut it as a funding sink, and without a funding sink and without escrowing we will be seriously retrograde in terms of value for non-U.S. participants.

We need to change the payday algorithm to settle up each week, rather than holding over from week to week. @carsomyr worked out the basics of this on #449.
##

**Comment by whit537** [comment]
Reopening in light of repercussions of the Balanced shutdown. Storing value is running us afoul of Stripe (https://github.com/gratipay/gratipay.com/issues/3245#issuecomment-91112973) and probably MTL in general (#3321).

**Comment by whit537** [comment]
We have three sources of escrow ([IRC](https://botbot.me/freenode/gratipay/2015-04-15/?msg=36705162&page=2)):

 1. **minimum charges**, in order to support micropayments (if you give $1/wk we charge ~$10/9wk)
 2. **giving holdover** (we hold funds for givers-who-receive week to week to cover next week's gifts, in order to avoid processing fees)
 3. **missing/broken withdrawal route** (we allow receivers to pool their money in Gratipay)

**Comment by whit537** [comment]
Looks like we don't need to get this done before Balanced shuts down, but it's still something we want to keep open.

**Comment by whit537** [comment]
We can't entirely eliminate escrow, because of the asynchronous nature of some payment methods. ACH credits can fail and we don't find out for days. We have to keep track of the balance in order to deal properly with such failures.

**Comment by whit537** [comment]
Also, we probably can't get rid of the payout threshold as long as there are per-transaction fees associated with that.

**Comment by whit537** [comment]
> Also, we probably can't get rid of the payout threshold as long as there are per-transaction fees associated with payouts.

And charging minimums in arrears doesn't entirely help: if I'm giving $1 each to 10 teams, then I'll be charged, but a given team will only end up with $1 in their account. Since PayPal doesn't have per-transaction fees, we could nip this source of escrow in the bud with a minimum payment of 50¢.

**Comment by rohitpaulk** [comment]
> if I'm giving $1 each to 10 teams, then I'll be charged, but a given team will only end up with $1 in their account.

How is that a problem? They're only getting $1 because I only intended to pay them $1.

**Comment by whit537** [comment]
@rohitpaulk Our current minimum payout is $10, so the team owner will end up with $1 in escrow with us. Payout minimums are a fourth [source of escrow](https://github.com/gratipay/gratipay.com/issues/1383#issuecomment-93550690).

**Comment by rohitpaulk** [comment]
Ah. I thought we were talking about the source that comes with **payin** minimums. :)

**Comment by whit537** [comment]
:)

**Comment by whit537** [comment]
We can refund the escrow due solely to payin minimums separately from the escrow due to other sources, and that wouldn't require user coordination. We need users to apply in order for us to pay *out* escrow, but not to refund escrow paid *in* that hasn't yet been shuffled around inside Gratipay.

**Comment by whit537** [comment]
And once we refactor payin minimums, we'll be able to drop payout minimums as well.

**Comment by whit537** [comment]
#### Sources of Escrow

| Source | Turned off? | Refunded? |
|----|-----|--------|
| pooling | [yes](https://medium.com/gratipay-blog/gratipay-2-0-2453d3c53077) | no |
| holdovers | [yes](https://github.com/gratipay/gratipay.com/pull/3629) | yes (right?) |
| payin minimum | no | no |
| payout minimum | no | no |
| async payouts | n/a | n/a |

**Comment by whit537** [comment]
Readded to Balanced Shutdown.

**Comment by whit537** [comment]
I'm revising "[Shuffle Escrow](http://inside.gratipay.com/howto/shuffle-escrow)" as part of responding to https://github.com/gratipay/gratipay.com/issues/726#issuecomment-127693234. In so doing, it occurs to me that with a much lower escrow, we will have to take care that we don't "bottom out" our escrow account at PayPal. With a higher escrow, we always had enough to top up PayPal a week ahead of time, so that we could pay out immediately every Thursday. After we refund 1.0 balances (#3539), it seems likely to be the case that we won't have enough cash in escrow to float the weekly transfer to PayPal. What's the answer? I suppose we might build up and maintain a buffer from operations. That would need to be about $10,000 based on current usage.

**Comment by whit537** [comment]
Since the buffer required will grow linearly with the weekly volume we're processing, it's impractical to maintain such a float. If we're moving $1,000,000 a week, we'll need a $1,000,000 buffer! No: we should delay payout to reflect the real cash we have in hand. We need to offset payouts by a week.

**Comment by whit537** [comment]
As I think about corporate givers, I'm not sure that won't be another source of escrow: experience indicates that companies want to pay a big chunk once, and not be bothered with lots of little (expensive) transactions. That means either supporting one-time payments (#5) or escrowing the money for them while we dole it out.

Under another corporate use-case, I know @timothyfcook is interested in using Gratipay for payroll-only. He wants to fund a Team with money received separately, using Gratipay only for the sharing/distribution side. Surely for that situation there will also be an interest in adding money in larger chunks and letting it sit for some period of time.

**Comment by whit537** [comment]
Blog post about charging in arrears, ready for review: https://medium.com/gratipay-blog/charging-in-arrears-18cacf779bee.

cc: @mattbk @kzisme @rorepo et al.

**Comment by mattbk** [comment]
> As I think about corporate givers, I'm not sure that won't be another source of escrow: experience indicates that companies want to pay a big chunk once, and not be bothered with lots of little (expensive) transactions. That means either supporting one-time payments (#5) or escrowing the money for them while we dole it out.

Is voluntary escrow a problem, legally?

**Comment by whit537** [comment]
Stripe [mentioned](https://github.com/gratipay/gratipay.com/issues/3245#issuecomment-91112973) "stored value" in the context of money transmission, but that now seems like a red herring. Nothing I've seen so far indicates to me that storing value is relevant to money transmission.

I just looked into the definition of a bank. It's not as clear as with money transmission (#3321). The place where money transmission [is defined](http://www.ecfr.gov/cgi-bin/text-idx?SID=a457db49113d5f8ca45f5252dd7dced0&mc=true&node=se31.3.1010_1100&rgn=div8) (cf. [IG-192](https://github.com/gratipay/inside.gratipay.com/issues/192#issuecomment-100048271)) defines a bank as:

> Each agent, agency, branch or office within the United States of any person doing business in one or more of the capacities listed below:
>
(1) A commercial bank or trust company organized under the laws of any State or of the United States;
>
(2) A private bank;
>
(3) A savings and loan association or a building and loan association organized under the laws of any State or of the United States;
>
(4) An insured institution as defined in section 401 of the National Housing Act;
>
(5) A savings bank, industrial bank or other thrift institution;
>
(6) A credit union organized under the law of any State or of the United States;
>
(7) Any other organization (except a money services business) chartered under the banking laws of any state and subject to the supervision of the bank supervisory authorities of a State;
>
(8) A bank organized under foreign law;
>
(9) Any national banking association or corporation acting under the provisions of section 25(a) of the Act of Dec. 23, 1913, as added by the Act of Dec. 24, 1919, ch. 18, 41 Stat. 378, as amended (12 U.S.C. 611-32).

It seems to focus on how the entity was chartered rather than on what the entity does. I don't find anything about operating an "unlicensed bank" that's similar to what we found with operating an "unlicensed money transmission business." I guess this is how PayPal gets away with [pretending they're not a bank](http://money.howstuffworks.com/paypal7.htm):

> The biggest criticism of PayPal is that it acts like a bank, but it isn't regulated like one. This means that PayPal offers none of the protection that real banks offer, and it isn't required to maintain any of the security, customer service or dispute resolution services that banks provide. At the same time, PayPal holds large amounts of their customers' money, makes millions of financial transactions and even offers credit and debit cards.
>
So why isn't it considered a bank? In 2002, the Federal Deposit Insurance Corporation (FDIC) declared that because PayPal didn't meet the federal definition of an entity accepting deposits as a bank, hold any physical money or have a bank charter, it was not a bank [source: [Wolverton](http://www.cnet.com/news/feds-paypal-not-a-bank/)]. In other words, PayPal isn't a bank because it doesn't call itself a bank. As a result, most states license PayPal as a "money service."

Is voluntary escrow a problem, legally?

The answer seems to be, "No."

**Comment by whit537** [comment]
Reviewing https://github.com/gratipay/gratipay.com/issues/1383#issuecomment-93550690 ...

 - [x] minimum charges—done in #3675. !m @rorepo
 - [x] giving holdover—done in #3629. !m @rorepo 
 - [ ] missing/broken withdrawal route
 - [x] ~~payout minimum~~—nothing more to be done about this

**Comment by whit537** [comment]
Looks like #3754 is the last thing need to close this ticket, eh?

**Comment by whit537** [comment]
In order to land #3754, we need to finish cleaning up the `exchanges` table:

 - avoid null `route`, `ref`, and `status` in new exchanges (https://github.com/gratipay/gratipay.com/issues/3822)
 - finish backfilling `route`, `ref`, and `status` in old exchanges (https://github.com/gratipay/gratipay.com/issues/2779)
 - constrain `route`, `ref`, and `status` to non-null (https://github.com/gratipay/gratipay.com/issues/3839)

**Comment by whit537** [comment]
Got this far enough for the Balanced Shutdown, taking off that milestone now.

**Comment by whit537** [comment]
It turns out that this isn't really necessary, and is in fact not workable in the long run. Online wallets are not banks (though there are some [early rumblings](http://www.bankingtech.com/735552/amazon-looking-to-buy-capital-one/) that regulation may eventually be coming to stored value accounts). Storing value did not turn out to be the "crux" of the money transmission issue with Gittipay 1.0 as Stripe had [suggested](https://github.com/gratipay/gratipay.com/issues/3245#issuecomment-91112973).

Moreover, in order to keep payments snappy, we actually _need_ an escrow. It takes us days to move funds under the hood, but we want to be able to pay out on demand. We need an escrow to float the difference. This is normal operating practice (e.g., I heard through the grapevine that it's one reason Uber has had to raise so much cash—to float the payouts to drivers before payins from riders are fully in hand; e.g., Patreon doesn't payout by default, one has to explicitly set that up after the fact; e.g. PayPal QED).

**Comment by Changaco** [comment]
FTR escrow is exactly what you need a licence for in Europe, because holding people's money means that they may lose it if you do stupid things with it.

In fact a few months ago the financial watchdog in France came down on an almost-bank which wasn't properly managing their clients' money.

**Comment by whit537** [comment]
Good to know.
