### ISSUE TITLE
Contact Chrome/Firefox plugin developers and ask them to add gittip links

### ISSUE THREAD

**Issue by greggles** [gratipay/gratipay.com#1392]
Lots of browser plugins are run as mini open source projects with one or two maintainers who often ask for donations via Paypal.

There seem to be two things to do:
1. Reach out to individual plugin contributors on an adhoc basis
2. Mozilla Addons even has paypal integration (e.g. [adblock](https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/?src=hp-dl-mostpopular) - look at the blue contribute button). Mozilla might be a good organization to try to partner with to get gittip added since one-time payments are less useful for plugin developers than ongoing ones.
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
