### ISSUE TITLE
pay in with bitcoin

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/gratipay.com#14]
**Status:** We need someone to join [Team Gittip](https://medium.com/building-gittip/eba0a27825b8) and take ownership of our bitcoin integration. Is it you?!

The essence of Gittip is recurring gifts, and there is (I gather) no way to do recurring bitcoin payments. Gittip will likely add explicit support for one-off (#5) and pre-paid (#113) gifts once the core recurring feature has matured. At that point we'll be ready for funding with bitcoin.

I (@whit537) am going to let someone else contribute the bulk of this work. On the pattern of Balanced contributing integration with their system (#78), my ideal would be to see a bitcoin processor such as [Bit-Pay](https://bit-pay.com/) step forward and contribute integration with their service. A lesser option would be for a non-Bit-Pay member of the Gittip community to contribute the integration.

**Comment by tchoulihan** [comment]
I like the project, but it seems pointless without bitcoin integration. Or you could just use stripe which already has bitcoin baked in.

**Comment by mattbk** [comment]
+1 from https://gratipay.freshdesk.com/helpdesk/tickets/3417.

**Comment by mattbk** [comment]
+1 from https://gratipay.freshdesk.com/helpdesk/tickets/5056.

Unfortunately, this does not seem likely to happen in the near future. See https://github.com/gratipay/gratipay.com/issues/1451#issuecomment-147424265 for an explanation.
