### ISSUE TITLE
Investigate infrastructure management solutions (Deploy! Deploy! Deploy!)

### ISSUE THREAD

**Issue by rummik** [gratipay/gratipay.com#1424]
IRC: https://botbot.me/freenode/gittip/msg/5899206/

Right now we're just using some manual configuration on [gttp.co](https://github.com/gittip/gttp.co), but it would be nice to have this automated so we just have to push couple buttons to deploy to a second VM in the future.

We'll also be using this for [www.gittip.com](https://github.com/gittip/www.gittip.com) when we've outgrown Heroku, so whatever it is needs to be pretty much language agnostic.

Some suggested solutions (see [IRC](https://botbot.me/freenode/gittip/msg/5899206/)):
- [Salt Stack](http://saltstack.com/)
- +1 [Chef](http://www.opscode.com/chef/)
- +1 [Puppet](https://puppetlabs.com/puppet/)
- +1 [Ansible](https://github.com/ansible/ansible) (@rgieseke)
##

**Comment by nobodxbodon** [comment]
We [decide](https://github.com/gratipay/inside.gratipay.com/issues/946) to continue using Heroku in short term.
