### ISSUE TITLE
clean up Tumblr blog

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#1431]
I set up the Gittip blog as a secondary blog, the primary blog of which was my personal Tumblr account, which I never use. Ideally we'd have a primary blog for Gittip:

http://www.tumblr.com/docs/en/blog_management#versus

Looks like the thing to try is creating a new Tumblr account and then transferring content via WordPress and Blogger:

http://smallbusiness.chron.com/transfer-tumblr-posts-another-account-63666.html

**Comment by mattbk** [comment]
Closing since we no longer use Tumblr.
