### ISSUE TITLE
Conditional header text

### ISSUE THREAD

**Issue by twolfson** [gratipay/gratipay.com#1436]
I saw the recent update to the header and while it is awesome to display the stats (i.e. X users exchanging $Y per week), it might not be the wisest thing to display to new users on the site.

![screen shot 2013-09-11 at 5 24 53 pm](https://f.cloud.github.com/assets/902488/1127648/c7327c0c-1b41-11e3-8eaf-77ea52987166.png)

In the case of a new user, assuming they have no notion of what Gittip is, would be very confused by the tag line. Especially if they land on a user's profile page, not the homepage.

My recommendation would be for a non-logged in user, display different header text which links back to the home page or the /about page. This header text could be a previous flavor (e.g. "Distributed Genius Grants") or the same text as the homepage (e.g. "Sustainable Crowdfunding") to hint at the purpose of Gittip.

![screen shot 2013-09-11 at 5 25 50 pm](https://f.cloud.github.com/assets/902488/1127651/e9cbd38a-1b41-11e3-8465-10aca23ac3ad.png)

**Comment by Changaco** [comment]
Closing as obsolete.
