### ISSUE TITLE
Proposal for full bitcoin integration

### ISSUE THREAD

**Issue by reedlaw** [gratipay/gratipay.com#1451]
While #14 addresses bitcoin pay-in and #310 pay-out using external services, this proposal is for supporting bitcoin directly as an alternative payment vehicle.

# Workflow
* A participant who wants to give bitcoin is presented with a custom Gittip funding address.
* Once this address is funded, the giver can start distributing it.
* Profiles with bitcoin enabled (i.e. with a bitcoin address) are eligible to receive bitcoin tips.
* Recurring payments will happen automatically until the giver's funds run low.
* Recipients are paid directly into their bitcoin wallet.
* Email notification are sent reminding givers to replenish their funds.

# Implementation
* A long passphrase is used to generate an offline wallet, or ["brainwallet"](http://brainwallet.org/).
* The passphrase-generated deterministic wallet is never stored on disk. By deterministic wallet I mean given a passphrase x and a procedure f, f(x) always generates the same wallet.
* The passphrase is never stored on disk but only as an environment variable on the Gittip server.
* The passphrase is converted to a private key which is used in memory for signing all bitcoin transactions.
* When a participant requests a bitcoin funding address, a new bitcoin address is generated based on the passphrase plus a unique identifier. The way [bitcoin addresses work](https://en.bitcoin.it/wiki/Technical_background_of_Bitcoin_addresses) is they are a key pair stored in a wallet file for each receiving address. This proposal uses offline wallets so it doesn't support storing multiple key pairs in a single wallet file. Instead, we can create a new key pair based on the passphrase + id of each participant.
* When it comes time to send out weekly payments, private keys are regenerated in memory based on the passphrase and ids. These keys are then used to sign transactions sending funds to recipients' addresses. They way bitcoin works is that transactions are stored in a chain of blocks representing every transaction from the beginning, including those that generate new bitcoins. These transactions must be signed cryptographically. Transaction history determines the current amount of bitcoins associated with each bitcoin address. In order to transfer bitcoins from one account to another, someone has to have the private key associated with the sending address. The private key signs a transaction in much the same way you would sign a check. A transaction signing is an event that is published immediately on the bitcoin network and rapidly confirmed by thousands of other nodes until it becomes a permenant record in the block chain. Thus bitcoin transactions are irreversible once signed. That's what makes the next section so important.
* Much of the bitcoin-related code has already been implemented and well documented elsewhere in multiple languages. Thus it would be a matter of integration.

# Security
* At first when the amount in the funding account is small, it should be sufficient to store the passphrase as an environment variable on the server. An attacker would have to have access to either the working memory on the server or its environment variables in order to compromise this system.
* A better solution would be not to store the passphrase anywhere, but instead use some form of secret sharing such as [Shamir's](https://en.wikipedia.org/wiki/Shamir's_Secret_Sharing) or implement multi-signature transactions like in the [Armory client](https://github.com/etotheipi/BitcoinArmory/blob/qtdev/armoryengine.py#L4685-L4700). This would mean that an attacker could not compromise the system with only a single secret, but it would be much harder to implement.

**Comment by rohitpaulk** [comment]
We don't do bitcoin anymore, closing this.

**Comment by knocte** [comment]
You've lost some users then :)  For anyone coming here and wondering about an alternative that *does* support bitcoin: bountysource's Salt.

**Comment by ELLIOTTCABLE** [comment]
@knocte thanks for the heads-up re: an alternative. /=

**Comment by mattbk** [comment]
For context, bitcoin was removed in order to meet anti-money-laundering regulations: https://github.com/gratipay/inside.gratipay.com/issues/192#issuecomment-100048271

**Comment by whit537** [comment]
> For context, bitcoin was removed in order to meet anti-money-laundering regulations

Yes. We dropped bitcoin in order to clearly meet the second of four parts to the definition of a payment processor (by which we are exempt from regulation as a money transmitter), namely, that we "operate through clearance and settlement systems that admit only BSA-regulated financial institutions". Here is [a longer explanation](https://github.com/gratipay/inside.gratipay.com/issues/201#issuecomment-102010517).

**Comment by mattbk** [comment]
I wanted to make it clear due to this Twitter stream: https://twitter.com/passcod/status/652630603574067200.

**Comment by passcod** [comment]
[Back-linked](https://twitter.com/passcod/status/653671096172941312) to this on the Twitter thread for accuracy :)

**Comment by mattbk** [comment]
Hey, thanks!
