### ISSUE TITLE
Document the API more fully for 3rd party developers

### ISSUE THREAD

**Issue by mvdkleijn** [gratipay/gratipay.com#1475]
Based on #1473 and the fact that I consider good - decent docs part of "Infrastructure". (in this case infra towards 3rd party devs)

I can take this one on myself by the way in the form of expanding / improving the existing docs.
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
