### ISSUE TITLE
implement bundles

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#1493]
A "bundle" would be a set of projects, where the user can give a fixed amount to the set and it will be split up among them according to some ratio.

----------

## Previous

_This idea started as "support the flattr 'divide the spoils' model" (#316), which got subsumed by "implement funds" (#449). That, however, took a different turn, which ended up as the [Teams](https://www.gittip.com/about/teams/) feature. There's still value in the funds idea, however, so here we're bringing it back up._

Funds would be lists of percentages with a total dollar figure attached. So you might have a "Linux" fund with 50 people on it and you could set a total dollar figure that would be split according to the percentages. Funds would be public (by default) in that anyone could give to your fund, but they would be anonymous in the particulars&mdash;even for those receiving through a fund.

Say Linus has a "Linux" fund. I trust his judgment on who should get money given to "Linux" so I give $10/wk to his fund. Each week my $10 goes into that fund and gets split according to the percentages that Linus has set.

**Comment by whit537** [comment]
+1 https://gratipay.freshdesk.com/helpdesk/tickets/1705

> It would be great if the giving page could be customised. Instead of one long list, the ability to have several customised lists. i.e. “Tips to Team”, “Tips to Members”, “Tips to Organisations We Love”, etc. This way we can have greater transparency over how we distribute our tips.

**Comment by mattbk** [comment]
Recently "[bundles](https://github.com/gratipay/inside.gratipay.com/issues/436#issuecomment-258194756)" have come up as a variation of this, but they wouldn't be public.

**Comment by whit537** [comment]
@dmk246 suggests the shopping cart model. Add projects to yer cart and then check out.

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
