### ISSUE TITLE
Build out a community ad network

### ISSUE THREAD

**Issue by chrismdp** [gratipay/gratipay.com#1513]
**was:** _HTML snippet to promote the Top Giver_

I think we should try to increase the Top Giver profile. They're doing a fantastic job for the community, and it should be as desirable as possible to get the Top Giver spot in order to maximise the amount people give.

Can we perhaps have a little HTML snippet or widget to promote the Top Giver page on our websites? I'd happily run a little mini-ad on my blog which automatically changed to the next Top Giver each week to help promote the fact they're giving back.

Any thoughts?
##

**Comment by whit537** [comment]
Can we call this GratiSense? :-)

**Comment by chrismdp** [comment]
YES! :) Glad to see this one might become a reality!

**Comment by whit537** [comment]
Relevant:

> Humanity Box is a free ad network designed to increase exposure to individuals raising funds for personal medical needs.

http://humanitybox.com/

![screen shot 2015-07-26 at 6 03 29 pm](https://cloud.githubusercontent.com/assets/134455/8896140/a55f6a1a-33c0-11e5-8a80-0d58e8813489.png)

**Comment by MartinDesigner** [comment]
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
As a main point for everyone(!) I propose to try this amazing free app. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi

**Comment by whit537** [comment]
OC is exploring this: https://twitter.com/opencollect/status/882735419774836737.

**Comment by whit537** [comment]
https://medium.com/open-collective/using-ads-to-sustain-open-source-d048b75d4979

**Comment by whit537** [comment]
> So many open source projects try to find funding through donation buttons. This can sometimes help, but rarely results in consistent or meaningful income. We believe sponsored advertising is the solution.

https://codesponsor.io/

**Comment by whit537** [comment]
They're using SVG with `no-cache`.

https://app.codesponsor.io/embed/PKGFLnhDiFvsUA5P4kAXfiPs/kentcdodds/cross-env.svg

```
[![Watch on GitHub][github-watch-badge]][github-watch]
[![Star on GitHub][github-star-badge]][github-star]
[![Tweet][twitter-badge]][twitter]

[![Sponsor](https://app.codesponsor.io/embed/PKGFLnhDiFvsUA5P4kAXfiPs/kentcdodds/cross-env.svg)](https://app.codesponsor.io/link/PKGFLnhDiFvsUA5P4kAXfiPs/kentcdodds/cross-env)

## The problem

Most Windows command prompts will choke when you set environment variables with
`NODE_ENV=production` like that. (The exception is [Bash on Windows][win-bash],
which uses native Bash.) Similarly, there's a difference in how windows and
POSIX commands utilize environment variables. With POSIX, you use: `$ENV_VAR`
```

https://github.com/kentcdodds/cross-env

![screen shot 2017-09-05 at 8 37 12 am](https://user-images.githubusercontent.com/134455/30061456-6fa78604-9215-11e7-91d5-8111f2720d69.png)

**Comment by whit537** [comment]
Talked to someone from [{Code}](https://thecodeteam.com/) (Dell) and he was interested in putting ads on his Dell/Code READMEs in order to gather data on traffic to his site. Non-[ethical advertising](https://codesponsor.io/developers/#ethical-advertising), in other words.

He had also seen a Gratipay badge on a job applicant's README recently! 😆

P.S. Badges are a form of advertising already extant on GitHub READMEs, as we [know](https://github.com/gratipay/inside.gratipay.com/issues/1133).

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
