### ISSUE TITLE
typecheck: discuss

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#1539]
We've got soft typechecking some places around the app. We should understand why we're doing that and do it consistently (if we don't decide to scrap the practice entirely).

[IRC](https://botbot.me/freenode/gittip/msg/6623517/)
##

**Comment by nobodxbodon** [comment]
Quick search in code base shows typecheck only used in gratipay/billing/exchanges.py now.
Please reopen if further discussion is still needed.
