### ISSUE TITLE
Use API to retrieve list of users that are currently tipping me

### ISSUE THREAD

**Issue by SjonHortensius** [gratipay/gratipay.com#1546]
I would like to offer additional service to people that are tipping me; but I need the list of people and the amount they tip me weekly, possibly including start-date and total-amount so far. Is this possible through the API?

**Comment by whit537** [comment]
+3 @syncome @rummik @incni over on #3126, which I'm closing as a dupe, reopening here.

**Comment by whit537** [comment]
+1 @clintonpaquin at https://github.com/gratipay/gratipay.com/issues/236#issuecomment-37193614:

> My idea was to reward tippers by granting them web access to certain areas of my project (think ACL). I don't really care who they are (Ie. I don't need their name, info, etc...) all I want is to know that they have tipped and then I can grant them ACL privileges. Even an endpoint that I can hit to give me a list of users that have tipped me would be sufficient. Thoughts?

**Comment by whit537** [comment]
+1 from me too, I guess, for Open Company Initiative membership (cf. https://github.com/opencompany/www.opencompany.org/issues/130).

**Comment by whit537** [comment]
+1 from Inkscape on #3351.

**Comment by mattbk** [comment]
This is part of https://github.com/gratipay/gratipay.com/issues/236.
