### ISSUE TITLE
Clean up db schema

### ISSUE THREAD

**Issue by zwn** [gratipay/gratipay.com#1549]
Currently we have a mix of different approaches. Decide on a single way and implement it.

##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃

**Comment by adewes** [comment]
@whit537 really sorry to hear this, it was a great project and as well as team behind it! I was very happy meeting you at the PyCon three years ago and I wish you good luck for your next project whatever that may be!
