### ISSUE TITLE
address all XXX and TODO comments throughout codebase

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#1550]
This could be too deep a rabbit hole.
##

**Comment by mattbk** [comment]
Found this ticket so I figured I would do a search: 14 results, although many of those are from the "todo_url" field that now exists for Teams.

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
