### ISSUE TITLE
Service for android users to easily tip app maintainers

### ISSUE THREAD

**Issue by patcon** [gratipay/gratipay.com#1587]
This is just a stub for a thought.

Was just thinking how best to use gittip, and as I was downloading a free app, I was thinking "I should just go through every free app that I'm using, and find the developer email, and then check if they have a gittip account!"

Needless to say, this is a ton of work. So the thought was that maybe we could create a simple service that someone auth's their Google account on, and it cross-checks for gittip accounts, perhaps emailing maintainers if they're not gittip members. But it seems that the [Android Market does not have an official API.](http://stackoverflow.com/questions/6469200/any-android-market-api-from-google)

However, I did find an [unofficial API](https://code.google.com/p/android-market-api/). There's also a [helper app that can be used to access this data on the phone itself](https://play.google.com/store/apps/details?id=com.jrummy.apps.google.play.api&hl=en).

Someone still need to dig in, but it sounds like this helper app can get access to extended info on installed apps, so perhaps one route would be to create an android app that uses this helper app to allow android uers to set up gifts for the maintainers of the apps they use. Obviously this is blocked on the fact that no Gittip android app yet exists :)

But as I said, I just wanted to get this idea out in the open!
##

**Comment by nobodxbodon** [comment]
Re-ticketed to [integrate with software repositories / package manager / crowdfunding services](https://github.com/gratipay/inside.gratipay.com/issues/982) for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.
