### ISSUE TITLE
Improve masspay script

### ISSUE THREAD

**Issue by zwn** [gratipay/gratipay.com#1630]
Reticketing from #1625. Bringing over the notes:
- Also this script (like the backup script) makes assumptions about what the filesystem looks like outside of the git repository (os.chdir).
- It would be great to know how to properly run it (what environment it requires) - to add to the top of the file
- It would be great to know what it is trying to do in the calculations - to add to each of the compute functions
- The csv files could be sorted by username (or by anything that is the same in all csvs) to ease comparing them.
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
