### ISSUE TITLE
Let teams decide for themselves how money is split.

### ISSUE THREAD

**Issue by traverseda** [gratipay/gratipay.com#1660]
Right now you've got a lot of very ideological and complicated code in how teams get paid out.

> Please note that no one, not even the team account owner, can change a member's take. The team account owner can only add or remove members.

That's simply not practical for a lot of projects.

I'd suggest having a bunch of different methods for managing team payments, including what you have now and completely central management by the team owner.
##

**Comment by whit537** [comment]
+1 @elliottw at https://github.com/gratipay/gratipay.com/issues/3480#issuecomment-106038415:

> instead of the kids eat first/double your income each week,
team decides on distribution, if team is size=1 then it's a no brainer
if no one makes a decision funds are split equally?? or some slightly smarter algorithm
I think the algorithm with which teams distribute funds has more social impact than most other parts of the app. I'd be curious about a model like "older kids look after younger kids" which I guess would be little like trickle down economics, but now that I type it, it doesn't sound so great.

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
