### ISSUE TITLE
Display top "ready to give" pending recipients

### ISSUE THREAD

**Issue by sreynen** [gratipay/gratipay.com#1676]
I would like to see a list of accounts that have the most payments "ready to give." I hope this would make it easier to convince people/organizations to take the effort to sign up. I already contact people and say "I want to give you money on Gittip, so you should sign up," and expect it would be a little more compelling to say "You're in the top 20 pending recipients on Gittip, so you should sign up."

It could also encourage more giving to accounts that haven't signed up yet, by making them more visible. Whenever I go to give to someone who hasn't signed up yet and see they already have pledges, I realize I would have pledged earlier if I'd seen the initial pledge.

**Comment by rohitpaulk** [comment]
We don't support pledges anymore, closing.
