### ISSUE TITLE
Put +1s and -1s in the original issue post (the 1st post on the issue) rather than new posts

### ISSUE THREAD

**Issue by balupton** [gratipay/gratipay.com#1687]
The gittip issues are becoming infinitely long with +1s and -1s. This is quite frustrating when I have a github notification to check out a new comment, and it is just another +1. It would be nice if they were just listed inside the original posts comment, and if one doesn't have those abilities to edit the original posts comment, they post a comment, and a repo owner adds it to the original post and deletes their individual comment.

+1s
- @balupton

**Comment by dchandramahanti** [comment]
+1
