### ISSUE TITLE
Create self test for the data in db

### ISSUE THREAD

**Issue by zwn** [gratipay/gratipay.com#1705]
#1118, #1549 and #1704 got me thinking that it would be good to set up some way to self test the data in the db.

If we do incremental updates in #1549 it would be good to run the rebuild from time to time to check if the incremental updates reflect correctly on all the situations. One special case of this is #1118.

The problem in #1704 could be checked for if we could encode application logic into the test like _after user is orphaned/absorbed it takes part in no transactions_. There may be others that cannot be expressed as a constraint in the db.

**Comment by Changaco** [comment]
Closing. I had planned to add the extra checks, but we'd have to either rewrite history or hard code exceptions to prevent them from failing, and I don't like either of those solutions.
