### ISSUE TITLE
Document development process

### ISSUE THREAD

**Issue by seanlinsley** [gratipay/gratipay.com#1728]
[Today in IRC](https://botbot.me/freenode/gittip/msg/8478988/) we've been discussing [Waffle.io](https://waffle.io/) and [Huboard](https://huboard.com/) as options to help visualize and track progress, and eventually decided we'd give Huboard a try: https://huboard.com/gittip/www.gittip.com :beers: 

Now we need to document the process so the custom way we use it is clear to newcomers.

**Comment by whit537** [comment]
We're no longer using Waffle or Huboard.
