### ISSUE TITLE
Add option to not show profile on leader boards / make profile unavailable in search (engines)

### ISSUE THREAD

**Issue by rummik** [gratipay/gratipay.com#1733]
Compliments #1683

Edit: It really seems like this should be a duplicate, but I couldn't find one.

**Comment by Changaco** [comment]
Closing as done/obsolete.

**Comment by whit537** [comment]
This is implemented in #3281, in that the communities (currently, still) query now respects `is_searchable`. However, that PR isn't landed yet.
