### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by zwn** [gratipay/gratipay.com#1739]
We do not have a tests for:
 
 * www/for/index.html.spt
 * www/for/%slug/index.html.spt
 * www/%username/horn/toot.json.spt
 * www/%username/horn/toots.json.spt
 * www/credit-card.json.spt
 * www/%username/history/index.html.spt
 * www/about/paydays.json.spt
 * www/about/charts.json.spt
 * www/about/fraud/2012-11-05.html.spt
 * www/about/fraud/review.html.spt
 * www/about/tip-distribution.json.spt
 * www/about/top.json.spt
 * www/on/github/%login/index.html.spt
 * www/on/twitter/%screen_name/index.html.spt
 * www/on/bitbucket/%username/index.html.spt
 * www/bank-account-complete.html.spt
 * www/bank-account.json.spt

This has been found in #1737.

**Comment by Changaco** [comment]
Closing, tests for GET requests on all simplates were added in #3033.
