### ISSUE TITLE
Personal charts don't give a very good sense of time

### ISSUE THREAD

**Issue by seanlinsley** [gratipay/gratipay.com#1782]
An illustration:

``` js
$.get('./charts.json',function(d){ Gittip.charts.make(d.slice(0,25)) })
```

Got me a second chart right below the normal one:
![screen shot 2013-12-17 at 7 58 10 pm](https://f.cloud.github.com/assets/688886/1770272/36f9393a-6788-11e3-8704-b9d4cbc66347.png)

I guestimated that I've been on Gittip for 25 weeks. Isn't that a better illustration, especially for people who recently joined?
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
