### ISSUE TITLE
allow C++ as community name

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#1794]
Requested by @pawbyte on [Twitter](https://twitter.com/Pawbyte/status/414779800180371456).

We currently disallow `+` in community names. They're using [`cplusplus`](https://www.gittip.com/for/cplusplus/). I tried UPDATEing under the hood to C++ but we actually 404 if the slug doesn't match the constraint.

**Comment by mattbk** [comment]
Closed until communities ([or tags](https://github.com/gratipay/gratipay.com/issues/3127)) return.
