### ISSUE TITLE
Effectively communicate tips recur weekly

### ISSUE THREAD

**Issue by bruceadams** [gratipay/gratipay.com#1799]
@j-francisco didn't realize, when first tipping on Gittip, that tips recur weekly. What can we do to avoid this confusion for new users?
##

**Comment by mattbk** [comment]
Looking at http://gratipay.com with fresh eyes, this is still valid. It's not until I get to a Team page that is says "You give $0.00 _per week_" (emphasis added).

**Comment by whit537** [comment]
We just had another support [inquiry](https://gratipay.freshdesk.com/helpdesk/tickets/6525) related to this:

> Omg, I just saw that I donated $192!?!?!?! I never wanted this. I thought I was giving an amount ONCE! Where has all this money gone to?
>
>Why would the interface ever ask for a weekly donation? Who donates weekly?
>
>Is there anything we can do about this? Any way I can recover some of this money? 

I think a better way to address this will be to adopt a more normal donation interface, via https://github.com/gratipay/gratipay.com/issues/3862.

**Comment by whit537** [comment]
Sorry, #3862 is less relevant here than #5. Both together would be part of a "normalized" giving interface.

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
