### ISSUE TITLE
Make /about/ecosystem page

### ISSUE THREAD

**Issue by patcon** [gratipay/gratipay.com#1828]
The thought was that we should help frame gittip as an **ecosystem**, and do our best to showcase when contributors either:
a) integrate gittip into libraries or components (ie. dev tools), or
b) leverage gittip within external services (think hosted web apps)

Developers can use (a), and end-users can easily use (b). It would strike me as important to make the distinction between these two types of offerings in the ecosystem. (b) has likely placed some big bets on the future of gittip, and so it would be great to reward them with the right sort of attention within the right audience. Also, those who create (b) services are those who are among are most passionate users, as we're the thing that they've invested BST (blood/sweat/tears), and their product hinges on ours :)

cc: @balupton has done thinking about "ecosystems" for the docpad project, so you might be interested in how this develops
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
