### ISSUE TITLE
Gittip iPhone app using in-app purchases

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#183]
Floated on [HN](http://news.ycombinator.com/item?id=4283375). Don't 100% understand the flow yet.
##

**Comment by nobodxbodon** [comment]
Re-ticketed to https://github.com/gratipay/inside.gratipay.com/issues/974 for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.
