### ISSUE TITLE
Create tutorial for new Gittip Developers

### ISSUE THREAD

**Issue by abnor** [gratipay/gratipay.com#1846]
We need a proper tutorial on what programming environment and programs/files/software that each new developer for Gittip will use to more easily integrate with.

So far the list of software needed to program in Gittip includes:

Windows:
Github
Git Shell
Git
Vagrant
Virtual Box

Macs:
???

Linux:

??? (Help me out here guys)
python
gcc
make
postgres server
##

**Comment by nobodxbodon** [comment]
Merged with "Lower the barrier for hacking on Gratipay" #2927
