### ISSUE TITLE
Get our TOS rated by TOS;DR

### ISSUE THREAD

**Issue by colindean** [gratipay/gratipay.com#1898]
[Terms of Service; Didn't Read](http://tosdr.org) is 

> a user rights initiative to rate and label website terms & privacy policies, from very good Class A to very bad Class E.

I think it would be a good step to have our [Terms](https://www.gittip.com/about/terms/) reviewed by this peer-reviewed body.

Their [Get Involved](http://tosdr.org/get-involved.html) section contains information on how to submit for review.
##

**Comment by mattbk** [comment]
This is something we could try again with #4117.

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃

**Comment by colindean** [comment]
Interestingly enough, Gratipay was just added a week ago: https://github.com/tosdr/tosback2/commit/107471c9669c54d62911154a165f15bb1188255e
