### ISSUE TITLE
Prevent abuse of the leaderboards, possibly remove them entirely

### ISSUE THREAD

**Issue by seanlinsley** [gratipay/gratipay.com#1928]
@galuszkak and I were able to do this, ostensibly because we have credit cards attached.

<img width=30%" src="https://f.cloud.github.com/assets/688886/1948712/f9b3e67c-80a7-11e3-97b3-7291f97daa1c.png"/>

This ticket is here to theorize about the possible ways users could abuse the statistics we provide, both on leaderboards and on profile pages.

[IRC](https://botbot.me/freenode/gittip/msg/9944897/)

**Comment by whit537** [comment]
After landing #3281 we could address this ticket by tracking giving amounts from the previous payday separately from the upcoming payday, and including both columns in the new explore table from over there.

**Comment by whit537** [comment]
Leaderboards are gone.
