### ISSUE TITLE
Events and data in Gittip

### ISSUE THREAD

**Issue by bruceadams** [gratipay/gratipay.com#1939]
A bunch of thoughts about how we can and should be handling data.
### Change tip

We have a new tip amount and two identities: the giver and the
recipient. The recipient may be place holder, when the recipient is
not currently associated with a Gittip user. At tip change time, the
giver has a clear authenticated Gittip login. (They may not have funds
behind their tip, but we're not worried about funding in this
discussion.) (The Gittip code calls these tipper and tippee. I find
these two words dangerously similar to read, especially in code. I'll
stick to giver and recipient.)

| Recipient | Record |
| --- | --- |
| not associated | service & remote-identity-name |
| associated | immutable Gittip user id |
### Establish identity

That is: successful OAuth with a Gittip supported OAuth provider.

There are several possible contexts for "establish identity".
- Login status
  1. not logged into Gittip
  2. already logged into Gittip
- OAuth identity
  1. has never been authenticated to Gittip
  2. is associated with a Gittip user
  3. was associated with a Gittip user, but has been detached

| _OAuth state_ | not logged in | already logged in |
| --- | --- | --- |
| **unknown** | ask: opt in? | ask: add association? |
| **associated** | simple login | ask: merge accounts? |
| **detached** | ask: opt in? | ask: add association? |
### Detach identity

A logged in Gittip user can dissociate from any OAuth identity they
have previously associated with. Similarly, the Gittip system can
dissociate any Gittip user from an OAuth identity that no longer
exists (for example: a Twitter identity that has been removed from
Twitter).

There is an edge case here. When a Gittip user has no associated
identities, the Gittip user is deactivated. No future tips, incoming
or outgoing, will involve this user. The user name is now available to
be reused by a new Gittip user. Historical references to the user will
be displayed in some way that indicates that the user is deactivated,
such as ~~strike through~~. Historical references can be followed to
the deactivated user's profile page. Little information is shown on
the profile page. Whatever statement the user made in the past is no
longer shown. (An old statement may now be inappropriate and no-one
can authenticate to edit it.) Gittip administrators can see tipping
history for the deactivated user.
### Financial connection

Such as credit card, debit card, bank account, PayPal or Venmo.

A Gittip user can connect, disconnect, replace a connection with any
Gittip supported financial service whenever they like. We need to ask
the user where they want funds to come into Gittip from and where they
want payouts to go to. (Currently, this isn't much of a question.
Money only comes in from credit cards or special one-shot funding and
money goes out to a bank account, if one is available. With no bank
account, we support pay out via PayPal and special one-shot
payouts (mostly BitCoin).)

Financial connections only have meaning for an activated Gittip user.
When a Gittip user is deactivated, all financial connections are
dropped for that user.
### Combinations

The tricky parts come from combining some of the basic actions
outlined above. What happens when an existing user adds an OAuth
association, and there are pending tips to that username on that OAuth
service? Even more complex, what happens when a Gittip user merges
with another Gittip user? Both of the users being combined may
independently have "changing the world" statements, incoming tips,
outgoing tips and multiple financial connections.
#### Associate with an unclaimed OAuth identity

Watching support requests come in, a common request for detaching from
an OAuth provider comes from a user who has multiple Twitter accounts
and mistakenly associates with the wrong one. When we provide
self-service, I expect a common user sequence to be:
1. associate with Twitter user _myBot_
2. detach from Twitter user _myBot_
3. associate with Twitter user _mySelf_

in fairly quick succession. We should support this sequence in such a
way that it has no visible side effects on _myBot_. Specifically, if
there are pending tips to _myBot_ they should remain pending tips to
_myBot_, not get switched to a Gittip user who didn't really intend to
make that association.

There is a potential security issue in this area. If someone gathers
login information to many identities for one of our OAuth providers,
they could quickly roll through associating a single Gittip user with
each of those identities. If we immediately switch pending tips to
that Gittip user, they could setup to collect tips intended for many
users. Adding a delay, where pending tips remain pending for a while,
helps avoid this scenario.

So, I am proposing continue to carry pending tips that were setup as
pending tips. The key question is: for how long? When, if ever, does
the tip switch from tied to the OAuth identity to being tied directly
to the Gittip user? I see two likely change points. An obvious one is
when the giver changes the tip. At that point the tip is being
directed to the Gittip user, not a user on Twitter, GitHub, or
wherever. A sooner, and maybe better time, is the instant we make a
transfer based on the tip. Transfers are definitely between Gittip
users. Once money has moved from user-to-user, there is some sense in
updating the tip to be user-to-user.
#### Merge Gittip user accounts

This is a hard problem.
##### What happens to the Gittip user ids?

Does one Gittip user live on with the other being deactivated?
##### Rewriting history !?

What do givers see in their history? From an giver point of view, a
combination looks just like an account rename, except for one case.
The recipient username in their history changes.

An uncomfortable case is a single giver who is giving to both of the
users being combined. Do we combine the tips? The giver is very likely
to notice. (Such as: "The maximum tip I've ever given is $2; where did
this $4 tip come from?") Do we pick the larger tip and drop the lower
one? The person combining users is likely to notice this; their total
receipts will go down.

How do we handle that in the data? A display name isn't a big deal; we
already support name changes. Actual tipping history isn't something I
want to mess with. History is history. Even though the users can't see
it, I'll be much more comfortable retaining the information that older
tips were going to two separate users.

Maybe both Gittip users remain alive, as aliases for each other. Erg.
Sounds risky. We could end up with weird bugs that only occur with
these combined users.

Maybe we have a special class of deactivated user, where the display
name of the deactivated user is the display name of its take-over user
and clicking on the deactivated user (in a giver's history) navigates
to the take-over user.

The history for the giver who gave to both of the combined users would
show the same recipient name twice for each payday. This isn't likely
to inspire confidence for the giver.
##### Combining financial connections

Then there are financial connections. At combine time, we need to ask
the user which financial connections to release, for any where there
are conflicts.
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
