### ISSUE TITLE
automate bitcoin payouts

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#1960]
Right now we're doing bitcoin payouts manually in response to user requests to support@gittip.com. We're starting to see enough of these requests that we should consider automating it via the Coinbase API (the user doesn't need to know or care that we're using Coinbase).

The twist is that Coinbase doesn't give us an API to buy BTC given a USD price. We have to check the price and then buy the BTC in two separate API calls, and the amount can and does shift in between those calls. So there's some fudge.

Here's the basic flow:

 - Check the price: https://coinbase.com/api/doc/1.0/prices/buy.html
 - Buy some BTC: https://coinbase.com/api/doc/1.0/buys/create.html
 - Send BTC: https://coinbase.com/api/doc/1.0/transactions/send_money.html

Unlike PayPal, we should fully automate this as part of the payout loop of payday.

**Comment by whit537** [comment]
+1 https://gratipay.freshdesk.com/helpdesk/tickets/1688

**Comment by sim6** [comment]
If I understood correctly, no more bitcoins in gratipay, so I'm going to close this issue. More info at https://github.com/gratipay/inside.gratipay.com/issues/201#issuecomment-102010517

**Comment by sim6** [comment]
I cannot close it, I am out of gratipay :(

**Comment by whit537** [comment]
> I cannot close it, I am out of gratipay :(

A bug! :-)

Invite resent ...

**Comment by sim6** [comment]
Thanks!

**Comment by whit537** [comment]
:-)
