### ISSUE TITLE
Allow sending of short, personal messages with tips

### ISSUE THREAD

**Issue by pjf** [gratipay/gratipay.com#2011]
I'm delighted that I have _two_ whole people sending me tips. However I don't know why. It could be my efforts in maintaining Dwarf Fortress mods, or my writing about science, or my public speaking, or my software development, or photography, or just because they like me. If people are giving me tips then I'd like to continue working on things they like.

It'd be great to have a "why are you tipping this person" field, that gets copied over as a transaction note (ie, you both can see it). It doesn't mean you know who the tip came from (although I guess someone could stick their name there), but it means they can write "Love your photos", or "Great work on exobrain", or whatever it is they wish to share (which could be nothing).

One could potentially allow this to be pre-filled (eg, with a URL from the referring page). Flattr does this, so recipients know what people are flattring them for. One could even include GET parameters to provide a suggested message.  (eg: https://gittip.com/pjf?for=photography)
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
