### ISSUE TITLE
Add webhook support (specifically "receiving_amount")

### ISSUE THREAD

**Issue by pjf** [gratipay/gratipay.com#2013]
Original issue title: Fire callback on change in receiving amount

---

Right now it looks like the only way I can tell if my tipping amount has changed is to go to the gittip website and check. It looks like there's also an API but I have to poll that to see if anything has changed.

I would love a simple, machine-friendly callback, that fires when the tipping amount changes. Let the user specify (in their 'advanced' settings) a URL to which we POST a chunk of JSON to when their receiving amount changes. I suggest it just contains:
- timestamp (seconds from the epoch)
- gittip user ID
- previous receiving amount
- new receiving amount
- transaction note (if #2011 is implemented)
- digital signature (optional, but means we can verify it's gittip making the callback)

One could generalise this ticket to trigger a callback when either the sending or receiving amount changes (in which case the above packet should have sending fields added).

This change would allow for easier creation of gateways into third-party message systems, and would allow advanced users to trigger their own events upon status changes. (I can hook callbacks into my exobrain system, which would give me gittip notifications going straight to my Pebble watch.)

These would be the gittip equivalent of what github does with [post receive hooks](https://help.github.com/articles/post-receive-hooks).
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
