### ISSUE TITLE
Add ability to A/B test features

### ISSUE THREAD

**Issue by patcon** [gratipay/gratipay.com#2060]
Reading through #2052 and #2053, thinking that it would be great to have real data on all the little decisions being made on UI and copy. Would be great to understand how callouts and [little changes](https://github.com/gittip/www.gittip.com/pull/2053#issuecomment-35589678) might affect conversion on the real things we care about :)

This seems to be the only platform-agnostic library out there:
https://pypi.python.org/pypi/swab

keywords: multivariate, split
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
