### ISSUE TITLE
balanced_customer_href is corrupted

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#2085]
https://www.gittip.com/autogato/ has a bad link to Balanced.
https://www.gittip.com/matt-lowe/ has a good link (so the problem isn't universal).

Discovered during #2084. Is this a regression from #1369? Or from #2056? Or ... ?

If the `balanced_customer_href` is bad then we're going to have API failures during payday. And that's bad. Three stars!

**Comment by Changaco** [comment]
Done in #3286.
