### ISSUE TITLE
pledge model for raising funding

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#209]
@cmbeelby suggests somehow supporting the pledge model where users can set a timeframe to raise weekly support per their funding goal, or all the tips revert to zero. There might be some merit to this. How could it be done as an addition over the base slow buildup model?
##

**Comment by nobodxbodon** [comment]
Merging [Team funding goals](https://github.com/gratipay/gratipay.com/issues/3057)

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
