### ISSUE TITLE
vault cards redundantly

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#210]
We can't afford to [lose cards](http://blog.gittip.com/post/25565694263/how-not-to-get-acquired) again. Can we vault with [SpreedlyCore](https://spreedlycore.com/) *and* Balanced?

Need to figure out both information flow and how Gittip would include this in pricing.

**Comment by whit537** [comment]
Reopening in light of [Balanced shutting down](http://blog.balancedpayments.com/shutting-down/).

**Comment by whit537** [comment]
I've read https://spreedly.com/files/spreedly-business-case.pdf and have created an account.

**Comment by whit537** [comment]
Looking at [pricing](https://spreedly.com/pricing/), we can fit in the $99/mo plan to start. That gives us 5,000 vaulted cards and 5,000 transactions per month. We have 3,052 working cards on file, and we do about 4,750 charges per month. Pricing increases linearly in $100 increments up to 45,000 cards and transactions per month.

**Comment by whit537** [comment]
I've set up a test environment on Spreedly.

**Comment by whit537** [comment]
Looks like there is [no official Python library](https://docs.spreedly.com/resources/apps-libs/), though are several unofficial ones:

https://github.com/mooballit/spreedly-core-python
https://github.com/ridgebit/python-spreedly
https://github.com/shelfworthy/python-spreedly

**Comment by whit537** [comment]
I've completed their [quick start](https://docs.spreedly.com/#quick-start) tutorial. There's a few quirks but all in all my first impression is that it's a solid API.

**Comment by whit537** [comment]
How strong is their business? How much investment have they taken and who are they competing with?

**Comment by whit537** [comment]
https://www.crunchbase.com/organization/spreedly

Funding Received: $2.2 Million in 4 Rounds from 1 Investor
Most Recent Funding: $899.7 Thousand Seed on January 22, 2015

http://blog.spreedly.com/2015/01/06/crossing-50-million-per-month/

> At Spreedly we’re challenging the status quo that a single payment stack is the right way to scale for web and mobile payments. December 2014 was our 22nd month since we [(pivoted) launched](http://blog.spreedly.com/2013/03/04/spreedly-funding-expanding-our-horizons-pivoting/) Spreedly as a service that solves for the development and data ownership/PCI challenges in digital payments and maximizes the ease with where and how you transact with your data. As the blog post title states our customers processed $50 million in credit card transactions on our platform for the month of December 2014.
> 
Many of our earliest customers took a big gamble on relying on such a small startup to help power their payments. So we want to let you know that we’re making great progress and plan to be here for a long time in the future. And better still if you’re one of those who’s been on the fence come on in the water’s fine.

**Comment by justinbenson** [comment]
A little over $2 million. We don't have any direct competition. Our
competition is say Stripe or Braintree where platforms decide whether they
want to work with one single processor or have support and flexibility for
many.

Our growth is very good/solid. We're a SaaS business so that makes life
more predictable.

**Comment by whit537** [comment]
From the FAQ on the pricing page:

>**What happens if my usage exceeds the plan that I am currently on?**
>Your service will not be interrupted. We will automatically update you to the appropriate plan for your usage.

**Comment by whit537** [comment]
@justinbenson What's your biggest challenge right now as a company?

**Comment by whit537** [comment]
Here's their GitHub: https://github.com/spreedly.

**Comment by justinbenson** [comment]
Awareness. We're coming at payments differently. Just focused on APIs and
PCI and not trying to be the processor/independence there for our clients.
So people don't know how to view us.

**Comment by whit537** [comment]
Having had to move gateways three times now, your value prop is clear to us. One thing I'm not seeing is pay*ins*. We're a marketplace and need to do ACH debits in addition to charging cards. Do you do that and I'm missing it? If not, is it on the radar?

**Comment by whit537** [comment]
Dang, sorry ... I'm not seeing pay*outs*. ;-)

**Comment by whit537** [comment]
https://twitter.com/whit537/status/583611866703728640

**Comment by whit537** [comment]
Aaaaaand I meant `s/ACH debits/ACH credits` sorry. :sheep:

**Comment by justinbenson** [comment]
We just support echecks through a few gateways today. Bigger plans but late
summer so a few months away for sure.

**Comment by whit537** [comment]
Okay. [eChecks](https://docs.spreedly.com/guides/echecks/) are still payin so I guess we solve payouts separately for now.

**Comment by whit537** [comment]
This is basically an insurance policy on our card numbers.

**Comment by whit537** [comment]
This is an expensive insurance policy. Our current highest [expense](http://inside.gratipay.com/appendices/finances) is Heroku at $90/mo (since we pass through processing fees to our users, those costs aren't equally visible to us). Cheapest option here is $99/mo. This also introduces friction, another moving part. Do we want to use the Braintree API, or the Spreedly API? We're under the gun on #3377 and I'm afraid that more moving parts means more implementation risk, slowing us down. :-(

**Comment by whit537** [comment]
> This also introduces friction, another moving part.

E.g., on https://docs.spreedly.com/payment-gateways/braintree/ I'm seeing credit card and Apply Pay as supported payment types. What about PayPal, Venmo, and Coinbase? If we work with Braintree directly we don't have the impedance mismatch.

Also, what's up with the "orange/blue" distinction? Where does that come from? I haven't seen that anywhere on Braintree yet. Is that a Spreedly distinction? What does it mean? Why?

**Comment by whit537** [comment]
> Braintree's vault (when using the "blue" API) has a top-level concept of a Customer, and Core allows limited interaction with the Customer when storing credit cards in Braintree's vault.

Another example of friction. What if we need to do more with the Customer than Spreedly allows for? This makes me nervous.

**Comment by whit537** [comment]
Making the call on this. Deciding Spreedly isn't the right move for us right now, because of cost vs. benefit, and increased implementation risk on #3377.
