### ISSUE TITLE
Gittip business contingency plan

### ISSUE THREAD

**Issue by patcon** [gratipay/gratipay.com#2114]
http://en.wikipedia.org/wiki/Contingency_plan

[IRC](https://botbot.me/freenode/gittip/msg/11656676/)

Was just thinking on what would happen to the Gittip project, a project that's even now financially supporting many people around the world in a real way, if something happened to Chad.

We should probably think on how to make Gittip Chad-getting-hit-by-a-bus-proof.

Thoughts:
1. **Make sure all critical systems are accessible by at least one other person or will be made so in the event of Chad becoming unable to lead the project.** This might include one of:
   1. Chad's wife having access to the master password of a password vault that stores credentials for all of Gittip. She should know of the expectation that she get this master password to someone, and who she should give it to. This should be something that's very easy to do and will take almost no effort on her part. Expecting her to gather information under the circumstances would be unrealistic.
   2. Some trusted member of the Gittip team having joint access to all critical accounts under normal circumstances.
   3. Use [Shamir's Secret Sharing crypto](http://en.wikipedia.org/wiki/Shamir's_Secret_Sharing) to share a key fragment for decrypting the master password to a vault, so that, for example, 4 people would need to collectively decide to gain access in order to do so. The idea is that you can trust that 4 independent people wouldn't conspire to surreptitiously decrypt the vault (ie. presumably maliciously). This seems a little over-engineered, when a non-technical solution might work, but wouldn't actually be that hard.
2. **Others should be familiar with the routine processes that Chad goes through** -- deploy, payday, PayPal payouts, Bitcoin payouts, managing Balanced, etc. (@whit537: What else am I missing?)
   1. Any measure would be greatly weakened if we didn't exercise the emergency ability regularly. We would probably want to choose a trusted person with which to alternate these routine tasks, perhaps on a weekly or monthly basis, as part of our _modus operandus_.

This is a WIP. Anything else I'm missing? Does this strike anyone as premature optimization? Be honest :)
## Action items

ie. What closes this issue?
- [ ] Rough doc of business contingency/succession plan
- [ ] Plan for actual and realistic changes to our process and way of operating, in order to make Gittip not implode in tragic circumstances. Implementation could be separate issues, but at the very least, we should know what we have to spin off into other issues.
#### Resources:

http://en.wikipedia.org/wiki/Business_continuity_planning
http://en.wikipedia.org/wiki/Succession_planning
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
