### ISSUE TITLE
Redirect FAQ to Freshdesk

### ISSUE THREAD

**Issue by patcon** [gratipay/gratipay.com#2116]
[IRC](https://botbot.me/freenode/gittip/msg/11702028/)

Now that theming the Freshdesk site is done...

http://gittip.freshdesk.com/support/solutions/folders/1000078951
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
