### ISSUE TITLE
Allow Connecting Canadian Bank Account

### ISSUE THREAD

**Issue by singpolyma** [gratipay/gratipay.com#2179]
My company (http://rippleunion.com) now has a fully-automated direct-deposit system that will work with _any_ Canadian bank account.  The limits are a bit low for now (500 CAD / day), but looking over gittip's stats, this should not be an issue for most users.  In fact, the biggest issue might be the other way -- due to fees coming from the banks our fee is currently a flat 5 CAD / transaction, which means I expect many users would need a way to only get the direct deposit after N weeks to avoid the fee?

We are gittip users and support the project, so we are willing to work with you guys to do whatever we can that makes the most sense for Canadian users, should this or other features be desirable.  We are also willing to do / help with development work so that integration goes as smoothly as possible.

This is related to #126
##

**Comment by nobodxbodon** [comment]
Re-ticketed to https://github.com/gratipay/inside.gratipay.com/issues/974 for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.
