### ISSUE TITLE
Statement tooltip doesn’t show on hybrid devices

### ISSUE THREAD

**Issue by ESWAT** [gratipay/gratipay.com#2193]
If you’re on a computer with both a mouse and touchscreen capabilities, you should still be able to see the tooltip when you hover over a card (the feature that was introduced in #2172). That’s not actually the case right now though.
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
