### ISSUE TITLE
Create script for doing credit card pay-ins of specified [large] value

### ISSUE THREAD

**Issue by patcon** [gratipay/gratipay.com#2221]
@rcross (@certifiedtorock on gittip) is international and so credit card charges are expensive. They wanted to top up for a year of tipping, but got stuck in support limbo for over a week since it's not a common request. We should create a script for this.

[IRC](https://botbot.me/freenode/gittip/msg/12839708/) | [Freskdesk ticket](http://gittip.freshdesk.com/helpdesk/tickets/62)
##

**Comment by nobodxbodon** [comment]
Re-ticketed to [support more means of payin and payout](https://github.com/gratipay/inside.gratipay.com/issues/974) for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.
