### ISSUE TITLE
Weekly heads-up email before charging

### ISSUE THREAD

**Issue by duckinator** [gratipay/gratipay.com#2224]
Reticketed from #1124:

_"If you warn me first, it might reduce chargebacks / fraud complaints / failed charges. You can put a link in the warning email back to my account so that I can immediately cancel my giving."_

Basically: we want an opt-in weekly email to send people notifications on the day before payday, informing them that we will be charging their credit card, preferably with an estimate.
##

**Comment by whit537** [comment]
+1 from Braintree on https://github.com/gratipay/gratipay.com/issues/3287.

**Comment by whit537** [comment]
E.g. from Shareable:

![screen shot 2016-01-05 at 3 12 55 pm](https://cloud.githubusercontent.com/assets/134455/12127312/825c950e-b3c4-11e5-82d8-97236067b0b7.png)

Etc. Etc. It's quite verbose.

**Comment by mattbk** [comment]
Loose +1 from support:

>Why don't you try to charge again for failed payments in the past?

This user's credit card was "processor declined." Maybe if the user was notified beforehand, this could have been rpevented?

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
