### ISSUE TITLE
Redeemables (gifts cards or coupon codes)

### ISSUE THREAD

**Issue by balupton** [gratipay/gratipay.com#2250]
EDIT: _Original title - Gift cards_
-- @patcon

---

It would be fantastic if Gittip allowed us to purchase Gift cards, that could be emailed, printed, or issued via the developer API.

This would be a great way to get the non-initiated into the community.

Such use cases could be:
- When one of us evangelises gittip to a friend, we can get them in by buying them a $20 gittip gift card. This technique is common place with bitcoin evangelists.
- We can get people gittip gift cards for their birthdays or whatever other special occasion. While this may be disgruntled by the regular joe, it's not the case for everyone, in fact a dear friend of mine @nikolayhg is working on [The Sharing Birthday Initiative](http://thesharingbirthday.github.io/) that focuses on reframing birthdays from one of taking, to one of giving, with good success.
- It would also allow some really interesting business models to arise.
  - One such example is allowing the customer direct control over where the commission/profit of a physical product actually goes. This can work by the retailer providing an online service where you enter your receipt and barcode number of the product into their online service, and the comisision/profit of the product is then given to you as a gittip gift card, that you can then distribute to whomever you pleased. This I feel is a game changer, for the purpose that vast vast majority of those whom I tell gittip about, never compute the model, however they already understand the typical value sale model. I buy a product for its perceived value, the seller gets the commission/profit, and unfortunately, I have no control of where that money goes, or who it should go to. With this change, it changes "commission/profit" into "mandatory donation" instead.
    - The actual conversations I have with those in the retail industry goes something like this: "I don't think this model of sales commission is ethical, as it is fundamentally excludes people — which retailer misses out on my commission? and which retailer gets to eat?" — "Yes... but it is still better than the pyramid scheme of Woolworths, at least, we the people, are getting the money" — "Yes, no doubt it is an improvement, though no stopping there, there is always room to aim for the best, not just what is better, perhaps, considering no one would deny the product is worth the price it is fixed at, how about, instead we give the user control of where there commission goes, to ensure they can feed all those they wish to feed with their commission. Now instead of the consumer deciding who starves and who gets to eat, dictated by who they conduct the sale with, now, when a sale is performed, the consumer can ensure all those who've given them value and who they believe in, gets to eat" — "Holy cow, that's amazing! We'd get behind that." — "Cool, I'll chat with the gittip people about it."

---

Update: I'll turn this new business model idea into a blog post instead, so it doesn't detract from the discussion about gift cards.
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
