### ISSUE TITLE
Create script to summarize and collate info on user suspiciousness

### ISSUE THREAD

**Issue by patcon** [gratipay/gratipay.com#2252]
Possible indicators to help determine whether user is flagged as suspicious:
- graph giving network (interested in all other indicators for other users on graph)
- Gittp sign-up date
- Gittip bank/CC attachment dates
- Elsewhere sign-up dates (GitHub, Twitter, etc)
- Elsewhere activity
- github ssh keys

cc: @bruceadams 
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
