### ISSUE TITLE
DB connections no longer showing up in Librato

### ISSUE THREAD

**Issue by seanlinsley** [gratipay/gratipay.com#2254]
What changed?

https://metrics.librato.com/share/dashboards/42hmoj9j?duration=8204400&source=production&end_time=1396671966

![screen shot 2014-04-04 at 11 53 14 pm](https://cloud.githubusercontent.com/assets/688886/2621955/42d30100-bc7e-11e3-9398-2dfc9a4b2acd.png)

**Comment by rohitpaulk** [comment]
Fixed, closing. 

![screenshot from 2015-02-22 18 08 24](https://cloud.githubusercontent.com/assets/3893573/6318539/dc6e3670-babd-11e4-819b-affcfc458e6f.png)
