### ISSUE TITLE
Add support for linking with Keybase

### ISSUE THREAD

**Issue by rummik** [gratipay/gratipay.com#2267]
Seems like all we need on our end is the ability to add a small bit of text on the side, similar to what we have for Bitcoin, as well as a field in public.json
##

**Comment by nobodxbodon** [comment]
Re-ticketed to [support more ways to login](https://github.com/gratipay/inside.gratipay.com/issues/983) for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.
