### ISSUE TITLE
change all passwords post-Heartbleed

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#2275]
Reticketing from #2259.

**Comment by benhc123** [comment]
Has this all been done?

**Comment by whit537** [comment]
We have some passwords in LastPass and some not in LastPass. When did we sign up for LastPass? Was that before or after Heartbleed? That would at least take care of those.

**Comment by whit537** [comment]
First LastPass payment was on May 1, 2014. Heartbleed was April 7.

**Comment by whit537** [comment]
All passwords in LastPass were changed in October at the earliest. Is that after each vendor fixed heartbleed?

 - [ ] DigitalOcean
 - [ ] Gravatar (WordPress)
 - [ ] Librato
 - [ ] Mandrill
 - [ ] MaxCDN
 - [ ] Optimizely
 - [ ] Pagerduty
 - [ ] Piwik (Account Management)
 - [ ] Piwik (Analytics Dashboard)
 - [ ] Segment.io
 - [ ] Sentry
 - [ ] Transifex
 - [ ] Typography.com
 - [ ] UptimeRobot
 - [ ] Wufoo

**Comment by whit537** [comment]
Ooh!

![screen shot 2015-03-26 at 5 09 39 pm](https://cloud.githubusercontent.com/assets/134455/6857113/ef1f9dfa-d3da-11e4-8cd0-e78fc8e31dbb.png)

**Comment by whit537** [comment]
Gah. Worthless UX. :disappointed:

**Comment by whit537** [comment]
Alright, so I guess the threat here is that a site we were using was compromised before they fixed Heartbleed, and our password was potentially stolen. We need to have changed the password after they fixed Heartbleed on any domains we login on. We can look at announcements from these services, but really we want to test the websites themselves that we provide our credentials to, and really not just the ones we provide credentials to, but any provided by the vendor (e.g., `www.librato.com` *and* `metrics.librato.com`). How deep down the rabbit hole do we go? Far enough to satisfy ourselves that we're okay.

**Comment by whit537** [comment]
Really this should turn into an exercise in collecting all of the services we use and changing the password for all of them, a manual take on https://github.com/gratipay/inside.gratipay.com/issues/159.

**Comment by whit537** [comment]
Steps:

 - [ ] Change all passwords for services stored in LastPass.
 - [ ] Enumerate all services not stored in LastPass and change passwords for them.
 - [ ] Enumerate all services for which we have API keys and change the API keys.

**Comment by whit537** [comment]
Change all passwords that are in LastPass:

 - [ ] DigitalOcean
 - [ ] Gravatar (WordPress)
 - [ ] Librato
 - [ ] Mandrill
 - [ ] MaxCDN
 - [ ] Optimizely
 - [ ] Pagerduty
 - [ ] Piwik (Account Management)
 - [ ] Piwik (Analytics Dashboard)
 - [ ] Segment.io
 - [ ] Sentry
 - [ ] Transifex
 - [ ] Typography.com
 - [ ] UptimeRobot
 - [ ] Wufoo

**Comment by whit537** [comment]
> How deep down the rabbit hole do we go?

For example, what about individual user accounts for services like GitHub or Sentry? Are we going to require them to change their passwords on those services? Is that even possible for us?

**Comment by whit537** [comment]
Not in LastPass:

 - [ ] Freshdesk
 - [ ] GitHub
 - [ ] Twitter
 - [ ] Google (Apps, Plus)
 - [ ] Facebook
 - [ ] Ally
 - [ ] Citizens
 - [ ] New Alliance
 - [ ] Balanced
 - [ ] Stripe

**Comment by whit537** [comment]
Multiple users:

 - [ ] Sentry
 - [ ] Freshdesk
 - [ ] Heroku

**Comment by whit537** [comment]
I believe I changed our WordPress.com account, but now signing in to Gravatar is broken:

https://twitter.com/whit537/status/581231371080900608

:-(

**Comment by whit537** [comment]
I believe I was able to change the Gravatar/WordPress password after all. I was able to access Gravatar and I changed the password (again?), which happens on WordPress.com. I'm now stuck in the same login loop as before. Maybe it's a cookie expiry issue or something?

**Comment by whit537** [comment]
Yeah, I can access Gravatar.

**Comment by whit537** [comment]
What should we do about accounts that have multiple users? We don't have control. For example, we can't force everyone who is a collaborator or owner on GitHub to change their GitHub passwords. Should we make an effort to get everyone to do this?

**Comment by kaguillera** [comment]
+1 We should at least try
