### ISSUE TITLE
Convert scripts into invoke tasks

### ISSUE THREAD

**Issue by patcon** [gratipay/gratipay.com#2294]
Invoke is the rake-like task-runner that was extracted out of fabric 1.x for use in fabric 2.x:
https://github.com/pyinvoke/invoke

Seemed to be support for exploring its use:
https://botbot.me/freenode/gittip/msg/13532026/

Main benefit would be a step toward testing and using shared libraries in the scripts themselves. Also, better help output.
## To Do
- [ ] masspay.py (https://github.com/gittip/www.gittip.com/issues/1630)
- [ ] snapper.py
- [ ] update-user-info.py
- [x] set-paypal-email.py (https://github.com/gittip/www.gittip.com/pull/2295)
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
