### ISSUE TITLE
Email Verification

### ISSUE THREAD

**Issue by clone1018** [gratipay/gratipay.com#2312]
We need email verification with Gittip. This Issue and associated PR's will need to handle:
- [x] Add initial mandrill support & keys (how to test?) #2313
- [x] Sending emails to all accounts on initial merge.
- [x] Send verification email on email add/change
- [x] Add new page for verifying email.
- [x] Somehow test everything above (pls help)
##

**Comment by davidak** [comment]
can i register using e-mail now?

**Comment by Changaco** [comment]
@davidak No, the "sign up with email" issue is #1052.
