### ISSUE TITLE
Pay-ins via Nochex

### ISSUE THREAD

**Issue by patcon** [gratipay/gratipay.com#2325]
https://www.nochex.com/

This was suggested in a support ticket as a way to make international pay-in easier:
http://gittip.freshdesk.com/helpdesk/tickets/68

Currently, we only offer credit cards charged in USD (with extra fees internationally), and bitcoin. However, Balanced is likely to [implement local currencies soon](https://www.balancedpayments.com/international-payments), so it might not be worth the effort for a stopgap in the meantime.

Also, I'm unclear whether, [like PayPal](https://github.com/gittip/www.gittip.com/issues/2286), Nochex would refuse to underwrite pay-ins for a marketplace website. That would need to be cleared up.
##

**Comment by nobodxbodon** [comment]
Re-ticketed to https://github.com/gratipay/inside.gratipay.com/issues/974 for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.
