### ISSUE TITLE
Use elsewhere emails

### ISSUE THREAD

**Issue by clone1018** [gratipay/gratipay.com#2330]
So currently we store 20,000 elsewhere email addresses. 

|   platform   | count |
|--------------|------- |
| github       | 19262 |
| bountysource |   633 |

Can we use these emails to somehow get almost all of our participants a valid email?

Go go ideas!

**Comment by rohitpaulk** [comment]
Copying over from https://github.com/gratipay/gratipay.com/pull/2752#discussion_r21167175:

> Should we really use elsewhere? Those emails were never given to us, at most we could send an email inviting those users to add that email to their Gratipay account, but we shouldn't just add them without asking. If we want to take emails from elsewhere accounts we should do that during sign-up. Until we do that during sign-up it doesn't make sense to do that for existing elsewhere's since we'll just start accumulating more elsewhere emails right away again (unless this PR also silently grabs elsewhere emails during sign-up, which I think we shouldn't do; we should ask).

**Comment by whit537** [comment]
We're moving away from social auth (#3837) and towards required emails (#1052). Closing.

**Comment by whit537** [comment]
#3506 is more relevant to requiring emails than #1052.
