### ISSUE TITLE
fix broken links on blog posts

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#2353]
http://www.brokenlinkcheck.com/ is helpful for finding broken links.
##

**Comment by nobodxbodon** [comment]
I suppose there's no need to maintain old blog.

**Comment by whit537** [comment]
Sure there is! We link to old blog posts from new ones regularly, and they are still indexed in search engines which means people can find that content. We should do our best to maintain those pages, imo.

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
