### ISSUE TITLE
Always keep schema.sql clean

### ISSUE THREAD

**Issue by Changaco** [gratipay/gratipay.com#2360]
The purpose of this issue is to gather opinions from other contributors. ~~What do you think about rewriting `schema.sql`?~~ *(that's done)* What do you think about changing ~~and automating~~ the use of `branch.sql` files?

From [IRC](https://botbot.me/freenode/gittip/msg/14334455/):

> \<Changaco> I've been wanting to rewrite schema.sql to only contain the current schema. New PRs would provide both the modifications to schema.sql and a branch.sql to actually make the changes in the DB. Then we could automate running branch.sql in release.sh, because it wouldn't have to be manually merged into schema.sql anymore.

> \<Changaco> Or at least rewrite schema.sql once, removing all the old stuff, to prevent problems like #2348 (we don't actually use hstore anymore, schema.sql just requires it and then drops it later).

> \<whit537> I could definitely see a periodic reset of schema.sql.
> \<whit537> I really like that we have a log of all the DDL we’ve run in production.
> \<whit537> Maybe we can archive by year?
> \<Changaco> all branch.sql files are in the git history, so no matter what we still have a log, it's just harder to read if you don't have the proper tool

> \<whit537> I’m not convinced that automating branch.sql in production is ideal.
> \<whit537> I’ll let you and others make that decision. :-)

**Comment by Changaco** [comment]
[IRC](https://botbot.me/freenode/gratipay/2015-01-22/?msg=30233695&page=2)

**Comment by whit537** [comment]
My concern is schema drift. I want to protect against a situation where production varies in any unintentional way from the result of running schema.sql to create a clean dev/test db. It seems like we could automate that check and perform it either during CI or release.

**Comment by whit537** [comment]
The reason I want to avoid schema drift is because schema drift would be a source of bugs.

**Comment by Changaco** [comment]
I see two possible solutions to avoid schema drift:

- keep editing `schema.sql` manually but automatically diff the results of `pg_dump -sO`
- generate `schema.sql` automatically from the production DB (requires finding or writing a tool designed to do that)

**Comment by whit537** [comment]
@Changaco I'd be fine with either of those approaches.

**Comment by techtonik** [comment]
`generate schema.sql automatically from the production DB (requires finding or writing a tool designed to do that)` - https://github.com/catherinedevlin/ddl-generator

**Comment by Changaco** [comment]
ddl-generator isn't what we're looking for, we don't want to guess the schema, we want to dump it from the DB in a "pretty" format.
