### ISSUE TITLE
Provide ability to embed static images

### ISSUE THREAD

**Issue by myano** [gratipay/gratipay.com#237]
Provide the ability for users to embed static images on their site, in addition to the current system. This would allow users to download the static image and serve it on their site from their server but allow the image to link back to gittip.com. This would allow site administrators to limit calls to external sites when their page loads (decrease load time and increase privacy of visitors).
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
