### ISSUE TITLE
Let people do their own paypal config

### ISSUE THREAD

**Issue by pjf** [gratipay/gratipay.com#2387]
This is one of our most common support requests. It shouldn't be. As far as I can tell, doing a paypal setup is just setting a field in the database, because that's what's done by the script run by support monkeys like myself.

This is something users *should* be able to do from their own user page. It shouldn't involve a support request at all.

Relevant discussions: #2177 (my stumbling to do paypal changes), and #2125 (Fraud HOWTO, where I'll discuss the fraud implications).

**Comment by whit537** [comment]
Especially with our new terms of service (#3408), I think it's time to implement this. We've been using PayPal without incident for years now, and Patreon does, too.

**Comment by rohitpaulk** [comment]
Most of the sites I've dealt with require PayPal emails to be verified emails on the platform. I'm proceeding with the same here, objections?

**Comment by whit537** [comment]
No objections, that sounds good to me.

**Comment by whit537** [comment]
Done in #3462.
