### ISSUE TITLE
Allow users to manually trigger a refresh of their elsewhere accounts

### ISSUE THREAD

**Issue by Changaco** [gratipay/gratipay.com#2393]
This would avoid issues like #2392. It's not a replacement for #900 which would still be needed to refresh inactive users.

We should throttle the refresh to prevent a user from exhausting our quotas of API calls.
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
