### ISSUE TITLE
Document the /about/me/* generic links

### ISSUE THREAD

**Issue by szabgab** [gratipay/gratipay.com#2394]
I'd like to be able to link to the "account" page of the currently logged in user. For example to write sentence like: "You can get the API key from your <a href="">account</a>"

Currently I think I can only link to https://www.gittip.com/USERNAME/account

Would it be possible to add a set of URLs such as
https://www.gittip.com/my/account
that would either show the data of the currently logged in user or redirect to it?
So that linking to that page would work for every logged in user and would show some nice explanation to visitors who are not currently logged in.
##

**Comment by mattbk** [comment]
This is listed at http://inside.gratipay.com/howto/support-users.

**Comment by whit537** [comment]
@mattbk That's internal documentation for support staff. I'm not sure yet where to put this for users.

**Comment by mattbk** [comment]
New page under https://gratipay.com/about/features/?  I don't know what else would go on such a page.  The website copy still mostly describes Gratipay 1.0 (https://github.com/gratipay/gratipay.com/issues/3398).

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
