### ISSUE TITLE
Reword "Hide total giving from others."

### ISSUE THREAD

**Issue by szabgab** [gratipay/gratipay.com#2396]
My account has "Hide total giving from others. " and "Hide total receiving from others."

Shouldn't the former be "Hide total receiving from others. "

s/giving/receiving/   ?

**Comment by techtonik** [comment]
> That might make it more clear to non-native English speakers, but for native English speakers adding quotes would imply that there's something untrustworthy or abnormal about "total receiving".

I am -1 on adding quotes for exactly the same reason.

**Comment by kzisme** [comment]
I disliked the quotes ,but I am a native English speaker.  

The quotes make it seem untrustworthy ie: https://github.com/gratipay/gratipay.com/issues/2396#issuecomment-43109971

I'm open to anything that makes it most clear.

**Comment by techtonik** [comment]
@kzisme so let's drop the quotes and use "Hide total giving to others." As a non-native English speaker I find it pretty clear.

To further improve the UX, there could be a link to a page where those totals are described, so a person can check how the setting works.
