### ISSUE TITLE
Annual prepayment plans (or once-a-week donations are *really* beancounter-unfriendly)

### ISSUE THREAD

**Issue by ribasushi** [gratipay/gratipay.com#2401]
As part of the push to get more companies participating in my community an interesting problem popped up. While a CTO or someone equally up-high is really interested in giving back to the people they depend on, the extra _weekly_ lineitem on the company books makes accountants cling to guns and stuff. This makes it a harder sell for a business as a whole, which is problematic.

On the other hand the once-a-week _payout_ is just the right balance for receiver sustainability, so upsetting that would be a step backwards.

Thus the only practical thing to keep everything smooth seems to be an introduction of an account-prepayment service. Gittip already has the infrastructure for this internally, all that would be needed is to expose things for donors-to-be.

A lot of details are up in the air of course:
- Could this encourage fire-and-forget donations undermining the sustainability principle?
- Is going less than annual wise? Perhaps 6/months?
- Is there a legal ramification of becoming an explicit escrow (as opposed to the implicit escrow gittip is today)
- other stuff I can't think of

Thoughts?
##

**Comment by whit537** [comment]
Folding this into https://github.com/gratipay/gratipay.com/issues/113.
