### ISSUE TITLE
/foobar/tips.json should return proper error messages

### ISSUE THREAD

**Issue by szabgab** [gratipay/gratipay.com#2410]
curl https://www.gittip.com/foobar/tips.json 

curl https://www.gittip.com/foobar/tip -u abc:     (invalid API_KEY)

Basically every error just returns ~~`*sigh*`~~ (Edit by @Changaco: we now return an empty body)

Could it return some more specific error message?
##

**Comment by nobodxbodon** [comment]
Consider obsolete.
