### ISSUE TITLE
log additional information in exchanges

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#2443]
When we move money between Gittip and the outside world we call that an "exchange" and we record each such event in the `exchanges` table. Here's its schema:

```
=> \d exchanges
                                     Table "public.exchanges"
┌─────────────┬──────────────────────────┬────────────────────────────────────────────────────────┐
│   Column    │           Type           │                       Modifiers                        │
├─────────────┼──────────────────────────┼────────────────────────────────────────────────────────┤
│ id          │ integer                  │ not null default nextval('exchanges_id_seq'::regclass) │
│ timestamp   │ timestamp with time zone │ not null default now()                                 │
│ amount      │ numeric(35,2)            │ not null                                               │
│ fee         │ numeric(35,2)            │ not null                                               │
│ participant │ text                     │ not null                                               │
│ recorder    │ text                     │                                                        │
│ note        │ text                     │                                                        │
└─────────────┴──────────────────────────┴────────────────────────────────────────────────────────┘
Indexes:
    "exchanges_pkey" PRIMARY KEY, btree (id)
Foreign-key constraints:
    "exchanges_participant_fkey" FOREIGN KEY (participant) REFERENCES participants(username) ON UPDATE CASCADE ON DELETE RESTRICT
    "exchanges_recorder_fkey" FOREIGN KEY (recorder) REFERENCES participants(username) ON UPDATE CASCADE ON DELETE RESTRICT
```

The relationship between amount and fee is complicated and should be cleaned up. That's #2442.

The `recorder` and `note` fields are used when an admin [manually enters an exchange](https://github.com/gittip/www.gittip.com/blob/6c5a9742ef2adfef235c924701ed61c1e001c955/www/%25username/history/record-an-exchange.spt).

What we need here is more information recorded during an exchange in order to aid debugging, e.g. on #2372. Exchanges involve API calls to Balanced (etc.). We should record detailed information about what API call was made and what the result was. We should also record what funding instrument was involved so that whether or not there is a failure we can make our reporting more accurate (#1681).

**Comment by Changaco** [comment]
Added to the [Balanced shutdown](https://github.com/gratipay/gratipay.com/milestones/Balanced%20shutdown) milestone.

**Comment by whit537** [comment]
> if we're comfortable trusting Balanced as our datastore

:disappointed:

**Comment by whit537** [comment]
> If we want to fix those we'll have to do lots of Balanced API queries to retrieve the information.

I downloaded all transactions in JSON format on https://github.com/gratipay/inside.gratipay.com/issues/308 and uploaded them to https://github.com/gratipay/logs/tree/master/misc/308/raw/balanced/transactions.

**Comment by whit537** [comment]
> We should also record what funding instrument was involved so that whether or not there is a failure we can make our reporting more accurate (#1681).

That's the `route` column, which we have now and need to use properly in #3839, which is blocked on #2779, which is blocked on #3822.

> What we need here is more information recorded during an exchange in order to aid debugging, e.g. on #2372. Exchanges involve API calls to Balanced (etc.). We should record detailed information about what API call was made and what the result was.

This is the new `ref` column that was added in #3810 and should be cleaned up alongside `route`.

Closing this as done with `ref`.
