### ISSUE TITLE
What does Gittip need from Regard?

### ISSUE THREAD

**Issue by eneiand** [gratipay/gratipay.com#2445]
Following on from the discussion we had last week with @whit537, @patcon and @duckinator (https://www.youtube.com/watch?v=s9ZetS4eyrg) I would like to open the topic of how we at Regard can implement a product that makes you guys and your users happy.

We are creating an analytics product that is:
- open
- transparent
- respectful of users
- useful

We're achieving these aims by:
- building the product in the open (www.github.com/with-regard)
- giving users the ability to view/delete any data they contribute at any time
- encouraging developers to only collect what they need

Here are a couple of designs where we've added Regard to our own fork of Adobe Brackets to give you an idea of what we're doing.

![regard brackets extension load time](https://cloud.githubusercontent.com/assets/553033/3117426/b8a07498-e72c-11e3-8d32-bdf8075bbe82.jpg)
![regard brackets extensions by user](https://cloud.githubusercontent.com/assets/553033/3117425/b89fda7e-e72c-11e3-97f4-5dce102b2573.jpg)

So what sort of data would you want to collect using Regard and why?

**Comment by rohitpaulk** [comment]
Doesn't look like this is active anymore, closing.
