### ISSUE TITLE
list Gittip staff on community pages

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#2452]
This idea grew out of a conversation about user advocates [over on BG](https://github.com/gittip/building.gittip.com/issues/56). Rather than making "user advocate" a special role, we decided in [IRC](https://botbot.me/freenode/gittip/2014-06-02/?msg=15528253&page=2) to add a listing of Gittip staff to community pages and then train *all* Gittip staff on proper handling of user feedback (consent! + education re: open source). The listing on the community pages will say something like, “Here are Gittip Staff members from this community. If you have feedback on or problems with Gittip please get in touch!”

**Comment by mattbk** [comment]
Closing until community pages ([or tags](https://github.com/gratipay/gratipay.com/issues/3127)) return
