### ISSUE TITLE
Idea - Gratipay Project Funds

### ISSUE THREAD

**Issue by andychase** [gratipay/gratipay.com#2455]
(This idea may have been suggested before, it seems obvious)

What if you want to be more specific about why you are giving to someone?

Gittip users could select repositories from their github account to be added to their profile. People could choose to give to the person, or give various amounts through one or more of their projects. People could add arbitrary projects if their projects aren't on Gittip or computers in general.

It would work the same way as it does now-- the money goes all together to the person with no strings attached-- Gittip would just keep track of the different projects amounts as form of communication (i.e. I'm giving to you weekly because I like that you are doing this).

If a recipient removed a project later, the weekly amount would simply roll into that person's basic weekly amount (instead of it going away, so people aren't afraid to remove projects).

12-second basic mockup maybe to help explain it: 

![idea](https://cloud.githubusercontent.com/assets/2470152/3170766/ac2b011c-ebbc-11e3-8d01-38d6ec2f1c46.png)

**Comment by whit537** [comment]
This is moot with the shift to [Gratipay 2.0](https://gratipay.news/gratipay-2-0-2453d3c53077), since we've moved away from no-strings-attached gifts to individuals in favor of payments to "Teams" (organizations) in view of specific products or services they provide.
