### ISSUE TITLE
Clarify what DNT means for Gravatar, Twitter, etc.

### ISSUE THREAD

**Issue by xnyhps** [gratipay/gratipay.com#2460]
https://www.gittip.com/about/dnt.html says:

> Gittip supports DNT. Enabling your browser's DNT settings ensures that Gittip will disable any use of third-party analytics services.

But with DNT enabled Gittip will still try to load images from Twitter and Gravatar (and maybe more I don't know about). Maybe these sites respect DNT (I haven't checked), but the page should mention that they _might_ track you.

I also think it's ironic you only exclude _thid-party_ analytics services, but don't say anything about how you change your own tracking. :)
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
