### ISSUE TITLE
Comply with EFF's DNT policy v0.1

### ISSUE THREAD

**Issue by patcon** [gratipay/gratipay.com#2461]
https://www.eff.org/dnt-policy

Seems pretty comprehensive, and might be a bit of work to get up to code. Just creating a stub for now so we don't lose it. [[IRC]](https://botbot.me/freenode/gittip/2014-06-04/?msg=15654625&page=2)

cc: @xnyhps @Changaco @ivanmushketyk
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
