### ISSUE TITLE
Add "website" profile field

### ISSUE THREAD

**Issue by aaronpk** [gratipay/gratipay.com#2477]
In addition to being able to link to my Twitter or Github profiles, I should be able to link to my own website. 

The link should include rel=me, so that it is possible to use Gittip as an authentication provider for https://indieauth.com/
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
