### ISSUE TITLE
Prevent failures during and after release

### ISSUE THREAD

**Issue by Changaco** [gratipay/gratipay.com#2487]
Yesterday we had trouble when deploying #2451 and #2485. Here's what happened:

After manually adding the content of `branch.sql` to `schema.sql`, I ran the following command:

`heroku pg:psql -a gittip <branch.sql && git rm branch.sql && git add schema.sql && git commit -m 'merge branch.sql into schema.sql' && git push && ./release.sh 13.1.6`

The two changes that ended up causing failures are:

1. The `branch.sql` from #2485 that I applied before running `release.sh`. Doing so shouldn't have caused any problem because the SQL only added a column to a table, which is a retro-compatible change. Unfortunately there's a bug in the libraries we use to interact with Postgresql, so most (if not all) HTTP requests failed in the time between the application of `branch.sql` and the completion of `release.sh`.
2. The `TESTING` environment created by #2451. I forgot to add it on Heroku, so `release.sh` worked but the newly deployed app crashed immediately.

The solutions are:

- [ ] Fix https://github.com/gittip/postgres.py/issues/26.
- [x] Add a pre-deployment check to ensure that the Heroku env contains all the required variables. We can probably add that easily in `release.sh`.

**Comment by rohitpaulk** [comment]
https://github.com/gratipay/postgres.py/issues/26 is fixed, closing this.
