### ISSUE TITLE
Fix fundamental perception lapse wrt "business like any other"

### ISSUE THREAD

**Issue by ribasushi** [gratipay/gratipay.com#2515]
Gittip has a problem - it's main point of innovation (i.e. being the first open company) is being utterly overshadowed by a discussion about "who is Gittip for". I find this doubly perplexing because this is an answered question - Gittip is for everybody. There are no background checks, there is no way for a 3rd party to take away someones funding, and there is no precedent of anyone with database keys altering non-fraudulent accounts.

So I want to carve a little brainpower towards the question I consider of utmost importance: How does one fix the main perception issue, namely so that statements like this stop popping up: https://twitter.com/XaiaX/status/479819234059366400 ?

**Comment by ribasushi** [comment]
Sorry for dropping this off my radar. It is hard to distill how this issue applies to GP2.0 while the transition is underway. Thus closing the current ticket, maybe will reopen it differently someday.

Cheers!

**Comment by whit537** [comment]
!m @ribasushi :-)
