### ISSUE TITLE
Email updates to givers

### ISSUE THREAD

**Issue by ericmeltzer** [gratipay/gratipay.com#2521]
My absolute favorite thing about Kickstarter, Watsi, DonorsChoose etc is getting updates from the people I donated to about what they're doing w/ my donation. A tool that would allow people I donate to on Gittip to send me messages about what they're doing would be AMAZING!

From IRC discussion it sounds like we don't have a way to contact all users of gittip, depending on what service they used to register. A minimal but useful solution to this issue would be to be able to contact all donors who ARE contactable (i.e. those who reg'd with twitter?)
##

**Comment by whit537** [comment]
+1 [IRC](https://botbot.me/freenode/gratipay/2015-04-01/?msg=35587253&page=1)

**Comment by mattbk** [comment]
> There is a sane reason not to grow Gratipay into yet another social network. It is assumed that communication with people already happens through their preferred channels. If people can not get in touch with their supporters, that's not a fault of GP.
>Gratipay could provide some support for microblogging, for messaging, for status updates, but that needs to be really well thought of.

I agree with this.  One of the best things about Gratipay is that it's focused on work, not on requiring all sorts of updates for givers.  In my mind the point is to help build a community around each team--and communities already have better ways of interacting with each other than something Gratipay could provide.  If you're donating to a team, you ought to already be on their email list for updates.

**Comment by whit537** [comment]
@tswast at https://github.com/gratipay/gratipay.com/issues/236#issuecomment-274930973:

> A backer update tool could be used to share patreon-like rewards with donors.

**Comment by whit537** [comment]
+1 from a representative of a [top-25](https://en.wikipedia.org/wiki/List_of_largest_Internet_companies) Internet company:

> We seek to measure the impact of our support. This helps us report back to the people with budget and show how their investment in support is paying off. It's one thing to give a developer $5K, it's another to show the impact metric resulting from it. This part is tricky since we're not looking to hire open source projects to do "work for hire" or fix specific bugs. Rather, think of how we invest in non-profits in the charity space -- we ask to measure impact to see things like "how many clients served" or "given this funding level, we can complete project X."

**Comment by whit537** [comment]
HackerOne has a great implementation of this, for reference.

![screen shot 2017-06-17 at 8 36 49 am](https://user-images.githubusercontent.com/134455/27252954-214ff9ee-5338-11e7-8113-10d86b31a94c.png)

**Comment by whit537** [comment]
Folding https://github.com/gratipay/inside.gratipay.com/issues/1172 into this.

E.g.

![my-impact-journey-began](https://user-images.githubusercontent.com/134455/30859579-54085cc4-a292-11e7-9354-35d8e26b282f.png)

> [Here's an example](https://my.charitywater.org/p/myprojectsview?project_id=ET.GOH.Q4.13.156.150) of the report you'll receive when the project is ready.
