### ISSUE TITLE
Make the Project Members page show faces!

### ISSUE THREAD

**Issue by ericmeltzer** [gratipay/gratipay.com#2523]
I think the members tab of teams pages should show the headshots of all team members. The current display (list of names w/ takes) could be moved to a tab called Payrolls, mockup here: 

![](http://imgur.com/bkMzCad.png)

Alternatively we could get rid of the 2-3 tabs (Profile, Members, Payroll) and just put everything in one long page. I think that's the best way to do it.
![](http://imgur.com/egOt4wz.png)

Besides just being a visually nice thing to have, faces on teams pages are **useful for when members of a team (especially the Gittip team) need to talk to the outside world**. If we can point to the team page when we tell a vendor, supplier, partner or whoever that we're representing Gittip and they can see our faces on that page, that's WAY better than seeing our username (which isn't even our real name in some cases) in a small grey font with a bunch of numbers next to it :)
##

**Comment by mattbk** [comment]
Still applicable under Gratipay 2.0.

**Comment by mattbk** [comment]
This list is currently under https://gratipay.com/Gratipay/distributing/...
