### ISSUE TITLE
Publish diversity stats for the Gittip team

### ISSUE THREAD

**Issue by seanlinsley** [gratipay/gratipay.com#2525]
While quite a few people from minorities left and are leaving because of recent events, this sort of thing would still be useful.

https://twitter.com/hypatiadotca/status/482191608574513152

http://www.salesforce.com/company/careers/diversity-numbers.jsp

![screen shot 2014-06-26 at 11 32 37 am](https://cloud.githubusercontent.com/assets/688886/3401381/b80ee5b2-fd4f-11e3-8a99-0b4bafb54bb4.png)
##

**Comment by nobodxbodon** [comment]
At least in the short term, how about just focus on what can be achieved no matter how much similar we seem to be?
