### ISSUE TITLE
Record failed transfers and modify the history page to show them correctly

### ISSUE THREAD

**Issue by seanlinsley** [gratipay/gratipay.com#2534]
People who depend on the money they receive on Gittip are rightfully concerned whenever their receiving amount suddenly jumps down after payday. We know that's because of CC failures, but they don't. We should update the history page to show the number of people that have a tip set up for them, but didn't tip anything because their CC failed. This should be shown for each individual payday, though I'm not sure we have that historical data.

Q: how should the wording change to accomidate people who fund their account with something else, like Bitcoin? Perhaps say that they had "insufficient funds"?
##

**Comment by whit537** [comment]
+2 from @anselmh @book in https://github.com/gratipay/gratipay.com/issues/3756.
