### ISSUE TITLE
Send an email when people you pledge to join Gratipay

### ISSUE THREAD

**Issue by seanlinsley** [gratipay/gratipay.com#2543]
It'd be nice if we sent an email to anyone who pledges to someone when that person joins Gittip. For example, I've pledged to https://www.gittip.com/on/twitter/hardcorehistory/. I'd love to get an email if they ever sign up.

Depends on #2312, etc.

**Comment by rohitpaulk** [comment]
Done in #3136.

**Comment by whit537** [comment]
Great work @rohitpaulk @Changaco! Our first notification! :dancer:
