### ISSUE TITLE
Pledge page for others people

### ISSUE THREAD

**Issue by rach** [gratipay/gratipay.com#2550]
Over the weekend I've seen the pledge page of Mayday.us like this one https://my.mayday.us/t/79cf-Miguel-de-Icaza/ 

That made me think that I would like to have pledge page on gittip where I can say why you should give to X or Y (under review of the person , i guess). 

I find that some great opensource developers are a bit shy to talk about their great contribution. I personally don't have the need of my profile page on gittip as I'm not looking for receiving any money, but I would like to make use of it to promote the work of others people that I find amazing. I give some money but I will like to show them my support too.

Just a suggestion. Let me know what you think.
##

**Comment by nobodxbodon** [comment]
I see complexities like receiving pledges without project owner's consent, and I believe current procedures are designed to avoid this. Plrease reopen if I'm wrong.
