### ISSUE TITLE
invalidate funding instruments during account close

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#2567]
See #941 for handling of Balanced account during take_over. This issue is about the close case. We want to invalidate all funding instruments on Balanced during account close. Once we have https://github.com/balanced/balanced-dashboard/issues/1353 we'll be able to see invalidated instruments on a Balanced account page for historical/debugging purposes.

**Comment by Changaco** [comment]
Closing in favor of #3111.
