### ISSUE TITLE
rebrand Teams feature as Payroll

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#2569]
'Cause that's more accurate.

**Comment by Changaco** [comment]
The Teams feature is not a payroll in the legal sense, and we don't want it to be, otherwise it becomes a tax nightmare. A team account is a group of people having a common tip jar and cooperatively splitting up the money at the end of the week. The money comes from the tippers, not from the legal entity behind the team (if there is one). For example Gratipay LLC is a member of the Gratipay team, it receives whatever is left after the other members have taken their shares. It's not the other way around, the members don't receive money from Gratipay LLC, they receive money from anonymous tippers.

**Comment by whit537** [comment]
> the members don't receive money from Gratipay LLC, they receive money from anonymous tippers.

That sounds to me like even more of an accounting nightmare. I think the closer we can model existing accounting realities, the easier time we're going to have one we're big enough for anyone to care.

I have a US tax professional in town here I'm hoping to talk to. I had figured on waiting until after tax season (April 15), but in light of the resurgence of #67 I might try to see him sooner.

**Comment by Changaco** [comment]
> That sounds to me like even more of an accounting nightmare.

Maybe for the people receiving the money, but not for Gratipay LLC. If you say that I, as a member of the Gratipay team, am receiving money from Gratipay LLC, then Gratipay LLC is breaking french law by disguising employment as freelancing, paying me below the minimum wage, etc.

**Comment by whit537** [comment]
> then Gratipay LLC is breaking french law

And potentially US law as well (by not withholding 30% of what Gratipay, LLC pays you).

"Gratipay LLC is a member of the Gratipay team [and] not the other way around" sounds like hand-waving to me. I would feel disingenuous telling that to users or governments.

In my view, the money given to the Gratipay account on Gratipay is clearly given to Gratipay, LLC. Legally speaking, I am an owner of Gratipay, LLC, and you are a contractor. Yes, we're playing really fast and loose with that right now. Yes, it's a [schlep](http://paulgraham.com/schlep.html) to clean up. That means that we should tackle it head on, because solving it will provide real value to people.

**Comment by whit537** [comment]
> That means that we should tackle it head on, because solving it will provide real value to people.

... and avoid us getting flipped over. :-(

**Comment by techtonik** [comment]
But! I must say the me taking from the Jar is not the same as me being donated directly. So these two flows need to be separated. I don't really care the name, but payroll sounds better to reflect that.

The issue with taxes is the right one to bring and discuss IMO. I didn't think about that, but Armin Ronacher brought the topic of economy in his blog - http://lucumr.pocoo.org/2014/11/2/payments-in-the-future/ and that made me think that economy of gratitude should address the issues. I certainly don't want to be put in jail for tax evasion, so do we make it clear for people how to deal with that sad of things with donations in the world?

How about we address this challenge https://herox.com/TaxFlowChallenge ? We can they define teams who wants to be transparent and chose how do they want to pay taxes from their donations, how can they register in their country to be safe and sound in front of authorities, or maybe they want to opt-out. Maybe their donation is already cleared from taxes, or they experience double taxation. I don't think there is another organization in the world like Gratipay that provides the necessary level of transparency to make it happen.

**Comment by whit537** [comment]
From Armin's post:

> I am a huge fan of gittip aka gratipay and bountysource. The reason for this is that they make it easy to contribute money for Open Source projects and the companies behind them are very nice and straightforward to work with. They will make sure that the model is watertight and legal.

Let's make sure our model is watertight and legal. :mouse:

**Comment by Changaco** [comment]
> And potentially US law as well (by not withholding 30% of what Gratipay, LLC pays you).

I don't think so.

> "Gratipay LLC is a member of the Gratipay team [and] not the other way around" sounds like hand-waving to me.

It's a pretty accurate description of how teams work.

> Legally speaking, I am an owner of Gratipay, LLC, and you are a contractor.

There isn't really a contract between me and Gratipay.

> Yes, it's a schlep to clean up. That means that we should tackle it head on, because solving it will provide real value to people.

You're assuming that there is a solution and that we have the resources to find it.

**Comment by whit537** [comment]
Consider using FBO accounts for this, per https://github.com/gratipay/inside.gratipay.com/issues/192#issuecomment-100330193 ff.

**Comment by whit537** [comment]
Folding #3529 into this.

>Reticketed from @webmaven at https://github.com/gratipay/inside.gratipay.com/issues/180#issuecomment-100501970:
>
>> In a sense, the problem you're describing is already solved for open source by [Fiscal Sponsors](https://lwn.net/Articles/548542/) like the [Software Freedom Conservancy](https://sfconservancy.org/), at least for projects that are too small to merit their own 501(c)3 (eg. not [The jQuery Foundation](https://jquery.org/team/)). I do not know how small their smallest project is. [...]
>>
Can Gratipay do anything to help individuals (or small teams) either find an appropriate Fiscal Sponsor or establish a corporation to get them over that hump?
>
I'm thinking of how Stripe abstracted away merchant accounts for people, but really more like Braintree, because we want to allow people to bring their own corporation (Braintree allows you to bring your own merchant account and just use them as a gateway, *or* use their simplified one-size-fits-all merchant account).
>
We're wrestling with Gratipay's structure on https://github.com/gratipay/inside.gratipay.com/issues/242 wrt @rohitpaulk's relationship to Gratipay, under pressure to bring back payroll (#3433).

**Comment by whit537** [comment]
Blocked on https://github.com/gratipay/inside.gratipay.com/issues/242.

**Comment by whit537** [comment]
https://github.com/gratipay/inside.gratipay.com/issues/242 is done, and we're already pitching as "Payroll."

![screen shot 2016-04-09 at 5 12 43 pm](https://cloud.githubusercontent.com/assets/134455/14406464/51cbe8de-fe76-11e5-9ec9-784de975d6a8.png)
