### ISSUE TITLE
up receiving limit for individuals

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#2570]
@jdorfman from @MaxCDN wants to start giving > $100/wk to individuals. We upped the receiving limit for groups in #1378. What would it look like to up the limit for individuals?

It sounds like @jdorfman's use case is starting to get into more of a payroll situation, where he's giving to someone who's doing a fair bit of work on @MaxCDN's open-source projects. In the past we've said that employment-type relationships are out of scope for Gittip, but now we actually have a payroll-like feature: [Teams](https://www.gittip.com/about/teams/) (cf. #2569). One possibility could be to use the existing Teams/Payroll feature with the MaxCDN Gittip account.

If we did want to up the receiving limit for individuals, I think we should do something like:

 - Payments > $100/wk are non-anonymous. The receiver sees who the giver is.
 - The receiver has to explicitly opt in.

**Comment by mattbk** [comment]
Closing, since with teams the limit is $1000 per week (yes, I just checked).
