### ISSUE TITLE
Fund your own project

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#2571]
One possible use case is for a company to set aside a budget to compensate contributors to its open source projects. In this case the money would be coming from the company rather than from payments received on Gratipay.

**Comment by whit537** [comment]
Folding #4324 into this ...

> Reticketed from https://github.com/gratipay/inside.gratipay.com/issues/432#issuecomment-163738482:
>
>> The flip side would be an organization that wanted to use us for payroll but not for payments. @timothyfcook has asked for this before. He wants to use Gratipay to distribute payroll for projects that are grant funded outside of Gratipay.
>
>Also cropped up [in slack](http://gratipay.slackarchive.io/gratipay/-/1486136421.005182/1486382591.005364/1486246090005355/ ) (cc: @simonmichael).

**Comment by whit537** [comment]
+1 in private email (from someone at a [top-25](https://en.wikipedia.org/wiki/List_of_largest_Internet_companies) Internet company) :

> One of the things that I've always been interested in is not just "\<Company\> gives $x to project", but also the flip side of that too. I would like a way for "\<Company\> to give $x developer, for their contributions to \<Company\> project".
>
>Not just giving back to the projects that we use, but to the developers that donate their time to our open source projects.

**Comment by whit537** [comment]
+1 from @bcomnes in [slack](https://gratipay.slackarchive.io/gratipay/page-81/ts-1490982844201937).

**Comment by whit537** [comment]
Seems like this is related to adding funds at any time (#113).

**Comment by bcomnes** [comment]
Or possibly drawing funds from a project as a member at any time.  Maybe I'm still stuck in thinking in terms of bank accounts though.
