### ISSUE TITLE
Wrong SSL cert occasionally

### ISSUE THREAD

**Issue by deltab** [gratipay/gratipay.com#2586]
I followed the 'Read more' link from the new homepage to https://www.gittip.com/about/, where Firefox displayed a security warning:

> This Connection is Untrusted

> You have asked Firefox to connect securely to www.gittip.com, but we can't confirm that your connection is secure.

> Normally, when you try to connect securely, sites will present trusted identification to prove that you are going to the right place. However, this site's identity can't be verified.

> [... more explanation, then ... ]

> Technical Details

> www.gittip.com uses an invalid security certificate.

> The certificate is only valid for the following names: nightclubsecurity.com , www.nightclubsecurity.com

> (Error code: ssl_error_bad_cert_domain)

> [option to accept certificate anyway]

Both sites use Amazon load balancing (IP addresses within us-east-1.elb.amazonaws.com).

This could be related to something I saw last week (in another browser on another ISP), when I saw an error message from an Acquia host (Gittip uses Heroku): https://botbot.me/freenode/gittip/msg/17915537/.

**Comment by whit537** [comment]
No new reports in six months. I'm considering closing this. Objections?

**Comment by whit537** [comment]
I feel helpless here. :-(
