### ISSUE TITLE
Make the unauthenticated homepage more engaging

### ISSUE THREAD

**Issue by timothyfcook** [gratipay/gratipay.com#2617]
Since the "top ten lists" have been taken off the homepage, we need some way to get potential users excited about contributing. They can't do this unless they see examples of what they could support. 

We need to tell the stories of users and highlight certain profiles on the homepage.

Communities should also be available for browsing. 

Basically, we need something beyond search on the homepage.

**Comment by whit537** [comment]
Done in #3718, etc.

**Comment by whit537** [comment]
![screen shot 2015-09-09 at 8 51 02 am](https://cloud.githubusercontent.com/assets/134455/9762191/ec2fc85e-56cf-11e5-91c6-9dae49f353f6.png)
