### ISSUE TITLE
Champion Service

### ISSUE THREAD

**Issue by balupton** [gratipay/gratipay.com#2621]
As an extension to https://github.com/gittip/www.gittip.com/issues/1273

I'm sick and tired of Gittip not actually being sustainable for 99.9% of its users. This needs work.

I've got an idea around this called Championing. It's a 3rd party service built on top of gittip where people/communities register, specify their gittip username, and how much they need a week (e.g. $1500), then it sets up a page for them. Companies then view that page, and enter their gittip api key, and start donating $100/week. They are now champions.

Champions are then listed in everything that the person/community does for the weeks they are champions — project READMEs, talks, etc. This is largely automated through the service provided APIs that can be quiried with the right tokens, and can use bevry/projectz to keep their readmes up to date. If a champions gittip donation changes or fails, they are no longer a champion, the service will autodetect this and email them in case it was a mistake with instructions on how to fix this.

There are only enough champions that are needed to bring in the needed amount. E.g. If a person/community specifies $1500/week, then that means they get 15 champions. This provides a really interesting dynamic, especially when coupled with the technical restrain here of Gittip's $100/week limit. It has exclusivity, which promotes urgency, and a tangible target that needs to be accomplished. Everyone know where they stand, and it is clear cut. If there is less than the needed amount of champions, then that is actually a seriously urgent situation, that luckily can be addressed fluidly and with enough financial leeway that the money from the existing champions can support the person/community in the meantime until they fill that spot. If there is all the available slots are filled, then they wannabe champions can signup on a waiting list instead. Champions are displayed in order of how much they have donated over time.

Champions will be able to see all the contributions that have financially supported, including talks, etc. It's about generosity giving, but businesses need tangible output to identify it was worth giving, having tangible output of what they sponsored exactly accomplishes this, without compromising values.

Several pointers are pointing towards this being a good idea. Years ago, I actually pitched this to Chad as an alternative service to Gittip, and he convinced me of the values of Gittip, which can be seen as evident in the above.

I'll be exploring this idea for Bevry, however if others are interested in this, let me know and we can work together to help make it easier for others to use it.

**Comment by whit537** [comment]
> It's a 3rd party service built on top of gittip
> This is largely automated through the service provided APIs 

What are the APIs Gratipay would need to provide to enable this?

**Comment by balupton** [comment]
I've started working on such a thing over at https://github.com/bevry/spnsored

The thing needed for gratipay is https://github.com/gratipay/gratipay.com/issues/236

So far, only the following part is planned for it:

> Champions are then listed in everything that the person/community does for the weeks they are champions — project READMEs, talks, etc. This is largely automated through the service provided APIs that can be quiried with the right tokens, and can use bevry/projectz to keep their readmes up to date. If a champions gittip donation changes or fails, they are no longer a champion, the service will autodetect this and email them in case it was a mistake with instructions on how to fix this.

**Comment by whit537** [comment]
> I've started working on such a thing over at https://github.com/bevry/spnsored

I think the correct link is https://github.com/bevry/sponsored, ya?

> The thing needed for gratipay is #236

Okay, cool. I've copied your comments over to #236. Closing here ...
