### ISSUE TITLE
correct any misuse of escrowed funds

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#265]
**was** move money from Zeta bank account into Balanced

We've got $2,203.89 escrowed in Balanced with a merchant balance of -$167.22. That's $2,036.67.

We owe people $5,449.41 (`SELECT sum(balance) FROM participants`), so I need to add $3,412.74 to my Balanced escrow.

How do I do that?

/cc @mtamizi, @jkwade, @mahmoudimus, @mjallday

**Comment by whit537** [comment]
Still slightly off.


```
121,627.17 New Alliance
 28,007.13 Balanced
  7,143.91 PayPal
----------
156,778.21


```

```
=> select sum(balance) from participants;
┌───────────┐
│    sum    │
├───────────┤
│ 156227.26 │
└───────────┘
(1 row)
```

**Comment by MikeFair** [comment]
Have you accounted for interest that would accrue in the bank accounts
and/or deleted/deactivated accounts that once had a balance?

**Comment by whit537** [comment]
@MikeFair Good call! No, I didn't factor in interest, but I know we've accrued some.

**Comment by whit537** [comment]
We've got a solid financial accounting system coming together in https://github.com/gratipay/inside.gratipay.com/pull/390 and https://github.com/gratipay/finances/pull/1. As we get caught up reconciling past months under this new accounting system, any escrow discrepancy should get squeezed out.

**Comment by whit537** [comment]
Closing to keep this repo clean now that we have https://github.com/gratipay/finances. This should get cleaned up in course and audited under https://github.com/gratipay/finances/issues/3.
