### ISSUE TITLE
Use a direct link to fonts.css

### ISSUE THREAD

**Issue by Changaco** [gratipay/gratipay.com#2654]
Reticketed from https://github.com/gittip/www.gittip.com/issues/1447#issuecomment-52313360. It shouldn't be required to send a `Referer` to third-party services (`typography.com` in this case).
##

**Comment by nobodxbodon** [comment]
According to https://github.com/gratipay/gratipay.com/issues/1447#issuecomment-52314694, as long as we still use Typography, I don't think the efforts to update link for font file changes is worth some of users losing fonts, for now. Please reopen if needed.
