### ISSUE TITLE
investigate and repair ach credit failures

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#2657]
I'm pretty sure Balanced has been sending us emails when ACH credits fail, and I thought we were up to date on correcting those manually. Here's [an example where we're not](https://dashboard.balancedpayments.com/#/marketplaces/MP12Xw5lL6iaILtqImIoroDL/customers/CU5rStPgkch0VyQtVWHXQbn1). What gives?

**Comment by Changaco** [comment]
Closing in favor of #2779.
