### ISSUE TITLE
Recognize companies

### ISSUE THREAD

**Issue by timothyfcook** [gratipay/gratipay.com#2695]
-------------------------------

✈️  **This is the flight deck for the [Recognize companies](https://github.com/orgs/gratipay/projects/16?fullscreen=true) project.** ✈️ 

-------------------------------

The top givers (often times companies) who are giving to Git... Gratipay should be shown on the main page.

This is an easy way to thank top givers for supporting projects and a good way to associate our brand with theirs.

Showing Heroku, Khan Academy, Bountysource, etc. on the front pages shows new users who is behind Gratipay and gives them a free advertisement saying "Hey, these folks are cool, they support open source, etc."

This list should change on each load and be drawn randomly from a mix of:
- the top 25 givers
- specifically curated givers with a unique story

Obviously, open to discussion. Just getting the ball rolling.

-------------------------------

✈️  **This is the flight deck for the [Recognize companies](https://github.com/orgs/gratipay/projects/16?fullscreen=true) project.** ✈️ 

-------------------------------

**Comment by whit537** [comment]
+1 from @JeffSpies in personal conversation.

**Comment by whit537** [comment]
+1 from @nayafia at https://www.youtube.com/watch?v=CXPDtPhnhus#t=55m34s.

**Comment by mattbk** [comment]
We'll need something like this soon, we now have 184 teams listed on the front page at http://gratipay.com!

**Comment by whit537** [comment]
Relevant: _[Building Web Reputation Systems](http://shop.oreilly.com/product/9780596159801.do)_ ([h/t](https://twitter.com/whit537/status/739838759127126017))

**Comment by whit537** [comment]
Circling back around to this from https://github.com/gratipay/inside.gratipay.com/issues/844 and https://github.com/gratipay/inside.gratipay.com/issues/836 ...

**Comment by whit537** [comment]
Basically applying for Y Combinator has really kicked me into gear on our [roadmap](https://github.com/gratipay/inside.gratipay.com/issues/840#issue-180502904), jumping ahead to 2.iii.

**Comment by whit537** [comment]
Like, if we *do* get out there for an interview or whatever, I want to show a website that has _at least one_ company giving to open source on the homepage.

**Comment by whit537** [comment]
PR started in https://github.com/gratipay/gratipay.com/pull/4135.

**Comment by whit537** [comment]
#4135 took a wrong turn at Albuquerque, which landed us at https://github.com/gratipay/inside.gratipay.com/issues/987, and back here via https://github.com/gratipay/inside.gratipay.com/issues/987#issuecomment-274151963. 😄

**Comment by whit537** [comment]
+1 from a representative of a [top-25](https://en.wikipedia.org/wiki/List_of_largest_Internet_companies) Internet company:

> We seek to celebrate the donors in a branded way (either we grant money to our employees who select projects, or we solicit ideas from them and grant for them, something like that). So we'd want to co-brand and say something that acknowledges both Dav and Yahoo for his sponsorship of this very important Node.JS module.

**Comment by whit537** [comment]
I've commandeered this ticket to be the flight deck for the [Recognize companies](https://github.com/orgs/gratipay/projects/16?fullscreen=true) project. Description duly updated.

**Comment by mattbk** [comment]
!m @whit537

**Comment by techtonik** [comment]
@whit537 how to apply for Google funding? bugs.python.org/Roundup needs a lot of work.

**Comment by techtonik** [comment]
For companies I would also provide a rating of how many of its employees are supporting open source by giving them API to donate through their company, but with their name.
