### ISSUE TITLE
Error in displaying Twitter profile

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#2727]
This is a screenshot of @seanlinsley's gratipay page - notice the double `(` and absence of `)` in the twitter row.
![screenshot from 2014-09-04 14 38 40](https://cloud.githubusercontent.com/assets/3893573/4147016/3cb86a1e-3413-11e4-83bd-81668f65932c.png)

This doesn't happen on many other profiles though, mine included.
![screenshot from 2014-09-04 14 38 46](https://cloud.githubusercontent.com/assets/3893573/4147017/3e7c66ca-3413-11e4-9f19-f3661e35064d.png)
##

**Comment by nobodxbodon** [comment]
Fixed:
![screen shot 2017-01-14 at 11 23 40 pm](https://cloud.githubusercontent.com/assets/392497/21960947/86476fcc-dab0-11e6-991a-3a5b862a0712.png)
