### ISSUE TITLE
API Implementation URLs in README.md are broken

### ISSUE THREAD

**Issue by vinayakumar** [gratipay/gratipay.com#2799]
in the Readme.md:API Implementation , there are 2 urls given as below

Node.js: Node-Gratipay (also see Khan Academy's setup)

Both these are not working. Any clue what is correct one ?

**Comment by techtonik** [comment]
Is that still actual? The links look ok, but I am not sure about clients, which seems to be a different issue.

**Comment by whit537** [comment]
I take it this was about just the links on the README, not the clients themselves. README links are fixed.
