### ISSUE TITLE
switch to opt-in

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/gratipay.com#28]
Gittip.com is currently opt-out, and that's not cool. See below for discussion.

**Original:**

We've got a fine line to toe. [Kachinga pissed people off](http://krisstraub.com/2011/11/20/kachingle-and-the-transgression-of-opt-out/) by collecting money on their behalf without explicit permission. We're a bit different (donor pays fee vs. cut to recipient, coop vs. corp) but it remains to be seen whether we're different enough.

Even if the world is okay with us being opt-out instead of opt-in, we still need an opt-out mechanism. This would involve claiming an account and then clicking a big red "Stop taking donations for me" button.

(This started as #26 but then got derailed. Reticketing.)

**Comment by mattbk** [comment]
Related: https://github.com/tip4commit/tip4commit/issues/127
