### ISSUE TITLE
Better Art 403

### ISSUE THREAD

**Issue by techtonik** [gratipay/gratipay.com#2813]
![clipboard](https://cloud.githubusercontent.com/assets/515889/4659633/80f69986-550f-11e4-84fa-df12b26ee121.png)
##

**Comment by nobodxbodon** [comment]
Now it's 401:
![screen shot 2017-01-10 at 11 21 37 pm](https://cloud.githubusercontent.com/assets/392497/21839241/98ce0c1e-d78b-11e6-8849-4301ee9fb8b8.png)
