### ISSUE TITLE
provide link to source file in GitHub from all pages

### ISSUE THREAD

**Issue by techtonik** [gratipay/gratipay.com#2816]
Assuming that one of the `gratipay.com` missions is providing Public Domain code that can be reused, it is important to provide convenient access to code from the pages that it renders. For example, today I paid attention at bar charts at https://gratipay.com/about/stats.html and really liked them. Browser asset inspection reveals used d3.js, but all scripts are minified, so it is impossible to see how good is the code that renders them. Page contains only link to GitHub from which it is not really clear where to get started.

Tracing where request started processing is a needed skill, but not many possess the skills and experience to do this. More important (and useful) for occasional contributor is to identify the **entrypoint** where request processing starts to be related to the actual content of rendered page. Good web framework should have and ability to map rendered page back to the sources from which it was compiled. In case of gratipay it might be easy, but I am not sure.
##

**Comment by nobodxbodon** [comment]
With github ribbon and simple mapping described [above](https://github.com/gratipay/gratipay.com/issues/2816#issuecomment-59495755), IMO it's good enough for anyone who wants to check out code.
