### ISSUE TITLE
None leaked on G+ take over

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#2817]
![screen shot 2014-10-17 at 10 01 17 am](https://cloud.githubusercontent.com/assets/134455/4679895/1ceae256-5606-11e4-808d-12d3e664db8f.png)
##

**Comment by nobodxbodon** [comment]
Not reproducible now:
![screen shot 2017-01-15 at 9 16 53 am](https://cloud.githubusercontent.com/assets/392497/21964585/6ddc204c-db03-11e6-9ad2-d2bc248923bd.png)
