### ISSUE TITLE
errant linebreak in `+ Add` button for elsewhere

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#2818]
This isn't intentional, is it?

![screen shot 2014-10-17 at 10 06 12 am](https://cloud.githubusercontent.com/assets/134455/4679970/d1051766-5606-11e4-8cd6-f0ae74d44479.png)
##

**Comment by nobodxbodon** [comment]
Not reproducible now (checked in both chrome and ff):
![screen shot 2017-01-15 at 9 19 50 am](https://cloud.githubusercontent.com/assets/392497/21964604/01b02b7e-db04-11e6-9f24-6c53c9e36253.png)
