### ISSUE TITLE
Speed up /about/stats

### ISSUE THREAD

**Issue by seanlinsley** [gratipay/gratipay.com#2826]
Looking at Heroku's new [database performance analyzer](https://postgres.heroku.com/databases/gratipay-heroku-postgresql-maroon), besides a long list of slow queries in `self_check`, I noticed that two queries in https://gratipay.com/about/stats were each taking a little over a second:

[`tip_stats`](https://github.com/gratipay/gratipay.com/blob/69f0900c667dd27f3b19feb0f27c1e3cd3a40d63/www/about/stats.spt#L38)

![screen shot 2014-10-19 at 10 08 04 am](https://cloud.githubusercontent.com/assets/688886/4693584/7f69f58c-57a2-11e4-82cf-8eb85d30149f.png)

[`average_tippees`](https://github.com/gratipay/gratipay.com/blob/69f0900c667dd27f3b19feb0f27c1e3cd3a40d63/www/about/stats.spt#L53)

![screen shot 2014-10-19 at 10 09 49 am](https://cloud.githubusercontent.com/assets/688886/4693585/7f6a9226-57a2-11e4-8075-7f442f8239ed.png)

Loading this page in production is currently taking between 3 and 4 seconds.
##

**Comment by nobodxbodon** [comment]
Now loading takes <50ms. Guessing caching is in place. Closing.
![screen shot 2017-01-11 at 10 20 03 pm](https://cloud.githubusercontent.com/assets/392497/21879253/31943764-d84c-11e6-86f2-224daef42adb.png)
