### ISSUE TITLE
Gratipay is using Segment.io, but which analytics integrations are currently in use?

### ISSUE THREAD

**Issue by webmaven** [gratipay/gratipay.com#2827]
https://segment.com/integrations#analytics

**Comment by whit537** [comment]
No longer using Segment.

**Comment by reinpk** [comment]
@whit537 sorry to hear you're not using segment any more :( can i ask what changed?

**Comment by patcon** [comment]
@reinpk decision was made over a year ago, so I don't think there's a clear answer there. Generally, we had some issues with setup and docs, and didn't see the value above just sending it to the one service we used (which we already had implemented)

**Comment by reinpk** [comment]
gotcha, sorry you had trouble with the docs and setup! wish we knew the details around what to fix, but sounds like we're too slow in our outreach to get the details. thanks for the response and best of luck!
