### ISSUE TITLE
Terms | Privacy | Fraud  --> Legal

### ISSUE THREAD

**Issue by techtonik** [gratipay/gratipay.com#2847]
![colophon](https://cloud.githubusercontent.com/assets/515889/4797731/c2971b84-5e0d-11e4-960a-05cef059f382.png)

Current footer is too huge - it is hard to scan for useful info, such as source code. Legal info could be compressed to a single link. There is also DNT page that is not present here - https://gratipay.com/about/dnt

**Comment by Changaco** [comment]
Closing as obsolete.

**Comment by techtonik** [comment]
Not as actual in new design anymore.
