### ISSUE TITLE
Only ask for OAuth permissions when we actually need them

### ISSUE THREAD

**Issue by jish** [gratipay/gratipay.com#2854]
Hello,

I haven't logged into my gratipay account since it was still called gittip. When I went to log in today, it seems you guys are requesting more access to my GitHub account.

Is it possible for me to still log in somehow? Can you remove the additional request for information?

---

![screen shot 2014-10-28 at 8 50 42 pm](https://cloud.githubusercontent.com/assets/1817/4820866/f376f366-5f1e-11e4-87c8-ba5d18556a35.png)
##

**Comment by techtonik** [comment]
Looks like I am be able to deal with it in any reasonable time frame. Need a diagram how the flow is implemented in Gratipay.

**Comment by techtonik** [comment]
Ok. I need to deal with this challenge sooner or later. Just raising the priority.
