### ISSUE TITLE
problem with {0}% in Transifex?

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#2856]
From @thiagoponte on https://www.transifex.com/projects/p/gratipay/translate/#pt_BR/core/35897010:

> Transifex is not allowing to write {0}% as translation. It should be: Apenas {0}% dos usuários ativos também {1}suportam o Gratipay{2}.

**Comment by Changaco** [comment]
+1 from @sidneygijzen in #3175:

> I was just translating the string "% Funded" into Dutch using the Transifex Web Editor. The string appears at the location ```www/explore/teams/index.spt:39```. I got the following warning:
>
> ```Warning: The expression '% F' is not present in the translation.```
>
> A short search resulted in [this Transifex FAQ page](http://docs.transifex.com/faq/#why-is-my-web-editor-complaining-about-the-percentage-sign), which describes some solutions to this problem. I have no clue which solution is preferred, but perhaps there is a policy on that?

**Comment by Changaco** [comment]
Closing. @sidneygijzen's comment says that he only got a warning, not an error, which means that Transifex fixed the bug that was keeping this issue open.
