### ISSUE TITLE
interface for changing tip on giving page is confusing

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#2895]
Reported by [UkuleleRod](https://gratipay.com/UkuleleRod). Since there are only "Cancel" buttons on the Giving page, it was unclear that by modifying the tip amount that a "Confirm" button would appear. The user was reluctant to experiment for fear of accidentally canceling the tip entirely.

We had some recent activity around this UI. @rohitpaulk Do you have that previous ticket handy for reference?

**Comment by Changaco** [comment]
Closing in favor of #3107.
