### ISSUE TITLE
Fix error page

### ISSUE THREAD

**Issue by Changaco** [gratipay/gratipay.com#2913]
https://app.getsentry.com/gratipay/gratipay-com/group/49625026/ (was https://app.getsentry.com/gratipay/gratipay-com/group/39866655/)

**Comment by whit537** [comment]
I infer from https://github.com/gratipay/gratipay.com/commit/ac9077437ed59a485105edd92d3c7fd83b9518ed that the problem here was that i18n wasn't configured before an 403 was triggered in `get_auth_from_request`, ya?

**Comment by Changaco** [comment]
@whit537 Correct. `error.spt` extends `templates/base.html` which uses i18n functions.

**Comment by whit537** [comment]
k thx
