### ISSUE TITLE
handle elsewhere changes from individual to team

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#2919]
It's possible in both GitHub and Bitbucket to change an account from an individual account to an organization account. Since we treat the two differently, it's possible for a Gratipay account to get into an inconsistent state if the user changes their account type elsewhere.
##

**Comment by nobodxbodon** [comment]
Seems user won't be able to sign into the converted account:
![screen shot 2017-01-15 at 2 00 23 pm](https://cloud.githubusercontent.com/assets/392497/21966594/1064c68a-db2b-11e6-9f21-e667853d85aa.png)
If the consequence is been unable to login to gratipay using the github account, I suppose admin can already handle that. Please reopen if I'm wrong.
