### ISSUE TITLE
configure Coveralls to reduce noise

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#2925]
Mailed support:

> Greetings! We recently started using Coveralls again (after our configuration went stale for a while due to a repo rename). Now we're once again getting Coveralls comments on PRs. However, we're finding these notifications to be too noisy. I find on the notifications page of the Coveralls.io dashboard that I can configure percentage thresholds for certain kinds of notifications (email, hipchat, campfire, webhook). How do I configure thresholds for the GitHub comments? Thanks! :-)
> 
> chad

IRC [one](https://botbot.me/freenode/gratipay/2014-11-11/?msg=25286849&page=1) [two](https://botbot.me/freenode/gratipay/2014-11-11/?msg=25293511&page=2)

**Comment by Changaco** [comment]
Closing. I don't remember how or when but obviously the problem got solved.
