### ISSUE TITLE
Lower the barrier for hacking on Gratipay

### ISSUE THREAD

**Issue by joeyespo** [gratipay/gratipay.com#2927]
Opening an issue dedicated to the ongoing discussion of getting Gratipay set up locally.

Why? It's a little overwhelming for newcomers, and is still time-consuming even if you've done it before.

Need more convincing?

![gratipay-getting-setup](https://cloud.githubusercontent.com/assets/634573/5005795/4c8a0d0e-6a04-11e4-9243-31e268655752.png)

That's how much of the README is dedicated to getting set up.
##

**Comment by nobodxbodon** [comment]
Merging [Create tutorial for new Gittip Developers](https://github.com/gratipay/gratipay.com/issues/1846)
