### ISSUE TITLE
can't link Facebook Pages to Gratipay account

### ISSUE THREAD

**Issue by timothyfcook** [gratipay/gratipay.com#2944]
If you type in Gratipay from the home page, it says that Gratipay has not joined Gratipay : (

![screen shot 2014-11-17 at 1 43 55 pm](https://cloud.githubusercontent.com/assets/1823300/5075385/78b317bc-6e60-11e4-90e9-d86884e9f953.png)
##

**Comment by whit537** [comment]
+1 https://gratipay.freshdesk.com/helpdesk/tickets/1910
