### ISSUE TITLE
jstests fail when Gratipay is already running

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#2953]
Reticketing from https://github.com/gratipay/gratipay.com/pull/2947#issuecomment-63671656 per [IRC](https://botbot.me/freenode/gratipay/2014-11-19/?msg=25812029&page=2).
##

**Comment by deivid-rodriguez** [comment]
I fixed this yesterday by adding the `stop` _task_ as a _prerrequisite_ for the `jstests` _task_ (not sure what the `make` terminology is here, I'm using [`rake`](https://github.com/ruby/rake) terminology, but I can add a diff if what I mean is not clear!). Unfortunately it broke the travis build. If this is considered a good approach to fixing this, I could dedicate some more time to figure out why the build broke.

**Comment by whit537** [comment]
@deivid-rodriguez As you've started to discover on #3911, our js test suite is not very mature yet. I see #3684 as a longer-term way to make js tests more integral to the project, and I believe it might fix this present ticket as a side-effect. Do you have any interest in pursuing that approach instead?

P.S. the `make` terminology would be "target" instead of "task" (in our case, a "[phony target](http://www.gnu.org/software/make/manual/make.html#Phony-Targets)" since it doesn't point to an actual file on the filesystem), and "dependency". "Prerequisite" or "dependency" are fine.

**Comment by deivid-rodriguez** [comment]
Oh yes, I know remember those terms from my C days! :)

Yes, it looks like approaching #3684 is better than doing extra work that _might_ get overwritten by it! I'll have a look at it!

**Comment by whit537** [comment]
Awesome, thanks! :-)

**Comment by whit537** [comment]
I'm pretty sure our infrastructure has changed enough that his is now moot.
