### ISSUE TITLE
Update or remove `gratipay.box`

### ISSUE THREAD

**Issue by techtonik** [gratipay/gratipay.com#2954]
With new Vagrantfile in place after #2948 is merged in, `gratipay.box` needs to be updated or README.md changed.
##

**Comment by techtonik** [comment]
gratipay.box was killed due to updated Vagrantfile. Need to check its location and remove it. It won't save much traffic, and Docker/LXC is *much* faster anyway.

**Comment by nobodxbodon** [comment]
Guess this issue is obsolete.

**Comment by whit537** [comment]
The work here is to login to MaxCDN, go to the assets manager for the downloads.gratipay.com push zone, and remove the file. It's crusty to try and find the ftp password to use for the assets manager so I'm reopening vs. actually doing this right now.

**Comment by whit537** [comment]
lol
