### ISSUE TITLE
consider joining Heroku's GitHub sync beta

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#2962]
> Hi there,
>  
> We're contacting you because you used the GitHub linking feature in the old Heroku Dashboard.
> 
> We're working on new integrations with GitHub. If you use GitHub as your `origin` and you are interested in exploring better GitHub/Heroku integrations such as auto-deployment and viewing diffs and if you're up for providing beta feedback, please subscribe to this mailing list.
> 
> We'll be providing instructions and periodic updates on progress directly to that list. If you sign up, you'll only get emails related to the new GitHub sync features that we're currently working on.
>  
> We're looking forward to your feedback
> The Heroku DevEx team

https://gratipay.freshdesk.com/helpdesk/tickets/1400

**Comment by rohitpaulk** [comment]
Stale, closing.
