### ISSUE TITLE
what's up with 404 Google+ accounts?

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#2965]
e.g.

https://gratipay.com/gabecq/ =>
https://plus.google.com/114095307417238376097 <- 404
##

**Comment by whit537** [comment]
https://gratipay.com/a.bonaccorsy/

**Comment by whit537** [comment]
https://gratipay.com/stony02/

**Comment by whit537** [comment]
https://gratipay.com/catcow33/

**Comment by whit537** [comment]
https://gratipay.com/Paul%20Boddie/

**Comment by benhc123** [comment]
Have we actually identified the problem here?

**Comment by whit537** [comment]
@benhc123 I haven't. What do you need in order to work on this?
