### ISSUE TITLE
implement a reputation system

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#2992]
Right now we have a binary (well, trinary) `is_suspicious` field to track reputation. We should evolve something more granular. Users should be able to unlock features by earning reputation. I feel like we've talked about this before but I don't know that we have a ticket dedicated to the idea.
##

**Comment by webmaven** [comment]
This might be helpful (both the book and the wiki):
http://buildingreputation.com/

**Comment by whit537** [comment]
For hard-suspending a user, we should evolve the existing `is_suspicious` knob into `is_suspended` (#3058).

**Comment by webmaven** [comment]
Assuming an owner gets banned, is the team banned as well, or is there opportunity for the team to be transferred to another owner?

If a team is banned, the members are not, correct (as they may be or become members of other teams)?

What will the processes (or lifecycle, if you will) look like for individuals joining/leaving teams?

Do we watch if teams have a high proportion of their members suspended or banned over time?
