### ISSUE TITLE
Allow unicode characters in usernames

### ISSUE THREAD

**Issue by benhc123** [gratipay/gratipay.com#3009]
Some foreign characters (non-english) which some people might want to use in their usernames are currently coming back as invalid.

Clearly we don't want to allow all characters for security reasons but we should allow the most common foreign ones.
##

**Comment by seanlinsley** [comment]
Is there a good blacklist to use?

It seems like we shouldn't allow zero-width characters and [control characters](https://en.wikipedia.org/wiki/Control_character), at least.

**Comment by mojo-chan** [comment]
I would like to see unicode support too. You need to do a couple of things.

Normalization, see MediaWiki for a widely used implementation of type C: http://www.unicode.org/reports/tr15/

For the security aspect, see here: http://www.unicode.org/reports/tr39/

I'm sure there are implementations of these you could grab from somewhere.
