### ISSUE TITLE
audit csrf_token for httponly

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/gratipay.com#3030]
We've received a security disclosure about [not setting `httponly` for `csrf_token`](https://github.com/gratipay/gratipay.com/blob/1749/gratipay/security/csrf.py#L153). We should review that decision and leave a comment in the code where that is necessitated.

**Comment by whit537** [comment]
+1 https://gratipay.freshdesk.com/helpdesk/tickets/2313
