### ISSUE TITLE
better communicate our policy on sexual content

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3032]
We're getting a minor influx of users from Patreon in light of the [new Community Guidelines](http://www.patreon.com/guidelines) they developed in response to 8chan joining Patreon. Some background:

 - http://pastie.org/9793622
 - http://www.patreon.com/user?u=162165
 - https://twitter.com/infinitechan/status/546601585669730304
 - https://twitter.com/MeinosKaen/status/547005491642396672
 - https://twitter.com/Taosym/status/547145680376967168
 - https://gratipay.freshdesk.com/helpdesk/tickets/1511 (login required)
 - https://gratipay.freshdesk.com/helpdesk/tickets/1501 (login required)

What do we want to do here?

**Comment by AManInBlack** [comment]
It's not just a matter of porn, for what it's worth.

https://twitter.com/a_man_in_black/status/563077608385310720

This is cropped, but I can provide a more complete version if necessary.

You have 8chan hosting boards for harassment and straight up crimes, with . Is this the sort of userbase Gratipay is looking to cultivate?

**Comment by whit537** [comment]
Implicit +1 on firming up the policy from https://gratipay.freshdesk.com/helpdesk/tickets/1778.

**Comment by whit537** [comment]
I think we should adopt a blanket "no" to people such as FD1778 who are asking "Can I fund my adult project on Gratipay?" They should use [Offbeatr](http://offbeatr.com/) instead.

**Comment by whit537** [comment]
Objections?

**Comment by whit537** [comment]
Another one: https://gratipay.freshdesk.com/helpdesk/tickets/1808.

My reply:

> Thanks for asking. It's a bit buried (in Balanced Payments' acceptable use policy), but Gratipay isn't the right fit for porn. We recommend [Offbeatr](http://offbeatr.com/).
>
Best of luck! :-)

**Comment by whit537** [comment]
> [...] offbeatr wants me to send them a pic of me holding government ID [...]

Me:

> Well, we're going to have to start doing the same before too long, too:
> 
https://github.com/gratipay/gratipay.com/issues/417#issuecomment-78267913
>
Sorry. :-/

**Comment by rohitpaulk** [comment]
> They should use Offbeatr instead.

Offbeatr is more of a kickstarter clone, and doesn't seem to offer weekly recurring payments.

**Comment by benhc123** [comment]
@rohitpaulk, that isn't really our problem.

**Comment by whit537** [comment]
@rohitpaulk Are you aware of an adult-oriented option that's closer to our model than Offbeatr is? Happy to recommend that instead.

**Comment by whit537** [comment]
https://gratipay.freshdesk.com/helpdesk/tickets/1925

**Comment by whit537** [comment]
This run through [team review](http://inside.gratipay.com/howto/review-teams) now.
