### ISSUE TITLE
Basic analytics for users

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3034]
It might be a useful feature if users could see basic analytics for their account page on Gratipay, even if it's just counting pageviews.
##

**Comment by webmaven** [comment]
GA has an API, the data could be pulled from there to display for users.

**Comment by rohitpaulk** [comment]
Do we still use GA? We added Piwik too somewhere, IIRC....

**Comment by whit537** [comment]
No GA since #761, as you've found. We used Piwik most recently, but stopped paying for it at https://github.com/gratipay/inside.gratipay.com/issues/328.

**Comment by rohitpaulk** [comment]
I'd like to work on analytics for users - Is it okay if I setup a Piwik instance on Digital Ocean? Do we have a team account there that you can add me to?

**Comment by rohitpaulk** [comment]
Ah, just saw this - https://github.com/gratipay/gratipay.com/issues/761#issuecomment-164339195

**Comment by emanwebdev** [comment]
IMHO, they are already plenty of analztics / tracking stuff all around we can iembed and bind to a Grtipay button e.g

**Comment by whit537** [comment]
@emanwebdev Does Piwik fit the bill? What do you mean by "bind to a Gratipay button"?

**Comment by solarimix** [comment]
Piwik is a good option. IMHO
