### ISSUE TITLE
Cannot close (delete) my account

### ISSUE THREAD

**Issue by sigmavirus24** [gratipay/gratipay.com#3044]
I works for a while but then I see an "Application Error" page from Heroku. Ostensibly the operation takes too long and Heroku kills the request.

**Comment by rohitpaulk** [comment]
@sigmavirus24 - When did you try this?

**Comment by Changaco** [comment]
I have successfully reproduced the deadlock locally. The account closing logic is choking on @sigmavirus24 still being part of a team.

**Comment by sigmavirus24** [comment]
@rohitpaulk I tried it twice, about 5 minutes in between each try. The last attempt was a minute before I filed the issue. @Changaco I didn't realize I was part of a team. How do I leave?

**Comment by whit537** [comment]
@sigmavirus24 Drop your take on https://gratipay.com/Gratipay/members/ to zero.

**Comment by sigmavirus24** [comment]
@whit537 done. Thanks. I don't know when my take was every > 0. I don't remember setting that. This should probably stay open given the fact that team members can't cancel their account but my problem is effectively solved. Thanks all!

**Comment by whit537** [comment]
@sigmavirus24 Cool. Best wishes. :-)

**Comment by whit537** [comment]
+1 from @kyzh via [Twitter](https://twitter.com/kyzh_ebooks/status/550668556825010178).
