### ISSUE TITLE
Funding goal clears when logging in

### ISSUE THREAD

**Issue by rummik** [gratipay/gratipay.com#3050]
When logging in I've noticed my funding goal clears.

Repro steps:

1. Log in
2. Set funding goal
3. Log out
4. Log in
5. Check funding goal

Video: https://9k1.us/xV@!/Screencast_2015-01-04_14:08:33.mp4

**Comment by whit537** [comment]
Ah, this is the ticket I was thinking of at [IRC](https://botbot.me/freenode/gratipay/2015-01-05/?msg=28800333&page=1).

> should there be a test for that?

@techtonik Yes! Want to write it? :-)

**Comment by Changaco** [comment]
We already have a regression test, it was with the fix in #3051.
