### ISSUE TITLE
Team funding goals

### ISSUE THREAD

**Issue by seanlinsley** [gratipay/gratipay.com#3057]
@rummik and I discussed the problem of team members being able to indicate how much they need for their work on a team. In the same way that you can set a personal funding goal, it would be useful to be able to set a funding goal for your work on a team. This data could also be used to derive a funding goal for the team as a whole, to better visualize how much a team needs.
##

**Comment by nobodxbodon** [comment]
> @claytron and @ehmatthes are looking for narrative goals.

Merged #759

**Comment by nobodxbodon** [comment]
Merged with [pledge model for raising funding](https://github.com/gratipay/gratipay.com/issues/209)
