### ISSUE TITLE
Show a note under "Statement" if no statement is available in the browser's locale

### ISSUE THREAD

**Issue by colindean** [gratipay/gratipay.com#3061]
When I go to a profile page, I expect to read their statement in my language. When I see that it's missing, I might think that the site hasn't translated something.

It'd be great to have a simple test that shows something like

> The user has not provided a statement in a language you've requested, so this statement is in the user's primarily language.

The test is simple: if the profile shown isn't in the browser's Accept-Language request header, show the above.
##

**Comment by benhc123** [comment]
+1

**Comment by colindean** [comment]
Made a little progress on this tonight. I realized when doing some testing that we don't currently show a statement at all if one is not available in an accepted language. I might need to revisit this or dumb down that check [here](https://github.com/gratipay/gratipay.com/blob/00f4897b5a9ea2b6b8938f8f7dbcfc6ced94e48e/www/%25username/index.html.spt#L23).

@Changaco Thoughts?

**Comment by Changaco** [comment]
We should list the languages in which the user has written a statement, and allow the visitor to switch between them. It's only to keep it simple that I didn't implement this in the original PR.
