### ISSUE TITLE
undefined widget error on profile widgets page

### ISSUE THREAD

**Issue by clone1018** [gratipay/gratipay.com#3065]
So I noticed this issue using Firefox, I can't reproduce it in Chrome.

I get the following error in the js console:
`TypeError: Gratipay.widgets is undefined`
##

**Comment by seanlinsley** [comment]
same

**Comment by nobodxbodon** [comment]
Seems to be not reproducible.
![screen shot 2017-01-14 at 9 44 31 pm](https://cloud.githubusercontent.com/assets/392497/21960488/b5f9278c-daa2-11e6-9fed-438697cdd561.png)
