### ISSUE TITLE
RuntimeError when running jstests

### ISSUE THREAD

**Issue by clone1018** [gratipay/gratipay.com#3069]
```
Running "webdriver:tests" (webdriver) task

RuntimeError: RuntimeError
     (UnknownError:13) An unknown server-side error occurred while processing the command.
     Problem: The path to the driver executable must be set by the phantomjs.binary.path capability/system property/PATH variable; for more information, see https://github.com/ariya/phantomjs/wiki. The latest version can be downloaded from http://phantomjs.org/download.html

     Callstack:
     -> init()

Makefile:70: recipe for target 'jstest' failed
make: *** [jstest] Error 8
```
##

**Comment by techtonik** [comment]
Can it be the failure reason for #3000 too?

**Comment by techtonik** [comment]
Looks like we're hitting https://github.com/webdriverio/webdriverio/issues/342

**Comment by techtonik** [comment]
Travis doesn't fail, because it has `phantomjs` binary in PATH. http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-PhantomJS

**Comment by techtonik** [comment]
Upgrading grunt-webdriver to 0.5.1 (selenium 0.4.4) didn't help.

**Comment by techtonik** [comment]
@clone1018 I can't repeat this error on LXC/LXD setup with grunt-webdriver updated in https://github.com/gratipay/gratipay.com/pull/3490 Can you test if it is still actual? What configuration/system do you run this on?

**Comment by fenryxo** [comment]
I have same issue in Debian Jessie. Phantomjs is in $PATH location, but not found by webdriver. Any ideas?

```
fenryxo@charmeleon:~/dev/projects/gratipay/gratipay.com$ which phantomjs 
/home/fenryxo/dev/tools/phantomjs/bin/phantomjs
fenryxo@charmeleon:~/dev/projects/gratipay/gratipay.com$ phantomjs --version
1.9.8
```

**Comment by whit537** [comment]
I think we should move to a different jstest infrastructure (#3684) and see if that fixes this.

**Comment by whit537** [comment]
Closing now that #3684 is done.
