### ISSUE TITLE
new user with empty statement prompts on profile nav-away

### ISSUE THREAD

**Issue by clone1018** [gratipay/gratipay.com#3081]
When a new user links their account to Gratipay they have a default statement so whenever they go to navigate away from the page it gives them a prompt(). This is a little confusing for new users.
##

**Comment by Changaco** [comment]
From @slaivyn in #3133:

> Every time I leave the profile page I have a popup with a message like "This page is asking you to confirm that you want to leave ; you may loose data".
> I am used to see this popup on other websites when leaving after having actually modified some editable content or at least after being entered (html "focus") in any textarea/input. But in Gratipay profile page, this check is ever activated which is a bit excessive and annoying.
> I think it could be improved adding a check in the callback 'beforeunload.js_edit' in https://github.com/gratipay/gratipay.com/blob/master/js/gratipay/forms.js#L102.
> We need a sort of flag at the form level that would be true if something has been modified in the form so the callback could check the flag and apply "e.preventDefault()" only if the flag is true.
