### ISSUE TITLE
run Gratipay 136

### ISSUE THREAD

**Issue by seanlinsley** [gratipay/gratipay.com#3088]
[135](https://github.com/gratipay/gratipay.com/issues/3045)

**Comment by clone1018** [comment]
You can't click the first balanced link, only the second.

**Comment by seanlinsley** [comment]
We really need to be recording people's legal names, even if we don't publicly display them.

**Comment by seanlinsley** [comment]
There are a number of elsewhere accounts on the review dashboard that 404 when you click on them.

**Comment by seanlinsley** [comment]
From [the documentation](http://inside.gratipay.com/howto/run-payday) it's not clear what we should be looking for when reviewing new accounts.

**Comment by seanlinsley** [comment]
There are also G+ people in the review list that 404; #2965

**Comment by whit537** [comment]
[IRC](https://botbot.me/freenode/gratipay/2015-01-08/?msg=29051342&page=1)

**Comment by rohitpaulk** [comment]
> You can't click the first balanced link, only the second.

Look like there's an extra `/` in the URL. For example, https://dashboard.balancedpayments.com/#//customers/CU70YXZ7dP8kr6GhQ0cZxlRl

**Comment by rohitpaulk** [comment]
@clone1018 - Can you confirm that https://dashboard.balancedpayments.com/#/customers/CU70YXZ7dP8kr6GhQ0cZxlRl works? If so, I'll send in a PR to fix the extra `/`.

**Comment by seanlinsley** [comment]
Apparently people get on the review list for connecting account. For example we have some people who've been on for a year, but just connected a bank account. The review page should list the reason they're on the list to begin with.

**Comment by whit537** [comment]
@rohitpaulk We have a ticket about that. I think it's a bit more complicated because Balanced switched URL formats at some point, and we have instances of both (something like that). I'd search for the ticket but I'm dead. :-)

**Comment by rohitpaulk** [comment]
`SELECT COUNT(*) FROM participants WHERE balanced_customer_href NOT LIKE '/%';` gave me `0`. 

Did the old URL format have two `/`s in it?

**Comment by rohitpaulk** [comment]
I can answer that myself. According to https://github.com/gratipay/gratipay.com/issues/2085, no they didn't.

**Comment by clone1018** [comment]
I feel like we should also include people on this list who have recently started giving a multiple of x to someone.

**Comment by whit537** [comment]
@clone1018 @seanlinsley

**Comment by seanlinsley** [comment]
We should be using something like S3 to store backups.

**Comment by clone1018** [comment]
58 (6 left) accounts reviewed.

**Comment by clone1018** [comment]
Backup taken and verified.

**Comment by clone1018** [comment]
So the digitalocean droplet had a user named whit537 that you should use, this isn't documented.

Remote login for user `root` is disabled on the droplet.

Password reset based authentication works for the remote console in DigialOcean.

**Comment by clone1018** [comment]
Droplet spun up and updated.

**Comment by clone1018** [comment]
```
pid-2114 thread-140040540878592 (MainThread) Traceback (most recent call last):
pid-2114 thread-140040540878592 (MainThread)   File "/home/whit537/gratipay.com/gratipay/cli.py", line 28, in payday
pid-2114 thread-140040540878592 (MainThread)     Payday.start().run()
pid-2114 thread-140040540878592 (MainThread)   File "/home/whit537/gratipay.com/gratipay/billing/payday.py", line 133, in run
pid-2114 thread-140040540878592 (MainThread)     self.payin()
pid-2114 thread-140040540878592 (MainThread)   File "/home/whit537/gratipay.com/gratipay/billing/payday.py", line 157, in payin
pid-2114 thread-140040540878592 (MainThread)     holds = self.create_card_holds(cursor)
pid-2114 thread-140040540878592 (MainThread)   File "/home/whit537/gratipay.com/gratipay/billing/payday.py", line 427, in create_card_holds
pid-2114 thread-140040540878592 (MainThread)     holds = self.fetch_card_holds(participant_ids)
pid-2114 thread-140040540878592 (MainThread)   File "/home/whit537/gratipay.com/gratipay/billing/payday.py", line 407, in fetch_card_holds
pid-2114 thread-140040540878592 (MainThread)     cancel_card_hold(hold)
pid-2114 thread-140040540878592 (MainThread)   File "/home/whit537/gratipay.com/gratipay/billing/exchanges.py", line 236, in cancel_card_hold
pid-2114 thread-140040540878592 (MainThread)     hold.save()
pid-2114 thread-140040540878592 (MainThread)   File "/home/whit537/gratipay.com/env/lib/python2.7/site-packages/balanced/resources.py", line 177, in save
pid-2114 thread-140040540878592 (MainThread)     resp = method(href, data=attrs)
pid-2114 thread-140040540878592 (MainThread)   File "/home/whit537/gratipay.com/env/lib/python2.7/site-packages/wac.py", line 460, in put
pid-2114 thread-140040540878592 (MainThread)     return self._op(self.interface.put, uri, data=data, **kwargs)
pid-2114 thread-140040540878592 (MainThread)   File "/home/whit537/gratipay.com/env/lib/python2.7/site-packages/wac.py", line 512, in _op
pid-2114 thread-140040540878592 (MainThread)     handle_error(ex)
pid-2114 thread-140040540878592 (MainThread)   File "/home/whit537/gratipay.com/env/lib/python2.7/site-packages/wac.py", line 489, in handle_error
pid-2114 thread-140040540878592 (MainThread)     raise ex
pid-2114 thread-140040540878592 (MainThread) HTTPError: HTTPError(status='Conflict', category_code='cannot-void-authorization', additional=None, status_code=409, category_type='logical', extras={}, request_id='OHM95716780975711e49c920230f00c9248', response=None, description='Hold already captured or voided. Your request id is OHM95716780975711e49c920230f00c9248.')
```

**Comment by Changaco** [comment]
That's a similar problem to last week, we didn't actually commit a fix on master.

**Comment by Changaco** [comment]
Actually, maybe it's not the same problem.

**Comment by clone1018** [comment]
Script ran for 15 minutes (0:15:41.935254).

**Comment by clone1018** [comment]
Logs downloaded and uploaded is not documented.

**Comment by clone1018** [comment]
Can't do masspay, need access credentials for Paypal

**Comment by clone1018** [comment]
Can't login to twitter to pin twitter.

**Comment by clone1018** [comment]
Logs downloaded and uploaded. Droplet destroyed.

**Comment by whit537** [comment]
MassPay done and posted back for 79 users. Log downloaded and uploaded.

**Comment by whit537** [comment]
Tweet pinned: https://twitter.com/Gratipay/status/553248050957664257.

```
Week 136—2924 users exchanged $10,581.80: https://gratipay.com/about/stats
```

Minor issues, I would've done:

```
Week 136—2,924 users exchanged $10,581: https://gratipay.com/about/stats.
```

 - comma in nusers
 - no cents
 - period at the end

**Comment by whit537** [comment]
Escrow shuffled.

**Comment by whit537** [comment]
!m @clone1018 @seanlinsley @rummik @Changaco

**Comment by whit537** [comment]
Hey @patcon I got hit by a bus this morning. ;-)

**Comment by whit537** [comment]
Should've marked ★★★ when opened.

**Comment by whit537** [comment]
Actually, reopening until we post-mortem and reticket.

**Comment by patcon** [comment]
First reaction: oh god no.

Upon further reading: HOORAAAAAYYYYY!!

**Comment by clone1018** [comment]
@whit537 We should automate it if you want it so specific. :)

**Comment by whit537** [comment]
I've set up [multi-user access](https://www.paypal.com/us/cgi-bin/webscr?cmd=p/mer/logins-outside) for @clone1018 at PayPal. Doesn't appear that we can use 2fa with that, however. :-/

**Comment by whit537** [comment]
> From the documentation it's not clear what we should be looking for when reviewing new accounts.

I added a new doc on this:

http://inside.gratipay.com/howto/review-accounts

**Comment by whit537** [comment]
> The review page should list the reason they're on the list to begin with.

@seanlinsley The reason is the same for everyone right now:

 - they are unreviewed (`is_suspicious is null`), and
 - they have a Balanced account attached (`balanced_customer_href is not null`).

See the [dashboard source](https://github.com/gratipay/gratipay.com/blob/1770/www/dashboard/index.spt#L13-L14).

**Comment by whit537** [comment]
> We should be using something like S3 to store backups.

We have some backups at Heroku and I store backups offsite. Do think we need a third layer?

**Comment by whit537** [comment]
> We should automate it if you want it so specific.

Begun in #3094.

> Can't login to twitter to pin twitter.

Not possible from the API. :-(

https://twittercommunity.com/t/pin-a-tweet-with-the-twitter-api/13048

**Comment by whit537** [comment]
> We really need to be recording people's legal names, even if we don't publicly display them.

Reticketed as #3098.

**Comment by whit537** [comment]
> I feel like we should also include people on this list who have recently started giving a multiple of x to someone.

Reticketed as #3099

**Comment by whit537** [comment]
> So the digitalocean droplet had a user named whit537 that you should use, this isn't documented.
> 
> Remote login for user `root` is disabled on the droplet.
> 
> Password reset based authentication works for the remote console in DigialOcean.

@clone1018 Is there an action item here? Please reticket if so.

**Comment by whit537** [comment]
> Logs downloaded and uploaded is not documented.

Doc reviewed in https://github.com/gratipay/inside.gratipay.com/commit/bcff70a002413f958f0001106fb1cdda21a0264e.

http://inside.gratipay.com/howto/run-payday

**Comment by whit537** [comment]
Pretty sure that's everything. Great work @clone1018, et al.! :dancer:

**Comment by patcon** [comment]
fwiw, this whole thread is a case-study in being awesome.

**Comment by seanlinsley** [comment]
>> We should be using something like S3 to store backups.

>@seanlinsley We have some backups at Heroku and I store backups offsite. Do think we need a third layer?

What @clone1018 and I had discussed was an append-only S3 bucket where database backups and payday logs could be pushed, preferably automatically.

**Comment by whit537** [comment]
@seanlinsley Okay, I'll let you make a ticket. :-)
