### ISSUE TITLE
missing avatars on search

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3090]
https://gratipay.com/search?q=cheese

![screen shot 2015-01-08 at 11 46 32 am](https://cloud.githubusercontent.com/assets/134455/5666203/0779f300-972c-11e4-8702-ebf4f9df4daa.png)

**Comment by Changaco** [comment]
Looks fine to me:

![gratipay-3090](https://cloud.githubusercontent.com/assets/1581590/5666321/0e80b796-975f-11e4-86b9-1474a5101d46.png)

**Comment by whit537** [comment]
Weird. I get a default avatar for https://gratipay.com/cheeseplus/:

![screen shot 2015-01-08 at 11 57 05 am](https://cloud.githubusercontent.com/assets/134455/5666434/7f3d6434-972d-11e4-91d9-1d1a7f12555e.png)

**Comment by seanlinsley** [comment]
I see the same thing as @whit537 here.

**Comment by Changaco** [comment]
Since the avatar I'm seeing isn't the one currently displayed on Twitter, I'm guessing that me still being able to load the old image is due to cache lag, and I think this should be closed as duplicate of #900.

**Comment by whit537** [comment]
@Changaco We should still fall back to the default avatar for search results, no?

**Comment by Changaco** [comment]
This behavior isn't specific to the search page, you can see the same thing on community pages. We don't fall back to the default avatar in these cases because they're displayed using the CSS `background` property instead of an `<img>` tag, so we can't use the `onerror` attribute.

**Comment by whit537** [comment]
Okay.
