### ISSUE TITLE
If I tip someone nothing, prompt me to Give/Donate, not Edit

### ISSUE THREAD

**Issue by colindean** [gratipay/gratipay.com#3093]
I'm sitting here looking at a profile page, and there's not really a call to action. 

The left column has something that looks like it: big numbers showing what I give. Below it, it says Edit. OK. Maybe I want to edit that? What does that mean? \*shrug\*

Maybe if I'm already giving something to someone, leave it say "Edit". Otherwise, perhaps it should have a stronger call to action: "Give to `$username`" or "Donate to `$username`".

**Comment by colindean** [comment]
@Changaco [says](https://github.com/gratipay/gratipay.com/pull/3095#issuecomment-69310542):

> This isn't correct, because once you save the tip the button still shows "Give to foo", when it should be "Edit".

Reopening so I can take a look at it when I get a chance.

**Comment by benhc123** [comment]
+1.
