### ISSUE TITLE
move Twitter app from whit537 account to Gratipay account

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3094]
Twitter's [contact](https://support.twitter.com/forms) doesn't have a relevant funnel. Do they have a support email address?

**Comment by whit537** [comment]
I sent a mail to support@twitter.com. Hasn't bounced yet. :-)

**Comment by whit537** [comment]
Oh well. :-/

![screen shot 2015-01-09 at 1 05 05 am](https://cloud.githubusercontent.com/assets/134455/5676030/9c1aedec-979b-11e4-8323-f3f594211695.png)

**Comment by whit537** [comment]
https://twittercommunity.com/t/how-can-i-move-a-deployed-app-to-a-different-developer-account/13823

**Comment by whit537** [comment]
I submitted transfer requests for both the `gratipay` and `gratipay-dev` apps.

**Comment by whit537** [comment]
re: `Gratipay`:

> For security reasons, we can only process this request if the email address you’re using to file this ticket belongs to a domain affiliated with the organization which registered your application. Could you please refile or respond to this ticket from a company account?

and re: `gratipay-dev`:

> Thanks for reaching out. For security purposes, we require that developers write in from the Twitter account and email address that currently owns the API key. Please file a new request from that account.

I replied to both cc'ing vendors@gratipay.com, and then replied from there. Hopefully that's sufficient.

**Comment by whit537** [comment]
https://gratipay.freshdesk.com/helpdesk/tickets/1586
https://gratipay.freshdesk.com/helpdesk/tickets/1587

**Comment by whit537** [comment]
Re: `gratipay-dev`:

> Thank you for writing in. We have transferred ownership of the app to the designated account.

Didn't receive anything re: `Gratipay`, and `gratipay-dev` is still showing up under whit537 and not Gratipay.

> Thanks for the update. However, I'm still seeing gratipay-dev connected to @whit537 instead of @Gratipay. Is there a time lag for this transfer?

**Comment by techtonik** [comment]
Time lag. Check again?

**Comment by whit537** [comment]
> Bump. Can you please help me move the Gratipay app from @whit537 to @Gratipay? Thanks! :-)

**Comment by whit537** [comment]
D'oh!

> Hello,
>
You tried to update a case that has been closed. Please submit a new case at http://support.twitter.com/forms. You can also visit our help center at http://support.twitter.com for self-help solutions to common problems.
>
Thank you!

**Comment by clone1018** [comment]
Wait so they closed it without responding or doing anything?

**Comment by whit537** [comment]
@clone1018 Sort of. They moved `gratipay-dev` but ignored `Gratipay`. :-/

**Comment by whit537** [comment]
I submitted a new transfer request.

**Comment by techtonik** [comment]
Yea, decomposition is the stuff that modern trackers lack.

**Comment by whit537** [comment]
> Thank you for writing in. We have transferred ownership of the app to the designated account.

Confirmed, and signing in with Twitter still works. Huzzah!

**Comment by techtonik** [comment]
!m @whit537
