### ISSUE TITLE
record legal names

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3098]
@seanlinsley on #3088:

> We really need to be recording people's legal names, even if we don't publicly display them.

Related to #987.

**Comment by benhc123** [comment]
Yes, I think this is a good idea.

**Comment by kaguillera** [comment]
+1

On January 12, 2015, at 3:39 PM, Ben Holden-Crowther <notifications@github.com> wrote:

Yes, I think this is a good idea.

**Comment by techtonik** [comment]
What is the cause for that +1's? The less private information we scavenge, the more resistant we are to what happened to Sony etc.

**Comment by benhc123** [comment]
@techtonik, I think comparing this to Sony is wrong.

**Comment by rummik** [comment]
@techtonik We already ask for it on credit card forms.  Unfortunately, it may also be a necessary evil to have it, along with some other info, privately for tax reasons.  It shouldn't ever be displayed publicly though, since there's no good reason to do so.

**Comment by whit537** [comment]
Closing in favor of #2449.
