### ISSUE TITLE
Create a set of design guidelines

### ISSUE THREAD

**Issue by rummik** [gratipay/gratipay.com#3102]
The idea is to standardize on border radius, padding, gutters, how to use colors, when and where borders are appropriate, etc, throughout the site.  This will help us have a more unified style across Gratipay and sub-projects (ex: widgets, and future mobile apps)

_Edit: Yes, I am volunteering :)_

**Comment by whit537** [comment]
@brareme was discussing something similar in #1172.

**Comment by rummik** [comment]
This would apply to images too.  I hadn't seen that the discussion moved to inside.gratipay.com, so I'll move this over there in a bit

**Comment by whit537** [comment]
Okay.

**Comment by rummik** [comment]
Incidentally, @whit537, I didn't see that conversation had picked back up on that ticket either. :P
