### ISSUE TITLE
Email address verification email bug when email address contains + (plus sign)

### ISSUE THREAD

**Issue by jhannah** [gratipay/gratipay.com#3110]
Howdy, 

You sent me an email Subject: "Connect to Foo on Gratipay?" containing a link to verify my email address. That link didn't work, because my email address has a + character in it, and you didn't escape the + in the URL you sent in the email.

Incorrect URL:
https://gratipay.com/Foo/emails/verify.html?nonce=...&email=jay+waterpolice@jays.net

Correct URL:
https://gratipay.com/Foo/emails/verify.html?nonce=...&email=jay%2Bwaterpolice@jays.net

`+` becomes `%2B`

Thank you!

**Comment by whit537** [comment]
Thanks for the report, @jhannah. I thought we paid attention to this case but I guess not sufficiently. :-)

**Comment by whit537** [comment]
+1 https://gratipay.freshdesk.com/helpdesk/tickets/1613

**Comment by whit537** [comment]
@rohitpaulk in [IRC](https://botbot.me/freenode/gratipay/2015-01-22/?msg=30233314&page=2):

> [W]e do sanitize the email before creating the link. https://github.com/gratipay/gratipay.com/blob/master/gratipay/models/participant.py#L556-L557

**Comment by rohitpaulk** [comment]
@Julian on #3141: 

> I've only tried this with my own email address to run into the issue, so I don't know which of the two options in the title it is, but if your email address looks like Julian+Gratipay@GMail.com, it's inserted literally into the email query string parameter in the confirmation email's link, which then will get unquoted, and the confirmation will fail because it's interpreted as a space. Emails should be quote(_plused), so that the plus is inserted as %2B, which after manual changing, made the confirmation go through.

**Comment by whit537** [comment]
+1 https://gratipay.freshdesk.com/helpdesk/tickets/1945

**Comment by whit537** [comment]
I am getting bit by this trying to set up a team for Aspen:

![screen shot 2016-03-02 at 9 39 58 am](https://cloud.githubusercontent.com/assets/134455/13463578/e44b90b8-e05a-11e5-9fd6-7e0e9dc3c1f3.png)

**Comment by whit537** [comment]
+1 from @BrettTrotter at https://github.com/gratipay/gratipay.com/issues/3964.

**Comment by whit537** [comment]
PR started in https://github.com/gratipay/gratipay.com/pull/3965.

**Comment by whit537** [comment]
Deploying the fix in #3965 ...

**Comment by whit537** [comment]
Blam! Wanna retry, @jhannah @Julian @BrettTrotter?

Plus in email working for me now:

![screen shot 2016-04-04 at 4 20 34 pm](https://cloud.githubusercontent.com/assets/134455/14262008/567fed42-fa81-11e5-8bd4-950d5b448369.png)

**Comment by whit537** [comment]
https://twitter.com/Gratipay/status/717085879995645953
