### ISSUE TITLE
Nicer error pages on search results needed

### ISSUE THREAD

**Issue by benhc123** [gratipay/gratipay.com#3115]
E.g. https://gratipay.com/on/twitter/adhsjakdjsdkjsajdhksda/
https://gratipay.com/on/facebook/adhsjakdjsdkjsajdhksda/
https://gratipay.com/on/github/adhsjakdjsdkjsajdhksda/
https://gratipay.com/on/bitbucket/adhsjakdjsdkjsajdhksda/

I'm not sure if this info is being fetched via JSON or something else but we should do something better with these error responses from APIs.

**Comment by clone1018** [comment]
Haha, awesome.

!m @benhc123

**Comment by kaguillera** [comment]
I am working on this but I was want to know if the intention of this issue is to improve the error pages for only the results of the Search or the error pages in general when a response other than a 200 is to be presented via the current error.spt

**Comment by Changaco** [comment]
Done in #3146.
