### ISSUE TITLE
Add ability to enter Payment Details for bank withdrawal

### ISSUE THREAD

**Issue by podarok** [gratipay/gratipay.com#3116]
There are some type of bank accounts that can be loaded only by entering Payment Details with a account number.
Currently I see that there are no ability to fill that in 
![image](https://cloud.githubusercontent.com/assets/563412/5740640/d9e316ce-9c0d-11e4-88fa-3e4173102777.png)

Good to have it, that can help a lot of people to withdraw their tips
##

**Comment by whit537** [comment]
Thanks for the report, @podarok. Could you give me an example of what "Payment Details" would be?

**Comment by podarok** [comment]
```ATTN: G123456```
This is for accounts from epayservices

**Comment by whit537** [comment]
Interesting, okay. I think we would need the underlying Balanced APIs to support this. Do you know if they do?

**Comment by podarok** [comment]
No I don't
This is a pretty standard field for wire transfers. They call it Payment Details. You can fill it with any text.

**Comment by whit537** [comment]
Okay, want to look into the [Balanced APIs](https://docs.balancedpayments.com/1.1/overview/)? If you can't find anything you can ask them on [their API repo](https://github.com/balanced/balanced-api/issues).

**Comment by Changaco** [comment]
It looks like [Stripe's API](https://stripe.com/docs/api) (#3245) doesn't support this either.
