### ISSUE TITLE
admins should be able to search everyone

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3121]
`is_searchable` should only apply to public/user search. Hidden users should still be searchable by admins. (I tried finding someone during review on #3118.)
##

**Comment by kzisme** [comment]
Fairly certain this issue relates [here](https://github.com/gratipay/gratipay.com/blob/f9749d98d2853701968adf437e9436deca1741aa/www/search.spt)

**Comment by rohitpaulk** [comment]
Yep, all the queries on that page seem to filter participants by `is_searchable`. We could make those constraints dynamic, and relax them depending on whether the logged in user is an admin or not.

**Comment by mattbk** [comment]
PR is #4190, ready for review.

**Comment by mattbk** [comment]
This accidentally made it in. Explanation in https://github.com/gratipay/gratipay.com/pull/4190#issuecomment-269891592.
