### ISSUE TITLE
admin should be able to see giving/receiving amounts

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3122]
In the sidebar, currently says `[hidden]`, maybe for admin keep the brackets to indicate hiddenness: `[100.00]`.

**Comment by threadmetal** [comment]
Definitely a feature you should have. Maybe require a click to reveal, though?

**Comment by whit537** [comment]
@threadmetal Want to give us a PR? :-)

**Comment by mattbk** [comment]
This works now.
