### ISSUE TITLE
Get some kind of callback from Gratipay after user successfully donated

### ISSUE THREAD

**Issue by synconme** [gratipay/gratipay.com#3126]
At our project we need to identify somehow those users, which donated to our project using Gratipay as we provide some additional features and support to donated users. I understand that Gratipay main feature is anonymity of donations, but we do not need any personal information of donator, just some API request for example, after successful donation. Do you guys think it may be possible?

Cheers,
Alex

**Comment by rohitpaulk** [comment]
>  we need to identify somehow those users, which donated to our project using Gratipay
>  just some API request for example, after successful donation

Wouldn't this in fact **reveal** the identity of the giver? 

As a side note, https://github.com/gratipay/gratipay.com/pull/3112 might be worth looking at.

**Comment by synconme** [comment]
Thanks for pointing me in this direction @rohitpaulk !
What I was thinking is: if there could be some way to send customer from our project page to Gratipay with generic ID, after a successful donation Gratipay would send a callback to us, with same ID, that way we know that supporter donated to our project. This way no private information is being revealed.

**Comment by rohitpaulk** [comment]
> we know that supporter donated to our project

This is exactly what we want to prevent, and why tips are anonymous. If you know that a user donated to your project, those tips are no longer **no-strings attached** and **anonymous**.

> This way no private information is being revealed.

I don't think that's the concern here.

**Comment by whit537** [comment]
@synconme Thanks for the feedback! #3112 is indeed the next step we'll be taking in this direction, so keep an eye out there. See also #236 for background discussion.

> This is exactly what we want to prevent, and why tips are anonymous.

@rohitpaulk Long story short: we're going to be loosening up on the anonymity in order to better support business use-cases for Gratipay. This came up at [the retreat](https://medium.com/gratipay-blog/at-our-second-retreat-we-met-our-third-users-5b473a2d1464). In fact, could I ask for a favor? :-) If/when you get around to watching the videos of session 1, could you listen for the part where I say "we've never truly been no-strings-attached all along" (or words to that effect) and link that segment on #236 for reference?

**Comment by whit537** [comment]
cc: @rummik You were interested in this, ya?

**Comment by rummik** [comment]
@whit537 Yup.

Been thinking about it for a while now.  I'd like to see the API expanded for this, in particular, as an OAuth option that will let someone opt-in to showing that they're giving to the person/group behind the app they're logging into.  This would provide some proof that this person is the one giving, and make it so they don't have to enable the opt in globally

**Comment by synconme** [comment]
@whit537 Thanks, that would be a very useful feature, I believe we are not alone who looking for this.
Of course, it is up to the donator, if he/she wants to reveal the fact of donation to public, but the option to make it visible to receiver should be available as well.

**Comment by incni** [comment]
@whit537 I agreed with @rummik the proof of giving would be a very logical addition to API, especially if donator want to be known to public.

**Comment by whit537** [comment]
Actually, let's use #1546 for this. Closing as a duplicate.
