### ISSUE TITLE
something weird happened

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3128]
Reticketing from https://github.com/gratipay/gratipay.com/issues/3118#issuecomment-70203399:

> I got charged by Gratipay.com for 10.00 and then credited by Gittip for 10 dollars...

cc: @clone1018

**Comment by whit537** [comment]
@clone1018 I'm not seeing this obviously for 137 on your history page. Can you say more about what you're seeing? You're looking at your bank/cc statements, I assume?

**Comment by clone1018** [comment]
This was on my bank statement:

![fa7gbpl](https://cloud.githubusercontent.com/assets/226638/5825319/f9d91e32-a0af-11e4-8a5a-e583a8ddd921.png)

**Comment by clone1018** [comment]
Still is as of right now.

**Comment by whit537** [comment]
The $10 pending makes sense because we placed a hold on your card.

**Comment by whit537** [comment]
Maybe the +10 from Gittip is what it looks like for you when we cancel a hold?

**Comment by whit537** [comment]
I don't see any other transactions for you on Jan 15 in Balanced.

**Comment by whit537** [comment]
Think we should take this up with Balanced to see if there's anything we can do about it? At the least it'd be great to s/Gittip/Gratipay.

**Comment by clone1018** [comment]
If I'm the only one, probably not, may be a bug with my bank? But if others experienced this then yes bring it up with balanced.

**Comment by whit537** [comment]
There's two issues here:

 - Holds are represented as debit followed by a credit.
 - The credit is named as `Gittip`.

I think you're more concerned about the former. I bet that's just how Simple represents cancelled holds. I think it's normal, expected behavior.

The latter is a bug, though I'm not sure it'd be worth the effort to squish.
