### ISSUE TITLE
Coordinate with @kaguillera on Wednesday bus rides to/from Ambridge

### ISSUE THREAD

**Issue by rummik** [gratipay/gratipay.com#3129]
@kaguillera I'm opening this ticket since I know we both are active on GitHub.  Though, we should probably discuss this off GitHub xD

Do you have a preferred method of contact?  I'm always on IRC.  Email is slow for me, since I don't typically get notifications for it, but it's an option.

**Comment by kaguillera** [comment]
Done

**Comment by whit537** [comment]
See yinz tomorrow, I hope! :dancer:

**Comment by kaguillera** [comment]
Yes see you tomorrow

**Comment by rummik** [comment]
Yup.  I'll be there.
