### ISSUE TITLE
learn from db snafu

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3132]
We [accidentally dropped the production database this morning](https://botbot.me/freenode/gratipay/2015-01-22/?msg=30194214&page=1). I'm drafting [a blog post about it](https://medium.com/@whit537/e3ba2f16e1f6). What are we going to do to prevent this sort of thing from happening again? Suggestions so far in IRC:
- bring back the testing seatbelt (#1991)
- add a check on host of URL&mdash;confirm if remote
- tighten up permissions so drop schema isn't available
- figure out how to restore recently dropped tables
- [use a system trigger](http://www.pateldenish.com/2014/02/preventing-human-errors-in-postgres.html) to prevent drastic actions ([code](https://gist.github.com/rohitpaulk/3dac33e28ae2da282bee))
##

**Comment by seanlinsley** [comment]
> tighten up permissions so drop schema isn't available

Seems like it shouldn't even be possible to modify data using `heroku pg:psql` without at least some sort of confirmation.

Additionally, if psql supports coloring we could make the console red when you have write access.

**Comment by seanlinsley** [comment]
Things like this make me wish that there was a database that would store all changes, for eternity.

**Comment by clone1018** [comment]
@seanlinsley http://www.postgresql.org/docs/9.3/static/wal-intro.html

**Comment by whit537** [comment]
GitHub's go-round a few years ago:

https://github.com/blog/744-today-s-outage

**Comment by whit537** [comment]
@seanlinsley Bruce pointed out http://www.datomic.com/ a while back.

**Comment by dekkers** [comment]
Point-in-Time Recovery would have prevented the data loss:
http://www.postgresql.org/docs/9.4/static/continuous-archiving.html

**Comment by whit537** [comment]
Thanks @dekkers. I'm not sure what we have access to since we're on Heroku Postgres.

**Comment by benhc123** [comment]
Constantly make back-ups?

**Comment by whit537** [comment]
@rohitpaulk Hindsight is 20/20. :-) What action should we take to close this ticket?

**Comment by whit537** [comment]
Gosh. Was that two years ago? 😞

**Comment by rohitpaulk** [comment]
I think this was closed by mistake..
