### ISSUE TITLE
A EUR bank account for Gratipay, LLC?

### ISSUE THREAD

**Issue by slaivyn** [gratipay/gratipay.com#3134]
In France I could open a USD bank account in my bank. Isn't it possible for Gratipay, LLC to open a EUR account to be able to accept that currency? Doing so there won't be any conversion between USD and EUR. Users would be able to accept both currencies.

I am sure the solution is not so easy but I would like to understand where is blocking point (impossible to open EUR bank account, not possible to handle this at the bank level, whatever)

I apology if I ask questions that have already been answered.
##

**Comment by Changaco** [comment]
Relevant: #1379.
