### ISSUE TITLE
*Apparent* multi-currency support

### ISSUE THREAD

**Issue by slaivyn** [gratipay/gratipay.com#3135]
As discussed in #1165, multi-currency support is not trivial.

What about using USD as a "transparent-currency" for non USD users? Explanations: my daily currency is EUR so I would like:
- to see my balance in EUR ;
- to define the amounts I give in EUR so that it would not change when the ratio USD/EUR evolve ;
- the people who give to me to be able to give (or to have the impression that they are giving) in EUR because most people are really not used to manipulate USD and are frightened by it;
- the debit on my credit card appearing to be in EUR = calculated to be equal to 10€ and not $10.

An basic example: Alice lives in Italy and she wants to give 0,50€ a week to Bob who lives in Germany. They are both in the Euro zone and don't have USD account. Initial balances are: 10€ for Alice and 0€ for Bob.
- Alice set a periodic payment of 0,50€ to Bob ;
- on each Friday:
  - 0,50€ is converted in USD ; today it's $0.56 ;
  - Bob receives $0,56 to its account which are converted back to EUR: 0,50€
- after the first pay day, Alice has 9,50€ and Bob has 0,50€.

It think this is possible by regularly getting the USD/EUR conversion ratio and silently do the conversion.

The (big) drawback is that the payment value would be fix (no more depending on the conversion ratio) but the balance would not be any more. Example: if today Alice has 10€ with 1 USD = 0.89 EUR, she could have 9€ some days later if USD falls to 0.80 EUR.
To be clear: Alice would not be using more money with this _apparent_ multi-currency system but it would be more visible to her and could be confusing so it should be clearly explained.

On some website BTC payments are handled this way. The price is in EUR and there is a double silent and instant conversion and a transfer behind: "EUR -> BTC" + "BTC transfer" + "BTC -> EUR". Maybe this is how BTC payments are handled in Gratipay. I have not looked into it for now.
##

**Comment by benhc123** [comment]
This is certainly a good idea. I would worry that using other currencies (e.g. GDP) might mean we Gratipay needs to deal with extra taxes from other countries. If using Euros, EU VAT might be an issue.

**Comment by slaivyn** [comment]
As Gratipay payments are gifts (there is no counterpart asked from the giver to the receiver), if the receiver is a person (not a company) there should not be any VAT; must be confirmed by a lawyer.

But if VAT is applicable, I think it is whatever the currency used is.

I just created issue #3140 to discuss this point.

**Comment by nobodxbodon** [comment]
Re-ticketed to https://github.com/gratipay/inside.gratipay.com/issues/974 for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.
