### ISSUE TITLE
Send introductory emails

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#3137]
It'd be nice to send people email notifications when they perform core actions **for the first time** on Gratipay. For example, when they setup their first tip we could send an email explaining how tips are recurring, how we don't charge anything but the cost of moving money, how you can view tips on your giving page etc. Similarly, when they receive their first payout - we could send out email explaining the various payout options that exist, and how they can setup each. 

We could also send emails to people who haven't done any of these actions yet (people who just signup and don't visit again), but that _might_ be considered as spam. 
##

**Comment by benhc123** [comment]
You wouldn't want this to become annoying. What if people did every action in one day. I do agree that gratipay should use email more though.
