### ISSUE TITLE
Documentation of when first withdraw will initiate when bank details are added.

### ISSUE THREAD

**Issue by bkuhn** [gratipay/gratipay.com#3138]
I just added a bank account to my account.  My Account screen now reports:

"Withdrawing Money
Bank Account
Your bank account is working "

There is no information on how to initiate a withdraw for the existing balance.  The Bank account edit screen says:
"When you receive money on Gratipay we'll automatically deposit it into your bank account. If you don't connect a bank account then your money will accumulate within Gratipay unless you regift it to others."

It doesn't speak to what happens when you add a bank account after money has accumulated.

I'm not sure that you need a button to force the issue, especially if withdraw of existing balance is automatic.  However, these screens should clearly explain what happens when you add a bank account.

**Comment by whit537** [comment]
Thanks for the report, @bkuhn, and sorry for the confusion. The short story is that we deposit to your bank account during our weekly "payday" on Thursday (deposit normally clears on Friday). Leaving this open for a doc change.
