### ISSUE TITLE
Is VAT applicable to Gratipay payments and which VAT?

### ISSUE THREAD

**Issue by slaivyn** [gratipay/gratipay.com#3140]
This are the money flows occurring on Gratipay:
Bob's bank account --1--> Bob's account --2--> Alice's account --3--> Alice's bank account

Is there any VAT applicable if Alice or Bob is for example in Euro zone? And if so, which of this flow is concerned?

**Comment by slaivyn** [comment]
As Gratipay payments are gifts (there is no counterpart asked from the giver to the receiver), if the receiver is a person (not a company) there should not be any VAT; must be confirmed by a lawyer.

**Comment by Changaco** [comment]
It's Alice's job to deal with taxes.

**Comment by slaivyn** [comment]
Basically I agree with you: if VAT is applicable Alice has to deal with it.

But I think it would be helpful to discuss whether VAT is applicable or not (in which cases) and to explain this on Gratipay website.
