### ISSUE TITLE
add a "reset" button for team memberships

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3144]
We're finding with the [Gratipay team](https://gratipay.com/Gratipay/members/) that we accumulate many team members who then drift away. Over time, the team gets cluttered up with people who aren't really part of the team anymore. They're probably not taking much so it's not a huge deal, but even a little bit adds up over time when we're constantly accumulating these "drifters" (so to speak).

One option is to simply remove those people entirely from the team. We did that once already (~~someone want to find the ticket?~~ #1899). @clone1018 is asking at https://github.com/gratipay/inside.gratipay.com/issues/136#issuecomment-71674228 for another round of clean-up.

I don't like brute-force removing people from the team. I'd rather drop people back to 1¢, because then at least they have the power to start upping their take again without first having to ask the team owner to add them back.

So let's add a reset button to the team page so the team owner can drop people back to a penny. Let's modify the team page to hide people who are only taking a penny.

Waddya think, @clone1018?
##

**Comment by clone1018** [comment]
The people I want removed are already at a penny.

**Comment by whit537** [comment]
@clone1018 Would hiding (or aggregating) them by default on the team listing be satisfactory?

**Comment by clone1018** [comment]
They're not a part of the team anymore though?

**Comment by whit537** [comment]
@clone1018 I think removal should be a two-step process:

1. After a period of inactivity, we drop you to a penny. You get an email notice saying as much.
1. After a year, we drop you entirely.

We could even make step two automatic for all teams, maybe?

**Comment by rohitpaulk** [comment]
Here's the ticket: https://github.com/gratipay/gratipay.com/issues/1899

**Comment by whit537** [comment]
!m @rohitpaulk :dancer:

**Comment by whit537** [comment]
[IRC](https://botbot.me/freenode/gratipay/2015-01-27/?msg=30586622&page=1)

**Comment by Changaco** [comment]
Maybe we should separate memberships from takes. When people become inactive we drop their takes to zero, but that wouldn't drop them from the team anymore, and they could start taking again if they come back. If they don't come back for some time then we drop them from the team entirely.

**Comment by kaguillera** [comment]
+1
