### ISSUE TITLE
Support for certain causes pt.2

### ISSUE THREAD

**Issue by techtonik** [gratipay/gratipay.com#3149]
This is a rewording of unclear #3049.

Provide a way to donate for certain `cause`. A person may be contributing to different causes, so there could be a way to have a public indicator that gives information that cause `techtonik/patch.py` receives $xx.xx.

The benefit over #222 and #2011 is that an account holder configures causes himself. Causes are no substitute for notes. The `cause mechanism` may allow to inform people about current focus, set goals, which results in better communication.

Causes is an opt-in mechanism. If there is no cause, the donation goes "just to that person". But if there is, the account owner can see the distribution and may adjust his/her focus accordingly.
##

**Comment by whit537** [comment]
I floated a similar idea at the retreat. @clone1018 @seanlinsley Do you remember the name I was using for this? It was like "activity" or "project" or something.

**Comment by whit537** [comment]
@rummik I talked about it with you, since you have lots of different projects going. :) Ring any bells?

**Comment by rummik** [comment]
@whit537 Nothing really comes to mind, though I do remember some related discussions about perks/rewards, which could almost be used for this, in a slightly confusing way xD
