### ISSUE TITLE
switch to autoescape

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3152]
Reticketing from #722. See there for initial notes (should copy over here). It's entangled with i18n.

**Comment by Changaco** [comment]
Do we want [partial](https://github.com/gratipay/gratipay.com/compare/autoescape) or [full](https://github.com/gratipay/gratipay.com/compare/autoescape-alt) autoescape ?

**Comment by whit537** [comment]
[IRC](https://botbot.me/freenode/gratipay/2015-02-06/?msg=31421995&page=1)

**Comment by whit537** [comment]
Digesting the difference between partial and full.

In both cases, we are modifying the two text-related i18n functions, `get_text` and `n_get_text`. The crucial difference I see is between:

```python
from markupsafe import Markup
return Markup(s.format(*a, **kw))
```

and

```python
from markupsafe import escape
return escape(s).format(*a, **kw)
```

One operates on the string after it is formatted, the other on the string before it is formatted.

**Comment by whit537** [comment]
What is `Markup`? Why are we using it there instead of `escape` in both cases?

**Comment by whit537** [comment]
http://www.pocoo.org/projects/markupsafe/

**Comment by whit537** [comment]
[`escape` returns a `Markup`](https://github.com/mitsuhiko/markupsafe/blob/0.23/markupsafe/_native.py#L15-L28)

**Comment by whit537** [comment]
```python
>>> from markupsafe import Markup, escape
>>> Markup('foo')
Markup(u'foo')
>>> escape('foo')
Markup(u'foo')
>>> Markup('<foo>')
Markup(u'<foo>')
>>> escape('<foo>')
Markup(u'&lt;foo&gt;')
>>>
```

So calling `Markup` in python is equivalent to using the `|safe` filter in Jinja2? And `escape` is equivalent to `|e`?

**Comment by Changaco** [comment]
Yes.

**Comment by whit537** [comment]
k

**Comment by whit537** [comment]
Alright, so we know the `s` strings are all safe, because we write those. That leaves the `a` and `kw`. Those could potentially be user input that we'd want to escape, but in a number of cases we are passing our own markup in, which is safe.

If I'm reading the partial approach right, we are trusting all gettext arguments, relying on explicit opt-in to escape values, such as at https://github.com/gratipay/gratipay.com/blob/5671008bb49fc8cadf8ecf880dacf4bc2319c637/emails/verification.spt#L5. If my understanding is correct, then I prefer the full approach, since `e(s).format(*a, **kw)` will escape values from `a` and `kw` that aren't explicitly marked safe.

```python
>>> escape('foo{0}').format('')
Markup(u'foo')
>>> escape('foo{0}').format(' bar')
Markup(u'foo bar')
>>> escape('foo{0}').format(' <bar>')
Markup(u'foo &lt;bar&gt;')
>>>
```

We should fail open.

**Comment by whit537** [comment]
Done in #3164.
