### ISSUE TITLE
Update ssl cert to one signed with sha2

### ISSUE THREAD

**Issue by greggles** [gratipay/gratipay.com#3160]
The current ssl cert for gratipay.com is signed with sha1. It would be great to use a sha2 certificate, both because it is better for security and because Chrome is starting to warn users about sha1-signed certs which can decrease trust in the gratipay brand.

See http://googleonlinesecurity.blogspot.com/2014/09/gradually-sunsetting-sha-1.html for details on when/why they are doing this.

It *should * be a fairly straightforward change: get a new cert from the issuer and put it in place.

**Comment by whit537** [comment]
> HTTPS sites whose certificate chains use SHA-1 and are valid past 1 January 2017 will no longer appear to be fully trustworthy in Chrome’s user interface.

Our cert expires August 27, 2016, and yet:

![screen shot 2015-02-05 at 4 03 50 pm](https://cloud.githubusercontent.com/assets/134455/6069234/aa9a2db8-ad50-11e4-8c4e-e61dbeecfbe2.png)

**Comment by whit537** [comment]
Nobody should be trusting a payments platform with a ![screen shot 2015-02-10 at 3 59 08 pm](https://cloud.githubusercontent.com/assets/134455/6136327/ca0cc516-b13d-11e4-9cc6-82b766078732.png).

**Comment by whit537** [comment]
> Our cert expires August 27, 2016, and yet:

Explanation:

> Beginning in January 2015, Chrome will show a warning for sites with SHA-1 certificates expiring after June 1, 2016.

A closer reading of Google's blog post bears this out.

**Comment by whit537** [comment]
[IRC](https://botbot.me/freenode/gratipay/2015-02-12/?msg=31873165&page=1)

**Comment by whit537** [comment]
The hash function is relevant when creating the CSR (include `-sha256` in the options to `openssl req`), and the way to inspect a CSR to determine what hash function was used to create it is:

```
$ openssl asn1parse -in server.csr
```

**Comment by whit537** [comment]
P.S. I usually refer to https://devcenter.heroku.com/articles/ssl-endpoint when I have to do this. At some point we'll want a howto on IG.

**Comment by whit537** [comment]
Looks like StartSSL wants me to revoke the previous certificate, which carries a $24.90 charge ... and a race condition. :-/

**Comment by whit537** [comment]
Revocation request submitted.

**Comment by whit537** [comment]
And I emailed them about the race condition.

**Comment by whit537** [comment]
It seems that StartSSL always uses a subdomain as the common name, adding the root as an alternate. The first subdomain added during the cert wizard becomes the common name, so to avoid revocation (which does carry the risk of downtime, in addition to the fee), they advised that I issue the certificate using a different subdomain as the common name.

**Comment by whit537** [comment]
They cancelled the revocation request. I'm waiting for the cert to be cleared.

**Comment by whit537** [comment]
>I just noticed that this domain belongs to Gratipay, LLC whereas the validated entity is Gittip, LLC. According to our policy we shouldn't issue this certificate.
>
>Please review the Subscriber Obligations at https://www.startssl.com/policy.pdf in particular:
>
- Never obtain and use a certificate for a domain name and/or web site that belongs to a different entity other than the entity referenced in the certificate and the entity that has been validated, e.g. a validated individual may obtain certificates for domain names and/or web sites he/she owns, but not for other individuals or organization, even if allegedly authorized or requested. Likewise a validated organization shall not obtain a certificate for a domain and/or web sites belonging to another entity or third party.

Me:

> Okay. We did rename Gittip, LLC to Gratipay, LLC. Tomorrow I'll go ahead and submit a new organization validation, and then proceed with the certificate request.

**Comment by whit537** [comment]
I started the verification process.

**Comment by whit537** [comment]
Extended validation reticketed as https://github.com/gratipay/inside.gratipay.com/issues/144. Blocking this on that.

**Comment by whit537** [comment]
Extended validation got bogged down and I abandoned the attempt. Now we're blocking on non-extended validation. :-)

**Comment by whit537** [comment]
Looks like we're validated again at StartSSL. Now for the new cert ...

**Comment by whit537** [comment]
From @deltab in [IRC](https://botbot.me/freenode/gratipay/2015-02-13/?msg=31899192&page=1):

```
$ openssl req -in server.csr -text
```

**Comment by whit537** [comment]
Is there a reason we can't use the CSR from a few weeks ago?

**Comment by whit537** [comment]
I submitted the CSR.

**Comment by whit537** [comment]
I used `2015-03-09.gratipay.com` as the common name, with `gratipay.com` and `www.gratipay.com` as alternates.

**Comment by whit537** [comment]
Oops. We need a lot more alternate names, for all of our alternate domains. Current:

![screen shot 2015-03-09 at 4 59 05 pm](https://cloud.githubusercontent.com/assets/134455/6564312/fadc7dc6-c67d-11e4-8415-6b79819c370c.png)

Here's the list from Heroku for comparison:

```
www.gratipay.net
gratipay.net
gittip.com
www.gittip.co
www.gittip.com
www.gittip.org
www.gratipay.co
www.gratipay.com
gittip.org
gratipay.co
gratipay.com
gratipay.herokuapp.com
www.gratipay.org
gittip.co
gratipay.org
```

We also need a separate cert for `assets.gratipay.com`.

**Comment by whit537** [comment]
So ... two new CSRs.

**Comment by whit537** [comment]
Boom! :rocket: Good look, @greggles. :-)

![screen shot 2015-03-09 at 6 53 24 pm](https://cloud.githubusercontent.com/assets/134455/6566209/9ab50930-c68d-11e4-8db7-b5bb3ca773b3.png)

**Comment by whit537** [comment]
Process documented:

http://inside.gratipay.com/howto/install-an-ssl-certificate

**Comment by whit537** [comment]
Now:

 - `{www.,}{grtp,gttp}.co`
 - {assets,downloads}.gratipay.com`

**Comment by greggles** [comment]
:+1:

**Comment by whit537** [comment]
CSRs submitted for CDN and widget server.

**Comment by whit537** [comment]
Certs are in hand!

**Comment by whit537** [comment]
I figured I'd configure DNS for alternate domains while I wait. I update nameservers to DNSimple for all `gratipay.com` alternates. However, we have a 10 domain limit on our DNSimple plan, so I was not able to add `gittip.co`. I'm considering dropping `giddip.com`.

```
aspen.io
giddip.com
gittip.com
gittip.org
gratipay.co
gratipay.com
gratipay.net
gratipay.org
motivate.im
simplates.org
```

**Comment by whit537** [comment]
At some point I turned off autorenew for `giddip.com`, as well as `giftip.org`. I'm going to remove `giddip.com` from DNS.

**Comment by whit537** [comment]
Okay, `gittip.com` is gone from DNS, and I've configured `ALIAS`/`CNAME` to `gratipay.com` for the alternates that are actually configured in Heroku (https://github.com/gratipay/gratipay.com/issues/3160#issuecomment-77942218).

**Comment by whit537** [comment]
I also removed the SPF record for gittip.com, since we shouldn't be sending mail from that domain anymore (we had been using it with Freshdesk).

**Comment by whit537** [comment]
To close this ticket I need to install the new CDN cert. I've reticketed widgets as https://github.com/gratipay/grtp.co/issues/92.

**Comment by whit537** [comment]
Hangup at MaxCDN:

![screen shot 2015-03-09 at 7 55 53 pm](https://cloud.githubusercontent.com/assets/134455/6566928/61b3c80c-c696-11e4-812b-ec50df3cdaa5.png)

I used a subdomain to avoid having to ask for a revocation at StartSSL (per their advice). I don't see a "force" option in the MaxCDN UI. Maybe a delete and readd?

**Comment by whit537** [comment]
I was able to add a new cert, need to associate it with `{assets,downloads}`.

**Comment by whit537** [comment]
Cert installed for both subdomains and old cert deleted. Waiting for propagation ...

**Comment by whit537** [comment]
Drat. Chrome is picking up the new cert but it's not green. :-(

https://assets.gratipay.com/gratipay.svg

![screen shot 2015-03-09 at 8 09 43 pm](https://cloud.githubusercontent.com/assets/134455/6567070/3fc1f794-c698-11e4-8c47-ed7a59d21209.png)

**Comment by whit537** [comment]
Skunked for tonight. Will revisit tomorrow ...

**Comment by whit537** [comment]
Still skunked. I inspected the cert using Chrome for both of these:

https://assets.gratipay.com/gratipay.svg
https://gratipay.com/assets/gratipay.svg

I can't see a meaningful difference.

**Comment by whit537** [comment]
Found it:

https://shaaaaaaaaaaaaa.com/check/gratipay.com

![screen shot 2015-03-10 at 6 38 25 am](https://cloud.githubusercontent.com/assets/134455/6573378/95f56aee-c6f0-11e4-9cda-1e666071acc0.png)

https://shaaaaaaaaaaaaa.com/check/assets.gratipay.com

![screen shot 2015-03-10 at 6 41 47 am](https://cloud.githubusercontent.com/assets/134455/6573388/9fbaf724-c6f0-11e4-9285-d8aa0eb7403b.png)

Looks like a tip to @konklone is in order. :-)

**Comment by whit537** [comment]
> As importantly, a 3-month window **forces Google to make cert rotation operationally simple**. This is the equivalent of [Netflix's Chaos Monkey](http://blog.codinghorror.com/working-with-the-chaos-monkey/) — forcing yourself to take entropy and change seriously by turning it from an emergency into the routine.

**Comment by whit537** [comment]
BLAM!!!!!!!!!!

![screen shot 2015-03-10 at 6 53 27 am](https://cloud.githubusercontent.com/assets/134455/6573537/3710196e-c6f2-11e4-9072-4aedd9fdc4d6.png)

**Comment by konklone** [comment]
> Looks like a tip to @konklone is in order. :-)

Tips always accepted. ^_^ Nice job getting this all done.

**Comment by whit537** [comment]
@konklone :-)

**Comment by captn3m0** [comment]
I am getting an SSL error for gratipay.com on Chrome+Linux

However, because of [a bug in chrome](https://code.google.com/p/chromium/issues/detail?id=474447), I don't know the root cause.

![1](https://cloud.githubusercontent.com/assets/584253/7017480/9075b1ba-dd15-11e4-8654-62e1ef38136d.png)

The website opens fine, and there are no errors in the console. This is the kind of error that I'd expect from sha1 certs, but that seems to have been fixed.

Will investigate further.

**Comment by techtonik** [comment]
Everything is fine here on Windoze + 41.0.2272.118 m
![gratipay_ssl](https://cloud.githubusercontent.com/assets/515889/7017920/0e31daca-dd07-11e4-8a15-ca7b726a99c9.png)

**Comment by konklone** [comment]
@captn3m0 Can you be more specific about versions? I'm on Chrome+Linux, and it looks fine for me.

Can you examine your browser trust store to see if StartCom's class 2 root is trusted at all?

**Comment by captn3m0** [comment]
This is weird. I didn't even restart my browser, and now the cert is green.

Version string is `43.0.2342.2 (Official Build) dev (64-bit)`.

**Comment by techtonik** [comment]
I don't know how Chrome updates itself, but I may guess that you could catch a moment when it updated resources, but didn't restarted the binary yet.

**Comment by whit537** [comment]
@captn3m0 Sounds like a dupe of #3278. tl;dr We're not targeting beta/dev browser versions. ;-)
