### ISSUE TITLE
jstests should shut down server

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3161]
Buuuuuut they don't. I thought we had a ticket for this but I'm not finding it.

cc: @rummik

**Comment by Changaco** [comment]
https://github.com/gratipay/gratipay.com/blob/1775/Gruntfile.js#L129

**Comment by rummik** [comment]
@whit537 It was fixed once before, but broke when switching to starting through Gunicorn

**Comment by whit537** [comment]
@rummik Okay, so does that mean you know how to fix it again? :)

**Comment by rummik** [comment]
@whit537 Nope ^^;  It has to do with Aspen not exiting when Gunicorn exits.  That's about all I know right now

**Comment by whit537** [comment]
@rummik There is no separate Aspen process anymore. Gunicorn is the only process.

**Comment by rummik** [comment]
@whit537 I'll have to look at it in a bit.  Planning on checking off another round of boxes on my widgets PR today

**Comment by whit537** [comment]
Found the old ticket. Closing as a dupe of #2953.
