### ISSUE TITLE
move SQL functions out of schema.sql

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3162]
Following on from #2360, and in view of the hack at https://github.com/gratipay/gratipay.com/pull/3154#issuecomment-73041912, what if we moved SQL functions to a separate file from schema.sql? If we had one file per function we could automate the process of updating those functions during deployment, and we'd get sensible diffs on PRs because we wouldn't have to use branch.sql as a go-between (branch.sql would remain for table changes).

**Comment by techtonik** [comment]
Decouple stored procedures from data structure seems like a logical way to do.
