### ISSUE TITLE
View newest members?

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3167]
Chalk this one up as another way for people to find other people to whom to donate.  It would be nice if https://gratipay.com/explore/ had a "most recent users" option in addition to communities.

(If my issues end up in the wrong place, please let me know.)

**Comment by whit537** [comment]
@mattbk The community pages each have a "most recent users" column on the left. Does that get at what you're after?

**Comment by mattbk** [comment]
I see that (after I started digging around Communities more), but I was wondering if there could be a "most recent users" on the main communities page.  It's interesting to dig around and see what kind of people are joining, regardless of community.

**Comment by whit537** [comment]
Sure, happy to leave this ticket open to track the idea. :)

**Comment by benhc123** [comment]
I would support a more clear (new users) function.

**Comment by mattbk** [comment]
Closed until communities ([or tags](https://github.com/gratipay/gratipay.com/issues/3127)) return. Until that happens, we really have no way of looking at ~user lists, only Teams on the front page.
