### ISSUE TITLE
update PGP key

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3174]
Mine expired a couple days ago:

http://pgp.mit.edu/pks/lookup?op=vindex&search=0x6EE18A8DC47977C2

**Comment by benhc123** [comment]
This is pretty easy to do isn't it?

**Comment by whit537** [comment]
Should be. It's probably a good time to move from `chad@zetaweb.com` to `security@gratipay.com`, too, though. No?

**Comment by whit537** [comment]
@benhc123 Want to work on this one with me? Let's set up security@gratipay.com and make a key for that that both you and I have access to. Waddya say? :)

**Comment by whit537** [comment]
I've created the `security` user in Google Apps, but I'm having trouble delegating access to it to my main Gmail account, which is how I have the others set up.

**Comment by whit537** [comment]
Once `security` is configured at Google the next step is to configure it at Freshdesk. That's where I'll give you access, @benhc123.

**Comment by whit537** [comment]
I just tried delegation again and it went through. Maybe it took time for the new account to propagate within Google? :fried_shrimp:

**Comment by whit537** [comment]
Okay, I've configured security@gratipay.com in Freshdesk. I've also made a security team on GitHub and a security group at Freshdesk with @benhc123 @greggles @Changaco and myself.

**Comment by whit537** [comment]
@benhc123 Can I put you in charge of making a PGP key for security@gratipay.com?

**Comment by whit537** [comment]
I'm looking at this. I'm writing up an IG doc as I go.

**Comment by whit537** [comment]
Is maintaining PGP worth it? Rarely do security researchers use PGP during disclosure.

**Comment by whit537** [comment]
GitHub discourages encrypted email for security disclosures:

> Where is your PGP key? I want to use it when I submit a vulnerability.

> If you absolutely believe encrypting the message is necessary, please read our [instructions and caveats for PGP submissions](https://bounty.github.com/pgp.html).

**Comment by greggles** [comment]
Does gratipay use a web-based form for submitting issues? If so I think that github page applies. Otherwise, the first paragraph and basis of their philosophy disappears ;)

**Comment by greggles** [comment]
That said...I also think that encrypted submissions are kinda silly.

* email encryption is a great idea for very high risk situations - the worst-case-scenario bug on gratipay is not yet as horrible as a worst-case-scenario bug on php.net or bankofamerica.com
* it's also worthwhile to encrypt data that shouldn't be leaked *eventually* - since inboxes have a way of eventually getting cracked - but the nature of security issues means that they should be kept secret only for a short time.

* encrypted emails do require key management (a pain in itself) 
* they make it harder to deal quickly with incoming submissions (find someone with the key)

**Comment by whit537** [comment]
But that's because they have a secure form on a website:

https://bounty.github.com/submit-a-vulnerability.html

As does Facebook: https://www.facebook.com/whitehat/report/.

**Comment by whit537** [comment]
> Does gratipay use a web-based form for submitting issues? If so I think that github page applies. Otherwise, the first paragraph and basis of their philosophy disappears ;)

Right. ;-)
