### ISSUE TITLE
Warning in translating "% Funded"

### ISSUE THREAD

**Issue by sidneygijzen** [gratipay/gratipay.com#3175]
I was just translating the string "% Funded" into Dutch using the Transifex Web Editor. The string appears at the location ```www/explore/teams/index.spt:39```. I got the following warning:

```Warning: The expression '% F' is not present in the translation.```

A short search resulted in [this Transifex FAQ page](http://docs.transifex.com/faq/#why-is-my-web-editor-complaining-about-the-percentage-sign), which describes some solutions to this problem. I have no clue which solution is preferred, but perhaps there is a policy on that?

**Comment by colindean** [comment]
I just ignored it for eo.

**Comment by Changaco** [comment]
Closing as duplicate of #2856.

**Comment by sidneygijzen** [comment]
Thanks for the fast replies guys!
