### ISSUE TITLE
interface difficulties

### ISSUE THREAD

**Issue by JeffSpies** [gratipay/gratipay.com#3177]
Hi, all,

My apologies that these are not nicely formatted issues; if I don't write to you (quickly) now, it likely won't happen. 

First off, nice job on connecting emails. That's a great feature.

I just logged into Gratipay after some time and am finding the interface difficult to use (perhaps non-intuitive would be more accurate). I had a "Members" menu (evidently because my account was marked as a team), and when I was trying to figure out what it was for I accidentally added a user and couldn't find out how to remove them. Later I found that by switching my account to individual, it would remove all users.  So:

1. Add indicator of what the menu is for. An easy start might be in the "No members" message: "No members on your team", but some other information about what that page does and what teams are would be nice.

2. Allow for removing the user on that page.

In the "Giving" section, I can no longer adjust amounts in batch, but I have to click on each user and then edit my giving there. My first thought is that this is purposeful inconvenience, which doesn't sit well with me. I doubt it is purposeful, knowing this team, but that's probably not the desired intuition. Takeaway:

1. I strongly prefer the previous interface where you can adjust giving all on one page.

Thanks for the time. Keep up the good work.

**Comment by whit537** [comment]
Thanks @JeffSpies! I've +1'd or reticketed your feedback.
