### ISSUE TITLE
provide better explanation on empty members tab

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3178]
Suggested by @JeffSpies in https://github.com/gratipay/gratipay.com/issues/3177:

> I just logged into Gratipay after some time and am finding the interface difficult to use (perhaps non-intuitive would be more accurate). I had a "Members" menu (evidently because my account was marked as a team), and when I was trying to figure out what it was for I accidentally added a user and couldn't find out how to remove them. Later I found that by switching my account to individual, it would remove all users.  So:
> 1. Add indicator of what the menu is for. An easy start might be in the "No members" message: "No members on your team", but some other information about what that page does and what teams are would be nice.
##

**Comment by mattbk** [comment]
This applied to Gratipay 1.0, so I am closing.
