### ISSUE TITLE
Make suggestions on who to tip

### ISSUE THREAD

**Issue by Changaco** [gratipay/gratipay.com#3183]
Reticketed from #2584. See #536, #537, #644, #2616 and #2805.
##

**Comment by benhc123** [comment]
Great idea!

**Comment by mattbk** [comment]
+1 from Twitter:
https://twitter.com/kimptoc/status/814546241023594496
> @Gratipay hi - is there a way to automatically scan my github account and match it to gratipay projects?  :P 

https://twitter.com/kimptoc/status/814584630603055104
> @Gratipay no, matching the projects I am "linked" with to existing gratipay entries.  Eg stars, following, comments etc

Starred GitHub projects is listed somewhat at https://github.com/gratipay/gratipay.com/issues/644, which was rolled into this ticket.
