### ISSUE TITLE
Admins see a 'members' tab for individual accounts. 

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#3191]
![screenshot from 2015-02-20 12 42 43](https://cloud.githubusercontent.com/assets/3893573/6282636/389bbef2-b8fe-11e4-8074-2fd85b1a4a7d.png)

**Comment by whit537** [comment]
"Dashboard" is also unhelpful for admins.

**Comment by rohitpaulk** [comment]
Invalid since the UI change.
