### ISSUE TITLE
Blurred (GitHub?) avatars on profile pages

### ISSUE THREAD

**Issue by korakinos** [gratipay/gratipay.com#3196]
Some profile pictures (avatars) appear blurry for me. Judging from a few samples, mostly pictures imported from Github seem to be affected. Take mine as an example:
https://gratipay.com/korakinos/
https://github.com/korakinos

Among the samples I took, almost all avatars from Twitter weren't blurred, except, strangely, for one. As I don't know if the person appreciates linking, I'll just post the username: InquilineKea

A similar issue in the past was [issue 887](https://github.com/gratipay/gratipay.com/issues/887). Only back then, Twitter images were blurred.

*(Off topic: Gratipay is awesome. Thank you all so much for your efforts!)*

**Comment by Changaco** [comment]
We used to show avatars in 128px maximum, then we switched to 160px, but we forgot to modify the avatar URLs.
