### ISSUE TITLE
Deal with closed accounts having a non-zero balance

### ISSUE THREAD

**Issue by Changaco** [gratipay/gratipay.com#3202]
We currently have 3 such accounts.

2 of them are the result of #2501 and can be fixed by doing a second "final gift".

The third one is more problematic: the user chose a bank account withdrawal as the disbursement method, it seemed to work, therefore the balance was zero and the account was closed, but the payout failed asynchronously (`/callbacks/balanced`). That's a flaw in the account closing logic that we need to fix one way or another.
##

**Comment by nobodxbodon** [comment]
Should be fixed by https://github.com/gratipay/gratipay.com/pull/4292 (consider it done).

**Comment by Changaco** [comment]
This issue is not related to project closing. It was about emptying all closed user accounts. However it may be too late for that now.

On the bright side, Liberapay doesn't have this kind of problem (a payout failure automatically reopens a closed account and the user is notified).
