### ISSUE TITLE
garbled year on credit card form?

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3203]
User reports in private email that they're entering "2015" for the year on the credit card page and are getting an error, `400: Invalid field [expiration_year] - "201517" must be <= 9999`.

**Comment by jdhtwo** [comment]
Slight correction (not sure that it matters) on the entered year and the returned year:

I am entering "2017" for year, but it is returning, "400: Invalid field [expiration_year] - "202017" must be <= 9999"

**Comment by whit537** [comment]
Oooooh. I tried to alter the details to maintain your privacy but I altered them wrong. :-)

**Comment by jdhtwo** [comment]
I thought that might be the case (that you were maintaining privacy), but I
didn't think it was too risky! Thanks!

**Comment by Changaco** [comment]
That's an easy one, the form is expecting only the last two digits of the year, and [blindly prefixes it with `20`](https://github.com/gratipay/gratipay.com/blob/1787/js/gratipay/payments.js#L404), so if you enter the four digits of the year like `2017`, we send `202017` to Balanced, which returns an error.

**Comment by Changaco** [comment]
Origin of the bug: 42cd006aae932c9e8e23b35d142c178f013b1566.

**Comment by jdhtwo** [comment]
So, I was autofilling this form, which explains why, while the form was
only asking for YY, my autofiller was filling in YYYY.

What about asking for YYYY, or, if you want to add "20", forcing only two
digits as entry?

**Comment by whit537** [comment]
I've deployed #3204. Mind trying again, @jdhtwo?

**Comment by jdhtwo** [comment]
I was able to fix the credit card info manually before you deployed #3204.

**Comment by whit537** [comment]
Ah, okay. !m @jdhtwo
