### ISSUE TITLE
split up registration process for payins and payouts

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#321]
Received from Jonas H. in email:

> I didn't understand why you wanted to know my bank account details right after registration. My goal with registering for Gittip was to *donate*, not to *receive*.
>
> So maybe it's a good idea to split the registration/setup process into two separate wizards; one for setting up payments and one for payouts.
>
> In my case I'd just skip the payout section - I don't expect anyone to donate towards my projects and I can't receive money anyways (I'm in Germany).  I think that's the case for > 80% of the people. Most people just don't have projects that are worth donating to :-)

**Comment by mattbk** [comment]
With Gratipay 2.0, I think this can be closed, unless more detail is warranted.

Maybe we could test a different landing page that explicitly lays out your options with Gratipay:
- Want to give? Sign up, hook up your credit card, and start giving.
- Want to receive? Sign your team up (or join one), tell us your PayPal address, and start receiving.

**Comment by whit537** [comment]
:
