### ISSUE TITLE
non-PR commits to master should trigger a PagerDuty alert

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3214]
[IRC](https://botbot.me/freenode/gratipay/2015-02-26/?msg=32906529&page=1) ff.

We need to be on guard against malicious/compromised committers sneaking in commits.

**Comment by Changaco** [comment]
Non-PR commits are part of the normal release process.

**Comment by Changaco** [comment]
How about showing the list of new commits as part of `release.sh` ? Bad commits are only dangerous if they're deployed, just being on master isn't much of a threat.

**Comment by whit537** [comment]
That's a step in the right direction. I wouldn't want to include merge commits because that would be noise and would drown out any actually anomalous commits directly to master. Basically I want to know about any commit to master that won't have otherwise resulted in an email notification in my inbox. How do we do that?

Commits aren't that bad until they're deployed, yes, but the ideal time to find out about them is when they occur, not when they are going to cause deployment to screech to a halt. If we find out about them when they occur then we have more control over addressing the issue. Even if it's just an accident from a committer, we want to find out about that early so we can educate them. If we find out about errant commits during deploy then we have to deal with the situation under the added pressure of trying to get a release out.

**Comment by Changaco** [comment]
Actually, if someone sneaked a bad commit in master, they would have access to a backup of the DB when I do `make run`, and they could do things in the background like trigger a release.

**Comment by whit537** [comment]
Good point, an attacker would have access to any developer's local system as the user the developer ran any gratipay scripts as.

**Comment by Changaco** [comment]
GitHub has an [Email hook](https://help.github.com/articles/receiving-email-notifications-for-pushes-to-a-repository/), but it's not very configurable (so it could be noisy) and is limited to two email addresses (so we'd need an external mailing list to notify more than two people).

**Comment by seanlinsley** [comment]
Perhaps: https://ifttt.com/github

**Comment by whit537** [comment]
A wild @seanlinsley appears! :bear: :-)

**Comment by Changaco** [comment]
Another option is to modify roobot's [github-repo-event-notifier script](https://github.com/hubot-scripts/hubot-github-repo-event-notifier/).

**Comment by whit537** [comment]
Closing in favor of https://github.com/gratipay/gratipay.com/issues/3915.
