### ISSUE TITLE
inline search on giving page

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3219]
I believe we heard this suggestion before (from @ncoghlan? not finding a ticket ...). I'm hearing it again from [UkuleleRod](https://gratipay.com/UkuleleRod/) IRL. "I want to add someone to my giving, so I go to my giving page, and ..."

**Comment by ncoghlan** [comment]
I also thought I'd filed an RFE for that, but apparently not. Perhaps it was just a comment on Twitter at some point?

**Comment by Changaco** [comment]
I think we want to inline search in the top nav instead so it's available on all pages.

**Comment by whit537** [comment]
@Changaco We should still have a prompt on the Giving page. "Search" in the site header doesn't provide the same affordance as "Add" within the Giving frame.

**Comment by rohitpaulk** [comment]
The original issue was #716, closing this in favor of that.
