### ISSUE TITLE
integrate Explore and Search

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3221]
They're really two ways of approaching the same task of discovery. The interfaces should bleed into each other. Reticketing from #3220.
##

**Comment by Changaco** [comment]
From https://github.com/gratipay/gratipay.com/issues/3222#issuecomment-77211246:

> Not yet. In #3221, I'm proposing that we unify the Explore and Search interfaces.

You mean downgrade the search page to display a table instead of showing the excerpt of the profile statement ?

**Comment by whit537** [comment]
There are a number of issues to think through here. I have time now to mention one:

We have a browse interface for communities on Explore, which includes a name filter that duplicates the communities results on Search (though the Explore filter doesn't have fuzzy matching; on the other hand it's zippier because the data is already loaded in the client). Why do we have two ways to search communities? We should have one.
