### ISSUE TITLE
clean up Profile/Account IA

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3236]
Over on #3220 it has surfaced that our IA around profiles and accounts is confused. Currently we treat Account as a private subset of Profile, when it would be more user-centric to treat Profile as a public subset of Account (cf. https://github.com/gratipay/gratipay.com/issues/3220#issuecomment-77561304). Any given user experiences Gratipay as a whole encompassing both public and private parts, so we should organize our IA with Account as the whole and Profile as a part thereof.

Current:

```
Profile
  Profile
  Members
  Receiving
  Giving
  History
  Widgets
  Account
  Events
```

Initially Proposed:

```
Account
  Dashboard
  Profile
    Basics
    Giving
    Receiving
    Members
  History
  Widgets
  Settings
  Events
```

Evolving Target:

```
Dashboard /
  Profile       /$username
  Members               /members
  Giving                /giving
  Receiving             /receiving
  Account → Settings
    Settings            /settings
    History             /history
    Widgets             /widgets
    Events              /events
```

Steps:
- [x] Rename Account to Settings (#3254)
- [x] ~~Move Dashboard, History, Widgets, Settings, and Events up to second-level nav, which is currently unused under Account~~
- [ ] move Settings, History, Widgets, and Events under Account (#3256)
- [ ] implement a proper dashboard at `/` (disentangled from Profile)
##

**Comment by whit537** [comment]
I believe this would also address the Dashboard issue lingering from ... #2938, was it?

**Comment by ESWAT** [comment]
By "second-level nav" do you mean in the sidebar, or should a new `.nav` be created somewhere near the existing one to act as a parent?

**Comment by whit537** [comment]
@ESWAT I'm referring to the sidebar nav, yes. I think we'll want to revisit the presentation of that nav downstream of #3063, but that's out of scope here.

**Comment by Changaco** [comment]
The profile pages use the sidebar so if you put the Account nav there then when you click on Profile the nav disappears. That's bad UI design IMO. I think modifying the top nav is a better idea, using dropdowns where necessary.

**Comment by whit537** [comment]
Account renamed to Settings in #3254.

**Comment by whit537** [comment]
Here are some other IA for comparison:

### GitHub
```
News Feed /
  Settings      /settings
    Account settings    /admin
    Emails              /emails
    Notification center /notifications
    Billing             /billing
    SSH keys            /ssh
    Security            /security
    Applications        /applications
    Repositories        /repositories
    Organizations       /organizations
  $User         /$username
    $Repo               /$repo
      Issues                    /issues
      Pull Requests             /pulls
      etc.
```

### Twitter
```
Home    /       
  Notifications         /i/notifications
  Messages              (modal)
  Discover              /i/discover
                        /settings → Account
    Account                     /account
    Security and privacy        /security
    Password                    /password
    Cards and shipping          /payments
    Order history               /orders
    Mobile                      /add_phone
    Email notifications         /notifications
    Web notifications           /web_notifications
    Muted accounts              /muted_following
    Blocked accounts            /blocked
    Design                      /design
    Apps                        /applications
    Widgets                     /widgets
  $User                 /$username
    Following                   /following
    Followers                   /followers
  Following             /following
  Followers             /followers
```

### Facebook
```
Wall    /
  Timeline              /$username
    About                       /about = ?section=overview
      Overview                  ?section=overview
      Work and Education        ?section=education
      Places You've Lived       ?section=living
      Contact and Basic Info    ?section=contact-info
      Family and Relationships  ?section=relationship
      Details About You         ?section=bio
      Life Events               ?section=year-overviews
    Friends                     /friends
    Photos                      /photos
    etc.
  Settings              /settings = ?tab=account
    General             ?tab=account
    Security            ?tab=security
    Privacy             ?tab=privacy
    Timeline and Tagging ?tab=timeline
    Blocking            ?tab=blocking
    Notifications       ?tab=notifications
    Mobile              ?tab=mobile
    Followers           ?tab=followers
    Apps                ?tab=applications
    Ads                 ?tab=ads
    Payments            ?tab=payments
    Support Dashboard /support
    Videos              ?tab=videos
```

**Comment by whit537** [comment]
I note that in all three cases, `/settings` is at the root, not under `/$username/settings`.

**Comment by whit537** [comment]
The basic structure of all three of GitHub, Twitter, and Facebook, is:

```
Stream  /
    $User       /$username
    Settings    /settings
```

**Comment by Changaco** [comment]
IMO URLs are out of scope, they only matter to developers.

**Comment by whit537** [comment]
If we take that as a standard, then our target should be:

```
Dashboard /
  Profile       /$username
    Members             /members
    Giving              /giving
    Receiving           /receiving
  Settings      /settings
    History             /history
    Widgets             /widgets
    Events              /events
```

To switch to settings we would need to implement sudo (#3238) so admins could still admin.

**Comment by whit537** [comment]
> IMO URLs are out of scope, they only matter to developers.

To an extent. Readable, logical URLs are better than unreadable, illogical URLs.

**Comment by whit537** [comment]
- [ ] Disentangle Dashboard from Profile

**Comment by whit537** [comment]
I updated the target IA to this:

```
Dashboard /
  Profile       /$username
    Members             /members
    Giving              /giving
    Receiving           /receiving
  Settings              /settings
    History                     /history
    Widgets                     /widgets
    Events                      /events
```

I don't want to block this on #3238, because that's too drastic a change to our current way of handling administration, and `/$username/settings/history` is a fine URL. I added a fourth todo.

**Comment by Changaco** [comment]
Why move History, Widgets and Events under Settings ? There are no Settings on these pages.

**Comment by whit537** [comment]
I find myself wanting to use the subnav as secondary nav and the sidebar as tertiary (it's hard to notice in the sidebar, but let's leave that aside for now). Here's a hackup:

![screen shot 2015-03-16 at 7 17 24 pm](https://cloud.githubusercontent.com/assets/134455/6678439/318697e2-cc11-11e4-933e-1c0d717e12c2.png)

![screen shot 2015-03-16 at 7 23 27 pm](https://cloud.githubusercontent.com/assets/134455/6678515/f61b12d6-cc11-11e4-97f1-29ad043679f6.png)

**Comment by whit537** [comment]
To do this, we'd have to invert the nav on the About pages, which is the only place we're using the sidebar nav right now (right?). I've added that as a todo.

**Comment by whit537** [comment]
> Why move History, Widgets and Events under Settings ? There are no Settings on these pages.

Then maybe we need a different name than Settings? How about:

```
Dashboard /
  Profile       /$username
  Members               /members
  Giving                /giving
  Receiving             /receiving
  Manage                /manage → Settings
    Settings                    /settings
    History                     /history
    Widgets                     /widgets
    Events                      /events
```

**Comment by whit537** [comment]
On GitHub, Twitter, and Facebook, Settings is a junk-drawer.

**Comment by whit537** [comment]
Or maybe just "More" or "Other"?

**Comment by whit537** [comment]
![screen shot 2015-03-16 at 7 48 08 pm](https://cloud.githubusercontent.com/assets/134455/6678799/9114c61c-cc15-11e4-9195-bb3e136b527a.png)

... or ...

![screen shot 2015-03-16 at 7 49 51 pm](https://cloud.githubusercontent.com/assets/134455/6678808/a7f1902c-cc15-11e4-9f70-a8ca4937ba57.png)

**Comment by whit537** [comment]
I think Manage could work because everything under it would always be private, whereas the other options (Members, Receiving, Giving) could be public or private depending on user settings. In which case you'd only ever see the Manage option on your own profile. It wouldn't be displayed when viewing any other profile (except for admins, of course).

**Comment by whit537** [comment]
Or maybe we're back to Account?

**Comment by whit537** [comment]
![screen shot 2015-03-16 at 8 01 07 pm](https://cloud.githubusercontent.com/assets/134455/6678922/3b36824c-cc17-11e4-82ff-5cd368029acc.png)

**Comment by whit537** [comment]
Alright, I'm confused. :-)

**Comment by Changaco** [comment]
I don't like the nav of the About pages, but I don't think reversing it is the answer. I think we have one too many nav. We often don't know what to put in the sidebar, so I think we should use it for nav, maybe eve exclusively for that, and prune the subnav.

**Comment by whit537** [comment]
@Changaco Are you saying that we should have only two levels of hierarchy on the site, or that we should have nested nav in the sidebar?

**Comment by whit537** [comment]
I don't think we can get away with only two levels of hierarchy. For example, on the history page we have the years as a fourth level of hierarchy:

![screen shot 2015-03-17 at 6 20 36 am](https://cloud.githubusercontent.com/assets/134455/6685160/ca53da32-cc6d-11e4-9001-fb05b06b3c63.png)

**Comment by whit537** [comment]
@Changaco Looks like I haven't actually said it yet: I see us moving toward getting rid of the sidebar.

**Comment by whit537** [comment]
We have two basic options for representing hierarchy in navigation:

 - a nested tree on the left
 - alternating top and side nav

**Comment by Changaco** [comment]
The history page's subnav is kind of an exception, originally I used a `<select>` but @rohitpaulk thought a nav was better. I merged it but eventually we may have to go back to a `<select>` because a year is still too much data for accounts like yours with lots of transactions, so we'll have to break it down further by month.

**Comment by whit537** [comment]
### Tree
```
 Profile        whit537
 Members        =======
 Receiving      
 Giving         History
*Account*       -------
   Settings     
  *History*     content ...
    2015        
   *2014*
      December    
     *November*
      October
      etc.
    2013
    2012
 Widgets      
 Events
```

### Alternating Top/Side
```
 whit537
 -------
 Profile  Members  Receiving  Giving  *Account*

 Settings     History
              -------
*History*     2015  *2014* 2013 2012

 Widgets      December    
                            content ...
 Events      *November*

              October

              etc.
```

**Comment by whit537** [comment]
### Tree
```
 Profile         whit537
 Members         =======
 Receiving      
 Giving          History
*Account*        -------
   Settings     
  *History*      content ...
    2015        
   *2014*
      December    
     *November*
      October
      etc.
    2013
    2012
 Widgets      
 Events
```

### Alternating
```
 whit537
 -------
 Profile  Members  Receiving  Giving  *Account*

 Settings     History
*History*     -------
 Widgets      2015  *2014* 2013 2012
 Events
              December    
             *November*     content ...
              October
              etc.
```

**Comment by Changaco** [comment]
There is a third option: instead of showing the whole nested tree you only show the current level, and a link at the top to go back up.

**Comment by whit537** [comment]
> originally I used a `<select>`

A `<select>` can make sense as part of a filtering interface, and we may want to implement History this way, more along the lines of PayPal's Transactions interface:

![screen shot 2015-03-17 at 6 40 21 am](https://cloud.githubusercontent.com/assets/134455/6685481/90de01e4-cc70-11e4-80a5-e4a8b73b4f08.png)

However, our filtering interfaces are still going to be embedded within browsing interfaces.

> There is a third option: instead of showing the whole nested tree you only show the current level, and a link at the top to go back up.

Sure, there are variants. My main point wrt navigation is that right now we have a hacked up variant of Alternating, and I think we should work within that for the purposes of this ticket. The main purpose of this ticket is to get the Profile/Account hierarchy right, within the existing navigation framework if possible. I think it's possible.

**Comment by Changaco** [comment]
> Looks like I haven't actually said it yet: I see us moving toward getting rid of the sidebar.

Are you sure about that ? We added it a couple of months ago, I don't want to remove it now just to bring it back in a few months.

**Comment by whit537** [comment]
> Are you sure about that ? We added it a couple of months ago, I don't want to remove it now just to bring it back in a few months.

If you're not comfortable changing the UI a lot over the next year, then we should start at the top with #3220 and do a more thorough job of designing our product from the top down, delaying implementation until we've thought through the whole thing top to bottom to top again. Since we're so starved for time and have gotten burned by over-large PRs, I guess I had figured on "thinking in code" and iterating towards the product we want. But maybe spending a couple weeks on design would be fruitful?

**Comment by whit537** [comment]
> To do this, we'd have to invert the nav on the About pages

This is actually false if we're going for Alternating, because the About nav is already secondary on the side. The header nav at the very top is primary.

**Comment by Changaco** [comment]
I'm comfortable changing the UI, I just think that removing something to add it back later is a waste of time, so you should be sure that you really want to remove it.

Knowing the final result you're aiming for doesn't mean you have to get there with one giant PR, you can do it step by step. On the other hand if you're going step by step without knowing what you're aiming for, then you may end up wasting time with steps that revert previous steps.

**Comment by whit537** [comment]
> Knowing the final result you're aiming for
> On the other hand if you're going step by step without knowing what you're aiming for

This is the classic waterfall/agile dichotomy. As with [other dichotomies](http://inside.gratipay.com/big-picture/mission), we have to pick a default and then tack on the other. I pick agile.

**Comment by whit537** [comment]
We talked on #3220 about splitting up Account further, so [this](https://github.com/gratipay/gratipay.com/issues/3236#issuecomment-81992148) is actually going end up more like this:

```
Dashboard /
  $User → Profile
    Profile     /$username
    Members             /members
    Giving              /giving
    Receiving           /receiving
    Account → Settings
      Settings          /settings
      Funding Instruments /funding-instruments
      Email             /email
      Notifications     /notifications
      Privacy           /privacy
      History           /history
      Widgets           /widgets
      Events            /events
      Close Account     /close
```

**Comment by Changaco** [comment]
Actually `/funding-instruments` is `/exchanges`, I have a branch almost complete for that.

**Comment by whit537** [comment]
> Actually `/funding-instruments` is `/exchanges`, I have a branch almost complete for that.

Say more? I was thinking Funding Instruments is the credit card and bank account forms.

**Comment by Changaco** [comment]
> Say more? I was thinking Funding Instruments is the credit card and bank account forms.

That's exactly what it is, "exchanges" is our internal name for money flows in and out of Gratipay, I think it should be called "Adding and Withdrawing Money" in the UI.

**Comment by whit537** [comment]
> "exchanges" is our internal name for money flows in and out of Gratipay

Sure, but the money flows are different than the instruments by which the money flows. I guess I'll wait to see your PR. :)

**Comment by whit537** [comment]
I've moved the nav-related todos to #3258. I think we should land #3254 and #3256 and close this ticket.

**Comment by whit537** [comment]
(I started looking at inverting the About nav, but I decided that the quick way to do that wasn't worth it; we should rationalize our nav further before making changes to the About pages.)

**Comment by whit537** [comment]
Blocking this on #3258.
