### ISSUE TITLE
should be able to add a user to a team from the user's page

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3242]
##

**Comment by rohitpaulk** [comment]
Isn't that the only place where you can add a member to the team? 

![screenshot from 2015-03-12 16 56 39](https://cloud.githubusercontent.com/assets/3893573/6616873/ce9aefe2-c8d8-11e4-8661-f63f258eebfc.png)

**Comment by whit537** [comment]
Oh the difference an apostrophe makes! <:)
