### ISSUE TITLE
expose rest of export functionality in UI

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3255]
Reticketing from #796. See https://github.com/gratipay/gratipay.com/pull/3246#issuecomment-81871323.
##

**Comment by whit537** [comment]
If we get this done then we can blog about updates to the history page. Would be great to get that out before US tax season is completely past.

**Comment by Changaco** [comment]
I don't see why we need this to blog about the updates to the history page.

**Comment by whit537** [comment]
@Changaco Because the point of the blog post would be that we now provide better reporting for tax and other accounting purposes. Splitting the history page by year is the first part of that and is probably enough for simple cases. The export feature is the second part of that and is suitable for more complex cases.
