### ISSUE TITLE
get nav out of sidebar

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3258]
In #2938 we got the nav out of the ol' box. Now on #3220 and #3236 we're talking about the next level of cleanup. Here's a ticket for that.
- [ ] invert subnav and sidebar nav on About pages (use subnav for secondary and sidebar for tertiary)
- [ ] move tertiary nav out of sidebar into content area

Basically we want to move the About nav out of the sidebar so that we can implement a third level of nav on Profile, where the sidebar is much more crowded (on About the nav is the only thing in the sidebar).
##

**Comment by Changaco** [comment]
I don't understand how you're seeing them as 3 separate issues.

**Comment by whit537** [comment]
@Changaco What does "them" refer to? The three todos on this ticket? Or the three other tickets linked in the description? Or ... ?

**Comment by Changaco** [comment]
I'm referring to the 3 GitHub issues: #3220, #3236 and this one.

**Comment by whit537** [comment]
The scope of #3220 is our entire product.

The scope of #3236 is the structure of Profile/Account.

The scope of this ticket is our navigation framework.

**Comment by whit537** [comment]
The scope of #3220 is our entire product.

The scope of #3236 is the logical structure of Profile/Account.

The scope of this ticket is our navigation framework.

**Comment by whit537** [comment]
#3220 is the whole of which #3236 and this ticket are parts.

**Comment by whit537** [comment]
Working on the logical structure of Profile/Account in #3236 revealed limitations of our navigation framework.

**Comment by Changaco** [comment]
I've been talking about navigation since the beginning: https://github.com/gratipay/gratipay.com/issues/3220#issuecomment-77164012.

**Comment by whit537** [comment]
@Changaco I'm making a distinction between the logical structure of the site, and the navigation interfaces we use to encode that structure for our users. You said at https://github.com/gratipay/gratipay.com/issues/3220#issuecomment-77164012 that you were talking about UI, but on #3220 I'm not talking about UI. On #3220 I'm talking about the logical structure of the site, the mental model we expect/want our users to have.

There's a dialectic between the discussion of the mental model on #3220, and the encoding of the mental model on tickets such as #3236 and this one.

**Comment by whit537** [comment]
> the logical structure of the site, the mental model we expect/want our users to have.

Namely, the information architecture.

**Comment by whit537** [comment]
> discuss roadmap based on information architecture

My purpose on #3220 is to wrestle with our information architecture, and let that drive our product development decisions. As I say, there's a dialectic between our mental model of the product and our implementation of it. #3220 is one end of that, and the PRs we're making are the other end. I want clarity about our product.

**Comment by whit537** [comment]
@Changaco A couple times now you've made a distinction between UI and URLs (https://github.com/gratipay/gratipay.com/issues/3220#issuecomment-77164012, https://github.com/gratipay/gratipay.com/issues/3236#issuecomment-81970811). I don't think that's a helpful distinction. We can't not have URLs, so we need to design them at some point. Furthermore, they're visible to users, and, like it or not, [users do in fact use them](http://www.nngroup.com/articles/url-as-ui/). I think we should think of URLs as a subset of UI, that is, as one aspect of encoding our information architecture.

**Comment by Changaco** [comment]
> 2 - invert subnav and sidebar nav on About pages (use subnav for secondary and sidebar for tertiary)
> 3 - move tertiary nav out of sidebar into content area

I don't see how the second step gets you closer to the final result, so I'd be inclined to skip it and do the 3rd step directly.

However before doing any of that we should make sure that we want to eventually remove the sidebar. Why did you add a sidebar in the first place? What things are we putting in the sidebar now and where will they be moved to? What if the sidebar was styled differently and invisible when it's empty, would that be better?

**Comment by whit537** [comment]
> I don't see how the second step gets you closer to the final result, so I'd be inclined to skip it and do the 3rd step directly.

Because without the second step, the nav would differ meaninglessly between About and Profile. On About it would be secondary in the sidebar, tertiary under the heading, while on Profile it would be secondary under the heading, tertiary in the sidebar.

**Comment by whit537** [comment]
> However before doing any of that we should make sure that we want to eventually remove the sidebar. Why did you add a sidebar in the first place? What things are we putting in the sidebar now and where will they be moved to? What if the sidebar was styled differently and invisible when it's empty, would that be better?

Good questions!

I added the sidebar in the first place to hold the remainder of the parts that used to be in the old box. I busted up the box (#2938) because the way we had navigation implemented in there was more or less dumbfounding. In #2938 we moved all nav underneath the heading. We started using the sidebar for nav later, in #3068.

> What things are we putting in the sidebar now[?]

Here's what's in the sidebar now:

 - **Picture** (avatar on Profile/Elsewhere; goofy bike chains on Communities/Community)
 - suspicious knob (Profile)
 - **Snapshot** (giving, receiving, goal, joined, closed, absorption on Profile; nmembers, ntips on Elsewhere; ncommunities on Communities; nmembers, ctime on Community)
 - **Call to Action** (auth: your tip on Profile; join on Community. anon: sign in)
 - **RIP** (one-off)
 - **secondary nav** (on About)

> [...] and where will they be moved to?

I don't know! We should talk about that. :-)

> What if the sidebar was styled differently and invisible when it's empty, would that be better?

Sure, that's a possibility.

**Comment by whit537** [comment]
> We should talk about that.

I'm going to see if I can get the nav out of the sidebar while leaving everything else there for now. That way we can dig out of this ticket and #3236, and then revisit your questions on #3220. If I can't pull it off we'll rewind back up to #3220 and block this ticket along with #3236.

**Comment by whit537** [comment]
I've moved "implement a proper dashboard at `/` (disentangled from Profile)" back up to #3236. We might have to bump it back up to #3220, we'll see.

**Comment by whit537** [comment]
Not coming together. Setting to blocked and dialing back out.
