### ISSUE TITLE
upgrade to Cedar-14

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3260]
>!   Cedar-10 will reach end-of-life on November 4th, 2015.
 !   Upgrade to Cedar-14 at your earliest convenience.
 !   For more information, check out the following Dev Center article:
 !   https://devcenter.heroku.com/articles/cedar-14-migration

**Comment by whit537** [comment]
Getting that message during deployment.

**Comment by whit537** [comment]
>On November 4th 2015, the Cedar-10 stack will reach its end-of-life. Cedar-14 is Heroku’s most modern stack and when we launched it one year ago, [Cedar-10 was deprecated](https://hello.heroku.com/e/36622/changelog-items-550/5y839g/481792037). After November 4th, the Cedar-10 stack will no longer receive security updates. You must migrate your app to Cedar-14 to ensure that it's running in a secure environment and we recommend that you do so as soon as possible.
>
Heroku is ending security support for Cedar-10 because the Ubuntu operating system that the stack is based on is [no longer maintained by Canonical](https://hello.heroku.com/e/36622/-end-of-life-on-april-30-2015-/5y839j/481792037). We take security very seriously, and we know you do too, so we want to help you migrate to a stack that is more secure.
>
The following apps which have received traffic recently, that you own or are collaborated on, currently run on Cedar-10:
>
shields-io, aspen-io, roobot-prod, img-shields-io, motivate-im, inside-gratipay-com, gratipay, gratipay-access-dashboard
>
To migrate an app, run the following commands:
> 
$ heroku stack:set cedar-14
$ git commit --allow-empty -m "Upgrading to Cedar-14"
$ git push heroku master
>
For details, see the [Cedar-14 migration guide on Dev Center](https://hello.heroku.com/e/36622/articles-cedar-14-migration/5y839l/481792037).
>
If an app has not been migrated by November 4th, Heroku will start a migration process for Cedar-10 apps, starting with free apps. Since there’s a slight chance your app won’t build correctly on Cedar-14 or that it performs in a subtly different way, you should not rely on the migration process. Instead, you should migrate apps yourself, to catch any errors or problems. If you have any questions, please let us know.
>
Happy coding,
>
Heroku

**Comment by whit537** [comment]
That was https://gratipay.freshdesk.com/helpdesk/tickets/2939.

**Comment by rohitpaulk** [comment]
Tried upgrading, got heroku's application error page soon after. Rolled back, checking for errors.

**Comment by rohitpaulk** [comment]
Nothing on Sentry, and I'm not able to find anythings in the logs, could be due to noise. Time to use `heroku fork`!

**Comment by rohitpaulk** [comment]
```
$ heroku fork --from gratipay --to paul-gratipay-copy
Forking gratipay... done. Forked to paul-gratipay-copy
Setting buildpacks... done
Deploying ade52df to paul-gratipay-copy...  ▸    You can't migrate to a deprecated stack.

There was an error forking to paul-gratipay-copy.

In order to avoid being charged for any resources on paul-gratipay-copy, it is being destroyed...
Destroying app paul-gratipay-copy... done
```

:unamused:

**Comment by techtonik** [comment]
Is it possible to just install to a new node? Maybe there is a link to old DB or something..

**Comment by rohitpaulk** [comment]
@techtonik - Going to do that, yh..

**Comment by rohitpaulk** [comment]
I've created a new test app, and pushed our code to it - 

```
remote:        Downloading/unpacking honcho==cfcc7ebb (from -r requirements.txt (line 38))
remote:          Could not find a version that satisfies the requirement honcho==cfcc7ebb (from -r requirements.txt (line 38)) (from versions: 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.0.1, 0.0.2
, 0.0.3, 0.0.4, 0.1.0, 0.2.0, 0.3.1, 0.4.0, 0.4.1, 0.4.2, 0.5.0)
remote:          Some insecure and unverifiable files were ignored (use --allow-unverified honcho to allow).
remote:        Cleaning up...
remote:        No distributions matching the version for honcho==cfcc7ebb (from -r requirements.txt (line 38))
```

**Comment by rohitpaulk** [comment]
Checking to see if this same error occurred in the build log when I pushed to our production app (with the stack set to cedar-14)

**Comment by rohitpaulk** [comment]
Yep, same error.

**Comment by rohitpaulk** [comment]
So heroku says - 

```
To add a local dependency in requirements.txt, specify the relative path to the directory containing setup.py:
./path/to/distribution
```

**Comment by rohitpaulk** [comment]
^ It's either that, or we maintain a custom buildback that instructs `pip` to fetch packages from `vendors`. First option sounds better to me, trying it out..

**Comment by rohitpaulk** [comment]
Works fine on my app - http://paul-gratipay-copy.herokuapp.com/

**Comment by whit537** [comment]
Done.

**Comment by whit537** [comment]
... in https://github.com/gratipay/gratipay.com/commit/64a4eb8fe01110fa4c10a8b325ff464878198802.
