### ISSUE TITLE
Travis build on master failed due to GitHub API rate limit

### ISSUE THREAD

**Issue by Changaco** [gratipay/gratipay.com#3266]
https://travis-ci.org/gratipay/gratipay.com/builds/54865481

I don't remember this happening before. The question is: can we do anything to prevent it?
##

**Comment by whit537** [comment]
@Changaco I think we're lumped in with all other Travis jobs on the same IP address. I don't think we should worry about this unless it starts happening alot.

**Comment by whit537** [comment]
https://travis-ci.org/gratipay/gratipay.com/builds/55019064

**Comment by Changaco** [comment]
> {"message":"API rate limit exceeded for 54.172.141.90. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}

**Comment by Changaco** [comment]
https://developer.github.com/v3/#increasing-the-unauthenticated-rate-limit-for-oauth-applications

**Comment by whit537** [comment]
https://travis-ci.org/gratipay/gratipay.com/builds/58263920
https://botbot.me/freenode/gratipay/2015-04-13/?msg=36484354&page=1

**Comment by whit537** [comment]
Haven't seen this in a while, presumably because our pace of development has slowed. Lowering priority.

**Comment by whit537** [comment]
(P.S. I'm not sold on leaking `client_secret` as in https://github.com/liberapay/liberapay.com/pull/26.)

**Comment by whit537** [comment]
Though I guess that's just what is set in `defaults.env` (or [`app-conf-defaults.sql`](https://github.com/liberapay/liberapay.com/blob/df538149d00e4f7724ad8a39ccd6e2f6c85c91c1/sql/app-conf-defaults.sql#L18-L19)), so that's fine.

**Comment by whit537** [comment]
Another [instance](https://travis-ci.org/gratipay/gratipay.com/builds/148140976#L1163-L1164).
