### ISSUE TITLE
upgrade virtualenv, setuptools, and pip

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3268]
```
"/Users/whit537/bin/python2.7" "./vendor/virtualenv-1.11.6.py" \
				--unzip-setuptools \
				--prompt="[gratipay] " \
				--extra-search-dir=./vendor/ \
				--always-copy \
				./env/
New python executable in ./env/bin/python2.7
Also creating executable in ./env/bin/python
Installing setuptools, pip...
  Complete output from command /Users/whit537/perso...om/env/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
  Ignoring indexes: https://pypi.python.org/simple/
Downloading/unpacking setuptools
  Running setup.py (path:/Users/whit537/personal/gratipay/gratipay.com/env/build/setuptools/setup.py) egg_info for package setuptools

    warning: no files found matching '*.c' under directory 'tests'
    warning: no files found matching '*.pyx' under directory 'tests'
Downloading/unpacking pip
  Running setup.py (path:/Users/whit537/personal/gratipay/gratipay.com/env/build/pip/setup.py) egg_info for package pip
    /Users/whit537/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'entry_points'
      warnings.warn(msg)
    /Users/whit537/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'extras_require'
      warnings.warn(msg)
    /Users/whit537/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'
      warnings.warn(msg)
    /Users/whit537/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'tests_require'
      warnings.warn(msg)
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: invalid command 'egg_info'
    Complete output from command python setup.py egg_info:
    /Users/whit537/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'entry_points'

  warnings.warn(msg)

/Users/whit537/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'extras_require'

  warnings.warn(msg)

/Users/whit537/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'zip_safe'

  warnings.warn(msg)

/Users/whit537/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'tests_require'

  warnings.warn(msg)

usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]

   or: -c --help [cmd1 cmd2 ...]

   or: -c --help-commands

   or: -c cmd --help



error: invalid command 'egg_info'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /Users/whit537/personal/gratipay/gratipay.com/env/build/pip
Storing debug log for failure in /Users/whit537/.pip/pip.log
----------------------------------------
...Installing setuptools, pip...done.
Traceback (most recent call last):
  File "./vendor/virtualenv-1.11.6.py", line 2338, in <module>
    main()
  File "./vendor/virtualenv-1.11.6.py", line 824, in main
    symlink=options.symlink)
  File "./vendor/virtualenv-1.11.6.py", line 992, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "./vendor/virtualenv-1.11.6.py", line 960, in install_wheel
    'PIP_NO_INDEX': '1'
  File "./vendor/virtualenv-1.11.6.py", line 902, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/whit537/perso...om/env/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1
make: *** [env] Error 1
```

**Comment by techtonik** [comment]
I suggest to upgrade virtualenv and pip and setuptools before getting too deep into their problems.

**Comment by whit537** [comment]
@techtonik But we include all three in `vendor/`. Did we recently update those?

**Comment by whit537** [comment]
Last updated four months ago in https://github.com/gratipay/gratipay.com/commit/8f13d711fd3cb9b1dc71b403416efc3e29d8d463, afaict.

**Comment by whit537** [comment]
Have I really not rebuilt in that long?

**Comment by whit537** [comment]
Huh. The problem is in fact that `make env` *is* using a newer version of setuptools, one that it finds outside of `vendor/` (I recently placed a tarball in `~/src/`). We should fix the build to only use `setuptools`/`pip` from `vendor/`.

**Comment by whit537** [comment]
s/fix the build/instruct virtualenv

**Comment by whit537** [comment]
Doesn't look like this is possible with the version of virtualenv we're using. However, it [appears](https://virtualenv.pypa.io/en/latest/userguide.html#the-extra-search-dir-option) that newer versions include setuptools and pip:

>This option allows you to provide your own versions of setuptools and/or pip to use instead of **the embedded versions that come with virtualenv**. [emphasis added]

I'm changing this ticket to be upgrading virtualenv/setuptools/pip.

**Comment by whit537** [comment]
I'll work around the bug locally by moving the newer tarballs out of the way.

**Comment by techtonik** [comment]
>
> This option allows you to provide your own versions of setuptools and/or
> pip to use instead of *the embedded versions that come with virtualenv*.
> [emphasis added]
>
This may not help. Quoting the same page:

> virtualenv will look for wheels in the specified directories, but will
use pip’s standard algorithm for selecting the wheel to install, which *looks
for the latest compatible wheel*. [emphasis added]

**Comment by techtonik** [comment]
>This option allows you to provide your own versions of setuptools and/or pip to use instead of **the embedded versions that come with virtualenv**. [emphasis added]

This may not help. Quoting the same page:

>virtualenv will look for wheels in the specified directories, but will use pip’s standard algorithm for selecting the wheel to install, which **looks for the latest compatible wheel**. [emphasis added]

See.

**Comment by techtonik** [comment]
And we already use `--extra-search-dir=./vendor/` option. It looks like it should precedence.

**Comment by techtonik** [comment]
Why do we need setuptools at all? Entry point scripts? I thought that we can just use ones in the root of the project.
