### ISSUE TITLE
Use InVision for getting feedback on design

### ISSUE THREAD

**Issue by techtonik** [gratipay/gratipay.com#3270]
http://www.invisionapp.com/ - this is truly awesome.

The idea is from here - http://meta.unix.stackexchange.com/questions/3429/site-design-updates

**Comment by whit537** [comment]
At first blush this looks similar to LayerVault (which just closed), with better testimonials.

**Comment by whit537** [comment]
We ended up not using LayerVault because it didn't offer enough value over GitHub+IRC. Have you used this "in anger," @techtonik? What does it offer over GitHub?

**Comment by techtonik** [comment]
I like the ability to point and comment directly over picture. GitHub is good for history, but it requires a lot of involvement to grab screens, cut them to get to the element and paste for discussions. I liked the concept, but I must admit that I haven't uploaded my site to InVision to see how easy it is to prepare the site for experiments.

**Comment by ESWAT** [comment]
I haven’t jumped into enough design work lately to get a sense if you guys need InVision or not. The value I got from it, especially while working remotely, was then a lot of confusion would occur where simply pointing at a spot on a mockup would work, which is hard to do through a GitHub Issue. So if you guys been getting that with some of the design-related Issues it would be worth exploring!

**Comment by whit537** [comment]
Thanks @ESWAT. Maybe something downstream of #3220 will make InVision worthwhile.

**Comment by benhc123** [comment]
InVision seems to be really good. The real question is whether Gratipay really needs it. What plan would we be using if we did? Would this be cost-effective for Gratipay?

We could simply be more proactive in collecting feedback about design from users and staff (a randomly-displayed survey might be an idea?).

**Comment by techtonik** [comment]
I don't see a demo of InVisioin anymore. It is a great thing, but without a demo it is hard to get what this ticket is about. Closing for now.
