### ISSUE TITLE
migrate to Braintree

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3287]
https://www.braintreepayments.com/features/marketplace

**Comment by Changaco** [comment]
> A PayPal Company

That worries me, and their [Acceptable Use Policy](https://www.braintreepayments.com/legal/acceptable-use-policy) isn't reassuring.

**Comment by chrisdev** [comment]
Yep Paypal is a major pita but is this not way we  facilitate most of our payouts to non US users?

**Comment by whit537** [comment]
@Changaco Their AUP looks pretty normal to me. What don't you like about it?

**Comment by whit537** [comment]
I'm looking for things in their docs that we run afoul of.

Links off of https://apply.braintreegateway.com/signup/us:

https://www.braintreepayments.com/legal/payment-services-agreement
https://www.braintreepayments.com/legal/bank-agreement-us
https://www.paypal.com/us/webapps/mpp/ua/privacy-full
https://www.braintreepayments.com/legal/acceptable-use-policy
https://www.braintreepayments.com/features/marketplace
https://www.braintreepayments.com/faq#marketplace

**Comment by whit537** [comment]
> Merchant accounts need to be specially approved for use with Marketplace. For more information, please contact support@braintreepayments.com.

https://developers.braintreepayments.com/ios+python/guides/marketplace/overview

**Comment by whit537** [comment]
I've created a Braintree account.

**Comment by whit537** [comment]
![screen shot 2015-04-09 at 6 52 21 pm](https://cloud.githubusercontent.com/assets/134455/7078699/9e49f5f0-dee9-11e4-8d2e-ca8d1a42f617.png)

**Comment by whit537** [comment]
On the application they asked about our business and I said we provide "Sustainable crowd-funding for open-source projects" or something like that.

**Comment by whit537** [comment]
>Thank you for applying with Braintree! I’ll be working with you to wrap up our application process. I only need a few more things from you before we move onto the next step.
>
1. Did you mean to apply for marketplace? Unfortunately our marketplace feature doesn’t support recurring billing. 
2. You listed your subscription billing as 75% monthly, 20% quarterly, 4% semi-annual and 1% annual. However your website states payments will be made weekly. Can you explain which recurring billing schedule your customers will be charged on?
3. How do you vet the individuals/businesses which will be accepting funds?
4. Can you please provide 3 current months of credit card processing statements to support your volume? These need to show a summary of processing volume, charge-backs and refunds.
5. The billing model charges customer’s credit cards once funds available are depleted. Are cardholders alerted in any way when their credit card is about to be charged?
>
Please let me know if you have any additional questions!

**Comment by whit537** [comment]
My response:

> Thanks! I've copied your email (without your name) to this public ticket, where I am tracking this issue with my community:
>
https://github.com/gratipay/gratipay.com/issues/3287
>
**1. Did you mean to apply for marketplace? Unfortunately our marketplace feature doesn’t support recurring billing.**
>
I'm pretty sure I did, yes. When you say marketplaces don't support recurring billing, do you mean that you don't persist cards such that we could charge them again at a later time? Or that we can't use Braintree's recurring billing code? We have our own recurring billing code, so as long as we can vault cards persistently I think we're okay. Happy to be reclassified however makes sense.
>
**2. You listed your subscription billing as 75% monthly, 20% quarterly, 4% semi-annual and 1% annual. However your website states payments will be made weekly. Can you explain which recurring billing schedule your customers will be charged on?**
>
The application form had no "weekly" option and required me to enter values that sum to 100. We have a minimum charge of $10 (to minimize processing fees), but many users give less than $10. So if I give $1 then I'm charged approximately every nine weeks, with money held in escrow and doled out weekly. The spread I gave you is an estimate based on how much people tend to give relative to that $10 minimum. Do you need me to firm up those numbers?
>
**3. How do you vet the individuals/businesses which will be accepting funds?**
>
We require users to sign up using a social media account (GitHub, Twitter, etc.), and that's currently the primary basis of our KYC efforts (you can see [our internal documentation here](http://inside.gratipay.com/howto/review-accounts)). We depended on our previous processor, Balanced Payments, to collect further PII from people who attach a bank account. You can read our tickets for improving KYC by [collecting PII directly](https://github.com/gratipay/gratipay.com/issues/3289) and also [collecting document scans](https://github.com/gratipay/gratipay.com/issues/2449).
>
**4. Can you please provide 3 current months of credit card processing statements to support your volume? These need to show a summary of processing volume, charge-backs and refunds.**
>
I don't believe Balanced gives us statements *per se*. I can run a report for you, or just give you the info. I'll work on this. Meanwhile, you can find charge volume data on [our stats page](http://gratipay.com/about/stats). I do know that our chargeback rate since launching three years ago is 0.016%.
>
**5. The billing model charges customer’s credit cards once funds available are depleted. Are cardholders alerted in any way when their credit card is about to be charged?**
>
We've been weak on this, to be honest. We have [code that will likely go out next week](https://github.com/gratipay/gratipay.com/pull/3301) to notify users when we charge their cards, but that's after the fact notification. We have a ticket about [notifying users before the fact](https://github.com/gratipay/gratipay.com/issues/2224) when we haven't charged them recently.

**Comment by chrisdev** [comment]
hey @whit537 @agfor from BrainTree came to the Garitpay booth to  say that you can ping him if you have any questions

**Comment by whit537** [comment]
Nice, thanks! :-)

**Comment by whit537** [comment]
Them:

> Hope you had a great weekend! We just have a few more follow ups for you before we move forward. Also regarding the recurring billing, as long as you have your own recurring billing code, our merchant support team can help you set it up with marketplace functionality.
>
- As the marketplace owner, do you understand that you are responsible for refunds and chargebacks?
- If you pay out your sub-merchants at a delay, will you use the Braintree escrow feature? Using our Escrow features you are able to collect funds from a cardholder, and keep them securely until your sub-merchant has provided the product.
>
Please let me know if you have any additional questions!

Me:

> Yes, thanks! Hope you did, too. :-)
>
Sounds good re: recurring billing.
>
Yes, I understand that we're responsible for refunds and chargebacks.
>
Yes, we'll use Braintree's escrow feature.
>
What are next steps? Do you still need three months statements or was the info I provided sufficient?

**Comment by whit537** [comment]
I signed this agreement:



Two things to note in particular:

 - Any user collecting $100,000 per year will need a separate merchant account.
 - *We're* responsible for complying with state-level MTL (#3321).

**Comment by whit537** [comment]
Marketplace Service Provider Agreement:

https://gratipay.freshdesk.com/helpdesk/tickets/1946
https://gratipay.freshdesk.com/helpdesk/tickets/1949

**Comment by rohitpaulk** [comment]
@whit537 - Braintree's escrow feature might not be what you think it is, have a look at this: 

> Although Braintree does not escrow funds, this is an option on transaction create where Braintree Marketplace will hold the Sub Merchant funds with our banking partner until you make an additional call to release them.

(from https://developers.braintreepayments.com/ios+ruby/guides/marketplace/overview)

Looks like we'll have to define the 'destination' (sub-merchant, as Braintree calls it) before we put a transaction into escrow.

**Comment by whit537** [comment]
@rohitpaulk I don't think that's a problem as long as we require a working payout route in order to receive funds, correct?

**Comment by whit537** [comment]
[IRC](https://botbot.me/freenode/gratipay/2015-04-13/?msg=36530501&page=2)

**Comment by rohitpaulk** [comment]
> I don't think that's a problem as long as we require a working payout route in order to receive funds, correct?

It still is. I tip you $0.25 per week. When I'm charged $10, you don't know the 'destination' for the complete $10 yet. What if I decide next week that I want to start tipping Changaco instead?

And there's one more problem (which braintree probably has a workaround for) - splitting transactions (a charge) between multiple receivers.

**Comment by rohitpaulk** [comment]
When you want to release a transaction from Escrow, you don't get to change the transaction's parameters (afaict). You just give braintree the transaction ID, and say "I want this released from escrow". So when we put a transaction into escrow, we've got to tell them beforehand - "This is who this will (eventually) be paid out to".

**Comment by whit537** [comment]
> What if I decide next week that I want to start tipping Changaco instead?

Hmm ... good point.

**Comment by whit537** [comment]
> Thanks for all of the information! I have good news, you’ve been approved and we are excited to have you as part of Braintree!! If you have any further questions our support team will take great care of you!

Huzzah! :dancer: :tada:

**Comment by whit537** [comment]
My response:

> Thanks so much! Looking forward to mapping out our integration plan. I will contact support with further questions.

**Comment by whit537** [comment]
> Not a problem! You are more than welcome to share [this PDF](https://www.dropbox.com/s/kifj8kja1l984i7/Braintree_MSP_Agreement.pdf) with your team.

**Comment by whit537** [comment]
> Congratulations Chad! You’re in. Welcome to a community of the most innovative companies accepting payments online.
>
You can start accepting payments immediately!

https://gratipay.freshdesk.com/helpdesk/tickets/1956

**Comment by whit537** [comment]
>**Braintree Application Approved**
>
Congratulations Chad! You’re in. Welcome to a community of the most innovative companies accepting payments online.
>
You can start accepting payments immediately!
>
Attached for your records is a copy of the application form you completed. You will also be receiving an email that includes instructions for logging in to your production Braintree Gateway account.
>
You can test your Braintree integration first by [registering for a Sandbox account](https://www.braintreepayments.com/get-started).
>
[Login here](https://sandbox.braintreegateway.com/login) if you already have a Sandbox account.
>
[Full documentation](https://www.braintreepayments.com/developers) is available including a step-by-step [guide](https://www.braintreepayments.com/docs/ruby/guide/overview), which is the best place to start.
>
To be in compliance with Visa & Mastercard there are certain items that need to be on your website/mobile app, and we will be confirming that these requirements are met. Failure to do so could result in your funds being held. Check here for more details to make sure you can meet these requirements.
>
Remember you can always contact our awesome support team if you have any questions.
>
Email: support@braintreepayments.com
Phone: 877.434.2894
>
Important: If you have processed transactions with Braintree before, you will need to contact us before accepting payments to prevent losing any transaction data.
>
Again, welcome to Braintree. We look forward to helping you grow.
>
Thank you,
The Braintree Team

https://gratipay.freshdesk.com/helpdesk/tickets/1956

**Comment by whit537** [comment]
> A new account in the Braintree Gateway has been created for you.
>
To access your Production account, simply click on the link below and complete the user information form.

https://gratipay.freshdesk.com/helpdesk/tickets/1957

**Comment by whit537** [comment]
[IRC](https://botbot.me/freenode/gratipay/2015-04-15/?msg=36702117&page=1)

**Comment by whit537** [comment]
https://twitter.com/Gratipay/status/588421397606707200

**Comment by whit537** [comment]
@agfor We're starting to really dig into integration details now that we have a production account. First question: can you help us get into the Coinbase beta? We currently offer bitcoin as both a payin and payout method and we'd like to preserve that capability to whatever extent possible.

**Comment by rohitpaulk** [comment]
Here are a few questions that I can think of: 

1. What is the minimum charge that we can make? If we intend on keeping zero escrow, this would have to be our minimum tip amount too. 

2. How would be go about splitting transactions? Let's say we have a user tipping 5 people $2 each. We want to make one $10 charge, and give it 5 destinations, not make 5 charges (each with one destination).

3. Is it mandatory that we reduce our escrow to absolute zero before we migrate? Would it be possible to have a sub-merchant (like [mentioned here](https://botbot.me/freenode/gratipay/2015-04-15/?msg=36705505&page=2)) of our own, who can have a pre-loaded balance and dispense funds to other sub-merchants?

**Comment by mickeyreiss** [comment]
@whit537 I'm another dev at Braintree, working on the iOS aspects of the Coinbase integration. I think we'll be able to add you to our Coinbase beta. I know it's a bit annoying, but would you mind emailing us at coinbase@braintreepayments.com? I'll make sure the right people are expecting the ping.

**Comment by whit537** [comment]
Thanks @mickeyreiss, mail sent! :-)

>Greetings!
>
We're a new customer investigating a migration from Balanced, and one of the things we're interested in is bitcoin integration. Are you able to add us to the Coinbase beta? Our username is Gratipay, and you can see our internal conversation about this here:
>
https://github.com/gratipay/gratipay.com/issues/3287#issuecomment-93548851
>
Let me know what else you need from me. Thanks! :-)

**Comment by whit537** [comment]
> Yes we can! It'd be quickest if you sent us your Braintree sandbox merchant ID as well; we may be able to look it up based on the Gratipay username but I'm traveling today so tough for me to log in and check. 

Sandbox merchant ID sent!

**Comment by whit537** [comment]
> Thanks for sending this over. We'll get you whitelisted and will reach out again once that's done!

**Comment by whit537** [comment]
>You should be good to go now in sandbox!
>
Here are the 3 pieces of info that you'll need:
>
1. Coinbase/Braintree [Integration Guide](https://developers.braintreepayments.com/guides/coinbase/overview) (hidden in the nav on the documentation site, but accessible via this direct link): 
2. Coinbase/Braintree [Integration FAQ](https://www.dropbox.com/s/mywvgn6ehmga1he/Coinbase%20FAQ%202015-03-16.pdf?dl=0)
3. Updated [client libraries for server integration](https://github.com/braintree/) (public GitHub repository)
>
Please let us know if you have any questions or feedback as you go through the integration.

**Comment by rohitpaulk** [comment]
> 12 . Will Coinbase be compatible with Marketplace?
 
> Not currently. As we continue to explore deeper integrations, this is something we may support in the future

**Comment by whit537** [comment]
I am reading https://developers.braintreepayments.com/javascript+python/start/overview.

**Comment by whit537** [comment]
> in production, Marketplace is not compatible with PayPal or currencies other than USD

https://articles.braintreepayments.com/get-started/payment-methods-currencies

**Comment by whit537** [comment]
Moving on to https://developers.braintreepayments.com/javascript+python/guides/marketplace/overview.

> Braintree's Marketplace is only for US-domiciled merchants accepting USD transactions on cards. It is not compatible with PayPal, Braintree's recurring billing, or most third-party shopping carts at this time.

**Comment by rohitpaulk** [comment]
From https://articles.braintreepayments.com/guides/paypal/overview:

> PayPal is not currently compatible with service fees. This means that if you are using Marketplace, PayPal transactions cannot be accepted at this time. You are able to use our Partners API as long as you don’t use service fees.

**Comment by whit537** [comment]
I just finished a first pass through the Braintree docs. I don't like the limitations associated with a Marketplace account. I wonder if there's a way we could structure Gratipay such that we'd be a regular merchant instead of a Marketplace? Moving to https://github.com/gratipay/inside.gratipay.com/issues/180 to explore ...

**Comment by whit537** [comment]
> Would it be possible to have a sub-merchant (like mentioned here) of our own, who can have a pre-loaded balance and dispense funds to other sub-merchants?

@rohitpaulk I believe the answer is no. If we route pay-ins to our own submerchant account (the master merchant, really), then that goes into our bank account. Braintree doesn't offer true escrow and so there's no way to shuffle money around inside Braintree.

Using Braintree Marketplace for payouts would then incur a second processing fee because Gratipay would be paying in via Braintree, and the only way to do that using Marketplace is with a credit card.

```
   giver --> Braintree --> Gratipay

Gratipay --> Braintree --> receiver
```

It appears that we're not going to be able to use Braintree for payouts. Braintree is still quite attractive for payins because it would add so many more options for us, but to maintain continuity on the payout side we would have to find another ACH credits vendor (e.g., #417, #3366).

**Comment by whit537** [comment]
I just talked to Braintree support and then sales on the phone, and they were fine with us dropping back from a Marketplace account to a regular merchant account and handling all of the submerchant logic on our end ("That's actually how some of our larger marketplace customers work with us; our Marketplace product is great but it's just a starting point."). The next step is to reapply.

**Comment by whit537** [comment]
New application submitted.

**Comment by whit537** [comment]
https://gratipay.freshdesk.com/helpdesk/tickets/2028

> I talked on the phone with sales just a bit ago, and they recommended that we reapply for a regular merchant account, because of the limitations of the Marketplace product (we'll implement our own marketplace logic on our end). We haven't actually processed transactions with our Marketplace account yet, but I went ahead and selected "yes" for "Have you processed transactions with Braintree before?" anyway, in case you want to try to reuse that account somehow (not sure how exactly things are wired up over there).
> 
Anyway, let me know if you have any further questions! :-)

**Comment by whit537** [comment]
>Great to see you applying for a new Braintree account!
Before we begin work on setting this account up, I want to be sure we understand the purpose of this application, since you applied with the same information as your existing account. If you could please explain the purpose of this application, I would appreciate it.
Best,

Response:

>Sure thing! We originally applied for the Marketplace product because we're coming from Balanced Payments. However, upon further review Braintree Marketplace is too limited for our needs (no escrow feature). I called Braintree support and was bumped to sales. Josh in sales advised that I reapply for a regular account. Everything else should be the same, except for the "Will your business use Braintree Marketplace?" question.
>
Does that help?

**Comment by whit537** [comment]
Huzzah! :dancer: 

> Perfect. We will replace your original marketplace account with your new regular account. I will update you if I have any follow ups!

https://gratipay.freshdesk.com/helpdesk/tickets/2031

**Comment by whit537** [comment]
> Any chance you could release the "gratipay" username for our production account? I can't login using it anymore, but I also can't use that for our new account either. :-/

**Comment by whit537** [comment]
> Your password cannot be reset because your account has been suspended.

**Comment by whit537** [comment]
> Unfortunately, we cannot make changes to those user names.

**Comment by whit537** [comment]
I went with `gratipay_`, because of PEP 8:

> In addition, the following special forms using leading or trailing underscores are recognized (these can generally be combined with any case convention):
>
[...]
- `single_trailing_underscore_`: used by convention to avoid conflicts with Python keyword

And Braintree's styling:

![screen shot 2015-04-29 at 1 03 08 pm](https://cloud.githubusercontent.com/assets/134455/7396569/325e7e06-ee70-11e4-84c8-850ee4a9def2.png)

![screen shot 2015-04-29 at 1 02 54 pm](https://cloud.githubusercontent.com/assets/134455/7396561/22c711b0-ee70-11e4-8f31-9cb8d5b367ed.png)

![screen shot 2015-04-29 at 1 02 40 pm](https://cloud.githubusercontent.com/assets/134455/7396565/2aed735c-ee70-11e4-94d9-a330b5049c72.png)

**Comment by whit537** [comment]
Reticketing from https://github.com/gratipay/gratipay.com/issues/3377:

How hard is it to change the bank account where our funds settle?

**Comment by whit537** [comment]
To: support@braintreepayments

> With our Braintree merchant account, what's the process for changing the bank account where funds ultimately settle? We're trying to plan our migration, and if this is a fairly straightforward thing to change, it will give us some additional flexibility.
>
I poked around the dashboard but didn't see this info. I have a recollection that I provided routing information during setup, but now I'm questioning myself. Did I give you routing info? If not, how do funds settle?

**Comment by whit537** [comment]
>Thank you for reaching out!
You have come to the right place for bank account changes. To do so, we will need [...]

Details on https://gratipay.freshdesk.com/helpdesk/tickets/2057.

**Comment by rohitpaulk** [comment]
I had a quick look through the docs, we won't have to deviate much from our current setup :)

I'm going to start working on this tomorrow, @whit537 - Time to initiate a convo with Balanced regarding migrating card info?

**Comment by whit537** [comment]
> I'm going to start working on this tomorrow, @whit537

Awesome! :dancer: 

!m @rohitpaulk 

> Time to initiate a convo with Balanced regarding migrating card info?

I've started a thread with them, mostly focused on the bank side right now (#3379). The card transfer should be pretty straightforward, but we should really get double-vaulting in place first: #3387.

**Comment by whit537** [comment]
Per https://github.com/gratipay/gratipay.com/issues/3377#issuecomment-100372126 let's try to change Braintree to settle at New Alliance before next Thursday.

> Okay, []. We are going to move forward with this change request. Unfortunately I don't have [the needed info]. I will work on that on Monday. Our ideal will be to have this completed by next Wednesday or Thursday at the latest, so I wanted to give you a heads up now in case that's simply too tight a time frame from your end.
>
Hopefully you will hear from me Monday! :-)

**Comment by whit537** [comment]
Documentation sent.

> We've pushed back our target by a week, so a little pressure off. We'd like this done by Wednesday, May 20. We'll need to change accounts one more time before our migration is fully complete, so I'll follow up with you again in a few weeks.
>
Thanks for your help! :-)

**Comment by whit537** [comment]
From: Braintree
To: Balanced
CC: me

> Hi Balanced Support,
>
Unfortunately I missed the window for this export. May I request it get run again? Thank you.

**Comment by whit537** [comment]
Migrating cards is #3391.

**Comment by whit537** [comment]
>Thank you for sending us that documentation. This email is to confirm that your bank account has been updated. This change typically goes into effect within one to two business days.

Yessssssss. One question that came up in the meeting with Citizens yesterday (#3366) is how quickly funds settle from Braintree into our bank account. With Balanced, funds were instantly available to us to pay out again, but I believe Balanced was floating that for us, and with a more DIY infrastructure we'll need to account for that float ourselves.

**Comment by whit537** [comment]
> Thanks, []! I'll get in touch again in a couple weeks when we're ready to do the final settlement account change ...

**Comment by whit537** [comment]
Curve ball: https://github.com/gratipay/gratipay.com/issues/3463.

**Comment by agfor** [comment]
Congrats on getting through the underwriting process & going live! I've been following along (even if I've not commented here); feel free to ping me if you've got any other Braintree related issues.

**Comment by whit537** [comment]
Thanks @agfor! We're quite excited about it, especially now that #3463 is resolved as well! :dancer:

**Comment by agfor** [comment]
Yep, I was glad to see that got worked out today.
