### ISSUE TITLE
Transaction routing - define inputs and outputs, tag inputs, show map

### ISSUE THREAD

**Issue by techtonik** [gratipay/gratipay.com#3306]
Gratipay is a gratitude routing platform. It is unfortunate that it is landlocked in US law and need to funnel all transaction through the US mainland to stay legal. We should show this on a map:

```
in: US     --> GP --> out: US       [$0.xx per hop]
in: World --> GP --> out: US      [$0.xx per hop]
in: World --> GP --> out: World  [denied]
```

The map above is not accurate. `in` would take a great role if we are to support different payment systems. `in` and `out` in the same payment system would not be the same price as `in` and `out` in different system. Transactions `Dwolla` --> `Dwolla` have different properties (both by reach and by cost) than `Dwolla` --> `PayPal`.

This is complicated, so we need to make a map and make it a public tool to play with this and learn how money is routed. I'd like to do this map, but for now I need a table of countries:
- from which you can send GP
- in which you can receive GP

The table should list a payment provider if that directly affects which countries are supported.
- [ ] the routing map

The next step is input tagging. It may happen that we won't be able to convert from Bitcoin to Dwolla or PayPal to Alipay. This may be used later to give users a hint that receiver is using Bitcoin or Dwolla and won't be able to receive the payment (or that it will incur additional conversion fee, which we will also be able to tell immediately). Tagging is applied to input value.
- [ ] input value tags

It may be that we will complicate the system, but the world of transactions is not that easy, and still we can make it more transparent. Input tags will also help us to track tax clearance in countries where it is possible. That should further dispell the FUD about GP usage.
##

**Comment by whit537** [comment]
- from which you can send GP

Any country from which you can use Visa, Mastercard, American Express, Discover, or bitcoin.

- in which you can receive GP

USA, plus any country from which you can use PayPal or bitcoin.

**Comment by techtonik** [comment]
The reality is more complicated. In my country there is a FUD that Bitcoin is illegal, so you can not buy them officially. Only through Visa or other means, which incurs additional penalty. So it will be good to list countries where you can just buy BTC legally by cash or by other means.

**Comment by techtonik** [comment]
Another usage example for Gratipay to consider - I want to "cash out" from Gratipay directly to Bountysource bounty, and I want it to be visible.
