### ISSUE TITLE
rename "exchanges" to "transfers"

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3316]
Exchange in a financial context means foreign exchange, i.e., trading currencies.

I looked at Ally, Citizens, and PayPal, and they all use the term "transfer" for moving money from an account at one institution to an account at another, which is what what we currently call exchanges is about. (Actually, Ally and Citizens use their transfer interface for moving money between accounts at the same institution as well.)
##

**Comment by whit537** [comment]
I've noticed in the history export that we're starting to leak the term `exchanges`, which is what prompted me to raise this issue now.

**Comment by Changaco** [comment]
What would we rename the current `transfers` table to?

> Exchange in a financial context means foreign exchange, i.e., trading currencies.

Exchanges in the Gratipay context can in fact involve currency exchange.

**Comment by whit537** [comment]
> What would we rename the current `transfers` table to?

Good question. I suggest `payments`. I also suggest renaming `tips` to `subscriptions`.

> Exchanges in the Gratipay context can in fact involve currency exchange.

Are you thinking of the bitcoin case? Credit card charges, bank payouts, and PayPal payouts are all done in USD.

**Comment by techtonik** [comment]
How about we start a glossary on http://inside.gratipay.com/? It will help both people without knowledge of English and people without knowledge of financial domain.

**Comment by whit537** [comment]
@techtonik Good idea! Go for it. :-) Let's put it under Appendices, and start by migrating the content from https://github.com/gratipay/gratipay.com#glossary.

**Comment by Changaco** [comment]
> Good question. I suggest `payments`. I also suggest renaming `tips` to `subscriptions`.

`payments` is generic, transfers and exchanges are both payments.

I suggest renaming the key in the history export, and nothing else. Unless we find a terminology that is very superior to the current one renaming everything seems like a waste of time to me.

> Are you thinking of the bitcoin case? Credit card charges, bank payouts, and PayPal payouts are all done in USD.

Obviously there's the Bitcoin case, but credit card charges can also involve a currency exchange even if it's "transparent".

**Comment by whit537** [comment]
See also: https://github.com/gratipay/inside.gratipay.com/issues/117.
