### ISSUE TITLE
communicate fees more clearly

### ISSUE THREAD

**Issue by techtonik** [gratipay/gratipay.com#3319]
There is a thread about alternative donation channels on Inkscape mailing list. 
https://sourceforge.net/p/inkscape/mailman/inkscape-devel/thread/F49DED4EE47949B2B4BD2B2A03BF6203%40JillsLaptop/#msg33697857

I am personally looking forward to use SVG + D3.js in Gratipay visualizations, so it looks logical to see if Gratipay can play a good role in Inkscape fundraising and adopt itself according to demand. What I see immediately is the necessity to have a less verbose information about fees. Current entrypoint at https://gratipay.com/about/faq is not concise enough.
##

**Comment by colindean** [comment]
Is the recently added paragraph on the about landing page sufficiently concise?

https://gratipay.com/about/

> Gratipay does not take a cut of payments, recipients get the full face value. Instead of taking a cut, Gratipay is funded by the voluntary payments of our users to our own Gratipay account. See our pricing page for more information.

**Comment by techtonik** [comment]
@colindean no, this is obscure. The people are interested to know exact fees for their case..

**Comment by whit537** [comment]
I know one of the developers. @liamwhite are you up on the funding Inkscape conversation?

@techtonik Why don't you join the mailing list and suggest Gratipay? :-)

**Comment by techtonik** [comment]
@whit537 actually, I did send the letter, but..
```
You are not allowed to post to this mailing list, and your message has
been automatically rejected.  If you think that your messages are
being rejected in error, contact the mailing list owner at
inkscape-devel-owner@lists.sourceforge.net.



---------- Forwarded message ----------
From: anatoly techtonik <techtonik@gmail.com>
To: inkscape-devel@lists.sourceforge.net
Cc: 
Date: Tue, 7 Apr 2015 15:25:56 +0300
Subject: Donating through Gratipay
```
I really prefer forums more. =)

**Comment by techtonik** [comment]
Done. http://sourceforge.net/p/inkscape/mailman/message/33764265/

**Comment by whit537** [comment]
!m @techtonik

**Comment by techtonik** [comment]
Looks like we should raise the importance of the issue. =) This is the feedback from [Inkscape](http://inkscape.13.x6.nabble.com/Donating-through-Gratipay-tt4973341.html#a4973355):
```
If there is one which doesn't take a
fee, I would say that would be ideal!  (Because when these apparently noble
groups who just want to support "the starving artist" or "the starving
programmer" take a fee, they start to look less noble, in my eyes.)(my
opinion)

While Flattr takes 10%, and Patreon takes 5% plus credit card fees, it
appears Gratipay is less "transparent".  The Gratipay terms say
"
Fees
Gratipay reserves the right to charge service fees based on the total amount
of your transaction. Such fees are subject to change without notice and in
Gratipay's sole discretion. All Gratipay fees will be disclosed to you
before you complete your transaction."

>From my point of view, that makes it difficult for a potential recipient of
these donations, to decide whether to use the service.  But again, my
opinion  :-)
```

This matches my perception of Gratipay from outside. The problem with current representation is that it is based on belief and trusts - and that's is a problem. We as developers do believe each other and trust each other, so we don't sense the issue, but for people from outside it is just not convincing.

We should be visually explicit about who takes what. If it is Paypal, let it be clear that PayPal takes 5%. If it is Bitcoin, let's show how it enters and leaves the system.

**Comment by whit537** [comment]
Sounds like a bug in our terms.

**Comment by mattbk** [comment]
+1

**Comment by techtonik** [comment]
From my communication on Inkscape-devel:
```
"As far as I can tell there is no fee for Gratipay service - it is fuelled by
direct donations - https://gratipay.com/about/pricing - the fees above
are set by payment providers. Well, except Bitcoin, but this needs
further clarifications. Last time I've heard about that, the Coinbase was
used."

Well, that seems in direction contradiction to what is stated in Terms of Service, #9.
https://gratipay.com/about/policies/terms-of-service

If the fees explained there are not for contributions or donations, or only for credit card transactions, it should be clarified.
```

@whit537 I believe only you can act on https://gratipay.com/about/policies/terms-of-service

The point #9 looks shady:
```
Fees

Gratipay reserves the right to charge service fees based on the total amount of your transaction. Such fees are subject to change without notice and in Gratipay's sole discretion. All Gratipay fees will be disclosed to you before you complete your transaction.
```

**Comment by mattbk** [comment]
At https://gratipay.com/about/pricing, I think the lead section should be "We don't take a cut, but we ask that you donate" and then get into suggested pricing.

Also, this page suggests that because I transfer $0.21 per week with Gratipay, I should pay an extra $0.25 for the service.  10% would be $0.02, so I assume the $0.25 is a hardcoded minimum?

**Comment by whit537** [comment]
@mattbk Yes, 25¢ is [a hard-coded minimum](https://github.com/gratipay/gratipay.com/blob/1864/gratipay/utils/pricing.py#L16).

**Comment by mattbk** [comment]
Does the credit card processor not divulge fees to us?  Or is it on a per-card basis that fees are calculated?

**Comment by mattbk** [comment]
NM, right here: https://gratipay.com/about/features/payments#fees

**Comment by nobodxbodon** [comment]
Seems the only remaining action item is https://github.com/gratipay/gratipay.com/issues/3326. Please reopen if otherwise.
