### ISSUE TITLE
Add a table about fees and routes

### ISSUE THREAD

**Issue by techtonik** [gratipay/gratipay.com#3326]
To ensure maximum transparency and solve #3319 we need need a table to let people experiment with visualization how money is routed through Gratipay from sender to receiver, who takes what on the way, what information is required by whom. 

Questions that should be covered.
1. Payday. When money are moved.
2. Fees. Who takes what during payday.

Ins (how the money are taken from sender):

```
Way | Fee | When
PayPal | ??? | At pay day
```
1. Are the money send directly or through intermediate Gratipay account?

This is critical to understand the fees. Doesn't look like `PayPal -> PayPal` is working, because we preserve anonymity. Looks like it is `PayPal -> GP -> PayPal`, in which case what are the fees for both `->`?

Can we route without anonymity and GP directly? If yes, then we should recommend this way.

The GP way should be provided as opt-in to either:
- preserve anonymity
- support Gratipay (with a way to split bounty like in Humble Indie bundle)

Outs (how the money are taken):

```
Way | Fee | When
PayPal | ??? | At pay day
```

### Notify
- [ ] https://gratipay.freshdesk.com/helpdesk/tickets/4827

##

**Comment by colindean** [comment]
:+1:

**Comment by rohitpaulk** [comment]
@techtonik - We don't accept money via PayPal, it's only a payout method.

Ins - Credit Card (Balanced), Bitcoin Payin (Coinbase, manual)
Outs - Bank Account (Balanced), Paypal, Bitcoin Payout (script)

**Comment by techtonik** [comment]
@rohitpaulk, :+1:. Do we route all Ins and Outs through the GP? Or do we connect some Ins and Outs directly (like Bitcoin -> Bitcoin)?

**Comment by rohitpaulk** [comment]
None are connected directly. Everything is through GP.

**Comment by mattbk** [comment]
Retickted from #4044:

> (reticketed from https://github.com/gratipay/inside.gratipay.com/issues/647)
> Re: https://gratipay.freshdesk.com/helpdesk/tickets/4827 (login required).
> We have a minimum payout amount which I think is dictated by PayPal so they receive at least $0.01 in transaction fees. This doesn't seem to be explained on gratipay.com anywhere.
> ### Notify
> - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/4827

**Comment by whit537** [comment]
Notify section added to ticket description.

**Comment by mattbk** [comment]
Reticketed from https://github.com/gratipay/gratipay.com/pull/4157#issuecomment-264317722:

> Should we mention PayPal fees on pay _out_ under the following? That would help close https://github.com/gratipay/gratipay.com/issues/3326.
>> WHAT ARE THE PAYMENT FEES? 
>> Our credit card processor, Braintree, charges 2.9% + 30¢ per transaction. We upcharge ~users to cover this fee at cost, and Teams receive the face value of the payment. For example, we'll charge $20.91 to cover a $20 payment

**Comment by mattbk** [comment]
This was added in https://github.com/gratipay/gratipay.com/pull/4157/files#diff-e1c620cb8be92eaa2a469cc9ce67ff13R74:

> Projects receive <a href="#methods">payouts</a> via PayPal, which charges 2%. This fee is passed on to the project on payday and is capped at $1 for U.S. PayPal accounts.

**Comment by nobodxbodon** [comment]
The transparency seems critical, both to gratipay's accounting or teams. To understand better about the fee structure, @mattbk could you share the reference about the 2% and $1 cap? I don't find any related info on https://www.paypal.com/us/webapps/mpp/paypal-fees

I also +1 to adding a report or visualization about the breakdowns (amount received from givers, fees, amount received by receivers) and make them available either to individual team or public.

**Comment by mattbk** [comment]
This is where I found it: https://github.com/gratipay/gratipay.com/blob/master/data/routing.txt#L17

**Comment by nobodxbodon** [comment]
I guess it's [mass payment](https://www.paypal.com/cgi-bin/webscr?cmd=_batch-payment-overview-outside).

**Comment by mattbk** [comment]
Yes, payday is run using masspay.

**Comment by mattbk** [comment]
Yes, payday is run using masspay: http://inside.gratipay.com/howto/run-payday.

**Comment by mattbk** [comment]
>  also +1 to adding a report or visualization about the breakdowns (amount received from givers, fees, amount received by receivers) and make them available either to individual team or public.

Have you seen https://github.com/gratipay/gratipay.com/pull/4128?
