### ISSUE TITLE
provide lay summaries of legalese

### ISSUE THREAD

**Issue by techtonik** [gratipay/gratipay.com#3327]
These pages:
- https://gratipay.com/about/policies/terms-and-conditions
- https://gratipay.com/about/policies/terms-of-service
- https://gratipay.com/about/policies/privacy

Need a docco translation to human language ([example](http://documentcloud.github.io/underscore/docs/underscore.html)).
##

**Comment by colindean** [comment]
:+1:

Someone should also update gittip to gratipay for TOS;DR: https://github.com/tosdr/tosback2/blob/master/rules/gittip.com.xml

**Comment by whit537** [comment]
WePay does [a pretty good job with this](https://www.wepay.com/legal/terms-of-service).

![screen shot 2015-04-12 at 12 48 38 pm](https://cloud.githubusercontent.com/assets/134455/7106543/46e4ce72-e112-11e4-83a8-23e583fc0e64.png)
