### ISSUE TITLE
Update TOS;DR entry

### ISSUE THREAD

**Issue by colindean** [gratipay/gratipay.com#3328]
[TOS;DR](https://tosdr.org/) still has a configuration for Gittip. It looks like it's been retrieving by following redirects, but it should probably be updated.

Here's the configuration:

https://github.com/tosdr/tosback2/blob/master/rules/gittip.com.xml

Reticketed from #3327.
##

**Comment by techtonik** [comment]
Awesome service that TOS;DR. I'd like to see it somewhere on http://inside.gratipay.com/appendices/colophon but not sure in which chapter exactly.

**Comment by colindean** [comment]
Interestingly enough https://github.com/tosdr/tosback2/pull/28 was just merged a week ago.
