### ISSUE TITLE
Add "number of tippees" to /about/paydays.json

### ISSUE THREAD

**Issue by lyndsysimon** [gratipay/gratipay.com#333]
The paydays table currently has `ntippers`, containing the number of tippers. We don't seem to have an `ntippees` column.

I propose that a column be added to `paydays`, appropriate logic added to the payday process to populate it each run, and the field be exposed on `/about/paydays.json`.

Alternatively, we could subquery out to `transfers`, selecting distinct tippees for the duration of the payday. This would probably work just fine for now, but would be more complex and wouldn't scale well.
##

**Comment by nobodxbodon** [comment]
As ntippers column is [dropped](https://github.com/gratipay/gratipay.com/pull/3730), I don't think this will be done until a full rework of stats page, which will be a whole new project and not in foreseeable future.
