### ISSUE TITLE
The bottom nav is invisible

### ISSUE THREAD

**Issue by techtonik** [gratipay/gratipay.com#3331]
The bottom bar is hidden through scrollback, so nobody sees it. Discovered the fact only because was looking how to deal with #2850.

![nobottom](https://cloud.githubusercontent.com/assets/515889/7111475/c168941a-e1c8-11e4-8949-85442deace5d.png)

**Comment by whit537** [comment]
Can you be more specific? I thought maybe you were referring to the footer, but I can see that just fine:

![screen shot 2015-04-13 at 7 34 28 am](https://cloud.githubusercontent.com/assets/134455/7114835/902c540e-e1af-11e4-9aa0-e284fd07b1cc.png)

**Comment by techtonik** [comment]
Yes. I am referring to footer. It is shown only when you scroll down no matter how small the page content is.

**Comment by whit537** [comment]
Ah, gotcha.

**Comment by whit537** [comment]
Addressed in #3718.
