### ISSUE TITLE
Make friend finder permissions an opt-in

### ISSUE THREAD

**Issue by techtonik** [gratipay/gratipay.com#3332]
I tried to login with G+ and found out that it now requires way to much private info from my account. It is good I have Bitbucket option, otherwise I may consider closing the account and moving somewhere else. I really think that any extended access to private user data should come as an opt-in.

I haven't got into OAuth stuff yet, but maybe request additional permissions when user is trying to use Friend Finder tool, not when the user is logged in?

**Comment by rohitpaulk** [comment]
Closing in favor of #2854, which you've assigned to yourself .
