### ISSUE TITLE
Add ¶ anchors to style

### ISSUE THREAD

**Issue by techtonik** [gratipay/gratipay.com#3333]
https://gratipay.com/about/faq and other pages lack visible anchors for easy linking to https://gratipay.com/about/faq#how-add-funds This should be an easy CSS fix.

**Comment by kaguillera** [comment]
@techtonik sure what you mean/want in his issue. Do you want the question/header highlighted or the links to the questions?

**Comment by kaguillera** [comment]
@whit537 explained working on it.

**Comment by kaguillera** [comment]
@whit537 explained working on it.

**Comment by techtonik** [comment]
Yes, the standard behaviour of showing an anchor that you can copy when you hover over paragraph header. It can be ¶ at the end of paragraph like in Trac, or something at the start of paragraph like in GitHub.

**Comment by techtonik** [comment]
!m @kaguillera @rohitpaulk :+1:
