### ISSUE TITLE
use HTTPS for OSM gravatars

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3334]
Looks like Gravatars for OpenStreetMap accounts elsewhere are using HTTP instead of HTTPS, resulting in a mixed content warning.

https://gratipay.com/nijel/

![screen shot 2015-04-13 at 8 54 44 am](https://cloud.githubusercontent.com/assets/134455/7115903/c685bfda-e1ba-11e4-89c7-87f92e6500ed.png)
##

**Comment by whit537** [comment]
![screen shot 2015-04-13 at 8 59 19 am](https://cloud.githubusercontent.com/assets/134455/7115957/6e221d1a-e1bb-11e4-99b9-aacea238be84.png)

**Comment by rohitpaulk** [comment]
```sql
SELECT COUNT(*) FROM elsewhere WHERE platform='openstreetmap' AND avatar_url LIKE 'http:%';
--> 104
SELECT COUNT(*) FROM elsewhere WHERE platform='openstreetmap' AND avatar_url LIKE 'https:%';
--> 390
```

**Comment by whit537** [comment]
So we should add some code to catch this when extracting the OSM avatar? And then repair the db?
