### ISSUE TITLE
implement projects

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3337]
Reticketing from https://github.com/gratipay/inside.gratipay.com/issues/180. We're going to phase out no-strings-attached individual-to-individual giving in favor of no-strings-attached voluntary payments to worthwhile projects.

First, a Gratipay user must have a certain trust level:

 - verified email address
 - PII (name, address, phone number, ???)
 - functioning withdrawal mechanism

Gratipay users above this trust level can create projects. Projects have these attributes:

 - project name
 - project description
 - project homepage
 - type of product or service

To start with, "type of product or service" will be hard-constrained to this list:

 - [ ] open-source software
 - [ ] open product
 - [ ] hackerspace
 - [ ] open-source community-building

Tips are attached to a project, no longer to a user.

**Comment by whit537** [comment]
> Tips are attached to a project, no longer to a user.

@rohitpaulk argues in [IRC](https://botbot.me/freenode/gratipay/2015-04-13/?msg=36531538&page=2) that we should still offer tipping a user.

**Comment by tshepang** [comment]
The most attractive use-case for Gratipay personally is tipping individuals:

> Thanks for doing this work. Here's my bit ($$$) in encouraging you to continue being awesome.

Ideally, one would end covering most (or all) their expenses via these gifts.

I don't know what the way forward should be, and I'm scared Gratipay may not survive this. This change in direction feels so hasty and desperate.

I don't know how you handle this much pressure @whit537. I hope you are doing fine.

**Comment by whit537** [comment]
Heh, thanks @tshepang. :-) I'm actually doing better now than in a long time.

> Thanks for doing this work. Here's my bit ($$$) in encouraging you to continue being awesome.

This wouldn't be accomplished by giving to `mitsuhiko > Flask` as opposed to plain ol' `mitsuhiko`?

**Comment by whit537** [comment]
It would be up to the founder of a project to decide when to move a project to an organization account instead of their personal account. Consider, toom that an individual could set up a project on Gratipay such as this:

**Name:** Research Projects
**Description:** Money given to this project will enable me to spend my time developing experiments and new projects.
**Homepage:** http://lucumr.pocoo.org/projects/
**Category:** open-source software

**Comment by whit537** [comment]
Would that adequately address the use-case of "genius grants" for especially productive individuals?

**Comment by chrisdev** [comment]
@whit537 I spoke to one of our prominent developers and his use case does not match this new direction. While he is a prominent dev so we can easily say you are tipping  his project. He in turn channels his tips to a non-developer who is on the platform. 
I'm also tipping my nephew primarily because he just started college.

**Comment by tshepang** [comment]
If I know who `mitsuhiko` is (I've seen his contributions in the past, which include his detailed posts and prolific open source work), I may want to give him some. Maybe I don't care as much for Flask.

**Comment by whit537** [comment]
> If I know who `mitsuhiko` is (I've seen his contributions in the past, which include his detailed posts and prolific open source work), I may want to give him some. Maybe I don't care as much for Flask.

Sorry, I was trying to pick a likely example. `s/mitsuhiko/???` :)

**Comment by tshepang** [comment]
@whit537 with a name like Research Projects, you might as well leave things the way they are now. That is, would others be allowed to join such a project? How is this different to a Team?

**Comment by chrisdev** [comment]
>functioning withdrawal mechanism
This would include PayPal and not just bank accounts?

**Comment by tshepang** [comment]
@whit537 yeah, I'm aware. My point is I'm a fan of one person's overall work, instead of specific projects.

**Comment by chrisdev** [comment]
Hmmm. The way this is going we better introduce one time payments.

**Comment by whit537** [comment]
@chrisdev Regarding your nephew, I would expect us to grandparent in existing receivers. For everyone currently receiving money on Gratipay, we would create a single project, something like this:

**Name:** My Life
**Description:** This is an automatically-generated project for a user who predates Gratipay's projects feature. See [link]() for details.
**Homepage:** https://gratipay.com/username/
**Category:** grandparented

So make sure you sign up all your family members soon! :-)

Regarding the developer passing through their tips, that would still be possible for someone new on Gratipay after this lands. Having to attach a withdrawal route would mildly discourage this, but wouldn't render it strictly impossible.

We want lots of viable businesses on Gratipay!

**Comment by tshepang** [comment]
Ok, I'm not sure I understand you @whit537.

**Comment by whit537** [comment]
>> functioning withdrawal mechanism
>This would include PayPal and not just bank accounts?

Yes, whatever withdrawal routes we support.

> with a name like Research Projects, you might as well leave things the way they are now.

A "Research Projects" project would approximate one of the founding use-cases of Gratipay. However, it would be explicit, and would exist alongside other use-cases, such as growing small projects into viable open businesses that support many, many people.

**Comment by whit537** [comment]
> The way this is going we better introduce one time payments.

Yeah, maybe.

**Comment by whit537** [comment]
> My point is I'm a fan of one person's overall work, instead of specific projects.

For open-source projects, where is the line between one person's work and the work of many people on a project?

**Comment by whit537** [comment]
> would others be allowed to join such a project?

For the "Research Projects" example I was thinking no: others wouldn't be allowed to join such a Project. Really it'd be up to the owner to decide. My brother-in-law runs a research lab where he employs a dozen people. On that parallel, maybe someone wants to use Gratipay to fund an open-source software R&D lab. Maybe someone else prefers to work alone on ideas, and then spin out a new Project utilizing the Teams feature as an idea gains traction.

> How is this different to a Team?

Teams becomes a Payroll feature (#2569) that attaches to a Project.

**Comment by whit537** [comment]
Users optionally have Projects.
Project optionally have Payroll.

**Comment by tshepang** [comment]
Many people distinguish themselves in multiple projects. Now, I don't want to go look for every project this person has contributed to. I just want person to continue contributing, or I just want to keep saying thanks ($), I'm still using that one tool you wrote years.

That other people deserve reward for their work on the same projects that this person happens to contribute to is a different matter. Teams was built to handle that one problem, I think.

**Comment by whit537** [comment]
> Many people distinguish themselves in multiple projects. Now, I don't want to go look for every project this person has contributed to. I just want person to continue contributing, or I just want to keep saying thanks ($), "I'm still using that one tool you wrote years ago".

"I'm still using that one tool" sounds like a great case for tipping a project. ;-)

That said, maybe everyone who joins Gratipay gets an automatic first project created for them:

**Name:** Tip Jar
**Description:** Tips appreciated. Thank you! :-)
**Homepage:** https://gratipay.com/username/
**Category:** open-source software

They would still have to attach a withdrawal route, etc., in order to "activate" their tip jar.

**Comment by tshepang** [comment]
sounds forced, but I guess you know better... you've had more time to think about this

**Comment by whit537** [comment]
+1 for individuals from https://gratipay.freshdesk.com/helpdesk/tickets/1980:

> Personally, I'm only interested in anonymous support of specific individuals whose open source work or blog posts were useful to me.

**Comment by whit537** [comment]
Closing in favor of #3399.
