### ISSUE TITLE
require a working payout route in order to receive money

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3338]
Reticketing from https://github.com/gratipay/inside.gratipay.com/issues/180.

Reduces escrow, keeping us on the near side of #3321 and better suiting us for #3287 and/or #3245.

**Comment by whit537** [comment]
Done somewhere under #3399.

**Comment by rohitpaulk** [comment]
^^, Closing.

**Comment by whit537** [comment]
:)
