### ISSUE TITLE
Gratipay as an integrative system

### ISSUE THREAD

**Issue by orschiro** [gratipay/gratipay.com#3340]
Dear all, 

I am looking for comments on an idea for a system that would integrate different projects that create social impact. That can range from open source software hosted on Launchpad or Github, to Wikipedia, Mozilla or Greenpeace. 

What is very important, however, as a user (donor) I want the platform to be dead simple to use. I want to keep an overview of my monthly donation amount and easily adjust (branch) the flows to the various projects. 

Please see the below scheme:

![branching social impact](https://cloud.githubusercontent.com/assets/170947/7178224/79d157ec-e42d-11e4-93bc-937e6b521aed.png)

Is this something that could be incorporated into Gratipay?

Thanks ahead!

Robert

**Comment by whit537** [comment]
@orschiro Thanks for jumping in! This sounds a lot like what Gratipay is intended to be. It looks like you've been a member of Gratipay for two years (wow!). What's missing from your Gratipay experience that would help it better match what you're describing here?

**Comment by orschiro** [comment]
@whit537 

Thanks for your quick response! In an essence, gratipay is too inconvenient to use. Let's say I would like to replicate the donation channels above. As a donor I don't want to take care of adding the desired projects to gratipay. That should happen behind the user's scene. I only want to easily select my desired projects (from Github, Launchpad, different foundations, etc.) and select the money to donate to. 

This feels too complicated for me as a user:

![image](https://cloud.githubusercontent.com/assets/170947/7188847/e8611c72-e47a-11e4-8b7d-d8a8ec3d8a62.png)

**Comment by whit537** [comment]
Unfortunately we can only accept tips for projects that decide to use Gratipay. See #28 for backstory.

**Comment by orschiro** [comment]
@whit537 

Thanks for your reference. Let's leave it as is for now. 

Warmly, 

Robert

**Comment by whit537** [comment]
Cheers, @orschiro. :-)
