### ISSUE TITLE
refund infinitechan tippers

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3342]
Now that we've asked infinitechan to leave and they have, we should refund anyone who was tipping only infinitechan. Reticketed from #3341.

**Comment by whit537** [comment]
I'm referring to the escrow balances these users are now carrying.

**Comment by whit537** [comment]
https://docs.balancedpayments.com/1.1/api/debits/#refund-a-debit

**Comment by whit537** [comment]
If I/we don't get to this quick, then it may as well be generalized as part of #1383.

**Comment by techtonik** [comment]
Why we asked infinitechan to leave?

**Comment by webmaven** [comment]
@whit537, has this been done yet?

**Comment by whit537** [comment]
Yes, under #3539.
