### ISSUE TITLE
Inkscape Story

### ISSUE THREAD

**Issue by techtonik** [gratipay/gratipay.com#3351]
By @doctormo via [inkscape-dev](http://inkscape.13.x6.nabble.com/Donating-through-Gratipay-tp4973341p4973359.html):
```
I'd also like to make sure we can record user contributions and
donations no matter how we got them. This is so user contributions are
rewarded and gives them a better community standing than currently.
where I feel coding is always given almost all the reputation points,
followed by docs writers, designers and other jobs and then at dead last
people who help finding :-). Not everyone can pay, not everyone can
code. But helping is helping.
```

There are two points raised, I don't know if we have open issues to address them:
1. [ ] - project needs a way to record people and their donations
2. [ ] - people are given reputation points for donations
3. [ ] - reputation points are not easy to calculate for docs, design and other jobs

From the other side, people may want to preserve privacy:
1. [ ] - users need a way to donate anonymously

So, we need to expose donations via API and provide a convenient interface to count such contributions.

We may also provide a way for people who code to value contributions of other community members, so that you (as a coder) can distribute some amount of points given to you among people who you think are also important for your work, but don't receive the deserved amount of share. This may be a parallel resource to donations, specific to the given project.

**Comment by whit537** [comment]
> So, we need to expose donations via API and provide a convenient interface to count such contributions.

I've added a +1 to #1546.

**Comment by whit537** [comment]
> We may also provide a way for people who code to value contributions of other community members, so that you (as a coder) can distribute some amount of points given to you among people who you think are also important for your work, but don't receive the deserved amount of share. 

We do! It's called money. :-)

Seriously, though, we have translators on the Gratipay team. They take money alongside developers.

**Comment by doctormo** [comment]
It sounded like you were saying we should give money to people who give us money. :palm_tree:
