### ISSUE TITLE
Double emails sent

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#3352]
I made a mistake - [IRC](https://botbot.me/freenode/gratipay/2015-04-18/?msg=36934380&page=1)

Related: https://gratipay.freshdesk.com/helpdesk/tickets/1988

**Comment by rohitpaulk** [comment]
I've deleted the backup I had (`a506.dump`), and the mandrill key too.

**Comment by rohitpaulk** [comment]
Replied to https://gratipay.freshdesk.com/helpdesk/tickets/1988.

**Comment by rohitpaulk** [comment]
Around 140 duplicate emails were sent.

**Comment by whit537** [comment]
Can we send a third email to the 140 that received duplicates? What we really want is a way to send arbitrary emails to arbitrary sets of users using the standard Gratipay email template.
