### ISSUE TITLE
Rename honcho

### ISSUE THREAD

**Issue by techtonik** [gratipay/gratipay.com#3358]
I am getting `No distributions matching the version for honcho==cfcc7ebb (from -r requirements.txt (line 38))` trying to bootstrap GP in Codenvy container. I don't know, maybe it is `pip` bug. Anyway. it should follow Linux (Debian?) version convention - honcho-x.x.x-gp1.
##

**Comment by techtonik** [comment]
gp1 is the Gratipay patch version.

**Comment by whit537** [comment]
We could also retire `honcho` in favor of [`run_dammit`](https://github.com/whit537/whit537.org/blob/419741cb4a59ff32ca2c6933152a4a82b76b8e6c/run_dammit).

**Comment by techtonik** [comment]
Too many redirections - `run_dammit -> honcho -> foreman -> Procfile`. This should be directly linked to http://blog.daviddollar.org/2011/05/06/introducing-foreman.html IMO.

**Comment by nobodxbodon** [comment]
Consider it's obsolete. Please reopen if otherwise.
