### ISSUE TITLE
reverse tab order on Giving page

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3360]
Not sure how I missed this, but Active should be first and Cancelled should be last.

![screen shot 2015-04-23 at 4 57 03 pm](https://cloud.githubusercontent.com/assets/134455/7308412/d8b21eb6-e9d9-11e4-947a-14aef720df6f.png)

**Comment by rohitpaulk** [comment]
Oops! That's the rubyist in me (Hashes maintain order in Ruby).

**Comment by whit537** [comment]
Ah, that explains it. :-)
