### ISSUE TITLE
Revert fe9862b3941(accidentally pushed to master)

### ISSUE THREAD

**Issue by techtonik** [gratipay/gratipay.com#3362]
I accidentally committed fe9862b3941 before review. I tested that it works, but it skips our review process and it should be followed by one more commit to close #3318. Can you revert it for now? Ping @whit537 @Changaco @rohitpaulk

**Comment by whit537** [comment]
I had already merged #3364 before seeing this, so instead of force-pushing fe9862b3941e795ae8f16c2deb9e29733d3eade5 off of master, I reverted it in 461588a644c14333ac5719525525e2f4637705a6. Please be more careful in the future.

**Comment by whit537** [comment]
@techtonik P.S. Changaco is [no longer part](http://changaco.oy.lc/blog/goodbye-gratipay/) of the Gratipay team, so please let's not ping him any more.

**Comment by techtonik** [comment]
That's sad news. I wish I could be available to discuss the issue and propose an alternative. No time for sustainability. Redirected him a $2 pension from my take.

As for Git, it occasionally happens. Can we add a hook script that prevents commit to trunk unless some keyword it present?
