### ISSUE TITLE
One-time payment

### ISSUE THREAD

**Issue by Maxhodges** [gratipay/gratipay.com#3368]
I'd like to just give some developers a one time payment. if I pay $1 per week to several people, more money is lost to credit card processing fees and also it creates additional work at my organization: the accounts payable team needs to enter the transactions each month in order to reconcile them. One-off is much more efficient. please add it as an option.

Cheers!

**Comment by tshepang** [comment]
Dupe of https://github.com/gratipay/gratipay.com/issues/5.

**Comment by rohitpaulk** [comment]
Hey @Maxhodges, I see that you've already commented on #5, so I'm closing this.
