### ISSUE TITLE
react to PGBackups deprecation

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3370]
https://gratipay.freshdesk.com/helpdesk/tickets/2040

**Action Required: Heroku PGBackups Addon Deprecated**

>Earlier this year, we announced the release of our [new PGBackups](https://hello.heroku.com/e/36622/-2015-3-11-pgbackups-levels-up/4dn8dg/461051929).  This new system comes with two big improvements: enhanced reliability and the ability to schedule backups. 
>
Over the coming week we will be migrating backups that have been created using the PGBackups add-on to the [new backup system](https://hello.heroku.com/e/36622/-2015-3-11-pgbackups-levels-up/4dn8dg/461051929).  We've identified apps that you're a collaborator on that will be impacted by this migration:
>
gratipay
>
The backups for these apps will be migrated to the new backup system. If you had automatic scheduled backups with the old PGBackups, we'll set up those scheduled backups in the new system. Although, with the new scheduling functionality, you can [set a backup time](https://hello.heroku.com/e/36622/-schedule-backups-on-your-time/4dn8dj/461051929) that works for you.  A notification will be sent when we start the migration process on your app and another when it completes. Upon completion of the migration, the PGBackups add-on will be removed from the app.
>
Developers are required to use the new backup system and [associated commands](https://hello.heroku.com/e/36622/ticles-heroku-postgres-backups/4dn8dl/461051929).  The new commands can be found in the Heroku Postgres namespace in the CLI instead of a separate add-on.  A [mapping document](https://hello.heroku.com/e/36622/les-mapping-pgbackups-commands/4dn8dn/461051929) has been created to ease the transition from the add-on to the new system.  Please make sure to upgrade your version of the Heroku CLI to at least version 3.32.0 to get the latest PGBackups commands:
>
$ heroku upgrade 
>
If you have any questions, please email us at pgbackups@heroku.com.  In the meantime, look out for the dashboard notifications and follow the @herokuchangelog to stay up to date with additions and changes to the Heroku platform.
>
Happy coding!
>
The Heroku team

**Comment by whit537** [comment]
From skimming it sounds to me like action is *not* required?

**Comment by rohitpaulk** [comment]
#3448
