### ISSUE TITLE
OpenACH for ACH?

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3371]
http://openach.com/

>Greetings!
>
I'm run [*sic*] a crowdfunding website called Gratipay. Our payment processor is going out of business(!), so we're in need of an ACH processor. Gratipay is an "open company" so we're aligned with the "Open" part of OpenACH. ;-)
>
Is OpenACH still active? Could we have a conversation about using OpenACH for Gratipay's ACH credits?

**Comment by whit537** [comment]
Previous mentions:

https://github.com/gratipay/gratipay.com/issues/777#issuecomment-31403103
https://github.com/gratipay/gratipay.com/issues/126#issuecomment-28636637
https://github.com/gratipay/gratipay.com/issues/1519#issuecomment-28643534

**Comment by whit537** [comment]
From:

> Yes, the project is still very much active and alive.  I would love to have a conversation.  What day/time works best for you?

To:

> Awesome, thanks! :-)

Do any of these work? What time zone are you in?
>
11am Thursday, April 30 (tomorrow; US/Eastern)
4pm Thursday, April 30
11am Monday, May 4
4pm Monday, May 4

**Comment by whit537** [comment]
From:

> I'm, in the Central time zone.  If 11am Eastern today still works for you, let's shoot for that.
>
Here's my cell number:

To: 

>Sounds good. I'll call you in ~30 minutes! :-)

**Comment by whit537** [comment]
Okay! Had a call w/ @sbrendtro. OpenACH is a standalone app for interfacing with the ACH network. We still need our own ACH origination account with a bank.

Looks like OpenACH is on Assembla:

https://www.assembla.com/spaces/openach/wiki

**Comment by sbrendtro** [comment]
Hello all, I've heard quite a bit about your platform (since the time it was Gittip), and glad to finally make the connection to your project.  As @whit537 mentioned, we are on Assembla, though I'm slowly getting ready to move things over to Github.  Here's the first move... our Docker container.  Feel free to try it out or clone and customize:

https://github.com/openach/docker-openach

**Comment by whit537** [comment]
Citizens rejected us (#3366), and we're going to try Zipmark (#3491) instead. No need to run OpenACH anymore.
