### ISSUE TITLE
SynapsePay for payouts?

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3373]
http://synapsepay.readme.io/v1.0/docs/show-masspay

**Comment by whit537** [comment]
Synapse is just another Dwolla.

![screen shot 2015-06-04 at 12 17 29 pm](https://cloud.githubusercontent.com/assets/134455/7988967/4fc7ac3c-0ab4-11e5-90ab-55e70a894aab.png)

**Comment by whit537** [comment]
Copying over from @mattbk at https://github.com/gratipay/gratipay.com/issues/67#issuecomment-129966803:

> Inquiry from support: https://gratipay.freshdesk.com/helpdesk/tickets/2766

**Comment by sankaet** [comment]
@whit537 users do not need to Signup for SynapsePay. Check out our whilelabled APIs [here](http://api.synapsepay.com/)

We do all the compliance+risk work for you, user never leaves your UX. Happy to hop on  a call and chat, if you want to learn more.
