### ISSUE TITLE
gravatar image incredibly blurry

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3381]
Reticketed from #3227:

> My gravatar image comes in at 80x80 and is incredibly blurry: https://gratipay.com/Jonathan%20Sundqvist/
##

**Comment by jonathan-s** [comment]
Looking at [this](https://gratipay.com/akshayah3/) page for instance I see that the reference to the image is the following `https://avatars.githubusercontent.com/u/4225167?s=160` I'm assuming that this is stored in a database. I would strip all query tags from the URLs and then implement the solution in my PR. 

The avatars from github follow the gravatar protocol after all. Are there any more image suppliers?

**Comment by whit537** [comment]
Actually, that's not sufficient, because we also use non-Gravatar avatars. I've reverted your PR in #3384. Sorry for the confusion.

**Comment by jonathan-s** [comment]
What are the other image sources that you use?

**Comment by whit537** [comment]
The various social networks we support. Here's a grep:

https://github.com/gratipay/gratipay.com/search?utf8=%E2%9C%93&q=avatar_url

**Comment by jonathan-s** [comment]
Ok, so what I gather is that you pull images from twitter and facebook too. Perhaps it could be solved with some logic in the template to check where the image comes from.
