### ISSUE TITLE
allow admin to search by email

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3382]
Is this a dupe?

**Comment by whit537** [comment]
+1 @mattbk #3809:

> It would save an email back-and-forth if admins could search for ~users by email when a ~username or team name is not provided in an initial support request.

**Comment by mattbk** [comment]
Note to self that this would still be useful.

**Comment by mattbk** [comment]
/me wonders if it might be as easy as changing https://github.com/gratipay/gratipay.com/blob/master/www/search.spt...
