### ISSUE TITLE
double-vault new cards at Balanced and Braintree

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3387]
Reticketed from #3377.

**Comment by rohitpaulk** [comment]
Why double vault? Can't we just send the new cards to Braintree, and migrate old cards there too?

**Comment by whit537** [comment]
@rohitpaulk I was thinking that that introduces a race condition, but since we don't process continuously and in fact aren't processing at all right now, maybe we should just go for it.

**Comment by whit537** [comment]
In order to avoid the race condition, we need to start vaulting new cards at Braintree before the transfer is initiated. The trick is that we want to *complete* the transfer before running payday on Braintree.

**Comment by rohitpaulk** [comment]
Yep. I'm working on vaulting new cards first for #3389. Once that's done, I'll visit the billing/exchanges functions.

**Comment by whit537** [comment]
@rohitpaulk Awesome, thank you. Let's deploy the vault changes ASAP. Let's change billing/exchanges in a separate PR, please.

**Comment by whit537** [comment]
Per https://github.com/gratipay/gratipay.com/issues/3377#issuecomment-100375980 there probably *is* a race condition, due to updates. I don't have time to rethink it all through again but we should.

**Comment by rohitpaulk** [comment]
Simplest solution here is to send all new cards **and** updated cards to braintree. And of course, not run them until we've moved off balanced.

**Comment by rohitpaulk** [comment]
AFAICT, we don't actually 'update' cards, we add a new payment method and [invalidate the old one](https://github.com/gratipay/gratipay.com/blob/master/www/%25username/routes/associate.json.spt#L46-L47).

**Comment by rohitpaulk** [comment]
I'm closing this. #3389 is ready for review. Updating a card vaults it with Braintree, and invalidates the previous card at Balanced.
