### ISSUE TITLE
write new terms

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3390]
We are writing new terms of service ~~for receivers~~, for two reasons:

 - There is legal uncertainty regarding our old terms (https://github.com/gratipay/inside.gratipay.com/issues/192).
 - We are pivoting (https://github.com/gratipay/inside.gratipay.com/issues/180).

This is a public ticket with a parallel private ticket where I'll be communicating with our lawyer, @copiesofcopies. Depends on https://github.com/gratipay/gratipay.com/issues/3367.

**Comment by whit537** [comment]
Copying from https://github.com/gratipay/inside.gratipay.com/issues/180#issuecomment-100511822, here's the sort of language I envision:

#### Apply to Receive
>
To receive payments on Gratipay, you must meet these criteria:
>
 - [ ] Offer goods or services in exchange for voluntary payments.
 - [ ] Offer open work. That is, you must provide a clear path for any individual to voluntarily begin contributing effort to the production and delivery of the goods and services you offer, and to be paid for the same (whether via Gratipay's Payroll feature or some other mechanism).
 - [ ] Not clash too strongly with our [brand](http://inside.gratipay.com/big-picture/brand/).
 - [ ] Provide a working withdrawal mechanism.

**Comment by dcht00** [comment]
I like this. Re first point - there's a fundamental difference of cases where no value is expended in an new instance (like a copy of software), to where there is (like daily food expenses of staying at a hackbase).
This was problematic/confusing for us and some of the contributors at https://gratipay.com/chtotalism/

**Comment by whit537** [comment]
> This was problematic/confusing for us and some of the contributors at https://gratipay.com/chtotalism/

Say more? Contributors had trouble knowing what to pay? Or how to split it? Or ... ?

**Comment by dcht00** [comment]
Because of the nature of the project (=has significant expenses connected to participation), the problem was understanding if Gratipay contributions are
1) pure donations (which will be used to finance project infrastructure), OR
2) should they count toward covering the expenses of hosting the contributors

**Comment by fenryxo** [comment]
Hi. I'm writing on behalf of http://gratipay.com/NuvolaPlayer (https://github.com/tiliado/nuvolaplayer here on GitHub). I'm a bit concerned whether I can meet the second criterion. The Nuvola Player project currently has only one developer (me), whose work is paid from donations, and a few occasional contributors. Although I would love to, I cannot afford to pay to these contributors for their work.

**Comment by silverhook** [comment]
Hullo. I’m writing on behalf of the [hackerspace Cyberpipe/Kiberpipa][cp] ([gratipay page][gp]). The legal entity we operate under is an NGO called [LUGOS – Linux User Group of Slovenia][lugos]. 

We are also also a tad concerned about the second criterion – especially the `“[…]to be paid for the same”` part. Currently we do have one employee, but this is a first ever since the LUG started in 1997. In general we are just a bunch of volunteers and the biggest expenses for us are the rent and equipment. At the moment we are fine with having an employee, but I cannot guarantee that we will always have one.

Regarding actually receiving the payments, we would very much like to see the option to directly transfer the donations onto bank accounts outside the US (in our case Slovenia, EU).

[gp]: https://gratipay.com/Kiberpipa/
[cp]: https://www.kiberpipa.org/en/
[lugos]: http://www.lugos.si

**Comment by mitar** [comment]
Hypothetically: Am I as an open source contributor to other open source projects offering any goods or services? I do not think so. So I will be excluded?

**Comment by whit537** [comment]
At https://github.com/gratipay/inside.gratipay.com/issues/180#issuecomment-100411554:

> Also, we're going to need to define "open culture" as clearly as possible since that's a line between projects we want and projects we don't.

+1 at https://gratipay.freshdesk.com/helpdesk/tickets/2116.

I'm seeing this ticket as our attempt to do this.

Back up, though: **Thank you** to all who have joined the discussion already and also those who are watching and those yet to discover us here. This is a crisis moment in the best sense of the word for Gratipay. It falls to us to decide what we want Gratipay to be for the next phase of its life. I see [32 (2^5) projects/entities](https://github.com/gratipay/inside.gratipay.com/issues/198#issuecomment-100410836) that I consider the "embers" of the old Gratipay, which, gathered together on this ticket together with anyone else who cares to participate, are going to form the core of the new Gratipay. We have an opportunity before us. I feel as if you all are people I should know way better than I do. I want Gratipay to be a community with a shared vision of what we're about and what it means to be a receiver, and building that new community starts on this ticket.

That said, my feeling is that we're under a bit of a time crunch, because we have stopped processing, and we can't start up again until we finalize our new terms of service. I know Gratipay is under financial pressure because of this, and I imagine the same is true for many of you as well. My hope is that we can work together to get through this, and emerge stronger, with renewed momentum.

But enough bullshit, let me actually read your comments now ... ;-)

**Comment by whit537** [comment]
I'm hearing concern from @fenryxo and @silverhook about criterion (2):

> [Y]ou must provide a clear path for any individual to voluntarily begin contributing effort to the production and delivery of the goods and services you offer, and to be paid for the same[.]

I believe the core of the concern is that income is so low that it barely covers expenses and perhaps a bit of labor, but certainly there is not a lot of extra revenue to share with contributors. Am I hearing you right?

My intention with (2) is that there be a clear process for sharing revenue, but we can hardly expect you to share more revenue than you have!

For example, on the Gratipay project itself, we publish a [budget](http://inside.gratipay.com/appendices/finances), and all contributors who have [access to revenue](https://gratipay.com/Gratipay/members/) also have access to the budget. This allows contributors to decide appropriately what they will take from the group's revenue, because of course all contributors understand the need to cover the group's expenses.

The same general principle applies in balancing "peripheral" contributor takes against "core" contributor takes. As you can see, I [take the largest](https://gratipay.com/Gratipay/members/) portion of Gratipay's revenue, with a few other contributors taking a significant but smaller portion, and a larger number taking a small or token amount.

The goal is to see a snowball effect, where contributors are financially incentivized to contribute to a project, which causes the project to be more successful, leading to increased revenue, which enables even more people to get involved.

**Comment by whit537** [comment]
Am I hearing you right, @fenryxo @silverhook? Does what I said address your concerns at all?

**Comment by whit537** [comment]
> Regarding actually receiving the payments, we would very much like to see the option to directly transfer the donations onto bank accounts outside the US (in our case Slovenia, EU).

I have a meeting with Citizens Bank on Thursday to discuss Gratipay's treasury services needs (#3366), specifically ACH. I'll make a point to ask them about international transfers as well.

**Comment by whit537** [comment]
> Hypothetically: Am I as an open source contributor to other open source projects offering any goods or services? I do not think so. So I will be excluded?

@mitar At this point, I believe individuals are categorically excluded from receiving, per https://github.com/gratipay/inside.gratipay.com/issues/180#issuecomment-100497390. However, I haven't yet digested your comment at https://github.com/gratipay/inside.gratipay.com/issues/180#issuecomment-100541145 ...

**Comment by ehmatthes** [comment]
Overall, I don't feel like I belong on gratipay anymore. But then when I read through the criteria above I feel like I meet all four criteria, or could easily:

> Offer goods or services in exchange for voluntary payments.

I'm building [introtopython.org](http://introtopython.org), an open resource for teaching and learning Python. It's gotten good feedback so far, and I'm picking up development on it again. It is one of the "goods and services" I offer in my open work.

> Offer open work. That is, you must provide a clear path for any individual to voluntarily begin contributing effort to the production and delivery of the goods and services you offer, and to be paid for the same (whether via Gratipay's Payroll feature or some other mechanism).

The project is [hosted on github](https://github.com/ehmatthes/intro_programming). There's a clear path for anyone to contribute. They can then set up a gratipay account as well. Or, I can set up a gratipay payroll structure for the project.

> Not clash too strongly with our brand.

I think my work, although low-traffic at this point, is in line with the gratipay brand. It's certainly open work.

> Provide a working withdrawal mechanism.

I have.

So do I belong on gratipay? I'm not just asking for my own sake, I'm also asking because I think there are a good number of current users in a similar situation.

**Comment by techtonik** [comment]
@whit537 these rules lack the open explanation *why*. I suspect that the short answer to that is that if we don't comply with them, we all will be money laundering criminals in the U.S. state law. But is still not clear why exactly, and, more importantly, how the law could be changed to allow service like Gratipay to exist.

It adds to the problem that there is not much time to read up on these details.

**Comment by fenryxo** [comment]
> I believe the core of the concern is that income is so low that it barely covers expenses and perhaps a bit of labor, but certainly there is not a lot of extra revenue to share with contributors. Am I hearing you right?

Exactly, there is not a lot of extra revenue to share with contributors for now. I plan to start sharing the revenue as soon as I get funded at least one work week monthly (40 hours, €10 per hour) of my own work on the project. This is a reasonable threshold that allows me to do some core development, manage package repositories, respond to support requests and actually review and accept pull requests from contributors. The contributors will be paid individually based on their preferred payment method (e.g. Gratipay, PayPal, Patreon, Bitcoin, ...). Is this revenue sharing model with a threshold OK for Gratipay?

**Comment by whit537** [comment]
> I'm building introtopython.org[.] So do I belong on gratipay?

@ehmatthes Excellent question. I would say introtopython.org certainly belongs on Gratipay. What's the relationship between it and you?

**Comment by whit537** [comment]
> Is this revenue sharing model with a threshold OK for Gratipay?

@fenryxo Yes, definitely, as long as it's clearly communicated up front so when I'm evaluating whether or not to contribute to NuvolaPlayer I can potentially use that information to inform my decision. "Hmmm ... what are the chances I could get paid eventually for hacking on NuvolaPlayer? Let's see ..."

I'm expecting we'll add a free-text field to Gratipay receiver profiles precisely for this info, so "clearly communicating" will just mean filling out that field. :-)

**Comment by whit537** [comment]
> I suspect that the short answer to that is that if we don't comply with them, we all will be money laundering criminals in the U.S. state law.

@techtonik Per https://github.com/gratipay/inside.gratipay.com/issues/180#issuecomment-100497390: 

>Legal concerns made us stop with our old model, but it's business vision that is driving our new model.

**Comment by techtonik** [comment]
@whit537 I think about roles that people could like to stick to. Like clearly communicating you're role on GP. Like (1) you're an individual and don't want to care about all the stuff, just want to give people something for a living and willing to spend tips on beer and don't think they are anything serious. Or (2) you're an individual, who invests a lot of time in your open source projects, can't live without it and hope that GP can help with meeting the ends. Or (3) you want to use GP values to indicate which people and projects are important for you.

The major difference of (2) is that this person probably wants to pay taxes and get pension. "probably" because it is criminal not to pay them. But we can't be criminals if people don't pay taxes. We could clarify and help people do this. This can be our business value to them.

But aforementioned legal concerns are not about taxes. They are about "money laundering". Is that the same?

**Comment by silverhook** [comment]
> I believe the core of the concern is that income is so low that it barely covers expenses and perhaps a bit of labor, but certainly there is not a lot of extra revenue to share with contributors. Am I hearing you right?

This is true. And there are other sources of income for us as well. Un unsubstantial part of this is grants for specific projects that we undertake in the LUG/hackerspace.

> My intention with (2) is that there be a clear process for sharing revenue, but we can hardly expect you to share more revenue than you have!

A further complication is that while the LUG has an open membership, neither the LUG nor its hackerspace have so far requested people to apply for membership in order to participate on any level (only for the right to vote inside the LUG). This open for all approach has served us well for a very long time now and changing it could disrupt the community.

I mention this, because it is somewhat related to the process of sharing revenue. The main point of a hackerspace is that what is being shared is the space, the knowledge, tools, equipment etc. This is what we spent most of our funds on and this is being shared with everyone.

*If* we had a that kind of money, we could reenstate the rule that people who do boring repetative tasks (such as organising events, rendering videos, running a proper PR), they would get reimbursed for their time.

If that qualifies, we do have a clear process for sharing revenue (in the case we at some point get enough revenue again).

**Comment by ehmatthes** [comment]
> @ehmatthes Excellent question. I would say introtopython.org certainly belongs on Gratipay. What's the relationship between it and you?

I built introtopython.org almost entirely myself so far. One of the main features of introtopython is the set of projects that people can engage in once they've learned the "Python essentials". In the next phase of work, I'm going to add another project and then invite others to start adding projects.

One project I'd love someone to contribute: how to use Python to control a servo motor. I don't have experience with physical devices, but someone who does could write up a quick ipython notebook covering the process, and it would be pulled right into introtopython.

So introtopython is a project I develop locally, push to github, and push to a server. introtopython could be really meaningful with me as the primary maintainer, and periodic one-off contributions from others. Someone could contribute regularly, but it's not critical to the project. It's also built as a platform for developing your own Python course. People have started exploring using iit as a platform for developing in-house Python data materials.

I have another project, [opencompetencies.org](http://opencompetencies.org) that's a much larger-scale project. I will definitely aim to build a team around opencompetencies. opencompetencies deals with education in general - it's way bigger than one person, and it leads to a suite of tools related to making education more open and efficient.

I want to build funding streams related to each of my projects, but also to myself as someone who mixes expertise in the education world with competence in the programming world. Programming will be my "second job" for the foreseeable future, and a moderate income through gratipay would let me focus on consistent development on these projects.

**Comment by ehmatthes** [comment]
> Exactly, there is not a lot of extra revenue to share with contributors for now. I plan to start sharing the revenue as soon as I get funded at least one work week monthly (40 hours, €10 per hour) of my own work on the project. This is a reasonable threshold that allows me to do some core development, manage package repositories, respond to support requests and actually review and accept pull requests from contributors. The contributors will be paid individually based on their preferred payment method (e.g. Gratipay, PayPal, Patreon, Bitcoin, ...). Is this revenue sharing model with a threshold OK for Gratipay?

This sounds like a clear and concise policy that would work well for many projects.

**Comment by whit537** [comment]
>But aforementioned legal concerns are not about taxes. They are about "money laundering". Is that the same?

@techtonik No, not the same. Re: taxes Gratipay offloads to the receivers and individuals. Re: money laundering, our primary obligation is to "know your customer" (KYC), i.e., verify identity in proportion to transaction volume and other risk factors, and report suspicious activity.

**Comment by whit537** [comment]
>I want to build funding streams related to each of my projects, but also to myself as someone who mixes expertise in the education world with competence in the programming world.

@ehmatthes Under the new Gratipay you could of course build funding streams related to each of your projects. That's definitely on target. You would just have a different Gratipay account for each project (just as you probably have a different GitHub account/repo, different Twitter, etc.). No-strings-attached funding streams to an individual, however, are precisely what we are having to give up.

I'll tell you what, though. For myself, I've been hoping that if Gratipay succeeds then I'll be able to keep taking a small draw from it for a long time, even if I move on to other projects in terms of my day-to-day efforts. I can imagine John Resig doing the same with jQuery, Guido with Python, Matz with Ruby, etc., etc. I'm seeing that as a workaround for the direct "genius grant" model of old Gratipay.

So I think the story for you on new Gratipay, @ehmatthes, is to make two accounts: introtopython and opencompetencies. Once you've gotten opencompetencies off the ground, you can keep a baseline of "emeritus" income coming from there in balance with the opencompetencies team, while being free to move on to other projects. Is that something you can live with?

My goal for Gratipay is to see thousands and thousands of projects such as introtopython and opencompetencies flourish. More open projects means more open work for everyone! I think it's appropriate that the founders of successful projects under this model enjoy some financial flexibility in view of their starting a successful project. This is parallel to the way founders of closed companies get rich on exit, but it's muted in proportion to the greater solidarity that founders in the open model share with everyone else they're working alongside.

**Comment by whit537** [comment]
> The main point of a hackerspace is that what is being shared is the space, the knowledge, tools, equipment etc.

Point taken, @silverhook. I was pleasantly surprised to discover that 7 of the 32 users specifically invited to join this discussion (22%) are hackerspaces:

http://gratipay.com/catapultpgh
http://gratipay.com/chtotalism
http://gratipay.com/Kiberpipa
http://gratipay.com/noisebridge
http://gratipay.com/omnicommons
http://gratipay.com/pocmakerspace
http://gratipay.com/sudoroom

I love the idea of using Gratipay to fund hackerspaces! Now I want to visit all of you! :airplane: Probably makes sense to start in :deciduous_tree:land. :-)

As you explain, the funding needs of hackerspaces are different from those of open-source projects. @dcht00 commented on this [above](https://github.com/gratipay/gratipay.com/issues/3390#issuecomment-100515797) as well.

How about if we make the following change?

> Offer open work. That is, you must provide a clear path for any individual to voluntarily begin contributing effort to the production and delivery of the goods and services you offer, and ~~to be paid for the same~~ **a clear explanation of how contributors share in any revenue the project generates** (whether via Gratipay's Payroll feature or some other mechanism).

**Comment by whit537** [comment]
I've approached @copiesofcopies privately to make sure we're going to be able to include hackerspaces under the new terms.

**Comment by whit537** [comment]
Also, I want to include a public vetting process here on GitHub as part of the application process for becoming a receiver on Gratipay. The existing Gratipay community should have input, especially regarding point (4), brand/community fit. "Speak now or forever hold your peace."

**Comment by ehmatthes** [comment]
> So I think the story for you on new Gratipay, @ehmatthes, is to make two accounts: introtopython and opencompetencies. Once you've gotten opencompetencies off the ground, you can keep a baseline of "emeritus" income coming from there in balance with the opencompetencies team, while being free to move on to other projects. Is that something you can live with?

I think I can. Do people now make an individual account, then make an account for each project? I assume funds go from individual gratipay donor -> gratipay project -> individual gratipay receiver?

**Comment by whit537** [comment]
>I think I can.

:steam_locomotive: :train: :train: :train: 

!m @ehmatthes

Thank you! :dancer: 

>Do people now make an individual account, then make an account for each project?

Unclear. Thinking that through now, whether we need to pull off #3337 before Thursday. I hope not, though it could makes sense for the future.

>I assume funds go from individual gratipay donor -> gratipay project -> individual gratipay receiver?

Yes. We also need to think through the implications of that for pachinko (regifting on Gratipay within a single payday).

**Comment by whit537** [comment]
Sounds like @copiesofcopies is thinking we'll have one terms of service that covers all parts of Gratipay (giving, receiving, taking). I've renamed this ticket to reflect that.

**Comment by whit537** [comment]
@copiesofcopies response [re](https://github.com/gratipay/gratipay.com/issues/3390#issuecomment-100732046): hackerspaces:

> I don't think this is controversial. The hackerspace is providing a space, tools, classes, etc. That sounds like a service to me.

**Comment by whit537** [comment]
Let's make sure our new terms are clearer about Gratipay's fees: #3319.

**Comment by webmaven** [comment]
From https://github.com/gratipay/inside.gratipay.com/issues/180#issuecomment-100574071:

> Are they approaching us as an individual? Yes. Are they approaching us as a corporation that fits our criteria? No.

and from https://github.com/gratipay/inside.gratipay.com/issues/180#issuecomment-100934529:

> With only a bit of guidance in the UI, They would approach as a one-person-corp.

> As you noted, Gratipay LLC itself is such a corporation. All I am saying here is that we should make sure that the next Gratipay (and Chad) aren't turned away, even when they are still at the one-person-corp stage.

Based on the subsequent discussion here, am I to understand that the criteria *will* allow an individual with a corporation to establish open work Projects even if they are the only starting team member? And that this will allow Gratipay to offer a path forward to more of it's current users, rather than just shoving them off onto alternative platforms like Patreon?

**Comment by silverhook** [comment]
> @copiesofcopies response re: hackerspaces:
> I don't think this is controversial. The hackerspace is providing a space, tools, classes, etc. That sounds like a service to me.

I would argue the same.

Good that we’re on the same page and in the clear on this ☺

**Comment by whit537** [comment]
> And that this will allow Gratipay to offer a path forward to more of it's current users, rather than just shoving them off onto alternative platforms like Patreon?

This is my understanding, yes. See discussion at https://github.com/gratipay/gratipay.com/issues/3399#issuecomment-101000562 and implementation underway on https://github.com/gratipay/gratipay.com/pull/3400.

**Comment by whit537** [comment]
>Based on the subsequent discussion here, am I to understand that the criteria *will* allow an individual with a corporation to establish open work Projects even if they are the only starting team member?

Yes. With or without a corporation, in fact. An individual without a corporation would then simply be operating as a sole proprietor (at least in the U.S.).

**Comment by whit537** [comment]
Okay! New terms are drafted and ready for review: #3408! :hatching_chick: :dancer:

**Comment by webmaven** [comment]
@whit537:
> @webmaven Yes. With or without a corporation, in fact. An individual without a corporation would then simply be operating as a sole proprietor (at least in the U.S.).

This is probably worth some activity on social media, even a blog post, to reassure a few of the folks that you scared earlier.

**Comment by whit537** [comment]
> This is probably worth some activity on social media, even a blog post, to reassure a few of the folks that you scared earlier.

Right now the preponderance of our effort has to go into #3408 and #3414 if we're going to pull off #3415 tomorrow. If we can get back on track tomorrow with at least a couple other users then yes, we'll make a blog post about the new system. Reticketed as #3419.
