### ISSUE TITLE
constrain payday based on approval

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3396]
Once new terms (#3390) and approval process (#3395) land, we need to constrain payday to only process payments for approved receivers.

**Comment by whit537** [comment]
Done in #3414!

**Comment by rohitpaulk** [comment]
> Done in #3414!

Not exactly, we still haven't constrained the payout phase.

**Comment by whit537** [comment]
Good point.

**Comment by rohitpaulk** [comment]
The last part of this is #3450.

**Comment by rohitpaulk** [comment]
We have constrained payday based on approval for team owners, what's left is payroll - that is part of https://github.com/gratipay/gratipay.com/milestones/Payroll. Closing this.
