### ISSUE TITLE
implement team member opt-in

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3397]
With our new terms (#3390) we'll need all team members to re-accept the new terms in order to receive their takes.

**Comment by rohitpaulk** [comment]
I'm thinking of decoupling team memberships from `takes`/`payroll` and creating a separate table named `team_memberships`.

**Comment by whit537** [comment]
Not a bad idea. Changaco suggested this at one point (too busy to dig up the reference atm).

**Comment by webmaven** [comment]
@rohitpaulk:
> I'm thinking of decoupling team memberships from ```takes/payroll``` and creating a separate table named ```team_memberships```.

Is this intended as a temporary measure? If not, you've implicitly created a category of 'third class citizens' who are members but have no take (however small).

**Comment by mattbk** [comment]
Is this still relevant after removing payroll and Gratipay 2.0?

**Comment by whit537** [comment]
> Is this still relevant after removing payroll and Gratipay 2.0?

This is relevant to *bringing back* payroll. However, I'm closing this as a ticket now that we have #3994 (the idea is captured there). This should reappear as a PR when the time is right.
