### ISSUE TITLE
review copy across website

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3398]
@webmaven at https://github.com/gratipay/inside.gratipay.com/issues/180#issuecomment-100934529:

>>Are they approaching us as an individual? Yes. Are they approaching us as a corporation that fits our criteria? No.
>
With only a bit of guidance in the UI, [they] *would* approach as a one-person-corp.
>
As you noted, Gratipay LLC itself is such a corporation. All I am saying here is that we should make sure that the next Gratipay (and Chad) aren't turned away, even when they are still at the one-person-corp stage.
>
This has implications not just for the wording of the criteria, but for the UI, help text, FAQ, etc.

**Comment by mattbk** [comment]
https://github.com/gratipay/gratipay.com/issues/3677 is part of this.

**Comment by whit537** [comment]
Okay! I made a [pass through all the About pages](https://github.com/gratipay/gratipay.com/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+author%3Awhit537+created%3A%222015-08-17+..+2015-08-18%22) except for [stats](https://github.com/gratipay/gratipay.com/issues/3446) (also, Pricing is affected by [cached values](https://github.com/gratipay/gratipay.com/pull/3599)).

**Comment by whit537** [comment]
We've rewritten pretty much all the copy on the site. Closing.
