### ISSUE TITLE
regression in credit card form

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3401]
https://app.getsentry.com/gratipay/gratipay-com/group/65471207/

I visited https://gratipay.com/about/me/routes/credit-card.html after #3389.

**Comment by rohitpaulk** [comment]
Ah, i forgot to mention steps for deployment - You'll have to add `participant_id` as a valid custom field in Braintree's dashboard. 

Go to `settings` > `processing`, scroll down till you see 'Custom Fields'

![screenshot from 2015-05-12 14 56 19](https://cloud.githubusercontent.com/assets/3893573/7583931/5cbb6276-f8b7-11e4-87ad-2c4efeacfbfc.png)

In the form, fill out `api_name` as `participant_id`, and check 'Store and pass back'

**Comment by whit537** [comment]
Awesome. I can load the credit card form now.

**Comment by whit537** [comment]
And I can save a card in production. I notice that we now display the first 6 along with the last 4 digits of the user's credit card number. We also require post code and have no option to add address info (we'll do that on identity?).

**Comment by whit537** [comment]
I see my card in the Braintree dashboard.

**Comment by whit537** [comment]
!m @rohitpaulk
