### ISSUE TITLE
Fix payday to write to payments table

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#3427]
Reticked from https://github.com/gratipay/gratipay.com/issues/3415#issuecomment-102185230.

This should include back-filling data for Payday 154.

**Comment by whit537** [comment]
We do `INSERT INTO payments`, in `update_balances`. As discussed on #3415 it's looking like that function didn't get run.

**Comment by rohitpaulk** [comment]
Ah, I created this ticket when I still hadn't figured out what happened. Closing this, let's work directly on #3415.
