### ISSUE TITLE
turn subscriptions back on in UI

### ISSUE THREAD

**Issue by schettino72** [gratipay/gratipay.com#3432]
Ok, that sounds stupid but I can't find the donation widget anywhere in the site.

I am using Firefox 36.0.4 on linux. I browsed the site with the console open but did not see any js error popping up.

**Comment by whit537** [comment]
@schettino72 Thanks for writing in, sorry for the confusion. :-(

We are in the midst of [a huge transition](https://github.com/gratipay/gratipay.com/issues/3399), during which we've disabled the donation widget. Let's use this ticket for bringing it back.

**Comment by whit537** [comment]
+1 on https://gratipay.freshdesk.com/helpdesk/tickets/2140:

>Hey, thought you guys would like to know, I tried to click the button to give $2 a month to gratipay, but it keeps coming back with an error.

**Comment by whit537** [comment]
+1 https://gratipay.freshdesk.com/helpdesk/tickets/2130

**Comment by whit537** [comment]
+1 from @colans on #3447:

> I searched all over the Web UI, but couldn't find a way to cancel a weekly tip/payment I'm making. Is this not possible? I would expect there to be a widget on the https://gratipay.com/~$USER/giving/ page allowing me to stop a payment.

**Comment by whit537** [comment]
+1 @deltab at https://github.com/gratipay/gratipay.com/issues/3447#issuecomment-102573883.

**Comment by whit537** [comment]
Can you review this one? I'd like to get #3419 out the door this evening.

**Comment by whit537** [comment]
... out the door after #3465, of course. ;-)
