### ISSUE TITLE
set fee structure for bank payouts

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3443]
We're on track to switch to Citizens for bank payouts via ACH and IAT (#3366). Our policy is to pass processing fees through to users at cost. Balanced hasn't charged us at all for payouts, as a special-case. Citizens has a more complicated fee structure. How should we structure fees for payouts?

**Comment by whit537** [comment]
Citizens gives us access to 25 countries through IAT, but the per-transaction costs are different: $1 for IAT vs. 15¢ for ACH. I'd love it if we could implement this in such a way that any Gratipay user who uses our Citizens implementation is treated the same. Can we aggregate all fees and allocate it per-user based on their transaction volume? Or can we find a flat percentage that should work, adjusting it over time?

Of course, accounts will still be in USD. :-/

**Comment by whit537** [comment]
Looks like we're going with Zipmark (#3491). They charge 50¢ each up to 500/month, but they've got a  $250 minimum, so the per-unit pricing doesn't really kick in until 501, at which point it's 35¢. We're going to have to eat the $250 minimum for a while (we were at just about 500/mo before the [Gratipocalypse](https://medium.com/gratipay-blog/gratipocalypse-42fd0ec0d9e8), now we're at, like, 25/mo).

**Comment by whit537** [comment]
Charging users at cost for this would I guess look like dividing the number of payouts into $250, but that'd be $10/each to start with, which is absurd. We're going to have to eat this to some degree. The 50¢ price is fairly arbitrary given the minimum. Should we just charge 35¢ out of the gate? Or should we charge $1? Our current payout minimum is $10, so $1 would be a lot, and 50¢ is still a fair amount.

**Comment by kaguillera** [comment]
+1 for 50¢

**Comment by whit537** [comment]
Moot with #3567.
