### ISSUE TITLE
clean up stats page

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3446]
Reticketed from #3415.

**Comment by whit537** [comment]
+1 https://gratipay.freshdesk.com/helpdesk/tickets/2151

> The current stats page says:
>
Gratipay is 35 months old and has 5 active users.
>
1 participants gave money in the past week.
0 received money.
-4 did both.
>
The -4 looks suspicious; just thought I’d let you know!

And:

> Here’s another suspicious number found on the pricing page:
>
>> 11140% of active users pay for Gratipay. Will you join them?

**Comment by ehmatthes** [comment]
I made an account for introtopython.org last week, and it was one of the teams that should have been included in last week's payday. But my balance is low enough that I didn't get a payout.

How will I know if my accounts are set up correctly, ie if my team was included in last week's payday? I don't know how to view my team account, or if it's even possible to view a profile page for that team yet. introtopython is not included in my teams page. My individual history doesn't show anything after payday 152.

**Comment by whit537** [comment]
@ehmatthes Yes, your balance was too low for a payout. We need to fix up history pages to show data from the new `payments` table as well as the old `transfers` table; reticketed as #3455.

**Comment by mcdonc** [comment]
Hi @whit357 and crew.  Thanks for turning the ship instead of giving up!  You are pretty awesome.

I'm wondering if there's anything individuals have to (or will have to) do in order to start receiving payments again when the dust settles.  I've tried to grok what's happening by reading the various github tickets, but it's still a little unclear.  In my case, I probably do have a balance high enough for payout (the last payout I had [and probably a lot of others] was 152), so on Friday, if everything remains static as far as contributions go,  payout 155 on friday (if the ship has turned by then and I do the right stuff) should result in a deposit of about $390.00 (~ $130/wk for 3 weeks, covering periods 153, 154, and 155).  Is that about the shape of things, delta the question of being able to do payouts during 155 at all?

**Comment by whit537** [comment]
@mcdonc Short story is https://gratipay.com/new. Long story we expect to announce tomorrow. Draft announcement is [here](https://medium.com/@Gratipay/2453d3c53077), with discussion [here](https://github.com/gratipay/gratipay.com/issues/3419). I don't see a reason from our end that you can't get back on track for 155, we just need you to fill out our application with an appropriate "Team" for your work. Take a look at those links and then feel free to ask here for clarification.

However, weeks 153 and 154 are lost. I'm really, really sorry. I know you were counting on us. :-(

**Comment by mcdonc** [comment]
Aw it's not a problem at all, truly and really, don't be sorry.  I'm so glad for your efforts; they've helped me through some very rough patches.  Thanks for filling me in.

**Comment by whit537** [comment]
@mcdonc I was thinking it could make sense in your case to create a Gratipay Team for Agendaless, and migrate your payments to that. What do you think?

**Comment by mcdonc** [comment]
Possible.  I'm not sure that any other Agendaless member currently receives or gives tips, but I don't have a problem with that.

**Comment by mcdonc** [comment]
Actually, now that I think of it, it's a lot more useful to me to receive payments to my personal account so I don't have to wait for Agendaless to cut me a check; this feature has saved my bacom a number of times when things got tight.  I could create an Agendaless account, but it'd be tied to my own personal account, which might be a little shady.  Thoughts?

**Comment by whit537** [comment]
@mcdonc Hmmm ... this conversation deserves its own thread. Can we pick up on https://github.com/gratipay/inside.gratipay.com/issues/208?

**Comment by mattbk** [comment]
Would like to reiterate the need for an updated stats page; could this title drop "for payday 154"?

**Comment by whit537** [comment]
@mattbk Yes, good find.

**Comment by techtonik** [comment]
How about this roadmap? =)

* [ ] encapsulate all stats calculations into one module
* [ ] fix the views

**Comment by mattbk** [comment]
Keep in mind that all paydays are still manual: https://github.com/gratipay/gratipay.com/issues/3634

**Comment by mattbk** [comment]
Perhaps the stats page could temporarily be hidden, since it is not showing accurate information?  I have no idea how hard it will be to clean this page up.

**Comment by mattbk** [comment]
Things on the stats page that need to be calculated ([x] indicates that it looks okay):
- [x] Gratipay is ___ months old
-

**Comment by whit537** [comment]
Blam! :-)

![screen shot 2015-08-31 at 4 08 22 pm](https://cloud.githubusercontent.com/assets/134455/9589192/ac7b3936-4ffa-11e5-8770-a286f732996d.png)

**Comment by mattbk** [comment]
Looks good!

This one confuses me:
![image](https://cloud.githubusercontent.com/assets/3729038/9589487/5461e502-4ff4-11e5-8670-33a8636a54b4.png)

**Comment by whit537** [comment]
@mattbk That chart is saying that $280 of our volume comes from payments in the $50.01 to $100.00 range, while $274 comes from payments in the $2.01 to $5.01 range, and only $23 from the 1¢ to 10¢ range.

**Comment by whit537** [comment]
It's to be read with the previous chart, which shows the *number* of payments in each bucket. The $280 in the high bucket comes from three payments, while the $23 in the low bucket comes from 270 payments.

![screen shot 2015-08-31 at 5 59 24 pm](https://cloud.githubusercontent.com/assets/134455/9591566/2e5399b2-500a-11e5-96b4-4cb88a32d761.png)
