### ISSUE TITLE
reverse eight accidental payouts

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3453]
During last week's payday (#3415; the first under Gratipay 2.0), we [accidentally paid out](https://github.com/gratipay/gratipay.com/issues/3415#issuecomment-102181981) to eight people that we shouldn't have. It hurts, but I think we need to issue reversals of these payouts. :-(

Let's try to notify the users privately via email.

**Comment by whit537** [comment]
Bah. We've also got people closing their accounts, and withdrawing that way (cf. https://github.com/gratipay/gratipay.com/pull/3392#issuecomment-100435765). :-(

**Comment by whit537** [comment]
It feels to me like a bridge too far to reverse bank payouts on closed accounts.

**Comment by whit537** [comment]
Two of the eight failed anyway.

**Comment by whit537** [comment]
I've issued reversals for the six successful accidental payouts last week. They will four or five days to process. Now to notify users ...

**Comment by whit537** [comment]
Upon reviewing history for the six users, I would actually expect two more of these payouts to fail (they've been failing in the recent past). That leaves four accidental successful payouts.

**Comment by whit537** [comment]
(One of which was to me, btw. :-)

**Comment by whit537** [comment]
Accidentally sent before I was finished (how do I turn on that "undo" feature in Gmail?), but thankfully only to @webmaven:

>Greetings!
>
You are one of four users to whom Gratipay accidentally made a payout last week.
>
We're in the midst of [a major transition](https://medium.com/gratipay-blog/gratipocalypse-42fd0ec0d9e8), during which we're changing our terms of service for receiving money on Gratipay. Our goal is to be able to bring you on under our new terms and send you your money, but we're not quite ready to do that yet, so unfortunately we've had to reverse last week's payout. :-(
>
chad

**Comment by whit537** [comment]
From: support@gratipay.com
To: support@gratipay.com
Bcc: [4]
Subject: erroneous payout

>Greetings!
>
You are receiving this message because you are one of four users to whom Gratipay made an erroneous payout last week.
>
We're in the midst of [a major transition](https://medium.com/gratipay-blog/gratipocalypse-42fd0ec0d9e8), during which we're changing our terms of service for receiving money on Gratipay. Our goal is to be able to bring you on under our new terms and send you your money, but we're not quite ready to do that yet, so unfortunately we've had to issue a reversal for last week's payout. Sorry. :-(
>
For more details, please see [this GitHub ticket](https://github.com/gratipay/gratipay.com/issues/3453).
>
I will follow up when we're ready to announce the new Gratipay terms.

**Comment by whit537** [comment]
Leaving open until the status of the payouts/reversals solidifies.

**Comment by webmaven** [comment]
@whit537 Let me know if you need any data on the transaction from my end.

**Comment by whit537** [comment]
Thanks @webmaven. It will be interesting to see how the transaction appears for you and I, because that will give us an idea of how it appears to the other two.

**Comment by webmaven** [comment]
Right now it appears as a credit to the account on 5/15.

**Comment by webmaven** [comment]
BTW, @whit537:
> how do I turn on that "undo" feature in Gmail?

https://support.google.com/mail/answer/1284885?hl=en

**Comment by whit537** [comment]
@webmaven I don't see a Labs tab:

![screen shot 2015-05-18 at 2 00 37 pm](https://cloud.githubusercontent.com/assets/134455/7686774/4ddfa72c-fd66-11e4-80c7-9d5b9014e95a.png)

I checked in Google Apps, and Labs is enabled for Gmail. Hmm ...

**Comment by whit537** [comment]
Maybe because I'm using support@gratipay.com as a [delegated account](https://support.google.com/mail/answer/138350?hl=en)?

**Comment by webmaven** [comment]
@whit537, that's as far as my knowledge goes, I'm afraid.

**Comment by kytrinyx** [comment]
I am one of the four users. Where does the money that got paid out and then reversed go to? My assumption would be that it would go back to my gratipay account, but my gratipay account shows a balance of $0.

**Comment by whit537** [comment]
@kytrinyx I expect it'll require a manual step to update balances in Gratipay. I hope to get to this ticket and bring it in for a landing on Wednesday, if someone else doesn't get to it sooner ...

**Comment by kytrinyx** [comment]
Ok, understood.

**Comment by heidigardner** [comment]
Apparently I got caught in the payout storm. 
My Gratipay account is still reading as if it did not get reversed as well. 
Let me know what happens with this. 

Ironically, the payout happened because I have been catching up here and updating my settings-- so when I added my bank account. BOOM. lol

**Comment by whit537** [comment]
Looking into this now ...

**Comment by whit537** [comment]
> Upon reviewing history for the six users, I would actually expect two more of these payouts to fail (they've been failing in the recent past).

And, indeed, these two more did fail.

> That leaves four accidental successful payouts.

And we're all on this ticket: @webmaven @kytrinyx @heidigardner @whit537. :-)

**Comment by whit537** [comment]
So did the reversals succeed?

**Comment by whit537** [comment]
Yes, per both user confirmation and the Balanced dashboard. Here's what the reversal looks like in my personal bank account:

![screen shot 2015-05-27 at 2 10 37 pm](https://cloud.githubusercontent.com/assets/134455/7843836/76d01fc0-047a-11e5-9026-dad639ebe9c7.png)
![screen shot 2015-05-27 at 2 10 57 pm](https://cloud.githubusercontent.com/assets/134455/7843835/72fe32ba-047a-11e5-9d98-c3108644b239.png)

**Comment by whit537** [comment]
So the next step is to record the reversals in Gratipay.

**Comment by heidigardner** [comment]
$$ are showing back in the Gratipay account. 
Good work, @whit537

**Comment by whit537** [comment]
Done. Check your history page, eh @webmaven @kytrinyx @heidigardner? Balance should now be correct. Aaaaaaaand I believe that closes out this issue! See you on #3481, etc. ...

**Comment by whit537** [comment]
@heidigardner Nice! Thanks for the confirmation. :)

**Comment by kytrinyx** [comment]
It's all sorted in my history page. Thanks!

**Comment by whit537** [comment]
@kytrinyx Huzzah! Just in time to get you paid out properly today. :P

**Comment by kytrinyx** [comment]
:heart:

**Comment by webmaven** [comment]
I see the reversal as well.

**Comment by whit537** [comment]
@webmaven Cool. Maybe once we bring back payroll (https://github.com/gratipay/gratipay.com/issues/3433) we can finally add you to Gratipay and get you paid out.
