### ISSUE TITLE
add `payments` to history pages

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3455]
@ehmatthes at https://github.com/gratipay/gratipay.com/issues/3446#issuecomment-103163666:

> I made an account for introtopython.org last week, and it was one of the teams that should have been included in last week's payday. But my balance is low enough that I didn't get a payout.
>
How will I know if my accounts are set up correctly, ie if my team was included in last week's payday? I don't know how to view my team account, or if it's even possible to view a profile page for that team yet. introtopython is not included in my teams page. My individual history doesn't show anything after payday 152.

#### Notify: 

- [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2233
- [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2358
- [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2405
- [ ]  https://gratipay.freshdesk.com/helpdesk/tickets/2514
- [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2468
- [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2354
- [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2540

**Comment by whit537** [comment]
+1 https://gratipay.freshdesk.com/helpdesk/tickets/2233

> [I]t looks like my (only) "2.0" subscription didn't work today: I can see only card charge in my Account Statement.
>
Speaking of which, it looks like I've managed to get negative balance during the period when there was no money on my card. Is it expected?

**Comment by whit537** [comment]
+1 from @thomasdavis at https://github.com/gratipay/gratipay.com/issues/3556#issue-88236989:

> But when I look at the history tab, it says it hasn't received anything since April.
>
> Have payments commenced since the switch?

**Comment by whit537** [comment]
+1 https://gratipay.freshdesk.com/helpdesk/tickets/2358

**Comment by whit537** [comment]
+1 from @noffle at https://github.com/gratipay/gratipay.com/issues/3572:

>According to my history, my $2.10 / week payments stopped going through as of April 30 2015. My credit card information looks up to date.

**Comment by mattbk** [comment]
+1 from me too, I don't see anything coming in on the History page, hence the confusion in my comment at https://github.com/gratipay/inside.gratipay.com/issues/234#issuecomment-115390821.

**Comment by mattbk** [comment]
+1 from Ticket #2450 on Freshdesk.

**Comment by mattbk** [comment]
[ ] https://gratipay.freshdesk.com/helpdesk/tickets/2514

**Comment by whit537** [comment]
@mattbk Can you add additional people to notify to the ticket description instead of appending new comments? That way they're all in one place.

**Comment by mattbk** [comment]
I don't think I have permissions for that, is there supposed to be an edit button?

**Comment by mattbk** [comment]
Based on the number of support tickets I've seen, can we confirm that anyone has gotten a weekly payout recently?

Actually, I may be confused.  This ticket is about receiving payments (and not about being charged), correct?

If payments are not being received, then one or more of the following are true?
- people subscribed to the team not receiving payments have unsubscribed by choice (including turning off credit card, closed account, etc.)
- people subscribed to the team not receiving payments have been lost in the transition of individuals to teams
- some other problem relating to transition to 2.0

**Comment by whit537** [comment]
Short answer: yes, Gratipay itself has received payouts.

**Comment by whit537** [comment]
This ticket is about modifying the history page to display information from the new `payments` table instead of from the old table, `transfers`, that it replaced.

**Comment by mattbk** [comment]
Should that history page be part of the team profile or the individual account?

**Comment by whit537** [comment]
@mattbk This ticket is about the individual's history page, which we still want since individuals are the ones we're charging via credit card and crediting on PayPal. I like the idea of a team history page as well; reticketed as #3612.

**Comment by whit537** [comment]
@mattbk I deployed #3616, so this ticket should be resolved. Can you confirm, and then follow up with the support requests linked in the description?

**Comment by mattbk** [comment]
It's so beautiful!  Yes, will follow up with support requests.

**Comment by whit537** [comment]
!m @mattbk

**Comment by whit537** [comment]
I just got https://github.com/gratipay/inside.gratipay.com/issues/249 over the hump.

**Comment by whit537** [comment]
Sorry, wrong thread. :)
