### ISSUE TITLE
bring back account closing

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3461]
Turned off in #3454, in order to avoid leaking payments under our old Gratipay 1.0 terms of service, about which there were some [legal concerns](https://medium.com/gratipay-blog/gratipocalypse-42fd0ec0d9e8).

##### Notify

 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2082
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2147
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2161
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2162
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2166
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2330
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2352
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2090
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2414
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2579
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2597

**Comment by rohitpaulk** [comment]
Have we decided what to do with the balances?

**Comment by whit537** [comment]
We're going to give people 90 days to migrate to a team, in which case we'll release their balance to them. After 90 days we'll try to refund the money back upstream for any remaining accounts (though we'll have to think about the interaction with other parts of #1383). Balanced's refund API is on until Oct 9, 142 days.

**Comment by whit537** [comment]
Probably should implement refunding balances back to supporters as a new disbursement strategy (cf. [FD2103](https://gratipay.freshdesk.com/helpdesk/tickets/2103)).

**Comment by whit537** [comment]
+1 https://gratipay.freshdesk.com/helpdesk/tickets/2161

**Comment by whit537** [comment]
+1 https://gratipay.freshdesk.com/helpdesk/tickets/2162

**Comment by whit537** [comment]
+1 https://gratipay.freshdesk.com/helpdesk/tickets/2166

**Comment by whit537** [comment]
Support requests blocking on this:

https://gratipay.freshdesk.com/helpdesk/tickets/2082
https://gratipay.freshdesk.com/helpdesk/tickets/2162

**Comment by whit537** [comment]
Consolidated relevant support requests in the ticket description.

**Comment by whit537** [comment]
Probably should also implement releasing Gratipay 1.0 balances to manually approved users as a new disbursement strategy: #3481.

**Comment by whit537** [comment]
Well, #3481 doesn't need to be tightly tied to account closing.

**Comment by whit537** [comment]
+1 @ribasushi on #3587.
