### ISSUE TITLE
release Gratipay 1.0 balances, case-by-case

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3481]
Having announced [Gratipay 2.0](https://medium.com/gratipay-blog/gratipay-2-0-2453d3c53077), we're hearing from some folks that, understandably, just want to cash out and close their Gratipay account. Today our options for them are:

 1. Apply for a team.
 2. Wait until August when we refund all remaining Gratipay 1.0 balances.

Neither of these are awesome. The first is dumb because it's just jumping through hoops. The second is dumb because we're making them wait a long time, and we're forcing them to refund their balance.  Refunding balances is better then letting balances sit in limbo, but obviously less desirable than paying them out.

~~Can we add a disbursement method to account closing that involves accepting a short agreement that the funds were received legitimately?~~ I've made a private ticket to discuss this with @copiesofcopies.

Let's disassociate this from account closing. Per https://github.com/gratipay/gratipay.com/issues/3481#issuecomment-106013128, we can manually review accounts and pay them out if they had been used for a product or service. That will free people up to close their account if they want to, but we don't need to strictly tie this to that.

##### Notify

 - [x] https://gratipay.freshdesk.com/helpdesk/tickets/2103
 - [x] https://gratipay.freshdesk.com/helpdesk/tickets/2147
 - [x] https://gratipay.freshdesk.com/helpdesk/tickets/2161
 - [x] https://gratipay.freshdesk.com/helpdesk/tickets/2187
 - [x] https://gratipay.freshdesk.com/helpdesk/tickets/2232
 - [x] https://github.com/gratipay/inside.gratipay.com/issues/210#issuecomment-106471300
 - [x] https://gratipay.freshdesk.com/helpdesk/tickets/2090
 - [x] https://gratipay.freshdesk.com/helpdesk/tickets/2315

**Comment by whit537** [comment]
If we *can't* figure this out, then I'm not sure how we're able to pay out balances received under Gratipay 1.0 even to people who migrate their tips to Gratipay 2.0 Teams.

**Comment by kytrinyx** [comment]
For (1) does this mean that one would be allowed to donate what is on an individual account to the new team account?

**Comment by whit537** [comment]
@kytrinyx Team accounts don't carry a balance, only ~user accounts do. See https://github.com/gratipay/gratipay.com/issues/3399#issuecomment-101470445 for a rough sketch (bottom of the comment). Sorry it's confusing, we need some better diagrams. :/

**Comment by whit537** [comment]
Teams have 1 owner and 0+ members.

Owners and members are users.

Users pay teams.

Teams distribute to members, with whatever is left going to the owner.

**Comment by kytrinyx** [comment]
I am sorry, I still don't understand how this works. I have a team account and an individual account. They both carry a balance. Or at least, I have received donations to both, and was patiently letting money accumulate in them, and when I wanted to withdraw the funds, I was unable to.

**Comment by whit537** [comment]
> I have a team account and an individual account.

Okay, sorry, I'm probably confused ... can you link to the two accounts?

**Comment by kytrinyx** [comment]
https://gratipay.com/~kytrinyx/
https://gratipay.com/~exercism_io/

The exercism_io account carries a balance of nearly $35 dollars. The kytrinyx account had been accumulating a balance for 2 years. Last week I attempted to withdraw it. The profile page says that my balance is 0. The history page says that the withdrawal succeeded, but I received email personally that said that the withdrawal has been canceled. So since I have not received that money, then the individual account should carry a balance.

**Comment by whit537** [comment]
@kytrinyx Okay, gotcha. The existence of the [`~exercism_io`](https://gratipay.com/~exercism_io/) account is what I was missing, sorry. Yes, your `~kytrinyx` account is affected by #3453, sorry. :-( Once we finish cleaning up #3453, your `~kytrinyx` history page will show a balance again.

#### Users vs. Teams

In Gratipay 2.0 terms, both `~kytrinyx` and `~exercism_io` are **user accounts**, and are distinct from Gratipay **teams**. Here's an explanation of the differences:

 - **User Accounts**
  - can be used to sign in
  - can add money (via credit card, etc.)
  - can withdraw money (via bank account, etc.)
  - can carry a balance, in some limited circumstances
  - can pay Teams
  - can receive payroll from Teams
  - [i.e.,] can be an owner or member of a Team
  - *cannot* receive payments directly from other Users
 - **Teams**
  - can receive payments from Users
  - can distribute payroll to Users
  - *cannot* be used to sign in
  - *cannot* add or withdraw funds
  - *cannot* carry a balance

I'm not saying this ontology is perfect, but it's the reality today, and I don't think it's *terrible* (especially considering that we [came up with it](https://github.com/gratipay/gratipay.com/issues/3399#issuecomment-101000562) under [duress](https://medium.com/gratipay-blog/gratipocalypse-42fd0ec0d9e8)). Hopefully in the future we can at least find better ways to communicate it, and if we really need to revise the ontology again, we can.


#### Closing Accounts

> They both carry a balance.

Both the `~kytrinyx` and `~exercism_io` user accounts carry a balance, yes. I believe your goal is to withdraw the balance from both accounts, and close both of them. Yes?

Once we land #3433 and #3461, here's how you will be able to withdraw the two balances and close the two user accounts, via an intermediary `Exercism` "team" (in the Gratipay 2.0 meaning of the term):

 1. Sign in to Gratipay as the `~exercism_io` user (i.e., using your `exercism_io` Twitter account).
 1. [Apply for a new team](https://gratipay.com/new) for Exercism. Since you're signed in as `~exercism_io`, `~exercism_io` will be the user account that is the "owner" of the `Exercism` "team."
 1. Add the `~kytrinyx` user as a member of the payroll for the `Exercism` team (pending #3433).
 1. Close the `~kytrinyx` user account (pending #3461). Because `~kytrinyx` is now a "member" of a "team" (namely, `Exercism`), we will allow you to withdraw your balance during the account closing process.
 1. Close the `~exercism_io` user account (pending #3461). Because `~exercism_io` is now an "owner" of a "team" (namely, `Exercism`), we will allow you to withdraw your balance during the account closing process.


#### Conclusion

That's the best I have to offer you today. This ticket is about finding a better option for people in your situation, but honestly I'm not sure there is one, since we need to vet accounts somehow before we pay them out and we've already got the teams infrastructure in place for doing that.

**Comment by whit537** [comment]
Sent on [FD3147](https://gratipay.freshdesk.com/helpdesk/tickets/2147):

>> I honestly just want to clear the account and close it, is there any **easy way** of doing this?
>
No. I'm sorry. :-(
>
The problem is that we've stopped processing payments under our old terms of service (and we've communicated as much to financial regulators). Because historically we've allowed you to pool money on Gratipay, the money currently in your Gratipay balance is in a half-processed state (btw, we no longer allow pooling on Gratipay 2.0). We certainly don't want to keep this money in limbo, so we have two basic options for resolving the half-processed state this money is in:
>
 1. **Refund it** to your supporters. This amounts to *backing out* a set of half-processed transactions.
 2. **Release it** to you. This amounts to *completing* a set of half-processed transactions.
>
For [legal reasons](https://github.com/gratipay/inside.gratipay.com/issues/201), we now need you to explicitly agree that the transactions we're processing on your behalf are payments for goods and services. If you're able to agree to this, then we're comfortable considering the half-processed past transactions represented by your current Gratipay balance to come under the same agreement, and to release the funds to you. Our [new team-centric terms of service](https://gratipay.com/about/terms) are the agreement we have in place for this.
>
We're looking at the possibility of a less hoop-jumpy option for people in your situation; here is [the public side of that conversation](https://github.com/gratipay/gratipay.com/issues/3481). If you *can't* agree to this (or otherwise don't take any action), then the worst-case scenario is that we'll refund your balance back to your supporters. We'll be doing that for all remaining Gratipay 1.0 balances in August.
>
Sorry I don't have an easier answer for you on this, []. :-( Hopefully this at least explains where we're coming from. Happy to answer any further questions ...

**Comment by kytrinyx** [comment]
Thanks so much for clarifying. I don't need a better option than this. Yes, there are hoops, but I understand that the whole situation is difficult.

I did not understand the distinction between the exercism.io user account which is listed as a "team" in the profile page, and an actual team.

It was also unclear to me previously that users could withdraw money, provided that this was a payout via a team. This now makes sense, as well.

**Comment by whit537** [comment]
Good news! We can cash people out who "just want out" on a case-by-case basis. We just need to manually verify that they were using their Gratipay profile to accept payments for a legitimate product or service. Let's implement that as an additional final disbursement option for account closing (#3461).

**Comment by whit537** [comment]
> Thanks so much for clarifying. I don't need a better option than this.

@kytrinyx Cool, thank you. Since you've already started down the "make a Team and then close it" path let's stay on that track.

**Comment by kytrinyx** [comment]
OK, cool. I'll just wait for confirmation that the team has been verified, then I'll go through the next steps.

**Comment by kytrinyx** [comment]
@whit537 I couldn't figure out how to add members to the payroll of a team. Would you point me in the right direction, please?

**Comment by whit537** [comment]
@kytrinyx Sorry, we're trying to bring that back for today but it's not quite landed yet: https://github.com/gratipay/gratipay.com/issues/3433. :-(

**Comment by whit537** [comment]
I'm thinking we should implement this with an admin-only form off the history page similar to record-an-exchange, that does the payout and records the exchange. It should require a link to a support or GitHub ticket as documentation, which it puts in the exchange note. Hmmm ... for bank accounts we can start a payout synchronously, but what about for PayPal?

**Comment by kytrinyx** [comment]
@whit537 Ah, I missed that. I'll check over the next few days to see if that's in place.

I could try adding a bank account for the ~exercism_io user, but I am not sure I could verify the identity in any way.

**Comment by kytrinyx** [comment]
@whit537 What's the status on being able to add members to teams? If this is going to be a while, could I just get the 1.0 balance closed out?

**Comment by whit537** [comment]
@kytrinyx et al. We made the code changes to support this in #3535 and #3542. I'm going through and whitelisting everyone on this ticket now. If you have a bank or PayPal attached you should see a payout today, or the next payment cycle after you add one on [your Gratipay settings page](https://gratipay.com/about/me/settings/). I'm also following up in email ...

**Comment by whit537** [comment]
Though actually, @kytrinyx, we've already paid you out since you went through the team migration process. I'll follow up with you again when #3461 is done ...

**Comment by whit537** [comment]
Yessssssss. Notified everyone listed in the description. Ready to handle new cases as they arise.

**Comment by kytrinyx** [comment]
@whit537 Yes, I go the payout for the ~kytrinyx account, but not for the ~exercism_io one.

**Comment by whit537** [comment]
@kytrinyx Okay, I've cleared ~exercism_io for payout next week.

**Comment by kytrinyx** [comment]
Thanks!

**Comment by bearbin** [comment]
Could all the money that has accumulated in my account (gratipay.com/~bearbin) be withdrawn to my paypal? It was all to do with the MCServer (now Cuberite) project.

**Comment by whit537** [comment]
@bearbin All cleared, @bearbin. Watch for that payout this Thursday! :-)
