### ISSUE TITLE
expose team info for editing

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3487]
I'd like to take a hands-on approach to team profiles. I think we should provide copy-editing and feedback as a service to teams. We want high quality team profiles that answer the questions that individuals will have.

**Comment by ehmatthes** [comment]
> I think we should provide copy-editing and feedback as a service to teams.

Are you planning to edit team profiles directly, or simply offer feedback and suggestions?

**Comment by whit537** [comment]
@ehmatthes I don't think it'd be right for Gratipay to directly edit team profiles without consent from the team owners. I was thinking more in terms of a collaboration: "How we change it to read [this]? What do you mean by [that]?" How does that strike you?

My goal is to have successful teams! :-)

I'm put in mind of #1273.

**Comment by ehmatthes** [comment]
> I was thinking more in terms of a collaboration: "How we change it to read [this]? What do you mean by [that]?" How does that strike you?

This sounds great. I think this would be helpful to many people.

**Comment by whit537** [comment]
Closing in favor of #3545.
