### ISSUE TITLE
Zipmark for ACH?

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3491]
We're pretty far along with Citizens (#3366), but it's always good to have options on the table. I learned about https://zipmark.com/deposit last night from [Andrew Somerville](https://hireanesquire.com/).

**Comment by whit537** [comment]
Called and left a message for the salesperson that Andrew gave me contact info for.

**Comment by whit537** [comment]
I filled out the contact form on their website.

**Comment by whit537** [comment]
Had a phone call. Follow-up scheduled for next Monday. Asked to have someone there that can talk to us about underwriting.

**Comment by whit537** [comment]
They collect name, SSN, mailing address, email address. Sounds like an iframe workflow.

**Comment by whit537** [comment]
Called back to fast-track, because Balanced deletes information a week from tomorrow. Call set for 2:15 (~45 minutes), to include their founder (@jakehow) as well as their bizdev person.

**Comment by whit537** [comment]
From a slide deck:

> Transparent, Tiered Pricing
>
| volume | $/ea |
|-----------|--------|
| 0-500 | 0.50 |
| 501-2,500 | 0.35 |
| 2,500+ | 0.25 |
>
The monthly minimum of $250 is applied to the ﬁrst 500 transactions of the month, and
transactions 501+ are billed at the rates noted above.

![screen shot 2015-06-04 at 1 37 29 pm](https://cloud.githubusercontent.com/assets/134455/7990418/e6e7c6ec-0abe-11e5-9753-8936e8170f0e.png)

**Comment by whit537** [comment]
Docs (login required, and there's no open registration):

https://dev.zipmark.com/docs/disbursement/creating_a_disbursement
https://dev.zipmark.com/docs/disbursement/creating_a_disbursement__no_vendor_relationship
https://dev.zipmark.com/docs/disbursement/listing_disbursements
https://dev.zipmark.com/docs/disbursement/viewing_a_disbursement

**Comment by whit537** [comment]
Just got off the horn. Sounds like this might actually work. !m @catskul

**Comment by whit537** [comment]
Honestly, though, it's a little unsettling that they have *no* underwriting process whatsoever. After dealing with Citizens (#3366), this feels like a pendulum swing too far in the other direction. :-(

**Comment by jakehow** [comment]
Hey guys. Let me know if you have any questions.

Re: underwriting

I assume gratipay.com is the merchant of record for this app.  If you guys go to production you will go through our underwriting process.

Our transactions are eventually routed to our partner banks so we abide by the same restrictions you might see if you go direct we are just much better at helping you through the process and automating the parts that can be.

**Comment by whit537** [comment]
Thanks @jakehow. We just got rejected trying to go direct (#3366), so it looks like you're our best bet. :)

I've got docs in email from your team, will be following up shortly ...

**Comment by jakehow** [comment]
@whit537 sounds good feel free to send us your emails to developers@zipmark.com for invites to our team slack if you need help.

**Comment by jakehow** [comment]
@whit537 also, make sure you are using the newest docs... http://docs.zipmark.com

If you don't have the login ping us on the same email.

**Comment by whit537** [comment]
Cool, just emailed re: @rohitpaulk and myself.

**Comment by whit537** [comment]
@jakehow Yeah, I have the login. I'll share it with @rohitpaulk. When will that be out of beta?

**Comment by whit537** [comment]
New API: http://docs.zipmark.com/api#make-a-deposit.

**Comment by jakehow** [comment]
@whit537 its in production we just have not finalized docs yet.

**Comment by whit537** [comment]
Okay, cool.

**Comment by whit537** [comment]
@jakehow Looks like [webhooks](http://docs.zipmark.com/api#webhook-notifications) aren't deployed yet? How are failures currently handled?

**Comment by whit537** [comment]
Note for Gratipay team: Zipmark has a $250/minimum, which at 50¢ per transaction is 500 transactions. We're not going to meet that for a while, which means this is going to be really expensive for us until we do. We were *almost* up to that level before the Gratipocalypse, and now we're back down to about 25 per month.

@jakehow Any chance you can cut us a break on the minimum for 3 months while we rebuild our userbase? See [Gratipocalypse](https://medium.com/gratipay-blog/gratipocalypse-42fd0ec0d9e8) and [Gratipay 2.0](https://medium.com/gratipay-blog/gratipay-2-0-2453d3c53077) for backstory. I'm happy to explain more if need be ...

**Comment by whit537** [comment]
Re: Webhooks ...

> I think that warning may be a little overzealous just because we may adjust the attributes still
> I’m looking into how webhooks currently operate as compared to the docs, I’ll let you know when I’m done.

**Comment by whit537** [comment]
Docs sent to Zipmark.

**Comment by whit537** [comment]
>The webhooks endpoint will work per the docs.  The issue is that none of the available resources on the docs are currently enabled to send notifications.   For example, you can `POST` to the webhooks endpoint to create a webhook that will receive notifications, but no events - like say creating a deposit - will not send a notification to the URL of that webhook.  We will be working on that and will let you know when we are finished. This is the last piece to get turned on in production and we will keep you posted on its status.  Are there any specific needs, concerns, or requirements you have for your webhooks that you want us to know about?

Me: 

> Thanks, []. The one webhook we're currently using at Balanced is ACH credit failures. How are those currently handled in the absence of webhooks?

**Comment by whit537** [comment]
> Docs sent to Zipmark.

Okay, with that, I'm closing this out! Migration reticketed as #3522, and modifying payday as #3523.

!m *

:dancer:

**Comment by catskul** [comment]
Awesome!

**Comment by whit537** [comment]
From: Zipmark

> Let's schedule a call tomorrow to go over your business model. We want to make sure that your new model is in compliance with regulations - a measure you seem to have taken. On the call will be Jake, whom you've been communicating with. Does 11am work for you?
>
Also, we will need an updated bank letter that is addressed to Zipmark. 

To: Zipmark

> Hah! I knew it. :)
>
Yes, happy to discuss. I can make 11am tomorrow work, yes. As background for our call, here is [Gratipay's risk management program](http://inside.gratipay.com/howto/manage-risk).
>
I will get you the new bank letter, either tomorrow or Monday.

lol

**Comment by whit537** [comment]
From: Zipmark

> Thanks for being so transparent. Just crossing our Ts and dotting our Is. 
>
Talk to you tomorrow.

**Comment by whit537** [comment]
To: Zipmark

> Thanks for the call. I really appreciate your willingness to help Gratipay clear the bar on BSA/AML compliance. Here is our [current review procedure](http://inside.gratipay.com/howto/review-accounts). I'll watch for a list of vendors from you and I'll come back to you with questions as we upgrade our CIP/CDD procedures this next week or so. Our target at this point would be to process on Zipmark on June 18, or June 25 at the latest.

**Comment by whit537** [comment]
> I'll watch for a list of vendors from you and I'll come back to you with questions as we upgrade our CIP/CDD procedures this next week or so.

The list of vendors is included in a sales slide deck I received in private email. Here's the content (linkified) from the two relevant slides, with the original slides screen-capped below.

> ### Integrations
>
Zipmark integrates with leading verification services, so we can validate customer information on your behalf with no additional work by your team.
>
* [Plaid](https://www.plaid.com/)
* [Clearbit](https://clearbit.com/)
* [MicroBilt](http://www.microbilt.com/)
* [BlockScore](https://blockscore.com/)
* [Jumio](https://www.jumio.com/)
>
### Other Integrations
 >
Some of these are proposed integrations and if there’s a need we will work with you to get them implemented.
>
#### Account Authentication
>
* [Plaid](https://www.plaid.com/)
* [Intuit ](https://developer.intuit.com/docs/0020_customeraccountdata/0005_service_features)
* [Yodlee](http://www.yodlee.com/)
* [MicroBilt](http://www.microbilt.com/)
* [Accuity](http://www.accuity.com/)
>
#### Fraud Scoring
>
* [SiftScience](https://siftscience.com/)
* [Signifyd](https://www.signifyd.com/)
* [Feedzai](https://www.feedzai.com/)
* [Early Warning](http://www.earlywarning.com/index.html)
>
#### Device Verification
>
* [ThreatMetrix](http://www.threatmetrix.com/)
* [Maxmind minFraud](https://www.maxmind.com/en/minfraud-services)
>
#### Business & Personal Data 
>
* [SmartyStreets](https://smartystreets.com/)
* [iovation](https://www.iovation.com/)
* [Trusteer](http://www-01.ibm.com/software/security/trusteer/)
>
#### Verification
>
* [Neustar](https://www.neustar.biz/)
* [Clearbit](https://clearbit.com/)
* [kickbox.io](http://kickbox.io/)
* [FullContact](https://www.fullcontact.com/)
* [41st Parameter](http://www.the41.com/)
>
#### Identity Verification
>
* [Blockscore]()https://blockscore.com/
* [EveryoneAPI](https://www.everyoneapi.com/)
* [Jumio](http://jumio.com/)
* [MicroBilt](http://www.microbilt.com/)
* [IDology](https://www.idology.com/)
>
#### Two Factor Authentication
>
* [Authy](https://www.authy.com/)
* [Twilio](https://www.twilio.com/)
* [VoiceVault](http://voicevault.com/)

![Integrations](https://cloud.githubusercontent.com/assets/134455/8045083/eb4e472c-0dfe-11e5-92ac-1033a1474743.png)

![Other Integrations](https://cloud.githubusercontent.com/assets/134455/8045089/f02b4e5c-0dfe-11e5-8255-4fcf2a02f107.png)

**Comment by whit537** [comment]
To: Zipmark

> I've moved the list to a private repo, and updated [this comment](https://github.com/gratipay/gratipay.com/issues/3491#issuecomment-110141495).
>
Note that we won't ultimately be able to keep the integrations we're using under wraps, for two reasons. First, our code is open source, so whatever third-party vendor(s) we end up using will show up in [our public source code repo on GitHub](https://github.com/gratipay/gratipay.com).
>
Second, and more importantly, I'll need to publicly discuss and decide together with the Gratipay community what vendor(s) we're in fact going to use for AML. Ease of integration with Zipmark would naturally be one of the criteria, but if you're willing to work with whomever we pick, then I guess we can simply pick based on other criteria.

**Comment by whit537** [comment]
From: Zipmark

> Thanks for doing that. 
>
We'll be ready to release that information soon so what you're doing now is fine by privatizing the repo.

**Comment by whit537** [comment]
From: Zipmark

>How is everything coming a long on your end? Do you need anything from me?
>
I'm out of the office, but I'm available by email and my office line directs to my cell. 
>
Talk to you soon. 

To: Zipmark

> Thanks for reaching out, []. I was able to connect with [] in Slack the other day, and we have [an initial understanding](https://github.com/gratipay/gratipay.com/issues/3522#issuecomment-110152812) of the work Gratipay needs to do to clear the compliance bar with Zipmark. If you can believe it, we've got a couple even hotter fires to put out this week, after which AML and Zipmark will become our top priorities.
>
The good news is that we have [an extra week](https://github.com/gratipay/gratipay.com/issues/3377#issuecomment-109019305) with ACH on Balanced (we found out last week). I expect we'll need it in order to achieve our compliance goals before migrating, so our current target is to run ACH on Zipmark on June 25.
>
Here are [the details of our scheduling and prioritization](https://github.com/gratipay/inside.gratipay.com/issues/244). Let's touch base again early next week.
>
Thanks! :)

**Comment by whit537** [comment]
From: Zipmark

> Sounds good to me. I'll reach out to you on Monday or Tuesday and we'll work to get you processing by June 25th.

**Comment by whit537** [comment]
From: Zipmark

> Hope you had a great weekend. I briefly skimmed over the links you sent in your previous email. Looks like we need to hammer down an AML solution in order to begin implementation. How have discussions gone on your end? Do we need to schedule another call help facilitate this?

To: Zipmark

>Thanks for checking in. I spent the morning [reviewing vendors](https://github.com/gratipay/gratipay.com/issues/2449#issuecomment-107104800) and starting to wrap my head around this project. Comments/questions:
>
I believe we're primarily looking at four pieces to this puzzle:
>
1. individual identity verification
- business identity verification
- sanction screening
- suspicious activity monitoring
>
Does that match your expectations?
>
Our ideal at this point will be for Gratipay to implement a program with global reach, even though with Zipmark we'll just be doing ACH for U.S. receivers.
>
Does Zipmark offer IAT?
>
What do you understand Gratipay's requirements to be in terms of suspicious activity monitoring and reporting?
>
Here are the vendors we're [currently evaluating](https://github.com/gratipay/gratipay.com/issues/2449#issuecomment-112179596) for individual IDV and sanction screening:
>
1. [Trulioo](https://www.trulioo.com/)
* [IDchecker](http://www.idchecker.com/strongid/)
* [Veratad IDMatch](http://veratad.com/solutions/identity-verification/)
* [Integrity](http://integrity.aristotle.com/products/)
* [BlockScore](https://blockscore.com/)
* [Jumio](https://www.jumio.com/)
* [Accuity](http://www.accuity.com/)
- [IDV Check](http://idvcheck.com/)
>
Any recommendations or red flags, looking at that list?
>
Here's where we're looking at [business IDV](https://github.com/gratipay/gratipay.com/issues/3557). How does business IDV impact our Zipmark integration?

**Comment by whit537** [comment]
To: Zipmark

> Our best option may be to scrap the Balanced migration data and sign up all users from scratch (we only have 16 users that we've already onboarded on the new Gratipay w/ bank payouts). Can we schedule a call or chat to discuss what that would look like?
>
How about tomorrow (Thursday) at 11am or 2pm?

h/t @kaguillera @dmk246

**Comment by whit537** [comment]
Had a call with Zipmark. It turns out that they need to perform identity checks on their side. It's not enough for us to perform the identity checks on our side (#2449, #3557). Any information collection we do on our side would then simply pre-load the workflow in their iframe, and they would hit identity services again. They're going to put together a pricing package for us.

**Comment by webmaven** [comment]
@whit537:
>  It turns out that they need to perform identity checks on their side. It's not enough for us to perform the identity checks on our side 

Would that mean it would be possible to offload identity checks onto ZipMark entirely?

**Comment by whit537** [comment]
To: Zipmark

> We've decided not to move forward with Zipmark for Gratipay, due to time constraints, the complexity of the task, and the low volumes we're operating at right now. I appreciate your willingness to try to make it happen for us, and especially your feedback on our AML program. Thank you.
>
You have an export file from Balanced with our users' information. Could you please see to it that that information is securely deleted? Thanks.

**Comment by whit537** [comment]
> Would that mean it would be possible to offload identity checks onto ZipMark entirely?

Not in a simple way, as I understand it.

I've made the call to pull out here.

**Comment by whit537** [comment]
From: Zipmark

> Thank you for the update. I'd like to talk to you about your decision soon so I can get a better understanding of what we can do to help you out. Let's stay in touch because Jake and I both believe that your volume will return to the level that which you had prior to the Balanced shut down. 
>
I'm out of the office today (sick), but I will make sure that the information we received is securely disposed of when I'm back in the office.

**Comment by whit537** [comment]
Received in private email:

_Subject:_ Intro: Zipmark and Gratipay

> Hi Chad,
>
I recently came across Gratipay and I wanted to reach out.
>
At Zipmark, we process payments for a wide range of companies, from on-demand service marketplaces to insurance companies, and to everything in-between. We provide a completely white-labeled solution, which helps our clients replace checks, offers flexible escrow management and enables faster clearing times for ACH transactions.
>
As a result, we have a lot of experience solving a wide range of payment issues. If your team is experiencing any pain points around its current process, I would be more than happy to set up a call. You can also schedule some time to talk by clicking the "My Calendar" button in my signature line.
>
Best,
>
[]

------------

Thanks Simona. No pain points right now, but I will keep you in mind.

P.S. Here's a record of our history with ZipMark:

https://github.com/gratipay/gratipay.com/issues/3491
