### ISSUE TITLE
build a vault

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3504]
We are going to start storing national identification numbers (https://github.com/gratipay/gratipay.com/issues/3289#issuecomment-107100341) as well as bank account numbers (#3377 downstream of #3366). We need a vault separate from our main application and database that is more highly secure. We should use the PCI DSS 3.0 standard to self-assess the security of our application (https://github.com/gratipay/inside.gratipay.com/issues/214). This ticket is about building a new vault component of our architecture.

**Comment by whit537** [comment]
I think we should host directly on AWS, since they clearly offer a PCI compliant environment, whereas Heroku doesn't advertise as much.


http://aws.amazon.com/compliance/pci-dss-level-1-faqs/

**Comment by whit537** [comment]
I'm envisioning a very simple key/value store, an expansion of https://github.com/whit537/whit537.org/blob/5957285ff970739e701ca46f493bfdd63a98aede/vault.py to put it on the network. I suppose the thing to do would be to use HTTP so we can post into it from javascript. We don't want to transmit sensitive data through the main web app at all.

**Comment by whit537** [comment]
Let's do some poking around ...

https://hashicorp.com/blog/vault.html

What else?

**Comment by whit537** [comment]
http://tokenator.org/

**Comment by whit537** [comment]
https://github.com/SimplyTapp/Tokenator

**Comment by whit537** [comment]
> ##### Data Encryption
>
In addition to being able to store secrets, Vault can be used to encrypt/decrypt data that is stored elsewhere. The primary use of this is to allow applications to encrypt their data while still storing it in the primary data store.
>
The benefit of this is that developers do not need to worry about how to properly encrypt data. The responsibility of encryption is on Vault and the security team managing it, and developers just encrypt/decrypt data as needed.

**Comment by whit537** [comment]
One key feature of our requirements here is that the web app only needs to *write* secrets, not read them. It's the payroll process that needs to read secrets, in order to originate ACH credits. My thought is that we should use public key cryptography, with the web app holding the public key (via `heroku config:set`) and the payroll process having access to the private key.

Introducing a server component, whether Vault or something else (including something DIY), increases our surface area and level of complexity significantly moreso than integrating encryption-before-storage into our existing application architecture. What are the PCI implications of the latter?

**Comment by whit537** [comment]
Another design requirement: I want separate access groups for the main web app and the PCI vault. I want to be able to grant access to Heroku (app + db) as we've been doing, which is carefully, to be sure ... but we need to be *even more careful* with access to vaulted data.

**Comment by whit537** [comment]
Let's distinguish the three pieces of information we're intending to collect, their risk profile, and our immediate application requirements regarding each.

| piece of information | risk | write | read (process, role, purpose) |
|:--|:--|:--|:--|
| bank account number (**BAN**) | financial theft | web | payroll, Gratipay, generation of NACHA files to submit for ACH origination | 
| individual national identification number (**NIN**) | personal identity theft | web | web, team owners, filling out tax forms |
| business identification number (<b>VAT/EIN</b>) | [business identity theft](http://www.businessidtheft.org/Education/BusinessIDTheftScams/BusinessEINandTaxFraud) | web | web, supporters and team owners, generation of invoices |

**Comment by whit537** [comment]
So the web app *does* need to read some secrets.

**Comment by whit537** [comment]
Meaning it *does* come under the systems we need to consider in terms of PCI compliance.

**Comment by whit537** [comment]
The requirement for invoices is that VAT be available to both supporters (buyers; https://github.com/gratipay/gratipay.com/issues/1199#issuecomment-24576143) and teams (sellers; https://github.com/gratipay/gratipay.com/issues/1199#issuecomment-67562705).

**Comment by whit537** [comment]
Hashi Vault supports [dynamic secrets](). Could we use that to ensure that access to Heroku doesn't entail access to our vault?

**Comment by whit537** [comment]
> **Dynamic Secrets**: Vault can generate secrets on-demand for some systems, such as AWS or SQL databases. For example, when an application needs to access an S3 bucket, it asks Vault for credentials, and Vault will generate an AWS keypair with valid permissions on demand. After creating these dynamic secrets, Vault will also automatically revoke them after the lease is up.

http://vaultproject.io/intro/

**Comment by whit537** [comment]
Like, when the app spins up, it asks our vault for credentials to our vault?

**Comment by whit537** [comment]
Looks like that would take some work.

**Comment by whit537** [comment]
I'm going through [the Vault intro](http://vaultproject.io/intro/getting-started/install.html).

**Comment by whit537** [comment]
Alright, I am introduced to Vault. It's a nice piece of software. We very well may be able to use it here.

**Comment by whit537** [comment]
> I want to give people access to a web app (at Heroku, as it happens) that has access to Vault, without giving the people the same access to Vault as the web app has. This could be achieved with a vault secret backend that supported dynamic secrets, yes?

https://github.com/hashicorp/vault/issues/288

**Comment by whit537** [comment]
I've registered for an AWS account.

**Comment by whit537** [comment]
Can we use the browser as the go-between to avoid leaking vault access to people with Heroku access?

**Comment by whit537** [comment]
I don't see how to meet this requirement with Vault. :(

**Comment by whit537** [comment]
Or at all, really. If the web app has to be able to write, then whoever has access to the web app could potentially write out their bank account details and collect all of payroll for a week.

**Comment by whit537** [comment]
Okay, so let's take it that we *don't* have a separate access tier that is even tighter than access to our production hosting environment and database.

Then we're back up against the fact that Heroku does not promise a PCI-compliant environment to nearly the extend that Amazon does.

**Comment by whit537** [comment]
Gosh. Are we talking about migrating away from Heroku? :mouse: 

> ##### Are your datacenters certified / PCI compliant?
>
All of our datacenters have been certified by national and/or international security standards.
>
Our NYC1 facility is SSAE16 SOC-1 Type II certified.
Our NYC2 facility is SSAE16 SOC-2 Type II certified.
Our NYC3 facility is SSAE16 SOC-2 and SOC-3 compliant.
Our AMS1 and AMS2 facilities are ISO27001:2005 and ISO9001 certified.
Our AMS3 facility is ISO9001, ISO27001, and SSAE16 Type II certified
Our SFO1 facility is SSAE16 SOC-1 Type II certified.
Our SGP1 facility is ISO27001:2005 certified.
Our LON1 facility is ISO9001:2008, ISO27001, and SSAE16 / ISAE 3402 certified.
Our FRA1 facility is ISO9001:2008, ISO27001:2005, and ISO22301:2012 certified.

https://www.digitalocean.com/help/policy/

**Comment by whit537** [comment]
Amazon > DO > Heroku

**Comment by whit537** [comment]
Okay! Reticketed as #3505. :swimmer:

**Comment by whit537** [comment]
Well, reopening because it still might make sense to separate out the vault from the main db.

**Comment by whit537** [comment]
See https://github.com/gratipay/inside.gratipay.com/issues/223 for overarching discussion about infosec risk management.

**Comment by whit537** [comment]
Here's the page listing [Vault storage backends](http://vaultproject.io/docs/config/). [Consul](https://consul.io/) looks like the only real option for us. They recommend 3-5 nodes per data center, and we should have at least two data centers (availability zones [AZ] in AWS-lingo).

**Comment by whit537** [comment]
Could we get away with one node and an EBS block?

**Comment by whit537** [comment]
"[AWS Tips I Wish I'd Known Before I Started](https://wblinks.com/notes/aws-tips-i-wish-id-known-before-i-started/)"

> A collection of random tips for Amazon Web Services (AWS) that I wish I'd been told a few years ago, based on what I've learned by building and deploying various applications on AWS.

**Comment by whit537** [comment]
How about two AZs, with one EC2 instance each, running both Vault and Consul + one EBS volume.

**Comment by techtonik** [comment]
I'd really really like to outsource the task of private information management to trusted parties, which could be security *and* privacy guarantees of our clients.

**Comment by whit537** [comment]
@techtonik Please make a concrete suggestion for how to do that in our case.

**Comment by techtonik** [comment]
Ok. The suggestion is that we only have to keep records like this:

- twitterid - privacyservice1:id

Then we need to query the bank requisites through OAuth **or** give the privacyservice1 a command "do transaction with ... on behalf of our client that is recorded as privacyservice1:id on your system".

I'd really avoid storing all the private info on GP, because then it will become an easy attack vector automatically.

**Comment by whit537** [comment]
@techtonik What are some examples of companies we could use for `privacyservice1`?

**Comment by techtonik** [comment]
@whit537 I think that lawyers should know about privacy services, so they should be aware for privacy services in banking industry as well.

**Comment by whit537** [comment]
@techtonik That's a cop out. Go find us some privacy services to talk to if you want us to pursue that possibility.

**Comment by techtonik** [comment]
@whit537 we do have a lawyer that we pay, don't we?

**Comment by whit537** [comment]
@techtonik That's a cop out. Go find us some privacy services to talk to if you want us to pursue that possibility.

**Comment by techtonik** [comment]
@whit537 is it possible to ask him directly first? I don't even know how these services are called in English, leave alone US specific terms.

**Comment by whit537** [comment]
@techtonik Can you link us to one example of such a service? Doesn't have to be in English, I just have no idea what you're talking about right now. :-(

**Comment by techtonik** [comment]
@whit537 I don't know. Some advanced banks have services that help to preserve user privacy. They can issue anonymous or one-time debit card, for example, and may exhibit a OAuth management API that can also hide the identity. This decreases the risk that user data will be stolen and reused by malicious party. Quick search - https://www.privacyworld.com/5mastercard.html

**Comment by whit537** [comment]
@techtonik I'm not sure what to do with that side. In any case, we were rejected by Citizens (#3366), so we're no longer trying to build our own direct ACH integration and we don't need to store bank numbers. We're going to try Zipmark instead (#3491). Closing ... for now(?!).

**Comment by whit537** [comment]
Zipmark didn't work out, and it turns out we want to do strong idv for employment reasons, not just AML reasons.

**Comment by whit537** [comment]
Blog post on Balanced's architecture:

http://blog.balancedpayments.com/balanceds-architecture/

**Comment by whit537** [comment]
"[best practices for storing ssn](https://www.google.com/search?q=best+practices+for+storing+ssn)]

 - http://stackoverflow.com/questions/254935/storing-social-security-numbers
 - https://community.spiceworks.com/topic/739855-best-practices-storing-personal-data-including-ssns
 - http://www.sqlservercentral.com/Forums/Topic1572097-373-1.aspx
 - https://www.socialsecurity.gov/kc/id_practices_best.htm
 - http://security.stackexchange.com/questions/9403/when-storing-private-identifying-information-in-a-web-application-what-is-indu
 - http://discuss.fogcreek.com/joelonsoftware1/default.asp?cmd=show&ixPost=32808
 - https://www.ssa.gov/phila/ProtectingSSNs.htm
 - http://passcouncil.washington.edu/site/files/uw_ssn_best_practices.pdf
 - http://passcouncil.washington.edu/site/files/uw_ssn_guide.pdf
 - https://www.reddit.com/r/AskNetsec/comments/2pswf5/securely_storing_ssn_details/

**Comment by whit537** [comment]
> I would look towards HIPAA de-identification guidelines on protected data from HHS.

https://www.reddit.com/r/AskNetsec/comments/2pswf5/securely_storing_ssn_details/cmzyxno

Haven't considered HIPAA before.

**Comment by kzisme** [comment]
http://www.heinz.cmu.edu/~acquisti/ssnstudy/

**Comment by whit537** [comment]
POI:

> ZeroDB is an end-to-end encrypted database. Data can be stored on untrusted database servers without ever exposing the encryption key. Clients can execute remote queries against the encrypted data without downloading all of it or suffering an excessive performance hit.

https://github.com/zero-db/zerodb

([h/t](http://us4.campaign-archive2.com/?u=9735795484d2e4c204da82a29&id=247cb9ae65))

**Comment by whit537** [comment]
I propose that we close this ticket. Why? Because **we already have a vault**. Meaning, we already have a database that contains sensitive information, which we [take care to protect](http://inside.gratipay.com/howto/handle-security-issues). Security means constant vigilance, there is no  "done" state where we'll be perfectly ready to store national identity numbers and passport scans. [Running HackerOne](https://hackerone.com/gratipay) for a while, observing the security practices of other organizations, and [watching NSA predators](https://github.com/gratipay/inside.gratipay.com/issues/479#issuecomment-177623636) has me feeling hesitantly confident that we're not at the back of the pack when it comes to security. I think we should go for it.

@rohitpaulk @clone1018 @aandis et. al?

**Comment by whit537** [comment]
> We need a vault separate from our main application and database that is more highly secure. We should use the PCI DSS 3.0 standard to self-assess the security of our application (gratipay/inside.gratipay.com#214). This ticket is about building a new vault component of our architecture.

Now I'm saying that we treat our main app and database as our vault (rather than building a separate component), and we evolve towards something like DSS as we scale.

**Comment by whit537** [comment]
Last call for objections to closing this ticket and declaring that we already have a vault ...

**Comment by whit537** [comment]
We're a far cry from Uphold's [definition of a vault](https://github.com/gratipay/gratipay.com/issues/3870#issuecomment-187718272). :-/

**Comment by whit537** [comment]
@mattbk at https://github.com/gratipay/inside.gratipay.com/issues/532#issuecomment-194589942:

> Note to self, what gets stored in the vault?

Unclear. Either everything (our current database *is* our vault) or just sensitive info such as national identity info (we have a second database). Though in the first case we would still differentiate sensitive info, and store it in the current database in encrypted form. Maybe the difference is semantic. Our vault has "layers" or something.

**Comment by whit537** [comment]
Alright @rohitpaulk @aandis @mattbk @kaguillera: per https://github.com/gratipay/inside.gratipay.com/issues/539#issuecomment-197699555, let's start with the five of us. Would you store your name, address, and national ID number in Gratipay today? Why not? What is the minimum we need to accomplish before you're comfortable doing so?

**Comment by rohitpaulk** [comment]
> Would you store your name, address, and national ID number in Gratipay today?

Yes, I would

**Comment by mattbk** [comment]
Sure.

**Comment by aandis** [comment]
:+1:

**Comment by whit537** [comment]
Awesome! Me, too. :-)

I will check with @kaguillera when I see him next week ...

**Comment by whit537** [comment]
> #### California Attorney General defines "reasonable security"
>
When businesses are breached, their liability is largely determined by if they had practiced reasonable security, so a lot of litigation regarding breaches is focused on determining that. This litigation is due to there being no definition of reasonable of security. The California Attorney General Kamala Harris, on February 16th, released [California's annual breach report](https://oag.ca.gov/news/press-releases/attorney-general-kamala-d-harris-releases-data-breach-report-over-49-million) and within it, she defined reasonable security, stating "The 20 controls in the Center for Internet Security’s Critical Security Controls identify a minimum level of information security that all organizations that collect or maintain personal information should meet. The failure to implement all the Controls that apply to an organization’s environment constitutes a lack of reasonable security."
>
The breach report itself, like most breach reports, isn't that interesting. California has been collecting information about breaches since 2003, when California became the first state to require businesses to inform affected parties when those victims are residents of California. Now 46 states have similar requirements.
>
The definition the Attorney General used for reasonable security, the [CIS Critical Security Controls](https://www.cisecurity.org/critical-controls.cfm) ([direct link](http://cybersecurity.idaho.gov/pdf/CSCmaster.pdf) to a copy), are extremely aggressive goals that few organizations outside of the Department of Defense currently implement. For example, it requires application white-listing (CSC 2.2), disabling javascript (CSC 7.3), and other controls which although valid recommendations, are difficult to implement in practice from a business perspective.

**Comment by whit537** [comment]
> [BeyondCorp: Design to Deployment](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/44860.pdf): Google's BeyondCorp strategy has been heralded as the right way forward for protecting networks. The concept is to no longer have an internal corp network that employees need to hard-wire or VPN into, because that promotes a crunchy outside and soft inside network, where once an attack gets on one of your employee laptops they end up with free rein. The BeyondCorp strategy that Google announced a year ago advises that you shouldn't provide access to systems just because of what network they come in on. This new paper describes this concept in more detail.

https://summitroute.com/blog/2016/04/10/downclimb/

**Comment by whit537** [comment]
Alright, talking w/ @kaguillera here IRL and he is good to go here. 👍 

(Though he also mentions that national ID numbers are not big in Trinidad and passport or driver's license would be more normal.)

**Comment by whit537** [comment]
Alright, folks! Closing this one out. We have a vault. 😳 

Future work to be organized on the [Security Radar](https://github.com/gratipay/inside.gratipay.com/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3ARadar+label%3A%22Security+Team%22).
