### ISSUE TITLE
require email before charging users

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3506]
Primary driver is consumer protection: we want to notify people about Gratipay charges to reduce surprises.
##

**Comment by whit537** [comment]
> Additionally, our sponsoring bank suggested collecting and saving cardholder information, such as phone numbers, in the future for cases where documentation may be necessary. These situations may occur if you have to dispute a chargeback and provide evidence for your supporting case. 

https://github.com/gratipay/gratipay.com/issues/3531#issuecomment-112256884

**Comment by whit537** [comment]
+1 https://gratipay.freshdesk.com/helpdesk/tickets/3292

**Comment by whit537** [comment]
+1 https://github.com/gratipay/inside.gratipay.com/issues/477#issuecomment-173634468

**Comment by mattbk** [comment]
Requiring email would help in cases like https://github.com/gratipay/gratipay.com/pull/4221, where the ToS is changing and we should notify people.
