### ISSUE TITLE
update subscriptions page

### ISSUE THREAD

**Issue by akarelas** [gratipay/gratipay.com#3511]
My account (akarelas) sees the following screen on gratipay. As you can see the numbers don't add up:

http://s3.postimg.org/g77tvv9eb/gratipay.png

##### Notify:

 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2233
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2398
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2399
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2408
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2405
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2483
 - [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2540

**Comment by whit537** [comment]
Thanks for the report, @akarelas, sorry for the trouble.

**Comment by whit537** [comment]
+1 https://gratipay.freshdesk.com/helpdesk/tickets/2233

> BTW, just noticed another issue: total sum of my payments (in "Giving" on dashboard or under my nickname in the header) is wrong. It seems to include pre-2.0 payments, but not current ones.

**Comment by whit537** [comment]
@timothyfcook on #3570:

>It says I'm giving $10.25 a week, but I see only see one item for $2.00 in my Subscriptions detail.
>
Is this an issue with the old recipients of my gifts not having activated/reconciled their accounts with the Gratipay 2.0 restrictions?
>
![screen shot 2015-06-19 at 11 28 58 am](https://cloud.githubusercontent.com/assets/1823300/8256669/7ddde56e-1676-11e5-9792-cc6106981073.png)

**Comment by whit537** [comment]
+1 from @noffle at https://github.com/gratipay/gratipay.com/issues/3572:

> On my account page it claims "You pay $2.10 per week", though under Subscriptions all I see is a $0.10 / week subscription to Gratipay.
>
According to my history, my $2.10 / week payments stopped going through as of April 30 2015. My credit card information looks up to date.

**Comment by whit537** [comment]
+1 from @joelhooks on #3589:

>http://cl.ly/image/0H431M3L250i
>
It says I am paying, but nothing shows up. What's up with that? I can't affect donations at all. This seems totally broken on my account.
>
> I can't add new payments or see my existing ones, so I removed my card altogether. This makes me sad for the people I was contributing too...
>
I'd say 2.0 is "alpha" ;(

**Comment by whit537** [comment]
@joelhooks Your History should reflect the true amount we're actually charging your credit card. Is that at least accurate?

**Comment by mattbk** [comment]
+1 from Ticket #2450 on Freshdesk.

**Comment by whit537** [comment]
(@mattbk Please use the Freshdesk URL as the #2450 notation links to the *GitHub* ticket with the same number. Also, I think we should add Freshdesk tickets to the Notify section of the ticket description instead of +1s in comments, so we have them all in one place. Eh?)

**Comment by mattbk** [comment]
Sounds like a plan. 

On July 9, 2015 6:07:34 PM CDT, Chad Whitacre <notifications@github.com> wrote:
>(@mattbk Please use the Freshdesk URL as the #2450 notation links to
>the *GitHub* ticket with the same number. Also, I think we should add
>Freshdesk tickets to the Notify section of the ticket description
>instead of +1s in comments, so we have them all in one place. Eh?)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/gratipay/gratipay.com/issues/3511#issuecomment-120171150

-- 
Sent from a phone that, although intelligent, is not street smart.

**Comment by whit537** [comment]
Thanks. :)

**Comment by mattbk** [comment]
While on the topic of Subscriptions, a comment from https://gratipay.freshdesk.com/helpdesk/tickets/2450:

> the word "Subscriptions" just seems ... unilluminating.  To me, a subscription is something that I receive in exchange for payment; but the whole point of gratipay is that I'm giving money _without_ expectation of receiving anything in return (unless you count warm fuzzies).  So every time I see "Subscriptions", my brain stumbles a little.

**Comment by whit537** [comment]
@mattbk Copied to https://github.com/gratipay/inside.gratipay.com/issues/117.

**Comment by mattbk** [comment]
Moving toward closing, if:
- the total giving amount is changed to be correct.
- only approved teams (and not ~users) are listed on the giving page.

Anything else to be done that falls under this ticket?

**Comment by whit537** [comment]
> the total giving amount is changed to be correct.

This should fall out from #3599.

> only approved teams (and not ~users) are listed on the giving page.

I believe this is now the case. Are you seeing otherwise?

**Comment by mattbk** [comment]
>> the total giving amount is changed to be correct.

>This should fall out from #3599.

Sounds good.

>> only approved teams (and not ~users) are listed on the giving page.

>I believe this is now the case. Are you seeing otherwise? 

No, I just wanted to check.

In which case, I am closing.

**Comment by mattbk** [comment]
No, will wait for #3599, then notify people on this ticket.

**Comment by whit537** [comment]
Yeah, let's wait until the numbers line up, especially since that was the original report. Almost there!

**Comment by whit537** [comment]
I believe this issue is fixed with #3663. @mattbk Can you confirm, please?

**Comment by whit537** [comment]
cc: @akarelas ;)

**Comment by akarelas** [comment]
It has been fixed, but there remains a problem: While in the middle of the page it says that I'm giving $0.60 per week, on the top right corner, right under my nickname, it says $0.86/wk

**Comment by whit537** [comment]
@akarelas Okay, let me squish that real quick ...

**Comment by whit537** [comment]
@akarelas Better now?

**Comment by akarelas** [comment]
Yes, problem solved.

**Comment by whit537** [comment]
Huzzah! :dancer: 

Thanks for your patience, @akarelas.

@mattbk Cleared to notify others (once you confirm for yourself ;-).
