### ISSUE TITLE
implement OpenID

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3512]
Suggested in https://gratipay.freshdesk.com/helpdesk/tickets/2228.

(This is a resurgence of #1503, because OpenStreetMap is purportedly "refusing further logins due to excess spam attacks." However, I just registered [an account](http://www.openstreetmap.org/user/gfhldsgflh) there, so I'm not sure that's (still?) true.)
##

**Comment by nobodxbodon** [comment]
Re-ticketed to https://github.com/gratipay/inside.gratipay.com/issues/983 for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.
