### ISSUE TITLE
explain why there's no unsubscribe

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3516]
We use `include_unsubscribe=False` for verification emails. There, it's obvious why there's no unsubscribe link. For any other case where we use this, we should provide an explanation, e.g.:

> This is an important transactional or relationship message associated with your Gratipay account. To avoid receiving messages like this in the future, please [close your Gratipay account](https://gratipay.com/about/me/settings/close).

Reticketed from https://github.com/gratipay/inside.gratipay.com/issues/235.
##

**Comment by ehmatthes** [comment]
> This is an important transactional or relationship message associated with your Gratipay account. To avoid receiving messages like this in the future, please close your Gratipay account.

This sounds a little aggressive, or overly blunt. I don't think it's a message people are used to seeing from other services. Perhaps it could be clarified a little?

> This is ~~an important~~ a critical transactional or relationship message associated with your Gratipay account. Critical messages are sent to all Gratipay users; to avoid receiving messages like this in the future, ~~please~~ you'll have to close your Gratipay account.

Also, is there a requirement to have an unsubscribe link, or just information about how to unsubscribe? If a link is required, the message should link to the page where people can close their account.

**Comment by whit537** [comment]
@ehmatthes The unsubscribe link is only required for "commercial" messages, not for "transactional and relational" messages. There's more on https://github.com/gratipay/inside.gratipay.com/issues/235#issuecomment-108447186 about the distinction.

If we follow the guidelines better about [distinguishing transactional and commercial messages](https://www.ftc.gov/tips-advice/business-center/guidance/can-spam-act-compliance-guide-business), maybe we can keep it simpler? What do most other services do?

**Comment by ehmatthes** [comment]
> What do most other services do?

I'm not sure exactly, but I'm pretty sure I've never seen a message telling me to delete my account in order to stop receiving emails.

**Comment by webmaven** [comment]
I think transactional messages can just have a 'manage subscriptions' link going to a page that lists all types of messaging, with checkboxes etc.

> To manage the types of messages you receive from Gratipay, go to the [manage subscriptions](#) page.

The note about transactional messages not being unsubscribable can appear on that page, perhaps with an appropriate link to the TOS.

Here is example from the footer of a e-commerce transactional message I received the other day:

> Need to update your information? It's easy. [Login to your account](#).

For that online retailer, all other messages seems to be opt-in, and I haven't received anything yet but that single transactional message.

**Comment by whit537** [comment]
> [...] I'm pretty sure I've never seen a message telling me to delete my account in order to stop receiving emails.

HackerOne provides an example ([ref](https://github.com/gratipay/inside.gratipay.com/issues/255#issuecomment-123940531)):

![screen shot 2015-07-22 at 11 30 23 pm](https://cloud.githubusercontent.com/assets/134455/8842554/b9ccd220-30c9-11e5-9ba0-0cef6a794132.png)

**Comment by whit537** [comment]
An example from Google:

![screen shot 2016-04-11 at 12 12 40 pm](https://cloud.githubusercontent.com/assets/134455/14434154/5d772d3c-ffdf-11e5-8477-f377ea55474f.png)

> You received this mandatory email service announcement to update you about important changes to your Google product or account.
