### ISSUE TITLE
PNC for ACH?

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3518]
Citizens rejected us (#3366). How about PNC?

**Comment by clone1018** [comment]
We have a good start on all the tools we'll need to continue applying to
banks until we get accepted :)

**Comment by whit537** [comment]
That's the spirit! :dancer:

**Comment by whit537** [comment]
I also have a couple friends at PNC, whom I can ask for advice.

**Comment by whit537** [comment]
We're now using PNC for operations (https://github.com/gratipay/inside.gratipay.com/issues/240), and I think we should have operations and escrow at different institutions, to reduce risk like we saw on #3366.
