### ISSUE TITLE
Setting to track/expose how much of my living cost is covered by Gratipay

### ISSUE THREAD

**Issue by techtonik** [gratipay/gratipay.com#3519]
If we're talking about donation based payroll, it makes sense to be able to see how much of your living cost the Gratipay covers. This will help other people to decide how much to give you, but also to visualize your own situation. It may also [help teams communicate their flow](https://mail.python.org/pipermail/pypy-dev/2015-June/013526.html), but right now I am talking about individuals.

I see it like a form to enter variable that gives a fixed amount of value that you need weekly.
- If entered, it becomes public info.
- When compared with your weekly income, a graph is shown.

The value is recorded every time. The change of value may come with comment to make you keep track of your requirements and reasons for the raise. The goal is to have a clean interface that will allow people to start adding to their living cost, and compare it using timeline. I would personally try to see how much do I need to spend on food every week, then raise it from "most cheap healthy food" to "comfortable food" bar, then separately "living cost" and "communication" and "transportation".
##

**Comment by webmaven** [comment]
@techtonik:
> If entered, it becomes public info.

I'd like the info, but don't like the idea of it defaulting to public.
