### ISSUE TITLE
Update routing.txt info about fees

### ISSUE THREAD

**Issue by techtonik** [gratipay/gratipay.com#3521]
The main question that bothers many is how much do we lose when we use the service. I want to update https://github.com/gratipay/gratipay.com/blob/master/data/routing.txt

If I understand correctly, there is no Bitcoin anymore, and Balanced is replaced by Braintree. What are the current fees?

**Comment by whit537** [comment]
Correct, [no bitcoin anymore](https://github.com/gratipay/inside.gratipay.com/issues/201#issuecomment-102010517), and Balanced is replaced by Braintree. Their [fee](https://www.braintreepayments.com/pricing) is "2.9% + $.30 per transaction after your first $50K." Hmmm ... that could actually offset some of the $250 minimum from Zipmark (#3443). What do those numbers look like?

**Comment by techtonik** [comment]
Where is the prooflink for $50K? I see only "2.9% + $.30 per transaction".

**Comment by whit537** [comment]
Same link, no?

![screen shot 2015-06-04 at 5 45 05 pm](https://cloud.githubusercontent.com/assets/134455/7995152/783794f2-0ae1-11e5-857c-2bc6d87e6cee.png)

**Comment by rohitpaulk** [comment]
@whit537 - I think it's country based, I don't see the $50k either.

**Comment by techtonik** [comment]
![braintree](https://cloud.githubusercontent.com/assets/515889/7995270/196ca8cc-0b1d-11e5-84c3-bf1eb6d9aac8.png)

**Comment by techtonik** [comment]
Definitely not clear. =)

**Comment by whit537** [comment]
Interesting. What do you see here: https://www.braintreepayments.com/faq#free-processing?

**Comment by techtonik** [comment]
The whole pricing paragraph is different:
> We've not published pricing for some countries because we work with multiple banking partners throughout the world and they have different pricing structures and accept different merchant types. We're working on standardizing this.

**Comment by techtonik** [comment]
I guess I need to add list of countries into the routing table.

**Comment by techtonik** [comment]
Please review the shutdown date in 567fa6d35ad5. I missed with creating a branch for this change.

**Comment by whit537** [comment]
@techtonik I've reverted 567fa6d35ad5745c404cbe62d98ad6013c7f52b3 in a88aa5ab2d6d687fb85a84f7ea9b0a1437b01b63. Please open a pull request. Commits to master are acceptable for developer documentation (e.g., `README.md`), but data/routing is intended to be user-facing documentation.
