### ISSUE TITLE
migrate bank account info to Zipmark

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3522]
Looks like we're going to go with Zipmark for ACH: #3491. This ticket is for migrating bank account info.

To: Balanced
Cc: Zipmark

> Well, it looks like Gratipay is going to be one of the last ones out the door. After trying to pull off our own ACH partnership with a bank, we're now turning to plan B (discovered last week): Zipmark. The Zipmark team is copied here. Can we please start the process of migrating Gratipay's users' bank account info to them? Let me know what you need from me. Thanks! :-)

**Comment by whit537** [comment]
[Private convo in Slack](https://zipmark.slack.com/archives/gratipay/p1433533811000002). Upshot:

> other point on the migration file is we need you to supplement some data customer_name,customer_type,tax_id,street,street2,city,state,zip_code,contact_first_name,contact_last_name,contact_email
so, if you can provide that w/ the customer_id, ill merge the two data sets for import
customer_type can be either 'organization', or 'individual'

We can complete the migration without name and address, though we'll need to collect that info (either ourselves or with a Zipmark iframe) before we can process payments. However, we need to collect tax id numbers (cf. https://github.com/gratipay/gratipay.com/issues/3289#issuecomment-107100341) before we can complete the migration, so we're blocking on https://github.com/gratipay/gratipay.com/issues/3289 here.



We

**Comment by whit537** [comment]
We can probably pull some name/address info out of Balanced.

**Comment by whit537** [comment]
> tax ID and email are necessary

We do require emails for team owners, so we're covered there.

**Comment by whit537** [comment]
To: Zipmark

> Our best option may be to scrap the Balanced migration data and sign up all users from scratch (we only have 16 users that we've already onboarded on the new Gratipay w/ bank payouts). Can we schedule a call or chat to discuss what that would look like?
>
How about tomorrow (Thursday) at 11am or 2pm?

h/t @kaguillera @dmk246

**Comment by rohitpaulk** [comment]
#3491 isn't happening, closing.
