### ISSUE TITLE
send email notification for payouts

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3526]
To complement the credit card charge {success,failure} notifications.
##

**Comment by whit537** [comment]
+1 https://gratipay.freshdesk.com/helpdesk/tickets/2243

> So I received $[] yesterday (a one weekly incoming), guessing that means we're approved yay!
I didn't get any confirmation notification.

**Comment by dcht00** [comment]
@whit537 maybe to clear it up:
* I do get a notification of payment from PayPal everytime. That's what I've always relied on
* What I meant as being confusing was I wasn't notified when my "new" application got approved (or denied). There was a ticket for that here, but the system should prob inform people in some other way they were approved than just seeing money starting to roll in :)
What happens if they're denied?

**Comment by whit537** [comment]
@dcht00 Ah, gotcha. Good call. Reticketed as https://github.com/gratipay/gratipay.com/issues/3564.

**Comment by whit537** [comment]
@bocajnotnef How far did you get with this the other day? Do you have any code you could start a PR with? I'm about to point @kzisme at this one.

**Comment by kzisme** [comment]
Just to be clear - what would be considered a new "application" ?  

So, an email notification about receiving funds (rather than just charge_succeeded) would be nice - as opposed to waiting on your own institution to notify you.  Right?

**Comment by whit537** [comment]
@kzisme A new "application" refers to https://gratipay.com/new ... but that's a different ticket (#3564).

This ticket is about sending an email notification when we make a payout to someone's bank account. We already do this during payday for credit card charges, in [`notify_participants`](https://github.com/gratipay/gratipay.com/blob/1857/gratipay/billing/payday.py#L506-L560). Check the `emails` directory for email templates.

**Comment by bocajnotnef** [comment]
Unfortunately I got nowhere. Foreign code base and that, spent most of the
time getting my bearings.

**Comment by whit537** [comment]
@bocajnotnef No worries, just wanted to make sure we weren't about to step on your toes. :)

**Comment by mattbk** [comment]
Because of https://github.com/gratipay/gratipay.com/issues/3567, there definitely needs to be a notification if a ~user/owner does _not_ have a PayPal account attached for receiving payouts.  I explain why at https://github.com/gratipay/gratipay.com/issues/3644#issuecomment-124994199.

**Comment by whit537** [comment]
This is actually less important now, because PayPal sends a notification.
