### ISSUE TITLE
configure SPF for gmail for support@gratipay.com

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3530]
Reticketing from https://github.com/gratipay/inside.gratipay.com/issues/234:

> The error that the other server returned was:
550 209.85.216.176 is not allowed to send mail from gratipay.com. Please see http://www.openspf.net/Why?scope=mfrom;identity=support@gratipay.com;ip=209.85.216.176

**Comment by whit537** [comment]
https://support.google.com/a/answer/178723

**Comment by whit537** [comment]
DNS updated. Waiting for propagation before closing.

**Comment by kyledrake** [comment]
Let me know if this is a problem on my end (entirely possible).

**Comment by whit537** [comment]
DNS has propagated.

@kyledrake I just sent you another message. Can you let us know whether that comes through?

**Comment by whit537** [comment]
All set! :)

https://gratipay.freshdesk.com/helpdesk/tickets/2297

**Comment by whit537** [comment]
Thanks, @kyledrake. :)
