### ISSUE TITLE
make Teams editable

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3545]
Reviewing teams is creating pressure to edit teams, as one might expect. :)

#### Notify
- [x] https://gratipay.freshdesk.com/helpdesk/tickets/2879
- [x] https://gratipay.freshdesk.com/helpdesk/tickets/3247

**Comment by whit537** [comment]
+1 from @stevepiercy at https://github.com/gratipay/gratipay.com/issues/3681#issuecomment-135148451:

> when I log in as ~stevepiercy and view my account profile, I expect to see a UI for me to manage Team KnopProject, but cannot find one. I couldn't manage the Team, so I assume one of the Gratipay staff assigned me as Owner on my behalf. Is some public Team management UI is forthcoming?

**Comment by book** [comment]
How will the team owner/admins invite new members to the team? I expect this to be part of "team management" too.

**Comment by whit537** [comment]
@book Yeah, on Gratipay 1.0 there was a page listing all of the members of the team, and team admins had an input on there to locate and add new members. We'll bring this back below #3433.

**Comment by whit537** [comment]
+1 @sils1297 at https://github.com/gratipay/team-review/issues/36#issuecomment-137971240.

**Comment by whit537** [comment]
+1 @duythien in https://github.com/gratipay/team-review/issues/84:

> My team https://gratipay.com/phanbook/ have just active and I want to change logo, but I'm does not see options. Can you help me change logo

**Comment by whit537** [comment]
+1 from @Jaex at https://github.com/gratipay/team-review/issues/79#issuecomment-148617054.

**Comment by whit537** [comment]
+1 from @webschik at https://github.com/gratipay/team-review/issues/83#issuecomment-148604227.

**Comment by mattbk** [comment]
+1 from me

**Comment by whit537** [comment]
+1 @senthilporunan https://github.com/gratipay/team-review/issues/89#issuecomment-150468492

**Comment by whit537** [comment]
How does Team editing interact with [review](http://inside.gratipay.com/howto/review-teams)? If Team pages are changing and we're making yes/no decisions based upon the content thereof, then should we freeze Team pages at some point? Or at least show the history of changes (at least for admins?)?

**Comment by whit537** [comment]
Should changes once a Team has been approved have to go through another approval process?

**Comment by whit537** [comment]
Or should we simply log those as `events` and provide a dashboard to passively review Team change events?

**Comment by kaguillera** [comment]
> simply log those as events and provide a dashboard to passively review Team change events
+1 
Let try to reduce the inconvenience of the users as much as possible. They have been through enough already.

**Comment by rohitpaulk** [comment]
+1 at https://github.com/gratipay/gratipay.com/issues/3871

**Comment by rohitpaulk** [comment]
+1 at https://github.com/gratipay/team-review/issues/91#issuecomment-164538766

**Comment by mattbk** [comment]
> Or should we simply log those as events and provide a dashboard to passively review Team change events?

Yes. We should also allow flagging Teams as part of https://github.com/gratipay/gratipay.com/issues/2992.

**Comment by whit537** [comment]
+1 from @Mottie in https://github.com/gratipay/team-review/issues/132.

**Comment by whit537** [comment]
+1 from @donv on https://github.com/gratipay/team-review/issues/146.

**Comment by whit537** [comment]
+1 from @KronicDeth at https://github.com/gratipay/team-review/issues/155#issuecomment-180667322.

**Comment by mattbk** [comment]
!m @aandis

**Comment by aandis** [comment]
Closed with #3923 :dancer:

**Comment by aandis** [comment]
@whit537 what are those freshdesk [tickets](https://github.com/gratipay/gratipay.com/issues/3545#issue-87458343) for? Can you mark them completed now?

**Comment by whit537** [comment]
!m @aandis Great work!

The freshdesk tickets are to circle back around and let people know this is done—you able to see to that, @mattbk?

**Comment by mattbk** [comment]
Yes, that's for me to do. Going to reopen this until I do that.

**Comment by mattbk** [comment]
I may just post a notification in every team application issue...

**Comment by whit537** [comment]
Sounds a little like https://github.com/gratipay/inside.gratipay.com/issues/515#issuecomment-191414090 but I guess it's different since it's our own repo, you're not posting in other people's repos.

**Comment by whit537** [comment]
@mattbk I say go for it! :-)

**Comment by whit537** [comment]
Do we have a good way to do that?

**Comment by mattbk** [comment]
"Editing Teams" could mean two things
- editing team properties (name, links, statement, logo) <--is "properties" a good term to use for this?
- adding or removing members

**Comment by whit537** [comment]
> is "properties" a good term to use for this?

Team "profile"?

**Comment by stevepiercy** [comment]
FWIW, the submit button named "Modify" confused me because I had just clicked the link "Edit Team". I thought that I had to click the Modify button to start editing, not Save what I would be editing. "Save" is more intuitive.

Also suggest inserting a non-breaking space in "Edit Team" so that it does not wrap to the next line like this:

![google chrome001](https://cloud.githubusercontent.com/assets/102112/13533988/c60e8d10-e1e7-11e5-8201-ae4fdb59c4da.jpg)

Finally, "properties" works for me. Profile is what law enforcement does to people of color.

**Comment by aandis** [comment]
@mattbk what am I assigned to here? Perhaps you meant #3935?

**Comment by aandis** [comment]
>> is "properties" a good term to use for this?

> Team "profile"?

I think `editing` sounds good in the context of changing team properties. We could also go with `Update`. Generally updating/editing a `profile` has a similar meaning. For adding and removing members, maybe `Manage` team?

**Comment by aandis** [comment]
I agree with @stevepiercy.  `Save` sounds better than `Modify`.

**Comment by mattbk** [comment]
@aandis you were originally assigned, so after I realized we couldn't both be assigned, I added you back on.

I'm going to assign it to myself now since I need to update everyone who +1'ed it.

**Comment by aandis** [comment]
oh okay! :)

**Comment by mattbk** [comment]
Closing this as I have notified everyone from FD and all the +1s on this ticket. Can address future questions as they come up.

**Comment by whit537** [comment]
!m @mattbk
