### ISSUE TITLE
sort out implications of holdover on 1.0 balances

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3551]
When paying out, we withhold money equal to `participants.giving` in order to cover next week's tips. This leads to unexpected behavior when cashing out 1.0 balances (#3481). Are we ready to drop holdovers (#3475)?

**Comment by whit537** [comment]
I believe someone in the `pending-payout` state will stay there indefinitely until their balance reaches zero.

**Comment by rohitpaulk** [comment]
> Are we ready to drop holdovers (#3475)?

Is that what's required here? The problem here is the condition that updates the `pending-payout` state - it should be 'has been paid out once', rather than 'has a balance of zero'.

**Comment by whit537** [comment]
Holdovers are gone in #3629.
