### ISSUE TITLE
"Your credit card is about to expire!" banner shows falsely.

### ISSUE THREAD

**Issue by YorikSar** [gratipay/gratipay.com#3553]
When I login, I see red "Your credit card is about to expire!" banner on top of the page. If I follow the link in it, I can see that my card is due to be expired in 2 years.

**Comment by whit537** [comment]
Hmm ... thanks for the report, @YorikSar.

**Comment by whit537** [comment]
!m @rohitpaulk 

Can you confirm, @YorikSar?

**Comment by YorikSar** [comment]
I've logged in to gratipay and saw that message once again. I followed the link, verified that the card there won't expire for more than a year, and... I don't see that message again. I guess it was some old notification stuck in the system somewhere.

**Comment by rohitpaulk** [comment]
> I guess it was some old notification stuck in the system somewhere.

Yes, true. We mark notifications as 'read' when you click on the link in them/close them. The root cause has been fixed, so you shouldn't see this anymore :) (hopefully)
