### ISSUE TITLE
Forte for payment processing (including ACH)?

### ISSUE THREAD

**Issue by catskul** [gratipay/gratipay.com#3554]
https://www.forte.net/

**Comment by whit537** [comment]
Thanks, @catskul!

**Comment by whit537** [comment]
Called, no answer.

**Comment by whit537** [comment]
I filled out their contact form.

**Comment by whit537** [comment]
> Thank you for your inquiry to Forte Payment Systems.
> 
At this time we are not accepting merchants in your industry.  If this should change in the future, we will gladly notify you back.
>
If you have further questions, please feel free to let me know.
