### ISSUE TITLE
SSL Cert not fully trusted by Chrome

### ISSUE THREAD

**Issue by catskul** [gratipay/gratipay.com#3555]
Chrome's claims:

1. *''The identity of this website has been verified by StartCom Class 2 Primary Intermediate Server CA but does not have public audit records."*

2. *"The site is using outdated security settings that may prevent future versions of Chrome from being able to safely access it."* (the one causing the red strike through)

StartCom forum thread discussing topic and possible solutions:

https://forum.startcom.org/viewtopic.php?p=21511

Screenshot of issue:

![image](https://cloud.githubusercontent.com/assets/375302/8143088/40254086-1168-11e5-8b3d-0b242b6c9892.png)

**Comment by whit537** [comment]
Sounds like a dupe of https://github.com/gratipay/gratipay.com/issues/3278. What version of Chrome are you using, @catskul?

**Comment by whit537** [comment]
Closing as a dupe of #3278.
