### ISSUE TITLE
retry cards a second week in some cases

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3558]
Reticketing from https://github.com/gratipay/gratipay.com/issues/3531:

> As for retrying declined cards, it does depend on the decline reason. You'll be able to view the decline reasons on the transaction page under "Processor Response Text" in the "Transaction Information" section. If the decline reason is one such as insufficient funds, or a generic decline with a reason code of 2046, we suggest trying the card again the next day. If it would decline after that, we suggest reaching out the cardholder directly to resolve the issue. However, if for another reason, such as Expired Card or Invalid credit card number, we suggest not retrying these declines and reaching out to cardholder directly to resolve it. You can see the decline reasons on the transaction page under Feel free to hover over the question mark for more detailed information about the decline.
##

**Comment by nobodxbodon** [comment]
Merging similar thoughts [retry on Fridays](https://github.com/gratipay/gratipay.com/issues/1637)
