### ISSUE TITLE
Woodgrain backgrounds look dumb and skeumorphic

### ISSUE THREAD

**Issue by timothyfcook** [gratipay/gratipay.com#3569]
: ) 

Sorry, but I think the site design would come off a lot cleaner if the layer with the wood/pennies background was removed or altered. The pennies might be okay, but the wood-grain comes off all wrong.

**Comment by kzisme** [comment]
Do you have any specific alteration suggestions?  I like the idea of the penny personally - mainly because it represents a monetary denomination.  The heart cut-out also works well for me - it makes even more sense after reading our (http://inside.gratipay.com/big-picture/mission) [Mission Statement](http://inside.gratipay.com/big-picture/mission).  

Other than that I'm not sure where the inspiration came from for the wood-grain.  It could be re-vitalized I suppose

**Comment by timothyfcook** [comment]
Yeah I think the wood-grain just happened to the context for the photo of the pennies that was taken.

I suggest either:

- a digital animation of the heart-coins with no background
- a new photo background that isn't set on top of wood

**Comment by techtonik** [comment]
My biggest complain about background is the huge 200kB jpeg.

**Comment by kzisme** [comment]
This may be considered completely off the wall, but if there is a push for a website re-design (whenever 2.0 releases) - I would like to see the color scheme stay the same, but using the heart-coin as a centerpiece.

**Comment by techtonik** [comment]
Before pushing for the new design, I would enjoy exploring the archive of previous art. But.. we don't have any.

**Comment by kzisme** [comment]
No previous art has existed, or is it just not archived?

**Comment by rohitpaulk** [comment]
Everything that ever existed is archived, that's why we use version control. I guess what @techtonik is saying is that it's not in a readily viewable format (like a bunch of images).

**Comment by techtonik** [comment]
@rohitpaulk yes. =)

**Comment by kzisme** [comment]
Ah thanks for the clarification @rohitpaulk

**Comment by kzisme** [comment]
@timothyfcook I suppose the wood grain was chosen since Ambridge used to be called Logstown - but that's a long-shot, and a lot of speculation :laughing:

**Comment by techtonik** [comment]
Ideally the image archive should be clickable, like in InVision #3270 

Web archive, unfortunately, was unable to get pages after user authorization https://web.archive.org/web/20140906122043/https://gratipay.com/

**Comment by whit537** [comment]
Dig through the blog, we have some posts there with old screenshots.

**Comment by timothyfcook** [comment]
Just for fun, here's an ancient attempt at an un-used design sketch:

![gittip mockup](https://cloud.githubusercontent.com/assets/1823300/8259692/7069129e-168c-11e5-8449-a3d46a95d2ed.png)

**Comment by whit537** [comment]
!m @timothyfcook :dancer:

**Comment by techtonik** [comment]
Yes! =)

**Comment by nobodxbodon** [comment]
Fixed by https://github.com/gratipay/gratipay.com/pull/4268
