### ISSUE TITLE
Create a gallery of Gratipay site designs and artwork

### ISSUE THREAD

**Issue by techtonik** [gratipay/gratipay.com#3571]
From https://github.com/gratipay/gratipay.com/issues/3569#issuecomment-113589836

Two questions:
1. Where should it be stored
2. How to name the files

**Comment by webmaven** [comment]
Suggested answers:
 1. Create a new repo gallery.gratipay.com using static site generator of your choice, and host said static site on GitHub.io.
 2. Use whatever scheme is convenient for the static site generator.

**Comment by whit537** [comment]
I suggest adding this to Inside Gratipay.
