### ISSUE TITLE
"You pay $N per week" doesn't agree with Subscriptions

### ISSUE THREAD

**Issue by noffle** [gratipay/gratipay.com#3572]
On my account page it claims "You pay $2.10 per week", though under Subscriptions all I see is a $0.10 / week subscription to Gratipay.

According to my history, my $2.10 / week payments stopped going through as of April 30 2015. My credit card information looks up to date.

**Comment by whit537** [comment]
Sorry for the trouble, @noffle. I've added +1s for you to #3511 and #3455. Closing this as a dupe.
