### ISSUE TITLE
Couple questions

### ISSUE THREAD

**Issue by gerroon** [gratipay/gratipay.com#3574]
Hi

I was interested to donate to couple projects but I have some questions concerns.

- I will never accept any donation, therefore I feel like I should never provide my Paypal email to you. You should be able to do Paypal pays like everyone else, that is the whole point of Paypal so I do not provide any details and other things to do my payments. I solely rely on Paypal to handle the privacy and pays.

- I am only interested in donating here and there and recurring donations is not sustainable to me. It is not clear to me how it can be done with your service. Maybe make it clear on the site?

thanks

**Comment by whit537** [comment]
>  I will never accept any donation, therefore I feel like I should never provide my Paypal email to you. You should be able to do Paypal pays like everyone else, that is the whole point of Paypal so I do not provide any details and other things to do my payments. I solely rely on Paypal to handle the privacy and pays.

I believe this is a +1 for https://github.com/gratipay/gratipay.com/issues/63, yes?

> I am only interested in donating here and there and recurring donations which is not sustainable to me. It is not clear to me how can be done with your service. Maybe make it clear on the site?

This is #5.

**Comment by gerroon** [comment]
thanks for the follow up.
