### ISSUE TITLE
Startcom SSLs?

### ISSUE THREAD

**Issue by gerroon** [gratipay/gratipay.com#3575]
Ok this is a sticky topic and it is only my own personal observation. 

I realize that your resources are limited but I recommend you to find another SSL provider because you are using an SSL provider that is "StartCom is a company based in Eilat, Israel that has three main activities: StartCom Linux Enterprise (Linux distribution), StartSSL (Certificate Authority) and MediaHost (Web hosting)." It is from a state that engages in regular cyber hacking and cyber attack on others at state level and this by itselfs gives me the creeps anytime I see a website that uses StartCom certificates.

CAs are doomed business model I get it, none of it is really secure at any level but something better than Startcom SSLs is a better option in my view given that you seem to be able to access people's private repositories on GIthub which is a gold mine for state level hackers.

Here is how they felt about heartbleed (from the WIkipedia page again) which just shows how ill intentioned they are.

"
Response to Heartbleed

On 13 April 2014, StartCom announced[10] a FAQ page[11] related to Heartbleed, a critical bug in OpenSSL estimated to have left 17% of the Internet's secure web servers vulnerable to data theft.

StartCom's policy is to charge $25 for each revoked certificate, and it refused to waive this fee in lieu of certificates compromised due to Heartbleed, though some paying customers were granted a single free revocation.[12][13][14][15]"

thanks

**Comment by captn3m0** [comment]
<https://letsencrypt.org/>

**Comment by whit537** [comment]
> It is from a state that engages in regular cyber hacking and cyber attack on others at state level[.]

What state *doesn't* engage in cyber-warfare?

**Comment by gerroon** [comment]
Well sure, but when you get the cert from that state, you have no legal control over it. It sounds like you are in the States, therefor you might at least have some basic rights over the certs you own. And I am guessing that it would be quasi illegal for state to forge certificates of a US business.
