### ISSUE TITLE
on-site notification about Gratipay 2.1

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3584]
Suggested in https://gratipay.freshdesk.com/helpdesk/tickets/2405.

Gratipay 2.1: https://github.com/gratipay/gratipay.com/issues/3399#issuecomment-112110512.

Sending an email notification for Gratipay 2.1 is https://github.com/gratipay/inside.gratipay.com/issues/254.
##

**Comment by webmaven** [comment]
It would likely be helpful if the [gratipay](/gratipay/gratipay.com) and [inside.gratipay.com](/gratipay/inside.gratipay.com) repos were to have 2.1 milestones.
