### ISSUE TITLE
Can't see current contributions?

### ISSUE THREAD

**Issue by joelhooks** [gratipay/gratipay.com#3589]
http://cl.ly/image/0H431M3L250i

It says I am paying, but nothing shows up. What's up with that? I can't affect donations at all. This seems totally broken on my account.

**Comment by joelhooks** [comment]
I can't add new payments or see my existing ones, so I removed my card altogether. This makes me sad for the people I was contributing too...

I'd say 2.0 is "alpha" ;(

**Comment by whit537** [comment]
@joelhooks 2.0 is definitely alpha. :-( We had to rush it under pressure from [Balanced shutting down](https://medium.com/gratipay-blog/balancedshutdown-3a9fdb32e9c6)—a hard deadline—and the [legal issues](https://medium.com/gratipay-blog/gratipocalypse-42fd0ec0d9e8) that uncovered—a HUGE challenge. Now we're slowly chipping away at it. Check [The Radar](https://github.com/gratipay/inside.gratipay.com/labels/Radar) for weekly priorities and progress. Current shortlist is:

 - Work down our security queue (we had a flood of reports come in when [the HackerOne directory](https://hackerone.com/gratipay) went online).
 - Bring back account closing: #3461.
 - Clean up Subscriptions (#3511) and History (#3455) pages.

I've added +1s with your comments to #3511; closing this as a dupe.
