### ISSUE TITLE
No way to donate. UI missing

### ISSUE THREAD

**Issue by remy** [gratipay/gratipay.com#3590]
The ui is missing. Signed in and looking at other uses, there's no way to donate. Kind of important!

**Comment by mattbk** [comment]
+1, seriously.

**Comment by mattbk** [comment]
Does this comment clarify anything?  https://github.com/gratipay/gratipay.com/issues/3556#issuecomment-119217978

**Comment by whit537** [comment]
We do also have https://gratipay.com/explore/teams/. Sorry for the troubles, @remy. :-(

**Comment by whit537** [comment]
We do technically have UI for donating, it's just confusing as heck right now. Closing this as a dupe of #3556.
