### ISSUE TITLE
"The transfer to your bank account has failed!" banner

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3591]
This shows on my account, but clicking sends me to https://gratipay.com/~nplainsathletes/routes/bank-account.html, which is 404.  I have PayPal set up as a bank, and the last deposit (getting rid of the escrow, I assume) worked fine.

Is this a real error?

**Comment by whit537** [comment]
We shouldn't have tried to send money to your bank account. https://github.com/gratipay/gratipay.com/pull/3608 fixes the underlying issue. Do we need a repair?

**Comment by whit537** [comment]
Looks like #3598 is the repair ...

**Comment by whit537** [comment]
I've deployed #3598 and #3608. Can you confirm this is fixed and close, @mattbk?

**Comment by mattbk** [comment]
Confirmed fixed.
