### ISSUE TITLE
Migrating account to Gratipay

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3605]
> Hi, Gratipay!
>I've been a user of Tugboat Yards to process microdonations on my website for the past six months. Now that they are shutting down, I'm looking for an alternative.
>Right now I have four subscribers (in addition to one-off donors), whose subscriptions work on a monthly or annual basis.
>Is there any way to migrate those subscriptions into a gratipay account--without undue stress on my or my kind subscribers?
>Please let me know.
>Thank you,

https://gratipay.freshdesk.com/helpdesk/tickets/2485

I assume that migrating subscribers would be impossible without their consent, but I wanted to put this out there as a question that has been asked.

**Comment by whit537** [comment]
@mattbk Yeah, I'm not sure how this would work. We would need payment information from the subscribers, which we couldn't get without their consent as well as cooperation from Tugboat Yards. :-(

**Comment by whit537** [comment]
Gonna go ahead and close this. Can I let you respond on Freshdesk, @mattbk?

**Comment by mattbk** [comment]
Responded and closed on Freshdesk.
