### ISSUE TITLE
You can donate to your own team

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3607]
Not sure if this is a bug or not, but I'm not sure why you would want to donate money to your own team.  I guess this could be left as-is in the interest of letting people experiment with it.

**Comment by whit537** [comment]
Let's say you receive grant funding from some major foundations, and you want to use Gratipay's payroll feature to pay your team (once we bring that back). In that case you'd want to fund your Gratipay account yourself, eh?

I know @timothyfcook has expressed interest in this use case.

**Comment by kzisme** [comment]
@whit537 Is there a place (FAQ or something) where we can document this as a feature rather an an issue?

**Comment by mattbk** [comment]
It could be added to https://gratipay.com/about/faq.

**Comment by kzisme** [comment]
Do you think that would be regarded as a feature to more than one user though?

**Comment by whit537** [comment]
Maybe under https://gratipay.com/about/features/?

**Comment by kzisme** [comment]
I would agree that it would be considered a feature and could be added there what are your thoughts @mattbk

**Comment by mattbk** [comment]
I do not have a problem with adding it there.

**Comment by mattbk** [comment]
This no longer looks possible to me. Closing.
