### ISSUE TITLE
migrating tips when already migrated

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3609]
Reticketed from https://github.com/gratipay/gratipay.com/issues/3592#issuecomment-118201780.

> > Why did we migrate tips for some teams that already had tips migrated? Shields, kivy ...
> 
> That's a bug, looks like it happens when there are no tips to migrate.
##

**Comment by mattbk** [comment]
Are tips being migrated when new teams are approved?  Can you point me somewhere we mention this?

**Comment by whit537** [comment]
> Are tips being migrated when new teams are approved? Can you point me somewhere we mention this?

Yes. It's mentioned in point three under "Getting Back on Track" on [Gratipay 2.0](https://medium.com/gratipay-blog/gratipay-2-0-2453d3c53077):

> If we approve your application, we will migrate the weekly payments from your Gratipay user account to your new Gratipay Team, and you’ll start receiving them as the owner of the team instead of receiving them directly. Your next payout will include any balance you’ve accumulated on Gratipay to date.

Recent paydays include the log output for this step on their respective tickets: https://github.com/gratipay/gratipay.com/search?q=run+gratipay&type=Issues&utf8=%E2%9C%93.

**Comment by whit537** [comment]
Is this possibly overwriting tips that have been said after the first migration?

**Comment by whit537** [comment]
Based on https://github.com/gratipay/gratipay.com/issues/3656#issuecomment-126440082, my hypothesis is that next week (166) we'll see "already migrated" for `zed` and `gkz-open-source`, and "0 tip(s)" for `matlab-schemer`.

**Comment by whit537** [comment]
Confirmed: https://github.com/gratipay/gratipay.com/issues/3669#issuecomment-128360874.
