### ISSUE TITLE
giving link from email is 404

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3610]
(Is this a dupe?)

![screen shot 2015-07-09 at 1 42 14 pm](https://cloud.githubusercontent.com/assets/134455/8602451/66288152-2640-11e5-8fe9-14bb6206c283.png)

Links to https://gratipay.com/~whit537/giving/, which is 404.
##

**Comment by nobodxbodon** [comment]
https://gratipay.com/~nobodxbodon/giving/ works now. Guess not reproducible.
