### ISSUE TITLE
implement a Team history page

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3612]
Reticketed from @mattbk at https://github.com/gratipay/gratipay.com/issues/3455#issuecomment-119667200, and somewhere else, too. :-)
#### Notify
- [ ] https://gratipay.freshdesk.com/helpdesk/tickets/3007
##

**Comment by benhc123** [comment]
Definitely a good idea.

**Comment by whit537** [comment]
+1 @anselmh in #3756.

**Comment by mattbk** [comment]
+1 from https://gratipay.freshdesk.com/helpdesk/tickets/3007

**Comment by whit537** [comment]
Copying from @fenryxo at https://github.com/gratipay/gratipay.com/issues/3800#issuecomment-144336521:

> it would be great to have a dashboard similar to Patreon's one to provide teams with information about progress. For example:
>
1. We are charging your patrons. It can take up to X days. $100 pledged by 25 patrons, $50 processed so far by 20 patrons.
1. We are transferring money for payout. $100 pledged by 25 patrons, $80 processed by 23 patrons. (2 declined)
1. We have sent you $90 ($10 fee). It can take up to X days. $100 pledged by 25 patrons, $80 processed by 23 patrons.

**Comment by whit537** [comment]
@fenryxo Got a screenshot? :-)

**Comment by fenryxo** [comment]
Patreon - Dashboard
![patreon_dashboard_0](https://cloud.githubusercontent.com/assets/853706/10195458/00deeb12-678e-11e5-9ce8-bae40ed4485f.png)

Patreon - Patron Manager entry
![patreon_manager_entry](https://cloud.githubusercontent.com/assets/853706/10195592/b184138e-678e-11e5-87f8-57bf226c5a55.png)

Patreon - Transactions - example of in/out transaction pair (the worst case was 8 days delay)
![patreon_transactions](https://cloud.githubusercontent.com/assets/853706/10195726/5fe7547c-678f-11e5-9bda-b241611935db.png)

**Comment by mattbk** [comment]
I like this idea, but can we please have it be a table of some sort instead of a stream?  It's easier to read if you are looking for errors, and easier to copy/paste out if you need to keep records.

**Comment by mattbk** [comment]
From #3799:

>>[M]ight it make sense to have pledged donations show up in the history?

>Yeah, I think so.

https://github.com/gratipay/gratipay.com/issues/3791#issuecomment-141784138

It's confusing to users to see "receiving x.xx" but not get a payout of that amount every week.  Adding pledged amounts to the history would alleviate this (but then we'd need to explain what pledges are).

**Comment by mattbk** [comment]
How do we keep track of pledges right now?  Is it just a table of tippee:amountperweek?

**Comment by whit537** [comment]
@mattbk It's a `due` field in the `payment_instructions` table.

**Comment by mattbk** [comment]
Note to self, look at whatever file does the calculations for for this

![image](https://cloud.githubusercontent.com/assets/3729038/10251922/cba1d06e-68f9-11e5-937b-a586ae2fc97d.png)

to better understand what could be pulled from for a history page.  I may not be much help in implementing it, but I want to know how the db relationships work.

**Comment by whit537** [comment]
+2 from @anselmh @book in https://github.com/gratipay/gratipay.com/issues/3756 for communicating due/owed on the Team history page.

**Comment by whit537** [comment]
+1 @dhct00 in https://github.com/gratipay/gratipay.com/issues/3858.

**Comment by whit537** [comment]
Bump. One of four left on Finish Team Basics. You're self-assigned @rohitpaulk. Still interested?

**Comment by rohitpaulk** [comment]
I'm interested - but I've removed my assignment for now, so that someone else can pick it up if they want to before I get to it :)

**Comment by kaguillera** [comment]
Considering taking this up... @rohitpaulk me know if you started it anything as yet.

**Comment by rohitpaulk** [comment]
Haven't started @kaguillera :)

**Comment by kaguillera** [comment]
So while working on this I realized that I need/should/want to clean/update `fake_data.py` so that I can visually design and test the page that this ticket should produce. So I am going to work on that first in a separate PR and then come back to this. Hopefully the `fake_data.py` cleanup should not take long. 

Oh but I have started working on this...

**Comment by kaguillera** [comment]
I just noticed https://github.com/gratipay/gratipay.com/pull/3596 and that I had this in mind before. So I will use this PR (hopefully) to make the necessary changes.

**Comment by kaguillera** [comment]
Ok https://github.com/gratipay/gratipay.com/pull/3596 is up for review so I am coming back to this. I would like https://github.com/gratipay/gratipay.com/pull/3596 to be merged before I do this but I think that I can move ahead and make some progress in the mean time. So when https://github.com/gratipay/gratipay.com/pull/3596 does finally get merged this should be close behind.

**Comment by mattbk** [comment]
https://github.com/gratipay/gratipay.com/pull/4128

**Comment by kaguillera** [comment]
Thanks for the reference @mattbk I should have done that... 😦

**Comment by whit537** [comment]
Moving to PR in #4128.
