### ISSUE TITLE
Make it clear that team applications become team pages

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3613]
+1 from https://twitter.com/rem/status/619243805217177600

I was unaware of this as well when I applied.  Although Gratipay defaults to open everything, people should know that first rather than finding out after submission.

**Comment by whit537** [comment]
> Didn't realise Team Requests would be used for public pages, that said, its consistent with @js_bin's open policies https://gratipay.com/jsbin/

**Comment by whit537** [comment]
Good point. Here's a quick PR: #3614.
