### ISSUE TITLE
No verification email after adding new email address

### ISSUE THREAD

**Issue by severoon** [gratipay/gratipay.com#3622]
When I add a new email address that references a list, no verification email is sent to that address. (When I add my personal email address, I do receive it.)

For my organization, I would like to receive emails at a list (does not go to one particular individual) using the following format: payment+gratipay@example.com. When I add this address, though, no email is sent.

I also tried removing the "+" style syntax, but payment@example.com doesn't work either. (My personal address in the same domain does work.)

This email address is a Google group managed by a Google Groups in a Google Apps for Nonprofits domain. I've checked the spam folder to make sure the verification emails weren't going there, but as far as I can tell, they're just not getting sent at all.

Thanks!
##

**Comment by whit537** [comment]
Weird. We do have issues with `+` in emails (#3110), but you say you are having the problem even without that.

**Comment by whit537** [comment]
@severoon I'm not finding your Gratipay account here: https://gratipay.com/on/github/severoon/. Would you mind linking to it here? If you don't want to share it publicly then feel free to privately email support@gratipay.com.

**Comment by mattbk** [comment]
This issue is https://gratipay.freshdesk.com/helpdesk/tickets/2624 on Freshdesk.

**Comment by whit537** [comment]
I *am* finding the [messages in Mandrill](https://mandrillapp.com/activity?q=sanbrunoedfound&date_range=90), and it looks like they "soft-bounced." Mandrill stores info for rejected messages for 90 days (30 days for delivered messages).

"[What Happens If An Email Bounces?](https://mandrill.zendesk.com/hc/en-us/articles/205582937-What-happens-if-an-email-bounces-)"

**Comment by whit537** [comment]
"[What Is A Bounce?](https://mandrill.zendesk.com/hc/en-us/articles/205583047-What-is-a-bounce-)"

**Comment by whit537** [comment]
"[How Do I View Details For Bounced Emails In Mandrill?](https://mandrill.zendesk.com/hc/en-us/articles/205583027-How-do-I-view-details-for-bounced-emails-in-Mandrill-)"

**Comment by whit537** [comment]
> In addition to a general bounce description or error message, Mandrill also stores raw bounce details for individual messages for 7 days for more in-depth troubleshooting.

@severoon Any chance you could retry adding your address so we can capture the raw bounce details?

**Comment by severoon** [comment]
Done!

**Comment by whit537** [comment]
@severoon Huh. Mandrill shows that it's delivered. Are you seeing it, or is Mandrill just being optimistic and we should wait a while? :)

**Comment by severoon** [comment]
@whit537 Strange...I tried resending the verification email and removed and re-added the email address with the + notation, and got nothing.

I tried an experiment where I just removed the + part of the email address, and that came through within a few minutes. (I've since removed that address b/c I'd prefer to use the one with +notation if possible.)

This is going to a Google Groups for Business group (which is running as part of a Google Apps for Nonprofits account). The no-+ version went straight through, and I've checked pending messages for the group to see if the + one get flagged as spam, but as far as I can tell it never arrived in the group.

I did another experiment where I emailed the + address directly. Oddly, it got delivered to the members of the group (including me), but doesn't show up in the Google Groups UI for that group.

So something weird is going on here, and it might not be on the Gratipay side. However, at the very least I would expect the + notation sent from Gratipay to be handled the same as the email I sent to that same address, i.e., I can't understand why I wouldn't receive the former but did receive the latter, even if it didn't get posted to the group...any ideas?

**Comment by severoon** [comment]
@whit537 Ah, scratch that! The test email I sent to the + address eventually got delivered, it just took a lot longer. I suspect Google Groups does more extensive spam filtering on it or something, but it did show up after 15-20 minutes in the group (though it was delivered to me as a member of the group much sooner).

So, to summarize:
- when I send email to our address with or without the + notation, everything works as expected
- when I try to round trip our email without + notation on our Gratipay account, it arrives as expected
- when I try to round trip our email with + notation on our Gratipay account, it never arrives

**Comment by whit537** [comment]
I've captured the bounce message and have [stored it privately](https://gratipay.freshdesk.com/helpdesk/tickets/2624).

**Comment by whit537** [comment]
Here's the relevant bit:

> Hello support@gratipay.com,
>
We're writing to let you know that the group you tried to contact (donation) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:
>
 * You might have spelled or formatted the group name incorrectly.
 * The owner of the group may have removed this group.
 * You may need to join the group before receiving permission to post.
 * This group may not be open to posting.
>
If you have questions related to this or any other Google Group, visit the Help Center at [https://support.google.com/a/topic/25838].

**Comment by whit537** [comment]
I sent test messages from support@gratipay.com (using Gmail directly, not Freshdesk or Mandrill), to both + and non-+ addresses. Let's see what those do ...

**Comment by nobodxbodon** [comment]
Obsolete. Sounds like a permission issue. Please reopen or re-ticket if the same happens again.
