### ISSUE TITLE
port to ArnoldC

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3623]
https://github.com/lhartikk/ArnoldC

h/t @hurlothrumbo

**Comment by rohitpaulk** [comment]
+1

Let's write Schwaspen too :P

**Comment by whit537** [comment]
Hmmm ... not sure it has an eval. @pjz Can you make a PR for us?

**Comment by techtonik** [comment]
Arnoldsey rocks1 =)

**Comment by pjz** [comment]
Sure, right after Intercal.

**Comment by whit537** [comment]
> INTERCAL statements all start with a "statement identifier"; in INTERCAL-72, this can be DO, PLEASE, or PLEASE DO, all of which mean the same to the program (but using one of these too heavily causes the program to be rejected, an undocumented feature in INTERCAL-72 that was mentioned in the C-INTERCAL manual)

https://en.wikipedia.org/wiki/INTERCAL

lol

**Comment by whit537** [comment]
Should we adopt the Google style guide?

http://cadie.googlecode.com/svn/trunk/INTERCAL-style-guide.html

**Comment by whit537** [comment]
![7866272514_7743c93ccc_b](https://cloud.githubusercontent.com/assets/134455/8753113/fce5b9e2-2c86-11e5-8724-12d1c3ecf93d.jpg)
