### ISSUE TITLE
/me redirects to /~me

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3625]
According to http://inside.gratipay.com/howto/support-users (which is very helpful), 

> Use about/me/* URLs wherever you can. Providing users with a link to their settings page is better than asking them to find it on their own. This works for history pages and profiles too.

but /me/settings currently redirects to /~me/settings, etc., which does not seem like the correct behavior.

**Comment by mattbk** [comment]
Never mind, I missed /about.

**Comment by whit537** [comment]
!m @mattbk
