### ISSUE TITLE
Link on Pricing page goes to 404

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3628]
"People" should go to "Teams" now, anyway.

https://github.com/gratipay/gratipay.com/blob/87b3966f8d9849f6929b6e3aa63b9516595d03d9/www/about/pricing.spt
`  <p>Your payments cover hosting and other costs of doing business, and the
    rest goes to the <a
    href="https://gratipay.com/Gratipay/members/">people</a> who are building
    Gratipay for you.`

**Comment by mattbk** [comment]
Notes for later. http://inside.gratipay.com/howto/build-gratipay

**Comment by mattbk** [comment]
I closed this because I opened a PR at https://github.com/gratipay/gratipay.com/pull/3631, not sure if that was the right way to do it.

**Comment by mattbk** [comment]
Opening because I didn't read closely enough.

**Comment by whit537** [comment]
@mattbk I propose that for now we just unlink "people," to be relinked once we bring back payroll (#3433).
