### ISSUE TITLE
How to subscribe to a person?

### ISSUE THREAD

**Issue by leberknecht** [gratipay/gratipay.com#3630]
Hi! I just dont get how to spend money to someone ^^ So i want to give like 5$ per week or something to this guy: https://gratipay.com/~skeelogy/ as i think hid did a great job on skunami.js. So i'm logged in now, i've a verified credit-card and paypal attached but i still dont see any CTAs to give him money or charge my account (do i have to manually?). 

I feel a bit lost in the usability :)

**Comment by mattbk** [comment]
It is confusing right now.  With [Gratipay 2.0](https://medium.com/gratipay-blog/gratipay-2-0-2453d3c53077) we switched to a system where you can only donate to [teams](https://gratipay.com/explore/teams/), not individuals.  Unfortunately, this user has not  applied for a team yet, so he can't receive donations.

If you'd like to donate to him using Gratipay, please let him know and encourage him to [apply for a team](http://gratipay.com/new).

**Comment by leberknecht** [comment]
Actually, i asked him to do so. He was not able to figure out how to create a team. So in the end he sent me his btc adress ... :/

**Comment by whit537** [comment]
Sorry, @leberknecht. :-(

We don't have a UI for applying for new teams yet. We're trying to clean up a few more things before generally advertising that. Currently one has to go to this direct link:

https://gratipay.com/new

**Comment by mattbk** [comment]
My suggestion [here](https://github.com/gratipay/gratipay.com/issues/3560#issuecomment-123363444) might clear things up for people.
> I think it would be appropriate to add the list of Teams they are on to the sidebar in place of the donate button. Then the UX is the same, regardless of what type of page you are looking at: if you want to donate, look left under the avatar.

Additionally, we would need to provide a "This user is not part of any teams, and cannot ~~receive~~ [take](https://github.com/gratipay/inside.gratipay.com/issues/117#issuecomment-126369596) money" text if there are no teams to show.

**Comment by mattbk** [comment]
Also, we're moving away from "subscribing" and back to "giving" (https://github.com/gratipay/inside.gratipay.com/issues/117).

**Comment by whit537** [comment]
I'm not seeing an action item on this ticket. Closing. Reopen if I'm missing it ...

**Comment by ntnsndr** [comment]
Forgive me for opening this up again, but just for clarity: I want to give regularly to an individual, a writer (not an open team). Is that something I can do on Gratipay, or would I have to use Patreon?

**Comment by mattbk** [comment]
>I want to give regularly to an individual, a writer (not an open team). Is that something I can do on Gratipay [...]?

At the moment, no. We are working on allowing "teams of one" (individuals) who are providing a product or service _without_ using Gratipay for payroll ([more information(https://github.com/gratipay/inside.gratipay.com/issues/432)). This would be the use case you are talking about. This person would still be required to apply for a team (they could name it "Team Jane the Writer" and be the only member) and go through [review](http://inside.gratipay.com/howto/review-teams). In that review link, what we're talking about in https://github.com/gratipay/inside.gratipay.com/issues/432 is to get rid of the first requirement.

**Comment by ntnsndr** [comment]
Thanks, @mattbk. So, just to be clear, this use-case is currently not possible? To be specific, here's what I'd like to do: Create an account for a friend, who is a writer who needs to get paid to write, and then transfer it to him on his birthday; then encourage lots of his friends to join Gratipay and donate to him. The main point is that he is not a team. But I do like the idea that Gratipay might encourage him to be transparent about actually using the time he's being paid for for writing.

I need to make this happen this week, so let me know whether this is currently an option, either way. If so, I'll get started on the application process.

**Comment by mattbk** [comment]
@ntnsndr, I think this is a great use-case and perfect example of why we need to finish  gratipay/inside.gratipay.com#432 by making open work and payroll optional. I think @whit537 needs to make any sort of call here.

**Comment by ntnsndr** [comment]
Thanks. @whit537 what do you say? Is this possible this week?

**Comment by whit537** [comment]
Gosh, I really want to say yes to this! :-)

Let me think through what that would mean, and how we could maybe pull this off ...

**Comment by kzisme** [comment]
This would be really cool - a few months back I remember us getting a handful of requests for this functionality. :dash:

**Comment by whit537** [comment]
@ntnsndr Okay, worked this through in the [context](https://github.com/gratipay/inside.gratipay.com/issues/794#issuecomment-243195098) of our product roadmap  and the [ticket](https://github.com/gratipay/inside.gratipay.com/issues/432#issuecomment-242988591) where we've been hashing this out over the past nine months. The short answer is that yes, we're _willing_ to do this—the question is whether we'll be _able_ to on such short notice! Mostly I think it's a legal issue: right now our [terms of service](https://gratipay.com/about/policies/terms-of-service) are written in terms of "a platform to enable Teams of Gratipay Participants to receive payments to fund Open Work." Let me give our lawyer a call here ...

**Comment by whit537** [comment]
Alright, made contact. I'm following up with an email, and expecting a call back later today, or tomorrow.

**Comment by ntnsndr** [comment]
Awesome, thanks! Keep me posted. The person I'm doing this for is fairly popular, so I think this could very Mich be worth your while. 

Again, I think the model of open work can be applied to individuals if it is focused on transparency in process and accountability. 


On August 29, 2016 2:52:30 PM MDT, Chad Whitacre <notifications@github.com> wrote:
>Alright, made contact. I'm following up with an email, and expecting a
>call back later today, or tomorrow.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/gratipay/gratipay.com/issues/3630#issuecomment-243252262

∴
Nathan Schneider
nathanschneider.info

**Comment by whit537** [comment]
Thanks @ntnsndr. If we can move forward without changing our terms of service then that will be the best case. If we do have to change our ToS then we still may be able to get this done. More as I have it!

> I think the model of open work can be applied to individuals if it is focused on transparency in process and accountability.

We work with [specific definitions](http://inside.gratipay.com/big-picture/brand/) of "open" as "sharing control" and "transparent" as "sharing information." I think there's some interesting possibilities for writers to open up their process to influence from their "superfans" (think, drafting in public—you may very well know of cases along these lines already). I think Gratipay will be more effective overall if we accept customers without _requiring_ the highest transparency and openness, while still _encouraging_ movement in that direction, as safety and consent allow. Thanks for experimenting with us! :-)

**Comment by ntnsndr** [comment]
Rad. In this use case, we couldn't require open drafting, because it may conflict with publisher relationships. But I think some documentation of work and progress would be fair accountability to payers. A time sheet at the least, or a at most open drafting or task management. 


On August 29, 2016 3:25:36 PM MDT, Chad Whitacre <notifications@github.com> wrote:
>Thanks @ntnsndr. If we can move forward without changing our terms of
>service then that will be the best case. If we do have to change our
>ToS then we still may be able to get this done. More as I have it!
>
>> I think the model of open work can be applied to individuals if it is
>focused on transparency in process and accountability.
>
>We work with [specific
>definitions](http://inside.gratipay.com/big-picture/brand/) of "open"
>as "sharing control" and "transparent" as "sharing information." I
>think there's some interesting possibilities for writers to open up
>their process to influence from their "superfans" (think, drafting in
>public—you may very well know of cases along these lines already). I
>think Gratipay will be more effective overall if we accept customers
>without _requiring_ the highest transparency and openness, while still
>_encouraging_ movement in that direction, as safety and consent allow.
>Thanks for experimenting with us! :-)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/gratipay/gratipay.com/issues/3630#issuecomment-243261521

∴
Nathan Schneider
nathanschneider.info

**Comment by whit537** [comment]
Okay! I caught up with our [lawyer](https://github.com/copiesofcopies) ([private ticket](https://github.com/gratipay/legal-tor-ekeland/issues/31)). We're clear to waive the first, "open work" criterion of [our current Team Review policy](http://inside.gratipay.com/howto/review-teams) as a special case, with the caveat that it's not "clean." Doing so doesn't introduce a compliance risk for Gratipay: it doesn't violate any external legal requirement that Gratipay is under, but merely relaxes one of our _own_ requirements.

Rather, this introduces some risk for the _receiver_ in question, since technically they'll be violating our current [Terms of Service](https://gratipay.com/about/policies/terms-of-service) ("The Service is a platform to enable Teams of Gratipay Participants to receive payments to fund Open Work. Open Work means that [etc., etc.]"). Our [intention](https://github.com/gratipay/inside.gratipay.com/issues/432) is to relax our Terms to explicitly allow for cases such as this one, but we haven't yet. I think we could get that done pretty easily within a month or three. We _could_ get it done inside a week if absolutely necessary.

@ntnsndr Do you need us to get the ToS rewritten before proceeding? Or would you and your friend be comfortable proceeding with a special waiver, on the understanding that we'll rewrite the Terms "soon"?

That's one question.

The second question is one of consent: does your friend know about this plan, or is it supposed to be a birthday surprise? We [learned early on](https://github.com/gratipay/gratipay.com/issues/28) that it's not right for us to collect money on someone else's behalf without their consent. This is a bit of a different situation, but if you haven't already gotten your friend's permission then we should probably talk that through before deciding to proceed.

**Comment by mattbk** [comment]
> Rather, this introduces some risk for the _receiver_ in question, since technically they'll be violating our current Terms of Service ("The Service is a platform to enable Teams of Gratipay Participants to receive payments to fund Open Work. Open Work means that [etc., etc.]").

Gratipay could provide a letter stating the exemption. The real "risk" is that Gratipay could decide that this team doesn't meet TOS, which isn't actually super risky.

**Comment by ntnsndr** [comment]
Okay that sounds great! How do we do it?

On August 30, 2016 12:23:27 PM MDT, mattbk <notifications@github.com> wrote:
>> Rather, this introduces some risk for the _receiver_ in question,
>since technically they'll be violating our current Terms of Service
>("The Service is a platform to enable Teams of Gratipay Participants to
>receive payments to fund Open Work. Open Work means that [etc.,
>etc.]").
>
>Gratipay could provide a letter stating the exemption. The real "risk"
>is that Gratipay could decide that this team doesn't meet TOS, which
>isn't actually super risky.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/gratipay/gratipay.com/issues/3630#issuecomment-243532883

∴
Nathan Schneider
nathanschneider.info

**Comment by whit537** [comment]
@ntnsndr Sorry to harp ... :-(

> The second question is one of consent: does your friend know about this plan, or is it supposed to be a birthday surprise? We [learned early on](https://github.com/gratipay/gratipay.com/issues/28) that it's not right for us to collect money on someone else's behalf without their consent. This is a bit of a different situation, but if you haven't already gotten your friend's permission then we should probably talk that through before deciding to proceed.

**Comment by whit537** [comment]
I have an idea if you do want to keep it a surprise, but if it's already not a surprise then that's easier. Is it supposed to be a surprise? :)

**Comment by whit537** [comment]
(You can also just call me at 412-925-4220 if that's easier.)

**Comment by ntnsndr** [comment]
Thanks for all this! I'll talk it over with the friend and see that it works. I really appreciate your help with this. I hope we can make it happen.

**Comment by whit537** [comment]
> I'll talk it over with the friend and see that it works.

Awesome! Thank you. :-)

> Gratipay could provide a letter stating the exemption.

I think it makes the most sense for us to simply state the exemption in the team review ticket.

@ntnsndr If/when you're ready, go ahead and fill out [the "New Team" application](https://gratipay.com/new) as best you can. That will kick off a ticket in our Team Review repo (as [w/ IoO](https://github.com/gratipay/team-review/issues/174)), where we can state the exemption and otherwise fine-tune things as needed.

I'm looking forward to your [friend's] application, quite curious to see who this is! :-)

**Comment by whit537** [comment]
I think we've taken this as far as we need to. Our eye is out for a new team ticket. :)

**Comment by ntnsndr** [comment]
Yes, sorry I've been quiet about that:)

**Comment by whit537** [comment]
Take your time. We are standing by! :-)
