### ISSUE TITLE
Community lists show incorrect giving and receiving numbers

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3633]
Community pages (e.g., https://gratipay.com/for/javascript/) still show top givers and top receivers, but these are based on pre-2.0 giving and receiving values.  

![screen shot 2015-08-15 at 5 23 01 pm](https://cloud.githubusercontent.com/assets/3729038/9291073/5a3c617a-4372-11e5-9788-9926bfd6071f.png)

Stepping back, should community pages show top givers as ~users and teams, and top receivers as teams?  Can teams join communities yet?  I don't think communities should be scrapped, just brought up to date with everything else.

**Comment by whit537** [comment]
#3599 may handle this.

For bigger questions about communities, let's review the ticket about converting "communities" into "tags": #3127. Is that still something we want to do?

**Comment by mattbk** [comment]
Will be nullified when https://github.com/gratipay/gratipay.com/pull/3706 is committed.
