### ISSUE TITLE
"Account Type" no longer meaningful?

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3640]
With Gratipay 2.0, "Account Type" on the Settings page doesn't mean anything anymore, does it?  This is confusing now that we have old teams and new teams.
![screenshot_072315_110127_am](https://cloud.githubusercontent.com/assets/3729038/8855403/978c7ec0-312a-11e5-96cf-37de9e2b75fc.jpg)

Suggest it be removed from the UI.

**Comment by mattbk** [comment]
Created a PR because I could.  https://github.com/gratipay/gratipay.com/pull/3647

**Comment by whit537** [comment]
!m @mattbk
