### ISSUE TITLE
Receiving totals are incorrect in various places

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3643]
- [x] On https://gratipay.com/about/me/receiving/ (e.g., https://gratipay.com/~luke.leighton/receiving/) (link has been removed?)
- [x] User Dashboard (this has been removed?)
- [x] On https://gratipay.com/about/me/widgets (even if [widgets don't work](https://github.com/gratipay/grtp.co/issues/103), they are still there) (we have removed the widgets link from the UI #3673)

##### Notify
- [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2405
- [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2427

**Comment by mattbk** [comment]
Problem is in get_participant?

- Receiving page https://github.com/gratipay/gratipay.com/blob/master/www/~/%25username/receiving/index.html.spt
- Dashboard https://github.com/gratipay/gratipay.com/blob/master/www/~/%25username/index.html.spt
- Widgets page https://github.com/gratipay/gratipay.com/blob/master/www/~/%25username/widgets/index.html.spt

**Comment by mattbk** [comment]
Looks like the receiving on the dashboard has been removed.

**Comment by mattbk** [comment]
Also looks like the receiving page is gone entirely.  If you try to reach it directly, it gives error 500.

**Comment by mattbk** [comment]
Created PR to remove widgets link until they can be fixed: https://github.com/gratipay/gratipay.com/pull/3673.

**Comment by whit537** [comment]
Widget link is turned off in #3673. Are we good to close this ticket?

**Comment by mattbk** [comment]
Gratipay.com is clean, then; offsite widgets issue is at https://github.com/gratipay/grtp.co/issues/103.
