### ISSUE TITLE
History error: "automatic withdrawal —403 Forbidden"

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3644]
The following appears in the Notes column for some weeks for some users, along with status "failed," 

` automatic withdrawal —403 Forbidden, <p>You don't have the permission to access the requested resource. It is either read-protected or not readable by the server.</p> Your request id is [redacted].`

Is it possible that even though bank account deposits have been removed from the UI, they still exist in the database and the payday script?

##### Examples
- https://gratipay.com/~luke.leighton/history/ (Week 161, then quits)
- https://gratipay.com/~mix/history/ (Week 161, continues in PayPal)
- https://gratipay.com/~sudoroom/history/ (Week 161, continues in PayPal)
- https://gratipay.com/~catapultpgh/history/ (Week 161, continues in PayPal)
- https://gratipay.com/~sudomesh/history/ (Week 161, continues in PayPal)

##### Notify
- [x] https://gratipay.freshdesk.com/helpdesk/tickets/2405

**Comment by mattbk** [comment]
> What I think happened was that on Payday 161, bank account payouts were still in the payday script and failed for everyone, then PayPal payouts were processed.  Because you didn't have a PayPal account, nothing was processed--but this is something I need to keep looking into, and there definitely needs to be a warning for users without an attached PayPal account.

**Comment by whit537** [comment]
> What I think happened was that on Payday 161, bank account payouts were still in the payday script and failed for everyone

Bingo.

Given that, what's your suggested action item on this ticket, @mattbk?

**Comment by mattbk** [comment]
I think it's solved, future work would be toward #3526.  That quote above was my notification to the support inquiry.

**Comment by whit537** [comment]
Cool, thanks.

!m @mattbk
