### ISSUE TITLE
Broken link in Gratipay README

### ISSUE THREAD

**Issue by seowyanyi** [gratipay/gratipay.com#3649]
At https://github.com/gratipay/gratipay.com#help, the "make an issue" link is broken. It points to https://github.com/gratipay/gratipay.com/blob/master/gratipay/gratipay.com/issues/new but should be https://github.com/gratipay/gratipay.com/issues/new

**Comment by seowyanyi** [comment]
Pull request: #3650

**Comment by mattbk** [comment]
Looks merged.
