### ISSUE TITLE
export tips

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3651]
Tips are going away (under #3539). Good form would be to give people an export option.
##

**Comment by whit537** [comment]
We didn't land #3539. Tips are sticking around indefinitely.

**Comment by nobodxbodon** [comment]
As far as I understand https://github.com/gratipay/gratipay.com/issues/3539#issuecomment-146504936, the $28,402.62 was what's left of the escrow without knowing who to pay to. I suppose it will stay in our bank account until someone claims part of it somehow?

Besides, is the $130,000 the amount gratipay 1.0 owe receivers? Why the ~100k difference (130,000 - 28,402)?

**Comment by whit537** [comment]
The $28,402.62 was what was left "in our Balanced account." Our escrow is divided amongst several physical accounts, [currently two](http://inside.gratipay.com/howto/shuffle-escrow). Our current escrow liability is $106,742.58, per the [stats page](https://gratipay.com/about/stats) (once we [catch up our books](https://github.com/gratipay/finances/issues/3) then that number should reconcile with our balance sheet).

I think we can close this ticket.
