### ISSUE TITLE
Improve flow to attach PayPal when applying for a project

### ISSUE THREAD

**Issue by brylie** [gratipay/gratipay.com#3654]
Please add a link to instructions regarding how to add a bank account on the [team sign-up page](https://gratipay.com/new). This is a bit tricky to figure out.
##

**Comment by whit537** [comment]
Sorry for the confusion, @brylie. What's worse is that we don't actually offer bank payouts anymore; the only option we support is PayPal (see #3567). Our error message is not just unhelpful. It's a lie. :-(

![screen shot 2015-07-30 at 8 06 24 am](https://cloud.githubusercontent.com/assets/134455/8982718/f1882142-3691-11e5-9a4e-7ef9d0a6df24.png)

You can attach a PayPal account [on your Gratipay settings page](https://gratipay.com/about/me/settings/).

**Comment by brylie** [comment]
Thanks. PayPal is not a great option for me. I moved from the U.S. to Finland over a year ago, and PayPal will not let me connect my Finnish bank information. Perhaps some alternative funding sources would be advisable?

**Comment by whit537** [comment]
@brylie It will take some time, but we eventually hope to [establish a proper anti-money laundering (AML) program](https://github.com/gratipay/inside.gratipay.com/issues/119), at which point we'll be able to approach vendors who would allow us to move money more directly (e.g. #417 #3366).

**Comment by whit537** [comment]
+1 from https://github.com/gratipay/gratipay.com/issues/3859#issue-119580300

> @Gratipay To apply for a "team" (2.0???), I apparently need to link a PayPal account, but don't see the option to do so.

https://twitter.com/untitaker/status/670667868133019649
