### ISSUE TITLE
consider deleting old statements

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3660]
Reticketing from @mattbk at https://github.com/gratipay/gratipay.com/issues/3556#issuecomment-121306989:

> [I]t's confusing to not be able to give money to a person, especially when I can see a profile that may still (post 1.0) explain what this person is doing and where contributions will be used.
##

**Comment by mattbk** [comment]
An update to this: I don't see any giving/receiving numbers anywhere but on the community pages now (e.g., https://gratipay.com/for/javascript/).

**Comment by whit537** [comment]
Or turn them off in the UI but leave them around for people to salvage for parts later, as we did with the old Team form fields (#3694).

**Comment by whit537** [comment]
Haven't seen much traffic on this ticket. Still worth considering, @mattbk?

**Comment by whit537** [comment]
Closing. The confusion between participants and projects is better addressed on https://github.com/gratipay/gratipay.com/issues/3852.
