### ISSUE TITLE
explore the brand

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3665]
We've evolved a pretty stable [mission](http://inside.gratipay.com/big-picture/mission) and set of [brand values](http://inside.gratipay.com/big-picture/brand/) over the years. We've got a pretty solid understanding of who our [customers](http://inside.gratipay.com/big-picture/customers/) are, what [product]() we're building for them, and our basic [nomenclature](https://github.com/gratipay/inside.gratipay.com/issues/117). We've [tried for years](https://github.com/gratipay/gratipay.com/issues/3248#issuecomment-81365745) to figure out the visual design side of Gratipay, without much success. I think as a first step towards improving in this area, we should have some expert help exploring a number of visual possibilities for the Gratipay brand. We need some fresh, professional eyes.

**Comment by benhc123** [comment]
Agreed.

**Comment by elliottw** [comment]
I don't have a background in brand, but I did go to CMU for HCI. I think these days brand and "interaction style" are closely linked, so count me in if I can help.

**Comment by whit537** [comment]
Thanks @elliottw! :-)

**Comment by elliottw** [comment]
Speaking of interaction styles being on brand or not, I just posted this concept for interactive signup and donate widgets to be placed on project sites:
https://github.com/gratipay/gratipay.com/issues/3676

**Comment by whit537** [comment]
We can't afford professional design help right now (https://github.com/gratipay/inside.gratipay.com/issues/298) . :-(

Closing, to be reopened when we're further along.

**Comment by webmaven** [comment]
Hey @whit537, I have branding experience, I'd be willing to put in some time on that if you just want to make me part of the team (frankly, Aspen has been a disincentive to contributing as a developer).

**Comment by whit537** [comment]
Invite sent! :-)

**Comment by whit537** [comment]
> to be reopened when we're further along.

Reopening in light of https://github.com/gratipay/grtp.co/issues/103#issuecomment-229479424.

**Comment by whit537** [comment]
Design was Slack's [secret sauce](https://medium.com/@awilkinson/slack-s-2-8-billion-dollar-secret-sauce-5c5ec7117908) (according to its designers).

Also:

> In 1999 Jakob Nielsen listed **4 ways in which a website can [communicate trustworthiness](https://www.nngroup.com/articles/communicating-trustworthiness/)**: design quality, up-front disclosure, comprehensive and current content, and connection to the rest of the web. In our study, we observed that these very same factors continue to influence users.

https://www.nngroup.com/articles/trustworthy-design/ (two months ago)

**Comment by whit537** [comment]
I just had an intro meeting with a designer who also works here at [Catapult](https://gratipay.com/catapultpgh/) (and uses Gratipay to pay for his membership! :). He's going to get us a quote for this.

**Comment by whit537** [comment]
He got back to me with a quote, and we're aiming to discuss on the 25th. I need to talk to him about https://github.com/gratipay/inside.gratipay.com/issues/411 before saying more here.

**Comment by whit537** [comment]
Bouncing back over to https://github.com/gratipay/inside.gratipay.com/issues/298#issuecomment-242416375 before proceeding here.
