### ISSUE TITLE
Blog should be highlighted on website

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3670]
So people can look at changes without having to dig through github issues.

**Comment by whit537** [comment]
We do have it in the footer, but maybe something on the (currently non-existent) homepage?

**Comment by whit537** [comment]
@mattbk I added a new "star" area to highlight the 1.0 payout, and at first it linked to our blog post though now it links to a page on the site. You think it's a good idea to keep that around post-1.0-refund and use it for the most recent blog post?

![screen shot 2015-09-09 at 8 31 21 am](https://cloud.githubusercontent.com/assets/134455/9761847/2ecbb770-56cd-11e5-819c-f0b445b22ccd.png)

**Comment by mattbk** [comment]
I think that is a good idea.

**Comment by whit537** [comment]
Okay, let's go ahead and close this out, then, since we have that in place. :-)
