### ISSUE TITLE
Bring back bank account transfers

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3671]
I've seen this a few time, especially from people who don't want to use PayPal.  Maybe not right now, but someday.
##### Notify
- [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2445
- [ ] https://gratipay.freshdesk.com/helpdesk/tickets/2405
- [ ] https://github.com/gratipay/gratipay.com/issues/3654#issuecomment-127145743
- [ ] https://gratipay.freshdesk.com/helpdesk/tickets/3028
##

**Comment by whit537** [comment]
Blocking on https://github.com/gratipay/inside.gratipay.com/issues/119.

**Comment by mattbk** [comment]
+1 from https://twitter.com/failvarez/status/644672998088163328

> @failvarez
@Gratipay Hmm, just noticed that you guys are only accepting PayPal. Any plans to switch it up? Hard to support scum like that via fees.

**Comment by mattbk** [comment]
+1 from https://twitter.com/untitaker/status/645356580251283456

> @untitaker
@Gratipay Also I'd rather not need a Paypal account for this.
