### ISSUE TITLE
500 Internal Server Error on Pricing Page

### ISSUE THREAD

**Issue by thejimbirch** [gratipay/gratipay.com#3674]
https://gratipay.com/about/pricing

**Comment by whit537** [comment]
Thanks @thejimbirch, confirmed.

**Comment by whit537** [comment]
NB: This is only for [some class of] authenticated users.

**Comment by whit537** [comment]
https://beta.getsentry.com/gratipay/gratipay-com/group/74118370/

**Comment by whit537** [comment]
Should be fixed now, @thejimbirch. Can you confirm?

https://gratipay.com/about/pricing

**Comment by thejimbirch** [comment]
Confirmed, working now.

**Comment by whit537** [comment]
Cool, thanks @thejimbirch. :-)
