### ISSUE TITLE
get seven users signed up for PayPal

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3681]
Reticketed from https://github.com/gratipay/inside.gratipay.com/issues/310#issuecomment-130873328. We have seven approved teams where the owner doesn't have a PayPal linked for whatever reason (signed up with a bank account before #3567? removed their PayPal after signing up?).

**Comment by mattbk** [comment]
One of those users refuses to use PayPal (https://gratipay.freshdesk.com/helpdesk/tickets/2405).

**Comment by whit537** [comment]
I mean, if they don't have a PayPal linked then they're not receiving payments. Maybe they did that on purpose? If we don't want to go to the trouble of chasing everyone down then we could close here and wait for them to initiate contact. What's your preference, @mattbk?

**Comment by mattbk** [comment]
As long as the copy is clear on the website, it could be personal choice.

I don't see any notification after removing my PayPal account.  Maybe there should be one?

**Comment by stevepiercy** [comment]
I might fall into this category. I filed a FreshDesk ticket https://gratipay.freshdesk.com/support/tickets/2879

I think at the very least, a courtesy notification should go out.

**Comment by mattbk** [comment]
@stevepiercy, the issue your FD ticket addresses isn't because you don't have a PayPal address, it's because we haven't built a way to add team members (part of https://github.com/gratipay/gratipay.com/issues/3433).

**Comment by stevepiercy** [comment]
@mattbk At this moment, Team KnopProject has no PayPal account associated to it. When I first applied for it as a Team, I used an email address that had no PayPal account (and never will). My Individual email address should be associated with the Team.

**Comment by whit537** [comment]
@stevepiercy I see that Team KnopProject is owned by ~stevepiercy, and ~stevepiercy does have a PayPal account associated with it, with a payout last week. Does that mean you were able to get your account configured to your liking?

**Comment by stevepiercy** [comment]
@whit537 when I log in as ~stevepiercy and view my account profile, I expect to see a UI for me to manage Team KnopProject, but cannot find one. I couldn't manage the Team, so I assume one of the Gratipay staff assigned me as Owner on my behalf. Is some public Team management UI is forthcoming?

So it's two issues:

1. Ownership of KnopProject by ~stevepiercy with ~stevepiercy's Primary address tied to a PayPal account to receive payouts (resolved)
2. Team management UI (not resolved)

**Comment by whit537** [comment]
> so I assume one of the Gratipay staff assigned me as Owner on my behalf.

That's probably true. It may even have been me. :-)

> Ownership of KnopProject by ~stevepiercy with ~stevepiercy's Primary address tied to a PayPal account to receive payouts (resolved)

Cool.

> Team management UI (not resolved)

Okay, let's use #3545 for the next steps on that.

**Comment by whit537** [comment]
I'm going to go ahead and close this ticket. Anyone without an attached PayPal won't receive any money, and they will contact us if/when they care. Since it's not obvious that the lack of a PayPal is because of something *we* did, and we're not accidentally pooling up money, I think we just let folks contact us if/when they notice and care.
