### ISSUE TITLE
Public domain is not CC0

### ISSUE THREAD

**Issue by thenoncoder** [gratipay/gratipay.com#3682]
You should correct this page : 
https://github.com/gratipay/gratipay.com/blob/master/CONTRIBUTING.md

CC0 is used in countries which don't have public domain laws, i.e, CC0 is technically speaking is still a license. 
And, technically speaking, it is possible that public domain offers more stuff than CC0 does.

**Comment by techtonik** [comment]
Technically speaking CC0 is not a license - it is a different tool. Licence is based on copyright law, CC0 cancels copyright. In some countries there is also no such term as "public domain", so on that page it is just a common sense concept, so than humans who don't know about CC0 and licensing can understand what all this is about .

**Comment by thenoncoder** [comment]
You're wrong CC0 is a license, ask the guys who made it.

**Comment by techtonik** [comment]
I am right. CC0 can act as a license only in countries where you can't weave your author rights. Therefore CC0 is call "an instrument" or "a tool" to release your stuff into public domain. 

See https://creativecommons.org/about/cc0 and https://wiki.creativecommons.org/wiki/CC0_FAQ

**Comment by thenoncoder** [comment]
You didn't read the whole of my first post.
 I had said : 

> CC0 is used in countries which don't have public domain laws, i.e, CC0 is technically speaking is still a license.

Which is exactly what you said now.

**Comment by thenoncoder** [comment]
Or check this from the [CC0 webpage](https://creativecommons.org/publicdomain/zero/1.0/legalcode) :

> 3. Public License Fallback. Should any part of the Waiver for any reason be judged legally invalid or ineffective under applicable law, then the Waiver shall be preserved to the maximum extent permitted taking into account Affirmer's express Statement of Purpose. In addition, to the extent the Waiver is so judged Affirmer hereby grants to each affected person a royalty-free, non transferable, non sublicensable, non exclusive, irrevocable and unconditional license to exercise Affirmer's Copyright and Related Rights in the Work (i) in all territories worldwide, (ii) for the maximum duration provided by applicable law or treaty (including future time extensions), (iii) in any current or future medium and for any number of copies, and (iv) for any purpose whatsoever, including without limitation commercial, advertising or promotional purposes (the "License"). The License shall be deemed effective as of the date CC0 was applied by Affirmer to the Work. Should any part of the License for any reason be judged legally invalid or ineffective under applicable law, such partial invalidity or ineffectiveness shall not invalidate the remainder of the License, and in such case Affirmer hereby affirms that he or she will not (i) exercise any of his or her remaining Copyright and Related Rights in the Work or (ii) assert any associated claims and causes of action with respect to the Work, in either case contrary to Affirmer's express Statement of Purpose.

As you can see, the CC0 license in indeed used in countries which do not have a public domain law Thus, under the laws of those countries, CC0 is a *license*.

Any country which **does have** public domain law, that country, shall not regard CC0 as a license, as stated by the CC0 page in the part which I had quoted above.

**Comment by techtonik** [comment]
Ok, what about US - it does have a notion of public domain, doesn't it? So CC0 is not a license there, right? And Gratipay is based in US, so.. should we insist that for Gratipay CC0 is still a license?

**Comment by thenoncoder** [comment]
I had already answered this my post above.
According to  the text of the CC0 license, it it cannot be a license if the country of origin of the work has public domain laws. If it does not have such laws, then CC0 is considered a *legally binding **license**
