### ISSUE TITLE
Use Splinter for web tests

### ISSUE THREAD

**Issue by techtonik** [gratipay/gratipay.com#3684]
Currently I don't know who knows how our web test work, because if is based on JavaScript stack. The Splinter allows to write the same stuff in Pythonic way.

https://splinter.readthedocs.org/en/latest/index.html

**Comment by whit537** [comment]
I started looking into this, and it's an interesting option. We have very few jstests currently. The main piece of work would be refactoring the Python test infrastructure to provide a browser instance, and, in particular, wiring up authentication (the in-process testing harness and the jstests both provide examples of this). Porting over the five tests we currently have would be trivial, and if we did so we could have a single test suite, which would greatly facilitate in-browser tests. Good idea! :-)

!m @techtonik

**Comment by whit537** [comment]
Having the js test infrastructure in Python would make it easier for our Python-centric team to fix problems like #2953. Other jstest issues: #3069 #3493.

**Comment by whit537** [comment]
@deivid-rodriguez Any interest in tackling this? :)

**Comment by deivid-rodriguez** [comment]
Yes! I don't know how long it will take to acquire the knowledge to tackle this, but I will definitely keep this on my radar and give it a try!

**Comment by whit537** [comment]
PR in #4079.

**Comment by whit537** [comment]
🎉
