### ISSUE TITLE
Heroku seems to be tightening up free dynos?

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3699]
https://devcenter.heroku.com/articles/dyno-sleeping

> In addition, if a free dyno exceeds a quota of 18 hours of activity during a 24 hour window, it will be forced to recharge.
>
[...]
>
Apps in the “recharging” state are shut down for 6 hours. No dyno (whether web, worker or one-off) will run during this period of time.
Any web traffic received in this state will return an error page and an HTTP status code 503. 

Oh, well. So much for that! :-)

**Comment by whit537** [comment]
I got an email notification from Heroku for an unrelated app.

> Your app [] is running on free dynos and has been active for more than 18 of the last 24 hours. Normally, your app would recharge for the next 6 hours. Don't worry, your app is still running. Right now we're simply sending notifications.

Ominous.

**Comment by whit537** [comment]
> Applications that use traditional dynos and that do not have paid usage will be migrated to free dynos starting on July 15th, 2015. However, if you have an application that is using traditional dynos and that has paid usage for dynos, a database or add-ons, you can choose to keep your app on traditional pricing through January 31, 2016.

**Comment by rohitpaulk** [comment]
I thought we had a ticket for this already? The new pricing is **$7**/dyno.

**Comment by whit537** [comment]
Okay, we might.

**Comment by rohitpaulk** [comment]
Found it - #3386 :) Closing this...
