### ISSUE TITLE
Handle owning multiple teams

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3708]
At https://gratipay.com/new:
> The 1 weekly payments totalling $0.10 that previously were directed to your [] user account will be redirected to your new Team, pending approval of your application.

I assume if someone applies for a second team, they will not have any tips to migrate.

**Comment by whit537** [comment]
Correct. All tips are migrated to the first new Team a ~user opens. It [didn't seem possible](https://github.com/gratipay/gratipay.com/issues/3399#issuecomment-101000562) to do something more fine-grained than that:

> Since giving to Participants has been ambiguous in regard to products or services delivered, migrating giving to a single-purpose Team will be a judgement call for our users. If I have 100 supporters, and 60 would say they were giving to me because of one product or service I provide, and 30 because of another, and 10 just because they love me, then how should I migrate? I don't even know who my supporters are, so it's not like I can manually review and make assignments ("Oh, this person is a Fizzbuzz user, that's probably why they've been supporting me. Let's move their payment to the new Fizzbuzz Team"). No: I have to guess at the 60-supporter product/service, and migrate all of my giving to a new Team dedicated to that. Then I can make a second Team for the 30-supporter product/service.

**Comment by whit537** [comment]
Beyond that, we do handle multiple teams per owner in the simple sense. @book runs three, e.g.:

https://gratipay.com/cpan-book/
https://gratipay.com/act/
https://gratipay.com/cpan-io/

:-)

**Comment by book** [comment]
Unfortunately, I created the cpan-io team first, but I think most of my tippers did it because of my CPAN contributions, which is covered by the cpan-book team that was created later.

**Comment by mattbk** [comment]
Okay, I think I will close this for now and we can reopen as needed.
