### ISSUE TITLE
move tips for @book

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3716]
From @book at https://github.com/gratipay/gratipay.com/issues/3708#issuecomment-134569479:

> Unfortunately, I created the cpan-io team first, but I think most of my tippers did it because of my CPAN contributions, which is covered by the cpan-book team that was created later.

Would you like to move the tips from `cpan-io` to `cpan-book` as a one-time thing? :)

**Comment by book** [comment]
@whit537, if that's not too much trouble, and not against the Terms of Service, then yes please. :-)

**Comment by whit537** [comment]
Done. :-)

```sql
=> update payment_instructions set team='cpan-book' where team='cpan-io';
UPDATE 8
```
