### ISSUE TITLE
make Team explorer sortable

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3736]
Reticketed from #3704.
##

**Comment by whit537** [comment]
Some sorts:

 - oldest
 - newest
 - receiving the most
 - receiving the least
 - most givers
 - fewest givers

As on #3704, use GitHub Issues sort UI as the exemplar.

**Comment by mattbk** [comment]
Once we sort, we'll need a default sort order. See  [levels](https://github.com/gratipay/inside.gratipay.com/issues/432#issuecomment-243245667) discussed regarding [Decouple](https://github.com/gratipay/gratipay.com/milestone/22):

>**Level 3:** Open Payouts &larr; _"open work" according to our current definition_
**Level 2:** Transparent Payouts &larr; _public payouts, but no self-onboarding_
**Level 1:** Closed Payouts &larr; _twyw, but private_
**Level 0:** No Payouts &larr; _no twyw; "team of one" or closed company or what have you_.

**Comment by kaguillera** [comment]
Is this a sort order or a filter?

**Comment by mattbk** [comment]
Could be both, but would be useful as a sort order _before_ anything else. So as a default, sort by level, then by most recent (within each level). The reason being that we're encouraging ~~teams~~ projects to "level up" and be more open by giving them better placement on the homepage. Sorts by the user would override this, e.g., clicking on "sort by age" would bump everyone into order without taking level into account.

So for some example projects:
Team A Level 3, most recent overall
Team B Level 3, third-most recent overall
Team C Level 3, fifth-most recent overall
Team D Level 2, second-most recent overall
Team E Level 1, fourth-most recent overall

**Comment by mattbk** [comment]
> Our old leaderboard was a big part of MaxCDN's motivation for giving on Gratipay. I think we reach out to Justin again once we have something back along those lines.

(https://github.com/gratipay/inside.gratipay.com/issues/757#issuecomment-256480761)

**Comment by JessaWitzel** [comment]
Does the Featured Tab count as a leaderboard or is that something else we want to implement?

**Comment by whit537** [comment]
It's a leaderboard of sorts for the receiver side, but https://github.com/gratipay/gratipay.com/issues/3736#issuecomment-256484342 is actually more along the lines of https://github.com/gratipay/gratipay.com/issues/2695.
