### ISSUE TITLE
add status icons to Team explorer

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3739]
red, yellow, green for rejected, under review, and approved

See GitHub Issues open/closed icons for inspiration.

Reticketed from #3704.

**Comment by whit537** [comment]
Done in #3749.

**Comment by mattbk** [comment]
Icons overlap text in Chrome for Windows.
![image](https://cloud.githubusercontent.com/assets/3729038/9737262/627e7a3e-560b-11e5-9d29-8202bf7550bc.png)

**Comment by whit537** [comment]
Interesting! I don't see that behavior in Chrome on Mac OS:

![screen shot 2015-09-08 at 7 51 35 pm](https://cloud.githubusercontent.com/assets/134455/9750239/177c6976-5663-11e5-84a8-4c29464fa322.png)

It's probably because we're depending on a font for those (they're Unicode characters) and the fonts differ between Windows and Mac OS.

**Comment by mattbk** [comment]
It starts by loading the image below, then switches to what I posted previously when the page is done loading.  Windows Chrome.  Is it loading emoji first, and then images?

![2015-09-09_08-12-34](https://cloud.githubusercontent.com/assets/3729038/9762716/dff0eeb0-56ca-11e5-8d03-2a9cdefb4d43.png)

**Comment by whit537** [comment]
The colored images are actually still emoji, but my hunch is it's starting with a default font and then upgrading to another font. We should probably just use images instead of emoji for consistency.

**Comment by mattbk** [comment]
Oops, this is a local problem.  I use the plugin "Emoji Input by
EmojiStuff.com" to add emoji.  When I turn it off, the icons show up as in
my most recent image.  That explains the delay when loading.

**Comment by whit537** [comment]
Ah, okay. But https://github.com/gratipay/gratipay.com/issues/3739#issuecomment-138579242 is still bad, right?

**Comment by mattbk** [comment]
Yes, but I'm not sure how common that would be.  I don't know how many
different emoji fonts there are.

**Comment by whit537** [comment]
Right, so for consistency's sake I think we should use the same icon font method we're using for the sign-in icons and the footer icons.

**Comment by whit537** [comment]
I've deployed #3765. How do the status icons look now, @mattbk?

**Comment by whit537** [comment]
Here's what I see:

![screen shot 2015-09-10 at 2 57 12 am](https://cloud.githubusercontent.com/assets/134455/9782037/ad202670-5767-11e5-9f06-a7ed7fd5f866.png)
