### ISSUE TITLE
pricing page calculation is wrong

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3746]
> We suggest a 5% voluntary payment to Gratipay. Your usage is $7.84, so we suggest $1.00 per week.

1 is not 5% of 7.84.

**Comment by yifeiwu** [comment]
There's a rounding function in the pricing calculations that rounds it to the nearest quarter dollar. Do you want this to still hold true?

**Comment by whit537** [comment]
@yifeiwu I think it's actually the fact that we apply 10% below $20 that is confusing here. The quarter-dollar rounding would yield 50¢ for 5% of 7.84, rounded up from 39¢, which I think is fine. I think we should do away with the variable rate and just use 5% no matter the usage. Want to make a PR? :-)

**Comment by mattbk** [comment]
FWIW, should users who only give money be asked to contribute to Gratipay?  Dicuss.

**Comment by yifeiwu** [comment]
@whit537 Sure, it's either that or remove the 5% part of the notification. Let me try a PR. It also seems strange you're getting a dollar when it should return 50 cents. 

@mattbk Do you have stats on this? If it turns out receivers don't really contribute anyway then it makes sense.

**Comment by whit537** [comment]
> It also seems strange you're getting a dollar when it should return 50 cents.

That's because below $10 we compute 10%, not 5%:

https://github.com/gratipay/gratipay.com/blob/87b3966f8d9849f6929b6e3aa63b9516595d03d9/gratipay/utils/pricing.py#L9-L10

**Comment by whit537** [comment]
Re: givers-only ... we do track "free riders," people who explicitly opt out of giving to Gratipay. We could look at whether that's more prevalent among givers-only or receivers-only. Let's make a new ticket to discuss that if we think it's really important, though.

**Comment by yifeiwu** [comment]
Ok, then that 5% notification is highly misleading if it doesn't vary along with the percentage. Let's just have a flat 5% across the board?

**Comment by whit537** [comment]
> Let's just have a flat 5% across the board?

Agreed! :-)

**Comment by yifeiwu** [comment]
https://github.com/gratipay/gratipay.com/pull/3770

**Comment by anselmh** [comment]
Calculation will be still wrong due to #3756.

**Comment by rohitpaulk** [comment]
#3770 has been closed, so I'm closing this. 

#3756 looks like it's related to https://github.com/gratipay/gratipay.com/issues/3811 (which has been closed), I'm not sure though.
