### ISSUE TITLE
Gratipay Team To-do link broken if not logged into GitHub

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3748]
> On https://gratipay.com/Gratipay/ there is a dead link ("To-do" – https://github.com/issues?q=is%3Aopen+user%3Agratipay) which points to a 404 on GitHub.

From https://gratipay.freshdesk.com/helpdesk/tickets/3001

**Comment by mattbk** [comment]
I'm not sure where to put this ticket.  It's technically a team error, not a Gratipay error.

**Comment by whit537** [comment]
Interesting! Why the heck does GitHub 404 for anon there? :-(

And what should we do?

**Comment by whit537** [comment]
@mattbk Wanna email support@github.com and notify them of the 404?

**Comment by clone1018** [comment]
I think that might be an older URL. I was able to get the following working:

https://github.com/search?l=&q=is%3Aopen+user%3Agratipay&ref=advsearch&type=Issues&utf8=%E2%9C%93

**Comment by whit537** [comment]
Good find! I've updated our to-do link to:

https://github.com/search?q=is%3Aopen+user%3Agratipay&type=Issues

And I've emailed GitHub support:

Subject: /issues is 404 for anon?

> Greetings!
>
Why is this URL 404 for unauthenticated users?
>
https://github.com/issues?q=is%3Aopen+user%3Agratipay
>
... when this URL isn't?
>
https://github.com/search?q=is%3Aopen+user%3Agratipay&type=Issues

Leaving this open to track their response ...

**Comment by whit537** [comment]
> The behavior you observed is expected for now, but I agree that behavior could be improved. The original purpose of the /issues page was to show you a list of _your_ issues, even though you can tweak the search to show you more than that. I'm guessing that for this reason -- you're seeing a 404 when making anonymous requests.
>
I'll pass your feedback to the team to consider, but can't make any promises. For now, you can use an alternative, which you already discovered.
>
Thanks for the interesting questions, as always.

--------------------

> Thanks, []. Here's our thread about this, for context:
>
https://github.com/gratipay/gratipay.com/issues/3748
>
Cheers! :-)

**Comment by whit537** [comment]
> I'm not sure where to put this ticket. It's technically a team error, not a Gratipay error.

P.S. I think https://github.com/gratipay/inside.gratipay.com/issues would've been a better fit.
