### ISSUE TITLE
A better homepage banner

### ISSUE THREAD

**Issue by timothyfcook** [gratipay/gratipay.com#3755]
Due to my intense dislike of the banner resulting from #3711 I offer a rough sketch of some alterations to improve the design:

![gratipay_banner_mockup](https://cloud.githubusercontent.com/assets/1823300/9691651/c06dd90c-5311-11e5-92fb-689b42b923b7.png)
##

**Comment by whit537** [comment]
@timothyfcook Looks good as a mockup. Next step would be clean this up and make a PR.

Your ticket title says "homepage." What do you envision on inside pages? Something different?

**Comment by whit537** [comment]
cc: @sils1297 per https://github.com/gratipay/team-review/issues/36#issuecomment-137971240

**Comment by whit537** [comment]
Here's the original for the current banner if you want to start with that:

![img_2673](https://cloud.githubusercontent.com/assets/134455/9717711/f3efc604-5542-11e5-8296-0726101c874e.JPG)

**Comment by whit537** [comment]
![screen shot 2015-09-07 at 9 12 35 pm](https://cloud.githubusercontent.com/assets/134455/9724443/34da89a8-55a5-11e5-9f1e-7648cbf5eeaf.png)

![screen shot 2015-09-07 at 9 11 37 pm](https://cloud.githubusercontent.com/assets/134455/9724438/2242c2c4-55a5-11e5-8cb6-b39f6de6d785.png)

**Comment by whit537** [comment]
![screen shot 2015-09-07 at 9 11 37 pm](https://cloud.githubusercontent.com/assets/134455/9724438/2242c2c4-55a5-11e5-8cb6-b39f6de6d785.png)

**Comment by whit537** [comment]
![screen shot 2015-09-07 at 10 07 09 pm](https://cloud.githubusercontent.com/assets/134455/9724942/d24525f2-55ac-11e5-95bf-1f3f918b641f.png)

**Comment by whit537** [comment]
I'm struggling with this. Without the lines of the banner image, I'm not sure what all of the elements of the top of the page relate to.

![screen shot 2015-09-07 at 10 13 13 pm](https://cloud.githubusercontent.com/assets/134455/9725004/a86a7362-55ad-11e5-9b35-22503c13eb00.png)

**Comment by whit537** [comment]
Without the banner, the content area also gets lost:

![screen shot 2015-09-07 at 10 15 14 pm](https://cloud.githubusercontent.com/assets/134455/9725025/00654aec-55ae-11e5-8467-530dad750a8e.png)

![screen shot 2015-09-07 at 10 16 20 pm](https://cloud.githubusercontent.com/assets/134455/9725029/16f00c48-55ae-11e5-9057-a6ca1bc135cc.png)

**Comment by whit537** [comment]
For comparison:

![screen shot 2015-09-07 at 10 16 52 pm](https://cloud.githubusercontent.com/assets/134455/9725036/34a95294-55ae-11e5-8e1a-36de31b24c97.png)

![screen shot 2015-09-07 at 10 17 07 pm](https://cloud.githubusercontent.com/assets/134455/9725038/38dfd2b6-55ae-11e5-9122-79beef6f76b9.png)

**Comment by whit537** [comment]
The stronger banner demarcates the left and right boundaries of the page, and also sets off the "top stuff" from the content area.

**Comment by whit537** [comment]
![screen shot 2015-09-07 at 10 19 12 pm](https://cloud.githubusercontent.com/assets/134455/9725058/7e38ef00-55ae-11e5-81b7-4593d27862a1.png)

![screen shot 2015-09-07 at 10 18 58 pm](https://cloud.githubusercontent.com/assets/134455/9725061/83fa8048-55ae-11e5-879c-13c136e7f744.png)

**Comment by whit537** [comment]
Needs more work, @timothyfcook. :-)

**Comment by whit537** [comment]
The pxm is 11 MB, so I'm reluctant to put it in the repo. I've uploaded it here:

https://www.dropbox.com/s/osrk0pt7j8soo24/banner.pxm?dl=0

Here's a branch with my code so far:

https://github.com/gratipay/gratipay.com/tree/no-wood

**Comment by whit537** [comment]
Okay! @timothyfcook is putting the squeeze on. He threw in $20 and I found a 10-spot in my pocket. That and some heartcoins and stickers and we've got a designer co-resident here at Stack on the case: he's going to do an illustration for us that we can hopefully drop-in replace for the picture of my table. :)

**Comment by timothyfcook** [comment]
So stoked.

**Comment by whit537** [comment]
Raw:

![untitled_artwork](https://cloud.githubusercontent.com/assets/134455/21573435/467a6ed0-ceb2-11e6-976b-3ebc5ae87554.png)

**Comment by whit537** [comment]
First cut at placement:

![screen shot 2016-12-30 at 5 05 13 pm](https://cloud.githubusercontent.com/assets/134455/21573445/560c624a-ceb2-11e6-930e-1fefa5908fc0.png)
![screen shot 2016-12-30 at 5 05 26 pm](https://cloud.githubusercontent.com/assets/134455/21573446/560d051a-ceb2-11e6-952d-3f53fdc38528.png)
![screen shot 2016-12-30 at 5 05 39 pm](https://cloud.githubusercontent.com/assets/134455/21573447/560fe4ec-ceb2-11e6-9274-3f3f8ae026fe.png)

**Comment by timothyfcook** [comment]
Looking great! I would maybe render the edge of it differently. Less of that border/drop-shadow. Maybe flat with rounded corners to match your button and icon style.

**Comment by whit537** [comment]
> edge of it

What is "it"? The profile pic and chalkboard?

**Comment by timothyfcook** [comment]
the green rectangle. the whole banner box.

**Comment by whit537** [comment]
There _is_ a 1px border on the top and bottom of the green rectangle, but ... you are seeing a drop shadow on the green rectangle?

**Comment by whit537** [comment]
More subtle coloring:

-----------------

![screen shot 2016-12-30 at 5 24 59 pm](https://cloud.githubusercontent.com/assets/134455/21573646/fcf53404-ceb4-11e6-9034-61adf1fac1a3.png)

-----------------------

![screen shot 2016-12-30 at 5 25 10 pm](https://cloud.githubusercontent.com/assets/134455/21573647/fcf7a7e8-ceb4-11e6-98fb-7eaff4bde4c3.png)

**Comment by timothyfcook** [comment]
looks good more subtle. Yeah, it's the 1px border. What does it look like without that, but with slightly rounded corners (like the rounded corners on the buttons). Obvs would have to sync the corner-rounding with that yellow notification box as well.

**Comment by whit537** [comment]
I used [this](http://www.rapidtables.com/convert/color/rgb-to-hsl.htm) and [this](http://help.pixelmator.com/mac/3.6/#90) to colorize the image. Then I trimmed transparent pixels, resized it, and positioned it in CSS. 

![screen shot 2016-12-30 at 5 31 54 pm](https://cloud.githubusercontent.com/assets/134455/21573723/ea25de86-ceb5-11e6-9ead-78895ad8e5e7.png)

**Comment by whit537** [comment]
Moving to https://github.com/gratipay/gratipay.com/pull/4267 ...

**Comment by whit537** [comment]
> What does it look like without that, but with slightly rounded corners (like the rounded corners on the buttons). Obvs would have to sync the corner-rounding with that yellow notification box as well.

If you can live without that and can give a +1 to #4267, I will merge that and deploy it right now. :-)

**Comment by whit537** [comment]
@timothyfcook Because that is SCOPE CREEP you didn't SAY ANYTHING ABOUT THE Border just the image!

**Comment by timothyfcook** [comment]
Agreed. lol. separate ticket.
