### ISSUE TITLE
1.0-payout page is broken

### ISSUE THREAD

**Issue by anselmh** [gratipay/gratipay.com#3758]
It seems that the https://gratipay.com/1.0-payout page is broken. If you’re not logged in it results in a 403 which is understandable (though an error message or login window would help more) but when logged in I only see the headline and nothing else. 
JS Console is empty so I don’t know what’s wrong there. It appears on Chrome and Firefox at least.
![screen shot 2015-09-07 at 16 25 48](https://cloud.githubusercontent.com/assets/399345/9718569/4a0cfa40-557d-11e5-9136-ff88d419c753.png)

**Comment by whit537** [comment]
Okay, major update to that page is coming down the pike in #3744. Let's revisit this after that lands ...

**Comment by whit537** [comment]
@anselmh The new 1.0 payout page (#3744) is out. Can you review and see if it's still broken for yo?

**Comment by anselmh** [comment]
Nice, works now as expected and with way more useful notices.

**Comment by whit537** [comment]
Awesome! Thanks for all the feedback. :-)
