### ISSUE TITLE
allow Teams to customize the banner

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3767]
Reticketed from https://github.com/gratipay/team-review/issues/36#issuecomment-137971240 and https://github.com/gratipay/gratipay.com/pull/3750#issuecomment-139265893:

> I was rather thinking about having the background banner customized, with an image like http://www.whatcanidoforcoala.org/static/themes/coala/img/background.jpg (probably with the coala on the other side), giving the whole page a more custom touch.
##

**Comment by whit537** [comment]
cc: @sils1297

**Comment by whit537** [comment]
![background](https://cloud.githubusercontent.com/assets/134455/9791286/401a474a-57a8-11e5-9f36-e14cfdf3a32a.jpg)

**Comment by sils1297** [comment]
@whit537 or rather this because you have text on the right side and your format is a bit wider:

![background](https://cloud.githubusercontent.com/assets/5716520/9791433/53e19aac-57db-11e5-9fe4-ea89a069b781.jpg)

Disclaimer, this is a prototype image for mockup purposes, for our production banner we'll want to consult our designer @ankitstarski for a better image.

**Comment by whit537** [comment]
:-)

I like it!

**Comment by anselmh** [comment]
I don’t get it. I like the idea but what is this about the one background image? I thought this would give people the possibility to upload their own bg image? Or is the koala only an example?

**Comment by sils1297** [comment]
> I thought this would give people the possibility to upload their own bg image?

IIUC yes. I don't see any reason why only us (coala) should get a feature and noone else, that would be bad. Thing is, a bg image/banner is better than just a logo to get some branded identity on that page.

**Comment by whit537** [comment]
Yeah, the koala is only an example. :-)

Are we thinking a Team would have *either* a logo *or* a background image? Or both? Or optionally both? I think we should have at least one or the other.

**Comment by anselmh** [comment]
Both I think would be the best option and make one or the other optional.

**Comment by whit537** [comment]
Okay. We'll still want the logo for use on listings:

![screen shot 2015-09-14 at 7 34 50 am](https://cloud.githubusercontent.com/assets/134455/9848871/1ba1ed9c-5ab3-11e5-82a5-cc8faddd252d.png)

**Comment by sils1297** [comment]
For our case I'd definitely prefer having a logo for the listing and a
banner without the logo for the page.

**Comment by sils1297** [comment]
Logo on default background could be used as a fallback if no banner is provided.

2015-09-14 13:44 GMT+02:00 Lasse Schuirmann <lasse.schuirmann@gmail.com>:
> For our case I'd definitely prefer having a logo for the listing and a
> banner without the logo for the page.

**Comment by whit537** [comment]
Okay. I'm personally prioritizing other things atm but I'd be happy to entertain a PR here, and I've labelled this "Ready to Start." :-)

**Comment by whit537** [comment]
+1 from Katie at the Internet Archive
