### ISSUE TITLE
Remove/Replace "Payments by Balanced"

### ISSUE THREAD

**Issue by kzisme** [gratipay/gratipay.com#3769]
When reviewing a users routes page

https://gratipay.com/~kzisme/routes/

There is still an image showing that payments are 
![capture](https://cloud.githubusercontent.com/assets/3493562/9798183/58e6891c-57cd-11e5-9b93-65b6ac02b4e2.PNG)

Is there a preferred image that could replace the existing or would it be okay to keep it around?

**Comment by whit537** [comment]
I've copied your comments over to #3565. Closing this as a dupe.
