### ISSUE TITLE
give more visibility into funding build-up

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3779]
Now that we're charging in arrears, we need to give both ~users and Teams visibility in their funding build-ups. Reticketed from #3378.
##

**Comment by whit537** [comment]
Here's what I'm currently seeing as the build-up for nuvola-player, e.g.:

```sql
=> select sum(due), count(*) from current_payment_instructions where due > 0 and team='nuvola-player';
┌───────┬───────┐
│  sum  │ count │
├───────┼───────┤
│ 79.18 │    59 │
└───────┴───────┘
(1 row)
```

However, I'm not sure how exactly this interacts with the `is_funded` column on `current_payment_instructions`.

**Comment by rohitpaulk** [comment]
There are two parts to this - the ~users UI, and Teams UI. The second part is blocked on https://github.com/gratipay/gratipay.com/issues/3705.
