### ISSUE TITLE
When I look at *my* profile, `[hidden]` should not be shown but the amount.

### ISSUE THREAD

**Issue by anselmh** [gratipay/gratipay.com#3783]
When I look at my own profile (logged in) I should see my amounts instead of `[hidden]` in the panel. It’s only for public that it shouldn’t be shown if I opt-in for that.

**Comment by mattbk** [comment]
I'm interested in trying to figure this out, but I'm not sure where the right template file is for that part of the page.

This is what you are looking at?
![image](https://cloud.githubusercontent.com/assets/3729038/9885169/6e4a4a7a-5ba9-11e5-88e0-0ef93c2cdc63.png)

**Comment by mattbk** [comment]
There it is: https://github.com/gratipay/gratipay.com/blob/035bf53e3125b9b78ae83fb7508927e4590000b0/templates/profile.html  

Hopefully I can get to it today.

**Comment by whit537** [comment]
Should be fixed in #3788. Can you confirm, @anselmh?

**Comment by anselmh** [comment]
Except that it’s a completely wrong amount (giving/receiving) which is already reported as well, it’s fixed.

**Comment by whit537** [comment]
> it’s a completely wrong amount (giving/receiving)

Is your *giving* wrong, too, or just your receiving (#3756)?

**Comment by anselmh** [comment]
Both.

----
Anselm

**Comment by whit537** [comment]
Blech. Looks like you're right. :-(

Reticketed bad giving as https://github.com/gratipay/gratipay.com/issues/3793.
