### ISSUE TITLE
Update documentation with arrears information

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3791]
[WHY IS MY TEAM RECEIVING LESS NOW THAN IT WAS BEFORE?](https://gratipay.com/about/features/payments#receiving-less)

Should this section have a link to how the arrears charging works?  Because if we're [charging in arrears](https://github.com/gratipay/gratipay.com/pull/3675) now, Teams (and hence ~users) may not receive a payment for weeks at a time, especially if there is only one giver, who happens to only give to one team.

Example: 
Alice gives $1 to Team Bob every week, and $0 to other teams.
Team Bob only receives from Alice.
It takes 10 weeks for Alice to build up enough to be charged, at which point Bob receives $10 all at once...and then drops down to receiving $0 per week for 10 more weeks.

Am I correct in assuming that "Taking" at the top of each ~user page includes those pledges that have not yet been charged?  I thought I read somewhere that this was an average derived from other data.

**Comment by mattbk** [comment]
If this is the case, might it make sense to have pledged donations show up in the history?  There would need to be a way to avoid doubling the bookkeeping though.

**Comment by whit537** [comment]
> [M]ight it make sense to have pledged donations show up in the history?

Yeah, I think so.

**Comment by mattbk** [comment]
I think this is happening here: https://gratipay.freshdesk.com/helpdesk/tickets/3169

**Comment by mattbk** [comment]
https://github.com/gratipay/gratipay.com/issues/3378#issuecomment-139774991

**Comment by mattbk** [comment]
See also https://github.com/gratipay/gratipay.com/issues/3794

**Comment by rohitpaulk** [comment]
> If this is the case, might it make sense to have pledged donations show up in the history?

I don't think it makes sense to put them in the history (because that's for actual payments), but it is important to expose this in the UI. I think the perfect place would be the 'receiving' tab for teams.

**Comment by mattbk** [comment]
Yes.

**Comment by whit537** [comment]
!m @rohitpaulk @mattbk

**Comment by whit537** [comment]
> Should this section have a link to how the arrears charging works?

Done on #3840.

> might it make sense to have pledged donations show up in the history?
> I don't think it makes sense to put them in the history

Looks like that convo is picked up on #3834.
