### ISSUE TITLE
giving differs between chalkboard and Giving

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3793]
Reticketed from https://github.com/gratipay/gratipay.com/issues/3783.

cc: @anselmh
##

**Comment by mattbk** [comment]
Wow, this fell off the radar.  How would I check to see if this is true for others as well?

**Comment by rohitpaulk** [comment]
I had a look at this - the cached values are correct for the user in question (https://gratipay.com/~Anselm%20Hannemann/).

**Comment by rohitpaulk** [comment]
Closing until we have better evidence...

**Comment by whit537** [comment]
I'm still seeing a discrepancy between the user's Giving > Active page/tab, and their Giving on the chalkboard. Now that I think about it, this is probably a duplicate of #3666 (no intra-payday regiving anymore since the Gratipay 2.0 payday rewrite).

**Comment by whit537** [comment]
> duplicate

... or at least related.

**Comment by whit537** [comment]
Yeah, this falls under #3666. The problem is that `giving` [only includes `is_funded`](https://github.com/gratipay/gratipay.com/blob/1928/gratipay/models/participant.py#L976) payment instructions. The chalkboard uses `participants.giving`, but the Giving tab doesn't.

**Comment by whit537** [comment]
> Yeah, this falls under #3666. 

Well, let's keep that separate.

**Comment by whit537** [comment]
Dropping from [Basic Math](https://github.com/gratipay/gratipay.com/milestones/Basic%20Math) since this isn't a math bug but rather a presentation bug.

**Comment by mattbk** [comment]
https://github.com/gratipay/gratipay.com/issues/4367 merged into this issue.
