### ISSUE TITLE
about/me/emails style glitch

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3798]
From https://gratipay.freshdesk.com/helpdesk/tickets/3189.

> Emails view is quite messy:
> 
> ![7b3036fa-6685-11e5-80c3-933a4d6be16e_092915_120734_pm](https://cloud.githubusercontent.com/assets/3729038/10172012/ac6d4b28-66a2-11e5-93c8-e35cb97abed1.jpg)
> 
> Latest Chrome and a really big screen.
##

**Comment by simison** [comment]
OSX Yosemite ver 10.10.5 (14F27)
Chrome ver 45.0.2454.99 (64-bit)

**Comment by webmaven** [comment]
Ew. Is this still occurring?

**Comment by simison** [comment]
Yep, still looks like this:

![e](https://cloud.githubusercontent.com/assets/87168/11349731/4e47e3b0-91f3-11e5-8547-03e36214ce17.jpg)

**Comment by webmaven** [comment]
@simison, thanks for the UI bug report. I'll see how soon I can deal with it.

**Comment by mattbk** [comment]
I'm not seeing this anymore, is anyone else?
