### ISSUE TITLE
Prompted to "back your payment with a credit card" even though I have one

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3801]
![image](https://cloud.githubusercontent.com/assets/3729038/10232012/b77d68d6-684b-11e5-91dc-ee8c662107f6.png)

I think this text should be removed if the user already has a payin route.
##

**Comment by rohitpaulk** [comment]
@mattbk - Can you confirm whether this still exists? I think it's related to https://github.com/gratipay/gratipay.com/issues/3811

**Comment by mattbk** [comment]
Still there for me.
