### ISSUE TITLE
Receiving includes tips from ~users with bad credit card info

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3811]
From https://gratipay.freshdesk.com/helpdesk/tickets/3240.

~user is seeing a higher number than he is receiving weekly.  This is not due to arrears, because the credit card info for one of the people tipping his team is bad.  

- Where is the documentation for how the receiving number is calculated?  It's some sort of moving average, right?

- Is this the desired behavior?

**Comment by whit537** [comment]
!m @rohitpaulk @mattbk

**Comment by rohitpaulk** [comment]
I'm noticing that the `receiving` on teams has been fixed, but the `taking` values on team owners are still stale. Reopening this, looking into it.
