### ISSUE TITLE
avoid increasing due beyond payin minimum when cards fail

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#3818]
If a ~user has a $5 tip set up to a team, and their card is failing - we won't charge them again until the card is updated, but we will be adding to their dues every week. If the user updates their card a year later, that's a $260 charge.

This should be clearly communicated to users - https://github.com/gratipay/gratipay.com/pull/3817 is step 1. Adding this to the documentation wherever relevant is step 2.

**Comment by rohitpaulk** [comment]
I just realized that canceling a subscription won't erase the dues - fixed in https://github.com/gratipay/gratipay.com/pull/3819

**Comment by whit537** [comment]
We should never increase dues beyond the minimum charge. If they reach the minimum charge and then their card fails, we should stop adding to due. If/when they fix their card we should charge the minimum at that point. We don't want $260 surprises!

**Comment by mattbk** [comment]
Nice catch.

**Comment by whit537** [comment]
@rohitpaulk Why do we have `Review` on this one?

**Comment by whit537** [comment]
Done with #3876. !m @rohitpaulk :dancer:
