### ISSUE TITLE
add top-level team members to about pages

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3820]
Random example courtesy of @Hammadqureshi (via call under https://github.com/gratipay/inside.gratipay.com/issues/361):

![screen shot 2015-10-12 at 10 06 43 am](https://cloud.githubusercontent.com/assets/134455/10429771/f70f2a9a-70c8-11e5-81a8-3fc90f429e51.png)
##

**Comment by Hammadqureshi** [comment]
Another preferable example:

<img width="858" alt="screen shot 2015-10-15 at 5 48 52 pm" src="https://cloud.githubusercontent.com/assets/9057459/10514059/117bd4fc-7365-11e5-87da-0a038abddfd1.png">

**Comment by Hammadqureshi** [comment]
Taken from a open source project codeigniter. URL : https://www.codeigniter.com/help/about.

**Comment by Hammadqureshi** [comment]
Another Example:

<img width="522" alt="screen shot 2015-10-28 at 12 17 21 am" src="https://cloud.githubusercontent.com/assets/9057459/10769940/93e2a53e-7d0a-11e5-8d70-4938614c919a.png">

This one looks looks cool. Any suggestions @whit537  ?

**Comment by webmaven** [comment]
A Gratipay 'Team' is approximately similar to a Github 'Organization' (which are a special case of a 'User', for many intents and purposes), so we can mimic Github's 'People' box on organization pages as a first step: 

![github_org_page](https://cloud.githubusercontent.com/assets/438502/11346167/8b8a6bfa-91d8-11e5-8d66-ba4e19026f89.png)

But the approximate mapping between Gratipay 'Teams' and Github 'Organizations', also suggests we could pick up some layout from the Github Organization Members page for more detail and a complete listing:

![github_org_members](https://cloud.githubusercontent.com/assets/438502/11346254/f532ce4e-91d8-11e5-8d2f-69c22de8db53.png)

If ever we wanted to allow Gratipay 'Teams' to have subgroups of some sort (such as 'projects', etc., depending on how the terminology shakes out): we could pick up elements of the Github 'Teams' page to list them:

![github_team_page](https://cloud.githubusercontent.com/assets/438502/11346301/3b0c8bd0-91d9-11e5-9ffa-fdf6a9cd3b81.png)

Q: All this suggests to me that perhaps we should rename Gratipay 'Teams' to 'Organizations' (as [mentioned in another ticket](/gratipay/gratipay.com/issues/3399#issuecomment-159010969), I also feel that 'Open Organization' is a better term than 'Open Company', this would unify the terminology even further). Does anyone else concur?

**Comment by whit537** [comment]
This could overlap with https://github.com/gratipay/inside.gratipay.com/issues/404, because we should have a visualization for holacracy circles and the team page would seem a natural fit.
