### ISSUE TITLE
avoid null route, ref, and status in new exchanges

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3822]
See #3810 for why cross-linking transactions is a good idea. We were doing this for Balanced by the end, but I don't think we're doing this for _any_ payment networks now.
##

**Comment by rohitpaulk** [comment]
We had the 'reverse' of this in balanced, iirc. There was a meta column named 'exchange_id' on every transaction in Balanced.

**Comment by whit537** [comment]
@rohitpaulk Yes! We preferred that on #3807:

https://github.com/gratipay/gratipay.com/blob/e236680d9daf21afa5e5c078561a3858a37b8c11/backfill-exchanges.py#L124-L129

**Comment by whit537** [comment]
Really we should refactor payment routes along the lines of accounts elsewhere, to have a more consistent interface across all of the routes we support, to include method and transaction linking, and status changes via postbacks.

**Comment by whit537** [comment]
We haven't had a `NULL` `route` (at least) since #3810. See https://github.com/gratipay/gratipay.com/pull/3975#issuecomment-262084837.

**Comment by whit537** [comment]
Folding this into #4442.
