### ISSUE TITLE
close out our Balanced account

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3826]
Refunds are just about done (#3810), meaning it's about time to put our Balanced account to rest.

**Comment by whit537** [comment]
I've downloaded JSON for everything I can think of in Balanced:

 - customers
 - bank_accounts
 - cards
 - transactions
 - disputes
 - invoices
 - logs

Right now they're in our `logs` repo, which is private, but I'm not really comfortable keeping all that data online. I think we should store it offline.

**Comment by whit537** [comment]
So that's one task: safely archiving our Balanced data. We do still need it because we should still backfill the exchange_routes and exchanges tables so we can un-NULL certain columns.

Another task is withdrawing our remaining funds.

**Comment by whit537** [comment]
I'm getting a `403` trying to withdraw our remaining $26,191 from Balanced. On the phone, Matin told me that they would be pushing our money to us as part of their final shutdown procedure, so I guess that's what we will wait for.

**Comment by whit537** [comment]
> On the phone

https://github.com/gratipay/gratipay.com/issues/3539#issuecomment-142102062

**Comment by whit537** [comment]
How about I'll follow up with Matin in November if we don't have the money by then. S'okay?

**Comment by whit537** [comment]
Checked, still there.

**Comment by whit537** [comment]
> Hey Matin. When should we expect Gratipay's final balance of $26,191 to be sent to our New Alliance bank account? Anything you need from me on that?
>
Thanks!

**Comment by whit537** [comment]
> I'm working on manually settling out each customer's balance throughout Nov. I'll add you to the queue.
>
To confirm, should I pay out the bank account you already have associated to your marketplace?

-----------

>>I'm working on manually settling out each customer's balance throughout Nov. I'll add you to the queue.
>
Cool, thank you.
>
>>To confirm, should I pay out the bank account you already have associated to your marketplace?
>
Yes, please. It's listed in the "Withdraw Funds" dialog as "Checking account: xxxxxx New Alliance Fcu."

**Comment by whit537** [comment]
To: Matin

> Ping?

**Comment by whit537** [comment]
To: Matin

> Hey, Matin. We're still waiting for the $26,191.00 left in our Balanced marketplace to be sent to us. Can you help me out with that? Thanks.

**Comment by finkiki** [comment]
He run away with.

**Comment by whit537** [comment]
Seems unlikely, but that would certainly be a plot twist, now wouldn't it? :moneybag: :runner:

**Comment by whit537** [comment]
I called and texted.

> Hey man, I really need you to help me close out Gratipay's account at Balanced. Please call me asap.

**Comment by rohitpaulk** [comment]
Two months... Man I hope this isn't trouble.

**Comment by whit537** [comment]
Hey @matin, we really need to get Gratipay's users' money back from Balanced. Please call me asap. 412-925-4220.

**Comment by whit537** [comment]
I've emailed mtamizi@gmail, per @matin's GitHub profile.

**Comment by whit537** [comment]
I've called and talked to @jkwade, who is not in frequent contact with @matin anymore, but offered to reach out on our behalf.

**Comment by whit537** [comment]
Balanced's SSL cert expired 10 days ago, which seems to have rendered the dashboard inoperable.

**Comment by matin** [comment]
Working on this now.

**Comment by whit537** [comment]
Just got a call from @matin. He asked for a day or two to fix the SSL issue and get the payment out to us.

To be clear: we should've withdrawn our balance (or at least the bulk of it) when we had the chance back in October.

**Comment by whit537** [comment]
> Working on this now.

Thanks, @matin. :-)

**Comment by matin** [comment]
I just created the credit. It'll go out on Monday, and you should see it in your account on Tuesday morning.

**Comment by whit537** [comment]
Awesome, @matin, thank you. I'll check for it on Tuesday and hopefully we can close out this ticket and this milestone!

**Comment by matin** [comment]
@whit537 You should have received the money today and be able to close out this issue.

**Comment by whit537** [comment]
I just checked, and yes: the money is in Gratipay's New Alliance account. :moneybag: :bank: 

Thank you for bringing us in for a landing here, @matin. You are an honorable man, and you should be proud of what you and your team accomplished. Balanced will be part of Gratipay's story for as long as we're around. We never could've made it this far without you, and we'll keep carrying the open company torch as best we can! :open_hands: 

!m @matin @jkwade @mahmoudimus @balanced :clap: :sparkles: :seedling: :bow:
