### ISSUE TITLE
invalid route_id on record an exchange

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3828]
@rohitpaulk My hunch is that this is due to a recent PR of yours ... ring any bells?

![screen shot 2015-10-15 at 8 52 29 pm](https://cloud.githubusercontent.com/assets/134455/10531364/b4bdadf2-737e-11e5-94a3-25d567e627d6.png)

**Comment by whit537** [comment]
Ah, hrm. I see that we now list the routes available on the "record an exchange" form. The issue here is that I'm trying to do a payout via Transferwise, which doesn't have proper route infrastructure yet.

**Comment by rohitpaulk** [comment]
@whit537 - Can this be closed now?

**Comment by whit537** [comment]
Yes. :)
