### ISSUE TITLE
It's not clear if Balanced is dead or my card is working

### ISSUE THREAD

**Issue by YorikSar** [gratipay/gratipay.com#3835]
In the Routes section of the profile, I see big "Your credit card is working" line. And "Payments by Balanced" near it. So I guess with Balanced out of business there are two options:

* Balanced had my card data, and you can't charge me anymore;
* Balanced transferred card data to you (how? why? is it secure?) and you process payments elsewhere.

In the first case I guess you should warn people that their credit card isn't actually working. In the second case you should strip all Balanced banners from profile pages (Overview and Credit Card tabs in Routes section).

**Comment by mattbk** [comment]
The switch from Balanced to Braintree is stuck in review in this PR: https://github.com/gratipay/gratipay.com/pull/3565.  Your credit card is working.

**Comment by YorikSar** [comment]
Ok, didn't see that one. I guess I should skim over PRs as well next time.

> Your credit card is working.

I wonder how was my credit card's information transferred to another payment processing company? I thought it's forbidden by Visa/MC rules or smth.

**Comment by rohitpaulk** [comment]
> I wonder how was my credit card's information transferred to another payment processing company? I thought it's forbidden by Visa/MC rules or smth.

Here's the ticket for the migration: https://github.com/gratipay/gratipay.com/issues/3391

**Comment by YorikSar** [comment]
Awesome transparency, great inside info. Thanks!

**Comment by whit537** [comment]
!m @YorikSar @rohitpaulk

**Comment by YorikSar** [comment]
@whit537 I've see this "!m" in other issues. What does it mean? I can't find it.

**Comment by mattbk** [comment]
It means "you're doing a good job."  On the IRC channel, !m @username calls a bot to say "You're doing a good job, @username."

**Comment by whit537** [comment]
!m @mattbk

http://motivate.im/ :-)

**Comment by YorikSar** [comment]
Oh, cool. So !m = "Inflict some motivation on". Thanks for the explanation!
