### ISSUE TITLE
drop social authentication

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3837]
Reticketed from #1052 and #3604.
##

**Comment by mattbk** [comment]
Switching to email/password or Medium authentication, or drop all social network links?

**Comment by whit537** [comment]
The proposal here is that we no longer allow people to use Facebook, Twitter, etc. to sign in to Gratipay. I think it's fine to support linking social accounts to one's Gratipay profile, but we'd only accept email to sign in.

**Comment by sampablokuper** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=27562722)](https://www.bountysource.com/issues/27562722-drop-social-authentication?utm_source=27562722&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by Changaco** [comment]
(Anyone willing to implement password auth in Gratipay might want to take a look at how it's done in Liberapay: [authentication.py](https://github.com/liberapay/liberapay.com/blob/126/liberapay/security/authentication.py), [participant.py](https://github.com/liberapay/liberapay.com/blob/126/liberapay/models/participant.py#L169-L230), etc.)

**Comment by EdOverflow** [comment]
I would recommend using bcrypt instead of PBKDF2 for password hashing, because the latter can be better accelerated with GPUs. There is a well maintained implementation of bcrypt by PyCA: https://github.com/pyca/bcrypt.

**Comment by whit537** [comment]
@rohitpaulk is -1

> I like the ease of social logins

https://gratipay.slackarchive.io/gratipay/page-100/ts-1496395293112456
