### ISSUE TITLE
drop account merging

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3838]
Account merging is complicated and therefore error-prone.

Reticketed from #1052.
##

**Comment by mattbk** [comment]
What's it blocked on?

**Comment by whit537** [comment]
Blocked on #3837, because the root cause of most account merging is that we allow multiple ways to authenticate with Gratipay. Someone signs in with Twitter, comes back six months later and signs in with GitHub: now they have two accounts. Once we drop social authentication and just have email authentication, we greatly reduce the need for account merging and can therefore do away with it.
