### ISSUE TITLE
cta percentage is 149%

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3841]
*sigh*

We suck at math. :-(

![screen shot 2015-10-21 at 5 01 42 pm](https://cloud.githubusercontent.com/assets/134455/10650066/78028004-7815-11e5-8f7e-558b316c91a3.png)

**Comment by yifeiwu** [comment]
def update_cta(website):
    nusers = website.db.one("""
        SELECT nusers FROM paydays
        ORDER BY ts_end DESC LIMIT 1
    """, default=0)
    nreceiving_from = website.db.one("""
        SELECT nreceiving_from
          FROM teams
         WHERE slug = 'Gratipay'
    """, default=0)
    website.support_current = cur = int(round(nreceiving_from / nusers * 100)) if nusers else 0

https://github.com/gratipay/gratipay.com/blob/f9749d98d2853701968adf437e9436deca1741aa/gratipay/utils/__init__.py
I think the math looks ok, I'm guessing something went wrong in the db?

**Comment by rohitpaulk** [comment]
Looks like `nusers FROM paydays` doesn't include the people who haven't been charged because of the new arrears system - and `nreceiving_from FROM teams` does.

**Comment by rohitpaulk** [comment]
Closed in #3848
