### ISSUE TITLE
admin UI for changing exchange status

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3845]
##

**Comment by mattbk** [comment]
What does "exchange status" mean?

**Comment by whit537** [comment]
> What does "exchange status" mean?

It refers to the status of an attempt to move money between Gratipay and other payment systems, one of:
[`('pre', 'pending', 'failed', 'succeeded')`](https://github.com/gratipay/gratipay.com/blob/1933/sql/schema.sql#L195).
