### ISSUE TITLE
add `noindex` to rejected Teams

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3846]
Reticketed from https://github.com/gratipay/team-review/issues/54.

**Comment by whit537** [comment]
I'm taking off the Embarrassing label since this is on a milestone.

**Comment by kaguillera** [comment]
Please note that the PR for this is up for review anyone...

**Comment by whit537** [comment]
Decided against this at https://github.com/gratipay/gratipay.com/pull/4125#issuecomment-255552348.
