### ISSUE TITLE
stats reports wrong active users

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3847]
Reticketed from https://github.com/gratipay/inside.gratipay.com/issues/382#issuecomment-150372263:

> What's with the dive in active users the past couple weeks?

![screen shot 2015-10-22 at 6 21 15 pm](https://cloud.githubusercontent.com/assets/134455/10679940/ba087ea2-78e9-11e5-9c4c-1f93e7342852.png)

Related to gratipay/gratipay.com#3841 per @rohitpaulk at https://github.com/gratipay/inside.gratipay.com/issues/382#issuecomment-150500368.

**Comment by rohitpaulk** [comment]
Closed in #3848
