### ISSUE TITLE
PayPal != Braintree

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3850]
Regression from #3565:

![screen shot 2015-10-26 at 9 52 32 pm](https://cloud.githubusercontent.com/assets/134455/10747474/f22835e4-7c2b-11e5-97d1-f8658fde37d3.png)

**Comment by kzisme** [comment]
Just wanted to quickly look into this...

Was looking at [this](https://github.com/gratipay/gratipay.com/blob/f9749d98d2853701968adf437e9436deca1741aa/www/~/%25username/routes/index.spt) and I was curious if that file should still contain remnants of "Balanced" at all.  

Also is the above link relevant at all to this issue? :stuck_out_tongue_winking_eye:

**Comment by mattbk** [comment]
@kzisme It looks like that's an admin link, so at least the users aren't seeing it right now?

Is this because of https://github.com/gratipay/gratipay.com/pull/3565/files#diff-adb0494911e9a62b5884a6e9eb56390d?

**Comment by kzisme** [comment]
@mattbk I believe that is what is causing it I suppose it should also be changed on admin pages too eh?
