### ISSUE TITLE
Improve schema for dues history

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#3851]
Reticketed from https://github.com/gratipay/gratipay.com/commit/918cf40a8727680377103970d80ea55c8fbb582b#commitcomment-13966584
##

**Comment by whit537** [comment]
I put this on Finish Teams Basics per https://github.com/gratipay/gratipay.com/pull/3873#issuecomment-165448321.

**Comment by whit537** [comment]
Aaaaaaaand I'm taking it off again, because https://github.com/gratipay/gratipay.com/issues/3992#issuecomment-207852330 and https://github.com/gratipay/gratipay.com/issues/3705#issuecomment-207852318.
