### ISSUE TITLE
Differentiate participants and projects

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3852]
Right now they're too close visually which is confusing. What's the difference between them?

![screen shot 2015-10-29 at 10 28 08 am](https://cloud.githubusercontent.com/assets/134455/10821248/c73592a2-7e27-11e5-9802-780c1fdc95aa.png)
![screen shot 2015-10-29 at 10 28 02 am](https://cloud.githubusercontent.com/assets/134455/10821249/c73a7d58-7e27-11e5-8181-3dd88349165b.png)
##

**Comment by whit537** [comment]
+1 https://github.com/gratipay/gratipay.com/issues/3853

**Comment by mattbk** [comment]
+1 from https://twitter.com/hadleywickham/status/688105609456058370.

**Comment by mattbk** [comment]
We've talked about parallels between these pages before, such as always having the donation action area on the left side (as shown in above screenshots). So I still think the ~user left sidebar should contain something like "Give to one of ~user's teams."

More extravagantly, how about ~user pages include team page snippets (the main body) that you can scroll through, each with its own donate button? Then each team page could be the reverse, and list the team members, albeit not with the donation links.

**catapultpgh's Teams**
![screen shot 2016-01-19 at 2 51 54 pm](https://cloud.githubusercontent.com/assets/3729038/12431684/642591b4-bebc-11e5-930e-4af3f1844ea6.png)
![screen shot 2016-01-19 at 2 51 54 pm](https://cloud.githubusercontent.com/assets/3729038/12431684/642591b4-bebc-11e5-930e-4af3f1844ea6.png)
![screen shot 2016-01-19 at 2 51 54 pm](https://cloud.githubusercontent.com/assets/3729038/12431684/642591b4-bebc-11e5-930e-4af3f1844ea6.png)

**Comment by mattbk** [comment]
+1 from https://gratipay.freshdesk.com/helpdesk/tickets/4104

**Comment by whit537** [comment]
+1 from @dakur in https://github.com/gratipay/gratipay.com/issues/3993:

> I found a link to this page: https://gratipay.com/~davegandy/ and I understood, that it should be page, where I can send some small amount of money to the user. But when I enter the page, I have no idea, what to do. There is nothing like "pay" or "give" or "send" button or something like that. Just "Search" ("what should I search?"), "Sign in" ("I don't want to sign in as I don't need to have profile on that page as I don't want to receive money from anyone") and links to social profiles ("I don't want to check the user's social profiles, I just want to send him some money."). So the only option I can do is to leave the page.
>
When I was thinking about it then, I would say, that I should sign up and sign in first and then somehow return to the user's page and there will be some "pay" button. But that's not intuitive and I don't want to create profile just to check out if this is the correct way to pay him.

**Comment by mattbk** [comment]
+1 from https://twitter.com/_jeremyharris/status/732759646268624896

> couldn't even find a damn donate button

**Comment by mattbk** [comment]
Any feedback on my idea here: https://github.com/gratipay/gratipay.com/issues/3852#issuecomment-172983882? We'd have to show just a teaser of the team description with a "read more" link.

**Comment by rohitpaulk** [comment]
I like the idea of making teams more prominent on ~user pages. 

I'm working on trying to create something that looks like: 

![img_20161030_171508](https://cloud.githubusercontent.com/assets/3893573/19836374/caf954c8-9ec4-11e6-9b97-84d6ac5a04dc.jpg)

**Comment by whit537** [comment]
@rohitpaulk Nice. Does it make sense to sync the visuals of that with the cards on the identities page? It could be a pattern we repeat across the site, payment methods also comes to mind.

**Comment by rohitpaulk** [comment]
> Does it make sense to sync the visuals of that with the cards on the identities page?

Yep, would be great if we could come up with a pattern that fit all of those. We could call this component a 'card' - it **must** contain an avatar + title text, and optionally **might** contain sub-text.

**Comment by whit537** [comment]
GitHub, for reference:

# Organization

![screen shot 2016-10-30 at 8 00 51 pm](https://cloud.githubusercontent.com/assets/134455/19841135/c833a68c-9edb-11e6-9197-43f967562e29.png)

# User

![screen shot 2016-10-30 at 8 01 02 pm](https://cloud.githubusercontent.com/assets/134455/19841136/c8465778-9edb-11e6-9df9-06007de04dc2.png)

**Comment by nobodxbodon** [comment]
Would it be a low-hanging fix to relabel and adjust layout like:
![screen shot 2016-12-21 at 5 58 27 pm](https://cloud.githubusercontent.com/assets/392497/21412708/25e774c2-c7a7-11e6-8dd9-374f315f308e.png)

**Comment by rohitpaulk** [comment]
Removing for now, focusing on bugs

**Comment by mattbk** [comment]
+1 from http://twitter.com/ABozicko/status/884031730436513792.

> @/sinemetu11 Hi, after half an hour of figuring out Gratipay for Poemmm, I give up. Just thought you might find it usefull x)

**Comment by mattbk** [comment]
> Would it be a low-hanging fix to relabel and adjust layout like:

How about a simple "X has no projects and cannot receive donations. Contact X to let them know you want to give!" under the "Projects" heading?

**Comment by mattbk** [comment]
+1 from https://github.com/aldeed/meteor-collection2-core/issues/32#issue-243209201.
