### ISSUE TITLE
add TransferWise as a regular payout method

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3855]
We've started using TransferWise for manual [1.0 payouts](https://medium.com/gratipay-blog/1-0-money-available-indefinitely-39c07bd031b) in situations where PayPal isn't an option. Can we add TransferWise as a first-class payout method so people can create Teams w/o PayPal?

Reticketed from https://github.com/naspeh/mailur/issues/4.

#### Notify:

- [ ] https://github.com/naspeh/mailur/issues/4
- [ ] https://gratipay.freshdesk.com/helpdesk/tickets/6190

##

**Comment by rohitpaulk** [comment]
Doesn't look like they have an API - I did see this on https://transferwise.com/partnerwise though

> In case you're looking for a different type of partnership / a partnership which requires product integration, please reach out to partners@transferwise.com

**Comment by whit537** [comment]
From https://github.com/gratipay/gratipay.com/issues/3944#issuecomment-194381204:

> Maybe this is a better alternative to #3870 than #726?

**Comment by nobodxbodon** [comment]
Re-ticketed to https://github.com/gratipay/inside.gratipay.com/issues/974 for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.
