### ISSUE TITLE
I don't understand the History page

### ISSUE THREAD

**Issue by dcht00** [gratipay/gratipay.com#3858]
A sketch of the situation:

* Before, I saw a bunch of "anonymous donations". You would relatively clearly see the incoming individual tips, and outgoing PayPal debits.
* This is now lost, it just says "Taken from [team]"
* It's not grouped into "Paydays" anymore. And it looks like some weeks, the donations aren't coming in at all. (Paydays 177,178,179)
* The amount "Taken from [team]" doesn't match what the team is getting. Sometimes it's just a few cents, sometimes it's double.

**Comment by whit537** [comment]
Sorry for the confusion, @dcht00. :-/

> - Before, I saw a bunch of "anonymous donations". You would relatively clearly see the incoming individual tips, and outgoing PayPal debits.
- This is now lost, it just says "Taken from [team]"

The anonymous donations are now to the Team, and the Team doesn't have a history page yet: #3759. +1 added for you there.

> - It's not grouped into "Paydays" anymore. And it looks like some weeks, the donations aren't coming in at all. (Paydays 177,178,179)

This I think has to do with the way charges in arrears are reported on history pages: #3834. +1 added for you there.

> - The amount "Taken from [team]" doesn't match what the team is getting. Sometimes it's just a few cents, sometimes it's double.

This is probably also related to #3834.

**Comment by whit537** [comment]
Closing here since I think these issues are covered in #3759 and #3834. Let's discuss further if I've got that wrong.
