### ISSUE TITLE
Project applications should have details and links

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3859]
- Details linking to TOS and [Glossary](https://github.com/gratipay/inside.gratipay.com/issues/243)
- Links to fix errors that come up during process

> @Gratipay To apply for a "team" (2.0???), I apparently need to link a PayPal account, but don't see the option to do so.

https://twitter.com/untitaker/status/670667868133019649

Also e.g., if you don't have an email address:

> 400
> Bad Request
> You must have a verified email address to apply for a new Team.
##

**Comment by mattbk** [comment]
Should be simple edit of https://github.com/gratipay/gratipay.com/blob/master/www/new.spt with /about/me links.

**Comment by mattbk** [comment]
Also at https://github.com/gratipay/gratipay.com/issues/3654.

**Comment by mattbk** [comment]
Nope, it's some other silliness with error code templates that I don't have time to figure out right now.

**Comment by mattbk** [comment]
Related: https://github.com/gratipay/team-review/issues/126#issuecomment-164890133

> As a future enhancement you might think about actually defining those terms out a little more (unless you already have this somewhere).

**Comment by whit537** [comment]
> I apparently need to link a PayPal account, but don't see the option to do so.

This might actually be https://github.com/gratipay/gratipay.com/issues/3654, ya?

**Comment by mattbk** [comment]
+1 from https://github.com/gratipay/team-review/issues/201#issuecomment-208356510

> I thought by on-boarding you meant "how to use this."

**Comment by whit537** [comment]
> I thought by on-boarding you meant "how to use this."

We did away with the onboarding links in #4222.

**Comment by whit537** [comment]
> Details linking to TOS and Glossary

We already link to TOS, and the glossary doesn't exist yet (and is hopefully unneeded with #4221).

> Links to fix errors that come up during process

Better addressed in https://github.com/gratipay/gratipay.com/issues/3654.

Closing.
