### ISSUE TITLE
offer other recurring schedules than weekly

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3862]
Gratipay has run on a weekly schedule since our inception. I propose that we loosen up. With [Gratipay 2.0](https://medium.com/gratipay-blog/gratipay-2-0-2453d3c53077) we now offer "payments and payroll for open work." We should offer all kinds of payments, not just weekly recurring payments. One-offs are #5. Here let's look at generalizing recurring payments.
##

**Comment by whit537** [comment]
One side-effect of this would be that we no longer need to track giving due for payin minimums, especially if we drop the minimum down to $1 (a la Patreon) or even lower: let the user pay the premium for a microtransaction, if they want. Eventually we should get around exorbitant microtransction fees with Dwolla (#65), or maybe someday even Coinbase. But in the mean time a user can pay $10 every three months or something. We charge them immediately and then every three months thereafter, rather than having to jump through hoops to keep track of the weekly buildup.

**Comment by whit537** [comment]
It's a UX problem: the difference between "due" and "receiving" is confusing.

**Comment by tshepang** [comment]
I much prefer we keep weekly payments as the only recurring option. Let that continue to be "our thing", keeping things simple too. Do you find we lose business because others want different recurring options?

**Comment by kzisme** [comment]
I'm assuming this was brought up since we are looking to do other types of transfers as well as the partnerships with different entities.  I believe one-off payments are crucial after pay-roll itself.  Other than that I feel that the weekly payment system is the most natural for most people.

**Comment by whit537** [comment]
> Do you find we lose business because others want different recurring options?

I doubt it'd be the first thing to optimize if we actually profiled it. I asked [on a call earlier today](https://www.youtube.com/watch?v=RkDSXUQO9ys#t=47m56s) and the answer was "weekly recurring is not a problem."

**Comment by fenryxo** [comment]
I'd prefer Gratipay payments to be monthly as the funding of the Nuvola Player project is aligned to [monthly fundraisers](https://tiliado.eu/nuvolaplayer/funding/). Processing of weekly payment takes more time as I have to record more individual payments in my funding tracking system. In addition, the switch to paying in arrears has made the weekly payments pretty unpredictable.

> Other than that I feel that the weekly payment system is the most natural for most people.

From my point of view, monthly payments are more natural than weekly ones. I receive my scholarship and salary monthly and I pay my rent/phone bill/insurance monthly as well.

**Comment by jcrben** [comment]
It makes more sense if, as a contributor, I can line up my banking transaction and my contribution transaction. The minimum banking transaction is $10. Currently I get that charge at some interval which is doled out over a period of weeks based on my total weekly contributions, which is unnecessarily complex.

I keep close track of all my transactions and I have little patience for lots of recurring small line items - I batch my transactions annually whenever possible. I refuse to use Patreon for that reason.

**Comment by whit537** [comment]
> Might make it more obvious that user can give fraction of dollar per week, or switch to per-month system.

https://twitter.com/JVimes/status/709575233603182593

**Comment by JVimes** [comment]
I'm 100% cool with transferring $10+ into Gratipay and lettings the micro-transactions happen within it. Once comfortable with the system, might load $50 in if it means saving fees.

**Comment by whit537** [comment]
Okay. We actually went to some trouble to [charge in arrears](https://medium.com/gratipay-blog/charging-in-arrears-18cacf779bee) instead of in advance. The way Gratipay currently works is that we keep track of your "giving due" until it reaches $10, *then* we charge you.

**Comment by JVimes** [comment]
Even better. ☺

**Comment by whit537** [comment]
Variable payin thresholds could come under https://github.com/gratipay/gratipay.com/issues/1063.
