### ISSUE TITLE
Allow donations to cover transaction fees

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3865]
From my comment at https://github.com/gratipay/inside.gratipay.com/issues/425#issuecomment-161722803:

Just read gratipay/gratipay.com#3862 (comment) and had an idea (not sure if it merits its own ticket yet). In the same way that we have talked about showing "excess" funds for teams, maybe we could encourage people to donate "excess" funds toward covering transaction fees for the smallest (below a certain value) donations.

This would essentially be a group pool; so rather than donating to a specific team (or to the Gratipay team), you'd be donating to everyone (both givers and receivers), by allowing them to keep more of their money.

It might be worthwhile to highlight how much users are paying in transaction fees on /about/charts as well, in order to encourage this.

Implementation could be an addition to a user's account in some way, or it could just be set up as a "special" Team--and then the receipts from that team each week could be used to replenish transaction fees.

Obviously not a priority, but just thinking about different ways for people to give.

ETA: ...although you could only distribute donated fees to people who had not donated their fees, otherwise the system wouldn't work. I suppose the idea of limiting this to the smallest receivers/largest givers could balance it out, though.
##

**Comment by whit537** [comment]
See #84 for another group pooling idea.
