### ISSUE TITLE
Payin + Payout via Uphold

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#3870]
https://uphold.com/en/developer/api/documentation/#introduction
##

**Comment by rohitpaulk** [comment]
Payouts look *very* promising. We could pay to a USD card, and users could use uphold to convert between USD <-> BTC.

**Comment by rohitpaulk** [comment]
https://support.uphold.com/hc/en-us/articles/205845376-In-which-countries-does-Uphold-offer-bank-account-funding-and-withdrawals-

**Comment by rohitpaulk** [comment]
People from other countries are allowed to be members though.

**Comment by whit537** [comment]
See also: https://github.com/naspeh/mailur/issues/4#issuecomment-158753298.

**Comment by mattbk** [comment]
I like options.

**Comment by whit537** [comment]
@kaguillera and I are prepared to account for this. Right, @kaguillera? :-)

**Comment by whit537** [comment]
I guess we'll need to sign up for an account and go through their due diligence process, eh?

**Comment by rohitpaulk** [comment]
@whit537 - Can you get started with that? At least we'll be able to clearly mark this ticket as 'Ready to start' or close it :)

**Comment by rohitpaulk** [comment]
> By integrating with Uphold’s seamless and open API; Uphold Connect, developers and third parties can create applications, products and services that instantly, and securely deliver and transfer any type of money or commodity to anyone, anywhere at no cost, including free currency conversations and storage. Uphold has built world-leading Know Your Customer (KYC) and Anti-Money Laundering (AML) controls right into its open API. This takes care of the regulatory burden and control requirements developers face when entering the financial economy, allowing innovation without restrictions on a globally compliant and robust platform.

**Comment by whit537** [comment]
> Can you get started with that?

Sure thing! :-)

**Comment by mattbk** [comment]
![200](https://cloud.githubusercontent.com/assets/3729038/12556462/9aa4f912-c34b-11e5-8b8d-5d3c4593e904.gif)

**Comment by whit537** [comment]
Hoping to dig into this tomorrow ...

**Comment by whit537** [comment]
Alright ...

**Comment by whit537** [comment]
/me watches their [intro video](https://uphold.com/release/images/homepage/intro-video.a73acdb8.mp4?v2.2.4)

**Comment by whit537** [comment]
Doing some digging.

http://fortune.com/2015/10/14/bitreserve-bitcoin-uphold/ ← Launched as Bitreserve in 2013, pivoted to Uphold in late 2014.

https://en.wikipedia.org/wiki/Halsey_Minor ← Founder. Made his money on CNET and Salesforce.

**Comment by whit537** [comment]
The question I'm asking is, what are the implications of Uphold for #3504?

**Comment by whit537** [comment]
Uphold requires users to join Uphold and go through identity verification on their side. Either, then:

 1. We decide that Uphold is going to be our new Balanced, and proactively drive our users to Uphold.
 1. Offer Uphold as an option for users who already have an Uphold account.

(1) is tempting, because they've got chops and capital and they're moving a lot faster than us. However, I see several risks down this path (eggs-in-one-basket, lack of control, making Halsey even richer), so we'd want to talk that through.

(2) should be driven by user demand. Do we have that yet? Do we have users clamoring for Uphold as a payments option?

**Comment by rohitpaulk** [comment]
Why not both?

**Comment by whit537** [comment]
Sure, I guess (1) is a superset of (2). Is that what you're saying?

**Comment by rohitpaulk** [comment]
Kinda. I see us doing exactly what we do with PayPal - If you have an account, you're welcome to link it.  If you don't - we'll encourage you to make one.

**Comment by whit537** [comment]
>  If you don't - we'll encourage you to make one.

Except that in the glorious future we want to be able to have users give *us* their identity info and bank details, so that we can deposit to them ourselves (via Transpay or ACH) rather than having another brand in between. Right?

**Comment by rohitpaulk** [comment]
> in the glorious future we want to be able to have users give us their identity info and bank details, so that we can deposit to them ourselves (via Transpay or ACH) rather than having another brand in between. Right?

That is the goal, yes :) My aim here is to get us some stability while we pursue that goal.

**Comment by whit537** [comment]
(Let's use https://github.com/gratipay/inside.gratipay.com/issues/479#issuecomment-175733684 for this convo).

**Comment by whit537** [comment]
I'm looking at creating an Uphold account, but it's not clear to me whether there's a difference between an individual and a business account.

**Comment by whit537** [comment]
I've created and confirmed email for an account. Looking at registering a dev app ... looking really nice ...

![screen shot 2016-02-05 at 9 19 37 pm](https://cloud.githubusercontent.com/assets/134455/12864024/3bb9b8a0-cc4e-11e5-8d4f-e58f3fbafba2.png)

![screen shot 2016-02-05 at 9 21 49 pm](https://cloud.githubusercontent.com/assets/134455/12864040/7f6de814-cc4e-11e5-8636-35377f0e1d1a.png)

**Comment by whit537** [comment]
I am reeeeeeeaaaalllllly wondering if we should go all-in on Uphold instead of rolling our own vault (https://github.com/gratipay/gratipay.com/issues/3504) and AML (https://github.com/gratipay/inside.gratipay.com/issues/119). What's our unique value proposition? Such existential questions!!!!

**Comment by whit537** [comment]
What specifically do you need in order to make progress here, @rohitpaulk?

**Comment by rohitpaulk** [comment]
> What specifically do you need in order to make progress here, @rohitpaulk?

I didn't see anything related to compliance when I signed up for a dev app - so I think sending them an email to confirm that our use case fits the bill should be enough for me to get started here.

**Comment by whit537** [comment]
https://support.uphold.com/hc/en-us/requests/new

![screen shot 2016-02-06 at 9 36 09 am](https://cloud.githubusercontent.com/assets/134455/12867196/175bbcc6-ccb5-11e5-9bb9-18079be48b3a.png)

**Comment by whit537** [comment]
Sent:

*Subject*: introducing Gratipay: a good fit?

> Greetings! I'm the founder of a payment processor called Gratipay. We've been around for about four years and have processed about $1M. Our niche is open-source software and other open culture projects. We currently support credit cards for payin, and PayPal for payouts. We're interested in adding Uphold as a payout method. Does this sound like a good fit?

**Comment by whit537** [comment]
A personal message to me from Halsey Minor! :scream_cat: 

> Our members are very important to us, and I personally want to ensure you have access to the right people in our team to provide you with the best possible experience. Drop us a line at:
>
 - partners@uphold.com - To learn about partnerships and our custom corporate services

https://gratipay.freshdesk.com/helpdesk/tickets/4052

**Comment by whit537** [comment]
Heard back from a sales rep: "This sounds like an excellent fit!" Gave me a link to schedule a call ...

> Thanks, []! I've scheduled a call for today at 2:30 PM (US/Eastern). Looking forward to it! :-)

@rohitpaulk I would've tried to work around your schedule so you could join the call, but all of the available times were in the afternoon US/Eastern. You're still welcome to join, of course. :)

-----------------

> P.S. Gratipay is an open company, which means (among other things) that we do our internal decision making in public. For your reference, I'll be summarizing our conversation on this public ticket:
>
https://github.com/gratipay/gratipay.com/issues/3870 
>
Talk soon! :-)

**Comment by rohitpaulk** [comment]
That looks like 1 AM for me, if I'm not wrong. If so, 80% probability that I'll attend :)

**Comment by whit537** [comment]
Okay! What's your Skype?

**Comment by whit537** [comment]
@rohitpaulk Or contact request me, I'm whit537 on Skype.

**Comment by rohitpaulk** [comment]
I've added you on Skype. I don't think basic Skype accounts support group calls, we might have to shift to Google Hangouts

**Comment by whit537** [comment]
Gotcha. I did find this:

> And now everyone has group video calling for free, it’s easier than ever.

http://www.skype.com/en/features/group-video-chat/

**Comment by rohitpaulk** [comment]
Aha, perfect

**Comment by whit537** [comment]
Sent a contact request on Skype and left a message for the Uphold sales rep. Waiting to hear bac.

**Comment by whit537** [comment]
Emailed:

> We on for a call or should we reschedule?

**Comment by rohitpaulk** [comment]
@whit537 - Looks like you haven't accepted the contact request yet, so I'm unable to call you

**Comment by whit537** [comment]
Really? I think I did accept it.

![screen shot 2016-02-10 at 2 38 10 pm](https://cloud.githubusercontent.com/assets/134455/12959323/f572e97a-d003-11e5-9330-530a412346c7.png)

**Comment by whit537** [comment]
I'm chatting with the sales rep in Skype, setting up the call ...

**Comment by whit537** [comment]
@rohitpaulk Privacy settings?

![screen shot 2016-02-10 at 2 40 54 pm](https://cloud.githubusercontent.com/assets/134455/12959421/52b83a4a-d004-11e5-8921-f076495fabdc.png)

**Comment by rohitpaulk** [comment]
Lemme check

**Comment by rohitpaulk** [comment]
I'm not getting any of those messages :|

**Comment by rohitpaulk** [comment]
> You need one member of the group who is a friend with all of the other members of the group, and he has to start the group chat (by adding all the other members).

> The friends status must be confirmed, ie the others must accept the request-just sending a request is not enough.

**Comment by rohitpaulk** [comment]
<img width="266" alt="screen shot 2016-02-11 at 1 19 56 am" src="https://cloud.githubusercontent.com/assets/3893573/12959698/98cf55a0-d05d-11e5-80ef-d1e99a4ac58a.png">

**Comment by whit537** [comment]
!m @rohitpaulk 

For the record, we got @rohitpaulk in for the second half of the call.

**Comment by whit537** [comment]
> I think my desktop client was outdated, on web now

**Comment by whit537** [comment]
Okay! So ... what did we learn?

 - Uphold has 60-70 employees worldwide.
 - Currently U.S. and Europe. They are working on payouts to Mexico now, aiming for India this summer.
 - We can only pay out in fiat currencies *to Uphold customers*. It's currently possible to pay out to raw bitcoin(!), but it sounds like they're going to tighten that up as well over the course of the year.
 - He made some interesting comments about payroll being "easier" from a regulatory standpoint,  referring obliquely to [money transmission exemptions](https://github.com/gratipay/inside.gratipay.com/issues/201#issuecomment-111157623). I didn't dig.
 - They're trying to differentiate from "wallet" on the one hand (crowded market: PayPal, Google Wallet—"novelty products"), and "bank" on the other (regulatory burden, "nerdy reasons")—"we call it cloud money" "for consumers, more utility etc. etc.; for our partners, the AWS of money"
 - We have limited access to identity information via OAuth (we specifically *don't* get the JPG of their passport).
 - They have a compliance department that'll do due diligence before we can get started. He hinted that their compliance department may require ongoing due diligence on *our* customers as well(!).

The next step is this [compliance form](https://www.cognitoforms.com/UpholdInc/BusinessAccountApplication).

**Comment by whit537** [comment]
Anything I missed, @rohitpaulk?

**Comment by whit537** [comment]
![screen shot 2016-02-10 at 3 28 02 pm](https://cloud.githubusercontent.com/assets/134455/12960749/eb8c62f4-d00a-11e5-82ee-fc7144404f80.png)

We got bit by this before by StartSSL if I remember right. Maybe I should get a business phone line at the house just for this purpose.

**Comment by whit537** [comment]
We forging ahead with compliance, @rohitpaulk?

**Comment by whit537** [comment]
We can try using our latest LLC amendment for address verification, I'm pretty sure I changed our registered address to 716 Park Road.

**Comment by rohitpaulk** [comment]
> We can only pay out in fiat currencies to Uphold customers. It's currently possible to pay out to raw bitcoin(!), but it sounds like they're going to tighten that up as well over the course of the year.

In the first case, all liability is on Uphold - they'll handle KYC on their end. In case of paying out to raw bitcoin (people who don't have a Uphold account), we'll have to provide them some information about the users we're paying out to - which would bring us back to #2449.

**Comment by rohitpaulk** [comment]
> We forging ahead with compliance, @rohitpaulk?

Yes :beers:

**Comment by whit537** [comment]
> Thanks for the call. As a reminder, here is the link to our business account application process. When you are done with that process, let's schedule more time to talk, and try to map out more of the solution!
>
https://www.cognitoforms.com/UpholdInc/BusinessAccountApplication

**Comment by whit537** [comment]
Took a look at this, figured I'd try using our LLC organization papers as proof of address. Started off well enough ...

![screen shot 2016-02-23 at 9 10 19 am](https://cloud.githubusercontent.com/assets/134455/13254361/073d2a5c-da0f-11e5-9ada-747d8a9b0142.png)
![screen shot 2016-02-23 at 9 10 41 am](https://cloud.githubusercontent.com/assets/134455/13254365/073ec196-da0f-11e5-8b23-5da8344076ad.png)
![screen shot 2016-02-23 at 9 11 09 am](https://cloud.githubusercontent.com/assets/134455/13254364/073d5162-da0f-11e5-97eb-4ee453515b87.png)

**Comment by whit537** [comment]
But then ... :flushed:


![screen shot 2016-02-23 at 9 12 06 am](https://cloud.githubusercontent.com/assets/134455/13254363/073d688c-da0f-11e5-9b81-ae88a25339df.png)
![screen shot 2016-02-23 at 9 12 18 am](https://cloud.githubusercontent.com/assets/134455/13254362/073d384e-da0f-11e5-9283-3143051e6ab4.png)
![screen shot 2016-02-23 at 9 12 27 am](https://cloud.githubusercontent.com/assets/134455/13254366/073fb95c-da0f-11e5-92e9-4e914fb30fb1.png)
![screen shot 2016-02-23 at 9 12 52 am](https://cloud.githubusercontent.com/assets/134455/13254367/074549e4-da0f-11e5-9160-9c2b63968378.png)
![screen shot 2016-02-23 at 9 13 01 am](https://cloud.githubusercontent.com/assets/134455/13254370/07485ee0-da0f-11e5-95c7-7d73aad21355.png)
![screen shot 2016-02-23 at 9 13 19 am](https://cloud.githubusercontent.com/assets/134455/13254372/074a3d8c-da0f-11e5-9260-7e81f6f0b60f.png)
![screen shot 2016-02-23 at 9 13 31 am](https://cloud.githubusercontent.com/assets/134455/13254368/0745dbe8-da0f-11e5-81d7-9ef1307810c8.png)
![screen shot 2016-02-23 at 9 13 44 am](https://cloud.githubusercontent.com/assets/134455/13254371/074925b4-da0f-11e5-859e-f043d7024564.png)
![screen shot 2016-02-23 at 9 14 00 am](https://cloud.githubusercontent.com/assets/134455/13254369/0746f1d6-da0f-11e5-99bf-9adb7262d18b.png)
![screen shot 2016-02-23 at 9 14 08 am](https://cloud.githubusercontent.com/assets/134455/13254373/074d4b80-da0f-11e5-97c3-38913ebde5be.png)
![screen shot 2016-02-23 at 9 14 17 am](https://cloud.githubusercontent.com/assets/134455/13254374/074d975c-da0f-11e5-9922-6d7bc078accb.png)
![screen shot 2016-02-23 at 9 14 26 am](https://cloud.githubusercontent.com/assets/134455/13254376/074f075e-da0f-11e5-88b8-20a16d86e400.png)
![screen shot 2016-02-23 at 9 14 40 am](https://cloud.githubusercontent.com/assets/134455/13254375/074f0998-da0f-11e5-8031-8910f69c041b.png)
![screen shot 2016-02-23 at 9 14 53 am](https://cloud.githubusercontent.com/assets/134455/13254377/07536dc6-da0f-11e5-9d80-3d67687670fc.png)
![screen shot 2016-02-23 at 9 18 03 am](https://cloud.githubusercontent.com/assets/134455/13254378/075aeaec-da0f-11e5-8262-013c1c316570.png)
![screen shot 2016-02-23 at 9 18 15 am](https://cloud.githubusercontent.com/assets/134455/13254381/075c8f50-da0f-11e5-88dc-73ec29147998.png)
![screen shot 2016-02-23 at 9 18 25 am](https://cloud.githubusercontent.com/assets/134455/13254379/075ae0e2-da0f-11e5-9df3-1345123a2f7e.png)
![screen shot 2016-02-23 at 9 18 34 am](https://cloud.githubusercontent.com/assets/134455/13254382/075cbfb6-da0f-11e5-8436-504a5a7f2868.png)
![screen shot 2016-02-23 at 9 18 45 am](https://cloud.githubusercontent.com/assets/134455/13254383/075ed1b6-da0f-11e5-8ee1-68bb02bfbece.png)
![screen shot 2016-02-23 at 9 18 55 am](https://cloud.githubusercontent.com/assets/134455/13254380/075bdd12-da0f-11e5-87bc-fa254e9a4cdc.png)
![screen shot 2016-02-23 at 9 19 05 am](https://cloud.githubusercontent.com/assets/134455/13254385/07629a3a-da0f-11e5-9531-55bbd549cf43.png)
![screen shot 2016-02-23 at 9 19 16 am](https://cloud.githubusercontent.com/assets/134455/13254384/07627aaa-da0f-11e5-857b-61d28c7c7e5c.png)
![screen shot 2016-02-23 at 9 19 30 am](https://cloud.githubusercontent.com/assets/134455/13254386/07639fca-da0f-11e5-85c4-24cf8b19348b.png)
![screen shot 2016-02-23 at 9 19 44 am](https://cloud.githubusercontent.com/assets/134455/13254387/07653380-da0f-11e5-9f0d-0dd3217ac0b1.png)
![screen shot 2016-02-23 at 9 19 56 am](https://cloud.githubusercontent.com/assets/134455/13254388/0768504c-da0f-11e5-9545-4a7eed3ce0e4.png)
![screen shot 2016-02-23 at 9 20 08 am](https://cloud.githubusercontent.com/assets/134455/13254389/07691bd0-da0f-11e5-813f-56e199af4c73.png)
![screen shot 2016-02-23 at 9 20 17 am](https://cloud.githubusercontent.com/assets/134455/13254390/076e48a8-da0f-11e5-9928-95d8ff9d673a.png)

**Comment by whit537** [comment]
We're right back to #3504 and https://github.com/gratipay/inside.gratipay.com/issues/214.

**Comment by whit537** [comment]
@rohitpaulk What do you see as next steps here?

**Comment by rohitpaulk** [comment]
I don't think this'll pan out anytime soon :confused: Shall we focus on https://github.com/gratipay/gratipay.com/issues/726 for the time being?

**Comment by whit537** [comment]
> Shall we focus on #726 for the time being?

Sounds like a plan ...

**Comment by mattbk** [comment]
Blocked by paperwork.

**Comment by whit537** [comment]
@mattbk More than just paperwork, I'm afraid. It's gonna take a lot of work to be able to answer their questions well!

**Comment by whit537** [comment]
[text version](https://gist.github.com/whit537/ce969dc9f75d2aa3fd36)

**Comment by nobodxbodon** [comment]
Re-ticketed to https://github.com/gratipay/inside.gratipay.com/issues/974 for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.
