### ISSUE TITLE
Changing team name does not auto-update slug/url

### ISSUE THREAD

**Issue by Sirjazzfeet** [gratipay/gratipay.com#3871]
I would like to change team name from below to "Citizens Network"
https://gratipay.com/citizens-cooperative/

**Comment by rohitpaulk** [comment]
```sql
=> UPDATE teams SET slug='citizens-network', slug_lower='citizens-network', name='Citizens Network' WHERE slug = 'citizens-cooperative';
UPDATE 1
```

Change made - https://gratipay.com/citizens-network/ :)

@Sirjazzfeet - I'll let you close this once you've verified the change. I've also added a +1 for you at https://github.com/gratipay/gratipay.com/issues/3545#issuecomment-164170493.

**Comment by whit537** [comment]
!m @rohitpaulk

**Comment by Sirjazzfeet** [comment]
Great, Thank you.

**Comment by mattbk** [comment]
@Sirjazzfeet, you can now edit your team info on the team page if you need to in the future.

**Comment by Sirjazzfeet** [comment]
@mattbk I did notice on Twitter, but thanks.

**Comment by Sirjazzfeet** [comment]
I would like to change team name from below to "Citizens Connect"
https://gratipay.com/citizens-network/

**Comment by mattbk** [comment]
You can now edit the team name yourself from the team page when you are logged in.

**Comment by Sirjazzfeet** [comment]
Thanks @mattbk - will url auto update?

**Comment by Sirjazzfeet** [comment]
reopening issue.

**Comment by mattbk** [comment]
Hmm, not sure if the slug will change on its own. Will ask later today.

**Comment by aandis** [comment]
It will not. See https://github.com/gratipay/gratipay.com/pull/3943#issuecomment-193881034 for related discussion.

**Comment by aandis** [comment]
Also, we use team slug for referencing other tables instead of using ids. So changing one team slug could do a lot of cascade updates (if that's specified in the schema at all)

**Comment by rohitpaulk** [comment]
I'm not sure what should be done here - should we change the URL automatically? Maybe we should make it configurable?

**Comment by rohitpaulk** [comment]
Dupe of #4373, looks like. Closing. @Sirjazzfeet I've added a +1 for you on #4373
