### ISSUE TITLE
admin should be able to disconnect credit card

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3879]
The disconnect button uses the authenticated user in the URL, not the user being viewed.

https://github.com/gratipay/gratipay.com/blob/1931/js/gratipay/routes.js#L39

**Comment by whit537** [comment]
ref.: https://gratipay.freshdesk.com/helpdesk/tickets/3641

**Comment by whit537** [comment]
Workaround:

```
$ heroku run python
>>> from gratipay import wireup
>>> env = wireup.env()
>>> wireup.db(env)
>>> wireup.billing(env)
>>> from gratipay.models.participant import Participant
>>> from gratipay.models.exchange_route import ExchangeRoute
>>> p = Participant.from_username('foo')
>>> route = ExchangeRoute.from_address(p, 'braintree-cc', 'deadbeef')
>>> route.invalidate()
```
```

**Comment by mattbk** [comment]
`deadbeef`?

**Comment by whit537** [comment]
`deadbeef` is a [metasyntactic variable](https://en.wikipedia.org/wiki/Metasyntactic_variable) like "foo," used for hex code-ish strings.

**Comment by mattbk** [comment]
Duplicate of https://github.com/gratipay/gratipay.com/issues/3548.
