### ISSUE TITLE
Botwiki team logo update request

### ISSUE THREAD

**Issue by fourtonfish** [gratipay/gratipay.com#3884]
Hi,

Could someone update the logo for [gratipay.com/botwiki-org](https://gratipay.com/botwiki-org/) for me?

Thank you in advance!

![botwiki-logo-615](https://cloud.githubusercontent.com/assets/3909390/11984958/21974d08-a98e-11e5-84b4-f1bdc93a8be8.png)

**Comment by mattbk** [comment]
Moving this over to https://github.com/gratipay/team-review/issues/68.
