### ISSUE TITLE
Support PaySafeCard

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3889]
Via https://gratipay.freshdesk.com/helpdesk/tickets/3837 (Facebook):

> Can you please support PaySafeCard?

This was mentioned previously in https://github.com/gratipay/gratipay.com/issues/126.
##

**Comment by nobodxbodon** [comment]
Re-ticketed to https://github.com/gratipay/inside.gratipay.com/issues/974 for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.
