### ISSUE TITLE
Explain Week 154 (post-Gratipay 2.0) on stats page

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3890]
Might be worth a link to the blog post launching 2.0.

From https://news.ycombinator.com/item?id=10834974:
> Gratipay Stats page ( https://gratipay.com/about/stats ) shows that on week 152, the total amount received by teams at Gratipay was $8652 and there were 2814 active users. Then all numbers dropped to 0 on week 153. But on week 154, the total amount received is only $1179 and there were only 639 active users. These numbers stay low since then. Why?

(I did attempt to answer this on that page today, but others probably have the same question.)

**Comment by whit537** [comment]
I think we still have a `note` class in CSS for this.

`<p class="note">Week 153 was the <a href="">Gratipocalypse</a>.</p>`

Something like that under the chart title.
