### ISSUE TITLE
Speed up tip migration script

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#3894]
Reticketed from https://github.com/gratipay/inside.gratipay.com/issues/468#issuecomment-171707621

When we wrote this script, we thought that we'd only be using it for a month or two. Now that it's here to stay - time to work on it a bit :) 

The script takes so long because we're pulling in *all* approved teams. We could place a check in the script so that we only pull in those teams that satisfy the following criteria - 

1) Team owner must have 0+ tips from Gratipay 1.0
2) Team must have zero `payment_instructions` that have a `ctime` lesser than the team's `ctime` (i.e. migrated tips). We use the `ctime` attribute to differentiate `payment_instructions` that were created as a result of migrated tips vs created in Gratipay 2.0

https://github.com/gratipay/gratipay.com/blob/master/bin/migrate-tips.py#L6-L10

**Comment by rohitpaulk** [comment]
!m @aandis

**Comment by aandis** [comment]
!m @rohitpaulk

**Comment by whit537** [comment]
!m @aandis @rohitpaulk :dancer:
