### ISSUE TITLE
Call to action on ~users without teams

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3903]
From https://github.com/gratipay/inside.gratipay.com/issues/472#issuecomment-173678430:

> Would adding a ~~call to action~~ special note on ~users without teams pages help (perhaps once we [make the pages distinct](https://github.com/gratipay/gratipay.com/issues/3852))?
> 
> > "This user is not on any teams, but if they're doing something cool and you want to give to them, why not tag them on social media and ask them to start a team?"
> 
> Sort of like the old way where you could give to people before they had an account (caught the mention of that in the call on Tuesday; didn't realize it had been dropped). CTA could be something like  we have here: https://gratipay.com/on/twitter/realdonaldtrump/.
##

**Comment by rohitpaulk** [comment]
If we could clearly distinguish between users who joined with the intention to receive money vs give money - that should make sense (on pages of users who intend to receive)

**Comment by mattbk** [comment]
That makes sense, but I'm not sure it's necessary. Because there's no real user directory anymore, most visits to user pages should probably be from following links elsewhere online--implying that this user is interested in receiving tips. Additionally, if the CTA is for the visitor to use regular social networks to say "hey, I'll donate if you create a team," rather than a button on Gratipay that automates bothering the user, it's more organic and less likely to be abused.

We could also add an opt-out-of-receiving checkbox, but I thought we used to have one of those anyway.

**Comment by mattbk** [comment]
Related: https://github.com/gratipay/gratipay.com/issues/4067
