### ISSUE TITLE
Review 0a546eb  

### ISSUE THREAD

**Issue by techtonik** [gratipay/gratipay.com#3907]
I hit `commit to master` again while editing in 0a546eb. Please review if it is ok.

**Comment by techtonik** [comment]
The "successfully canceled" sounds strange to me.

**Comment by rohitpaulk** [comment]
:+1:

**Comment by techtonik** [comment]
@rohitpaulk thanks!

**Comment by whit537** [comment]
> I hit `commit to master` again while editing in 0a546eb.

:disappointed:
