### ISSUE TITLE
Use only one api for getting and setting payment instructions.

### ISSUE THREAD

**Issue by aandis** [gratipay/gratipay.com#3913]
Reticketed from https://github.com/gratipay/gratipay.com/pull/3909#issuecomment-180403944.

> @aandis I think it's best to have one API that both we and third parties use. Maybe we should:
> 1. Drop the singular %team/payment-instruction.json.spt
> 2. Change our views that use the singular endpoint to use the plural ~/%username/payment-instructions.json.spt instead.
##

**Comment by rohitpaulk** [comment]
-ve on this, I think we should have long living endpoints for thirdparties - probably versioned too, like `api/v1/username/payment-instructions.json` etc. 

We could start out with using those internally, but in the future we should be able to change our internal use patterns without changing the thirdparty endpoints.

**Comment by aandis** [comment]
> we should be able to change our internal use patterns without changing the thirdparty endpoints.

True. But then the important question to ask is, why was it decided to expose `payment-instruction.json` as an api instead of using it only internally? Having two apis which do more or less similar stuff can be confusing.
