### ISSUE TITLE
Charts.json bad request on team

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3914]
```
{
    "error_code": 400,
    "error_message_long": "Missing key: u'username'",
    "error_message_short": "Bad Request"
}
```

**Comment by rohitpaulk** [comment]
https://github.com/gratipay/gratipay.com/pull/3873 should fix this, leaving this here for reference

**Comment by mattbk** [comment]
Looks fixed. Contains data for teams you have access to, empty `[]` for teams you don't.
