### ISSUE TITLE
fix deployment to work w/ a fully-protected branch

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3915]
We protected `master` at https://github.com/gratipay/inside.gratipay.com/issues/487#issuecomment-180008641. First deploy since then reveals a problem:

```
remote: -----> Launching...
remote:        Released v1566
remote:        https://gratipay.herokuapp.com/ deployed to Heroku
remote:
remote: Verifying deploy.... done.
To git@heroku.com:gratipay.git
   4dd7fec..2c5ccd2  master -> master
Counting objects: 14, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (13/13), done.
Writing objects: 100% (14/14), 1.37 KiB | 0 bytes/s, done.
Total 14 (delta 9), reused 0 (delta 0)
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: Required status check "continuous-integration/travis-ci" is expected
To git@github.com:gratipay/gratipay.com.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:gratipay/gratipay.com.git'
$
```
##

**Comment by whit537** [comment]
I relaxed the protection for admins as a workaround.

![screen shot 2016-02-09 at 3 06 52 pm](https://cloud.githubusercontent.com/assets/134455/12929045/ccfcb662-cf3e-11e5-9bf9-15510a802f38.png)

**Comment by whit537** [comment]
I made a @gratipay/deployers team w/ @rohitpaulk @clone1018 and myself with admin access on the repo so we can deploy.

**Comment by whit537** [comment]
Looks like all three of us have 2FA set up, which is good.

**Comment by nobodxbodon** [comment]
Seems like done in short term. BTW issues like this seem to be better in inside.gratipay.com to me.

**Comment by whit537** [comment]
> Seems like done in short term.

Does it? How?

> BTW issues like this seem to be better in inside.gratipay.com to me.

Why? The issue is specific to gratipay.com, no?
