### ISSUE TITLE
payout via ACH

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3920]
#3366 unraveled but the dream is still alive! Blocked on

Some good background: http://www.programmableweb.com/news/ordering-%E2%80%9Csecret-menu%E2%80%9D-ach-payment-platforms/analysis/2016/02/16.

Payin is #777.
##

**Comment by nobodxbodon** [comment]
Re-ticketed to https://github.com/gratipay/inside.gratipay.com/issues/974 for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.
