### ISSUE TITLE
Method for eliminating teams created by security checks?

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3925]
Looks like someone has been testing the new team form. Is there a way to clear these, or a term we can tell security researchers to use so they don't show up on the website?

**Comment by aandis** [comment]
Perhaps introduce captchas to disallow bots at least? This will also make it a bit tedious for spammers.

**Comment by mattbk** [comment]
I've never seen any spam activity, I'm not sure why not. I think recent activity is because we're pushing HackerOne security bounties. Since there aren't a whole lot of public-facing forms, seems like they're "attacking" the create team page.

![image](https://cloud.githubusercontent.com/assets/3729038/13253463/d1060268-da01-11e5-9f87-b87a66dbfd7b.png)

**Comment by mattbk** [comment]
@aandis [pointed out to me](https://github.com/gratipay/team-review/issues/168) that anyone with admin access can do this manually.

See also: https://github.com/gratipay/team-review/issues/170

![image](https://cloud.githubusercontent.com/assets/3729038/13303762/be02502a-db16-11e5-97b1-67d95daaeba5.png)
