### ISSUE TITLE
Make new team application and edit to work even without js

### ISSUE THREAD

**Issue by aandis** [gratipay/gratipay.com#3930]
Reticketed from https://github.com/gratipay/gratipay.com/pull/3923#issuecomment-189099923

> I wonder if there is a way to make it work even without JS though. It might not be possible in this case, but worth looking into. If we can make it such that submitting the form before the JS kicks in gives us a slightly worse user experience, but the same functionality (no weird errors) that'd be cool.

**Comment by rohitpaulk** [comment]
I'm -ve on this. Too much to maintain + a lot of core features don't work without JS already (sign-in/sign-up, editing profile etc).

**Comment by whit537** [comment]
Heh. Looks like you proposed the idea originally, @rohitpaulk. ;-)

Closing ...

**Comment by rohitpaulk** [comment]
Haha :D Evolution
