### ISSUE TITLE
No "Edit your team" link

### ISSUE THREAD

**Issue by stevepiercy** [gratipay/gratipay.com#3932]
Team KnopProject does not have a link to "Edit your team" as shown in #3923. I have tried logged in as either the user ~KnopProject and ~stevepiercy. ~stevepiercy is the owner of the team KnopProject.

**Comment by aandis** [comment]
@stevepiercy #3923 is not live yet. You'll see the link once it's deployed. :)

**Comment by stevepiercy** [comment]
OK, I thought I had missed something. Thanks.
