### ISSUE TITLE
Allow Team owners to manage/add/remove members

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3935]
Splitting this off from https://github.com/gratipay/gratipay.com/issues/3545.

https://github.com/gratipay/gratipay.com/issues/3545#issuecomment-136154542

#### Notify

- [ ] https://gratipay.freshdesk.com/helpdesk/tickets/3126

**Comment by whit537** [comment]
@mattbk Are you thinking we'll allow adding Team members before we bring back payroll itself?

**Comment by mattbk** [comment]
It could be possible, although it would require a lot of explaining.

Is there a ticket for this technical aspect of bringing back Payroll? I mostly wanted to distinguish this from "edit teams" (which is done).

**Comment by whit537** [comment]
> It could be possible, although it would require a lot of explaining.

Agreed.

> Is there a ticket for this technical aspect of bringing back Payroll? I mostly wanted to distinguish this from "edit teams" (which is done).

We have #3433 but that's pretty general. I think having a ticket for this is fine, but I'm not sure about having it on the `Team Basics` milestone. Why'd you go for that instead of `Payroll`?

**Comment by mattbk** [comment]
+1 from @stevepiercy at https://github.com/gratipay/gratipay.com/issues/3681#issuecomment-135148451:

> when I log in as ~stevepiercy and view my account profile, I expect to see a UI for me to manage Team KnopProject, but cannot find one. I couldn't manage the Team, so I assume one of the Gratipay staff assigned me as Owner on my behalf. Is some public Team management UI is forthcoming?

**Comment by whit537** [comment]
Closing this ticket now that we have #3994, where this idea is captured as part of our plan to bring back payroll for Team Gratipay. Looks like the "notify" here is already cross-listed over on #3433.
