### ISSUE TITLE
Trending teams

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3939]
Could calculate and display teams that are showing the most growth in either number of givers or amount being received. Stats page or part of a more general "find teams" system (https://github.com/gratipay/gratipay.com/issues/3127, https://github.com/gratipay/gratipay.com/issues/3938, etc.).

**Comment by aandis** [comment]
https://github.com/gratipay/gratipay.com/issues/3736?

**Comment by mattbk** [comment]
I think that's related, but in order to incorporate #3127 it might need to not be on the front page. Or maybe that's a simple dropdown in the UI that could be made to look okay.

**Comment by aandis** [comment]
> number of givers or amount being received.

I meant these two could be part of those sort, but the sorting thing will probably be on the homepage.

**Comment by mattbk** [comment]
How often would the "trending" calculator run? I assume we have other processes that run on a schedule, could this be rolled in to recalculate a database value for `is_trending`?

**Comment by whit537** [comment]
FYI we do have some [cron-ish infrastructure](https://github.com/gratipay/gratipay.com/blob/1942/gratipay/main.py#L82-L88).

**Comment by whit537** [comment]
We might also consider migrating cron-ish work out of the web app and over to @gratipay-bot.

**Comment by mattbk** [comment]
> We might also consider migrating cron-ish work out of the web app and over to @gratipay-bot.

Out of curiosity, why?

**Comment by whit537** [comment]
Because it's hackish to have async tasks running in a thread in the main web app server. It makes it complicated to scale beyond one webserver, because one generally wants to scale async workers separately from web workers.

**Comment by mattbk** [comment]
>  It makes it complicated to scale beyond one webserver, because one generally wants to scale async workers separately from web workers.

Ahh, that makes sense. So @gratipay-bot could do its thing over multiple servers if needed, whereas crontab would need to be mirrored to each machine.

**Comment by mattbk** [comment]
* http://stackoverflow.com/questions/787496/what-is-the-best-way-to-compute-trending-topics-or-tags
    * specifically http://stackoverflow.com/a/826509/2152245

**Comment by mattbk** [comment]
Inspiration at http://github.com/explore:

![image](https://cloud.githubusercontent.com/assets/3729038/13750192/60f8d802-e9d2-11e5-9b94-ea096f0fd004.png)

Twitter:
![image](https://cloud.githubusercontent.com/assets/3729038/13750202/70457036-e9d2-11e5-83bb-71c1071ea8ce.png)
