### ISSUE TITLE
Fix max image size in error messages. 

### ISSUE THREAD

**Issue by aandis** [gratipay/gratipay.com#3942]
From https://github.com/gratipay/gratipay.com/pull/3923

> The UI seems to suggest that the maximum size is 256kb, but the error notif says it is 100kb

On experimenting with different image sizes, the correct max image size appears to be 256kB.

**Comment by whit537** [comment]
> On experimenting

@aandis Note that source code is [available](https://github.com/gratipay/gip.rocks/blob/b3ada5c5b137907868aaafe2361c39b906c93c13/www/v1.spt#L12). ;-)
