### ISSUE TITLE
Allow classification/tagging/other of ~users and Teams

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#3963]
The natural result of closing https://github.com/gratipay/gratipay.com/issues/3127. That thread has several idea about how to proceed, but this thread is starting from a position of ignoring previous communities and starting with a blank slate.

How do we want to 
- help discovery of projects by potential contributors
- help discovery of projects by potential givers
- help teams realize they aren't alone (within their area of interest) in using Gratipay

Freetagging is one natural option; are there others?

**Comment by mattbk** [comment]
Inspiration:
![image](https://cloud.githubusercontent.com/assets/3729038/13750145/363e845e-e9d2-11e5-808a-c13b58f05a51.png)

**Comment by mattbk** [comment]
+1 from https://github.com/gratipay/team-review/issues/141#issuecomment-171751680.

> I admit it's a bit unwieldy at the moment, but rather than maintaining a separate list of "good" applications, I think the long-term answer is add better discoverability features to Gratipay so that you are empowered to determine for yourself which approved Teams are similar to yours.

**Comment by whit537** [comment]
Picking up from the [levels](https://github.com/gratipay/gratipay.com/issues/3736#issuecomment-248949250) idea ... how about badges?

https://wiki.mozilla.org/Badges
https://openbadges.org/
https://osf.io/tvyxz/wiki/home/
http://stackoverflow.com/help/badges
https://badges.fedoraproject.org/
https://www.reddit.com/wiki/awards
&nbsp; (I love impressing the likes of @oakes with my [Ten Year Club trophy](https://www.reddit.com/user/whit537/)! :)

**Comment by whit537** [comment]
National identities are possibly related to this.

![screen shot 2016-12-08 at 6 26 49 pm](https://cloud.githubusercontent.com/assets/134455/21031881/e6fefb8c-bd73-11e6-9e30-dd98260c11df.png)

**Comment by whit537** [comment]
"You've been awarded the `JavaScript` badge!"

**Comment by whit537** [comment]
> I will also be adding a Contributor Club badge added to your Opensource.com profile soon.
