### ISSUE TITLE
SEPA / IBAN payment

### ISSUE THREAD

**Issue by n1trux** [gratipay/gratipay.com#3967]
Hey, since I don't like paying with PayPal or Credit Card, could you add the option to pay via wire transfer over IBAN/SEPA?

**Comment by whit537** [comment]
I was about to create this ticket from your email to support. :-)

We've done a couple wire transfers to pay *out*, happy to have this ticket for pay *ins*.

**Comment by whit537** [comment]
Payout: https://github.com/gratipay/inside.gratipay.com/issues/249.

**Comment by whit537** [comment]
> I was about to create this ticket from your email to support. :-)

Sorry, I'm a dork. What I saw was the GitHub notification from this ticket ... not an email to support. Perhaps contributing to my confusion was Gmail's helpful warning:

![screen shot 2016-03-17 at 7 25 18 am](https://cloud.githubusercontent.com/assets/134455/13844657/77294576-ec11-11e5-9ca5-57e626720e03.png)


:-)

**Comment by nobodxbodon** [comment]
Re-ticketed to https://github.com/gratipay/inside.gratipay.com/issues/974 for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.
