### ISSUE TITLE
Resend verification email is broken.

### ISSUE THREAD

**Issue by aandis** [gratipay/gratipay.com#3982]
[Resend verification email](https://github.com/gratipay/gratipay.com/blob/master/www/~/%25username/emails/verify.html.spt#L84) calls [`Gratipay.settings.post_email`](https://github.com/gratipay/gratipay.com/blob/master/www/~/%25username/emails/verify.html.spt#L35) which is not defined anywhere. 
Should call [`Gratipay.emails.post`](https://github.com/gratipay/gratipay.com/blob/master/js/gratipay/emails.js#L3).

**Comment by whit537** [comment]
Blech.

(P.S. GitHub [protip](https://help.github.com/articles/getting-permanent-links-to-files/): "When viewing a file on GitHub, you can press the 'y' key to update the URL to a permalink to the exact version of the file you see.")
