### ISSUE TITLE
Travis says this is not an active repository

### ISSUE THREAD

**Issue by aandis** [gratipay/gratipay.com#3988]
https://travis-ci.org/gratipay/gratipay.com

![screenshot from 2016-04-06 22 50 52](https://cloud.githubusercontent.com/assets/4983347/14326100/07d0482a-fc4a-11e5-9efc-b9c80e9eb0b4.png)

I think we are pretty active. ;)

**Comment by whit537** [comment]
What's up with that? The build history is current (though what's up with the recent fails?):

https://travis-ci.org/gratipay/gratipay.com/builds

@aandis Wanna reach out to Travis support?

**Comment by whit537** [comment]
> though what's up with the recent fails?

Buncha 502s

**Comment by rohitpaulk** [comment]
![bugs](http://s2.quickmeme.com/img/2e/2e241cbbfa40b515d22f0718ddaab4f25631dfed32a8c3e571ae5a5533e92406.jpg)

**Comment by aandis** [comment]
> @aandis Wanna reach out to Travis support?

Before that, a quick google search shows many matching [results](http://www.google.com/#q=travis+this+is+not+an+active+repository). Can it because of [this](https://github.com/travis-ci/travis-ci/issues/5629#issuecomment-184246684)?

**Comment by aandis** [comment]
>> though what's up with the recent fails?

> Buncha 502s

Tests pass locally though..

**Comment by whit537** [comment]
> Tests pass locally though..

Yeah, it's because we don't hit external APIs locally, but we do on master. Probably worth investigating, reticketed as https://github.com/gratipay/gratipay.com/issues/3989.

**Comment by whit537** [comment]
Indeed.

![screen shot 2016-04-06 at 2 11 30 pm](https://cloud.githubusercontent.com/assets/134455/14327716/8249fe1e-fc01-11e5-82d4-e5c0817bce3d.png)

**Comment by whit537** [comment]
![screen shot 2016-04-06 at 2 12 29 pm](https://cloud.githubusercontent.com/assets/134455/14327757/afc2934c-fc01-11e5-942d-2be35773a400.png)
![screen shot 2016-04-06 at 2 12 51 pm](https://cloud.githubusercontent.com/assets/134455/14327756/afc07616-fc01-11e5-84b5-5adc5aa27651.png)

**Comment by whit537** [comment]
!m @aandis
