### ISSUE TITLE
investigate failing master on Travis

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3989]
Reticketed from #3988.

**Comment by whit537** [comment]
This is still an issue:

![screen shot 2016-07-12 at 11 48 18 am](https://cloud.githubusercontent.com/assets/134455/16773773/363d00e4-4827-11e6-8e50-44094003594c.png)

**Comment by whit537** [comment]
Doesn't seem to be a single issue, though they appear to generally be network-related:

https://travis-ci.org/gratipay/gratipay.com/builds/144060555#L1031-L1032

There's a bunch of:

> assert <ErrorResult 'Transaction can only be voided if status is authorized or submitted_for_settlement.' at 2b11c259a810>.is_success

https://travis-ci.org/gratipay/gratipay.com/builds/138327150#L1050
https://travis-ci.org/gratipay/gratipay.com/builds/138247355#L1028
https://travis-ci.org/gratipay/gratipay.com/builds/138246002#L1022
https://travis-ci.org/gratipay/gratipay.com/builds/138243055#L1025
https://travis-ci.org/gratipay/gratipay.com/builds/138242378#L1020

**Comment by whit537** [comment]
Is this a dupe of #3266?

**Comment by whit537** [comment]
No. They're two different errors.

**Comment by nobodxbodon** [comment]
Please reopen if this still happens.

**Comment by whit537** [comment]
I'm not finding a good history view in Travis for the master branch. I _think_ the past few have been okay? 😕
