### ISSUE TITLE
disconnecting an elsewhere sends to user instead of ~user

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#3991]
1. connect an elsewhere
2. disconnect the elsewhere

Shouldn't see `/user/` in the network console, only `/~user/`.

Seeing `/user/` in the network console.

**Comment by emanwebdev** [comment]
+1

**Comment by rohitpaulk** [comment]
Hmm, I think this has been fixed - 

<img width="699" alt="screen shot 2016-10-31 at 5 51 41 pm" src="https://cloud.githubusercontent.com/assets/3893573/19854023/bcf97550-9f92-11e6-9cf8-6df6be21dd6b.png">
