### ISSUE TITLE
get Font Awesome back on Gratipay

### ISSUE THREAD

**Issue by dakur** [gratipay/gratipay.com#3993]
I found a link to this page: https://gratipay.com/~davegandy/ and I understood, that it should be page, where I can send some small amount of money to the user. But when I enter the page, I have no idea, what to do. There is nothing like "pay" or "give" or "send" button or something like that. Just "Search" ("what should I search?"), "Sign in" ("I don't want to sign in as I don't need to have profile on that page as I don't want to receive money from anyone") and links to social profiles ("I don't want to check the user's social profiles, I just want to send him some money."). So the only option I can do is to leave the page.  
When I was thinking about it then, I would say, that I should sign up and sign in first and then somehow return to the user's page and there will be some "pay" button. But that's not intuitive and I don't want to create profile just to check out if this is the correct way to pay him.

**Comment by whit537** [comment]
Sorry for the frustration, @dakur, and thanks for reaching out. What's going on is that ~davegandy is a *~user* account, and you can only give to *Team* accounts.

(Background: We used to support giving to ~users. This changed last year with [Gratipay 2.0](https://gratipay.news/gratipay-2-0-2453d3c53077), but many links still point to ~user pages. However, we do need to do a better job of differentiating ~user and Team pages; I've added a +1 for you to #3852.)

More to the point: We would love to have Font Awesome as a Team on Gratipay! :-)

@davegandy Any interest in (re-)[signing up](https://gratipay.com/new) for Gratipay 2.0? :-)

**Comment by davegandy** [comment]
Sure. I just noticed I stopped receiving gratipay a while back. How do I sign up again? Do I need to do it through Font Awesome?

**Comment by whit537** [comment]
@davegandy Yay! 💃 

> How do I sign up again?

 1. Sign in to [Gratipay](https://gratipay.com/) using either of these:
  - your @davegandy GitHub account, *or*
  - the [@fontawesome](https://twitter.com/fontawesome) Twitter account.
 1. Fill out the application at https://gratipay.com/new.
 1. Bear with us during [our review process](http://inside.gratipay.com/howto/review-teams).

After Step 2 you'll have a ticket in our [review repo](https://github.com/gratipay/team-review) and we can pick up the conversation over there. If you get stuck before then drop a line here.

Thanks! :-)

**Comment by davegandy** [comment]
I just applied, but think I misunderstand teams now. I just want folks to be able to donate to Font Awesome. Is that not what this is?

**Comment by davegandy** [comment]
And my username is wonky. It tells me the username "davegandy" is taken.

**Comment by mattbk** [comment]
> I just applied, but think I misunderstand teams now. I just want folks to be able to donate to Font Awesome. Is that not what this is?

You did the right thing.

> And my username is wonky. It tells me the username "davegandy" is taken.

Checking...

**Comment by mattbk** [comment]
You have an existing account at https://gratipay.com/~davegandy/ (hooked up to two social accounts). 

@whit537 is it possible to change the ownership of https://gratipay.com/Font-Awesome/ to https://gratipay.com/~davegandy/ ?

**Comment by whit537** [comment]
> @whit537 is it possible to change the ownership of https://gratipay.com/Font-Awesome/ to https://gratipay.com/~davegandy/ ?

Done! :-)

@davegandy Sorry the way we use social logins is making things confusing. 😞  To manage your Gratipay account in the future you'll need to sign in with `GitHub/davegandy` or `Twitter/fontawesome` (*not* `Twitter/davegandy`).

| | Twitter | GitHub |
|:---|:-------:|:----------:|
| `@davegandy` | ❌ | ✅ |
| `@fontawesome` | ✅ | ❌ |

**Comment by whit537** [comment]
> I just applied, but think I misunderstand teams now. I just want folks to be able to donate to Font Awesome. Is that not what this is?

Gratipay Teams are for two things:

 1. folks to be able to donate to Font Awesome
 1. Font Awesome to be able to share income with collaborators

Buuuuuut (2) is actually vaporware right now, and will be for a while yet (https://github.com/gratipay/gratipay.com/issues/3433). 😖 

Are you generally open to sharing Font Awesome income with your collaborators?

**Comment by mattbk** [comment]
We're not quite done with the transfer, waiting on a PayPal address before payday will work: https://github.com/gratipay/team-review/issues/206#issuecomment-217161588

**Comment by mattbk** [comment]
> We're not quite done with the transfer, 

Done now. Looks like there was a payout, even though https://gratipay.com/Font-Awesome/ doesn't show any reciving.

**Comment by whit537** [comment]
I think we're good! 💃 

![screen shot 2016-05-31 at 5 58 38 pm](https://cloud.githubusercontent.com/assets/134455/15691902/63edfff0-2759-11e6-8b95-566376e77c54.png)
