### ISSUE TITLE
Create a widget service that identifies user by linked identity.

### ISSUE THREAD

**Issue by ironchefpython** [gratipay/gratipay.com#400]
This is the current widget code for embedding .  

```
<iframe style="border: 0; margin: 0; padding: 0;"
    src="https://www.gittip.com/username/widget.html"
    width="48pt" height="22pt"></iframe>
```

Unfortunately, when automatically embedding this widget in a github or twitter page, the owner of that page might have a different github or twitter username than their gittip username.  There should be a way to generate a widget that looks up the gittip information when given an idenitiy provider and username.

As a starting point, perhaps a url of the form: 

`https://www.gittip.com/id/` <identity provider> `/` <username> '/widget.html'

So for example, my widget would be loaded via `https://www.gittip.com/id/github.com/ironchefpython/widget.html`
##

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
