### ISSUE TITLE
Simplates <---> URL mapping

### ISSUE THREAD

**Issue by techtonik** [gratipay/gratipay.com#4021]
How hard it is for simplate to figure out its own URL and map it to repository location? In other words:

How can https://github.com/gratipay/gratipay.com/blob/master/www/about/index.spt place GitHub link to itself in https://gratipay.com/about/ ?

**Comment by whit537** [comment]
We do something like that on Inside Gratipay with the edit / history / comment links at the bottom. Maybe go digging there?
