### ISSUE TITLE
Flesh out about/features/payments with regard to uneven payments and arrears

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#4022]
Running into some questions from users, [one of whom writes](https://gratipay.freshdesk.com/helpdesk/tickets/4827) (after I tried to explain)

> It kind of helps, but I still don't get it and it deeply worries me.

"Deeply worries" is not something we want to hear!

The main question is 

> 1) I'm receiving $x.xx, but where is this showing up consistently, like $ rolling in every week on some balance?

- [x] I need to dig around the issues and PRs a little more to refresh my memory on this, but just glancing at https://gratipay.com/about/features/payments, it seems like more detail is warranted.

### Notify
- [ ] https://gratipay.freshdesk.com/helpdesk/tickets/4827

**Comment by mattbk** [comment]
Also link to docs from

- team history 
- user history

**Comment by mattbk** [comment]
I think this is right (draft of customer email). @rohitpaulk, does this make sense?

> I'm not sure that bouncing cards are included, but this is unclear at https://gratipay.com/about/features/payments#receiving-less. The other explanations there explain why your payouts are volatile.
> At https://gratipay.com/TEAM/receiving/, there is a section for funded and unfunded dues. Funded dues (29.50) have a working credit card attached, but the user has not reached the $10 threshold where we actually charge the card. Unfunded dues (3.00) have a credit card that has failed. You'll also see that your estimated payment for next week is 34.60.

**Comment by rohitpaulk** [comment]
@mattbk - Yes, that looks right.

**Comment by mattbk** [comment]
Running into more need for https://github.com/gratipay/inside.gratipay.com/issues/117.
