### ISSUE TITLE
Credit Card input field doesn't play nicely with Chrome's credit card auto fill feature

### ISSUE THREAD

**Issue by JVimes** [gratipay/gratipay.com#4041]
Chrome has a secure way to store credit card info and auto-fill it. The input field (under /routes/credit-card) doesn't seem to play nicely with it. When I start typing in the field, I expect Chrome to suggest saved credit cards. In the case of Gratipay, the suggestion doesn't happen unless I type a little and then hit backspace.

**Comment by whit537** [comment]
Interesting. Okay, thanks for the report, @JVimes.

**Comment by JVimes** [comment]
Just FYI, I ran into this a second time today (previous credit card cancelled). I know it's not the highest priority, but should be an easy client side fix ☺️

**Comment by mattbk** [comment]
https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill for future reference.

**Comment by whit537** [comment]
Sorry @JVimes. 😕  Do you happen to know what the fix is off-hand?

@mattbk Can you see what the fix is from the link there?

**Comment by JVimes** [comment]
@whit537, @mattbk I found two things that seem to work, at least in devtools:
 * Removing `autocomplete="off"` from the form. Oddly, this doesn't work on the original form, but does work if I copy/paste the form so there are now two forms, and I edit the new copy.
 * Disabling JavaScript fixes it without editing HTML or messing with autocomplete.

**Comment by mattbk** [comment]
Thanks for digging in, @JVimes. I can't play with this until tonight at the earliest.

**Comment by whit537** [comment]
Maybe someone from 24 Pull Requests could pick this one off?

https://twitter.com/Gratipay/status/806918094199230464

**Comment by mattbk** [comment]
Locally I'm not secure!
![screen shot 2016-12-08 at 9 38 48 pm](https://cloud.githubusercontent.com/assets/3729038/21036892/c6772720-bd8e-11e6-976f-35fe4f5e4063.png)
