### ISSUE TITLE
implement Estonian identity verification

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4054]
While [considering](https://github.com/gratipay/inside.gratipay.com/issues/438) evolving our corporate structure, we learned about [Estonia's next-gen national identity implementation](https://e-estonia.com/e-residents/about/) (and now [I'm an e-Resident](https://github.com/gratipay/inside.gratipay.com/issues/438#issuecomment-225232814)! :). They have a _much_ cleaner solution to national identity verification than the current ugly hackish kludge of cross-checking passports through identity wholesalers (https://github.com/gratipay/gratipay.com/issues/2449). It's still early days for this, but it seems not unlikely to be the future—[Kaspar](https://www.linkedin.com/in/kasparkorjus) reported at [OuiShare Fest](https://github.com/gratipay/inside.gratipay.com/issues/314) that he knows of "[five countries who are copying this at the moment](https://www.youtube.com/watch?v=c7mR9y3N4ck#t=18m46s)."

I want to verify my identity on Gratipay using my Estonian e-Resident smart card!

**Comment by techtonik** [comment]
Nice. If we have a link how to legally receive funds from Gratipay LLC. in Estonia (pay taxes etc.) - that would help a lot to get more users from this country.
