### ISSUE TITLE
Allow for contributions without account (specifically one-off ones)

### ISSUE THREAD

**Issue by Jaxkr** [gratipay/gratipay.com#4069]
I know this is already an issue, but seriously, it would make your platform not dead anymore.

**Comment by whit537** [comment]
#5 is our ticket for one-time giving. I don't recall whether we already have a ticket about giving without registering an account, so I guess let's use this for that unless someone finds an previous ticket. I think implementing one-time gifts/payments would be a prerequisite for "unregistered" (?) giving. I.e., I think first we'd implement one-time gifts from registered accounts, and then expand that to include unregistered folks. Does that sound right?

**Comment by whit537** [comment]
Whether that's sufficient to make us not dead anymore remains to be seen. ;-)
