### ISSUE TITLE
allow manual additions/withdrawals

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4071]
Companies spending money through Gratipay—whether giving (cf. #1199) or distributing (i.e., wanting to only use Gratipay for take-what-you-want payouts)—will want more control over the flow of funds.

(This may be a dupe.)

**Comment by mattbk** [comment]
Will this increase the amount held in escrow? Maybe it would balance out.

**Comment by whit537** [comment]
> Will this increase the amount held in escrow?

It very well might, yes.
