### ISSUE TITLE
Changed GitHub username, things explode

### ISSUE THREAD

**Issue by ntnsndr** [gratipay/gratipay.com#4080]
Dear Gratipay friends,

I just changed my GitHub username from nathanairplane > ntnsndr. I was using that to log in to Gratipay, at which my username was nathanairplane. Now when I log in at Gratipay, my username is ntnsndr and it's a blank account. Also, I need to change my credit card details for payments. Can my nathanairplane account be transferred to my new GitHub login, ntnsndr? Let me know how to proceed.

Thanks.

**Comment by mattbk** [comment]
Is this your old account? https://gratipay.com/~nathanairplane/

If so, you should be able to follow these steps:
- log in and close your new https://gratipay.com/~ntnsndr account (https://gratipay.com/about/me/settings/close)
- log in with Twitter to https://gratipay.com/~nathanairplane/
- make sure you are logged into GitHub on the right account
- on your profile (https://gratipay.com/~nathanairplane/), scroll down to "Social Profiles" and click [+ Add] by GitHub
- confirm that Gratipay is allowed to use your GitHub credentials 

This should connect your new GitHub username to your existing account.

If https://gratipay.com/~nathanairplane/ is *not* you, please let us know.

**Comment by ntnsndr** [comment]
Awesome, thank you! That did the trick.

**Comment by mattbk** [comment]
Glad to help.
