### ISSUE TITLE
Review of the French translation

### ISSUE THREAD

**Issue by nashe** [gratipay/gratipay.com#4081]
Aloha,

I just finished translating the ~200 sentences that were missing for the French locale (and reached the 100% goal).
I contacted Changaco on IRC (because he's the only reviewer for this language) and he told me that he's no more working on this projects. Do you know another active translator that could review my work?

I think there will be some fixes to apply once deployed, but definitely, it should not look too bad :-)

Edit: There are some reviewed strings I need to edit, if somebody can "unreview" it for me…

**Comment by whit537** [comment]
Merci beaucoup, @nashe! I've just done the following:

- Removed @Changaco from our Transifex team.
- Sent you an invite to be our Language Coordinator for French! If you're up for it? :-)
- Set the "[Translator Instructions URL](http://inside.gratipay.com/howto/translate-gratipay)" (while I was at it :).

If you accept the Language Coordinator invite, does that enable you to edit reviewed strings?

**Comment by whit537** [comment]
I just deployed, which should've picked up your translations. :)

**Comment by nashe** [comment]
I accepted the invite and I can now change the strings I had to, thanks!

My translations were correctly pushed on Github, but nothing changed on https://gratipay.com/, since I haven't reviewed my work on Transifex (see [Makefile:L102](https://github.com/gratipay/gratipay.com/blob/master/Makefile#L102)). I'll try to do it today.

**Comment by whit537** [comment]
Awesome, drop a line here or on the [Tech Radar](https://github.com/gratipay/inside.gratipay.com/issues?utf8=%E2%9C%93&q=is%3Aopen%20label%3ATech%20label%3ARadar%20) when you're ready for another deploy! :-)

**Comment by nashe** [comment]
Fixed few more things related to the French translation (it was causing display issues), you'll just have to fetch the latests files on your next deploy! Closing this issue since we don't really need it anymore.

**Comment by whit537** [comment]
Awesome! Updating translations happens automatically during deploy ... I've deployed. :)
