### ISSUE TITLE
Not compliant with GNU LibreJS (i.e. FSF FreeJS)

### ISSUE THREAD

**Issue by sampablokuper** [gratipay/gratipay.com#4084]
Please can the Gratipay website either:
- (ideally) not require visitors to execute JavaScript; or
- (failing that) comply with GNU LibreJS as per the FSF's [FreeJS](https://fsf.org/campaigns/freejs) initiative?

Thanks!

**Comment by whit537** [comment]
Why are we not already compliant with FreeJS?

**Comment by sampablokuper** [comment]
> Why are we not already compliant with FreeJS?

The JavaScript on gratipay.com is not currently [labelled in a way that is detectable by LibreJS](https://www.gnu.org/software/librejs/free-your-javascript.html).

**Comment by whit537** [comment]
PRs welcome.
