### ISSUE TITLE
Allow teams to opt out of receiving

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#4088]
> If you're asking to derive your daily bread from open source work through community donations, you'll work to ensure the stability of that bread — inspiration or not.

From http://david.heinemeierhansson.com/2013/the-perils-of-mixing-open-source-and-money.html, thanks @whit537 for the link over at https://github.com/gratipay/inside.gratipay.com/issues/683.

This is an edge case, but what if a team shuts down for a while? For teams of one especially, there may be periods where the owner is not taking enough contributions to warrant working on the product full time, while also not being able to work on the project due to other commitments. In such a case, the owner may feel that continued acceptance of contributions is unethical, even though people contributing feel that their support is warranted because they value the product. This puts the owner in a bind; currently they would have no choice but to shut down the team if they didn't wish to receive contributions.

This isn't likely to happen (almost everyone who builds a product is underpaid for it), but in the vein of [consent](http://inside.gratipay.com/big-picture/brand/), shouldn't there be a way for an owner to turn off taking without leaving the team?

A question to go along with this, and maybe it's the way forward: If no user takes from a team, does that team still receive?

**Comment by whit537** [comment]
> currently they would have no choice but to shut down the team

They can't even do _that_ until https://github.com/gratipay/gratipay.com/issues/3602. :-/

> shouldn't there be a way for an owner to turn off taking

Sounds like a subset of https://github.com/gratipay/inside.gratipay.com/issues/432.
