### ISSUE TITLE
Forbid the username ".."

### ISSUE THREAD

**Issue by nashe** [gratipay/gratipay.com#4089]
Reported by [sh4dow](https://hackerone.com/sh4dow) (thanks!) on HackerOne ([#152477](https://hackerone.com/reports/152477)):

> If I change my username to "test" then as in normal case it will send a GET request to /test/settings but if I change my username to ".." (double dot within inverted commas) then it will send GET request to /settings because /../settings will change to /settings and hence final GET request will be to /settings which will show a 404 page.

 

> Moreover if username etc exists then https://gratipay.com/etc/ will redirect me to actual profile link https://gratipay.com/~etc/ but https://gratipay.com/../ will not redirect me to actual profile link https://gratipay.com/~../

It's not presenting any security issue, but it can be problematic for some users.

**Comment by whit537** [comment]
> it can be problematic for some users.

I think it's only problematic for this one user, right? What's happening is that some layer (the browser? the server?) is interpreting `..` as "parent directory" and so is sending, e.g., https://gratipay.com/../ to https://gratipay.com/. I think this behavior is a fitting reward for `..`'s clever choice of username. ;-)

**Comment by nashe** [comment]
Oops, I was doing something else at the same time and got mind-fuck*d. It'll only be problematic for the user so-called `..` :-)

**Comment by nashe** [comment]
Obviously a very low priority, just to avoid 404 if the username is displayed somewhere on the site ("Team xx owned by ..").

**Comment by whit537** [comment]
I'm gonna go ahead and close as wont-fix. A user has already claimed the username `..`, and links to https://gratipay.com/~../ should work as expected.
