### ISSUE TITLE
Auto-logout after 20 minutes?

### ISSUE THREAD

**Issue by nashe** [gratipay/gratipay.com#4096]
Was reading some code when I saw something related to the issue [H1-123897](https://hackerone.com/reports/123897).

We already have [some timeout](https://github.com/gratipay/gratipay.com/blob/f211a35bba1f90fb396a242a6dc1c1931f89041d/gratipay/security/user.py#L12). 

Is it really useful to decrease the time to 20 minutes? I find already the 6 hours really short compared to the other websites. No credit card data is displayed and if somebody tries to change your Paypal email, you get a notification since he has to add an email to your account. In addition, if we start requiring to enter the password again for sensitive actions, it won't be really needed.

What are you thoughts about this?

**Comment by whit537** [comment]
> In addition, if we start requiring to enter the password again for sensitive actions, it won't be really needed.

I'm fine with this approach. We incorporate both financial and social elements. The financial elements (payment methods, transaction details) should be considered sensitive, but not the social elements (profiles, team pages).

**Comment by nashe** [comment]
Closing this issue in favour of one related to password confirmation, then.
