### ISSUE TITLE
Switch to another Markdown renderer

### ISSUE THREAD

**Issue by nashe** [gratipay/gratipay.com#4101]
In order to be able to fix 4~5 behaviours reported on HackerOne, I'm planing to change the Markdown parser we are using. Misaka is fast (if not the fastest—everything is parsed/handled/rendered using the C module) but we don't have much control over the "extensions" (I did not even figured out how to create a new one without having to fork the whole project). The current settings will be "migrated" to the new renderer, to keep the same functionalities.

[mistune](https://github.com/lepture/mistune) sounds promising: we can create "renderers" and "lexers" to change the behaviour or add our own formats (not really needed at the moment, but… elegant).

If somebody have anything to point out before I work on this, just let me know!

**Comment by EdOverflow** [comment]
I was wondering if there's any progress on the issue.

**Comment by nashe** [comment]
Hi @EdOverflow! Unfortunately not, since I don't have to contribute to Gratipay anymore (I hope it'll change soon). 
The idea was to find a good and extensible Markdown parser. I don't think that speed is one real issue so we don't really need to find a native Python module (and take the associated risks—you'll have some bad surprises if you fuzz the most known ones for few hours!). The _extensible_ part is required in order to add restrictions we can't apply with the current parser. 
This is not really one urgent issue since I don't remember any high-risk issue on HackerOne which is related to the Markdown parser. The amount of work needed just to fix content-spoofing-related issues is disproportionate :-)

**Comment by Changaco** [comment]
The <https://github.com/liberapay/liberapay.com/pull/502> PR, which upgrades Misaka from v1 to v2, contains a Renderer subclass that would also be useful with Mistune.
