### ISSUE TITLE
fix a spurious test failure

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4118]
Timing w/ a TTW test.

https://travis-ci.org/gratipay/gratipay.com/builds/156678522

**Comment by whit537** [comment]
https://travis-ci.org/gratipay/gratipay.com/builds/156686933

**Comment by rohitpaulk** [comment]
Screenshots please :) Travis links aren't persistent, both the links above point to 💚 builds

**Comment by whit537** [comment]
Eep! Sorry about that. Closing for now until I see this again ...

**Comment by whit537** [comment]
Here's one:

https://travis-ci.org/gratipay/gratipay.com/builds/156897977#L1077-L1094

```
______________________ Tests.test_owner_can_add_a_member _______________________
self = <test_team_distributing.Tests testMethod=test_owner_can_add_a_member>
    def test_owner_can_add_a_member(self):
        self.sign_in('picard')
        self.visit('/TheEnterprise/distributing/')
        self.css('.lookup-container .query').first.fill('alice')
        time.sleep(0.1)
        self.css('.lookup-container button').first.click()
        time.sleep(0.1)
>       assert [a.text for a in self.css('table.team a')] == ['alice']
E       AssertionError: assert [] == ['alice']
E         Right contains more items, first extra item: 'alice'
E         Use -v to get the full diff
tests/ttw/test_team_distributing.py:26: AssertionError
```

![screen shot 2016-09-01 at 2 58 15 pm](https://cloud.githubusercontent.com/assets/134455/18180360/87554d38-7054-11e6-9787-fc6629c1d564.png)

**Comment by whit537** [comment]
I am hitting this regularly.

**Comment by whit537** [comment]
PR in #4129 ...
