### ISSUE TITLE
update policies in light of recent downtime

### ISSUE THREAD

**Issue by arcfide** [gratipay/gratipay.com#4124]
Where would I check to find out the status of the Gratipay website and services?

**Comment by rohitpaulk** [comment]
Gratipay indeed *was* down, I restarted the dynos and looks like it is back up now. 

<img width="1920" alt="screen shot 2016-09-04 at 1 24 18 pm" src="https://cloud.githubusercontent.com/assets/3893573/18229779/fecfc1fe-72a2-11e6-8b41-55fd33cb7b6a.png">

**Comment by rohitpaulk** [comment]
@arcfide We've got some stats up on http://inside.gratipay.com/appendices/health

**Comment by rohitpaulk** [comment]
<img width="1920" alt="screen shot 2016-09-04 at 1 26 49 pm" src="https://cloud.githubusercontent.com/assets/3893573/18229790/45b05ac0-72a3-11e6-9b2e-e42a23bf0814.png">

**Comment by rohitpaulk** [comment]
Was down for over an hour 😕

**Comment by rohitpaulk** [comment]
Heroku shows alerts on its dashboard - 

<img width="1231" alt="screen shot 2016-09-04 at 1 29 12 pm" src="https://cloud.githubusercontent.com/assets/3893573/18229809/a36acc36-72a3-11e6-940d-3858f5d4b926.png">

**Comment by rohitpaulk** [comment]
According to the graphs, this is the time window we were down for:

**4th September 2016** 
06:10 AM - 07:50 AM

**Comment by rohitpaulk** [comment]
:( We've exhausted our papertrail capacity, so can't view logs

<img width="1053" alt="screen shot 2016-09-04 at 1 32 32 pm" src="https://cloud.githubusercontent.com/assets/3893573/18229821/0f1bb508-72a4-11e6-84b9-8baff3c6bacc.png">

**Comment by rohitpaulk** [comment]
No new events on [Sentry](https://sentry.io/gratipay/gratipay-com)

**Comment by rohitpaulk** [comment]
- [ ] Fix/Re-activate pagerduty alerts
- [ ] Upgrade papertrail plan

**Comment by rohitpaulk** [comment]
I don't see any obvious traffic spikes

**Comment by rohitpaulk** [comment]
No hackerone reports either

**Comment by rohitpaulk** [comment]
Heroku has a button to 'Configure Alerts', but I'm not able to click on it - I guess this is because we're using Hobby dynos, not the Professional ones

**Comment by arcfide** [comment]
Glad to see it back up. I can't tell from the above trail whether the Gratipay team is automatically notified of downtime or not? Anyways, glad to see that things are up. Hope the above issues are easily resolved. Keep up the good work.

**Comment by rohitpaulk** [comment]
:) We used to have pagerduty alerts long ago, I think that our subscription has either expired or we haven't set them up properly. 

https://github.com/gratipay/gratipay.com/issues/4124#issuecomment-244589602 is my checklist for how we can better address such situations in the future

**Comment by techtonik** [comment]
https://github.com/gratipay/inside.gratipay.com/issues/790

**Comment by techtonik** [comment]
Need a speccy for engineering max uptime reliability (SLA?), of which monitoring is a critical step:

* [ ] notify when Gratipay is down
  * [ ] notification list with free subscribe
* [ ] provide manual instructions for troubleshooting downtime
  * [ ] make it starting from http://status.gratipay.com
  * [ ] make mechanism to ensure instructions are always up to date
* [ ] deploy status/monitoring server on independent server
  * [ ] make sure monitor is monitored

Do I overengineer it? =)

**Comment by techtonik** [comment]
> :( We've exhausted our papertrail capacity, so can't view logs

What a fail. Paying money just to know one that "you haven't been paying enough, sorry". =)

I guess there are no any distributed monitoring solutions that ping each other and send alerts when only one monitoring node is left. I guess each node should know somehow that it is still connected to the net, so that it won't go into panic and start collecting deferred alerts in mailbox.

If that was possible, I could run monitor on my machine too.

**Comment by whit537** [comment]
Blech. 😞

> Fix/Re-activate pagerduty alerts

We do have PagerDuty still, and I did get SMS notifications for this. I didn't see them until after seeing this, however. Maybe a new ticket to sort out a PagerDuty rotation?

**Comment by whit537** [comment]
> Maybe a new ticket to sort out a PagerDuty rotation?

Or we can do it here. I guess we take the payday rotation as our pattern? Should it be the same rotation? cc: @clone1018

**Comment by techtonik** [comment]
Why there is no service like http://www.fedmsg.com/en/latest/ where any can subscribe?

**Comment by rohitpaulk** [comment]
How bout we just fan out messages - and the first person to see them will respond?

**Comment by rohitpaulk** [comment]
(rather than rotation)

**Comment by techtonik** [comment]
Yea, and ping someone who can ping someone who can ping the servers. =)

**Comment by whit537** [comment]
> How bout we just fan out messages - and the first person to see them will respond?

I like the idea of fanning out messages, but I think we should also have someone on call, or it will only be a matter of time before an incident occurs and no-one sees it for longer than we'd like.

**Comment by whit537** [comment]
> Fix/Re-activate pagerduty alerts

@rohitpaulk You should have a Pagerduty invite. I guess for now adding you to the list is doubling our capacity, ya?

> Upgrade papertrail plan

Is the $7 a month plan okay?

| $ / mo | MB / day | search (days) | archive (days) |
|-------:|----------:|---------:|----------:|
| 0 | 10 | 2 | 7 |
| 7 | 50 | 7 | 365 |
| 15 | 100 | 7 | 365 |
| 29 | 200 | 7 | 365 |
| 65 | 500 | 7 | 365 |

**Comment by whit537** [comment]
I'm seeing SMS notifications that we were down for about two hours earlier today (ending about six hours ago).

**Comment by whit537** [comment]
@rohitpaulk Looks like you accepted the PagerDuty invite. Did you receive the notifications? Did you take any action?

**Comment by whit537** [comment]
Hmm ... now it's looking like we got DOS'd by a security researcher. The timeline syncs up with https://hackerone.com/reports/172573.

**Comment by whit537** [comment]
I've upgraded Papertrail to the $7/mo plan.

**Comment by rohitpaulk** [comment]
> Did you receive the notifications? Did you take any action?

Yes, I've accepted it - and I'm not sure what to do now...

**Comment by whit537** [comment]
> Do I overengineer it? =)

Maybe a bit. :)

> notify when Gratipay is down

We've got notifications, now to two of us. !m @rohitpaulk :)

> deploy status/monitoring server on independent server

Done. We use Uptime Robot for monitoring, and it emails PagerDuty, which fans out via SMS.

> make sure monitor is monitored

Meh. That's Uptime Robot's problem for now. ;)

> notification list with free subscribe

http://rss.uptimerobot.com/u128001-24a87b86a29b9037c031a7e6691db9fc 💃

> provide manual instructions for troubleshooting downtime

The catch is that this requires access to our Heroku account, which right now resides with @rohitpaulk @clone1018 and myself. Furthermore, debugging downtime is a complex task, not a rote one. I don't see value in maintaining complex documentation for just the three of us.

**Comment by whit537** [comment]
> Yes, I've accepted it - and I'm not sure what to do now...

I've reconfigured our PagerDuty escalation policy to simply notify you and I immediately after an incident is triggered. I've manually created an incident in order to test. Didja get a notification? :-)

**Comment by whit537** [comment]
I've added Papertrail to the [budget](https://docs.google.com/spreadsheets/d/1p3DpF9ZLEsViBx0685FwJaYN1vVScKVUgXHb2zyqXZg/pub?output=html&widget=true).

**Comment by rohitpaulk** [comment]
Didn't get the notification the first time around as a call (coz I had entered my phone number wrong) - fixed now.

So. Good to close? :)

**Comment by whit537** [comment]
Yeah, I think so! 💃

**Comment by whit537** [comment]
> Didn't get the notification the first time around as a call

Does that mean someone is wondering what the heck the message they got is about? 😁

**Comment by rohitpaulk** [comment]
Probably :D
