### ISSUE TITLE
Teams should be able to give a percentage to other teams

### ISSUE THREAD

**Issue by tswast** [gratipay/gratipay.com#4126]
I've been giving on Gratipay for years, but it wasn't until recently that I made a team for Who Goes First and am now receiving my first payments.

I love that Gratipay is pay-what-you-want, but I think this process could be improved. I as an individual can pay Gratipay (and have been for a while) because I think you are doing great work, but there is no way for a team itself to give to Gratipay what the team thinks the value it is receiving from Gratipay. I'd love to have Who Goes First be able to give 5% of what it receives to Gratipay.

It's not just Gratipay that teams could feel gratitude towards. ReadTheDocs is funded on Gratipay, I believe, and I am certain that other open source projects feel that they are providing value to them.

The reason I think it should be a percentage is that the value I receive from having Gratipay as a platform is relative to the amount I am given. Likewise, ReadTheDocs provides value relative to the community size that is using an open source package. The amount I receive is approximately proportional to the community size.

**Comment by mattbk** [comment]
I see two separate ideas here (both good):
- Teams giving to other teams
- Giving as a percentage of income

**Comment by whit537** [comment]
Thanks for the feedback, @tswast ... and thanks for giving on Gratipay for years ... and for giving _to_ Gratipay ❤️ ... and now for signing up for Gratipay with Who Goes First!💃 🙇  :-)

Seems like there's something to your idea. Certainly for Gratipay the value you receive from us is directly proportional to your income you receive through us, so it makes a lot of sense to express your payment to Gratipay as a percentage of your income (certainly this is the pricing model other payments and crowdfunding companies use ;). For something like Read the Docs (which hasn't made the jump to Gratipay 2.0 yet, I'm afraid), the connection is somewhat weaker, but I suppose it could make sense to let each team and/or user decide.

Do you think it'd be tenable to implement percentages to Gratipay as a one-off? Or do you see enough value in the model to generalize it?

**Comment by mattbk** [comment]
> Do you think it'd be tenable to implement percentages to Gratipay as a one-off? Or do you see enough value in the model to generalize it?

I'd love to see teams-giving-to-teams generalized in order to encourage "trickle-down." Percentages would be even better...

If Team A uses Team B's product as part of Team A's OSS, then regardless of how much Team B receives directly, it's also now receiving more as Team A grows...encouraging further development. Gratipay-->Aspen would be an example.

**Comment by whit537** [comment]
We'd want to think about how this interacts with team takes, where we opted for absolute instead of percentages ([e.g.](https://github.com/gratipay/gratipay.com/issues/3994#issuecomment-222995512)).

**Comment by tswast** [comment]
Who Goes First -> Weblate is another one that might make sense for giving a percentage, since I'm considering hosting a weblate server for translation and want to encourage development on that project.

That said, I think starting with a one-off for giving to Gratipay makes a lot of sense, since all teams on Gratipay benefit from that, whereas general team-team may only make sense for a few teams.

**Comment by whit537** [comment]
It's important to me for Gratipay to be "just like any other ~~team~~ [*project*](https://github.com/gratipay/gratipay.com/pull/4117)." I'd like to find a way to implement this by, e.g., exposing an API that *any* project could use, and have Gratipay use that API on gratipay.com itsel.f

**Comment by mattbk** [comment]
Until take-what-you-want returns for projects in general, there may not be a need for projects-giving-to-projects because all funds flow through the project owner, who can then give to the other project in question. I see the return of TWYW and PGTP as going hand in hand. Keeping the books straight if you ran multiple projects would be a reason to separate out PGTP before then.

https://gratipay.slack.com/archives/gratipay/p1482441691001211

**Comment by mattbk** [comment]
+1 from Slack: https://gratipay.slack.com/archives/gratipay/p1482449884001217

**Comment by whit537** [comment]
@mattbk Can we use http://gratipay.slackarchive.io/gratipay/ for Slack permalinks instead of slack.com? I'm given to understand that the former are more permanent.

**Comment by mattbk** [comment]
+1 from https://twitter.com/wSokra/status/831828196681216000
> @opencollect I want to donate to the mocha collective from the webpack collective. Is there a way to move funds without paying fees twice?
