### ISSUE TITLE
Add a note at https://gratipay.com/Gratipay/receiving/ about arrears

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#4132]
https://github.com/gratipay/inside.gratipay.com/issues/382#issuecomment-150372263

https://github.com/gratipay/inside.gratipay.com/issues/382#issuecomment-150500368

**Comment by nobodxbodon** [comment]
May be part of https://github.com/gratipay/inside.gratipay.com/issues/993?

**Comment by whit537** [comment]
We already have this [in the FAQ](https://gratipay.com/about/features/#receiving-less), fwiw.

**Comment by whit537** [comment]
Removing `TeamX` because the audience for this note is users, no?
