### ISSUE TITLE
Send email when PayPal masspay is denied

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#4137]
https://github.com/gratipay/inside.gratipay.com/issues/736#issuecomment-241554073

> > Hmm, do we send out emails to users when this happens?
> 
> I'm not sure that we do. We should if we don't ... new ticket?

Here is a ticket to notify ~users when they were supposed to receive payouts via PayPal but PayPal denied it.

**Comment by whit537** [comment]
+1 in https://gratipay.freshdesk.com/helpdesk/tickets/6190
