### ISSUE TITLE
show amount receiving instead of giving on button

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#416]
@dianaclarke [points out](https://twitter.com/diana_clarke/status/277201580212776960) that showing the amount you give violates the anonymity principle. Instead of [showing](https://twitter.com/diana_clarke/status/277202314073341952) just the text "Gittip," how about if we show the amount the person is receiving? That'd be more like GitHub's "Star" widget and Twitter's "Follow" widget. We should show a depressed button if we wanted to indicate tippage without giving away the amount.

One problem is that we have limited width due to the hard-coded iframe embed.
##

**Comment by nobodxbodon** [comment]
AFAIK it's done.

**Comment by mattbk** [comment]
@nobodxbodon, you should check the grtp.co repo amd reticket widget stuff there if it needs to be.

**Comment by nobodxbodon** [comment]
@mattbk actually I checked the one served on shields.io, and seemed it's showing amount receiving. Thus I closed this one. Sorry I should have made it clear.
