### ISSUE TITLE
Make agreement to TOS implicit in clicking "Apply"

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#4166]
Looking at our current signup process, I see two things that look like they can be stripped off. 
- The `todo_url` field. The self-onboarding documentation URL would contain that info anyway, why ask for a separate link? I think that we added this field because we wanted to make open work mandatory, and pasting a specific link would make the user consciously aware that they satisfy that requirement. Is this really worth it?
- The three separate checkboxes. Why not implicitly tick them (with the wording "When you click on 'Apply', you agree to x, y and z" when the user clicks on 'Apply'? Reference: http://ux.stackexchange.com/questions/55571/auto-agreement-to-the-tos-by-clicking-sign-up-button-in-sign-up-form

**Comment by whit537** [comment]
I'm adding this to the Decouple milestone, because it's related to https://github.com/gratipay/gratipay.com/issues/4123.

**Comment by mattbk** [comment]
Part of https://github.com/gratipay/gratipay.com/pull/4130.

**Comment by whit537** [comment]
Moving to PR in #4124 for point 1. Point 2 moved to #4130.

**Comment by whit537** [comment]
Point 2 moved back here. :-)

**Comment by whit537** [comment]
Removing from milestone and project. Nice to have if we can get to it.
