### ISSUE TITLE
Disconnect PayPal gives "Looks like you've found a bug! Sorry for the inconvenience, we'll get it fixed ASAP!"

### ISSUE THREAD

**Issue by toy** [gratipay/gratipay.com#4168]
Account toy, I have only one verified email, when clicking Disconnect button on PayPal page, I get the error.

**Comment by whit537** [comment]
Sorry, @toy. :-/

Don't have time now, but I will look into this when I get a chance if someone else doesn't get to it first ...

**Comment by toy** [comment]
It is not really urgent. I already saw this bug, but assumed that you are getting notifications, but as the bug was not fixed, I've created an issue.

**Comment by rohitpaulk** [comment]
Copying the error from Sentry: 

```
IntegrityError: update or delete on table "exchange_routes" violates foreign key constraint "exchanges_route_fkey" on table "exchanges"
DETAIL:  Key (id)=(10189) is still referenced from table "exchanges".
```

Looks like we're trying to delete the exchange route, but the foreign key constraint between `exchanges` -> `exchange_routes` prevents us from doing so. 

Hmm, maybe we should be soft deleting exchange routes?

**Comment by whit537** [comment]
> assumed that you are getting notifications

We are getting notifications, but we're not staying on top of them. Sorry. 😞

**Comment by rohitpaulk** [comment]
Aha! 

<img width="572" alt="screen shot 2016-10-31 at 6 37 24 pm" src="https://cloud.githubusercontent.com/assets/3893573/19855171/190b5f56-9f99-11e6-9696-671ad4db3ec1.png">

**Comment by rohitpaulk** [comment]
Added by me in https://github.com/gratipay/gratipay.com/commit/0500105b9dc148855b7957963b3949d89a7cc3b4, and @whit537 added the comment in https://github.com/gratipay/gratipay.com/commit/e27a2283211bf9ade2121dec222714110e37b93b. 

I think the best way out here is to update the error to 'invalidated' irrespective of the `network` - and when user tries to add the route again for paypal, we revive the previous `exchange_route`.

**Comment by rohitpaulk** [comment]
Moving implementation details to a PR so that we don't pollute this issue

**Comment by toy** [comment]
Still not possible to disconnect

**Comment by whit537** [comment]
Mind giving this another shot, @toy? We just deployed #4170 in an attempt to fix this.

**Comment by toy** [comment]
@whit537 Thanks! It seems to work, as I was able to disconnect the paypal account.

**Comment by whit537** [comment]
Woo-hoo! Thanks for your patience. :-)
