### ISSUE TITLE
pay out via Trans-pay

### ISSUE THREAD

**Issue by nraoTF** [gratipay/gratipay.com#417]
_Original:_ **Direct bank Payout into 100 countries**

I was invited by Jareau Wade to join this forum. We currently provide our payout facility to a large marketplace company out of silicon valley and I can confidently say that we are the only company in the world who can resolve this forums issue on payouts.

You can have you company connect into us through an API and we provide payout capability into any bank account into over 100 countries within 24 hours. You don't have to look at rudimentary firms like Payoneer or Bitpay our platform is single plugin and robust.

Please let me know if you want to discuss this further on 2125183876. Thanks 
##

**Comment by whit537** [comment]
Heard from @nraoTF and just got off the phone. Their new site:

https://www.transpay.global/

I'm expecting an application in email.

**Comment by whit537** [comment]
I've received the application and am scheduling a time for a demo in the next week or so.

**Comment by whit537** [comment]
Demo is 2:30pm US/Eastern on Thursday, Feb 19.

**Comment by whit537** [comment]
I've manually keyed the country for the 122 participants we've paid out via PayPal since Nov 1. With that in hand, I'll proceed to generate the spreadsheet.

**Comment by whit537** [comment]
https://docs.google.com/spreadsheets/d/105lkO5mDQpPYShNmaojk7mP07K8EWml2bn18M4IELfA/edit?usp=sharing

**Comment by whit537** [comment]
Here's a spreadsheet showing [Gratipay's PayPal Usage](https://docs.google.com/spreadsheets/d/105lkO5mDQpPYShNmaojk7mP07K8EWml2bn18M4IELfA/edit?usp=sharing).

**Comment by whit537** [comment]
https://twitter.com/whit537/status/568636749154529281

**Comment by whit537** [comment]
Here's the script I used: https://gist.github.com/whit537/2ba365bb0a833c9b9450 to generate the CSV to import into Google Docs. You'll see that the script takes country data from a flat file, which I generated by hand after dumping distinct usernames for the relevant exchanges.

**Comment by whit537** [comment]
First round of docs sent (application, organization docs, photo id, spreadsheet).

**Comment by whit537** [comment]
I've updated the spreadsheet with payout figures for Balanced and Coinbase, for comparison.

**Comment by whit537** [comment]
#### Payouts

| Method | Transactions (%) | Volume (%) |
|------------|------------------------|-----------------|
| Balanced | 57.2 | 73.8 |
| PayPal | 42.4 | 23.6 |
| Coinbase | 0.4 | 2.5 |

**Comment by whit537** [comment]
Sent:

> Any update on this? How can I help move this along?

**Comment by whit537** [comment]
> I checked in with my Compliance Dept. and they would not approve your application due to multiple companies located at same home address and overall AML/KYC compliance wariness with your business. My boss and myself talked with them to see if we could reconsider, but as you know, compliance is extremely strict in the MSB area and they explained that your company does not meet the minimum criteria for Compliance for transpay.
I’m very sorry and wish you luck.

**Comment by whit537** [comment]
Replied:

> Thanks. I appreciate your feedback and I would like to move my business in the direction of greater compliance, as of course that will be best for us regardless of whether we are able to partner with Transpay. It sounds like setting up a proper business office is the next step. Are you able to provide further concrete action items for us to achieve minimum compliance?

Setting up an office reticketed as #155.

Re: "overall AML/KYC compliance wariness" I'm assuming that's https://github.com/gratipay/gratipay.com/issues/417#issuecomment-54667221.

**Comment by techtonik** [comment]
Yes. The "overall AML/KYC compliance wariness" is a very vague refusal. In my practice compliance == checklist. And here it is doesn't sound like a checklist, more like "we don't want to deal with your shady business". =)

**Comment by whit537** [comment]
Blocked on AML (https://github.com/gratipay/inside.gratipay.com/issues/119).

**Comment by whit537** [comment]
Heard from a new sales rep, setting up a call.

**Comment by whit537** [comment]
Private call scheduled for Wednesday at 10 am UTC-5.

**Comment by whit537** [comment]
Sounds like Transpay is doing well, they landed deals with Upwork and Google. They're streamlining their onboarding process, here's their new [Client Application (US).pdf](https://github.com/gratipay/gratipay.com/files/99632/Client.Application.US.pdf). We're still too small for this to make sense yet, but maybe next year? The product looks great.

**Comment by whit537** [comment]
> Thanks, []. I think it's going to take us at least a year to get our KYC/AML and our growth where we want it to be before reapproaching Transpay, but I'd be fine with a touchpoint in six months or so if you like ...

**Comment by whit537** [comment]
> United States: Transfast is registered as a Money Transfer Business with the Financial Crimes Enforcement Network (FinCEN) and licensed as a money transmitter in 37 U.S. states. 

https://www.transpay.global/Home/FAQ (click "Licences")

It occurred to me that we would need this to be the case in order to use Transpay.

**Comment by justinxreese** [comment]
@whit537 Do you have a 10,000 foot view on Gratipay's stance with Transpay? Considering it in a project, but there is a lot of information in this thread to parse.

**Comment by whit537** [comment]
@justinxreese Latest comments (since https://github.com/gratipay/gratipay.com/issues/417#issuecomment-172587142) give a good overview. We'd like to use their service but we want to tighten up our KYC first. Your best bet is probably to get into a sales call with them. I can introduce you in email if you want ... let me know! :-)

**Comment by nobodxbodon** [comment]
Re-ticketed to https://github.com/gratipay/inside.gratipay.com/issues/974 for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.
