### ISSUE TITLE
Upgrade Sentry Client

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#4191]
<img width="512" alt="screen shot 2016-11-14 at 8 55 57 am" src="https://cloud.githubusercontent.com/assets/3893573/20252444/417b339e-aa48-11e6-9038-d78b99990d43.png">

**Comment by rohitpaulk** [comment]
Again...

![screen shot 2017-05-05 at 4 58 00 pm](https://cloud.githubusercontent.com/assets/3893573/25750655/f9e12286-31cf-11e7-875b-7a74a3d60c2e.png)

**Comment by whit537** [comment]
@EdOverflow has looked into tooling to help us stay up to date with (Python) deps. Have those tickets handy, @EdOverflow?

**Comment by EdOverflow** [comment]
@whit537 I do not believe there are any open tickets. This may have simply been a discussion on the Slack channel.

**Comment by whit537** [comment]
I was thinking of the pyup integration, e.g., https://github.com/gratipay/gratipay.com/pull/4376.
