### ISSUE TITLE
Bring back pledging

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4195]
Once we have ~~#4148~~ &rarr; #4305, let's bring back pledging (killed in #3403). Reticketed from https://github.com/gratipay/inside.gratipay.com/issues/893.

In this context, "pledging" means being able to set up a weekly payment to a potential project that we won't start collecting on until the potential project opts in to become an actual project and receive funds.

**Comment by kaguillera** [comment]
Didn't we discuss this before you left for SF @whit537? Let people pledge to projects that they would like to see on Gratipay and use that as incentive to woo those projects to register on Gratipay. Is this illegal @mattbk even if it is just pledges and not actual money?

**Comment by whit537** [comment]
What _haven't_ we talked about, @kaguillera? ;-)

I don't see a legal issue with pledging.

**Comment by whit537** [comment]
Closing this issue since the idea is captured on https://github.com/gratipay/inside.gratipay.com/issues/987. We'll make a PR when we get to it.

**Comment by mattbk** [comment]
> Is this illegal @mattbk even if it is just pledges and not actual money?

Oh gosh, please don't ask me for legal advice. :fearful:

**Comment by whit537** [comment]
Reopening because we're getting ready to get to it, but I'm not ready to make a PR yet. ☺️

**Comment by whit537** [comment]
Did some noodling on this today with @kaguillera. Write-up forthcoming.

**Comment by mattbk** [comment]
Is GratipayAlerts on Twitter coming back?

**Comment by whit537** [comment]
Well, we have an email address for package maintainers, which seems a better contact method than Twitter, ya?

**Comment by mattbk** [comment]
> Well, we have an email address for package maintainers, which seems a better contact method than Twitter, ya?

Agree, unless you want Twitter to be used for advertising.

**Comment by whit537** [comment]
Hopefuly we'll have better things to advertise once companies start paying for their `package.json`. "Thanks to Acme Corp for paying $1,000 for their package.json!"

**Comment by JessaWitzel** [comment]
I would like writeup of said noodling if it can be remembered :)

**Comment by whit537** [comment]
I'm actually gonna go ahead and close this out. The new strategy is to [crowdfund for all of open source at once](https://github.com/gratipay/inside.gratipay.com#1160) vs. individually picking and choosing projects to give to.
