### ISSUE TITLE
Use 401 instead of 403 where appropriate

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#4196]
https://github.com/gratipay/gratipay.com/issues/4040#issuecomment-261589195
> 401 = not logged in
403 = already logged in but still not allowed

Then why do I get 403 when not logged in, for pages like this?
![image](https://cloud.githubusercontent.com/assets/3729038/20439498/52f767aa-ad81-11e6-98fa-c87b47157870.png)

https://github.com/gratipay/gratipay.com/issues/4040#issuecomment-261589885
> Because we're doing it wrong? :)
> Unless we're not, but I think we are ...
> https://httpstatuses.com/401
https://httpstatuses.com/403

Relates to #4189, which is due to #4040.

**Comment by mattbk** [comment]
Based on some discussion at http://stackoverflow.com/questions/3297048/403-forbidden-vs-401-unauthorized-http-responses, it looks like 401 should be returned if you are not logged in and are trying to access a page you need to be logged in to see, regardless of whether you have privileges to see it or not as an authenticated user. This is what @whit537 notes at the beginning of this issue.

**Comment by nobodxbodon** [comment]
Please reopen if there's new finding which is not covered by https://github.com/gratipay/gratipay.com/pull/4197
