### ISSUE TITLE
19th November Downtime

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#4198]
Gratipay was down for about an hour (1800 - 1900 19th November) - the request throughput shot up just before this happened. 

Screenshots from Heroku: 

<img width="1231" alt="screen shot 2016-11-20 at 10 06 22 am" src="https://cloud.githubusercontent.com/assets/3893573/20460459/113097c2-af09-11e6-8f7f-3ac0b274f97a.png">

**Comment by whit537** [comment]
Did you do something to bring it back up? I noticed the notifications soon after but when I checked it was back up.

**Comment by rohitpaulk** [comment]
Nope, I didn't do anything - I only saw the notifications around 6 hours later

**Comment by whit537** [comment]
Likely another security researcher. Can we check that in the logs? Is our logging fixed enough to have that available?
