### ISSUE TITLE
Retire librato

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4203]
Do we need Librato now that we have charts from Heroku? E.g.: https://github.com/gratipay/gratipay.com/issues/4198.

The Heroku logs aren't public-able, are they?

To: metrics-feedback@heroku.com
Subject: public metrics?

> Greetings! Our current metrics solution is [public](http://inside.gratipay.com/appendices/health). It'd be swell if we could use Heroku metrics publicly as well!

**Comment by JessaWitzel** [comment]
@whit537 I am willing to give an opinion if you want to take the time to tell me the pros and cons. If they are both logging the same information and Heroku logs can be made public then my answer is no! Let's ax it.

**Comment by whit537** [comment]
I heard back from Heroku. They were very receptive to the +1, but logs/stats can't be made public right now. :-/

**Comment by nobodxbodon** [comment]
Close as there's no action item in short term.
