### ISSUE TITLE
"open work" and ngo's

### ISSUE THREAD

**Issue by paskalito** [gratipay/gratipay.com#4207]
> “Open work” means that your company or organization makes it easy for any individual to do your work for you without asking you first, and as a result to share in any revenue you generate. Basically you need to have a public issue tracker with documentation for self-onboarding, and be willing to use our payroll feature once we bring it back.

according to that would u accept common ngo's like greenpeace wwf and amnesty international? // - can i tell them if they like to have money from me they should make a team here?

**Comment by mattbk** [comment]
They would probably fit better once we finish the [new TOS](https://github.com/gratipay/gratipay.com/pull/4117), which doesn't require revenue sharing.

**Comment by whit537** [comment]
> can i tell them if they like to have money from me they should make a team here?

[You can now](https://gratipay.news/from-teams-to-projects-45c46718507b)! 💃
