### ISSUE TITLE
Add "percentage to charity" like Humble Bundle has

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4209]
I thought @mattbk or someone talked about this before, but I'm not finding it by searching for "charity" in this repo. Gittipay 1.0 really took off when we combined charitable giving to diversity activists with more pragmatic giving to open source projects. Can we do the same under Gratipay 2.0, adapted to our new project focus?

One implementation possibility is the Humble Bundle [model](https://www.humblebundle.com/store/select-charity), where charitable giving is tacked on as a percentage of the total bill. Diversity-focused charities are still probably a good place to start, since that is a pressing concern in the tech industry.

![screen shot 2016-11-28 at 6 37 24 pm](https://cloud.githubusercontent.com/assets/134455/20690624/bf93ef44-b599-11e6-829e-8d27eca80b9f.png)

**Comment by whit537** [comment]
http://www.blackgirlscode.com/
https://www.girldevelopit.com/
https://watsi.org/

**Comment by mattbk** [comment]
It wasn't me. The closest I can think of is when I suggested something like a giving pool, where you could give to a general pool that could be opted into by a team/project. Somewhat different than a curated bundle, this would essentially be TWYW but at the project level.

**Comment by whit537** [comment]
This is now potentially evolving into a tax(!): https://github.com/gratipay/inside.gratipay.com/issues/637#issuecomment-263590417.

**Comment by nobodxbodon** [comment]
> TWYW but at the project level

@mattbk I should have commented in your original issue, and maybe the following has been mentioned already. IMO TWYW is based on mutual respect and understanding. It might be feasible in a small circle like our own team, but I imagine it would cause more conflicts than harmony among different and maybe sometimes completing projects.

> This is now potentially evolving into a tax

Are we considering switching our model? If there's a explict tax, will it decrease the direct giving to Gratipay?

**Comment by mattbk** [comment]
I'm against a tax that isn't opt-in.

Could we reward people for opting in with something? Social capital?

**Comment by whit537** [comment]
Yeah, I'm not sure a "tax" makes sense since this is optional giving in the first place, and that's kind the whole point. :-)

**Comment by JessaWitzel** [comment]
So how do you give to charity on here? In fact, isn't there a support ticket like this? Is there a way for charitable organizations to create teams? Or for teams to partner with charitable organizations?

**Comment by techtonik** [comment]
This organizations need official status, so we need to import list from somewhere. https://www.charitynavigator.org/ looks like a good start.

**Comment by whit537** [comment]
> If your nonprofit makes an arrangement with a business to receive a percentage of sales – or if a business offers that deal to your nonprofit – beware. In at least 22 states that’s a regulated activity that may require a special registration filing. - See more at: https://www.councilofnonprofits.org/tools-resources/commercial-co-ventures-and-cause-related-marketing#sthash.6xXMhpEf.dpuf

https://www.councilofnonprofits.org/tools-resources/commercial-co-ventures-and-cause-related-marketing

**Comment by whit537** [comment]
Also https://www.quora.com/How-do-for-profit-companies-that-raise-funds-for-non-profits-and-causes-make-money
