### ISSUE TITLE
Refresh Team Banner

### ISSUE THREAD

**Issue by clone1018** [gratipay/gratipay.com#4213]
This is going to be my focus for awhile, I want to mess around with the design a bit in an issue before I move it to a pull request.

My first draft is: 
![image](https://cloud.githubusercontent.com/assets/226638/20740541/80e3a5aa-b689-11e6-9906-114f68b7b9a2.png)

My goals were: 

- Supporting teams on Gratipay is AMAZING! Let's show that off
- Highlight you (the user) setting up an easy gift to the team

I'd love some initial thoughts! Please be aware my "Gratipay Terminology" is way old :)

To Do:

- [ ] Ugly black border!
- [ ] What are tip amounts? Buttons? Anchors?
- [ ] I added a semi-black transparency to the banner for the white text, good solution?
- [ ] Update terminology

**Comment by clone1018** [comment]
Side note, in order to build this out, I had to tear up the rest of the site haha

**Comment by nobodxbodon** [comment]
My $0.02:

- Is the amount for the latest week or average?
- are the numbers ($5.00, $10.00..) clickable? If so it's not quite obvious. And maybe $1 (without .00) is more concise
- is "setup gift" to setup weekly giving? If it's just to give different number, maybe relabel to something like "other"?

**Comment by clone1018** [comment]
I'm thinking when you click on any of the numbers OR the button, it slides to this menu:

![image](https://cloud.githubusercontent.com/assets/226638/20752781/b8d24cf2-b6c8-11e6-8977-d8498804dbff.png)

**Comment by whit537** [comment]
@clone1018 Maybe keep that up all the time, no slide?

**Comment by whit537** [comment]
@clone1018 Can we close this in favor of #4215?

**Comment by clone1018** [comment]
Yeah I meant to! Thanks
