### ISSUE TITLE
Testing Problems

### ISSUE THREAD

**Issue by JessaWitzel** [gratipay/gratipay.com#4216]
I was making changes trying to fix #4214 and deleted todo_url from 6 places. It was finally working and the tests all passed (except the three that never pass) but then all of a sudden everything failed. I make cleaned et al and now I am having big testing issues.

I stashed my code changes and got my local env is up to date with master and I have rebooted, and make clean/schema/fake a half dozen times. I can make run and the local page works.

When I make pytest it collects 751 items and then hangs on the first test (test_api_key_json.py) if that's relevant. 

If I try to make test instead I get: 
env/bin/honcho run -e defaults.env,tests/test.env,tests/local.env ./recreate-schema.sh
Recreating public schema ... 
and it hangs. @whit537  or anyone... can you help?

**Comment by clone1018** [comment]
What's the current result of `git status` ?

**Comment by JessaWitzel** [comment]
On branch master
Your branch is up-to-date with 'upstream/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	www/assets/gratipay.css
	www/assets/gratipay.js

nothing added to commit but untracked files present (use "git add" to track)

**Comment by clone1018** [comment]
Do you get a postgresql console when you do:

`psql gratipay`

**Comment by JessaWitzel** [comment]
yes. it says gratipay=#

**Comment by clone1018** [comment]
Hrm, weird! The only thing I can think of:

Switch back to your branch, commit your changes and push them to origin (so you don't lose them) and then blow it up and do a fresh git clone

**Comment by JessaWitzel** [comment]
Just did that. :/ same problem.

**Comment by JessaWitzel** [comment]
Husband just dropped gratipay and gratipay-test databases and reran make schema and it is working now! I have a million errors but this is progress!
