### ISSUE TITLE
Fix ridiculous "13 failed" Travis failure

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4226]
Reticketed from https://github.com/gratipay/gratipay.com/pull/4221#issuecomment-265580315. We may have a ticket already but I'm not finding it.

**Comment by mattbk** [comment]
Also in #4222 now.

**Comment by whit537** [comment]
I don't even have a log right now. :(

**Comment by whit537** [comment]
Here we go: https://gist.github.com/whit537/bac6d2be5a7d5f2aa9b60fb1df73218b.

Snagged from #4222.

**Comment by whit537** [comment]
Actually, this could be a case of https://github.com/gratipay/gratipay.com/pull/4225 [after all](https://gist.github.com/whit537/bac6d2be5a7d5f2aa9b60fb1df73218b#file-13-failed-log-L69).

**Comment by whit537** [comment]
Closing wtih #4225. Let's see if that does it ...
