### ISSUE TITLE
Use Card for nicer credit card UI

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4233]
[h/t](https://twitter.com/changelog/status/809051832869879808)

https://jessepollak.github.io/card/
https://github.com/jessepollak/card

![687474703a2f2f692e696d6775722e636f6d2f71473354656e4f2e676966](https://cloud.githubusercontent.com/assets/134455/21188880/c95c4f96-c1ea-11e6-9991-d629dd6fedd8.gif)

**Comment by Changaco** [comment]
I considered doing this in Liberapay but I decided to go with something simpler instead. The result is https://github.com/liberapay/liberapay.com/pull/679 and the creation of https://github.com/liberapay/payment-cards.js
