### ISSUE TITLE
Smarten up rendered descriptions in search

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4235]
When displaying search results, we include a participant's profile statement, which we render as markdown and then excerpt (theoretically we'll do the same for project's some day). Applying styles to the rendered markdown can have unintended side effects. For example, [searching for webpack](https://gratipay.com/search?q=webpack) matches the usernames `webchick` and `Weblate`, and the half-open HTML from the first's description clobbers the markup for the second.

------------------------------

![screen shot 2016-12-16 at 6 09 19 am](https://cloud.githubusercontent.com/assets/134455/21260902/35b6303c-c356-11e6-9519-e870fd931244.png)

---------------------------------
![screen shot 2016-12-16 at 6 16 42 am](https://cloud.githubusercontent.com/assets/134455/21261069/402aafe2-c357-11e6-9ca6-146e9026d7d3.png)

**Comment by mattbk** [comment]
Helpful? https://coderwall.com/p/dnnlea/how-to-truncate-a-string-that-s-markdown-format

**Comment by whit537** [comment]
Hmm ... maybe. a) I think that's Ruby? and b) Why would it work to truncate before escaping instead of after? We don't even want to escape, do we?

Probably the real way to do this is to store an html-stripped version of the text, and search over and display that.

**Comment by mattbk** [comment]
I think your first point is the most valid.

**Comment by whit537** [comment]
I think we should try using http://stackoverflow.com/a/925630 to compute and store a flattened plain-text version of the content, and search/display against that instead of the marked-up version.

**Comment by whit537** [comment]
Or possibly https://github.com/aaronsw/html2text but that seems like overkill.

**Comment by whit537** [comment]
Moving to a PR in #4266.

**Comment by whit537** [comment]
[Fixed](https://gratipay.com/search?q=webpack)! 💃

![screen shot 2017-01-09 at 4 30 14 pm](https://cloud.githubusercontent.com/assets/134455/21784299/ec43e692-d688-11e6-8cad-22ceec67a0fe.png)
