### ISSUE TITLE
Integrate CRAN

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#4237]
The repository for R packages. 

Like #4148.

**Comment by whit537** [comment]
Looks like CRAN is on https://libraries.io/. My thinking is that after #4148, we will have a much better idea of what we need from Libraries.io in terms of API. Ideally they would be able to build out whatever API we might need, and then we can go from 1 to 30+ other package managers in one fell swoop. Does that sound right to you?

**Comment by mattbk** [comment]
Sounds good. Wanted to get it on the list.

**Comment by mattbk** [comment]
Working with http://www.crantastic.org/ would be great as well. It's a search/review site for CRAN packages. They're on GitHub: https://github.com/hadley/crantastic/tree/master

**Comment by mattbk** [comment]
I mentioned this [here](https://github.com/gratipay/inside.gratipay.com/issues/412#issuecomment-159634566), too, apparently.

**Comment by daroczig** [comment]
Crantastic (as far as I know) is not under active development anymore, unfortunately :(
I'd rather suggest checking METACRAN at https://www.r-pkg.org

**Comment by gaborcsardi** [comment]
:+1:

I am not sure what kind of API you need from the packages manager, but I'll be happy to improve the CRAN API at METACRAN.

**Comment by nobodxbodon** [comment]
Re-ticketed to [integrate with software repositories / package manager](https://github.com/gratipay/inside.gratipay.com/issues/982) for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.

**Comment by mattbk** [comment]
I know you're trying to get things organized, but why can't we have issues in both places? I assume the IG issue is going to be about prioritizing which to implement first?

**Comment by nobodxbodon** [comment]
@mattbk IMO, as there are other similar issues it's better to be planned together. In case contributor from external platform wants to make a push on this, or someone wants to just discuss about it, that assembly issue is still a good place to start with, as we'll still need to decide relative priority among those similar issues, and (if decide to start working) who from our side to work with them, while keeping in mind our short-term focus.

In case an arbitrary contributor wants to pick some open issue to work on, there are still plenty other more actionable issues with higher severities (bugs, usabilities, UI, etc), and closing issues that are not immediately actionable will make the other issues more likely to be solved, as those contributors will be more focused.
