### ISSUE TITLE
Deploy SRI for remote resources

### ISSUE THREAD

**Issue by EdOverflow** [gratipay/gratipay.com#4240]
With SRI deployed, remote resources can be used safely, without fear of them being modified by malicious parties.

The following remote resources do not use SRI:

**5 scripts:**
https://assets.gratipay.com/jquery.min.js
https://assets.gratipay.com/chosen.jquery.min.js
https://assets.gratipay.com/tipr.min.js
https://assets.gratipay.com/bootstrap-dropdown.js
https://assets.gratipay.com/gratipay.js

**1 CSS file:**
https://assets.gratipay.com/gratipay.css

This is how it can be implemented:

~~~
<script src="https://assets.gratipay.com/jquery.min.js" integrity="sha384-hK8q2gkBjirpIGHAH+sgqYMv6i6mfx2JVZWJ50jyYhkuEHASU6AS1UTWSo32wuGL" crossorigin="anonymous"></script>
~~~

Here are two ways you can generate SRI hashes manually:

1) Using https://www.srihash.org/.
2) Using OpenSSL: `openssl dgst -sha384 -binary FILENAME | openssl base64 -A`

In Python this can be done as follows (Edited version of: https://tenzer.dk/generating-subresource-integrity-checksums/):

~~~
import base64
import hashlib

def checksum(input):
    if isinstance(input, str):
        input = input.encode()

    hash = hashlib.sha384(input).digest()
    hash_base64 = base64.b64encode(hash).decode()
    return 'sha384-{}'.format(hash_base64)
~~~

**Comment by EdOverflow** [comment]
It would also be a nice feature to supply the SRI hash of the `GIVING & TAKING WIDGETS`:

~~~
<script data-gratipay-username="EdOverflow" src="//grtp.co/v1.js"></script>
~~~

**Comment by whit537** [comment]
Sounds good to me, though I suppose we'll need a way to automate this, ya?

**Comment by EdOverflow** [comment]
Yep, exactly. You will need to hash the file, base64 encode the message digest and then finally insert it into the `integrity` attribute.

**Comment by whit537** [comment]
Okay, up for a PR on this one? :-)

**Comment by EdOverflow** [comment]
I'll submit a pull request for this one as soon as I find time. :)
