### ISSUE TITLE
Add "hidden" option for rejected projects that are spam or security testing

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#4241]
So they don't show up under the "rejected" tab.

**Comment by whit537** [comment]
Or we could just delete them.

**Comment by mattbk** [comment]
Yeah, but I need someone with database access to do that.

**Comment by whit537** [comment]
I was thinking we could add an admin knob so you could do it through the website.

**Comment by whit537** [comment]
Though "archived" or "hidden" is probably safer.

**Comment by mattbk** [comment]
The "closed" status clears this up.
