### ISSUE TITLE
Move projects under participants in URL structure

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4246]
In the spirit of differentiating participants and projects (#3852), I think it could make sense to move projects underneath participants in our URL structure. So instead of:

`https://gratipay.com/~kennethreitz/`
`https://gratipay.com/requests/`

We would have:

`https://gratipay.com/kennethreitz/`
`https://gratipay.com/kennethreitz/requests/`

Projects have exactly one owner: the legal entity behind them. This URL structure makes the ownership clear, and could help differentiate the two.

Fiscal sponsorship could throw a wrench in this—if hypothetically PSF were the sponsor of Requests, which would we have,

`https://gratipay.com/kennethreitz/requests/`

or

`https://gratipay.com/python/requests/`?

**Comment by mattbk** [comment]
I think this 

1. Increases the likelihood of links breaking 
1. Reduces projects from primary to secondary importance 

That being said, it's what GitHub does.

**Comment by whit537** [comment]
> Increases the likelihood of links breaking

Yeah, we'd want to be careful about maintaining redirects. Perhaps we would need to snapshot project names at the time of the cutover in order to be able to redirect them in perpetuity?

> Reduces projects from primary to secondary importance

I think your GitHub example counters this somewhat.

**Comment by mattbk** [comment]
From #4338:
> I think @mattbk and I talked about this but I don't recall reticketing (dupe alert!).
> I propose that we move projects under owners in the URL structure, like GitHub does:
> https://gratipay.com/Gratipay/
https://gratipay.com/~gratipay/Gratipay/
> Contributes to disambiguation of ~participants and projects (#3852).

**Comment by whit537** [comment]
+1 from @andrew in Libraries.io slack.

**Comment by whit537** [comment]
The npm integration puts pressure on this, because (e.g.) https://gratipay.com/mysql/ isn't actually MySQL. 😳

**Comment by whit537** [comment]
Closing the loop: https://github.com/gratipay/project-review/issues/424. ☺️

**Comment by whit537** [comment]
+1 from @balupton in https://github.com/gratipay/project-review/issues/465.
