### ISSUE TITLE
about/me/history does not match other pages that require login to view

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#4258]
`about/me/history` (not logged in):
![image](https://cloud.githubusercontent.com/assets/3729038/21457009/add265ea-c8f1-11e6-9635-b42bcee036a9.png)

`~whit537/history` (not logged in)
![image](https://cloud.githubusercontent.com/assets/3729038/21457017/c4751856-c8f1-11e6-8f84-142beb955910.png)

The latter is a 401 code, the former is not.

**Comment by whit537** [comment]
Thanks for ticketing, I noticed this the other day, too.
