### ISSUE TITLE
Join the IoO Project Council?

### ISSUE THREAD

**Issue by ntnsndr** [gratipay/gratipay.com#4260]
For some months, @devinbalkind and I have been developing a Project Council as an institutional frame for The Internet of Ownership, a federated resource network for the platform co-op ecosystem. We already use Gratipay for our fundraising, and we'd love to work more closely with you. Would Gratipay be interested in joining our Project Council? Right now, the meaning of this is still being worked out, but the goal is to work together to develop a democratic, shared resource pool for platform co-op efforts. Right now we're quite small, but we're about to add a third project, and we'd love if you might be interested in co-creating this effort with us. The expectations are quite modest. We have a Loomio group for decisions. And [here's some information about it, such as there is](http://internetofownership.net/project-council/).

Would this be of interest?

**Comment by whit537** [comment]
Thanks for the invitation, @ntnsndr! Moving to https://github.com/gratipay/inside.gratipay.com/issues/954 since we use that repo for organizational issues such as this one, while issues in the gratipay.com repo are more for product issues with the website itself.
