### ISSUE TITLE
Display warning when clicking on external link.

### ISSUE THREAD

**Issue by EdOverflow** [gratipay/gratipay.com#4261]
In order to reduce the impact of open redirects, I would recommend adding a warning page. The warning should display where the user is being redirected to.

The following is HackerOne's implementation:

![c](https://cloud.githubusercontent.com/assets/18099289/21466712/1e2381c0-c9d4-11e6-92cc-2a1d6a47a5f2.PNG)

**Comment by whit537** [comment]
This would be just for user-generated content, correct?

**Comment by EdOverflow** [comment]
Yep, that's right.
