### ISSUE TITLE
History page balances are messed up

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4274]
Is it because we're so close to the new year?

https://gratipay.com/~whit537/history/?year=2016

![screen shot 2017-01-05 at 1 50 55 pm](https://cloud.githubusercontent.com/assets/134455/21693208/0e5404c6-d34e-11e6-8913-a5522662321b.png)

**Comment by kaguillera** [comment]
Not sure but will check into it.

**Comment by mattbk** [comment]
This is still being weird, so it doesn't look like a year thing?

E.g., 
![image](https://cloud.githubusercontent.com/assets/3729038/22483019/18bd96de-e7c1-11e6-8009-52688f04d962.png) is the first week of one account. So it starts at $192.

**Comment by rohitpaulk** [comment]
Fixing in #4439

**Comment by mattbk** [comment]
#4439 is merged, close?

**Comment by rohitpaulk** [comment]
Yep
