### ISSUE TITLE
What sequence of steps do I need to perform to eradicate my account?

### ISSUE THREAD

**Issue by kytrinyx** [gratipay/gratipay.com#4286]
I've been waiting for the ability to close my account since May 2015.

There was a support thread, but I don't know the link to this.

See also:

- https://github.com/gratipay/gratipay.com/issues/3481
- https://github.com/gratipay/gratipay.com/issues/3453

I just got the email about the revised terms of service. The email says I can now close my account, however when I log in it says that I can't, because I'm a team owner.

I became a team owner in 2015 because I was instructed that this was the only way I could close my account without losing the accumulated donations, however after having jumped through those hoops, it then turned out that there was no way to close the account.

I've been quite patient, but I really would rather not have to read through a new terms of service. I just want this to be over with.

What sequence of steps do I need to take in order to completely close my account?

**Comment by mattbk** [comment]
(Note to self, Freshdesk ticket is https://gratipay.freshdesk.com/helpdesk/tickets/2161.)

I'm sorry for the confusion. We don't have an automated way to [close projects](https://github.com/gratipay/gratipay.com/issues/3602) yet, but we should be able to clear things out manually. Please stand by while I see what's possible.

**Comment by whit537** [comment]
Mea maxima culpa. 😞

Working on this ...

**Comment by whit537** [comment]
I find two relevant accounts:

- https://gratipay.com/~exercism_io/
- https://gratipay.com/~kytrinyx/

I've gone ahead and closed the former. The latter had a 15¢ balance, which I've paid out via PayPal, and is also the owner of the project/team in question:

- https://gratipay.com/exercism/

I've manually marked the project as closed in the database. It will still show up on the homepage and will also prevent us from closing the ~kytrinyx account until we deploy #4287. Once we deploy that PR I will close the ~kytrinyx account, and I think you should be all set at that point.

Are we on the right track, @kytrinyx?[](url)

**Comment by kytrinyx** [comment]
I appreciate it, @mattbk, thanks for the quick response.

@whit537 Yes, those are the two user accounts, and that is the correct team. If you close the ~kytrinyx account as soon as that is possible, that would be great. Thank you.

**Comment by whit537** [comment]
@kytrinyx The https://gratipay.com/~kytrinyx/ account is now closed. I believe that finally takes care of this, I hope? Thanks for your patience, and sorry this took so long. :-(

Best wishes! :-)

**Comment by kytrinyx** [comment]
Thank you @whit537! Indeed, I think that's it.

**Comment by whit537** [comment]
Thanks again for being so patient with me/us. ☺️
