### ISSUE TITLE
Disallow slashes and other naughty strings in project names

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#4295]
Per some security researchers, we get project names like this:
- https://github.com/gratipay/project-review/issues/313 /www.evil.com/user_ip.php?gratipay
- https://github.com/gratipay/project-review/issues/312 //www.google.com/?><x>
- https://github.com/gratipay/project-review/issues/311 //www.google.com/?

All of these break the URL, so the project page can't be reached and needs to be manually removed from the database.

Not a security issue, but is an annoyance and could be used for spam.

**Comment by whit537** [comment]
@dmk246 @EdOverflow Would one of you be able to cross-link this to the relevant HackerOne ticket?

**Comment by EdOverflow** [comment]
@whit537 Done. https://hackerone.com/reports/176396

**Comment by mattbk** [comment]
Potentially useful? https://github.com/minimaxir/big-list-of-naughty-strings

**Comment by mattbk** [comment]
These types of names also produce errors on the front page ([FD](https://gratipay.freshdesk.com/helpdesk/tickets/6688)):

> Also I am wondering why there are some requests to Google (https://www.google.de/?gws_rd=cr&ei=fSCKWLGaIoGjsgGhuYPoAg), whcih return 0 byte answers and there is one failing request to 
https://gratipay.com/x.x/?>/image?size=small, which returns a 404 error.

**Comment by mattbk** [comment]
NB, to delete existing bad projects, use `branch.sql`.
http://gratipay.slackarchive.io/gratipay/-/1488556344.00768/1488986867.00782/1488986782007817/

**Comment by mattbk** [comment]
[Interesting](https://github.com/gratipay/gratipay.com/blob/b3426f059305a6432e747f16b37a5aafcf2a022e/gratipay/models/team/__init__.py#L23).
> TEAM_NAME_PATTERN = re.compile(r'^(?=.*[A-Za-z])([A-Za-z0-9.,-_ ]+)$')

**Comment by mattbk** [comment]
Those are the required characters. At least one letter and then you can have some other stuff that isn't required.

_/me wanders off to learn how to regex out / and ? at the same time..._

**Comment by whit537** [comment]
@mattbk I'm pretty sure there's a bug in the regex because `-` indicates a range encompassing all of the ASCII characters between `,` and `_`. If my hypothesis is correct than the way to fix is probably for the `-` to be the last character in the set.

**Comment by whit537** [comment]
Note that there's another similar regex for usernames which may have the same bug.

**Comment by mattbk** [comment]
I will try that.
