### ISSUE TITLE
Separate project membership from takes

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4299]
Reticketing from https://github.com/gratipay/gratipay.com/issues/3144#issuecomment-71684060:

> Maybe we should separate memberships from takes. When people become inactive we drop their takes to zero, but that wouldn't drop them from the team anymore, and they could start taking again if they come back. If they don't come back for some time then we drop them from the team entirely.

**Comment by whit537** [comment]
+1 from @kaguillera at https://github.com/gratipay/gratipay.com/issues/3144#issuecomment-71705641 and @nobodxbodon at https://github.com/gratipay/inside.gratipay.com/issues/986#issuecomment-272980954. @dmk246 is the third one right now who is doing significant work but for her own reasons is not taking money. These folks are important members of our team even if they're not taking money right now.

**Comment by mattbk** [comment]
Would this include adding members who aren't legally eligible for takes (e.g., who haven't completed verification or who can't accept American money)? I would see this working as being on the team but having inability to set takes at all.

**Comment by whit537** [comment]
> Would this include adding members who aren't legally eligible for takes (e.g., who haven't completed verification or who can't accept American money)? I would see this working as being on the team but having inability to set takes at all.

I had thought that this would be up to the user—they can take or not take as they choose. But I guess since taking depends on filing national identity, then yes, someone could be a member of the project but not capable of taking.

**Comment by mattbk** [comment]
> national identity

I was thinking specifically of @kaguillera, yes.
