### ISSUE TITLE
Permissions, required for Bitbucket integration

### ISSUE THREAD

**Issue by maxkoryukov** [gratipay/gratipay.com#4300]
Hello! Thank you for the service!

I've tried to connect my bitbucket acc to the gratipay profile, and stopped on the list of required permissions: why so much???

> Gratipay is requesting access to the following:
> * Read and modify your account information
> * Read and modify your repositories' issues
> * Access your repositories' build pipelines and configure their variables
> * Read and modify your team's project settings, and read and transfer repositories within your team's projects
> * Read and modify your repositories and their pull requests
> * Administer your repositories
> * Delete your repositories
> * Read and modify your snippets
> * Read and modify your team membership information
> * Read and modify your repositories' webhooks
> * Read and modify your repositories' wikis

### Screenshot:

![selection_017](https://cloud.githubusercontent.com/assets/8887971/22095057/a8e347e6-de33-11e6-9f5d-a330e6444916.jpg)

**Comment by maxkoryukov** [comment]
hmm, seems, like this is just a duplicate. @nobodxbodon, Should I close this?

**Comment by nobodxbodon** [comment]
Thanks a lot for the feedback. No worries to keep it open for now. After we fix the issue, we'll close them all together. Seems to me the fix should be a quick config change, but @whit537 and others would know better.

**Comment by whit537** [comment]
Let's go ahead and use https://github.com/gratipay/gratipay.com/issues/822, yes.

**Comment by maxkoryukov** [comment]
@whit537 @nobodxbodon fast and precise interaction;) thank you!

**Comment by maxkoryukov** [comment]
Great;)

![selection_018](https://cloud.githubusercontent.com/assets/8887971/22185337/82f6529c-e105-11e6-9d9b-c7eae978670a.jpg)
