### ISSUE TITLE
Feautre Request: send and receive bitcoin

### ISSUE THREAD

**Issue by andrasfuchs** [gratipay/gratipay.com#4310]
Please add support to bitcoin payments. 

[Braintree also supports it now](https://www.braintreepayments.com/payment-methods/accept-bitcoin), but I guess they would have a cut.

**Comment by whit537** [comment]
Thanks, @andrasfuchs. I've noted this on https://github.com/gratipay/inside.gratipay.com/issues/974, which is where we've recently started collecting requests such as this.

**Comment by jhabdas** [comment]
@andrasfuchs I'm working towards having a license approved by SPDX for Bitcoin wallet addresses directly in licenses and have requested GitHub add support for the [BIP-0021 URI scheme](https://github.com/bitcoin/bips/blob/master/bip-0021.mediawiki) to markdown files. Longer-term my hope is crypto licenses will open the door to additional crypto licenses and enable FOSS to receive payments simply for having their works out in the wild.

If this seems interesting to you I've written the following article on Medium:
https://medium.com/@jhabdas/introducing-the-btc-license-28650887eb11
