### ISSUE TITLE
Allow SVG images for product/service image

### ISSUE THREAD

**Issue by rugk** [gratipay/gratipay.com#4311]
Currently we can only use JPG or PNG. It would however be nice to use vector-images (which are usually far superior to these pixel images) - in particular SVG.

**Comment by EdOverflow** [comment]
Gratipay team, please keep in mind that SVG files can contain code and therefore we should be very careful if we decide to incorporate this feature.

**Comment by whit537** [comment]
Security is the reason we don't support SVG already. What's the state of the art on securely handling SVGs from users? Does [Camo](https://github.com/atmos/camo) help?

**Comment by rugk** [comment]
From what I read Camo is a (TLS) proxy. Why should it help?

**Comment by EdOverflow** [comment]
I would rather we do not allow SVG files. The amount of CVEs I have seen related to SVG files bothers me.

In answer to your question @whit537, I believe most websites blacklist possibly malicious code in SVGs. Unfortunately, this is a very complicated and error prone procedure.

**Comment by Changaco** [comment]
I suggest running the SVG through an optimizer like [svgcleaner](https://launchpad.net/svg-cleaner). That process should remove any malicious code, although I can't guarantee that (someone would need to take a deeper look if it hasn't been done yet).

**Comment by rugk** [comment]
FYI here is a good presentation about [security issues with SVG files](https://www.owasp.org/images/0/03/Mario_Heiderich_OWASP_Sweden_The_image_that_called_me.pdf).
