### ISSUE TITLE
Trivia: remove "n=" from tab headers on homepage

### ISSUE THREAD

**Issue by nobodxbodon** [gratipay/gratipay.com#4315]
IMO 'n=' doesn't make it easier to understand what the number means
![screen shot 2017-02-01 at 9 19 22 pm](https://cloud.githubusercontent.com/assets/392497/22538031/5b9f6ac8-e8c4-11e6-94e8-5ed9dbe15bb7.png)

**Comment by whit537** [comment]
Fwiw, the `n=` are derived from the Chicago Manual of Style [on tables](http://www.chicagomanualofstyle.org/16/ch03/ch03_toc.html) (paywall).

**Comment by nobodxbodon** [comment]
Seems that link requires subscription, which I don't have. So it recommends using 'n='? IMO a similar case is the mozilla reviewer tool:
![screen shot 2017-02-02 at 12 42 48 pm](https://cloud.githubusercontent.com/assets/392497/22567581/55dc1e2a-e945-11e6-880e-5c3512bb1920.png)

**Comment by whit537** [comment]
> Seems that link requires subscription, which I don't have.

Right, that's what I meant by "(paywall)." Not sure what to do about that. I actually don't have a subscription anymore either, if I ever did. I'm inclined to think that anyone working on design should have the CMoS to work with, but I'm not sure how best to accomplish that (each pay? Gratipay pays?).

**Comment by mattbk** [comment]
That would help the wrap I'm seeing now:
![image](https://cloud.githubusercontent.com/assets/3729038/22791513/3997e518-eeaf-11e6-8c0b-d641167e6bb5.png)

**Comment by clone1018** [comment]
I'm for removing them, not sure the value of the numbers. https://github.com/gratipay/gratipay.com/pull/4392

**Comment by whit537** [comment]
Done in #4392!
