### ISSUE TITLE
Rename "Teams" to "projects" under the hood

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4318]
We [renamed Teams to projects](https://gratipay.news/from-teams-to-projects-45c46718507b) in the UI, but not under the hood. We should rename under the hood as well to avoid confusion, especially for new developers. Let's try this in layers:

- HTML/JavaScript
- Python
- Postgres

I think we should make multiple small PRs for each layer, one bite at a time. 🐘

**Comment by whit537** [comment]
> The task is basically to grep for ‘team’ under `js/`, pick a file, and make a PR changing just that file.

http://gratipay.slackarchive.io/gratipay/-/1486054441.004742/1486056248.004937/1486056248004937/

**Comment by whit537** [comment]
@jacquieline-homan Renaming files is just the beginning, we also want to change variables names in source as well.

**Comment by whit537** [comment]
@jacqueline-homan Note that renaming files is just the beginning, we also want to change variables names in source as well.

**Comment by jacqueline-homan** [comment]
@whit537 Which is why CTRL + F and "Replace All" are the most best features of a text editor :) Just let me know which variables in the source code need to be changed.

**Comment by whit537** [comment]
`team` &rarr; `project`

**Comment by jacqueline-homan** [comment]
Got it :)

**Comment by whit537** [comment]
[slack](http://gratipay.slackarchive.io/gratipay/-/1486644886.005667/1486666682.005823/1486666437005774/)
