### ISSUE TITLE
Localhost not loading in Firefox

### ISSUE THREAD

**Issue by kaguillera** [gratipay/gratipay.com#4322]
Just found this problem in Firefox while setting up Gratipay locally on @dmk246 laptop. For some reason the page never loads when you `make run` and try to open localhost:8537 in Firefox it hangs. We believe it is because `gratipay.report_uri.io`

**Comment by whit537** [comment]
Indeed.

![screen shot 2017-02-16 at 1 34 35 pm](https://cloud.githubusercontent.com/assets/134455/23035321/ab821156-f44c-11e6-995b-49716ed4ec74.png)

**Comment by whit537** [comment]
Why do we have a CSP violation in stock Gratipay?

![screen shot 2017-03-24 at 11 06 05 am](https://cloud.githubusercontent.com/assets/134455/24300167/edae5a34-1081-11e7-99b2-d4faea310637.png)

**Comment by whit537** [comment]
Chrome also recognizes violations. Presumably their implementation precludes blocking on same.

![screen shot 2017-03-24 at 11 12 34 am](https://cloud.githubusercontent.com/assets/134455/24300428/cd8c3522-1082-11e7-8c38-ad8de8dc780d.png)

**Comment by EdOverflow** [comment]
> The Content Security Policy directive 'upgrade-insecure-requests' is ignored when delivered in a report-only policy.

The `upgrade-insecure-requests` directive is ignored when sent via a `Content-Security-Policy-Report-Only` header: https://www.w3.org/TR/upgrade-insecure-requests/#delivery

> Unrecognized Content-Security-Policy directive 'reflected-xss'.

The `reflected-xss` directive has been deprecated in Chrome 56+: https://www.chromestatus.com/feature/5769374145183744

> Refused to apply inline style because it violates the following Content Security Policy directive: [...]

```html
<a class="github-ribbon" href="https://github.com/gratipay/gratipay.com">
   <img style="position: absolute; top: 0; right: 0; border: 0;"
      src="https://s3.amazonaws.com/github/ribbons/forkme_right_darkblue_121621.png"
      alt="Fork me on GitHub"> <!-- This line is the issue! -->
</a>
```

**Comment by whit537** [comment]
Ah! So *that's* what @nobodxbodon was [on about](https://github.com/gratipay/gratipay.com/issues/4359#issuecomment-287519144). :D

**Comment by EdOverflow** [comment]
Yep. We must remove the inline style attribute from the GitHub banner.

**Comment by whit537** [comment]
Okay, I did that and the CSP error is gone, but FF is still spinning, and any other request even from another browser also blocks until I cancel the FF request. :thinking:

![screen shot 2017-03-24 at 11 32 33 am](https://cloud.githubusercontent.com/assets/134455/24301309/aed769a0-1085-11e7-8e3c-b736ca0bff4d.png)

**Comment by EdOverflow** [comment]
> The upgrade-insecure-requests directive is evaluated before block-all-mixed-content and if it is set, the latter is effectively a no-op. **It is recommended to set one directive or the other, but not both.** [[Source]]

Whoops!

```
"upgrade-insecure-requests;"
"block-all-mixed-content;"
```
Link to source code: https://github.com/gratipay/gratipay.com/blob/master/gratipay/security/__init__.py#L56-L57

[Source]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/upgrade-insecure-requests

**Comment by whit537** [comment]
Yeah, okay. I was just dialing in on `upgrade-insecure-requests` as the culprit.

**Comment by whit537** [comment]
Whittled down to the base page + one asset which should've been 404 but was still triggering tailspin.

![screen shot 2017-03-24 at 11 41 16 am](https://cloud.githubusercontent.com/assets/134455/24301781/dd5e8636-1086-11e7-87f7-1a415d9c71f5.png)

**Comment by whit537** [comment]
Okay! Root cause! Fix?

**Comment by EdOverflow** [comment]
PR on the way!

**Comment by whit537** [comment]
@EdOverflow Beat ya to it? https://github.com/gratipay/gratipay.com/pull/4390 😁

**Comment by EdOverflow** [comment]
I have changed my opinion on this and would prefer we stick to `upgrade-insecure-requests` and not `block-all-mixed-content`. `block-all-mixed-content` is purely experimental and `upgrade-insecure-requests` would solve [h1:118023](https://hackerone.com/reports/118023).

**Comment by kaguillera** [comment]
This is fixed...well the original issue of not loading localhost in firefox. I am closing this an opening the security issue on another ticket see https://github.com/gratipay/gratipay.com/issues/4591
