### ISSUE TITLE
Retire welcome message

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4325]
@hmig suggests [on Twitter](https://twitter.com/_hmig/status/829467538471997441) that the welcome popup constitutes an [intrusive interstitial](https://webmasters.googleblog.com/2016/08/helping-users-easily-access-content-on.html) and should be removed.

![c4lcu0mwcaaimlj](https://cloud.githubusercontent.com/assets/134455/22785815/d9b12c1e-eea3-11e6-8e23-839eb37e87b6.jpg)

**Comment by finkiki** [comment]
I agree.

**Comment by whit537** [comment]
> just to clarify, the text is fine...The issue is just having a pop up. I'd suggest putting the content in the page. ;)
> e.g. Maybe putting it in a bar above the header that can be closed.

**Comment by whit537** [comment]
There are three bits of info in the popup:

1. number of projects
1. total weekly dollar volume
1. link to "About"

(1) and (3) are already on the main page (I'm not sure they were when we added the popup). Is there an easy way to work the dollar volume into the main page?

**Comment by mattbk** [comment]
![image](https://cloud.githubusercontent.com/assets/3729038/22888293/c570af5c-f1ca-11e6-89fb-dc9716004b4b.png)

**Comment by whit537** [comment]
It could be confusing there: is it scoped to the current tab?

**Comment by whit537** [comment]
The dollar volume _is_ available under About > Stats. How about we just go with #4334?

**Comment by mattbk** [comment]
Sounds good.
