### ISSUE TITLE
How to use the shields button?

### ISSUE THREAD

**Issue by rugk** [gratipay/gratipay.com#4328]
I don't get how to properly use the shields button. I can use [this one](https://img.shields.io/gratipay/user/rugk.svg) for users, but how to do it for projects?

**Comment by whit537** [comment]
Projects were called "teams" until recently. Is Shields still perhaps using the old nomenclature?

https://img.shields.io/gratipay/team/XenForo-Threema-Gateway.svg

**Comment by whit537** [comment]
> Projects were called "teams" until recently.

https://gratipay.news/from-teams-to-projects-45c46718507b, btw

**Comment by rugk** [comment]
Mhh, so is it intended that `anonymous` is shown for projects which have not received any money yet. Or why are they "anonymous"?

**Comment by whit537** [comment]
Dunno, I just checked the Shields [homepage](http://shields.io/) and `teams` is what they advertise.

**Comment by whit537** [comment]
We'll have to dig deeper into the API calls that Shields is making to Gratipay, and what those calls are returning. You motivated to do that, @rugk? :-)

**Comment by rugk** [comment]
Uh, not really, no. If it does not work I use a text link for now… 😉

**Comment by mattbk** [comment]
If you're receiving $0.00, the shield defaults to "anonymous"

https://img.shields.io/gratipay/team/XenForo-Threema-Gateway.svg works is the right url.

I tipped you a penny, it shows up correctly (markdown below, not a static image):
[![Gratipay User](https://img.shields.io/gratipay/team/XenForo-Threema-Gateway.svg)]()

**Comment by whit537** [comment]
We good here, @rugk?

**Comment by rugk** [comment]
@mattbk Nice!
And thanks for the penny. 😃

**Comment by rugk** [comment]
> This seems like a bug with how public.json is being read by Shields.

I think it would be good if this can be fixed in Shields.io. Then this issue can be closed IMHO…

**Comment by mattbk** [comment]
Looks like this has been fixed.
