### ISSUE TITLE
Suggested donation banner populates incorrect amount in some other languages

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#4332]
From [FD](https://gratipay.freshdesk.com/helpdesk/tickets/6792):

> I've donated to a project and then when your portal offered my to donate 0,40 to Gratipay I've clicked the button, but then my account shows u$s 4 dollar donation to Gratipay
May be it's a bug or I didn't undestand it. The BUTTON clearly displayed the number 0,40. Then I clicked it.

This works correctly for me. I think this may be a language issue around `,` vs `.` for currency? Screenshot submitted by FD user shows `,` is used.

English:
![image](https://cloud.githubusercontent.com/assets/3729038/22831759/25b27280-ef71-11e6-91e2-5228a928148f.png)

I am not sure how to change my language so I can test this myself.

## notify
- [ ] https://gratipay.freshdesk.com/helpdesk/tickets/6792

**Comment by whit537** [comment]
@mattbk Changing language is in browser settings under "Content" for Chrome/FF, not sure about others.

**Comment by whit537** [comment]
Well, "Advanced settings" > "Languages" in Chrome:

![screen shot 2017-02-10 at 11 38 28 am](https://cloud.githubusercontent.com/assets/134455/22835073/80cba3e4-ef85-11e6-8997-e036fb89a9ba.png)

**Comment by mattbk** [comment]
That works for you? Gratipay still shows up in English for me if I change to Italian or French in Chrome. I get the option to translate the page, but I know that's Google translating it, not the Transifex translations.

**Comment by mattbk** [comment]
Stand by...

**Comment by mattbk** [comment]
Aha! https://chrome.google.com/webstore/detail/quick-language-switcher/pmjbhfmaphnpbehdanbjphdcniaelfie?hl=en

**Comment by mattbk** [comment]
Problem confirmed, with Italian:

![image](https://cloud.githubusercontent.com/assets/3729038/22836835/9b5a0b62-ef83-11e6-992c-f6dcd36df02f.png)

click `US$ 0,30`

![image](https://cloud.githubusercontent.com/assets/3729038/22836845/a5f61160-ef83-11e6-9555-285243e3c458.png)

and on /about/me/giving:

![image](https://cloud.githubusercontent.com/assets/3729038/22836857/b38ef940-ef83-11e6-93a0-b9c0f11552ab.png)

**Comment by whit537** [comment]
Maybe [something to do](https://github.com/gratipay/gratipay.com/blob/2049/gratipay/utils/i18n.py#L200-L201) with [`trailing_zeroes=False`](https://github.com/gratipay/gratipay.com/blob/2049/templates/support-gratipay.html#L20-L21)?

**Comment by whit537** [comment]
PR ready to go in #4337.

**Comment by mattbk** [comment]
Notified in Freshdesk.
