### ISSUE TITLE
Update Medium icon in footer

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4336]
We're [way behind](https://blog.medium.com/the-story-behind-medium-s-new-logo-4cd3e143dfcf).

![screen shot 2017-02-16 at 8 35 41 am](https://cloud.githubusercontent.com/assets/134455/23023316/ee8cece8-f422-11e6-916a-da0c9cfdc22c.png)

**Comment by whit537** [comment]
https://medium.design/logos-and-brand-guidelines-f1a01a733592?gi=4d2cf265adb2

**Comment by whit537** [comment]
lol, didn't keep up. Seems they've moved again!

![screen shot 2017-08-22 at 11 33 25 am](https://user-images.githubusercontent.com/134455/29573727-ba2e52b8-872d-11e7-9c82-caf7c9f78183.png)

![screen shot 2017-08-22 at 11 33 40 am](https://user-images.githubusercontent.com/134455/29573763-cbde4bf8-872d-11e7-98c4-391f0ff6c80d.png)

**Comment by whit537** [comment]
Previous:

![screen shot 2017-08-22 at 11 36 58 am](https://user-images.githubusercontent.com/134455/29573984-48db240a-872e-11e7-9c6d-48e892cb73f7.png)
![screen shot 2017-08-22 at 11 37 21 am](https://user-images.githubusercontent.com/134455/29573983-48d87322-872e-11e7-8762-95ea9b755df2.png)
![screen shot 2017-08-22 at 11 37 15 am](https://user-images.githubusercontent.com/134455/29573982-48d84258-872e-11e7-8b4b-4bab4c64e716.png)
![screen shot 2017-08-22 at 11 37 08 am](https://user-images.githubusercontent.com/134455/29573985-48ee9abc-872e-11e7-8aef-f1be96871dff.png)

**Comment by whit537** [comment]
@kaguillera @dmk246 Here is what I know about updating the logo in our icon font: https://github.com/gratipay/gratipay.com/pull/4234#issuecomment-273451537

**Comment by kaguillera** [comment]
Thank you we will continue to look at this next week @dmk246 had to leave.
