### ISSUE TITLE
Move projects under users

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4338]
I think @mattbk and I talked about this but I don't recall reticketing (dupe alert!).

I propose that we move projects under owners in the URL structure, like GitHub does:

https://gratipay.com/Gratipay/
https://gratipay.com/~gratipay/Gratipay/

Contributes to disambiguation of ~participants and projects (#3852).

**Comment by mattbk** [comment]
I think it was on Slack but I haven't found it yet.

**Comment by mattbk** [comment]
Duplicate of https://github.com/gratipay/gratipay.com/issues/4246.

Wasn't Slack. :cry:
