### ISSUE TITLE
Implement expensing

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4339]
Open Collective has a great alternative for take-what-you-want distributions: expensing. Each project has a cash balance, and anyone on the internet can submit an expense report against that balance at any time. This is much more flexible than our weekly twyw that we have now for Team Gratipay. It's a general case that could be used as we're using weekly twyw, but could also account for other models (one-time contractors or special expenses).

![screen shot 2017-02-16 at 4 10 27 pm](https://cloud.githubusercontent.com/assets/134455/23041301/766670fa-f462-11e6-951b-8e086360d515.png)

**Comment by whit537** [comment]
With this we don't even need the concept of "members" per se. Anyone can submit an expense report. The definition of "members" emerges as those-who-submit-expenses.

**Comment by whit537** [comment]
I sortta feel like we _have_ to do this to stay competitive with OC. True or false?

**Comment by whit537** [comment]
+1 from @ntnsndr at https://social.coop/@ntnsndr/17510.

(I don't know how to respond [remotely?] via Mastodon or I would.)

**Comment by mattbk** [comment]
The "Open in web" link at the bottom takes you to the Mastodon interface if you're logged in, then you can reply.

**Comment by ntnsndr** [comment]
I would be very glad to see this. Since OC seems to be hitting that membership/expense niche well, in certain ways, it'd be great to think of ways that Gratipay can do even more. Some ideas:

- More sophisticated membership management
- Other legal support structure options
- Decision-making tools or integration with other ones
- GitHub/Lab integration

For the social.coop project, I'm not sure how things are playing out, but I've recommended a structure wherein members are users and contributors (who can receive payouts for labor or services) may or may not be members, strictly.

**Comment by whit537** [comment]
Our current focus is on tapping into corporate wealth for open source projects via aggregation (deep dive on https://github.com/gratipay/inside.gratipay.com/issues/987; hopefully a first announcement will hit the [blog](https://gratipay.news/) in a few weeks). We think there's room for innovation there, and that this also gets at a deeper issue: no matter how good an expensing implementation might be, it doesn't matter if there's no money to share! I don't know exactly what the sequence will be, but at some point we'll need to revisit the areas where we overlap more with OC (etc.) and clean up those parts of the product. As you suggest, we don't see a ton of strategic value in trying to incrementally improve on what others are already doing if we're not also offering a unique value.

As to serving co-ops, I think that deserves its own thread: https://github.com/gratipay/inside.gratipay.com/issues/1052.

**Comment by whit537** [comment]
+1 from @kennethreitz by phone.
