### ISSUE TITLE
Remove payout route requirement

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4340]
Right now we require a working payout route in order to move money (ostensibly; in practice we still move money if a participant has a failing payout route). We did this because we wanted to reduce or even eliminate our escrow (#1383), but it's now clear that that is both unnecessary and undesirable. We should allow projects to pool funds in Gratipay, to give us more flexibility to grow our escrow in step with volume (which we need to do in order to be able to keep funds transfer snappy), and also to give projects more flexibility (e.g., https://github.com/gratipay/gratipay.com/issues/4339).

**Comment by mattbk** [comment]
Along with this should be some rejiggering of the payday process so cards aren't charged if there is money to use.
