### ISSUE TITLE
React to SHA-1 collision (SHAttered).

### ISSUE THREAD

**Issue by EdOverflow** [gratipay/gratipay.com#4354]
On February 23, 2017, CWI Amsterdam and Google, demonstrated a first real SHA-1 collision. (https://shattered.io/) Although many of us were aware that this would happen any time soon, we must ensure that the security of Gratipay's users is not affected in any way.

# Summary

![](https://pbs.twimg.com/media/C5XLJ2rWQAAjv07.jpg)

Original: http://www.poorlydrawnlines.com/
Edited by: https://twitter.com/nathonsecurity

# Investigation

Gratipay will take the necessary precautions to remediate any issue related to SHA-1.

Gratipay took the following steps during the investigation:

1) Ensure none of our services use SHA-1 (HMAC-SHA-1 is not really a problem).
2) Ensure that no services used by Gratipay use SHA-1.

We checked whether:

- Certificate chains are signed with SHA-1. (Certificate)
- SHA-1 was used somewhere in the source code. (Source code)
- SHA-1 was present somewhere anywhere else. (Other)

# Does Gratipay use SHA-1?

| Service                | Certificate | Source code | Other |
|------------------------|-------------|-----------------------|-------|
| gratipay.com           | NO          | NO                    | NO    |
| assets.gratipay.com    | NO          | NO                    | NO    |
| downloads.gratipay.com | NO          | NO                    | NO    |
| grtp.co                | NO          | NO                    | NO    |

# Are any services used by Gratipay affected?

Gratipay uses 6 OAuth providers, which we believe are not affected by this incident.

| Service       | Certificate | 
|---------------|------------|
| Twitter       | NO         |
| GitHub        | NO         |
| Facebook      | NO         |
| Google        | NO         |
| Bitbucket     | NO         |
| OpenStreetMap | NO         |

These are other services Gratipay uses:

| Service             | Certificate       |
|---------------------|-------------------|
| report-uri.io       | NO                |
| Paramount           | -                 |
| Heroku              | NO                |
| Freshdesk           | NO                |
| iWantMyName         | NO                |
| Transifex           | NO                |
| MaxCDN              | NO                |
| DigitalOcean        | NO |
| StartSSL            | NO                |
| Typography.com      | NO                |
| Papertrail          | NO                |
| Librato             | NO                |
| LastPass            | NO                |
| DNSimple            | NO                |
| GSuite              | NO                |
| PagerDuty           | NO    |
| Sentry              | NO                |
| Travis CI           | NO                |
| Balsamiq            | NO                |
| Uptime Robot        | NO                |
| SlackArchive.io     | NO                |
| Slack               | NO                |
| Amazon Web Services | NO                |
| Read the Docs       | NO                |
| Icomoon             | NO                |

# Conclusion

This investigation reveals that **Gratipay's users are not directly affected by this incident.**

We would like to thank CWI Amsterdam & Google for their fantastic work.

---

<details>
  <summary>Psst...</summary>
	If you are interested in learning about SHA-1 and cryptography in general, I would highly recommend you have a look at https://www.crypto101.io/.
</details>

**Comment by whit537** [comment]
😳

```
<details>
  <summary>Psst...</summary>
	If you are interested in learning about SHA-1 and cryptography in general, I would highly recommend you have a look at https://www.crypto101.io/.
</details>
```

**Comment by EdOverflow** [comment]
¯\_(ツ)_/¯

**Comment by whit537** [comment]
Any implications for our Git usage?

https://plus.google.com/+LinusTorvalds/posts/7tp2gYWQugL

I suppose this is something GitHub would start addressing?

**Comment by EdOverflow** [comment]
> Any implications for our Git usage?

This is not something we should really worry about as of right now. I will let you know if there are any updates in the future.

In case someone is interested, here is a StackOverflow discussion demonstrating how Git would handle a SHA-1 collision on a blob: https://stackoverflow.com/a/34599081

> I suppose this is something GitHub would start addressing?

I hope so.

**Comment by whit537** [comment]
!m @EdOverflow

**Comment by EdOverflow** [comment]
https://github.com/git/git/commit/e1fae930193b3e8ff02cee936605625f63e1d1e4

**Comment by EdOverflow** [comment]
https://github.com/blog/2338-sha-1-collision-detection-on-github-com
