### ISSUE TITLE
Travis often hangs on ttw tests

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4359]
Not infrequently, a build will fail at Travis due to the 10 minute timeout. Restarting the build generally fixes it. From what I've observed, the tests hang on the ttw tests. I think I've been able to observe this behavior locally as well, so perhaps this is debuggable. In the mean time ... restart build!

**Comment by whit537** [comment]
Ah! We *do* have an AWS S3 dependency: the GitHub ribbon.

AWS is [having an issue](https://status.aws.amazon.com/) with S3 right now:

> Update at 10:33 AM PST: We're continuing to work to remediate the availability issues for Amazon S3 in US-EAST-1. AWS services and customer applications depending on S3 will continue to experience high error rates as we are actively working to remediate the errors in Amazon S3.

(Their status reporting is terrible, so I can't link to a specific incident report.)

**Comment by whit537** [comment]
GitHub failed to post my screenshot of our S3 dependency, leading me to wonder whether they have an S3 dependency as well. ;-)

**Comment by whit537** [comment]
Yeah, ttw tests proceed with normal slowness when I remove the ribbon.

**Comment by whit537** [comment]
Sounds to me like another reason to have a knob to turn off report-uri.io in development/CI.

**Comment by whit537** [comment]
This is really slowing me down.

**Comment by nobodxbodon** [comment]
Would [host github ribbon on our own](https://github.com/lukaszx0/queues.io/commit/4a8756494888442e8ab10f96b052ab537d806b02) help?

**Comment by whit537** [comment]
I don't think it's the ribbon that is slowing us up, I think it's report-uri.io. Need to confirm though ...

**Comment by whit537** [comment]
The thing is that we *want* to test report uri, but maybe not all the time.

**Comment by whit537** [comment]
But really it's not like we ever want to block page loading on report-uri.com. Is there something wrong with our implementation?

**Comment by whit537** [comment]
Perhaps related to #4322?

**Comment by whit537** [comment]
Looks like in #4390 this is not due to the CSP violation from the GitHub ribbon. That actually makes sense, since that was affecting Firefox only, and we use PhantomJS (WebKit ~= Chrome) at Travis.

**Comment by whit537** [comment]
I usually run the ttw tests locally using Chrome. Can I repro w/ PhantomJS?

**Comment by whit537** [comment]
Hmm ... different than hang. :thinking: 

```
Traceback (most recent call last):
  File "/Users/whit537/personal/gratipay/gratipay.com/tests/ttw/test_trim.py", line 14, in test_trim_strips_all_unicode
    assert self.trim('Úaø¶') == 'a'
  File "/Users/whit537/personal/gratipay/gratipay.com/tests/ttw/test_trim.py", line 10, in trim
    return self.js("window.Gratipay.trim('{}')".format(val))
  File "/Users/whit537/personal/gratipay/gratipay.com/gratipay/testing/browser.py", line 73, in js
    return self.evaluate_script(code)
  File "/Users/whit537/personal/gratipay/gratipay.com/env/lib/python2.7/site-packages/splinter/driver/webdriver/__init__.py", line 199, in evaluate_script
    return self.driver.execute_script("return %s" % script)
  File "/Users/whit537/personal/gratipay/gratipay.com/env/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 465, in execute_script
    'args': converted_args})['value']
  File "/Users/whit537/personal/gratipay/gratipay.com/env/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 236, in execute
    self.error_handler.check_response(response)
  File "/Users/whit537/personal/gratipay/gratipay.com/env/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 192, in check_response
    raise exception_class(message, screen, stacktrace)
WebDriverException: Message: {"errorMessage":"Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: \"script-src 'self' assets.gratipay.com 'unsafe-inline'\".\n","request":{"headers":{"Accept":"application/json","Accept-Encoding":"identity","Connection":"close","Content-Length":"129","Content-Type":"application/json;charset=UTF-8","Host":"127.0.0.1:63194","User-Agent":"Python-urllib/2.7"},"httpVersion":"1.1","method":"POST","post":"{\"sessionId\": \"737b2390-10be-11e7-a20f-6d0e1704f4cf\", \"args\": [], \"script\": \"return window.Gratipay.trim('\\u02daa\\u00f8\\u00b6')\"}","url":"/execute","urlParsed":{"anchor":"","query":"","file":"execute","directory":"/","path":"/execute","relative":"/execute","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/execute","queryKey":{},"chunks":["execute"]},"urlOriginal":"/session/737b2390-10be-11e7-a20f-6d0e1704f4cf/execute"}}
Screenshot: available via screen

================================= 13 failed, 7 passed in 48.98 seconds ==================================
[gratipay] $
```

**Comment by whit537** [comment]
```
[gratipay] $ phantomjs --version
2.1.1
```

[Latest](http://phantomjs.org/).

**Comment by whit537** [comment]
Moving to a PR in #4391 ...
