### ISSUE TITLE
Giving amount confusing / inconsistent

### ISSUE THREAD

**Issue by deivid-rodriguez** [gratipay/gratipay.com#4367]
I'm not sure whether I'm giving money to RuboCop or not... Am I? I want to :)

![gratipay](https://cloud.githubusercontent.com/assets/2887858/23588242/68add9d2-0199-11e7-8567-99419c2ed6f7.png)

**Comment by deivid-rodriguez** [comment]
Just FYI, I just started giving the recommended percentage of my income to Gratipay!

The number in the giving taking table or in the header still didn't update, though.

**Comment by mattbk** [comment]
I think this is because the number in the header table is calculated on payday (Thursday).

Do you have a credit card hooked up? This is also required, I believe.

**Comment by deivid-rodriguez** [comment]
> I think this is because the number in the header table is calculated on payday (Thursday).

But I've been giving to `RuboCop` for a lot of Thursdays... Or at least thinking I am.

> Do you have a credit card hooked up? This is also required, I believe.

No, I don't. Paypal only.

**Comment by mattbk** [comment]
Yes, I can see from your history that you've been giving to RuboCop...but only intermittently.

I was incorrect earlier; the header should update immediately.

This appears to be related to https://github.com/gratipay/gratipay.com/pull/4255#issue-197367394, which describes how you can end up with a negative balance (through our error, not yours). In such cases, normally your donations to a project would get covered by your credit card, but you don't have one set up. (We know people want to [pay in with PayPal](https://github.com/gratipay/gratipay.com/issues/63), but we're not there yet.)

I'll keep digging around for an answer.

**Comment by deivid-rodriguez** [comment]
I see, so since you're currently not able to pay in through `Paypal`, if the donations I receive were retired... my balance would go negative, right? I guess the user should be informed about this gotcha somehow and encouraged to set up a credit card.

Anyways, all that is different from the bug reported here, right?

**Comment by mattbk** [comment]
If you stopped receiving donations, your balance would stop at $0. The only time it goes negative should be when we make a mistake on our end. What would happen is that RuboCop would see that you were donating, but they wouldn't receive the payout and it would be listed as "Unfunded Dues" on the Receiving page for RuboCop.

@whit537 or @rohitpaulk, any ideas to solve the original issue?

**Comment by deivid-rodriguez** [comment]
Yes, I had just realized that the "negative balance situation" described by @whit537 was different. That's good to know!

**Comment by mattbk** [comment]
This falls under https://github.com/gratipay/gratipay.com/issues/3793, so closing here and picking up over there. [The chalkboard only shows amounts that are backed by a credit card](https://github.com/gratipay/gratipay.com/issues/3793#issuecomment-151962307).

**Comment by deivid-rodriguez** [comment]
Cool, thanks!
