### ISSUE TITLE
Recover access to activeadmin project

### ISSUE THREAD

**Issue by deivid-rodriguez** [gratipay/gratipay.com#4368]
I'm trying to get access to this project: https://gratipay.com/~activeadmin/

Apparently two people had access: @gregbell, who is inactive in GitHub since 2014 and told us he can't access, and @seanlinsley who deleted his gratipay account, so he can't access either.

I'd like to know how to proceed to revive the project.

**Comment by deivid-rodriguez** [comment]
As far as I can see, there's "nothing" there, so I think it would be fine to delete the account, and get it created & re-approved again, if that's easier for you.

**Comment by mattbk** [comment]
https://gratipay.com/~activeadmin/ is a user account, not a project. We can approve a project under the same name if you open an application (the names won't collide).

We don't like to delete accounts because they have transaction history attached, but I will email @gregbell to ask if he minds us changing the username on that account so it is no longer confusingly called ~activeadmin. Or if you know the best way to contact him, please have him drop a line to support@gratipay.com if he doesn't want to post here.

**Comment by mattbk** [comment]
[FD email](https://gratipay.freshdesk.com/helpdesk/tickets/6965).

**Comment by deivid-rodriguez** [comment]
Aaaah, ok. Yeah, the name confused... Although I could've suspected something from the picture... :)

I guess the best thing to do here is whatever @gregbell wants to do, either delete or rename.

**Comment by deivid-rodriguez** [comment]
I created an ActiveAdmin project, up for review: https://github.com/gratipay/project-review/issues/345

**Comment by deivid-rodriguez** [comment]
I can ping you back in a few days and if you haven't got a reply I can try contact him through other means. Sounds good?

**Comment by mattbk** [comment]
:+1:

**Comment by deivid-rodriguez** [comment]
Cool, thanks for your help!

**Comment by deivid-rodriguez** [comment]
@mattbk No news? Shall I try get in touch? Maybe he doesn't use or has lost access to the email associated to his gratipay account.

**Comment by mattbk** [comment]
No word on this end, you can try to get in touch.

**Comment by deivid-rodriguez** [comment]
I've been told that he usually responds to emails but usually takes him a long time to do it. So, since this is not something urgent for us, let's just wait for a long time :)

My plan is to ping you back in a month, for example, and if no news yet by then, I'll assume the contact I've been given is different from the contact Gratipay has, and I'll try to contact him myself. It's just that I want to avoid bothering him twice for the same matter if possible.

Sounds good?

**Comment by mattbk** [comment]
:+1:

**Comment by deivid-rodriguez** [comment]
@mattbk I tried to contact Greg myself, let's see.

**Comment by gregbell** [comment]
Hi Everybody. I've closed the personal ~activeadmin account. Should be good to manage it however you like now. Let me know if you need anything else in regards to this manner.

**Comment by deivid-rodriguez** [comment]
Thanks @gregbell and sorry for bothering you :heart: .

Closing!
