### ISSUE TITLE
Change in Readme - git clone over HTTPS rather than ssh

### ISSUE THREAD

**Issue by clearnote01** [gratipay/gratipay.com#4370]
It makes the clone process a bit easier, eliminates the need of using a public key. 

Change in Readme.md 

> git clone https://github.com/gratipay/gratipay.com.git

instead of

> git clone git@github.com:gratipay/gratipay.com.git

**Comment by whit537** [comment]
@clearnote01 Want to make a PR? Should be doable through the GitHub UI. :-)

**Comment by clearnote01** [comment]
Sure! : )
