### ISSUE TITLE
Displays file paths instead of email with confirmation page.

### ISSUE THREAD

**Issue by kepoorhampond** [gratipay/gratipay.com#4379]
When I clicked on the confirm link for confirming emails, it displays some paths and not my email:
![2017-03-14-190819_1920x1080_scrot](https://cloud.githubusercontent.com/assets/11763039/23930495/e4d14966-08e9-11e7-979f-fc0234abb018.png)

**Comment by whit537** [comment]
Blech, that's embarrassing. Thanks for letting us know, @kepoorhampond!

**Comment by whit537** [comment]
Probably a regression from recent changes to this template?

**Comment by whit537** [comment]
PR in https://github.com/gratipay/gratipay.com/pull/4380.
