### ISSUE TITLE
Add total projects to charts on /about/stats

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#4386]
Old title: "Front page projects should count down, not up."

Rather than last project being number 1, it should be number n, where n is the total number of projects on the tab.

**Comment by mattbk** [comment]
https://9-volt.github.io/bug-life/?repo=gratipay/project-review

**Comment by mattbk** [comment]
Actually, I only want this so we can make a graph of project n milestones...but it should really go at https://gratipay.com/about/stats. Can we add a second (gray?) series behind the green bars for "total projects"?
![image](https://cloud.githubusercontent.com/assets/3729038/24205953/d65f2dc4-0eea-11e7-99cd-dd5062265f17.png)

**Comment by whit537** [comment]
Active projects is actually more interesting and honest. 😶

**Comment by whit537** [comment]
You can see when I stopped giving 5¢ to new projects. 🙈

**Comment by mattbk** [comment]
I agree that active is more interesting, but being able to compare it with total could be more honest.

**Comment by whit537** [comment]
Even more interesting is rate of change.

**Comment by mattbk** [comment]
We could plot the derivative of the curve.
