### ISSUE TITLE
Provide metrics to inform distribution

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4389]
Libraries.io has introduced a [bus factor](https://libraries.io/bus-factor) metric. The idea on this ticket is to feed this metric (or something like it) into the distribution algorithm we come up with underneath https://github.com/gratipay/inside.gratipay.com/issues/987.

Prompted by this feedback from a representative of a [top-25](https://en.wikipedia.org/wiki/List_of_largest_Internet_companies) Internet company:

> We seek a way to know when we are taking a risk by relying upon a project that is at risk of being abandoned. The risk is some measure that takes into account -- how much we rely upon it, how fragile or needy it is, how complex or impossible to assume maintenance on our own if we needed to, how much more funding is needed, etc. Given the plethora of open source project we use, we could use some objective way to ensure we support the ones that we need to support the most (based on our expected value for doing so).

**Comment by whit537** [comment]
Widening scope here to encompass additional info relevant to distribution decisions:

- https://ke4qqq.wordpress.com/2015/02/08/pony-factor-math/
- https://www.coreinfrastructure.org/programs/census-project
- https://libraries.io/bus-factor
- https://libraries.io/unseen-infrastructure
- existing corporate backing (https://github.com/gratipay/inside.gratipay.com/issues/964#issuecomment-274246500)

**Comment by mattbk** [comment]
Does https://github.com/gratipay/gratipay.com/issues/3963 play into this at all for Gratipay 2.0 (i.e., non-package-manager) projects? Or should we leave those alone and just integrate them if they fit within the libraries.io framework once we expand beyond just npm?

**Comment by whit537** [comment]
Not sure. Can we pick this up once there's money to distribute? 😆

**Comment by mattbk** [comment]
Sure, I just wanted to get the thought out there.
