### ISSUE TITLE
Confirmation emails not being sent!?

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4393]
Reported by @dguido [on Twitter](https://twitter.com/dguido/status/846893365677346817).

> Thanks but your confirmation emails are not being sent. I can't confirm my email. It's GApps and it's not in spam

**Comment by whit537** [comment]
I will look at this in a few hours if someone else doesn't get to it first. :)

**Comment by whit537** [comment]
cc: @rohitpaulk?

**Comment by whit537** [comment]
I added an email and am not seeing the verification message. What's in the queue?

**Comment by whit537** [comment]
40 messages, mostly verifications. 😞

**Comment by whit537** [comment]
So we're not flushing the queue? Is the flusher not running, or failing? Or ... ?

**Comment by whit537** [comment]
Let's check the logs ...

**Comment by whit537** [comment]
Okay, I think we got clogged up by bad data from a security researcher. I saw this come through on Sentry the other day ...

```
Mar 29 11:35:17 gratipay app/web.1:  pid-12 thread-139708333029120 (Thread-4) Traceback (most recent call last): 
Mar 29 11:35:17 gratipay app/web.1:  pid-12 thread-139708333029120 (Thread-4)   File "/app/gratipay/cron.py", line 26, in f 
Mar 29 11:35:17 gratipay app/web.1:  pid-12 thread-139708333029120 (Thread-4)     func() 
Mar 29 11:35:17 gratipay app/web.1:  pid-12 thread-139708333029120 (Thread-4)   File "/app/gratipay/email.py", line 104, in flush 
Mar 29 11:35:17 gratipay app/web.1:  pid-12 thread-139708333029120 (Thread-4)     r = self._flush_one(rec) 
Mar 29 11:35:17 gratipay app/web.1:  pid-12 thread-139708333029120 (Thread-4)   File "/app/gratipay/email.py", line 122, in _flush_one 
Mar 29 11:35:17 gratipay app/web.1:  pid-12 thread-139708333029120 (Thread-4)     self._mailer.send_email(**message) 
Mar 29 11:35:17 gratipay app/web.1:  pid-12 thread-139708333029120 (Thread-4)   File "/app/.heroku/python/lib/python2.7/site-packages/botocore/client.py", line 252, in _api_call  
Mar 29 11:35:17 gratipay app/web.1:  pid-12 thread-139708333029120 (Thread-4)     return self._make_api_call(operation_name, kwargs) 
Mar 29 11:35:17 gratipay app/web.1:  pid-12 thread-139708333029120 (Thread-4)   File "/app/.heroku/python/lib/python2.7/site-packages/botocore/client.py", line 542, in _make_api_call 
Mar 29 11:35:17 gratipay app/web.1:  pid-12 thread-139708333029120 (Thread-4)     raise ClientError(parsed_response, operation_name) 
Mar 29 11:35:17 gratipay app/web.1:  pid-12 thread-139708333029120 (Thread-4) ClientError: An error occurred (InvalidParameterValue) when calling the SendEmail operation: Domain contains illegal character 
```

**Comment by whit537** [comment]
https://sentry.io/gratipay/gratipay-com/issues/242242031/

**Comment by whit537** [comment]
![screen shot 2017-03-29 at 7 17 00 am](https://cloud.githubusercontent.com/assets/134455/24452120/bc099e18-144f-11e7-894c-b51f8dc861a3.png)

**Comment by whit537** [comment]
So the workaround is to remove that message from the queue. It should correct itself automatically.

Root cause fix is to automatically remove messages from the queue given certain error conditions.

**Comment by whit537** [comment]
> after which the queue should correct itself automatically.

Are we okay sending old verifications, though?

**Comment by whit537** [comment]
Can we resend new verifications for those affected? The team approval notices can go through as-is.

**Comment by whit537** [comment]
Or at least reset `verification_start` and dedupe?

**Comment by rohitpaulk** [comment]
> Can we resend new verifications for those affected? The team approval notices can go through as-is.

I think that makes sense.

**Comment by whit537** [comment]
Alright, so the procedure is:

1. Extract addresses from verification messages in `email_queue`.
1. Remove duplicate verifications from `email_queue`.
1. Reset `emails.verification_start` for affected addresses.
1. Remove the verifications with bad addresses.
1. Get a PR together for root cause fix.

Ya?

**Comment by whit537** [comment]
I've dumped the queue with:

```
psql> \copy (select * from email_queue order by id) to queue.csv with csv;
```

Then `grep verification queue.csv > verifications.csv` and hand-edited the latter to only have `email_queue.id` and an email address. Now deduping ...

**Comment by whit537** [comment]
```
[gratipay] $ ./dupes.py 
DELETE FROM email_queue WHERE id = ANY('{10788,10789,10808,10806,10796,10778,10804,10772,10773,10791,10798,10799,10801,10766})'::int[]
[gratipay] $
```

http://www.postgresonline.com/journal/archives/228-PostgreSQL-Array-The-ANY-and-Contains-trick.html

```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, print_function, unicode_literals

import csv
from collections import defaultdict


address_to_messages = defaultdict(list)


for message_id, address in csv.reader(open('verifications.csv')):
    address_to_messages[address].append(message_id)

delete = []
for address, messages in address_to_messages.items():
    keep = messages.pop()
    delete.extend(messages)

print("DELETE FROM email_queue WHERE id = ANY('{{{}}})'::int[]".format(','.join(delete)))
```

**Comment by whit537** [comment]
```
gratipay::MAROON=> DELETE FROM email_queue WHERE id = ANY('{10766,10808,10796,10804,10772,10773,10778,10791,10806,10801,10788,10789,10798,10799}'::int[]);
DELETE 14
gratipay::MAROON=>
```

**Comment by whit537** [comment]
(3):

```sql
UPDATE emails SET verification_start=now() WHERE ID = ANY('alice@example.com,bob@example.com'::text[]);
```

**Comment by whit537** [comment]
Starting with:

```sql
SELECT * FROM emails WHERE address = ANY('{...}'::text[]);
```

**Comment by whit537** [comment]
```
gratipay::MAROON=> \i reset-verification.sql
UPDATE 17
┌───────┬─────────────────────────────┬──────────┬──────────────────────────────────────┬────────────────
│  id   │           address           │ verified │                nonce                 │      verificati
├───────┼─────────────────────────────┼──────────┼──────────────────────────────────────┼────────────────
│  ...  │                             │          │                                      │                
└───────┴─────────────────────────────┴──────────┴──────────────────────────────────────┴────────────────
(17 rows)
```

```sql
   UPDATE emails
      SET verification_start=now()
    WHERE address = ANY('{...}'::text[]);

   SELECT *
     FROM emails
    WHERE address = ANY('{...}'::text[])
 ORDER BY verification_start;
```

**Comment by whit537** [comment]
I think I'm also going to send a message from support@ to those affected.

**Comment by whit537** [comment]
Freshdesk doesn't allow bcc's, so we'll have to send individually.

**Comment by whit537** [comment]
Prepped:

> Greetings!
>
>Due to a bug in our email processing, we didn't immediately send out email verifications that were initiated in the past two days. We've [cleared things up](https://github.com/gratipay/gratipay.com/issues/4393) and you should have received the verification now.
>
>Sorry for the trouble, and thanks for using Gratipay! Let us know if there is anything else we can answer or help with. :-)
>
>
>chad
>\----
>Chad Whitacre
>Founder, Gratipay

**Comment by whit537** [comment]
Revised:

> An email verification was initiated for this address in the past two days, but due to a bug on our end, we didn't immediately send it out. We've [cleared things up](https://github.com/gratipay/gratipay.com/issues/4393), and you should have received the verification now.

**Comment by whit537** [comment]
Saved temporarily as a canned response for easier sending.

**Comment by whit537** [comment]
Okay! Ready to pull the plug out?

**Comment by whit537** [comment]
```
gratipay::MAROON=> delete from email_queue where participant = [];
DELETE 3
gratipay::MAROON=> select count(*) from email_queue;
┌───────┐
│ count │
├───────┤
│    23 │
└───────┘
(1 row)
```

**Comment by whit537** [comment]
```
gratipay::MAROON=> select count(*) from email_queue;
┌───────┐
│ count │
├───────┤
│    11 │
└───────┘
(1 row)

gratipay::MAROON=> select count(*) from email_queue;
┌───────┐
│ count │
├───────┤
│     9 │
└───────┘
(1 row)

gratipay::MAROON=> select count(*) from email_queue;
┌───────┐
│ count │
├───────┤
│     8 │
└───────┘
(1 row)

gratipay::MAROON=> select count(*) from email_queue;
┌───────┐
│ count │
├───────┤
│     1 │
└───────┘
(1 row)

gratipay::MAROON=> select count(*) from email_queue;
┌───────┐
│ count │
├───────┤
│     0 │
└───────┘
(1 row)
```

**Comment by whit537** [comment]
Sentry issue resolved. Sending follow-ups ...

**Comment by whit537** [comment]
Okay! Follow-ups sent and received, here at least. :-)

![screen shot 2017-03-29 at 8 31 13 am](https://cloud.githubusercontent.com/assets/134455/24454497/1b3a19b2-145a-11e7-9d4c-35ba5f369f01.png)

**Comment by whit537** [comment]
PR for root cause fix in a bit ...

**Comment by whit537** [comment]
PR in https://github.com/gratipay/gratipay.com/pull/4395.

**Comment by whit537** [comment]
Finally deploying https://github.com/gratipay/gratipay.com/pull/4395 after getting bit by this again. I have a list of emails to apologize to after we flush the queue.

**Comment by whit537** [comment]
https://github.com/gratipay/gratipay.com/pull/4395 deployed.

**Comment by whit537** [comment]
```
gratipay::MAROON=> select dead, count(*) from email_queue group by dead;
┌──────┬───────┐
│ dead │ count │
├──────┼───────┤
│ f    │    79 │
│ t    │     3 │
└──────┴───────┘
(2 rows)
```

**Comment by whit537** [comment]
```
gratipay::MAROON=> select dead, count(*) from email_queue group by dead;
┌──────┬───────┐
│ dead │ count │
├──────┼───────┤
│ t    │     3 │
└──────┴───────┘
(1 row)
```

**Comment by whit537** [comment]
Mail received. 👍

![screen shot 2017-04-24 at 2 06 03 pm](https://cloud.githubusercontent.com/assets/134455/25351624/2f94623a-28f7-11e7-9242-0018f7b934dd.png)

**Comment by whit537** [comment]
Three failures are in Sentry at: https://sentry.io/gratipay/gratipay-com/issues/259220081/. Marking previous as resolved.

**Comment by whit537** [comment]
Now for apologies ...

**Comment by whit537** [comment]
2 down, 55 to go ...

**Comment by whit537** [comment]
Done. Sent 53. Three were the failures that clogged us up in the first (well, second ;) place, the fourth was @mattbk as at https://github.com/gratipay/gratipay.com/pull/4395#issuecomment-296747169.

Closing!
