### ISSUE TITLE
Float "Fund Your Project" button as on homepage

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4394]
# Homepage

![screen shot 2017-03-29 at 7 05 18 am](https://cloud.githubusercontent.com/assets/134455/24451760/14acaaf8-144e-11e7-961b-7a62f10cdb70.png)

# Profile

![screen shot 2017-03-29 at 7 04 25 am](https://cloud.githubusercontent.com/assets/134455/24451732/0399ab08-144e-11e7-8260-0aa251a6eebf.png)

**Comment by d3vil0p3r** [comment]
@whit537 @EdOverflow I would love to try this, is this still open?
