### ISSUE TITLE
"Export as CSV" link on ~user History yields blank CSV file

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#4399]
https://gratipay.com/about/me/history/

![image](https://cloud.githubusercontent.com/assets/3729038/24765504/ae0c8afe-1abd-11e7-9033-3c2c81166c75.png)

**Comment by EdOverflow** [comment]
Just out of interest, what is exported to a CSV file? Is it only the amount or are recipient names included?

**Comment by mattbk** [comment]
https://github.com/gratipay/gratipay.com/blob/4b5b0b3e287424a3e5b4179d49eddac44064f7e4/www/~/%25username/history/export.spt

Looks like 
`participant, year, mode`

**Comment by EdOverflow** [comment]
HackerOne report on its way...

**Comment by EdOverflow** [comment]
The report can be found here: https://hackerone.com/reports/219323

**Comment by rohitpaulk** [comment]
The problem here is that the new Gratipay 2.x changes haven't been carried over properly - we're only considering `transfers` (Gratipay 1.0), not `payments` (Gratipay 2.x)

**Comment by rohitpaulk** [comment]
Might need a few changes in the JSON structure - `tipper`/`tippee` isn't valid terminology anymore.

![screen shot 2017-05-03 at 8 49 14 pm](https://cloud.githubusercontent.com/assets/3893573/25667730/05111114-3042-11e7-942e-d281825ee454.png)

**Comment by rohitpaulk** [comment]
Also, `aggregate` is the only `mode` used, although we support output of individual exchanges and transfers if the parameter isn't supplied. Looks like an undocumented feature, I don't think it is worth maintaining as of now.

**Comment by mattbk** [comment]
Fixed in #4439.
