### ISSUE TITLE
Add faircoin to gratipay

### ISSUE THREAD

**Issue by enricduran** [gratipay/gratipay.com#4402]
Could be great that gratipay integrate faircoin as a way do contribute to open source projects without the fees intermaditions of card systesm,
Faircoin is supported by a broad cooperative movement and is aligned with the values of gratipay.

We could support the integration with the tech community of faircoin and faircoop.

**Comment by whit537** [comment]
Thanks for joining us here, @enricduran! As a matter of regulatory compliance, we can only work with "clearance and settlement systems that admit only BSA-regulated institutions." What is faircoin's regulatory standing?

**Comment by enricduran** [comment]
Thanks for your answer. Faircoin is from the same family than Bitcoin, therefore participate of the same regulatory framework. You can see for example a regulatory guide for Bitcoin in NA here:  https://blog.identitymindglobal.com/general/bitcoin-regulation-address-anti-money-laundering-compliance

**Comment by whit537** [comment]
Is there something like Coinbase for Faircoin?

**Comment by whit537** [comment]
There are two sides to this, payin and payout. For both we would need to consult with a lawyer first to understand the regulatory implications better. Which did you have in mind? One or the other or both?

For payin we'd need to land #1165 first unless we're going to convert faircoin to USD on the fly. #1165 is a ways off, it's a big project and not a priority for us right now (here's our [roadmap](http://inside.gratipay.com/big-picture/roadmap)).

We have a ticket at https://github.com/gratipay/inside.gratipay.com/issues/974 for comparing various additional payment routes and looking at the big picture.
