### ISSUE TITLE
Add social call to action when tip is set

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#4403]
As seen on many other sites. After clicking "save" on amount, we have an alert ribbon. Could include populated tweet and FB post links there.

![image](https://cloud.githubusercontent.com/assets/3729038/24867338/7f7b9816-1dd2-11e7-8467-40e8add43745.png)

**Comment by whit537** [comment]
This may be a dupe, fwiw.

**Comment by mattbk** [comment]
Will look.
