### ISSUE TITLE
Prune expired email verifications

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4408]
@dowski points out at https://github.com/gratipay/gratipay.com/pull/4335#discussion_r111307971 that we might consider regularly pruning expired email verifications (and, by extension, package claims).

```
gratipay::MAROON=> select count(*) from emails where verification_end is null and verification_start < now() - '1 day'::interval;
┌───────┐
│ count │
├───────┤
│  1702 │
└───────┘
(1 row)

gratipay::MAROON=> select count(*) from emails where verification_end is null;
┌───────┐
│ count │
├───────┤
│  1703 │
└───────┘
(1 row)

gratipay::MAROON=> select count(*) from emails;
┌───────┐
│ count │
├───────┤
│  7911 │
└───────┘
(1 row)

gratipay::MAROON=>
```

**Comment by rohitpaulk** [comment]
Interesting

**Comment by whit537** [comment]
Maybe after 30 days so we have them around for a while for debugging if need be?

**Comment by rohitpaulk** [comment]
One way to do this is to add a cron task that purges old verifications. 

Resources that might help: 
 
- [Example of a PR that adds a cron job](https://github.com/gratipay/gratipay.com/pull/4502/files)
- [Code that registers cron tasks](https://github.com/gratipay/gratipay.com/blob/2e55453d9947ad51216e657a55da65bc59ae3ff4/gratipay/application.py#L52)
