### ISSUE TITLE
crypto.py review

### ISSUE THREAD

**Issue by EdOverflow** [gratipay/gratipay.com#4409]
I have been looking at `crypto.py` and have noted a couple of things.

## 1) Constant time comparison

Why do we not just use `hmac.compare_digest()` for `constant_time_compare()`?

~~~diff
def constant_time_compare(val1, val2):
    """
    Returns True if the two strings are equal, False otherwise.
    The time taken is independent of the number of characters that match.
    """
-   if len(val1) != len(val2):
-       return False
-   result = 0
-   for x, y in zip(val1, val2):
-       result |= ord(x) ^ ord(y)
-   return result == 0
+   return hmac.compare_digest(force_bytes(val1), force_bytes(val2))
~~~

## 2) Encoding

Why do we not encode the string?

~~~diff
random.seed(
            hashlib.sha256(
                "%s%s%s" % (
                    random.getstate(),
                    time.time(),
-                    UNSECURE_RANDOM_STRING)
+                    UNSECURE_RANDOM_STRING).encode()
                ).digest())
~~~

**Comment by whit537** [comment]
1) Didn't know about `compare_digest`, looks suitable. Our `crypto.py` is descended from Django. Happy to swap that code out.

2) I don't know. :) Why would we want to?

**Comment by EdOverflow** [comment]
> Didn't know about compare_digest, looks suitable. Our crypto.py is descended from Django. Happy to swap that code out.

I will submit a PR.

> I don't know. :) Why would we want to?

For some reason, I assumed we were feeding it with bytes. ¯\\\_(ツ)_\/¯

**Comment by whit537** [comment]
Ftr PR was https://github.com/gratipay/gratipay.com/pull/4412.
