### ISSUE TITLE
IMG SRC tag after ~usr/ causing odd redirection behavior.

### ISSUE THREAD

**Issue by B3nac** [gratipay/gratipay.com#4419]
When I put the following xss payload after the user directory:

https://gratipay.com/~B3nac/IMG%20SRC=jAVasCrIPt:alert(%E2%80%98XSS%E2%80%99)

Gratiplay doesn't redirect properly and adds a lot of ~ before the username like so.

![url](https://cloud.githubusercontent.com/assets/7663357/25302841/2da653d6-26fc-11e7-9f30-45a4313f4bde.png)

I stumbled upon this while testing for DOM XSS in the statement box and then following the IMG SRC links in the page source code. I'm not entirely sure what is causing this error.

**Comment by whit537** [comment]
Thanks @B3nac. There's a function to redirect `/foo/` to `/~foo/` and that's probably wha'ts getting confused.

**Comment by whit537** [comment]
[`use_tildes_for_participants `](https://github.com/gratipay/gratipay.com/blob/2070/gratipay/utils/__init__.py#L50)
