### ISSUE TITLE
Marking a user as suspicious doesn't update 'giving' value on teams

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#4420]
- User `Alice` gives $10 to team `EvilCorp`
- User `Alice` gets marked as suspicious

**Expected:** 
`EvilCorp`'s value for `receiving` must reduce by $10

**Actual**
`EvilCorp`'s value for `receiving` stays the same

**Comment by EdOverflow** [comment]
![](https://media.giphy.com/media/p2Odpzf87PSkU/giphy.gif)

Sorry, I had to.

**Comment by mattbk** [comment]
Is that in here?

https://github.com/gratipay/gratipay.com/blob/5ace6cd9ccfcb7d68abef109110038f02c9cccb6/gratipay/models/team/__init__.py#L275-L304?

When does this get called?

**Comment by mattbk** [comment]
Oh, I see. Essentially it is part of `set_payment_instruction()`.

**Comment by mattbk** [comment]
So first you would need to grab all the projects that a ~user is giving to (before becoming suspicious) and then run `team.update_receiving` on each one?
