### ISSUE TITLE
Bug in revive allows one participant to get another's paypal?

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4437]
Reticketed from https://github.com/gratipay/gratipay.com/pull/4428. Get into the revive test and code. I don't think we scope sufficiently to the participant.

**Comment by rohitpaulk** [comment]
Hmm, I don't see anything obvious: 

![route](https://cloud.githubusercontent.com/assets/3893573/25776156/55804162-32d4-11e7-8849-1bb27d029359.png)

**Comment by whit537** [comment]
Thanks for reviewing.
