### ISSUE TITLE
Renew TLS certificates at Let's Encrypt

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#4441]
Expire on May 11.

https://gratipay.freshdesk.com/helpdesk/tickets/8237
https://gratipay.freshdesk.com/helpdesk/tickets/8250
https://gratipay.freshdesk.com/helpdesk/tickets/8252

**Comment by whit537** [comment]
This is on my radar to get done this week before I leave for https://github.com/gratipay/inside.gratipay.com/issues/948. Probably tomorrow?

**Comment by whit537** [comment]
Can we work on this together on Monday, @clone1018? You okay with punting until then?

**Comment by whit537** [comment]
Closing this in favor of https://github.com/gratipay/inside.gratipay.com/issues/1051.
