### ISSUE TITLE
Contact Travis CI about upgrading Postgres to 9.6.2

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#4445]
Reticketed from https://github.com/gratipay/gratipay.com/pull/4438#issuecomment-299441124

**Comment by whit537** [comment]
Sent.

Subject: upgrade Postgres add-on to 9.6.2?

> We just upgraded our application to Postgres 9.6, and unfortunately we're hitting a bug that is present in 9.6.1, which is the version available on Travis when specifying `postgres=9.6`. The bug is fixed in 9.6.2. Could you let me know when you're able to upgrade the Postgres add-on to 9.6.2?
>
Thanks! :-)

**Comment by whit537** [comment]
Heard back from @meatballhat. :-)

**Comment by whit537** [comment]
Suggested workaround:

```
before_install:
  - sudo add-apt-repository "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main"
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install postgresql-9.6
```

**Comment by rohitpaulk** [comment]
> Suggested workaround:

I've applied that to https://github.com/gratipay/gratipay.com/pull/4444, let's see..

**Comment by rohitpaulk** [comment]
The workaround worked
