### ISSUE TITLE
Get deployment back on track w/ npm in search

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4459]
When we deployed https://github.com/gratipay/gratipay.com/pull/4458 yesterday, the site slowed down significantly, to the point where it was unusable and we rolled back in Heroku ([slack](https://gratipay.slackarchive.io/gratipay/page-98/ts-1494428056110009)). We need to get back on track.

**Comment by rohitpaulk** [comment]
Health dashboard for the last 3 days: 

![screen shot 2017-05-11 at 5 43 47 pm](https://cloud.githubusercontent.com/assets/3893573/25948530/81abf646-3671-11e7-9dd6-3059b80248bd.png)

**Comment by rohitpaulk** [comment]
The response time spike started at 9 May, 18:30 (UTC) (around midnight indian time). 

![screen shot 2017-05-11 at 5 45 52 pm](https://cloud.githubusercontent.com/assets/3893573/25948573/bd12b620-3671-11e7-9a0e-719a94d959b6.png)

I see 2 deploys around that time: 

![screen shot 2017-05-11 at 5 49 58 pm](https://cloud.githubusercontent.com/assets/3893573/25948690/53d9f532-3672-11e7-8842-c89416f68580.png)

**Comment by rohitpaulk** [comment]
The first one (before rollback) is: https://github.com/gratipay/gratipay.com/commit/64ff91e7f6d80510bf6e3cc17186a7c29a168190

**Comment by whit537** [comment]
I rolled us forward again a few minutes ago and the site is still exhibiting normal response times relative to the (higher perc99) baseline since #4305.

**Comment by whit537** [comment]
@rohitpaulk I think we should close this out and open a new ticket about bringing our overall response times down. Eh?
