### ISSUE TITLE
Investigate spike in response time

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#4460]
Looks like the spike started after #4305 was deployed. Split out from #4459

**Comment by rohitpaulk** [comment]
https://github.com/gratipay/gratipay.com/issues/4459#issuecomment-300771123

**Comment by rohitpaulk** [comment]
[notes on slack](https://gratipay.slack.com/archives/C36LJJF9V/p1494511808681584)

**Comment by rohitpaulk** [comment]
A few stats to get started: 

Gratipay does an average of 300 requests/minute i.e. 5 requests/sec (screenshot from heroku attached)

![screen shot 2017-05-11 at 8 42 59 pm](https://cloud.githubusercontent.com/assets/3893573/25956842/76008ece-368a-11e7-934a-32e04f3bd212.png)

Our web server is gunicorn, and we run it with a single worker of the 'synchronous' worker type. If we look at Gratipay as a restaurant, we have a single waiter (worker, in gunicorn terms) for multiple customers (requests, in gunicorn terms). Given 5 customers/sec and a waiter who can only process one customer at a time - the waiter will be able to serve all requests on time as long as each customer takes less than 200ms to serve. If the requests/sec falls below 5, the waiter will have idle time. If the requests/sec goes above 5 - certain customers will have to wait for the waiter to finish requests for other customers before they can be served. 

This can be proven by hitting gratipay concurrently with a sizable request (homepage is a good example) and observing response times. 

First, let's take github.com as an example to prove how a web server within capacity responds. 

![github](https://cloud.githubusercontent.com/assets/3893573/25957965/1762d414-368d-11e7-85ac-bdd0951c0e83.png)

Next, let's take the Gratipay homepage. Since we're almost exhausting our capacity, the response times vary a lot because certain requests are waiting on the others to finish. 

![gratipay_home](https://cloud.githubusercontent.com/assets/3893573/25958005/35a33cde-368d-11e7-8987-462cfe44c8bb.png)

Note though, this is only visible for endpoints that have significant processing time. If the endpoint is light (`gratipay.com/version.txt`, for example), this can't be observed: 

![gratipay_version](https://cloud.githubusercontent.com/assets/3893573/25958045/52007eb4-368d-11e7-89d4-226ef6949823.png)

**Comment by rohitpaulk** [comment]
There are two solutions to this: 

- Increase the number of waiters in the restaurant (add a dyno, add a gunicorn worker, change to threaded server etc.)
- Decrease the time it takes to serve a customer (optimize expensive requests)

**Comment by rohitpaulk** [comment]
The former is easier, as long as we've designed for that possibility. I remember and issue created about this... trying to fetch it

**Comment by rohitpaulk** [comment]
Related: https://github.com/gratipay/gratipay.com/issues/1098

**Comment by rohitpaulk** [comment]
Similar work done in https://github.com/gratipay/gratipay.com/issues/1617, apparently [`ab` on Mac has limitations](https://github.com/gratipay/gratipay.com/issues/1617#issuecomment-27704841)?

**Comment by rohitpaulk** [comment]
> apparently `ab` on Mac has limitations?

I'm not going down this route right now - if it works fine on GitHub.com but not Gratipay.com, unlikely to be an `ab` limitation

**Comment by rohitpaulk** [comment]
> I remember an issue created about this... trying to fetch it

Hmm, still can't find it. I vaguely remember that it listed two reasons that we won't be able to run multiple dynos/processes: 

- Crons were locking in-memory (they should use the database). I think this is solved now
- Something OAuth related, where we store an authorization token in memory?

**Comment by mattbk** [comment]
Even allowing multiple requests for non-auth pages seems like it would help.

**Comment by Changaco** [comment]
@rohitpaulk I believe #715 is the issue you're thinking of.

**Comment by rohitpaulk** [comment]
Exactly, thanks

**Comment by rohitpaulk** [comment]
> Even allowing multiple requests for non-auth pages seems like it would help.

True. I'd treat that as a last resort though, better if we don't have to drop requests :)

**Comment by rohitpaulk** [comment]
Edited https://github.com/gratipay/gratipay.com/issues/4460#issuecomment-300828057 to include ^

**Comment by rohitpaulk** [comment]
Now that #715 is closed, I think we can go ahead and add more capacity. I'm pretty confident that adding a dyno will work fine, not sure about increasing the the worker count for gunicorn. Will wait for @whit537's confirmation for the latter - I'm going to go ahead and add another dyno for now.

**Comment by rohitpaulk** [comment]
> Heroku apps running on Professional-tier dynos (any dyno type except Free or Hobby) can be scaled to run on multiple dynos simultaneously.

😞 Heroku removed support for horizontal scaling if dynos are of the 'Hobby' type. Professional dynos start at $25/month, we're currently at $7/month. 

Might have to look into the gunicorn worker count.

**Comment by mattbk** [comment]
[Slack](https://gratipay.slackarchive.io/gratipay/page-99)
>  Gittip's slowness mostly comes for non-optimized DB queries, adding dynos doesn't scale the DB AFAIK, so it potentially just makes it worst by increasing the rate of queries [irc](https://botbot.me/freenode/gratipay/2014-07-04/?msg=17463286&page=1)

> ok i remember our scaling issues were because some tokens were held in memory vs database

**Comment by whit537** [comment]
If we're looking at gunicorn worker count we should also have [h1:203366](https://hackerone.com/reports/203366) in mind.

**Comment by rohitpaulk** [comment]
> Gittip's slowness mostly comes for non-optimized DB queries, adding dynos doesn't scale the DB AFAIK, so it potentially just makes it worst by increasing the rate of queries

I think the situation was different then. Our baseline response time might be slower now because of non-optimized DB queries (customer who take a long time to order), but the huge spikes are not because of them - it is because of requests (not enough waiters) piling up.

**Comment by rohitpaulk** [comment]
I've increased the gunicorn worker count to 2 on production. Will posts results in a while

**Comment by rohitpaulk** [comment]
I'm seeing a few spikes - will revert in 30 minutes if it doesn't settle down

**Comment by rohitpaulk** [comment]
Reverted, that didn't work out well. I'll figure out a way to try this in a staging environment.

**Comment by rohitpaulk** [comment]
I've created staging apps on my personal account before, going to experiment with Heroku pipelines now so that we can document how this is done

**Comment by rohitpaulk** [comment]
After a lot of experimenting with staging, I'm coming to the conclusion that our spikes are mostly due to the homepage. I'm going to run a quick experiment on staging to prove it - will need to provision a Standard database for a couple of hours

**Comment by rohitpaulk** [comment]
Confirmed. Most of the spikes correspond with periods when the homepage was accessed directly. Surprisingly, a vast majority of our requests are for `widget.html` and `public.json` - not the homepage.

Tests against staging with our same database: 

![response](https://cloud.githubusercontent.com/assets/3893573/26079606/f56a3800-39e0-11e7-9de8-b1f424bcbeae.png)

(yellow is the response time within Aspen, green is the total response time including time spent in heroku)

**Comment by rohitpaulk** [comment]
Two steps to fix this: 

- Reduce size of homepage, only load featured (https://github.com/gratipay/gratipay.com/pull/4470)
- Add pagination to teams listing

**Comment by mattbk** [comment]
I like it. Rather than listing all the teams on the homepage, maybe we should beef up the search capabilities with additional filters?

**Comment by rohitpaulk** [comment]
> Rather than listing all the teams on the homepage, maybe we should beef up the search capabilities with additional filters?

Yep, that is something that we can look into too.

**Comment by rohitpaulk** [comment]
Investigation done, we now know what to focus on. Closing

**Comment by whit537** [comment]
:male_detective:

**Comment by whit537** [comment]
So satisfying! 💃

http://inside.gratipay.com/appendices/health

# 24 Hours

![screen shot 2017-05-16 at 7 55 32 pm](https://cloud.githubusercontent.com/assets/134455/26132952/ade69f3c-3a71-11e7-9c4a-674ffdf96b91.png)

# 4 Weeks

![screen shot 2017-05-16 at 7 55 15 pm](https://cloud.githubusercontent.com/assets/134455/26132955/b11078d6-3a71-11e7-8a36-b977d6d93483.png)
