### ISSUE TITLE
Strip markdown from npm descriptions

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4461]
😞 

https://gratipay.com/on/npm/Express/

![screen shot 2017-05-11 at 7 51 02 am](https://cloud.githubusercontent.com/assets/134455/25949857/a116e818-361e-11e7-84c1-6d2a7a07b511.png)

**Comment by whit537** [comment]
Can we render to markdown (I guess using marky-markdown after all) and then [strip all HTML](http://stackoverflow.com/a/925630)?

**Comment by rohitpaulk** [comment]
Or.. just render to HTML? If npm does it, we could too?

**Comment by whit537** [comment]
@rohitpaulk A big part of the reason we backed off of including READMEs on the package pages is that rendering markdown increases security issues. It seems that rendering and then stripping is the simplest way to keep our security surface minimal while avoiding the unsightliness of unrendered markdown.

**Comment by whit537** [comment]
https://twitter.com/Gratipay/status/870024324199088128 😞

![screen shot 2017-05-31 at 5 10 29 pm](https://cloud.githubusercontent.com/assets/134455/26654242/15a99d1e-4624-11e7-8664-c0e7d960fce5.png)

**Comment by whit537** [comment]
Maybe use https://pypi.python.org/pypi/bleach for this?

**Comment by whit537** [comment]
`<meta name="description"` looks like a good way to get what npm is actually rendering. We can bleach based on that.

![screen shot 2017-05-31 at 5 21 31 pm](https://cloud.githubusercontent.com/assets/134455/26654668/b1ea7d46-4625-11e7-80b0-4dc777d87c5c.png)

Or maybe https://stackoverflow.com/questions/38670851/whats-a-script-type-application-ldjsonjsonobj-script-in-a-head-sec

![screen shot 2017-05-31 at 5 24 25 pm](https://cloud.githubusercontent.com/assets/134455/26654766/04e946d0-4626-11e7-875b-409924af8d2f.png)

view-source:https://www.npmjs.com/package/Express

**Comment by whit537** [comment]
I like the idea of using npmjs.org as a microservice for this rather than installing `marky-markdown` locally (and trying to keep up with changes to it). We'll still need to bring back the processing machinery:

- add a NULL-able `description_rendered` field to `packages`
- in templating, fall back on `description` if `description_rendered` is missing
- use a `description_render_state` field to signal need to rerender, do that on update and of course for all to start with
- run in the same dyno (separate thread) as the change stream consumer
- add an instrument to the [dashboard](http://inside.gratipay.com/appendices/health) for readme processing lag

**Comment by whit537** [comment]
Looks like we would need to unescape before bleaching.

**Comment by whit537** [comment]
> Or.. just render to HTML? If npm does it, we could too?

I've been thinking that we should be more conservative than npm, because we have money on the line. Also, in this context there would be design issues if we have blockquotes or whatever in the description. I suppose we could look at what markup actually exists in the corpus at hand before deciding.

**Comment by whit537** [comment]
Talking IRL, seems like a regular expression would be the simplest way to parse `ld+json` from the npm package page source. Then `json.loads` that and voilà.

**Comment by kaguillera** [comment]
Make sense so I am going to work on this.

**Comment by whit537** [comment]
Untested:

```python
re.match(r'.*?<script type="application/ld+json">(.*?)</script>.*', npm_page_source, re.MULTILINE | re.DOTALL).groups()[0]
```

**Comment by kaguillera** [comment]
tanx
