### ISSUE TITLE
Show package description in search results

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4462]
Kinda plain otherwise.

![screen shot 2017-05-11 at 8 15 29 am](https://cloud.githubusercontent.com/assets/134455/25951040/2106e110-3622-11e7-9a05-6bbd4e2c1923.png)

**Comment by kaguillera** [comment]
Should this be closed because it looks a little different now.

**Comment by kaguillera** [comment]
Oh I think what is necessary...these are projects that have not been claimed.

**Comment by whit537** [comment]
Yeah the description should come from the `packages` table, but this will increase pressure on #4461 since that will now show up in an additional context.
