### ISSUE TITLE
Setup a staging environment on heroku

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#4465]
While working on https://github.com/gratipay/gratipay.com/issues/4460, realized that it would be  useful to have a separate app ready to test configuration changes.

**Comment by rohitpaulk** [comment]
Yay! I have a basic app up: http://gratipay-staging.herokuapp.com/?tab=approved

**Comment by rohitpaulk** [comment]
Heroku pipelines don't seem to support organization accounts :/ Every time I try to create one, it gets created under my person account. I tried the CLI tool too, didn't work. I've written to support asking if there is a workaround.

**Comment by rohitpaulk** [comment]
This has been super useful! I've already [upgraded us from cedar-14 to heroku-16](https://github.com/gratipay/gratipay.com/issues/4467), and [removed one extra step from payday](https://github.com/gratipay/inside.gratipay.com/pull/1062).

**Comment by rohitpaulk** [comment]
We don't have access to free dynos though, I had to manually dial down the web dyno count to 0 once I was done.

**Comment by rohitpaulk** [comment]
Hmm, the heroku postgres DB we get is always 9.6.1, not 9.6.2 (like we have on production). Looks like they have a lot of old pre-made DBs for the hobby tier that haven't exhausted? I've written to support asking for help.

**Comment by rohitpaulk** [comment]
> Heroku pipelines don't seem to support organization accounts :/ Every time I try to create one, it gets created under my person account. I tried the CLI tool too, didn't work. I've written to support asking if there is a workaround.

Heard back from heroku - 

> Pipelines don't currently have a notion of an owner. We do track who created the pipeline, but the ownership and access control of the pipeline is that of the apps inside the pipeline. This is a gap that we plan on starting to addressing this quarter. If your expectation is that other people in your organization start seeing the pipeline, they will do so once you add apps to the pipeline that they've got access to.

**Comment by rohitpaulk** [comment]
> Hmm, the heroku postgres DB we get is always 9.6.1, not 9.6.2 (like we have on production). Looks like they have a lot of old pre-made DBs for the hobby tier that haven't exhausted? I've written to support asking for help.

Heard back..

> Hobby tier databases are added to multitenant hosts on the fly and based upon density of the host and the resulting point release for the hobby plan is dependent on the host. Most of these multitenant hosts are 9.6.1 but there are a couple 9.6.2 hosts out there. Unfortunately, there is no way to select 9.6.2 so you would have to keep trying until you landed on one.
> 
> Sorry that I don't have better news here. Give that a shot and let us know if you have any other questions.

**Comment by rohitpaulk** [comment]
Managed to get a 9.6.2 DB attached.

**Comment by whit537** [comment]
Will this staging server be long-lived? Could we get some docs on usage, maybe as a howto on Inside Gratipay?

**Comment by rohitpaulk** [comment]
> Will this staging server be long-lived? 

The app will be long-lived, but as of now I'm only activating dynos as and when we need them. 

> Could we get some docs on usage, maybe as a howto on Inside Gratipay?

Definitely. I'm going to keep this open for a while until I manage to lower the barrier of entry - via docs, processes etc.
