### ISSUE TITLE
Reduce scope of custom heroku buildpack

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#4466]
Over on https://github.com/heroku/heroku-buildpack-python/issues/299, we discovered that the default Heroku python buildpack does not work with local pip packages. To get around this, we started using a [custom buildpack](https://github.com/gratipay/buildpack-python), with [this change](https://github.com/gratipay/buildpack-python/commit/1227f1e68d0ed94574d4973b3692ec80c9a84916#comments). 

Now that Heroku supports multiple buildpacks, we can reduce the scope of https://github.com/gratipay/buildpack-python to **only** install `libffi`.

Making this change will require some testing at Heroku, which will be pretty easy once https://github.com/gratipay/gratipay.com/issues/4465 is done.

**Comment by clone1018** [comment]
I think we're also needlessly including the nodejs buildpack
