### ISSUE TITLE
Certain postgres metrics not being reported since upgrade

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#4471]
Sent to Heroku: 

<hr/>

Hi, 

I was looking at our Librato stats, looks like the `read-iops` metric is no longer being reported (it always has a value of 0). 

![Screen Shot 2017-05-15 at 7.39.44 PM.png](https://heroku-support-production.s3.amazonaws.com/485b7006-1d37-4ea9-9b39-0745462cbafc%2F071a22d5-2722-4970-8fd1-1c0ff8f71176%2FScreen+Shot+2017-05-15+at+7.39.44+PM.png)

To make sure this wasn't a Librato integration bug, I checked the raw logs: 

![Screen Shot 2017-05-15 at 7.34.26 PM.png](https://heroku-support-production.s3.amazonaws.com/485b7006-1d37-4ea9-9b39-0745462cbafc%2F071a22d5-2722-4970-8fd1-1c0ff8f71176%2FScreen+Shot+2017-05-15+at+7.34.26+PM.png)

If it helps, we did upgrade our database around that time - could be related to the new version? 

Regards,
Paul

<hr/>

**Comment by whit537** [comment]
@rohitpaulk Maybe browse the list of available metrics in Librato? Perhaps it was simply renamed?

**Comment by rohitpaulk** [comment]
> Perhaps it was simply renamed?

The metric is still being reported, with a value of `0`.

**Comment by whit537** [comment]
Mmmm.

**Comment by rohitpaulk** [comment]
> Hi Paul,

> If your dataset is entirely memory resident that it's not unreasonable that read iops are frequently reported as 0. Additionally, the API we rely on to retrieve the underlying io numbers on these volumes is convoluted and practically eliminates the possibility of acquiring pinpoint accurate numbers. Instead we must rely on proxy metrics like blkio.throttle.io_service_bytes. The iops metrics are most useful in marking out trends and spikes and using this information as a guide when trying to debug performance issues.

> Given that your dataset is modest relative to the available cache on your plan I would not anticipate that your instance will consume much in the way of piops until it begins to outgrow the plan. Hopefully this explanation makes the io metrics a little more useful to you.

> Let us know if there is anything else we can help with.

> Cheers,
> Bradley
