### ISSUE TITLE
Can gratipay be adapted and used to crowdfund persons (donation for personal projects) ?

### ISSUE THREAD

**Issue by HTCode** [gratipay/gratipay.com#4474]
I am wondering if it is easily possible to modify gratipay  and use it as a donation crowdfunding platform ? Is it straightforward to do ?
Also is, it possible to donate for a project only once and not on weekly basis ?

**Comment by whit537** [comment]
> I am wondering if it is easily possible to modify gratipay and use it as a donation crowdfunding platform ? Is it straightforward to do ?

Are you asking about running a separate modified instance of Gratipay for your own purposes? That's not what Gratipay is designed for—we're designed for the single instance at https://gratipay.com/—so it's probably not straightforward.

What are the limitations of https://gratipay.com/ as it stands today for what you hope to accomplish?

> Also is, it possible to donate for a project only once and not on weekly basis ?

I've added a +1 for you to #5.

**Comment by HTCode** [comment]
@whit537 Yes I am asking about running a separate modified instance of Gratipay for my own purposes. I am not sure what you mean by "we're designed for the single instance".

**Comment by whit537** [comment]
> Yes I am asking about running a separate modified instance of Gratipay for my own purposes. 

Gotcha.

> I am not sure what you mean by "we're designed for the single instance".

I mean that, while you're certainly free to spin up your own instance of this software, our development decisions are based on the needs of hosting https://gratipay.com/, not on running other instances. As an example, if you wanted to modified the code to work with a database other than Postgres, we wouldn't be interested in a PR for that.

Good luck! :-)
