### ISSUE TITLE
Events page is 500

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4478]
https://gratipay.com/~whit537/events/

But I'm not seeing it in Sentry?

**Comment by mattbk** [comment]
Seems to be only on production?

**Comment by whit537** [comment]
Hit this under https://github.com/gratipay/inside.gratipay.com/issues/1110#issuecomment-313436926 ([slack](https://gratipay.slackarchive.io/gratipay/page-100/ts-1499355387116544)).

**Comment by whit537** [comment]
E.g.: https://sentry.io/gratipay/gratipay-com/issues/271315249/

**Comment by whit537** [comment]
Even in the db:

```
gratipay::DATABASE=> SELECT * FROM events WHERE type = 'participant' AND payload->>'id' = '495913' order by ts desc;
ERROR:  unsupported Unicode escape sequence
DETAIL:  \u0000 cannot be converted to text.
CONTEXT:  JSON data, line 1: {"values": {"email":...
gratipay::DATABASE=> SELECT * FROM events WHERE type = 'participant' AND payload->>'id' = '1453' order by ts desc;
ERROR:  unsupported Unicode escape sequence
DETAIL:  \u0000 cannot be converted to text.
CONTEXT:  JSON data, line 1: {"values": {"email":...
gratipay::DATABASE=>
```

**Comment by mattbk** [comment]
That's a `NULL` value? https://stackoverflow.com/questions/31671634/handling-unicode-sequences-in-postgresql

**Comment by mattbk** [comment]
This is still freaking annoying for support.
