### ISSUE TITLE
Reverse project numbering on homepage

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#4484]
The latest projects should have higher numbers when looking at the full list. This would easily let someone see how many projects there are (same as n=).

I swear I suggested this somewhere else but I can't find it.

**Comment by whit537** [comment]
Not sure I agree. If there's any value to showing those numbers at all, it's to be able to determine things like "g20 is the fourth most recently approved project on Gratipay." That doesn't add much value right now, but will be more interesting once we start adding other sorting options (dollar amounts in particular).

**Comment by whit537** [comment]
I think we should bring back `N=` in some more subtle way once the current status tabs evolve into more general filters.
