### ISSUE TITLE
Specify target amount for projects and take small commissions on payments.

### ISSUE THREAD

**Issue by HTCode** [gratipay/gratipay.com#4486]
I would like to run a separate modified instance of Gratipay for my own purposes, in order to use it as a donation crowdfunding platform for various types of projects.

I am wondering if it is reasonably easy to modify the software to:
- Specify a target amount when creating a new project.
- Take small commissions on payments, or on project basis if it reaches a certain amount.

Any ideas on how to proceed with that? Which parts of the source code should I focus on more to achieve this?

**Comment by whit537** [comment]
Sorry, @HTCode. As mentioned on https://github.com/gratipay/gratipay.com/issues/4474, you're welcome to run your own instance of Gratipay, but we don't provide support for that use case. Good luck!
