### ISSUE TITLE
Email link UX issue

### ISSUE THREAD

**Issue by JVimes** [gratipay/gratipay.com#4489]
Users click email links and often this this:

![image](https://cloud.githubusercontent.com/assets/6148201/26510550/0f722810-421b-11e7-945c-4a3810e82d9c.png)

That makes the user think they did something wrong or that your system is broken. I know there's a login prompt down there, but its ***tiny*** compared to the tremendous 401 banner. Users don't care about HTTP error codes, so I suggest getting rid of the 401 banner and giving the prompt more presence:

![image](https://cloud.githubusercontent.com/assets/6148201/26510810/4cbb688e-421c-11e7-9d5d-248a8ed9390c.png)

If you really want the error code, make it the thing that's tiny.

![image](https://cloud.githubusercontent.com/assets/6148201/26510996/2e29158c-421d-11e7-8914-1bf5f8009edb.png)

**Comment by rohitpaulk** [comment]
Thanks for the report, @JVimes. This is definitely embarrassing, I see no reason to expose the `401` on that page.

**Comment by whit537** [comment]
> This is definitely embarrassing

We even have a label for that! 😊

**Comment by whit537** [comment]
P.S. This may actually be a dupe, but leaving open for now.

**Comment by JVimes** [comment]
Could be. It's about the same as #4040, which was closed.
