### ISSUE TITLE
Link to givers from project history for admin

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4490]
Admin should be able to link to specific accounts as we do on participant history page.

**Comment by kaguillera** [comment]
Correct me if I am wrong is Project = Team. If yes then on then aren't the givers on the Team history page `Anonymous`?  

Do you want to change that?

**Comment by whit537** [comment]
Yes, project = team. They are anonymous to receivers (until ever we get to #3112), but admins should still be able to see them. Can be helpful during fraud review.

**Comment by kaguillera** [comment]
So do you want [this](https://github.com/gratipay/gratipay.com/pull/3112) after has been accomplished or should givers be visible to admins only before #3112  drops. I could work on this since we are postponing backfill for now?

**Comment by whit537** [comment]
Admins only. Shouldn't wait for #3112. We have an `if admin` flag on the participant history page, should be parallel here.
