### ISSUE TITLE
Broken URL links for npm packages with special characters? 

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#4496]
From @calvinhp on [Slack](https://gratipay.slackarchive.io/gratipay/page-100/ts-1496325029088097): 

> I just found a 404 :slightly_smiling_face:
> If I search for Plone, the first matching project is @plone/plone-react
> but it is a 404

[Search results](https://gratipay.com/search?q=Plone): 

![screen shot 2017-06-01 at 8 00 50 pm](https://cloud.githubusercontent.com/assets/3893573/26684619/1246a946-4705-11e7-821f-04d03028cbdb.png)

Broken Link: https://gratipay.com/on/npm/@plone/plone-react/

I tried URL encoding it to be https://gratipay.com/on/npm/%40plone%2Fplone-react/, didn't work. I've encountered similar problems with common routing libraries where a `/` can't be URL-encoded and placed in the URL, although the spec supports it - might be related.

**Comment by whit537** [comment]
Blorg. At a minimum I guess we need to support these under `/on/npm/`. We don't allow forward slash in Gratipay project slugs (for, ahem, obvious reasons). So what are we going to do with projects claimed from these packages?

**Comment by whit537** [comment]
We also [don't](https://github.com/gratipay/gratipay.com/blob/2099/gratipay/models/team/__init__.py#L23) allow `@`.

**Comment by whit537** [comment]
It looks to me like this is a namespacing hack. We plan to implement namespacing (#4246), at which point the obvious thing to do is undo npm's hack and simply name the project `plone-react`. We could do the same now against the promise of #4246.

**Comment by whit537** [comment]
I think it's safer to consume the remainder of the string under `/on/npm/` since we're not expecting to use that URL space for other things.

**Comment by whit537** [comment]
Can npm packages have `/` as the final character in their name? If so we've got a trailing slash race.

**Comment by whit537** [comment]
> simply name the project `plone-react`

That's what they're doing on GitHub anyway: https://github.com/plone/plone-react.

**Comment by whit537** [comment]
> If so we've got a trailing slash race.

I guess we can do an extra db query if we don't find a match under `/` or vice-versa.

**Comment by whit537** [comment]
Though the trailing slash case should be so rare that we should always try the non-trailing db query first I think. Much more likely to send `/on/npm/foo/` and want `/foo` than the other way around.

**Comment by whit537** [comment]
I think the name itself can't include a `/`:

> The name ends up being part of a URL, an argument on the command line, and a folder name. Therefore, the name can't contain any non-URL-safe characters.

https://docs.npmjs.com/files/package.json

**Comment by whit537** [comment]
How are scoped packages stored in our packages table?

**Comment by whit537** [comment]
With the scope in the name. 👍 

```
gratipay::DATABASE=> select * from packages where name like '@%' limit 10;
┌────────┬─────────────────┬──────────────────────────────────────────┬──────────────────────────────────
│   id   │ package_manager │                   name                   │                                 d
├────────┼─────────────────┼──────────────────────────────────────────┼──────────────────────────────────
│ 872909 │ npm             │ @zeke/scopey                             │ A package for testing npm scopes 
│ 873868 │ npm             │ @scdhhs/document-services                │ A collection of services that pro
│ 874294 │ npm             │ @lib/tsargs                              │ Adapter for using tsconfig.json f
│ 874527 │ npm             │ @asaayers/react-a11y                     │ Warns about potential accessibili
│ 874540 │ npm             │ @dmail/test                              │                                  
│ 874829 │ npm             │ @smikes/bletch                           │                                  
│ 874996 │ npm             │ @planeshifter/tweet-sentiment            │ SVM Classifier to Detect Sentimen
│ 875207 │ npm             │ @jasonfill/lambda-cloud-watch-log-parser │ Parses event data from cloud watc
│ 875344 │ npm             │ @stevegill/test-module                   │ testing out scoped modules       
│ 875568 │ npm             │ @netapps/netapps-session                 │ netapps-api session store for Exp
└────────┴─────────────────┴──────────────────────────────────────────┴──────────────────────────────────
(10 rows)

```

**Comment by whit537** [comment]
In that case we should add redirect from trailing slash to non-trailing slash just for `on/npm/$package.spt`. We'll never want a trailing slash as part of a name, but we don't want to 404 if we get one.

**Comment by whit537** [comment]
Moving to a PR in #4565 ...

**Comment by whit537** [comment]
Reopening for clean-up. When packages are claimed they get a name, and the name is wrong on some already claimed:

```
gratipay::DATABASE=> select name, slug, slug_lower from teams where slug like '@%';
┌─────────────────────────────┬─────────────────────────────┬─────────────────────────────┐
│            name             │            slug             │         slug_lower          │
├─────────────────────────────┼─────────────────────────────┼─────────────────────────────┤
│ @sky-uk/eslint-config-sky   │ @sky-uk/eslint-config-sky   │ @sky-uk/eslint-config-sky   │
│ @ciffi-js/cookies           │ @ciffi-js/cookies           │ @ciffi-js/cookies           │
│ @ciffi-js/custom-select     │ @ciffi-js/custom-select     │ @ciffi-js/custom-select     │
│ @ciffi-js/device            │ @ciffi-js/device            │ @ciffi-js/device            │
│ @ciffi-js/responsive-images │ @ciffi-js/responsive-images │ @ciffi-js/responsive-images │
│ @ciffi-js/router            │ @ciffi-js/router            │ @ciffi-js/router            │
│ @ciffi-js/utils             │ @ciffi-js/utils             │ @ciffi-js/utils             │
└─────────────────────────────┴─────────────────────────────┴─────────────────────────────┘
(7 rows)

gratipay::DATABASE=>
```

**Comment by whit537** [comment]
`slug_lower` has a unique constraint on it.

```sql
BEGIN;
    UPDATE teams SET slug='eslint-config-sky', slug_lower='eslint-config-sky', name='eslint-config-sky'
     WHERE id=910;
    UPDATE teams SET slug='cookies', slug_lower='cookies', name='cookies'
     WHERE id=808;
    UPDATE teams SET slug='custom-select', slug_lower='custom-select', name='custom-select'
     WHERE id=809;
    UPDATE teams SET slug='device', slug_lower='device', name='device'
     WHERE id=810;
    UPDATE teams SET slug='responsive-images', slug_lower='responsive-images', name='responsive-images'
     WHERE id=811;
    UPDATE teams SET slug='router', slug_lower='router', name='router'
     WHERE id=812;
    UPDATE teams SET slug='utils', slug_lower='utils', name='utils'
     WHERE id=814;
END;
```

**Comment by whit537** [comment]
```
gratipay::DATABASE=> \i rename.sql 
BEGIN
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
COMMIT
gratipay::DATABASE=>
```

**Comment by whit537** [comment]
https://gratipay.com/eslint-config-sky
https://gratipay.com/cookies
https://gratipay.com/custom-select
https://gratipay.com/device
https://gratipay.com/responsive-images
https://gratipay.com/router
https://gratipay.com/utils

**Comment by whit537** [comment]
Actually, let's manually namespace ciffi ahead of #4246. `utils` is just too general to leave in the top-level namespace.

```sql
BEGIN;
    UPDATE teams SET slug='ciffi-cookies'
                   , slug_lower='ciffi-cookies'
                   , name='ciffi-cookies'
     WHERE id=808;
    UPDATE teams SET slug='ciffi-custom-select'
                   , slug_lower='ciffi-custom-select'
                   , name='ciffi-custom-select'
     WHERE id=809;
    UPDATE teams SET slug='ciffi-device'
                   , slug_lower='ciffi-device'
                   , name='ciffi-device'
     WHERE id=810;
    UPDATE teams SET slug='ciffi-responsive-images'
                   , slug_lower='ciffi-responsive-images'
                   , name='ciffi-responsive-images'
     WHERE id=811;
    UPDATE teams SET slug='ciffi-router'
                   , slug_lower='ciffi-router'
                   , name='ciffi-router'
     WHERE id=812;
    UPDATE teams SET slug='ciffi-utils'
                   , slug_lower='ciffi-utils'
                   , name='ciffi-utils'
     WHERE id=814;
END;
```

```
gratipay::DATABASE=> \i rename.sql
BEGIN
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
UPDATE 1
COMMIT
gratipay::DATABASE=>
```

https://gratipay.com/ciffi-cookies
https://gratipay.com/ciffi-custom-select
https://gratipay.com/ciffi-device
https://gratipay.com/ciffi-responsive-images
https://gratipay.com/ciffi-router
https://gratipay.com/ciffi-utils
