### ISSUE TITLE
Investigate dead emails in email_queue

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#4497]
```
gratipay::DATABASE=> select username, dead from email_queue JOIN participants ON participants.id = email_queue.participant ;
 username | dead
----------+------
 v1       | t
 v1       | t
 v1       | t
(3 rows)
```

**Comment by rohitpaulk** [comment]
All 3 are verification emails.

**Comment by rohitpaulk** [comment]
We need a creation timestamp on this table... Would make it easier for us to decide whether to purge or revive emails.

**Comment by rohitpaulk** [comment]
Also, we should add the dead emails count + queue count to our health dashboard

**Comment by rohitpaulk** [comment]
I don't see any relevant errors in sentry..

**Comment by rohitpaulk** [comment]
Does our sentry wiring ensure that exceptions from all threads are reported?

**Comment by whit537** [comment]
@rohitpaulk Those are leftovers from when we first created the queue. Iirc they are from a security researcher who used a malformed address. I believe we can safely delete them.

**Comment by whit537** [comment]
> Does our sentry wiring ensure that exceptions from all threads are reported?

I believe that is the intention, yes.

**Comment by rohitpaulk** [comment]
Creation timestamp and librato stats PRs are ready

**Comment by rohitpaulk** [comment]
Whoops, we're now at 10 dead emails!

**Comment by rohitpaulk** [comment]
I deleted the first 3. Now looking at Sentry for errors related to the others...

**Comment by rohitpaulk** [comment]
https://sentry.io/gratipay/gratipay-com/issues/259220081/events/ accounts for 4 of the 7 remaining  errors. 

The error says: `An error occurred (InvalidParameterValue) when calling the SendEmail operation: Local address contains control or whitespace`

**Comment by rohitpaulk** [comment]
https://sentry.io/gratipay/gratipay-com/issues/293013675/events/ accounts for the other 3. 

The error says: `EOFErrorpickle in load_eof`

```
EOFError: null
  File "gratipay/cron.py", line 26, in f
    func()
  File "gratipay/email.py", line 106, in flush
    r = self._flush_one(rec)
  File "gratipay/email.py", line 124, in _flush_one
    message = self._prepare_email_message_for_ses(rec)
  File "gratipay/email.py", line 147, in _prepare_email_message_for_ses
    context = pickle.loads(rec.context)
  File "python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "python2.7/pickle.py", line 886, in load_eof
    raise EOFError
```
