### ISSUE TITLE
Credit card expiration hard to overtype

### ISSUE THREAD

**Issue by cben** [gratipay/gratipay.com#4524]
Minor annoyance (#4233 would probably solve this and the more important #4041):

Chromium 52, Chrome 59, Firefox 53 on fedora 25.
https://gratipay.com/~USERNAME/routes/credit-card
I came to update an expired credit card.
Tabbing into the Expiration day/month fields, it looks like the content of the field is selected so just typing should overwrite it, but typing doesn't do anything.
Ctrl+A to select all still doesn't allow typing.  Have to use backspace before you can type.

**Comment by whit537** [comment]
Gosh, that's annoying. Sorry and thanks for reporting!
