### ISSUE TITLE
Switch to Sentry for CSP reporting

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4526]
Sentry has CSP reporting in beta:

https://sentry.io/gratipay/gratipay-com/settings/csp/

![screen shot 2017-06-19 at 4 50 53 am](https://user-images.githubusercontent.com/134455/27283818-e93bc0fa-54aa-11e7-913d-3c54a69538df.png)
![screen shot 2017-06-19 at 4 52 11 am](https://user-images.githubusercontent.com/134455/27283847-1d554f1e-54ab-11e7-91d9-2e239e81a9bf.png)

**Comment by whit537** [comment]
Reopening to track deployment ...

**Comment by whit537** [comment]
Header is deployed. Let's see if we can trigger a report ...

**Comment by whit537** [comment]
Actually, I give up. 😊

**Comment by David263** [comment]
Wow. Too bad; it actually works, more or less, in December.
