### ISSUE TITLE
Bulk-approve projects

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#4527]
This may become a problem with npm integrated. For example, https://github.com/gratipay/project-review/issues/465 is a ticket with 183 projects to approve.

**Comment by whit537** [comment]
Oh golly ... the other side! 😱

**Comment by whit537** [comment]
Also with this, we should only send a single notification email, per https://github.com/gratipay/project-review/issues/465#issuecomment-309935108.

**Comment by whit537** [comment]
The workaround for now is `update teams set is_approved=true where owner='foo';`. Bypassing Python means we don't send emails (which is okay because otherwise we send too many emails, one per project!), and we also lose an `add_event` call.
