### ISSUE TITLE
Replace temporary 'email2' param with 'email' when verifying emails

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#4541]
In https://github.com/gratipay/gratipay.com/pull/3965, we changed the value of the `email` parameter to be query-string encoded instead of raw text. To make this backward compatible, we changed the parameter name from `email` to `email2` and retained support for both. 

This was a **long** time ago, time to clean up. 

**Current**: We support `email2` (if the value is encoded) and `email` (if it isn't encoded. 
**End Goal**: Support only `email`, with encoded value

To achieve this without breaking existing links, we'll need an intermediary step. 

- Add support for `email`, with encoded value + send `email` in the links instead of `email2`. Don't drop support for `email2` as of yet. 
- Once the above is done, wait for the duration that verification links live - and then drop support for `email2`. 

Here's the related code: https://github.com/gratipay/gratipay.com/blob/master/www/~/%25username/emails/verify.html.spt#L14

**Comment by isaeef** [comment]
@rohitpaulk  I am up for it and submit the patch in a week. This is my first PR.
