### ISSUE TITLE
Switch from SentEmailHarness to QueuedEmailHarness in notify_participant tests

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#4544]
We have two test helpers for testing emails - [`SentEmailHarness`](https://github.com/gratipay/gratipay.com/blob/231af7959bdd85c33b0cb15a91170e9523f5f620/gratipay/testing/email.py#L51) and [`QueuedEmailHarness`](https://github.com/gratipay/gratipay.com/blob/231af7959bdd85c33b0cb15a91170e9523f5f620/gratipay/testing/email.py#L39). The former mocks the actual mailer call, whereas the latter picks values from the database queue (bypassing the mailer call). 

We don't use the `SentEmailHarness` almost everywhere in our test suite, except for 

1. [FlushEmailQueue](https://github.com/gratipay/gratipay.com/blob/231af7959bdd85c33b0cb15a91170e9523f5f620/tests/py/test_email.py#L398), which is valid - since we're testing the queue itself.
2. [TestNotifyParticipants](https://github.com/gratipay/gratipay.com/blob/231af7959bdd85c33b0cb15a91170e9523f5f620/tests/py/test_billing_payday.py#L619) - we shouldn't have to do this, `QueuedEmailHarness` should work just fine since `notify_participants` writes to the email queue

**Comment by redixhumayun** [comment]
Hey, I am looking to contribute to my first open source project, and I was wondering if you'd be open to me making a fix to this issue.

**Comment by rohitpaulk** [comment]
@redixhumayun: absolutely :) Let us know if you need help.

**Comment by whit537** [comment]
@redixhumayun And be sure to check out #4555 from @misara for their previous attempt. Maybe you can work out a solution together?

**Comment by redixhumayun** [comment]
@whit537 I'll make sure to do that :)

**Comment by redixhumayun** [comment]
Hey, so I have a pretty noob question here. I have been trying to get this running locally on my Mac and I am running into some issues. When I run the 
`scripts/bootstrap-debian.sh` command, I get the following error after entering my password 
`sudo: apt-get: command not found`. My question is should I install all the required dependencies myself using homebrew? I already have postgresql up and running, but probably the others? 

Also, I tried running the `make -j$(nproc) schema fake` command but that eventually errors out with the following errors

`make: env/bin/honcho: No such file or directory
make: *** [fake] Error 1` 

`fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    error: command 'cc' failed with exit status 1`

Not sure how to proceed

**Comment by clone1018** [comment]
Yeah, you don't want to run bootstrap-debian.sh, that's only for Linux Debian based distros. 

You want to make sure you have the postgres depdenencies and Python 2.7. After you do that you'll want to create the DB like instructed here: https://github.com/gratipay/gratipay.com#table-of-contents

and then `make env` and let us know the output of that command.

**Comment by mattbk** [comment]
Do you use homebrew? I think that's how I installed postgresql.

**Comment by redixhumayun** [comment]
Alright, so I set up the required dbs using psql. Now, when I run the `make test` command, it looks like the tables are created but it eventually errors out with the following 

`
env/bin/honcho run -e defaults.env,tests/test.env,tests/local.env env/bin/py.test -vv --cov gratipay ./tests/
/bin/sh: env/bin/py.test: No such file or directory
make: *** [test] Error 127
`
And on running the `make run` command, I get the following error message. 

`
from cryptography.fernet import Fernet, MultiFernet
ImportError: No module named cryptography.fernet
[2017-08-11 23:44:08 +0530] [30588] [INFO] Worker exiting (pid: 30588)
[2017-08-11 23:44:08 +0530] [30585] [INFO] Shutting down: Master
[2017-08-11 23:44:08 +0530] [30585] [INFO] Reason: Worker failed to boot.
make: *** [run] Error 3
`
Do I need to manually install the `crytography.fernet` module using pip? Why is it not installed as part of the `requirements.txt` file?

**Comment by mattbk** [comment]
Did you `make env`?

**Comment by whit537** [comment]
> Did you `make env`?

You shouldn't need to as `make test` includes `env` in its dependency chain, but if `py.test` and `cryptography` aren't installed then a `make clean env` could be what you need to get back on track.

**Comment by redixhumayun** [comment]
Running `make clean env` gives me an error with the cryptography module

`Running setup.py install for cryptography ... error` 

This then prints out a whole stack trace of errors, resulting in

`fatal error: too many errors emitted, stopping now [-ferror-limit=]
    20 errors generated.
    error: command 'cc' failed with exit status 1`

Right now, it just seems to be the cryptography module and this is one of the errors from the trace

`build/temp.macosx-10.10-intel-2.7/_openssl.c:578:30: error: expected function body after function declarator
    typedef LHASH_OF(CONF_VALUE) Cryptography_LHASH_OF_CONF_VALUE;`

**Comment by mattbk** [comment]
From a few Googles, I'm wondering what version of pip you're running.

**Comment by redixhumayun** [comment]
Hey, sorry it took me so long to fix this. I was just having massive troubles with getting the project up and running. 

https://github.com/gratipay/gratipay.com/pull/4576

The fix should work. Thanks again for letting me contribute.

**Comment by rohitpaulk** [comment]
:+1: Thanks @redixhumayun. 

The fix looks good, a couple of linter errors left and we're good to go.

**Comment by whit537** [comment]
Awesome work, @redixhumayun! If there's one thing we could change about our install docs or onboarding process, what would it be?

**Comment by redixhumayun** [comment]
@whit537 The biggest issue I had with was resolving dependencies.

Specifically, getting the cryptography module to work. The link @mattbk shared helped solve the issue. I had another issue with the mock module ([link to SO question](https://stackoverflow.com/questions/31417964/importerror-cannot-import-name-wraps)), where the mock module had a dependency on another module, which had versioning issues. 

I'm guessing this is bound to happen with such a massive project, but maybe documenting common errors and fixes with module dependencies would help?

**Comment by mattbk** [comment]
> documenting common errors and fixes with module dependencies would help?

You're part of the solution! Now this problem is searchable in our issue queue.

**Comment by whit537** [comment]
Re: cryptography ... was it C dependencies or Python dependencies that gave the problem? I'd expect C, and therefore a bit out of our scope. :-/

For mock I'd expect Python deps were the problem. If that sounds plausible to you then we should review network-less installation to see if we have a leak in `vendor/` ...  our aim is to bundle all Python deps at fixed versions in `vendor/` precisely to avoid dependency h*ck.
