### ISSUE TITLE
Send email messages immediately

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#4545]
The current email_queue implementation we have polls every 60 seconds for pending emails. This works fine for cases where delivery time isn't noticeable/important (payday emails, for example). 

In scenarios where users expect an email immediately (verification link when adding an email, [email sign-in links](https://github.com/gratipay/gratipay.com/pull/4543)), a delay anywhere between 0-60 secs will be observed. We can make this better by adding event-based notifications in addition to the current polling mechanism. i.e. every time we insert an email into the database, we fire an event. The email_queue listens for that event and processes accordingly. [Postgres supports `LISTEN`/`NOTIFY`](https://www.postgresql.org/docs/9.0/static/sql-notify.html).

**Comment by rohitpaulk** [comment]
Note: this will require some thinking about throttling. Currently, we throttle based on how many emails are in the queue already. If queue processing becomes almost instantaneous, then throttling will become ineffective.

**Comment by whit537** [comment]
@Changaco had input on this when we implemented throttling. He implemented an alternative on Liberapay, I don't remember the details off hand but we could dig that up.

**Comment by Changaco** [comment]
Actually I still haven't implemented a throttling mechanism in Liberapay: <https://github.com/liberapay/liberapay.com/issues/61>.
