### ISSUE TITLE
Add support for queuing emails without a participant linked

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#4547]
This is a requirement for [sign-up via email](https://github.com/gratipay/gratipay.com/issues/1052). 

Our `email_queue` currently only supports queuing emails linked to a participant. Extend this to support queuing emails with only an email address.

If a linked participant is present, stick to throttling based on `participant_id`. If only email_address is provided, throttle based on `email_address`.

**Comment by whit537** [comment]
How about a stub participant like we do for accounts elsewhere?

**Comment by rohitpaulk** [comment]
Hmm, that _could_ work. I'm on the edge here though, there are pros and cons to this approach. 

**Upside**

Schema + code is simplified in some places - we don't end up implementing the stuff that is common, can reuse some features.

**Downside**

We'll need special handling in a lot of places to differentiate claimed participants from unclaimed participants. It seems easier for bugs to creep in when we're not explicitly stating that the participant could be half-baked. For example, the changes we'll need to make if we go with this approach: 
  - `email_queue` will now have the handle the case of an `unclaimed` participant differently. We should be careful to not link the random username anywhere
  - We'll need to create a random participant the first time, and then pick the same participant every time after so that throttling based on `participant` works as intended. 

I see how this approach made perfect sense under Gittip/Gratipay 1 - A lot of the core features related to users who hadn't signed up yet (pledging etc). I'm not sure if we should continue with that pattern for auth, I do see benefits in being explicit about the inexistence of an actual user record to deal with. 

This posts explains my thoughts better: http://rdingwall.com/2009/11/20/the-trouble-with-soft-delete/ ('soft create' is what we're dealing with)

**Comment by rohitpaulk** [comment]
@whit537 (pinging so that this appears in your notifications) thoughts?

**Comment by whit537** [comment]
From http://rdingwall.com/2009/11/20/the-trouble-with-soft-delete/:

> Primary transactional tables should only contain data that is valid and active right now.

I think stub participants are valid and active. We are actively initiating package claims for them, no? And over on https://github.com/gratipay/gratipay.com/pull/4598 we want to start placing credit card holds for them as well.

**Comment by whit537** [comment]
We want to send them email: https://github.com/gratipay/gratipay.com/pull/4548. That seems active.

**Comment by whit537** [comment]
Honestly I'm still drawn to the idea of using `elsewhere` for email:

https://github.com/gratipay/gratipay.com/blob/139dca62aa80b504dc75fb3895ce0c31b6df0545/sql/schema.sql#L311-L325

**Comment by whit537** [comment]
Because then we get stub participants for free:

https://github.com/gratipay/gratipay.com/blob/139dca62aa80b504dc75fb3895ce0c31b6df0545/gratipay/models/participant/__init__.py#L268-L281
