### ISSUE TITLE
Login modal still mentions that one can create an account on Gratipay

### ISSUE THREAD

**Issue by tuxayo** [gratipay/gratipay.com#4554]
It seems that when can't create anymore an account on Gratipay because only third-party provider are available but the modal says:

> Use a third-party provider to sign in or create an account on Gratipay

**Comment by mattbk** [comment]
You can create an account by using one of the third-party providers. If you don't already have an account and click "GitHub" you will be into the account-creation workflow, for example.

We're working on an email-based solution at https://github.com/gratipay/gratipay.com/pull/4539.

**Comment by mattbk** [comment]
@tuxayo, does that make sense?

**Comment by tuxayo** [comment]
Well the current version is confusing. But as I'm not a native speaker, that might be a reason.

About the upcoming email-based solution, yes it makes sense. It's great to see the same strategy as https://passwordless.net/ being used. (that's what it is right?)

**Comment by mattbk** [comment]
Yes, same idea. Thanks for the feedback!

**Comment by mattbk** [comment]
Calling this completed.
