### ISSUE TITLE
Expose APIs to support an `npm-tip` cli tool

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4556]
Per Twitter [convo](https://twitter.com/guybedford/status/890500229065297924) w/ @morsdyce @guybedford:

> [guybedford] But surely someone can make something around npm that distributes a monthly budget amongst the packages you most rely on.
> [morsdyce] That's what @/Gratipay does afaik
> [Gratipay] Yes! Check out https://gratipay.com/on/npm/  and let us know what you think.
> [guybedford] Amazing, I wonder if this could be packaged up into an `npm-tip` CLI tool...
> [guybedford] `npmx gratipay-tip` to run a CLI wizard to support your dependencies, with Zeit-style payment process.

**Comment by whit537** [comment]
What is a "Zeit-style payment process"?

**Comment by whit537** [comment]
Presumably https://zeit.co/blog/now-billing?

> Today we are introducing two new commands to our [now](https://zeit.co/now) CLI toolchain:
> - `now billing` (or `now cc`) to manage your credit cards
> - `now upgrade` (or `now downgrade`) to pick your plan

**Comment by whit537** [comment]
Probably time for us to dust off https://github.com/gratipay/gratipay.com/#api, see what still is true there and what is missing that would be needed to support this use case.

**Comment by guybedford** [comment]
Thanks for being receptive here! It's possible to imagine all sorts of nice things, like seeing the funding status of your dependencies with ticks or crosses for their targets, and then to give according to who needs most etc etc. Auto-suggesting a list of payments, with the ability to then edit that manually.

Users who make monthly donations with the tool could get a special label applied to their issues when they post issues on GitHub (if the project opts into this). The more perks to the user for being part of it the better.

Could be some really interesting possibilities, but it's super open ended though this stuff, and would be quite an effort! I feel bad throwing out ideas with no ability to follow through :)

**Comment by whit537** [comment]
No worries, happy to keep this open in case anybody picks up on the idea. I think we'll have to see someone from the community step forward to make this happen ... I know personally I've got my hands full already. ☺️ But if someone wants to hack on this and needs API updates or whatever, happy to help from that angle! 🚀  ✨
