### ISSUE TITLE
Set httpOnly cookies.

### ISSUE THREAD

**Issue by EdOverflow** [gratipay/gratipay.com#4561]
Using the HttpOnly flag when generating a cookie helps mitigate the risk of client side script accessing the protected cookie (if the browser supports it). [[1]](https://www.owasp.org/index.php/HttpOnly#What_is_HttpOnly.3F)

**Comment by rozuur** [comment]
Can I work on this for hacktoberfest?

**Comment by EdOverflow** [comment]
@rozuur: Of course you can!
