### ISSUE TITLE
Email notify on receiving payments to project

### ISSUE THREAD

**Issue by mrfearless** [gratipay/gratipay.com#4564]
Just an idea, didnt find any other issue that mentions this.

Could be handy to have an email sent to account owner when another user supports/backs one of their projects. Also maybe include a summary of total no of users supporting the project with received information, like estimated payment totals as well prehaps.

Thanks.

**Comment by rohitpaulk** [comment]
I think this is useful for the first tip, and then maybe the 10th, 100th etc. The email could also include an explanation saying that tips are anonymous, so we can't reveal who the giver is. 

Notifying on every single new tip... borderline spam IMO.

**Comment by whit537** [comment]
Could also send weekly summaries: https://github.com/gratipay/gratipay.com/issues/1022. Should we fold this into that?

**Comment by mattbk** [comment]
Seeing the +1 from the OP on folding into #1022, reticketing this there.
