### ISSUE TITLE
Make Invoice a PDF

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#4622]
Per @jdorfman in rl convo. Easier to send to accounting as PDF than HTML that I have to ... what? Print?

http://weasyprint.org/ is nice but deps are heavy. Another service like https://gip.rocks/?

**Comment by rohitpaulk** [comment]
http://prawnpdf.org/manual.pdf - Ruby, but looks solid.

**Comment by whit537** [comment]
I used https://invoice-generator.com/ when I was putting the HTML invoice together. I didn't realize it's open source! 😆  Seems like a good fit to me.

**Comment by rohitpaulk** [comment]
It's not open source, that repo only has a readme : 👅

**Comment by whit537** [comment]
Heh. Oops! :P
