### ISSUE TITLE
Image is outdated - when will it update?

### ISSUE THREAD

**Issue by ferventcoder** [gratipay/gratipay.com#4625]
What is shown on project:
![image](https://user-images.githubusercontent.com/63502/30326059-d29aa4b8-978c-11e7-93b5-99f6a29f5919.png)

Expected:
![image](https://user-images.githubusercontent.com/63502/30326009-a61e7220-978c-11e7-80c2-d10e8c1cbd30.png)

The expected view is what I see when I log into the account, how do we get the other one to reflect that updated image as well?

**Comment by ferventcoder** [comment]
Nevermind - determined how to get into the "project" and fix this myself.

**Comment by whit537** [comment]
Sorry for the roadbump, glad you got it sorted! :-)
