### ISSUE TITLE
Promote use of Shields in application tickets

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#4634]
Inspired by https://github.com/gratipay/project-review/issues/579, we could drop the code in when the ticket is automatically created:

> [![Gratipay](https://img.shields.io/gratipay/project/tarsana.svg)](https://gratipay.com/Tarsana/)

> Add to your repo when approved:
```[![Gratipay](https://img.shields.io/gratipay/project/tarsana.svg)](https://gratipay.com/Tarsana/)```

Place a shield next to each project URL, or just use the first (or only) one as an example with the code?

**Comment by mattbk** [comment]
Or we could add it back to the profile where widgets used to be. Or both.

**Comment by whit537** [comment]
I like it!

**Comment by mattbk** [comment]
https://github.com/gratipay/gratipay.com/blob/1985e43033edd87bd16cdb46c16adbcda0bb6bc4/gratipay/project_review_process.py#L54
