### ISSUE TITLE
Add notification for missing credit card

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#4644]
On [FD](https://gratipay.freshdesk.com/helpdesk/tickets/9803), someone wasn't paying in every 10 weeks on a $1/week donation. Turns out they didn't have a credit card set up.

- There should be a notification on the site for this (credit cards are required for giving and you don't have one) if they are giving.
- It should remind you that your giving won't happen during the remove card process
- Do we send an email out if you are due for payin but there is no credit card? I know we do for expired cards or failed charges, but what about for missing?

These are all the banner notifications, yes? https://github.com/gratipay/gratipay.com/blob/4b5b0b3e287424a3e5b4179d49eddac44064f7e4/gratipay/utils/notifications.py

(Most of these I can dig up, just writing the questions down to come back to.)

todo
- [ ] don't let people give without a credit card, or
- [ ] notify them that giving won't work, after they give without a credit card
- [ ] email people if they _don't_ have a credit card and payment is due (currently we only email for failed charges)
- [ ] notify people when they remove a credit card that giving will no longer work

**Comment by mattbk** [comment]
We require a credit card to set up a gift initially, right?

**Comment by mattbk** [comment]
No! There's just a gentle reminder. We should make this a hard rule, because otherwise what's the point?

![image](https://user-images.githubusercontent.com/3729038/30819988-3ec53a0a-a1e6-11e7-9870-11e961799ae1.png)

I'd also go so far (once this is fixed) as to email everyone who is giving but doesn't have a card set up to tell them that they aren't actually giving and need to set a card up.

**Comment by mattbk** [comment]
@whit537 can you query how many `is_funded = FALSE` ~users there are? What's the scale of this problem?

**Comment by mattbk** [comment]
I think it would be something like 
```
    SELECT username
         , balance
         , (SELECT SUM(amount) FROM payment_instructions WHERE participant_id = p.id) AS giving
         , (SELECT COUNT(*) FROM payment_instructions WHERE participant_id = p.id AND amount > 0) AS ngiving_to
      FROM participants p
     WHERE is_suspicious IS NULL
       AND (                                  -- They do not have a credit card set up
             SELECT COUNT(*)
               FROM exchange_routes r
              WHERE r.participant = p.id
              AND r.network = 'balanced-cc'
           ) = 0
       AND giving > 0
       AND NOT is_closed
  ORDER BY claimed_time
```
Modified from https://github.com/gratipay/gratipay.com/blob/992bf1bf03d256931f97a31dad8de6e254e43a29/www/dashboard/index.spt#L10.

**Comment by whit537** [comment]
```
(188 rows)
```

**Comment by mattbk** [comment]
Was my query right?

**Comment by whit537** [comment]
I didn't dig that deep, I just ran it. 🐭

**Comment by mattbk** [comment]
Are you feeling okay? Is now the time for me to submit PRs without tests? ;-)

**Comment by whit537** [comment]
I mean, I skimmed it for `UPDATE` `DELETE` and `INSERT`. :P
