### ISSUE TITLE
Unclaimed packages overwhelm search results 

### ISSUE THREAD

**Issue by mattbk** [gratipay/gratipay.com#4646]
Should manage this somehow to allow both claimed and unclaimed to be searched. Part of #3938?

**Comment by whit537** [comment]
It'd be different if you could actually pledge to unclaimed packages.

**Comment by mattbk** [comment]
Why would it be different?

I'f I'm looking for project "foo" and there are 15 npm packages that are variations of "foo," the one I'm looking for may not even show up in the search results because we only show the top 10 matches.

**Comment by whit537** [comment]
Could be improved with a) paging and b) weighting based on popularity or somesuch?

Pledging would be different because then you could *do* something with those unclaimed packages. Right now they are inert.
