### ISSUE TITLE
Campaign banner broken on Firefox

### ISSUE THREAD

**Issue by rohitpaulk** [gratipay/gratipay.com#4652]
**URL:** https://gratipay.com/?i_am_fancy=yes

**Firefox:**

![screen shot 2017-09-28 at 6 13 32 am](https://user-images.githubusercontent.com/3893573/30944268-449b29a0-a414-11e7-8100-aaa82f117d55.png)

**Chrome:** 

![screen shot 2017-09-28 at 6 13 41 am](https://user-images.githubusercontent.com/3893573/30944269-44f4b36c-a414-11e7-9f7b-f4d4c75467f8.png)

**Comment by whit537** [comment]
Gah! That's right. I poked at this a bit earlier under #4598, need to squish it.

Good catch. :)

**Comment by AlanLZY** [comment]
Hi!, I am a first timer trying out! Would be willing to tryout! Can I try?

**Comment by mattbk** [comment]
Go for it!

**Comment by whit537** [comment]
@AlanLZY Thanks for stepping forward! Feel free to join us in Slack if you would like to chat in real 
time while you get going on this:

http://inside.gratipay.com/appendices/chat

Also happy to discuss here. 💃

**Comment by pinoaffe** [comment]
Hi everybody, I made a fix for this issue at github.com/pinoaffe/gratipay.com

**Comment by 0xibram** [comment]
Fixed in #4664. !m @pinoaffe 😄
