### ISSUE TITLE
npm module says it's receiving money but has never had any come in

### ISSUE THREAD

**Issue by andrew** [gratipay/gratipay.com#4667]
<img width="601" alt="screen shot 2017-10-03 at 11 17 37 am" src="https://user-images.githubusercontent.com/1060/31120768-9a4eadbe-a82d-11e7-81df-8656baf8fe46.png">

My node module `readcontrol` has said that it's receiving $2.00 per week for the past couple months, but hasn't ever actually seen any money coming in, is there something broken or am I reading this wrong?

**Comment by mattbk** [comment]
Credit cards aren't charged (and you don't see funds) until a giver owes more than $10 on a given week. So if your $2 is from one person and this is the only project being given to by them, it would be five weeks until you received money, but you would get it as a $10 chunk (for example).

**Comment by rohitpaulk** [comment]
I think this is the case of a broken credit card. If it was the pooling upto $10 case, we'd see a non-zero value for 'Funded dues' in the screenshot.

Most likely a bug in the caching logic that determines whether a payment is 'funded' or not.

**Comment by mattbk** [comment]
Why is unfunded zero?

Questions like these are hard for me to answer without speculation because I can't just query the database and giving is anonymous even for admin users.

**Comment by mattbk** [comment]
Once https://github.com/gratipay/gratipay.com/pull/4669 is deployed I will take a look.

**Comment by mattbk** [comment]
Okay, we're deployed. 

There are two ~users giving to readcontrol, both of whom have been marked `suspicious` by admins because it looked like they were fraudulent. This means that their cards are not charged.

I have to dig a little deeper and maybe fix #4478 to see what the reasoning was.

Obviously, we should change these values to not include giving from `suspicious` accounts.

**Comment by rohitpaulk** [comment]
https://github.com/gratipay/gratipay.com/issues/4420
