### ISSUE TITLE
Look into Packagist Support

### ISSUE THREAD

**Issue by clone1018** [gratipay/gratipay.com#467]
Packagist is the RubyGems/PyPi of the PHP world, it's the repository for Composer, a PHP dependency manager. @tehgeekmeister is currently working on #223 which integrates Gittip with RubyGems, let's see if we can get the ball rolling with the guys over at Packagist.

You can find them on Gittip here:
https://www.gittip.com/naderman/
https://www.gittip.com/Seldaek/
##

**Comment by nobodxbodon** [comment]
Re-ticketed to https://github.com/gratipay/inside.gratipay.com/issues/982 for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.
