### ISSUE TITLE
Suggestion - Add a "language" filter and/or show language in the title on the browse page.

### ISSUE THREAD

**Issue by xurei** [gratipay/gratipay.com#4672]
I like to use the Browse page to discover new libraries and modules.

Something I miss is a quick way to know the main language of a project. 
I see two ways to have this : either add a "filter by language" feature, or show the main language in the project list item.
Or both, obviously.

What do you think ?

**Comment by mattbk** [comment]
Hi xurei, do you think we could roll this in with #3938?

**Comment by xurei** [comment]
Yes, that would fit in there :-)
