### ISSUE TITLE
Sign in button moves down on smaller screens

### ISSUE THREAD

**Issue by 0xibram** [gratipay/gratipay.com#4675]
![image-1](https://user-images.githubusercontent.com/9266001/31303195-8ed83dea-aad7-11e7-92a9-c055e074c416.jpg)

**Comment by 0xibram** [comment]
#4637

**Comment by PallaviDas07** [comment]
Is this issue solved? I am interested to work on this.

**Comment by EdOverflow** [comment]
Closing in favour of https://github.com/gratipay/gratipay.com/issues/4637.

@PallaviDas07: As far as I can tell, this issue has not been resolved. Feel free to submit a PR.

**Comment by 0xibram** [comment]
@EdOverflow this happens on really small screens (iphone 6s in this case) only. Are you sure it’s the same root cause as #4637?
