### ISSUE TITLE
Improve search box

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#469]
Suggested by Liz Pullen via [Twitter](https://twitter.com/nwjerseyliz/status/290248651035529216):

> Just looked into Gittip...at any point, will it be searchable? So, you'd search for people working on specific kinds of projects?

Adding this to The Nexus:

https://github.com/gittip/www.gittip.com/issues?milestone=25&state=open

**Comment by whit537** [comment]
+1 in [FD1528](https://gratipay.freshdesk.com/helpdesk/tickets/1528)

**Comment by Changaco** [comment]
The work on this is almost done, but we need to merge #2938 first.

**Comment by rohitpaulk** [comment]
!m @Changaco !
