### ISSUE TITLE
/on/dribbble/

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#504]
Suggested by @zethussuen via [Twitter](https://twitter.com/zethussuen/status/293450599373082627).
##

**Comment by nobodxbodon** [comment]
Re-ticketed to [integrate with software repositories / package manager](https://github.com/gratipay/inside.gratipay.com/issues/982) for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.
