### ISSUE TITLE
Show me my friends who have Gittip accounts

### ISSUE THREAD

**Issue by jameysharp** [gratipay/gratipay.com#536]
Once I've linked my Twitter account to gittip, I'd like an easy way to see which of my follows or followers there have also linked their Twitter accounts to Gittip. Same goes for GitHub follows/followers&mdash;as well as edges from other social networks as they become supported in Gittip, like Facebook friends or Google+ circles.

Principle: I'm more likely to want to contribute money to people who I have a social-network relationship with than to random Gittip users.

As it stands, I'm overwhelmed at the prospect of thinking of people I want to 'tip'. Seeding my thoughts with people I recognize should make getting started easier, psychologically.
##

**Comment by whit537** [comment]
Reopening because this didn't make it into #2809, which closed #2584, and this is sufficiently different from #3183, where we're talking about making suggestions based on as-yet-undetermined criteria. This ticket is about something more direct: allow me to see my friends.

**Comment by whit537** [comment]
The one I really want is Facebook but I don't see that we're going to be able to do it. They provide a [`user/friends`](https://developers.facebook.com/docs/graph-api/reference/v2.2/user/friends) API that gives a listing of friends currently using the service, but then we need people to invite all their friends on Gratipay before we can provide a useful friend finder. The provide an [`invitable_friends`](https://developers.facebook.com/docs/graph-api/reference/v2.2/user/invitable_friends) API but only for apps classified as a [game](https://developers.facebook.com/docs/games/appcenter/categories). Good luck with that for us, methinks.

I looked at hacking up a Facebook search. The [AJAX](https://www.facebook.com/typeahead/search/facebar/query/?value=[%22john%22]&grammar_version=94ad0a5516d7a8d7a8aefb2f83aaf2e8e424b256&__a=1) and [HTML](https://www.facebook.com/search/str/john/keywords_users) endpoints for search are both protected by the absence of an `Access-Control-Origin-Allow: *` and the presence of `X-Frame-Options: Deny`, so they're not usable from either via either AJAX or iframe. That means we'd have to perform a search server-side, where we can't login as the user. Facebook doesn't provide a proper search endpoint in their [graph API](https://developers.facebook.com/docs/graph-api/reference/).

I guess we have to content ourselves with `user/friends` and ask people to invite their friends. :-(

**Comment by whit537** [comment]
I'm looking at [Canvas](https://developers.facebook.com/docs/games/canvas) and [Page Tabs](https://developers.facebook.com/docs/appsonfacebook/pagetabs) as possibilities for implementing a Facebook integration.

**Comment by whit537** [comment]
Those don't help. They allow us to embed content within the Facebook as an iframe, but all of the same permission limitations apply.

**Comment by whit537** [comment]
Maybe Gratipay-Everywhere is the way to go for integrating with Facebook? How well will that work on mobile?

**Comment by whit537** [comment]
From the [survey](http://inside.gratipay.com/appendices/survey):

![screen shot 2015-02-17 at 10 24 28 pm](https://cloud.githubusercontent.com/assets/134455/6241938/d29337cc-b6f3-11e4-951a-0aa9ca04f211.png)

**Comment by mattbk** [comment]
+1 for original idea.

**Comment by whit537** [comment]
+1 at https://twitter.com/nplainsathletes/status/570978480222969859.

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
