### ISSUE TITLE
Email notify users when they are marked suspicious

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#557]
Send an email notification when possible to users when we mark them suspicious.

----------------

## Original

This might be controversial.

I want to have a page at `/about/fraud/untrusted/` which simply lists all participants with  `is_suspicious is true`. As our fraud system evolves (#556), so will this listing. The principle is that untrusted users are announced as such so that false positives have a chance to discover this and attempt to redeem themselves. We can't be like PayPal, an infuriatingly opaque black box if you're a false positive.
##

**Comment by mattbk** [comment]
> Perhaps, we also notify the user (if possible)

+1 to this. Recently interacted with a user at [FD](https://gratipay.freshdesk.com/helpdesk/tickets/5953) who couldn't log in and wasn't notified why--nothing happened when the user tried to log in. Took me a while to think of checking `is_suspicious`. Showing a message would help.

**Comment by mattbk** [comment]
> Perhaps, we also notify the user (if possible) and put a note on their
profile?

If you view the profile when not logged in, it has a pink overlay at the top and the word "Suspicious" below the avatar. That doesn't tell people what to do, however. And since they can't log in, showing them a notification doesn't help.

**Comment by whit537** [comment]
> Recently interacted with a user at FD who couldn't log in and wasn't notified why--nothing happened when the user tried to log in.

For the record, the user [turned out](https://github.com/gratipay/inside.gratipay.com/issues/890#issuecomment-261123662) to be a true positive. ;-)

**Comment by whit537** [comment]
> Perhaps, we also notify the user (if possible) and put a note on their profile?

As discussed at https://github.com/gratipay/gratipay.com/pull/4188#issuecomment-262073906, I like this solution better than the listing of suspicious accounts, because a) it's much less work for those affected to discover that they're affected, and b) it's more respectful of user privacy. A public listing would only seem to make sense if we're trying to warn others about these users or something like that, but that doesn't seem necessary since suspicious users can't do anything on the site (so there's nothing to watch out for).

**Comment by mattbk** [comment]
I'm fine with that, but I think there should be a message (not just a note on the profile) when someone tries to log in and are denied because they're suspicious. My first inkling in such a case would be that the login form is broken, not that I should go look at my own profile page to see what's up.

**Comment by whit537** [comment]
>I'm fine with that, but I think there should be a message (not just a note on the profile) when someone tries to log in and are denied because they're suspicious.

Okay. I've rescoped this to be about email notification, and reticketed the login prompt as #4199.

**Comment by mattbk** [comment]
Is there an example I can look at for how to send an email?

I see that the templates are in https://github.com/gratipay/gratipay.com/tree/4b5b0b3e287424a3e5b4179d49eddac44064f7e4/emails.

**Comment by whit537** [comment]
Search for `app.email_queue.put`.
