### ISSUE TITLE
pay in with PayPal

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#63]
_was: pay in <b>and out</b> with paypal_

Since we now do PayPal payouts (though it's a second-class option), let's refocus this ticket on PayPal for payins. Currently closed but we do get requests for this so it's worth tracking somewhere. Who knows?

I usually link to https://github.com/gittip/www.gittip.com/issues/63#issuecomment-14676114 to explain why this is closed.
##

**Comment by whit537** [comment]
+1 https://gratipay.freshdesk.com/helpdesk/tickets/1929

**Comment by whit537** [comment]
Reopening in light of Balanced shutdown, and our consequent reliance on PayPal for payouts (#3567).

**Comment by whit537** [comment]
+1 https://github.com/gratipay/gratipay.com/issues/3574

**Comment by EmilyBjoerk** [comment]
+1 Many would-be supporters turn around when they realize they have to register to "the site of the week" and provide their CC number. Otherwise I would be all over this.

**Comment by mattbk** [comment]
+1s from comments at http://www.somersf1.co.uk/p/width640-height360-srcwww.html:

> Can I contribute through PayPal? It is preferable to continued debit of my account.

> I agree with Mack there, a paypal donate button would be preferable! (Although I will continue to support you through Gratipay)

**Comment by mattbk** [comment]
+1 from https://twitter.com/yusijs/status/779009959820455936.

**Comment by whit537** [comment]
+1 from Earl at the coffee shop! ☕️
+1 from my dad at some point!

**Comment by nobodxbodon** [comment]
Re-ticketed to https://github.com/gratipay/inside.gratipay.com/issues/974 for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.

**Comment by mattbk** [comment]
+1 from [FD 9412](https://gratipay.freshdesk.com/helpdesk/tickets/9412):
> why don't you take payments by PayPal? Bottom line is this for me, I won't use it unless I can pay with PayPal, as I don't use a credit card on-line. And no, explaining the ease, security and benefits of using a credit card won't change that ;-). And I wonder if I'm alone.

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
