### ISSUE TITLE
payin with dwolla

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#65]
"[Ultimately we're trying to build the next Visa, not the next PayPal.](http://articles.businessinsider.com/2011-11-11/tech/30381380_1_credit-card-interchange-fees-paypal)"

[Dwolla](https://dwolla.com/) is similar to [Stripe Platform](https://stripe.com/platform) (see #58) in that everyone would have to create an account on Dwolla and then money would go directly from person to person instead of through a central Gittip bank account. I like this a lot. I had to upload a photo of my drivers license in order to integrate with a bank account, and there appears to be a manual review process before my bank is linked, and it's unclear that my bank is even linkable (it says "We could not add your bank at this time. Please complete any additional verification requirements.").

Geez. I think this would even be free.

"[Cost to receive money in amounts greater than $10:  $0.25](http://help.dwolla.com/customer/portal/articles/86684-dwolla-fees)"

Is the Dwolla (photo ID!) hurdle higher than giving up credit card details?

I think we need to support multiple options, like Venmo does (see #38). If tipper and tippee have Dwolla then we use that, if not then do a credit card dance. Something like that.
##

**Comment by whit537** [comment]
Dwolla sales: https://gratipay.freshdesk.com/helpdesk/tickets/1947.

**Comment by avimar** [comment]
Dwolla cancelled their transaction fees, BTW.

**Comment by webmaven** [comment]
I figure, since I am stumping for Dwolla payouts for myself (in #726), I might as well give my own :+1: for Dwolla pay*ins*, as well.

**Comment by mattbk** [comment]
+1 from https://gratipay.freshdesk.com/helpdesk/tickets/4078.

**Comment by nobodxbodon** [comment]
Re-ticketed to https://github.com/gratipay/inside.gratipay.com/issues/974 for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.
