### ISSUE TITLE
break history page into multiple pages

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#662]
Each week should get its own page, with paging nav added in the box.

**Comment by Changaco** [comment]
+1 for yearly totals from https://gratipay.freshdesk.com/helpdesk/tickets/1749 with the additional requests of showing totals for each tippee and providing a CSV export

**Comment by whit537** [comment]
+1 https://twitter.com/mervinej/status/569942684233674753 with a workaround:

https://gist.github.com/jmervine/336c50ad5473c40f7751
