### ISSUE TITLE
find a payments partner

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#67]
~~Gittip~~ Gratipay is technically a "third-party payment aggregator," which means it is a third party collecting money on behalf of someone else. Credit card companies are [down on this](https://www.braintreepayments.com/blog/high-risk-mechant-account-third-party-payments-aggregation):

> There are a few reasons why TPPA's are considered higher risk in the credit card processing industry: 1) The merchant has reduced control over the quality and delivery of the product being sold, and 2) The merchant is being trusted to pay the third party for the money they've collected on their behalf. 3) The business that owns the merchant account is responsible for all transactions charged by that account even though a majority percentage is passed onto a third party

But of course TPPA's exist: PayPal, Etsy, Kickstarter, Flattr, etc. Somehow there has to be a way to "get it right." The above link concludes: "That is not to say that merchant accounts cannot get approved for TPP processing, it is just more difficult and the underwriting conditions will more likely include a reserve and other similar safeguards. " Do you have experience with this?

Here's [Stripe's position](https://stripe.com/help/faq#marketplaces):

> Stripe can only transfer to one bank account; we don't support transferring to many different users or splitting transaction proceeds among different people. Marketplaces on Stripe work in one of two ways:
> 
> One option is to have the marketplace's users (so the merchants on top of the marketplace) each set up their own Stripe account. This can be done entirely online. Then you, as the marketplace owner, will need to collect the users' API keys and make transactions on their behalf with their API keys. Stripe will then transfer directly to these users' bank accounts. If you want to collect a fee on the transactions, you can charge your users with your API key using Stripe.
> 
> The other way marketplaces use Stripe is by simply collecting all their users' payments. In this scenario, Stripe will transfer to the marketplace owner's bank account. You will then need to transfer to your users using programmatic ACH transfers (most business bank accounts allow you to set this up). The caveat in this scenario is that it needs to be very clear to any consumers that they are paying you, the marketplace, when making the transaction. Additionally, in this scenario, you will be liable for any chargebacks or disputes.

Option one is [Stripe Platform](https://stripe.com/platform), and it doesn't work for us because of the high per-transaction cost of moving 8 cents at a time over the credit card network (see [#58](https://github.com/whit537/www.gittip.com/issues/58#issuecomment-6366717)). Dwolla is basically Stripe Platform without the credit card network middleman, so adding Dwolla support (#65) would definitely mitigate the risk that we're kaiboshed by (Stripe because of) the credit card companies.

Option two sounds like what we're trying to do, so the low-hanging fruit here is to make it "very clear to any consumers that they are paying you, the marketplace, when making the transaction."

**Comment by whit537** [comment]
Reopening in view of [Balanced shutting down](http://blog.balancedpayments.com/shutting-down/). :-(

**Comment by whit537** [comment]
Talking with Stripe is #3245 

Talking with Braintree is #3287.

**Comment by whit537** [comment]
Another option is to partner directly with a bank. We don't get the nice APIs of Stripe or Braintree, but it may be the only way to find someone who will work with our use case. I've started building a relationship with Citizens here in town, and that's where I'd start: #3288.

**Comment by whit537** [comment]
Whichever route we go on this, I have to imagine that cleaning up our act is a prerequisite. Cleaning up our act means:

 - tightening up our identity requirements (#3289)
 - properly reimplementing Teams as Payroll (#2569)
 - cleaning up the site (About pages, and #3220) so it's more obvious what we're doing

**Comment by techtonik** [comment]
I really don't get how Gratipay is connected to banks. Is there a diagram of the structure somewhere?

I'd like to explore an integration with Dwolla.

**Comment by rohitpaulk** [comment]
@techtonik - Dwolla is ticketed as #65 and #726.

**Comment by whit537** [comment]
> I really don't get how Gratipay is connected to banks. Is there a diagram of the structure somewhere?

@techtonik We're connected to banks via an intermediate payments vendor. This has been Balanced, but Balanced is shutting down.

**Comment by whit537** [comment]
Blech. We can only have one milestone at a time. :-/

**Comment by whit537** [comment]
I mean, that makes sense, but it means that sprint milestones and non-sprint milestones conflict.

**Comment by whit537** [comment]
Milestone discussion carried forward in #163.

**Comment by whit537** [comment]
This is an existential risk for Gratipay. If we don't have a payment processor, then we're effed. We're flipped. My current sense is that Stripe seems likely to reject us, Braintree might accept us, and Citizens is a wildcard (we just don't have enough experience at that level of abstraction; we're used to dealing with start-up-y abstractors instead of banks; but #417 is discouraging here).

If we can't find a credit card/ACH credit  processor by June 11, then we have a couple options:

 - Lean more heavily on credit card alternatives such as Dwolla and cryptocoins.
 - Change our model to avoid micropayments (like, maybe we drop the individual tips use case in favor of a b2b large-transaction-size use case?)

**Comment by tshepang** [comment]
How about using Paypal until something more suitable "turns up"?

**Comment by techtonik** [comment]
Diversification is a good thing, and it is too bad that we didn't have this before, so I am for adding multiple inputs and outputs (writing issue already).

**Comment by Changaco** [comment]
> My current sense is that Stripe seems likely to reject us

In the short term I don't see a reason why we couldn't use their deprecated US-only API, it's only international payments that are problematic.

**Comment by whit537** [comment]
> In the short term I don't see a reason why we couldn't use their deprecated US-only API, it's only international payouts that are problematic.

If we migrate to Stripe's [deprecated API](https://stripe.com/docs/tutorials/sending-transfers), then we can be certain of facing this same existential crisis again in the future, either when they terminate the API in general, or when they ask us in particular to leave. They deprecated the API for a reason. I don't see that they state their reason, but it's not unlikely that it has to do with precisely the strictures we run afoul of with managed accounts. What's more, the short term could turn out to be *very* short, given that they've already asked us to leave once (see above, at https://github.com/gratipay/gratipay.com/issues/67#issuecomment-6553374). If this is truly our best option then we are in deep :hankey:.

**Comment by whit537** [comment]
> Diversification is a good thing

Agreed. I've reopened #210.

**Comment by whit537** [comment]
At this point I'm feeling pretty good about Spreedly (#210). The biggest drawback I see is that they're only payouts, not payins, so they're not a complete solution for us. But for payins they seem to be a good fit for us, since our relationship with gateways is so uncertain. :-(

**Comment by whit537** [comment]
Review site for merchant services providers:

http://www.merchantmaverick.com/review-category/merchant-accounts/

**Comment by whit537** [comment]
Alright, so ... Gratipay requires four things: identity verification, payins, escrow, payouts. Here's our current vendor landscape:

 1. **identity verification**&mdash;Balanced
 1. **payins**&mdash;Balanced (credit cards), Coinbase (bitcoin)
 1. **escrow**&mdash;Balanced, New Alliance, Ally, PayPal, Coinbase
 1. **payouts**&mdash;Balanced (U.S. bank accounts), Coinbase (bitcoin), PayPal

With Balanced going away, here's what we need to replace to maintain our current level of service:

 1. **identity verification**
 1. **payins**&mdash;credit cards
 1. 
 1. **payouts**&mdash;U.S. bank accounts

**Comment by whit537** [comment]
Let's start with an ideal scenario:

 1. We find a credit union that's willing to underwrite us as an MSB agent of theirs (#3322). They provide **compliance** and **escrow**.
 1. We find a merchant services provider to provide **payins** (credit card), while probably revaulting our cards at Spreedly (#210) as insurance against future gateway changes.
 1. We convince Trans-Pay that we're good to go (#417), and they provide **bank payouts**.

What can we realistically get done how fast?

**Comment by whit537** [comment]
I reached out to someone for a (soft) intro to IAFCU.

**Comment by whit537** [comment]
WePay (#69) and Braintree (#3287) are the remaining one-stop-shop marketplace offerings. I guess it could be even more ideal to drop one of those in for Balanced.

**Comment by whit537** [comment]
Even if we go with WePay and/or Braintree, I think we should take two steps to reduce the risk for the *next* time our gateway stops underwriting us for whatever reason (this is the third time now):

 1. Migrate to Spreedly now.
 1. Improve our compliance story via #3321 #3322 gratipay/inside.gratipay.com#119 and whatever else may come out of https://github.com/gratipay/inside.gratipay.com/issues/119.

If we can't use WePay and/or Braintree then the only option I see is to fast-track 2 and hope for the best with companies like IAFCU and Trans-Pay ... and that seems really risky to me. :-(

**Comment by whit537** [comment]
If we can't partner with companies that can provide traditional credit card and bank account processing, then option 3 would be to use non-traditional options such as Coinbase and Dwolla.

Scenarios, best to worst:

 1. **compliance**, **payins** (credit card), and **payouts** (bank account) via WePay and/or Braintree
 1. DIY **compliance**, **payins** (credit card), and **payouts** (credit card) via other partnerships
 1. DIY **compliance**, **payins** (non-traditional) and **payouts** (non-traditional) via other partnerships

**Comment by whit537** [comment]
Dwolla has a partnership with a credit union. Linked from their footer:

> Dwolla operates a software platform that sends your payment instructions to our financial institution partner, Veridian Credit Union. Your Dwolla balance, if any, is held in a pooled account at this financial institution. Please note that Dwolla balances are not insured. Dwolla is an agent of its financial institution partner.

https://legal.dwolla.com/about-our-financial-institution-partner/

**Comment by whit537** [comment]
Another option would be to more radically change our model so we could fit Stripe. Let's talk about that on #3324.

**Comment by whit537** [comment]
I'm starting to think of this whole process as a chance to clarify our product, refocus on open culture&mdash;open-source projects, open products, hackerspaces, cooperatives, etc., shifting the focus from tipping *individuals* to paying *projects*, with individuals behind the scenes splitting the money. I have in mind Braintree's advice a few years ago (above at https://github.com/gratipay/gratipay.com/issues/67#issuecomment-6566710):

> [N]arrow the focus, i.e., explicitly target open source developers for the first phase of buildout. If and when that is proven stable we can adjust our account to expand further.

**Comment by whit537** [comment]
We got the green light from Braintree (#3287)!

https://twitter.com/Gratipay/status/588421397606707200

**Comment by whit537** [comment]
We have a solution from Stripe! From https://github.com/gratipay/gratipay.com/issues/3324#issuecomment-93562216:

> 1) You make it clear that this is intended to support actual services, even if they're provided to the community and not to the payer (for example, ongoing open source development). We cannot support people using this to just pay out individuals for arbitrary usage.

This is the intention behind https://github.com/gratipay/inside.gratipay.com/issues/180.

> 2) You cap contributions from a single payer to a single receiver at $100/wk (as opposed to the current $1,000 limit for organizations). It doesn't look like anyone currently goes above $100 anyway, correct?

It looks like we only have two tips above $100, so we should be able to dial back to that level without too much trouble. Ironically, Stripe was the one for whom we upped the limit in the first place: https://github.com/gratipay/gratipay.com/issues/1378#issuecomment-44040763. :-)

> 3) You remain US-only for recipients for the time being.

Almost half of our payouts are outside the US, so this is going to be a significant obstacle for us. Let's dig in on #3287 to understand better what Braintree offers us here.

> 4) As previously stated, funds are paid out directly to bank accounts, no stored balances with redistribution.

Both Braintree and Stripe are requiring this. We're looking at zeroing out our escrow in #1383. It's going to be hard but at this point I think we have to do it, because both Braintree and Stripe are requiring it.

**Comment by rohitpaulk** [comment]
> 1) You make it clear that this is intended to support actual services, even if they're provided to the community and not to the payer (for example, ongoing open source development). We cannot support people using this to just pay out individuals for arbitrary usage.

> This is the intention behind gratipay/inside.gratipay.com#180.

We don't need that with braintree, they haven't mentioned such a limitation.

**Comment by whit537** [comment]
> they haven't mentioned such a limitation.

That could be because I put down "Sustainable crowdfunding for open-source projects" for "Business Description" on our application. I figured they'd have similar requirements as Stripe in this regard. I have a vague sense that other payments companies want this, too. Maybe I picked this up from Trans-pay? Anyway, we could/should scour the Braintree ToS and ask on #3287 (and/or email) to be sure if we want to try to avoid this requirement.

**Comment by whit537** [comment]
https://medium.com/gratipay-blog/balancedshutdown-3a9fdb32e9c6
https://twitter.com/Gratipay/status/588825910956130304

**Comment by whit537** [comment]
> That could be because I put down "Sustainable crowdfunding for open-source projects" for "Business Description" on our application. I figured they'd have similar requirements as Stripe in this regard.

Now that I think about it, I was also acting under the influence of their advice from a few years ago (above at https://github.com/gratipay/gratipay.com/issues/67#issuecomment-6566710):

> His advice was to narrow the focus, i.e., explicitly target open source developers for the first phase of buildout. If and when that is proven stable we can adjust our account to expand further.

**Comment by whit537** [comment]
> Almost half of our payouts are outside the US, so this is going to be a significant obstacle for us. Let's dig in on #3287 to understand better what Braintree offers us here.

Braintree marketplaces are also [US-only for payouts](https://github.com/gratipay/gratipay.com/issues/3287#issuecomment-94475862).

**Comment by whit537** [comment]
Status report:

##### Stripe (#3324)

Not feeling warm and fuzzy. Patreon works around Stripe's US limitations in the same way we worked around Balanced's (via alternate services, PayPal and Payoneer in their case). Would Stripe let us get away with the same practice? I'm reluctant to trust that they would, but I'm also reluctant to press the point. :-(

##### Braintree (#3287)

We can't use their Marketplace product because they don't provide true escrow (https://github.com/gratipay/gratipay.com/issues/3287#issuecomment-96666583). We could potentially use a regular merchant account with them in conjunction with a separate ACH provider for payouts (e.g., #3366).

##### MangoPay (#891)

Nervous because they're small like Balanced was. They do provide true escrow, and they have better international support than Stripe or Braintree, but still not good enough (we couldn't pay @rohitpaulk, e.g.).

**Comment by whit537** [comment]
I'm currently leaning towards a tier-2 [scenario](https://github.com/gratipay/gratipay.com/issues/67#issuecomment-91369922), with Braintree for merchant services and Citizens for ACH. I have intro calls with lawyers starting this afternoon, I'll use those to start exploring what it would mean for us to own our own regulatory compliance.

**Comment by whit537** [comment]
> we couldn't pay @rohitpaulk, e.g.

Unless we could? I can't tell, actually. Is IBAN enough, @rohitpaulk?

https://docs.mangopay.com/api-references/bank-accounts/.

**Comment by whit537** [comment]
More evidence that what we were doing with Balanced was acceptable, from the MangoPay [FAQ](https://www.mangopay.com/faqs/):

> In order to accept payments via PayPal, you will need to implement PayPal outside of our solution and open a merchant account directly with them.

**Comment by rohitpaulk** [comment]
> Unless we could? I can't tell, actually. Is IBAN enough, @rohitpaulk?

Yes, for India. I've been paid through Payoneer before, and IIRC they asked for my IBAN and my bank's SWIFT/BIC code.

**Comment by whit537** [comment]
[IRC](https://botbot.me/freenode/gratipay/2015-04-27/?msg=37676292&page=1)

**Comment by whit537** [comment]
> Hi everyone,
>
Most of you have already migrated, but this email is relevant to everyone. It outlines what you should expect after June 11, the day we stop processing. 
>
On June 12, we are going to clear our vault of all card numbers and almost all bank account numbers [1], and we will not support tokenizing any new cards or banks accounts. Refunds don't need card numbers, and we'll continue to support refunds until October 9. However, our bank requires a bank account number for ACH reversal, so June 11 is the last day you'll be able to perform a reversal. 
>
If you haven't already migrated, I suggest you do so by mid-May to give yourself enough time in case you need to resolve any issues and adequate time to be able to reverse payouts. 
>
Matin
>
[1] We will keep your marketplaces bank account number to give you the ability to manage your escrow balance by debiting from and crediting to your bank account.

**Comment by whit537** [comment]
Okay! We have a Braintree account! :dancer: 

We also almost have a lawyer to help us with regulatory compliance (https://github.com/gratipay/inside.gratipay.com/issues/193)!

Now all we need is an ACH provider ...

**Comment by whit537** [comment]
ACH is going to be [non-trivial](http://www.quora.com/What-provider-offers-the-best-way-to-send-ACH-payments-programmatically-through-an-API). Starting with two options: Citizens (https://github.com/gratipay/gratipay.com/issues/3366) and OpenACH (https://github.com/gratipay/gratipay.com/issues/3371).

**Comment by whit537** [comment]
Reached out to IAFCU re: ACH: #3372.

**Comment by whit537** [comment]
SynapsePay? #3373

**Comment by whit537** [comment]
Finxera? #3374

**Comment by whit537** [comment]
We chose an attorney (https://github.com/gratipay/inside.gratipay.com/issues/193), and Citizens is working on pricing for us (which makes it sound like they've decided to underwrite us). I'm hopeful that those two relationships will fully crystallize in a week to ten days. Let's look at a timeline ...

**Comment by whit537** [comment]
Here's a timeline we can update as we go along: https://gist.github.com/whit537/fe8e098364f20e77fd80.

**Comment by whit537** [comment]
Here's a timeline we can update as we go along:

https://docs.google.com/spreadsheets/d/1NVi9C0pYkrgh5wNTi0KzlBZCovKACmbHuToFoCa-Ks4/edit?usp=sharing

**Comment by whit537** [comment]
As we wrap up the design of our new processing infrastructure on this ticket, I've reticketed implementation as #3377.

**Comment by whit537** [comment]
Balanced requires us to be PCI compliant in order to give us bank accounts and identity info. :wrench:

**Comment by whit537** [comment]
See #3379 for getting certified by Balanced to receive bank accounts and identity info.

**Comment by whit537** [comment]
I'm leaning against Spreedly because a) it's expensive, b) we're in a [cash crunch](https://github.com/gratipay/inside.gratipay.com/issues/149#issuecomment-98786721), and c) it's another moving part, which is an implementation risk (https://github.com/gratipay/gratipay.com/issues/210#issuecomment-98784291). I think we should go with straight Braintree.

**Comment by whit537** [comment]
Okay, made the call on #210. No Spreedly, vaulting with Braintree.

**Comment by webmaven** [comment]
Braintree owns [Venmo](https://venmo.com/),  and they may have some helpful code such as:
https://github.com/venmo/btnamespace

I also found this: https://github.com/highfidelity/fake_braintree

**Comment by whit537** [comment]
Dialing back out from #3377: We are now on Braintree. Yay! :dancer: 

On the bank payout side, we're stuck. We do have New Alliance for escrow and we do have PayPal for payouts, but we're stuck on ACH. We tried Citizens (#3366) but they rejected us. What should we do?

**Comment by whit537** [comment]
Options:

 - Drop ACH payouts. Only support PayPal.
 - Find a bank that will take us.
 - Chase one of these wrappers: #3373 #3374 #3491.

**Comment by whit537** [comment]
Here's a list of banks:

http://files.consumerfinance.gov/f/201503_cfpb_depository-institutions-list.pdf

**Comment by whit537** [comment]
Looks like Zipmark (#3491) is working out.

**Comment by whit537** [comment]
Zipmark is getting mired in complication around AML (gratipay/inside.gratipay.com#119, #2449).

**Comment by whit537** [comment]
Proposal: We drop U.S. bank payouts. PayPal is the only way to get money out of Gratipay. Thoughts?

**Comment by whit537** [comment]
Escrow shuffled from New Alliance to PayPal. Emptying our Balanced escrow reticketed as https://github.com/gratipay/inside.gratipay.com/issues/266.

**Comment by whit537** [comment]
Sorry, wrong ticket. :)

**Comment by whit537** [comment]
##### The Case for PayPal

Gratipay already uses PayPal. We were running roughly 50% PayPal before the [Gratipocalypse](https://medium.com/gratipay-blog/gratipocalypse-42fd0ec0d9e8), and today we made 20 PayPal payouts, and 6 bank payouts. PayPal's fees are not actually that bad: 2%, capped at $1 for U.S., and $20 for non-U.S. It's simple and ubiquitous. Compared to the [red nightmare](https://vimeo.com/44061751) that #3491 is turning into, MassPay doesn't seem that bad.

Since we already have PayPal implemented, it'd be only a little extra work on our part (just ripping out bank accounts and notifying people, basically), and it would get us out of a *lot* of AML work. We could work on https://github.com/gratipay/inside.gratipay.com/issues/119 over the next year or so, and then maybe reapproach Transpay (#417; they seem the best-suited to help with global bank payouts). We can take our time and do this right. Not rush and cut corners. We've learned a *lot* this time around. Now we know what "right" means.

**Comment by whit537** [comment]
MassPay goes up to 5,000 payouts. Transpay, et al. want to see more scale from us anyway. I got blatantly laughed at by one vendor (https://github.com/gratipay/inside.gratipay.com/issues/259). We've got a lot of product problems to solve and community-building to do, PayPal for payouts would not be our bottleneck. We could grow for a year and then revisit the idea of being "a true payments company."

**Comment by tshepang** [comment]
where is the *laughed at* part in that link

**Comment by whit537** [comment]
@tshepang Added to https://github.com/gratipay/inside.gratipay.com/issues/259#issuecomment-113185704 (and link updated in above comment).

**Comment by webmaven** [comment]
@whit537:
> PayPal for payouts would not be our bottleneck. 

It would be a dealbreaker for me. I refuse to do business with them (observed too many others with spurious 'frozen funds' issues and PP refusing to deal with problems of their own making until sufficient internet rage is directed at them), and do not have an account.

I really do not want my accumulated balance to be refunded to donors simply because I refuse to accept funds through PP.

**Comment by whit537** [comment]
@webmaven How about Dwolla?

**Comment by webmaven** [comment]
@whit537, never tried them.

**Comment by whit537** [comment]
@webmaven Dwolla would be sort of a cross between what we've been offering so far with ACH and PayPal: they're U.S.-only like ACH, but they require signing up for an account like PayPal. There is no per-transaction cost (Gratipay would pay a flat monthly fee for features such as next-day transfers).

Mind looking into them? Technically speaking, they're quite parallel to PayPal, so implementation would be fairly straightforward. I think it could complement PayPal nicely for us.

**Comment by webmaven** [comment]
I'll look into them. As long as they don't have stories like these floating around, I'll likely be OK with them:
* https://www.google.com/?#q=paypal%20smashed%20violin
* https://www.google.com/?#q=paypal+frozen+crowdfunding

**Comment by rohitpaulk** [comment]
^^ I don't see how those cases are wrong. 

In the first case,

> "While we cannot talk about this particular case due to PayPal's privacy policy, we carefully review each case, and in general we may ask a buyer to destroy counterfeit goods if they supply signed evidence from a knowledgeable third party that the goods are indeed counterfeit. The reason why we reserve the option to ask the buyer to destroy the goods is that in many countries, including the US, it is a criminal offense to mail counterfeit goods back to a seller."

In the second case, 

> We are now in the midst of overhauling our policies in this space. We're talking to the major crowdfunding players that we work with to put in place a permanent solution that avoids unnecessary account limitations. But making this work for all stakeholders—contributors, entrepreneurs, crowdfunding sites and us—is pretty complicated. As soon as I have more to share, I promise to update everyone.
> In the meantime, we will ensure that each crowdfunding campaign is reviewed by a senior member of my team before any action is taken. It’s a small, but important step.

**Comment by whit537** [comment]
Sources I'm finding for @rohitpaulk's quotes:

http://gizmodo.com/5872958/paypal-smashed-some-ladys-antique-violin-and-can-smash-yours-too

https://www.paypal-community.com/t5/PayPal-Forward/PayPal-and-Crowdfunding/ba-p/782560

(P.S. I wish Google ranked original sources higher than derivative content from ad companies ... but I guess they themselves are an ad company. :-/)

**Comment by webmaven** [comment]
Yeah, that September '13 blog post from PayPal is *really* reassuring. Oh, wait, not really, they are still doing this to people:
http://garethhayes.net/paypal-warning/

**Comment by webmaven** [comment]
OK, it looks like Dwolla passes the smell test. At least, I can't find any horror stories regarding them. So far as I can tell, they only freeze funds when they are told to by law enforcement.

@whit537, can you get statements from them regarding their policies in this area? Do they ever proactively freeze accounts or reverse transactions that 'seem' suspicious to them?

**Comment by whit537** [comment]
> OK, it looks like Dwolla passes the smell test.

@webmaven Cool. 

> [C]an you get statements from them regarding their policies in this area? Do they ever proactively freeze accounts or reverse transactions that 'seem' suspicious to them?

I'll let you pursue that if you like, perhaps on #726.

**Comment by whit537** [comment]
Okay! We have new payment partners: Braintree for payins, New Alliance for escrow, and PayPal for payouts. We have [survived the Balanced shutdown](https://medium.com/gratipay-blog/off-balanced-e3d19f2abece)! With that, may this ticket pass once again into the quietude of history, whenceforth it was called in our hour of need. It has served us well, now may it enjoy a hero's rest.

:horse: :flags: :fallen_leaf:

**Comment by mattbk** [comment]
Inquiry from support: https://gratipay.freshdesk.com/helpdesk/tickets/2766
