### ISSUE TITLE
look into WePay

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#69]
Somehow missed [WePay](https://www.wepay.com/) when switching away from Samurai (#58). Here's their [marketplace use case](https://www.wepay.com/developer/usecases/marketplace).

**Comment by whit537** [comment]
[IRC](https://botbot.me/freenode/gratipay/2015-04-02/?msg=35662257&page=1)

**Comment by Changaco** [comment]
WePay is nice, but AFAICT they don't let us handle all user interactions, and since they don't seem to have full i18n it'd be a step backwards in terms of UX.

**Comment by lookfirst** [comment]
@Changaco It is the difference between [WePay Connect and WePay Clear](https://wepay.com/developer/wepay-clear).

With Clear, you assume a lot more of the PCI compliance. That is why they offer two 'versions' of the service. 

In my experience using the Connect version for about 4 years now, it hasn't been an issue on the customer end. 

If there is i18n languages that they don't support, it is worth talking with WePay about getting translations for them. They have always been responsive to me about these things.

**Comment by whit537** [comment]
> In both products, WePay communicates with merchants and payers through a variety of emails. With WePay Clear, partners are given opportunities to insert their brand into these emails and manage the communication process—although the emails are sent from WePay, they appear to come from the platform.

**Comment by whit537** [comment]
> If you are interested in integrating WePay Clear with your site, contact our sales team who will review your needs and make a detailed implementation guide available.

**Comment by Changaco** [comment]
Obviously I had looked at WePay Clear, and as I said it doesn't let us handle all user interactions.

I don't see evidence that WePay has any i18n, and if they don't have the underlying architecture it could take a while for them to implement it.

Finally, WePay is still US-only for payouts.

**Comment by whit537** [comment]
> Finally, WePay is still US-only for payouts.

I saw that they have a Canada beta, but certainly they don't have the reach of Stripe or Braintree.

**Comment by whit537** [comment]
+1 https://github.com/gratipay/inside.gratipay.com/issues/192#issuecomment-100504400

**Comment by whit537** [comment]
Over on #67 we've ended up going with a piecemeal solution, with Braintree for payins, and PayPal/Zipmark (hopefully; #3491) for payouts.
