### ISSUE TITLE
make logo files available under /about/

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#707]
So people can grab it to work with however they want.

**Comment by davelab6** [comment]
I seems the Gratipay logotype is made with a proprietary font, http://www.myfonts.com/fonts/mti/mundo-sans/std-bold/

I'd like to suggest using a libre font :)

**Comment by whit537** [comment]
@davelab6 Reticketed as https://github.com/gratipay/inside.gratipay.com/issues/147. :)

**Comment by whit537** [comment]
These are on http://inside.gratipay.com/big-picture/brand/.
