### ISSUE TITLE
show a "staff" badge on profiles of Gratipay employees

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#709]
ht @carsomyr after pghrb tonight
##

**Comment by nobodxbodon** [comment]
It depends on other non-tech issues like defining employee/payroll/contract. IMO the current 'project' section in user profile is enough.

**Comment by whit537** [comment]
Reopening because I still like this idea. Basically https://gratipay.com/Gratipay/distributing/ would drive this. https://github.com/gratipay/gratipay.com/issues/4299 is relevant.

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
