### ISSUE TITLE
Make it easier to add new recipients on the "Giving" screen

### ISSUE THREAD

**Issue by ncoghlan** [gratipay/gratipay.com#716]
Currently, to add a new recipient, I have to leave the giving screen, find their profile, then add them.

I'd like to be able to just add new recipients directly on the giving screen (defaulting to "0.00", which I could then increase to one of the other levels)
##

**Comment by nobodxbodon** [comment]
Merged with https://github.com/gratipay/gratipay.com/issues/3107.
