### ISSUE TITLE
integrate with Skrill (was Moneybookers)

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#718]
https://www.skrill.com/app/

Reticketed from #65 (@chmike).
##

**Comment by whit537** [comment]
Reopening per https://github.com/naspeh/mailur/issues/4.

**Comment by whit537** [comment]
Heh. Thanks, @rohitpaulk. :-)

**Comment by nobodxbodon** [comment]
Re-ticketed to [support more means of payin and payout](https://github.com/gratipay/inside.gratipay.com/issues/974) for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.
