### ISSUE TITLE
review site for html injections

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#722]
I just discovered that I wasn't escaping statements. :-(

I'm not sure how that happened, but it did. We need to review the whole site for html injections.

**Comment by whit537** [comment]
Here's all the places in our templates where we use Jinja2 text interpolation:

https://gist.github.com/whit537/755c59aec14335b019b9

**Comment by whit537** [comment]
> Why is Autoescaping not the Default?
>
> There are multiple reasons why automatic escaping is not the default mode and also not the recommended one. While automatic escaping of variables means that you will less likely have an XSS problem it also causes a huge amount of extra processing in the template engine which can cause serious performance problems. As Python doesn’t provide a way to mark strings as unsafe Jinja has to hack around that limitation by providing a custom string class (the Markup string) that safely interacts with safe and unsafe strings.
> 
> With explicit escaping however the template engine doesn’t have to perform any safety checks on variables. Also a human knows not to escape integers or strings that may never contain characters one has to escape or already HTML markup. For example when iterating over a list over a table of integers and floats for a table of statistics the template designer can omit the escaping because he knows that integers or floats don’t contain any unsafe parameters.
> 
> Additionally Jinja2 is a general purpose template engine and not only used for HTML/XML generation. For example you may generate LaTeX, emails, CSS, JavaScript, or configuration files.

http://jinja.pocoo.org/docs/dev/faq/#why-is-autoescaping-not-the-default

**Comment by whit537** [comment]
Summarizing:

 - not always HTML
 - not always necessary even in HTML
 - performance

**Comment by whit537** [comment]
Retort:

 - We're only using Jinja2 for HTML.
 - But it doesn't *hurt* to use it when it's not needed.
 - Hmmm ... really?

**Comment by whit537** [comment]
It just seems increasingly stupid to rely on "a human knows" for the [544 places](https://gist.github.com/whit537/755c59aec14335b019b9) where are potentially vulnerable to injection. Performance will have to be *really* bad to justify not switching to autoescaping. No?

**Comment by whit537** [comment]
http://jinja.pocoo.org/docs/dev/api/#autoescaping

**Comment by whit537** [comment]
Autoescape interacts with i18n somehow:

![screen shot 2015-02-04 at 1 15 30 pm](https://cloud.githubusercontent.com/assets/134455/6046414/f7ceb702-ac6f-11e4-9eed-586c3e2eb1ca.png)

**Comment by whit537** [comment]
> Also if [newstyle gettext calls] are used in an autoescaping environment they better support automatic escaping. 

http://jinja.pocoo.org/docs/dev/extensions/#newstyle-gettext

**Comment by whit537** [comment]
So it looks like implementing autoescaping will take some work. It's not a trivial quick answer to this ticket.

**Comment by Changaco** [comment]
> - We're only using Jinja2 for HTML.

Not true, we also use it for plain text in email simplates.

**Comment by whit537** [comment]
P.S. The place to implement autoescaping would be in aspen_jinja2, by adding `autoescape=True, extensions['jinja2.ext.autoescape']` to the `Environment` instantiation. Then, another thing to work around is that we don't want to autoescape the CSS and JS assets. The workaround for that is:

```
[---]
{% autoescape false %}{{ css }}{% endautoescape %}
```

> If the application enables the Autoescape Extension one can activate and deactivate the autoescaping from within the templates.

http://jinja.pocoo.org/docs/dev/templates/#autoescape-extension

**Comment by whit537** [comment]
> Not true, we also use it for plain text in email simplates.

Okay, so if we go with autoescaping I guess we'd use the `{% autoescape false %}` mechanism to turn it off for the text/plain email parts.

**Comment by whit537** [comment]
@Changaco Can you speak to whether we're using newstyle gettext calls?

**Comment by Changaco** [comment]
Sort of, we use custom functions.

**Comment by whit537** [comment]
Here's a slightly differently-formatted list:

https://gist.github.com/whit537/03b1e5f88fcf38c3dd87

Looks like we have 527 replacements on master right now

**Comment by whit537** [comment]
I separated out the places where we are just doing i18n `{{ _("Greetings, program!") }}`.

https://gist.github.com/whit537/007d96927377a7ed0419

**Comment by whit537** [comment]
| Category | N |
| --- | --- |
| High Risk | 336 |
| Simple i18n | 139 |
| Assets | 23 |
| Escaped | 29 |

https://gist.github.com/whit537/0a60f06b87ecc332f4fe

**Comment by whit537** [comment]
Alright, I still don't want to go through 336 of these. :-)

**Comment by whit537** [comment]
The next step down the autoescaping path is to benchmark performance. If performance isn't "really a lot" worse with autoescaping then we should just use that. It'll take a chunk of work to switch over though due to i18n so benchmarking probably makes sense to make sure it'll be worth it.

**Comment by whit537** [comment]
If performance is really as atrocious as promised then we should review the 336 places and make it part of our PR review habit.

**Comment by whit537** [comment]
Here's a script I wrote to help with benchmarking:

https://gist.github.com/whit537/352a6b02d5f644720007

Gonna do some benchmarks now.

**Comment by whit537** [comment]
```
[gratipay] $ honcho run -e defaults.env,local.env ./env/bin/python benchmark-autoescaping.py | grep " seconds "
11.9522500038 seconds without autoescaping
12.4190990925 seconds *with* autoescaping
[gratipay] $
```

```python
#!/usr/bin/env python
"""This is a helper script for benchmarking page performance re: #722.

Set this in local.env to avoid a canonicalizing redirect:

    CANONICAL_HOST=

Then run this script like so:

    [gratipay] $ honcho run -e defaults.env,local.env ./env/bin/python benchmark-autoescaping.py

"""
import time
import aspen_jinja2_renderer
from gratipay.testing import Harness


def autoescaping_compile_meta(self, configuration):
    loader = None
    if configuration.project_root is not None:
        # Instantiate a loader that will be used to resolve template bases.
        loader = aspen_jinja2_renderer.FileSystemLoader(configuration.project_root)
    return aspen_jinja2_renderer.Environment( loader=loader
                                            , autoescape=True
                                            , extensions=['jinja2.ext.autoescape']
                                             )

start = time.time()
for i in range(100):
    Harness.client.GET('/')
print("{} seconds without autoescaping".format(time.time() - start))

aspen_jinja2_renderer.Factory.compile_meta = autoescaping_compile_meta

start = time.time()
for i in range(100):
    Harness.client.GET('/')
print("{} seconds *with* autoescaping".format(time.time() - start))
```

**Comment by whit537** [comment]
10x

```
[gratipay] $ honcho run -e defaults.env,local.env ./env/bin/python benchmark-autoescaping.py | grep " seconds "
1.3902361393 seconds without autoescaping
1.18036794662 seconds *with* autoescaping
[gratipay] $
```

**Comment by whit537** [comment]
```
[gratipay] $ honcho run -e defaults.env,local.env ./env/bin/python benchmark-autoescaping.py 10 | grep " seconds "
1.29223489761 seconds without autoescaping
1.17796278 seconds *with* autoescaping
[gratipay] $ honcho run -e defaults.env,local.env ./env/bin/python benchmark-autoescaping.py 100 | grep " seconds "
11.9243550301 seconds without autoescaping
12.4741439819 seconds *with* autoescaping
[gratipay] $ honcho run -e defaults.env,local.env ./env/bin/python benchmark-autoescaping.py 1000 | grep " seconds "
124.910935163 seconds without autoescaping
132.204340935 seconds *with* autoescaping
[gratipay] $
```

```python
#!/usr/bin/env python
"""This is a helper script for benchmarking page performance re: #722.

Set this in local.env to avoid a canonicalizing redirect:

    CANONICAL_HOST=

Then run this script like so:

    [gratipay] $ honcho run -e defaults.env,local.env ./env/bin/python benchmark-autoescaping.py

"""
import sys
import time

import aspen_jinja2_renderer
from gratipay.testing import Harness


def autoescaping_compile_meta(self, configuration):
    loader = None
    if configuration.project_root is not None:
        # Instantiate a loader that will be used to resolve template bases.
        loader = aspen_jinja2_renderer.FileSystemLoader(configuration.project_root)
    return aspen_jinja2_renderer.Environment( loader=loader
                                            , autoescape=True
                                            , extensions=['jinja2.ext.autoescape']
                                             )

try:
    n = int(sys.argv[1])
except IndexError:
    n = 10

start = time.time()
for i in range(n):
    Harness.client.GET('/')
print("{} seconds without autoescaping".format(time.time() - start))

aspen_jinja2_renderer.Factory.compile_meta = autoescaping_compile_meta

start = time.time()
for i in range(n):
    Harness.client.GET('/')
print("{} seconds *with* autoescaping".format(time.time() - start))
```

**Comment by whit537** [comment]
Alright, performance concerns look like FUD to me.
