### ISSUE TITLE
payout via dwolla masspay

### ISSUE THREAD

**Issue by colindean** [gratipay/gratipay.com#726]
Dwolla has a newish [MassPay](https://masspay.dwollalabs.com/) system, which allows up to 2,000 payouts at a time (limit can be raised). There's a [MassPay Node.js](http://blog.dwolla.com/masspay-nodejs/) library, and it's likely portable to Python.

I'm not sure about the intermediary steps - I think this API may assume that people are to be paid from a company's Dwolla balance, so the need to move cash from the company bank account to Dwolla exists. That may not be able to be automated, or may have an unacceptable delay.

Also, there's a 25¢ fee to send/receive > $10. This would affect users who are receiving greater than $10 per week and who choose Dwolla as a payout option.

#### Notify

- [ ] https://gratipay.freshdesk.com/helpdesk/tickets/6190

##

**Comment by whit537** [comment]
Dwolla sales: https://gratipay.freshdesk.com/helpdesk/tickets/1947.

**Comment by whit537** [comment]
I'm looking at Dwolla briefly in the context of the Balanced Shutdown. We're not going to pull off Zipmark (#3491), and we have nine users we need to transition to *something*. PayPal is the obvious choice since we already have it implemented. I *think* Dwolla is technically very similar to PayPal, so if it's an easy integration then it'd be nice to be able to offer it as an alternative to PayPal, since PayPal has some detractors (e.g., https://github.com/gratipay/gratipay.com/issues/67#issuecomment-113803821).

**Comment by whit537** [comment]
I've signed up for a vendors@gratipay.com Dwolla account (I actually did this a while ago, but I can't find my notes).

**Comment by whit537** [comment]
... but my phone number is linked to another Dwolla account, so I'm trying to recover *that* account. If we end up going with Dwolla we probably want two accounts anyway (escrow and operations).

**Comment by whit537** [comment]
Called 1-888-289-8744 and had them lookup the old account by phone number (412-925-4220), and send a password reset. I have access to both accounts now.

**Comment by whit537** [comment]
I've configured the two accounts to be the same (except for different emails and phone numbers). We have an EIN mismatch with the operations Dwolla account, due to https://github.com/gratipay/gratipay.com/issues/3463; we'll see what they say during the verification process.

**Comment by whit537** [comment]
P.S. They changed their pricing model: http://blog.dwolla.com/free-bank-transfers/. No more transaction fees. Instead, Gratipay would pay monthly for features such as next-day transfers and higher limits: https://www.dwolla.com/pricing.

**Comment by whit537** [comment]
I've refunded the $1.00 that @bpmilne sent us when we opened our account on September 3, 2012. ;-)

**Comment by whit537** [comment]
I've kicked off trial deposit verification of our escrow bank account. This is the bank account I linked three years ago. It's at a tiny credit union, and at the time Dwolla choked on verifying it, which is what stalled us out back then.

**Comment by whit537** [comment]
MassPay looks very similar to PayPal:

![Dwolla MassPay UI](https://cloud.githubusercontent.com/assets/134455/8291483/f85c6e90-18f7-11e5-9cf0-2dcb7721a1fe.png)

**Comment by whit537** [comment]
Operations Dwolla account verified.

https://gratipay.freshdesk.com/helpdesk/tickets/2437

**Comment by capablemonkey** [comment]
@whit537 let me know if you need any help integrating Dwolla!  Happy to lend a hand.

Check out our [dwolla-python](https://github.com/Dwolla/dwolla-python) library.  The [MassPay example](https://github.com/Dwolla/dwolla-python/blob/master/examples/masspay.py) file should be helpful.

**Comment by whit537** [comment]
Thanks @capablemonkey! Will ping you if we have questions. :-)

**Comment by webmaven** [comment]
@capablemonkey, So far as I can tell, you only freeze funds when are told to by law enforcement.

Can you make any statements regarding your policies in this area?

Do you ever proactively freeze accounts or reverse transactions that 'seem' suspicious to you (for example, because of a sudden surge of financial activity)? This is the thing that seems to still get Kickstarter projects in trouble with PayPal.

**Comment by mattbk** [comment]
+1 for an alternative payout method from https://gratipay.freshdesk.com/helpdesk/tickets/2405, who does not want to use PayPal.

**Comment by capablemonkey** [comment]
Hey @webmaven, so sorry for the late reply.

Unfortunately, there are always bad actors who to seek to take advantage of either Dwolla or Dwolla customers.  To insure the integrity of Dwolla's network, we may take proactive action as necessary in the event of fraudulent activity, activity that is prohibited by our TOS, or activity that could appear to be money laundering or terrorist financing.

We do our best to insure that these actions are limited in nature and only used when truly necessary.

**Comment by webmaven** [comment]
@capablemonkey, does Dwolla have policies in place to prevent the sort of overreaction that results in incidents like these?:
http://hackaday.com/2015/01/22/when-paypal-and-crowdfunding-dont-mix/
http://www.businessinsider.com/paypal-violin-destroy-return-refund-2012-1

**Comment by capablemonkey** [comment]
@webmaven,

We do our best to vet customers up front, and make that determination prior to holding customer funds and creating a situation like the one you mentioned.  As for the violin incident, Dwolla does not currently, nor will we in the forseeable future, have any requirement to destroy items as part of our dispute process.

**Comment by whit537** [comment]
> Coming soon, Dwolla white label partners will be able to seamlessly create customer records and initiate payouts via the API. Your business name will display next to the subsequent deposits on a customer’s bank account, and all required email communication will be sent and branded from you.
>
But wait, there's more. This is only phase one of Dwolla's white label solution.

http://blog.dwolla.com/white-label-coming/

**Comment by webmaven** [comment]
@capablemonkey, what's the vetting porocess?

**Comment by capablemonkey** [comment]
@webmaven, here's an answer from our risk team:

The vetting process depends on the type of business and the risks surrounding it.  Some of the main risks we take under consideration are credit risk and regulatory risk; for example, the more complex the regulations surrounding a business type, the more questions and/or documents we will likely need.

**Comment by webmaven** [comment]
OK, @capablemonkey, can we narrow the scope to the Open Work that Gratipay is trying to support? What vetting would I have to go through as a open source project leader/maintainer, or as the creator of open content, of various sorts, etc.?

If a project on Gratipay starts seeing a large influx of payments due to increased popularity (because most successful projects start out very small), will that trigger any problems?

**Comment by capablemonkey** [comment]
On the payout side, we'd only need one party to be fully verified.  It looks like your operations account is already fully vetted, so we're good there!  Assuming you'll be paying out from that account, your recipients can claim their pay out by creating a lightweight Dwolla Direct account, which only requires them to create a login and provide their full name, routing and acc. no.

It sounds like you're also considering using Dwolla for pay-ins.  If you do accept Dwolla on the pay-in side, would you want the tips to go directly from the tipper to the recipient?  Or, would all the tips be pooled to a main 'escrow' account, where they're later disbursed?  If the former, then all the users-to-be-tipped will need to create fully verified, vetted Dwolla account.

Increased popularity/volume shouldn't trigger any problems by itself.

**Comment by webmaven** [comment]
@whit537, I think @capablemonkey's Qs are best answered by you.

**Comment by whit537** [comment]
> [W]ould you want the tips to go directly from the tipper to the recipient? Or, would all the tips be pooled to a main 'escrow' account, where they're later disbursed?

The latter. We pool all payments into an escrow account ([docs](http://inside.gratipay.com/howto/shuffle-escrow)), and then make payouts from there.

> It looks like your operations account is already fully vetted, so we're good there!

We have two Dwolla accounts. The one we'd use for our escrow account is under `dwolla@gratipay.com`. Gratipay is funded by voluntary payments [via Gratipay](https://gratipay.com/Gratipay/) (so meta! :), so if we decided to use Dwolla to withdraw our own voluntary payments received, we'd use our second Dwolla account, the operations one under `vendors@gratipay.com`. Sounds like the operations account is ready to go. Is the escrow account fully vetted, @capablemonkey?

**Comment by webmaven** [comment]
@capablemonkey: ping

**Comment by capablemonkey** [comment]
@webmaven @whit537, checking in here.  I believe Ryan from our risk team is continuing the conversation with you in private over email.  Let me know if that's not the case, or if you've got any other questions!

**Comment by whit537** [comment]
Thanks @capablemonkey. :-)

Do you know whom Ryan contacted? I haven't noticed a message come through yet. vendors@gratipay.com is probably the best email to use.

**Comment by capablemonkey** [comment]
@whit537 whoops!  I'll connect you two via email then.

**Comment by whit537** [comment]
Awesome, thanks @capablemonkey. :-)

**Comment by whit537** [comment]
P.S. Happy to cc: in @webmaven if you were mailing him.

**Comment by whit537** [comment]
https://gratipay.freshdesk.com/helpdesk/tickets/2948

**Comment by whit537** [comment]
> I want to put you in touch with Ryan from our risk team at Dwolla.  He had some questions for you regarding your proposed integration.  He can also address any questions you may have around our fraud policies.

---------

> Good to connect, Ryan. Should we schedule a phone call? Mondays and Thursdays are usually pretty good for me, and I'm in US/Eastern. Let me know how you'd like to proceed. :-)

**Comment by whit537** [comment]
https://gratipay.freshdesk.com/helpdesk/tickets/2960

> Either a phone call or e-mail works for me, whichever you prefer.  Thursday I'm available at 10am PDT; Monday is pretty booked other than 2pm PDT.
>
As I believe you have worked back and forth with, I wanted to see where you stand in regards to money transmission and your potential model of aggregating funds in your own Dwolla account.

----------

>We rewrote our [terms of service](https://gratipay.com/about/policies/terms-of-service) a few months ago to fit the payment processor exemption to the definition of a money transmitter. As I'm sure you know, the four criteria to fit this exemption are:
>
 - the entity providing the service must facilitate the purchase of goods or services, or the payment of bills for goods or services (other than money transmission itself);
 - the entity must operate through clearance and settlement systems that admit only BSA-regulated financial institutions;
 - the entity must provide the service pursuant to a formal agreement;
 - and the entity’s agreement must be at a minimum with the seller or creditor that provided the goods or services and receives the funds.
>
I can walk you through our terms if you like so you can understand our approach in detail. Almost all of our internal discussions are public, so if you want to peak inside you could start with [this comment](https://github.com/gratipay/inside.gratipay.com/issues/192#issuecomment-100048271).
>
As to aggregating funds, here is [our current setup](http://inside.gratipay.com/howto/shuffle-escrow). We would be looking to use Dwolla as an additional escrow account within our system.
>
What risks are you concerned about with our scenario? What controls are you looking for? What questions can I answer?

**Comment by whit537** [comment]
> Thanks for the response and the links; I appreciate the thoughtful process involved here.
>
Have these controls in this comment been implemented? https://github.com/gratipay/gratipay.com/issues/3324#issuecomment-93562216
>
If so, I think we can close out our concerns on this end, thank you.

----------------

>> Have these controls in this comment been implemented?
>
We have implemented half of the controls Stripe asked for:
>
1) Yes. This was the crucial issue in our terms rewrite.
2) No. The weekly cap is still at $1,000.
3) No. About half our users are outside the U.S.
4) Yes. We stopped escrowing indefinitely as part of our [Gratipay 2.0](https://medium.com/gratipay-blog/gratipay-2-0-2453d3c53077) upgrade (which also included the terms rewrite).
>
Here's [our original analysis](https://github.com/gratipay/gratipay.com/issues/67#issuecomment-93580252) of Stripe's proposal, for the record.
>
(3) is still going to be hard-to-impossible for us to accept, because so many of our users are outside the U.S. Dwolla is U.S.-only, correct? Therefore, we would of course only expect to be able to offer Dwolla payins and payouts to our U.S. customers. However, our payouts via Dwolla would be aggregated partially from payins originating outside the U.S., and vice versa. PayPal is the only other payout route we offer; we are drafting off them for KYC.
>
Regarding (2), we don't actually have any payments over $100/wk right now—you can see the current spread towards the bottom of [our stats page](https://gratipay.com/about/stats)—so this would be pretty easy for us to accept. I know we'll get pressure eventually to up the limit again. Can we agree to revisit this cap in the future?

**Comment by whit537** [comment]
> $1,000/week is fine; I'm sure once we see some actual activity flowing through the system we'd be happy to talk about adjusting limits to different levels.
>
Thanks Chad; Gordon, I don't think I have any further questions, and can let you and Chad get back at it.

-------------------

> Awesome, thanks Ryan! :D

:dancer: :dancers:

**Comment by whit537** [comment]
> Sweet!  Thanks so much for bringing this front to a close, Ryan and Chad!  
>
Chad, could you remind me where we left off?

-------------------

>I think we can move back over to GitHub to see if webmaven is satisfied, and start thinking about implementation.
>
https://github.com/gratipay/gratipay.com/issues/726
>
See you there! :-)

**Comment by whit537** [comment]
Satisfied, @webmaven? :-)

**Comment by webmaven** [comment]
Satisfied.

**Comment by whit537** [comment]
Awesome. :-)

Next step is for someone to make a PR to add Dwolla as a payout route.

**Comment by whit537** [comment]
Convenient timed in my inbox ... ;-)

"[Introducing Dwolla white label (for payouts)](http://blog.dwolla.com/simple-integrated-ach-payouts/)"

**Comment by whit537** [comment]
@capablemonkey What's the pricing like on white-label?

**Comment by whit537** [comment]
Ironically, Dwolla's lack of per-transaction pricing is inconvenient for us, since we've been in the habit of passing that along to our users.

**Comment by mattbk** [comment]
Any movement on this, or will Dwolla not be happening?

**Comment by mattbk** [comment]
Also, how does this fit in with gratipay/inside.gratipay.com/issues/119?

**Comment by mattbk** [comment]
Okay, it looks like Dwolla is okay because it's not a bank?

**Comment by whit537** [comment]
> Also, how does this fit in with gratipay/inside.gratipay.com#119?

I don't see any roadblocks in that regard. Dwolla does its own KYC, and their risk department has cleared us.

**Comment by webmaven** [comment]
@whit537 is Dwolla going to be available by the deadline, or am I going to lose my balance?

**Comment by whit537** [comment]
@webmaven How about I send you a cashier's check? Let me know your mailing address on chad@zetaweb.com, eh?

**Comment by capablemonkey** [comment]
Hey @whit537 -- let me chat with our team and get back to you on pricing. I think we can come up with a special rate for Gratipay, considering you're an open source project that we'd love to support.

Did you guys need anything else from else before getting started on this integration?  Let me know how I can lend a hand.

**Comment by whit537** [comment]
Thanks, @capablemonkey. The bottleneck at this point is engineering bandwidth. In the past we've had engineers from Balanced Payments and Venmo contribute PRs for their respective services (#137 and #1857). Just sayin'. ;-)

In terms of pricing, we actually prefer to pay full price rather than taking advantage of open-source discounts. The reason is that the whole point of Gratipay is to value the work people do ... and we value the work you all do! :-)

**Comment by webmaven** [comment]
@whit537, mailing address sent.

If you want to (and can) defer my payout until Dwolla is available, that would be acceptable as well.

**Comment by whit537** [comment]
> Hey Chad,
>
Hope you're well!
>
I want to introduce you to [] who leads our Sales team.  He can talk to you about the pricing for White Label and whether or not it would be a good fit for Gratipay. If not, we can return to our original plan of using the free Dwolla-branded payout experience.
>
Thanks!

--------------

> Thanks for the introduction, Gordon.
>
Chad, very nice to e-meet you.  I'd be more than happy to discuss your overall payment needs and help determine if our white label solution would integrate with your goals.  Do you have 30m free tomorrow at 1pm or 3pm EST?  Let me know and I'll shoot over an invite to hold the time.  Otherwise, I'm free before 12pm EST on Friday as well.
>
Thanks - look forward to connecting!

-------------------

> Thanks []. Do you have any availability on Monday the 5th?

**Comment by whit537** [comment]
> Absolutely.  Does 3pm EST work for you?

--------------

> Sure, let's do it! :-)
>
My cell is 412-925-4220. Is that the best way to connect?

**Comment by whit537** [comment]
> Happy Monday! I did get your gcal invite but it's not convenient for me to accept due to the way our Google Apps are set up. Sorry!
>
Despite that, I'm looking forward to our call at 3:00! :-)

**Comment by whit537** [comment]
Just got off the phone with Dwolla sales. Whitelabel is out of our price range ($2,500 - $7,500 per month, 2-year minimum). We're looking at the free tier or Plus, if we want next-day payouts. I asked when the next internal hackday is, and it sounds like it would be in Des Moines in early November. Maybe I can cowork out there to get this done? :-)

**Comment by whit537** [comment]
@capablemonkey To put a point on it: If I show up in Des Moines in early November, would I be able to work with a Dwolla developer to add Dwolla as a payout option for Gratipay? What are the prospects? :-)

**Comment by webmaven** [comment]
@capablemonkey, @whit537, any progress on this issue? Will I be able to receive money anytime soon?

**Comment by whit537** [comment]
@webmaven Blocked on engineering bandwidth. PRs welcome! :-)

**Comment by webmaven** [comment]
Show me the Money! :wink: 

![Jerry Maguire GIF](https://media.giphy.com/media/3oEdv22bKDUluFKkxi/giphy.gif)

**Comment by whit537** [comment]
:stuck_out_tongue_winking_eye:

**Comment by webmaven** [comment]
@capablemonkey, If I start the work to integrate @Dwolla into GP myself, how much assistance can I expect from you (or perhaps someone else at your company)? I'm a reasonably experienced web dev, but this would be the first payment integration that I have ever done, and I am only superficially familiar with the GP codebase at present.

IOW, are you as incentivized to get this working as I am? :grinning:

**Comment by spencerhunter** [comment]
@webmaven @capablemonkey transitioned out of Dwolla a few weeks ago. Unfortunately the Dwolla team has limited bandwidth at this time, however we can definitely try to help out with any questions you may have. Feel free to shoot me(spencer@dwolla.com) a note and @mach-kernel and I will assist in any way we can!

**Comment by whit537** [comment]
@webmaven I've initiated a manual payout to you as a next step here. Can you confirm if/when that lands? Unfortunately, we didn't get #3861 merged and I wasn't careful enough and I ran payday (https://github.com/gratipay/inside.gratipay.com/issues/427) today without having recorded the exchange in your history. I've kludged it with a `cash` exchange route and the net net is that you now have a -1¢ balance. :P

**Comment by whit537** [comment]
@spencerhunter Thanks for reaching out! We'll circle back with you and @mach-kernel when we're ready to move forward with a full implementation. :-)

**Comment by webmaven** [comment]
@whit537, I got notification of a pending payment on Dec 1st, I am still waiting for it to clear.

**Comment by whit537** [comment]
@webmaven We got a notification that the payment is complete. Look good on your end?

**Comment by webmaven** [comment]
Yep.

**Comment by mattbk** [comment]
+1 from https://gratipay.freshdesk.com/helpdesk/tickets/4078.

**Comment by whit537** [comment]
@rohitpaulk Picking up from https://github.com/gratipay/gratipay.com/issues/3870#issuecomment-191053741 ... what do you need from me here? We have an account set up and we have the green light from Dwolla risk.

**Comment by whit537** [comment]
> Over the past year we’ve made a strategic pivot, transitioning our focus away from a consumer application to a SaaS model designed for businesses who need to access the ACH network and incorporate bank transfers into their own application or service.

http://blog.dwolla.com/your-brand-our-payments-platform/

**Comment by spencerhunter** [comment]
@whit537 and @rohitpaulk Let me know if I can assist in answering any questions on the Dwolla integration. Gordon provided an example [here](https://github.com/Dwolla/dwolla-python/blob/master/examples/masspay.py) if you're looking to use python. Here are a few additional helpful links:

https://docs.dwolla.com/#oauth
https://docs.dwolla.com/#masspay

I also wanted to mentioned that we recently released MassPay in our new v2 API: https://docsv2.dwolla.com/#masspay

**Comment by nobodxbodon** [comment]
Re-ticketed to https://github.com/gratipay/inside.gratipay.com/issues/974 for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.
