### ISSUE TITLE
reach out to content creators

### ISSUE THREAD

**Issue by chadwhitacre** [gratipay/gratipay.com#737]
Started thinking about this with Amanda Palmer, and really started thinking about this with Hank Green:

https://twitter.com/vihartvihart/status/312729706984267779
http://www.youtube.com/watch?v=IEYTFud4jBg
http://www.reddit.com/r/nerdfighters/comments/1adkeb/hanks_discussion_content_and_how_to_fund_it/
https://www.gittip.com/hankgreen/

Looks like he rolled his own:

http://nk.cm/brainscoop/

How can we go after this use case?

**Comment by whit537** [comment]
Ftr, [Patreon](https://www.patreon.com/) won this one.
