### ISSUE TITLE
don't use Google Analytics

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#761]
Per @buchuki.

**Comment by whit537** [comment]
Piwik PRO is $65/mo and afaict is reasonable wrt user privacy. From the [TOS](https://cloud.piwik.pro/tos/):

> 6.2.2 Piwik PRO may collect data on behalf of Customer while hosting Piwik Software on Piwik PRO servers; this data is fully owned by Customer and Piwik PRO does not make any use of such data and do not share it with third parties.

**Comment by whit537** [comment]
Piwik trial started:

![screen shot 2015-03-12 at 5 43 46 pm](https://cloud.githubusercontent.com/assets/134455/6628867/62ebeccc-c8df-11e4-87b1-cfdc765940de.png)

**Comment by whit537** [comment]
I believe that anyone with access to the shared folder on LastPass should be able to access https://gratipay.piwik.pro/. Can anyone confirm?

**Comment by solarimix** [comment]
Folks should do further analysis of Google's Analytics platform re: privacy concerns and keeping your data secure from malicious "non state actors" like big corporations who care nothing about small entrepreneurs or small businesses or orgs.

AwStats, and Piwik are great alternatives.  hoping to see more adoption of GNU in new tech and more web statistics analysis

I'm also partial to StatCounter
http://statcounter.com/about/mission/

...both sitemeter and statcounter also provide free and paid web analytics tiers, not sure how usable that is for an app or a web app.

cheers!

**Comment by webmaven** [comment]
@whit537, just tried to access, and it didn't work:

```
Error: Wrong Username and password combination.
```

**Comment by whit537** [comment]
I'm unable to access Piwik as well. I can get into our Piwik Pro account management interface, but not the Piwik instance itself.

**Comment by clone1018** [comment]
Maybe you have to make actual users for the piwik instance

**Comment by whit537** [comment]
@clone1018 Yeah, I did make one but I lost the password. Reset now, with a second entry in LastPass. 

Try again with "Piwik (Analytics Dashboard)"?

**Comment by webmaven** [comment]
Works now with the 2nd acct.

**Comment by whit537** [comment]
@webmaven Yay! Do you know enough about Piwik to say that it's adequate for our needs? Or would you need to do some evaluation vis-a-vis Google Analytics first?

**Comment by webmaven** [comment]
Would need to do some evaluation personally (and I can't give you a timeline for that right now), but by most accounts I've heard/read it should be adequate.

**Comment by whit537** [comment]
Okay, the trial is 30 days. I'm inclined to go for Piwik. We barely use Google Analytics. Surely Piwik can handle our basic needs.

**Comment by whit537** [comment]
I'm ready to drop GA and start paying for Pwiki. Objections?

**Comment by whit537** [comment]
I subscribed us to Piwik. First payment hits in 12 days, at the end of our 30-day trial.

**Comment by whit537** [comment]
I updated v.

**Comment by whit537** [comment]
I updated http://inside.gratipay.com/appendices/finances.

**Comment by whit537** [comment]
#3299 is deployed. All done here! :-)

**Comment by rohitpaulk** [comment]
> I updated http://inside.gratipay.com/appendices/finances. 

I don't see Piwik in http://inside.gratipay.com/appendices/finances. Was it removed later?

**Comment by techtonik** [comment]
Maybe we self-host it? It that case it would still be nice to have a line that says that this service comes ti us for free.

**Comment by whit537** [comment]
> I don't see Piwik in http://inside.gratipay.com/appendices/finances. Was it removed later?

Yes: https://github.com/gratipay/inside.gratipay.com/issues/328.

**Comment by whit537** [comment]
>>I don't see Piwik in http://inside.gratipay.com/appendices/finances. Was it removed later?
>Yes: gratipay/inside.gratipay.com#328.

@rohitpaulk I'll let you reticket in the Inside Gratipay repo if you want to turn Piwik back on. M'kay? :-)

**Comment by whit537** [comment]
> Maybe we self-host it? It that case it would still be nice to have a line that says that this service comes ti us for free.

Also an option. Reticket if you want to drive this.

**Comment by emanwebdev** [comment]
correct, we are all concerned

**Comment by solarimix** [comment]
Kewl
