### ISSUE TITLE
payin via ACH debit

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#777]
**was:** take money from Carl's bank account

@carljm thought since he connected a bank account that we would take his money.
##

**Comment by mattbk** [comment]
+1 on https://gratipay.freshdesk.com/helpdesk/tickets/4494

> Several of the companies that want to support the project are not willing to make payments using a credit card. Instead, they prefer to use a traditional invoicing process. That brings me to my question.
Does Gratipay accept payments by invoicing the contributing entity? **As an alternative, does Gratipay accept payments via ACH?**

**Comment by mojavelinux** [comment]
:+1: to ACH payments from contributors.

**Comment by nobodxbodon** [comment]
Re-ticketed to https://github.com/gratipay/inside.gratipay.com/issues/974 for further discussion and planning. After deciding on concrete implementation plan and dev work starts, this will be reopened for tracking purpose.
