### ISSUE TITLE
make a nice screencast / video for Gittip

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#783]
Per @tarekziade via [Twitter](https://twitter.com/tarek_ziade/status/314619441038110720), a la:

http://www.youtube.com/watch?v=3BCan_ASY0w
##

**Comment by rohitpaulk** [comment]
+1 on this. (Not powtoon, just the issue in general).

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
