### ISSUE TITLE
add data export for history

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#796]
Per @esacteksab on his [blog](http://www.barrymorrison.com/2013/Mar/19/how-i-use-gittip-and-why/).

**Comment by patcon** [comment]
+1

mostly interested in not having to manually tally "Gifts in", "Gifts out", and "Team take in", which seem to be the important distinctions in Canada for tax purposes -- "Gifts received (personal)", "Gifts given (business)" and "Income"

(Still need to talk to my accountant, so I might be corrected on the above.)

**Comment by whit537** [comment]
+1 https://gratipay.freshdesk.com/helpdesk/tickets/1749 (cf. https://github.com/gratipay/gratipay.com/issues/662#issuecomment-77820324)

**Comment by whit537** [comment]
> Here's what I whipped up in a spreadsheet and sent to our accountant:
>```
Annual Gratipay summary:
>
-------------------------------------------------------------------------------
{recipient} | {amount received} | {individual or organization} |
-------------------------------------------------------------------------------
{recipient} | {amount received} | {individual or organization} |
>
```
>A CSV export scoped to each calendar year would be great. :)

**Comment by whit537** [comment]
Me:

> What's the difference between "recipient" and "individual or organization"?

Them:

> Probably wouldn't be needed in the CSV export feature — it's how I'm distinguishing between donations to "a specific individual" vs. "a general org" like Homebrew or Bundler. (which our accountant asked for)
