### ISSUE TITLE
Document JavaScript testing

### ISSUE THREAD

**Issue by berryp** [gratipay/gratipay.com#808]
We now have a framework for JavaScript testing - though no real tests right now due to being blocked until #509 has been implemented (see note below.) We need documentation in the README for getting up and running with the JS tests, as well as information regarding the curent state.

*\* _A note on the state of the JS tests:_ **

_The tests we have right now are more for testing the testing setup to help ensure the test requirements are set up correctly than gittip itself. The reason for not having real code tests yet is most useful tests will be testing code that requires network authentication (e.g. via Twitter and Github.) Once DevNetwork (see issue #509) has been rolled we'll be able to write tests without having to worry about external authentication networks._
##

**Comment by nobodxbodon** [comment]
https://github.com/gratipay/gratipay.com/commits/master/tests/ttw seems to be replacement.
