### ISSUE TITLE
we ask for too many perms on bitbucket

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#822]
Reported in private email. We should ask for the minimum perms.

~~**This [is a Bitbucket limitation](https://twitter.com/erikvanzijst/status/323269226313965568), and it does not appear they have any intention of changing this, according to [official docs](https://confluence.atlassian.com/display/BITBUCKET/OAuth+FAQ#OAuthFAQ-DoIhavegranularcontrolofOAuthpermissions%28scopes%29?).**~~

Bitbucket has rolled out [OAuth 2.0](https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html#OAuthonBitbucketCloud-OAuth2.0), with a reasonable set of [scopes](https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html#OAuthonBitbucketCloud-Scopes).

##

**Comment by techtonik** [comment]
+me =/

**Comment by techtonik** [comment]
![badbucket](https://cloud.githubusercontent.com/assets/515889/7333828/b21652a6-eb85-11e4-99dc-7a935ac46775.png)

**Comment by nobodxbodon** [comment]
https://bitbucket.org/site/master/issues/3318 resolved. Now seems better:
![screen shot 2017-01-13 at 10 18 36 pm](https://cloud.githubusercontent.com/assets/392497/21952915/4274362c-d9de-11e6-86d8-e6c77092ae4b.png)

**Comment by nobodxbodon** [comment]
Obviously I overlooked the fact that the permissions are over-broard, as I did some research after receiving another [user feedback](https://github.com/gratipay/gratipay.com/issues/4300).

According to https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html, seems we only need Account permission? Shall we adjust this ASAP, as it seems to be a quick config change?

**Comment by whit537** [comment]
Actually, it requires upgrading from their [OAuth 1.0](https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html#OAuthonBitbucketCloud-OAuth1.0) implementation to their [OAuth 2.0](https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html#OAuthonBitbucketCloud-OAuth2.0) implementation. Good to know they have that now! :-)

**Comment by whit537** [comment]
> Obviously I overlooked the fact that the permissions are over-broard

No worries, so did I. 🎉  retracted! :)

**Comment by nobodxbodon** [comment]
Based on the document, it seems not so complex but still some workload to setup OAuth 2.0 consumer? How about the workload on coding on our side? Anything I can help to work this out?

**Comment by whit537** [comment]
We do have an OAuth2 abstraction, which we use for other providers such as GitHub. Ideally this is an hour or two of work.

**Comment by nobodxbodon** [comment]
@whit537 could you give some pointers for any work that I could handle, without sharing your account/password? As it directly impacts user enrollment, IMO it's high priority.

**Comment by whit537** [comment]
Check out `gratipay/elsewhere/bitbucket.py` for the implementation and `gratipay/elsewhere/github.py` for an OAuth2 example.

**Comment by Changaco** [comment]
There's no need to switch to OAuth2, permissions are configurable on Bitbucket. Here's what we ask for Liberapay:

![spectacle h30368](https://cloud.githubusercontent.com/assets/1581590/22173434/20cb4368-dfc3-11e6-9e52-9177b006c761.png)

And here's what I see when I try to connect a Bitbucket account:

![spectacle m30399](https://cloud.githubusercontent.com/assets/1581590/22173446/8b9fa35a-dfc3-11e6-9a1e-6200d906a0e1.png)

**Comment by whit537** [comment]
I've changed our settings. Care to retry, @maxkoryukov?

P.S. For the record, our Bitbucket app is under "Settings > Access Management > OAuth > OAuth consumers" for my personal Bitbucket account.

**Comment by maxkoryukov** [comment]
@whit537 , works great!

I've connected BitBucket already;)

**Comment by whit537** [comment]
Nice! I've downgrade the scope of this ticket again and am closing it.
