### ISSUE TITLE
Make it so that you do no-account widgets

### ISSUE THREAD

**Issue by jeresig** [gratipay/gratipay.com#879]
For example the following should work:

```
<iframe style="border: 0; margin: 0; padding: 0;"
    src="https://www.gittip.com/on/github/jeresig/widget.html"
    width="48pt" height="22pt"></iframe>
```

And the embed would still exist and would link to the correct page (either the user page or the "on *" page letting them know that they don't have an account).
##

**Comment by nobodxbodon** [comment]
Reticketed to widget repo.
