### ISSUE TITLE
automate payday

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#9]
Heroku Scheduler doesn't have a weekly option, only daily. Open a support request with Heroku for this. In the meantime do one of:
- modify the script to work when scheduled daily
- use a cron on a different box than Heroku
- run the script manually

Right now we're running it manually (on my laptop :scream:). We should automate this.
##

**Comment by whit537** [comment]
Closing as stale.

**Comment by rohitpaulk** [comment]
I think the current script (at least the way I run it) could do with a bit of automation. I'm keeping this open and assigning to myself - will try to add stuff here every payday as I try to automate more and more of payday

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
