### ISSUE TITLE
add even more complex image widgets

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#912]
We have a popular ticket for Travis CI-style dynamic PNGs (#21), @emTr0 suggests in private email that we offer even more complex widgets this way:

> I tried to add the Gittip widget to my sidebar but was reminded that Wordpress.com does not allow certain types of code anywhere on their website, including scripts and iframes.
> 
> This gave me an idea I'd like to suggest. I'm a member of the websites Raptr.com and BF3Stats.com. They have a method of offering widgets which are updated and hosted server-side, and then served up as plain html-called images. You can see the widgets in my sidebar on emtr0.com.
>
> I thought this would be a great way for Gittip to have its members embed their widgets on sites that are restrictive on the types of code a user can post. Most sites allow html-called images too. I know I'd definitely use it on my site.

http://raptr.com/badge/emTr0/uc.png
http://g.bf3stats.com/360/qgTpw7hu/emTr0.png

![screen shot 2013-05-02 at 6 24 11 am](https://f.cloud.github.com/assets/134455/453360/77973242-b312-11e2-9ad5-6fc5eb68ebe8.png)

**Comment by mattbk** [comment]
Moved to grtp.co.
