### ISSUE TITLE
properly reflect tips to patrons-no-tips in the UI

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#918]
As of #893, `goal < 0` now means "no tips, please." We should update the UI around tips that were already pledged to patrons-no-tips before they became that:
- In the giving page on your profile you should see a list of those tips, just like you see the list of people you've pledge to but who haven't signed up yet. We don't want surprises when a patron-no-tips all the sudden starts accepting tips.
- The box for patrons-no-tips shouldn't include any pledged tips in the receiving amount shown.
- Stats should be updated as needed.
##

**Comment by nobodxbodon** [comment]
Consider obsolete as I don't think there's a no-tip option now. Please reopen if I'm wrong.
