### ISSUE TITLE
implement our own profile pic feature

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#920]
We have a ticket for Gravatar (#648). Someone on Facebook ([link](https://www.facebook.com/permalink.php?story_fbid=279218905547407&id=229465400522758&comment_id=1239582)) would like to not use Gravatar:

> I haven't researched [Gravatar] much, but I try to stay high & fly low throughout life, if you know what I mean. Something as universal where my picture will be ascribed to every action I commit on the internet kind of scares me I guess ... was just trying to avoid it by uploading a simple jpg. Maybe you could ad this option someday, I know you're busy, but I don't think many people will donate to a pictureless blob, either!
##

**Comment by whit537** [comment]
+1 https://twitter.com/kellyrued/status/582916641924710401

**Comment by mattbk** [comment]
+1 from https://gratipay.freshdesk.com/helpdesk/tickets/5326:

> I don't see an option to change my profile pic on gratipay. It would be useful, wouldn't it? Currently it automatically fetches the profile pic of the latest social media account added, with no option to fetch it back from a previously added account or to upload a pic.

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
