### ISSUE TITLE
Unable to stay logged in to Gratipay.com with multiple devices

### ISSUE THREAD

**Issue by shurcooL** [gratipay/gratipay.com#921]
This isn't a high priority, but I figured I'd log it since I couldn't find an existing issue.

With pretty much any other website with logins like Twitter, GitHub, facebook, etc., I can stay logged in on multiple devices (computers, smartphones, etc.).

This doesn't work on Gittip.com. I have two devices, and whenever I login to Gittip.com on one, it signs me out of the other. Logging back in is as easy as clicking on the "login with..." link once (so no passwords to enter), but until I do that, I see the anonymous version of Gittip.com.

If possible, this should be fixed. For people who check Gittip.com from multiple devices, it can cause confusion if they see the anon version instead of their personalized one.
##

**Comment by whit537** [comment]
Bump in 2016.

**Comment by whit537** [comment]
Closing in light of our decision to [shut down Gratipay](https://gratipay.news/the-end-cbfba8f50981).

Thank you all for a great run, and I'm sorry it didn't work out! 😞  💃
