### ISSUE TITLE
Create a Status display, link to it from error pages

### ISSUE THREAD

**Issue by trinary** [gratipay/gratipay.com#947]
It'd be nice to have a status page that we can link to in our error pages and that we can use to keep people informed in the event of an application outage.

The simplest thing that would work is a static page that we can update ourselves, but there are all kinds of ways to automatically update it from stats gathered on the server, add custom "current status" messages conveniently, etc.

For safety's sake, this should probably exist separate from the main application. If a catastrophic failure occurs, we should still have a way to communicate status.

Things to track:
- Server error rate (5xx status codes) to see application errors
- Successful GET to / from another environment to see infrastructure errors
- mean and 95th percentile request time to see performance issues
##

**Comment by nobodxbodon** [comment]
Seems duplication of https://github.com/gratipay/gratipay.com/issues/4203

**Comment by whit537** [comment]
I'm pretty sure this _is_ a duplicate, but not (it would seem( of #4203.

**Comment by whit537** [comment]
Here it is: https://github.com/gratipay/inside.gratipay.com/issues/790.
