### ISSUE TITLE
show active members and dollar volume per community

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#954]
Right now we show total number of ~~givers~~ members per community. We should show active members and dollar volume to give a better sense of the viability of each. This would also [encourage some friendly competition](https://twitter.com/ncoghlan_dev/status/334488329036902400) (ht @ncoghlan). :-)

This could take the form of reproducing the global stats and charts pages, but per community (ht @pjz, whom I thought had already ticketed this but maybe not?).

**Comment by mattbk** [comment]
Closing until communities (or tags) return.
