### ISSUE TITLE
community page should occasion some kind of communing

### ISSUE THREAD

**Issue by whit537** [gratipay/gratipay.com#967]
From: https://twitter.com/whit537/status/336466917487431680

> Carolyn: Does having one's own homepage make something easier? Facilitate conversation? Gifting? Or? I'm all about it, just gotta know.

> Chad: Right now it helps you see new members + top givers and receivers in a community. How can we make those pages better?

> Carolyn: Hm... maybe if the pages displayed profile statements and uploaded portfolios from all the members? so one could get a quick overview of all the intense awesomeness in a community? Maybe there could also be a space for a brief community tagline or statement of purpose, and perhaps some kind of forum or posting function for members to discuss their projects / fundraising / gifting strategies? In other words, it would be cool if the community page occasioned some kind of communing.

**Comment by mattbk** [comment]
Closed until communities ([or tags](https://github.com/gratipay/gratipay.com/issues/3127)) return.
